### ISSUE TITLE
Inconsistent number of variations

### ISSUE THREAD

**Issue by matjazpotocnik** [processwire/processwire-issues#1000]
The number of image variations is inconsistent. Please check the video: when you hover over the image, the tooltip says 2 variations, when you edit the image (or you are in grid mode) there are 3 variations and when you click on variations link, there are 4 variations. 

![variations](https://user-images.githubusercontent.com/7663992/66945042-a356c980-f04e-11e9-9990-1de85106428c.gif)

I think it would be better to remove this line in InputfieldImage.module in ___renderButtons():

`if($pagefile->webp()->exists()) $variationCount++;`

And while here, how can I remove webp "variation"?

Also, I would expect that thumbs generated in admin (0x260) would have the note "Auto-generated admin thumbnail" and not "API-generated variation". 

Also, I find the text "Original (webp 42%)" and "Original (webp -10%)" somehow unintuitive, maybe it would be better "42% smaller" and "10% larger"?

**Comment by ryancramerdesign** [comment]
Thanks @matjazpotocnik I've pushed a fix for this issue. 

To answer your questions, a webp is not considered a variation, but rather a part of a variation (referred to as an "extra" in the code). When the variation is removed, any extras are also removed. In terms of the admin, the extras are not managed separately from the variation, but are shown for informational purposes so that it's easy to compare size or quality. 

Regarding the admin thumb, it is still considered an API generated variation since that's essentially what it is. It's true more could also also be said about it, but I hadn't intended on going more detailed than that—maybe could down the road sometime if there's a need for it. 

Regarding the savingsPct label, I think I just want to keep this simple and without language translation since the file sizes are also shown, which also answer the larger/smaller distinction.

**Comment by matjazpotocnik** [comment]
> To answer your questions, a webp is not considered a variation, but rather a part of a variation (referred to as an "extra" in the code). When the variation is removed, any extras are also removed. In terms of the admin, the extras are not managed separately from the variation, but are shown for informational purposes so that it's easy to compare size or quality.

Ryan, I know how webp is considered, that's why I put the variation word in an apostrophe (I'm still struggling with word extra). And I also understand that webp will be deleted when you delete a variation. But if you delete a variation then you lose all the data with that variation. And the same applies for original: if you want to delete webp (because, for example, I changed $config->webpOptions quality settings), then I have to delete the original. Is it OK in such a situation (I guess it's not something that will happen regularly), to delete webp file from the /site/assests/files/1234 folder directly?

> Regarding the admin thumb, it is still considered an API generated variation since that's essentially what it is. It's true more could also also be said about it, but I hadn't intended on going more detailed than that—maybe could down the road sometime if there's a need for it.

Thanks for the explanation. I'm asking this because there are these lines in ProcessPageImageSelect.module that make me think about that:

```
if(!count($notes) && $info['width'] == $adminThumbOptions['width'] && $info['height'] == $adminThumbOptions['height']) {
    $notes[] = $this->_x('Auto-generated admin thumbnail', 'notes'); 
}
if(!count($notes)) $notes[] = $this->_x('API-generated variation', 'notes');
```
Thank you for the fix!
