### ISSUE TITLE
FieldtypeOptions getOptions method returns options in default language

### ISSUE THREAD

**Issue by esl51** [processwire/processwire-issues#1004]
### Short description of the issue

FieldtypeOptions getOptions method returns options in default language. Need to specify `title{$user->language}` when rendering to get current language titles.

### Expected behavior

FieldtypeOptions getOptions method must return options in user language. `title` must return ttile in user language, not in default language, I think.

### Steps to reproduce the issue

1. Create field `country` of type `Options`
2. Add some options in all app langauges
3. Try to render field options when user language is not default:
```php
$countries = $fieldtypes->get('FieldtypeOptions')->getOptions('country');
foreach ($countries as $country) {
    echo $country->title . '<br>';
}
```
This "hack" works as expected:
```php
$countries = $fieldtypes->get('FieldtypeOptions')->getOptions('country');
$titleField = $user->language->name == 'default' ? 'title' : "title{$user->language}";
foreach ($countries as $country) {
    echo $country->{$titleField} . '<br>';
}
```

### Setup/Environment

* ProcessWire version: 3.0.142

**Comment by ryancramerdesign** [comment]
@esl51 Your code example is retrieving options independently of a Page object, so there will be no output formatting involved here. Thus the properties of the SelectableOption will be exactly as they are stored. While what you are doing to get the other language values is certainly fine, you may instead want to use `getTitle()` rather than `title`, which will perform that conversion for you, returning the title in the current user language:
~~~~~
echo $country->getTitle();
~~~~~
Or you can turn on output formatting for the options before your foreach(), and then your properties will be specific to the current language: 
~~~~~
$countries->of(true); 
~~~~~
Now usually you get options from a field on a Page, and so the above will happen automatically, consistent with the Page's output formatting state (which is always on by default on the front-end). But since you are working with options independently of a Page, you are getting a value in its unformatted state (a state where it can still be manipulated), so you'll want to do one of the above.

**Comment by esl51** [comment]
Thank you, Ryan!

Used this variant:
```php
$countries->of(true); 
```
