### ISSUE TITLE
PageArray returned by $page->parents() has wrong keys if you use selectors

### ISSUE THREAD

**Issue by stefan-scholl** [processwire/processwire-issues#102]
### Short description of the issue

I wanted to access the second page returned from `$page->parents("template!=home")` but got the first one. Methods `first()` and `last()` worked as expected but I couldn't use `[$x]` or `get($x)` with an index.

Looking at the output of `getKeys()` showed keys starting from the number `1`.

Calling `$page->parents()` (without selector) returns a PageArray with the first key being `0` as expected.

### Expected behavior
Given: `$parents = $page->parents("template!=home")`

Expected: Index keys starting with `0`.

`$parents->first()`,  `$parents->get(0)`, and `$parents[0]` returning the same page.

### Actual behavior

Index keys starting with `1`.

`$parents[0]` is `false`

### Suggestion for a possible fix

Changes to this behavior could break old code that is aware of this. Explain it in documentation.

### Steps to reproduce the issue

1. Page not being the homepage.
2. $parents = $page->parents("template!=home")
3. Debug outpu: $parents->getKeys()

### Setup/Environment
* ProcessWire version: 3.0.42
* PHP version: 5.5.9 (Ubuntu 14.04 LTS)

**Comment by LostKobrakai** [comment]
Did you try `->eq(1)`, which is the method you're actually supposed to use in that case.

**Comment by stefan-scholl** [comment]
Yes, `eq()` works. Thanks!

One of the jQuery idiosyncrasies that bothered me a lot. The name has nothing to do with its function. Completely different from the `EQ` function in ANSI Common Lisp or the `Eq` type class in Haskell.

And the documentation to `WireArray::get($key)` says: 

> Key of item to retrieve. If not specified, **0 is assumed (for first item)**.

**Comment by ryancramerdesign** [comment]
The WireArray keys really don't mean anything significant and they are subject to change when operations are run on it (like being filtered by a selector). A WireArray key is not necessarily reflective of its position. Since you passed a selector to the `parents()` method, it removed pages (and their associated keys) that didn't match the selector. In order to rely on a specific position, you'd have to use one of the position methods like `eq()`, `slice()` or `index()`. Another option would be to call the `getValues()` method which returns a regular PHP array that is indexed starting from 0 (consistent with PHP's `array_values()` method). 

>  If not specified, 0 is assumed (for first item).

This isn't correct because $key is a required argument, so nothing is assumed. I think maybe we had the argument as optional at one point, duplicating the first() behavior. I will remove that, thanks.
