### ISSUE TITLE
PHP breaks WEBP

### ISSUE THREAD

**Issue by germankirichenko** [processwire/processwire-issues#1022]
### Short description of the issue
When you generate WEBP via $image->webp (IMagick Image Sizer enabled), files are created, but they are not valid. Accordingly, they do not open in the browser. These files look quite functional, but are not displayed. I can’t understand what kind of images can go bad during generation.

### Expected behavior
Images should always be generated and displayed.

### Optional: Suggestion for a possible fix
I took one image, generated it in the same formats to get a working webp and a broken one. Google Chrome in the console displayed loading webp images, but did not display it. I downloaded both files. Comparing the files that I discovered a size mismatch for the generated WEBP files. File sizes differed by only 1 byte.
[screenshot](https://yadi.sk/d/4pGZHX49p-KIPA).

With the help of the HEX editor I looked at what was missing there. It turned out that during the generation of PHP does not append 1 byte to the end of the file, the file is not valid and Chrome can not display it.

[Working file](http://jcup.ru/files/php/chinim-generaciyu-webp-v-php/jcup-gen.webp);
[Broken file](http://jcup.ru/files/php/chinim-generaciyu-webp-v-php/jcup-ru.webp);

Having studied the structure of WEBP a bit, I came to the conclusion that all live files always end with byte x00, in addition WEBP continues to work fine if you add any number of x00 to the end. You can check it yourself, everything works fine.

```//x00 webp generation fix
$image = $page->images->first();
$resized = $image->size(1600, 960);
$webp = $resized->webp->url;
$file = fopen($webp, "a+");
fwrite($file, chr(0x00));
fclose($file);

**Comment by ryancramerdesign** [comment]
@germankirichenko I can't seem to duplicate the issue here. I'm also using IMagick image sizer for webp generation, but not seeing any issues with the output of the resulting webp files. Is it possible you've got a version of ImageMagick that has some bug in it? Also double check that it is IMagick that's creating the webp files by adding this to your /site/templates/admin.php file and then viewing any page in the admin (remember to remove it afterwards):
~~~~~
$s = new ImageSizer();
$s->message($s->getEngineInfo());  
~~~~~
If it's IMagick that's generating your webp files, then you'll see it in the "targets" list for IMagick. A lot of IMagick installs don't support webp, so if that's the case in your installation, you'll see webp in the list of targets for GD instead. I mention GD just because the issue you describe sounds a lot like one that was appearing in some versions of PHP's libgd imagewebp() function: https://bugs.php.net/bug.php?id=66590

**Comment by germankirichenko** [comment]
@ryancramerdesign you're right. On my hosting PHP 7.2 and ImageMagick 3.4.3 (6.7.7-10 2018-09-28). This version IM not supported webp format.. Do I understand correctly that if ImageMagick is enabled but does not support the format, will the GD library be used? Does the bug fire when using GD?

Having written in support and received an answer that they install only proven and compatible software. Convincing them to update the IMagick module failed. Can this problem be solved using the GD library until the module is updated? I don’t really want to change the hosting.

**Comment by ryancramerdesign** [comment]
@germankirichenko Whether using IMagick or GD to create WebP images, the result is similar, which is to say they both do a good job. In your case, it's using GD, which is just fine. (I use both GD and IMagick for WebP and am happy with both). But it sounds like one of the external libraries used by PHP/GD (libwebp I think) is an older version that might have this bug in it linked above. So as far as I understand the issue, it could be fixed by the admin of the server adding WebP support to their ImageMagick version, or by upgrading the libwebp version (or whatever is used by GD) to one without the issue.

**Comment by matjazpotocnik** [comment]
@germankirichenko maybe you could force GD engine? Not sure I've got parameters right or if that would help, just an idea...
```
$config->imageSizerOptions = array_merge($config->imageSizerOptions, array(
	'forceEngine' => 'ImageSizerEngineGD'
)); 
```
@ryancramerdesign when I use 
```
$s = new ImageSizer();
bd($s->getEngineInfo()); 
```
I get an exception:

![image](https://user-images.githubusercontent.com/7663992/68498928-52ef1800-0258-11ea-831d-24dd80f433e4.png)

I don't understand why an exception is not caught in try/catch

**Comment by ryancramerdesign** [comment]
@matjazpotocnik He doesn't need to force the GD engine because it's already using it. The ImageSizerEngines automatically select whichever engine has support for the format. In his case, ImageMagick doesn't have support but GD does (though sounds like the GD has a buggy libwebp). I'm not sure why you are getting an Exception there but it shows that it's getting thrown when creating a new IMagick instances, so likely you've got the module installed on an installation that doesn't support IMagick. Either that, or something's not right with the IMagick since it's throwing an Exception when attempting to instantiate it.

**Comment by matjazpotocnik** [comment]
@ryancramerdesign Thanks for pointing me in the right direction! It was indeed a problem with IMagick failing after a PHP upgrade. 

@germankirichenko how do you feel about closing this issue since it looks like a problem with your local environment?

**Comment by germankirichenko** [comment]
@ryancramerdesign thank you!
@matjazpotocnik yes, I close this issue. Bug in libwebp on my hosting.. On local work fine..
