### ISSUE TITLE
Repeater Issue with API

### ISSUE THREAD

**Issue by Valduc** [processwire/processwire-issues#1031]
### Short description of the issue

When using the API to delete pages and then adding new pages with repeater fields, then Processwire gets stuck with an error:
"Can't save page 0: /1473421482-73-1/: It has no parent assigned"

### Expected behavior

It should be possible to delete all pages (that have repeaters) and then add new pages (that have repeaters).  

### Actual behavior

If there are no pages to delete, then it is possible to add pages (that have repeaters) with the API.
But if I delete all pages and I try to add new pages (that have repeaters), then Processwire gets stuck, only one page will be added, but without the repeater data.

### Optional: Screenshots/Links that demonstrate the issue

See also:
https://processwire.com/talk/topic/14208-repeater-issue/

### Setup/Environment

* ProcessWire version: since 2016, until 2019

**Comment by ryancramerdesign** [comment]
@Valduc Thanks, I have pushed a fix for this issue. I wasn't able to duplicate it at first, but then tried doing the delete+create actions back-to-back in the same http request, and then was able to duplicate and fix it. Since we're not working off of shared example code that demonstrates the issue, can you confirm it also fixes it there?

**Comment by Valduc** [comment]
I can confirm that the issue is solved.
Thank you, Ryan!
