### ISSUE TITLE
InputfieldPage does not display page titles properly with < within the title

### ISSUE THREAD

**Issue by cb2004** [processwire/processwire-issues#104]
### Short description of the issue

As title

### Expected behavior

I have a page field which selects pages from a categories section, one of the categories has the title Tractors <27hp which should display in the inputfield

### Actual behavior

The title actually displays as Tractors with nothing after that. There is a category called Tractors >27hp which displays properly

### Optional: Screenshots/Links that demonstrate the issue

Your screenshots/links go here.

### Optional: Suggestion for a possible fix

Your possible fix goes here.

### Steps to reproduce the issue

1. Step 1
2. Step 2
3. Step 3

### Setup/Environment

* ProcessWire version: 3.0.42
* (Optional) PHP version: 
* (Optional) MySQL version: 
* (Optional) Any 3rd party modules that are installed and could be related to the issue:

**Comment by LostKobrakai** [comment]
Which inputfield type are you using to display those pages?

**Comment by ryancramerdesign** [comment]
Also check your "Textformatters" for that title field and make sure that "Entity encoder" is selected.

**Comment by cb2004** [comment]
@LostKobrakai this happens with any inputfield.

@ryancramerdesign "Entity encoder is selected".

Here are some screens to help.
![pages](https://cloud.githubusercontent.com/assets/6205980/20807317/5c321e3a-b7f6-11e6-9c89-7d92d7fa1be6.gif)
![asm](https://cloud.githubusercontent.com/assets/6205980/20807326/60473bb8-b7f6-11e6-8d38-29724ece94af.gif)
![selectmultiple](https://cloud.githubusercontent.com/assets/6205980/20807337/67b56974-b7f6-11e6-9bd8-2869cac2d5f9.gif)

**Comment by ryancramerdesign** [comment]
Thanks for the screenshots. I was able to duplicate it with `<27hp` but not with `< 27hp` (with the space). As part of the sanitization for preparation of putting items in options, it runs through a PHP `strip_tags()` function and that is what strips the `<27hp`. The strip_tags is there as a safety and beautification measure for page labels, so I don't think we can remove it. If it's possible to change your page titles to have the space between the "<" and "hp" I think that would be the best route, so that it can't be confused as a markup tag that gets stripped.

**Comment by ryancramerdesign** [comment]
I'll close this one since it's just a sanitizer doing its job, and adjusting it is potentially going to cause more problems than it would solve. But if it comes up repeatedly we'll look to see what else might be possible.

**Comment by matjazpotocnik** [comment]
This is now (PW 3.0.244) fixed https://github.com/processwire/processwire/commit/fa47338eede1c7e822ef0e938ef8214aca4f5f3f
