### ISSUE TITLE
$user->language->title is not a string on homepage when logged in

### ISSUE THREAD

**Issue by Valduc** [processwire/processwire-issues#1049]
### Short description of the issue

$user->language->title is not a string on the homepage when logged in.

### Expected behavior

$user->language->title should be a string on every page.

### Actual behavior (edit: when using _init.php)

EDIT: I use _init.php and store to a variable: $LANG = $user->language->title;

When not logged in, $LANG is a string on every page.
But when a user is logged in, the $LANG is a string on every page, but not on the homepage.  On the homepage $LANG then becomes an object.

### Link that demonstrate the issue

[https://processwire.com/talk/topic/22738-strange-behavior-with-uppercase-and-lowercase-on-home-template/](url)

### Suggestion for a possible fix

$user->language->title should always be a string ?

### Setup/Environment

ProcessWire version I have tested with: 3.0.140+146
PHP version: 7.2

**Comment by ryancramerdesign** [comment]
@Valduc If you have a multi-language field value with output formatting off then it is an object from which you can ask for any language from it. If you typecast it as a string, then it'll return the value in whatever the current language is, i.e. `$value = (string) $user->language->title;`. But I wouldn't suggest doing any of this from _init.php because no API variables are guaranteed at that point, and any that are will be in an unformatted state. The ready state is when API variables (like $page and $user and any others) are ready to use for this kind of stuff.
