### ISSUE TITLE
PagePathHistory (Core): Redirection with pagination ends in 404

### ISSUE THREAD

**Issue by FlipZoomMedia** [processwire/processwire-issues#105]
### Short description of the issue

If I change the path of a page that has an activated pagination, old links with pagination are not correctly redirected. With pagination appears a 404.

Example:

Old Path: /test/ (Has pagination, e.g. /test/site-2/)
New Path: /demo/

Now call the following page: /test/ (redirects to /demo/, correct), now call /test/site-2/ (ends in a 404 error, but should actually forward to /demo/site-2/).

### Expected behavior

Redirection with pagination.

### Actual behavior

If pagination exists, it ends in a 404 error.

### Setup/Environment

* ProcessWire version: 3.0.42
* (Optional) PHP version: 7.0.12
* (Optional) MySQL version: 5.5.53-MariaDB

**Comment by ryancramerdesign** [comment]
PagePathHistory is focused on actual page URLs as they exist in the database, not URLs involving user input. It doesn't perform redirects that involve dynamic user input whether that be from query strings, URL segments or page numbers. When you are dealing with redirects that involve user input, you've really got to stick to your .htaccess file for these. However, pagination may be one case that would be possible to support since the pagination prefix is predefined and consistently ends with a number. Though if we add this as a feature in the future, I'd think it should redirect to the non-paginated/main page, since there's a good chance the contents of a pagination from the past is not going to be the same as a pagination from the future. Or a pagination may no longer exist.

**Comment by netcarver** [comment]
@FlipZoomMedia Hello David. It looks like this issue has been open a long time & Ryan's marked this as not being a bug. I don't know if you read the reply or not, perhaps it resolved things for you. Anyway, can you let us know if you want to continue the discussion or, if not, can this issue be closed?
