### ISSUE TITLE
$input->cookie issues

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1053]
### Short description of the issue

I've been working with the relatively new `$input->cookie` and want to raise a few issues:

1\. The online documentation for `$input->cookie` is pretty minimal: https://processwire.com/api/ref/wire-input/cookie/
It would be useful if the PhpDoc comments from the `WireInputDataCookie` class were included or linked to on this documentation page. I couldn't find documentation for this class anywhere in the online docs.

2\. `$input->cookie` doesn't seem to be able to write to or remove cookies set by Javascript. 

I'm using [js-cookie](https://github.com/js-cookie/js-cookie) which I believe is one of the most widely used cookie libraries.

If I set a cookie via the js-cookie API...

```js
Cookies.set('colour', 'blue');
```

...then it *looks like* I can write to and remove this cookie...
![2019-12-17_141232](https://user-images.githubusercontent.com/1538852/70955952-61421680-20d7-11ea-9c77-15557fd22a2f.png)
![2019-12-17_141253](https://user-images.githubusercontent.com/1538852/70955955-63a47080-20d7-11ea-907c-57c7b9dd510e.png)

...but on the next page load the "colour" cookie exists and the value is "blue".

3\. For some reason, the cookie domain set by $input->cookie has a leading dot, unlike the other cookies set by PW and js-cookie. Not sure if this is related to issue 2.
![2019-12-17_141615](https://user-images.githubusercontent.com/1538852/70956170-1379de00-20d8-11ea-8103-971dcccedefa.png)
![2019-12-17_141639](https://user-images.githubusercontent.com/1538852/70956175-170d6500-20d8-11ea-995b-7bc34a828ace.png)

### Setup/Environment

* ProcessWire version: 3.0.144

**Comment by ryancramerdesign** [comment]
@Toutouwai The leading dot on a hostname is required by some older browsers, and it indicates that the cookie should be available to all subdomains of the domain (same as just domain). Though I'm not seeing the leading dot added in my case (and don't see that we've got code that does that), so it might be something PHP does, depending on the value of the setcookie domain argument. In any case, I think the leading dot is probably okay since it's something that it sounds like has a legacy/fallback purpose.

I don't have experience with js-cookie so don't know if there's any factors related to that. I've always used the jQuery cookie plugin that's included with PW in /wire/modules/Jquery/JqueryCore/jquery.cookie.js. 

I'd suggest is copying the value for `$config->cookieOptions` from /wire/config.php to your /site/config.php and make adjustments to the settings there, as I think some of these settings need to be in alignment between JS and PHP in order for the same cookies to be readable to both. Though let me know if you still can't get it to work.

**Comment by Toutouwai** [comment]
> I don't have experience with js-cookie so don't know if there's any factors related to that.

js-cookie is a continuation of jquery-cookie by the same author. Also, I get the same problems if I use the old jquery-cookie plugin.

js-cookie and jquery-cookie do not require a domain to be supplied, and the default is that no domain is used - if you don't supply a domain you get the current domain without a leading dot. PHP's `setcookie()` works the same - if you don't supply a domain parameter then you get the current domain without a leading dot. For both js-cookie/jquery-cookie and `setcookie()` if you do supply a domain you get that domain with the leading dot.

So a cookie set with a domain is a different cookie to a cookie of the same name set without a domain.

The issue seems to be that PW is always supplying a domain to `setcookie()` regardless of what is set for 'domain' in `$config->cookieOptions`. If I dump $domain immediately before it is supplied to `setcookie()` [here](https://github.com/processwire/processwire/blob/dev/wire/core/WireInputDataCookie.php#L277) then it is the same if `$config->cookieOptions` 'domain' is `null` or `true`. I think if config setting for domain is `null` then `null` should be supplied to `setcookie()`. Then the `$input->cookie` defaults will be compatible with the JS cookie library defaults out-of-the-box.

**Comment by ryancramerdesign** [comment]
@Toutouwai As far as I can tell, PHP’s setcookie() does not consider NULL to be a valid value for the the $domain argument. Do you mean instead to set it as a blank string? (which does seem to be valid). The PHP docs state that blank string is the default value for the domain argument, though it never says what that implies...

In our docs for `$config->cookieOptions` we state to use "null for current hostname", which is what it does, putting in the `$config->httpHost` value for the domain argument. That's also the default value in cookieOptions. If you try changing your setting to be a blank string, i.e. `$config->cookieOptions['domain'] = '';` I think that might provide what you are looking for? (and maybe it would be a better default?). Or do you find that setcookie() literally requires a NULL for the domain argument? If so, that would be an undocumented behavior of PHP's setcookie() function, so not sure we'd want to rely on that. But if a blank string does it, that might be a good default for us to use instead of the current hostname substitute.

**Comment by Toutouwai** [comment]
Sorry, the default for the setcookie() domain argument is an empty string and not NULL.

With this set in my /site/config.php...

```php
$config->cookieOptions('domain', '');
```

...the cookie is set for the current domain without a leading dot. I'm in favour of this becoming the default so that PW and JS will read and write the same cookie files out-of-the-box without any extra configuration needed.

**Comment by matjazpotocnik** [comment]
@Toutouwai does Ryan's fix work for you?
