### ISSUE TITLE
Checking for .htaccess

### ISSUE THREAD

**Issue by matjazpotocnik** [processwire/processwire-issues#1059]
After upgrade from PW 3.0.104 to the latest dev, I get this error:

> SystemUpdaterChecks: Unable to locate required file: D:/www/.htaccess

I'm using IIS, not apache, and IIS has no .htacces file. Instead, you should check for "web.config" file or perhaps skip this check on the non-apache server?

**Comment by ryancramerdesign** [comment]
Thanks @matjazpotocnik I've pushed an update that will suppress this error, as it doesn't seem necessary since SystemUpdateChecks couldn't run if there wasn't an .htaccess or equivalent present. Note though that ProcessWire doesn't officially support IIS, so it might still be a good idea to keep an .htaccess file there just so you'll still get notified when PW detects something needs to change, which would indicate the equivalent would need to change in your web.config file.
