### ISSUE TITLE
Inputfield toggle default value not considered

### ISSUE THREAD

**Issue by NilsWiere** [processwire/processwire-issues#1060]
### Short description of the issue

When choosing a default selected options for the Inputfield Toggle, the chosen value is correctly highlighted in the admin UI, but but not considered set when using selectors in the code.

### Expected behavior

When choosing a default selected option of Yes (=1), I expect all newly created pages containing that field to be populated with the default value and to be able to find those pages via selectors.

### Actual behavior

When choosing a default selected option of Yes (=1), I get zero results when using a selector and searching for pages with a toggle field value of 1.

### Steps to reproduce the issue

1. Create Toggle (Yes/No) field (eg "toggle_test")
2. Choose integer option in the Details tab
3. Choose default selected option "Yes" within the Input tab
4. Add the field to a template that is assigned to multiple existing pages
5. Search for pages which have a default value of 1, eg $pages->find("toggle_test=1");
6. There won't be any results so edit a page with the toggle_test field, choose "No", hit save, choose "Yes, hit save again
7. Now that single page will pop up when searching for pages with toggle_test=1

### Setup/Environment
* ProcessWire version: 3.0.148

**Comment by Toutouwai** [comment]
I think you might be overlooking the difference between an _Inputfield_ and a _Field_.

An Inputfield is a UI element in the PW admin. It's the interface through which a user enters data when they edit a page. An Inputfield isn't responsible for storing data in the database - that's the job of a Field, via its Fieldtype.

There is InputfieldToggle and FieldtypeToggle. The "Default selected option" is a feature of InputfieldToggle - you can tell this because it is configured on the Input tab (belongs to the inputfield) and not on the Details tab (belongs to the fieldtype).

So when you set a default selected option this means that any time the toggle inputfield is viewed in the PW admin and the corresponding field does not have an existing value it will show the default option selected in the inputfield. No more, no less - this setting doesn't do anything to the field values in the database for existing pages. For a default inputfield value to get saved as a field value you have to open Page Edit in the admin (so the inputfield comes into play) and save the page.

If you need to set a value to multiple existing pages and don't want to do it via the admin UI you can use the API to loop over the pages and set the value.

**Comment by NilsWiere** [comment]
@Toutouwai Thanks for clarifying this. 

What still is a little confusing to me: When I edit an existing page with the newly added toggle inputfield – which per default highlights "Yes" – and hit save, the value is still is not saved to the database. I have to choose another option, hit save and switch back to the desired option to make it work. Also, initially the UI doesn't reflect, whether a value is set or not. Or did I miss anything here? 

On the other side, the default option works, when adding new pages.

By the way: How would I use the API to change a value for multiple existing pages at once? Would I use the set() method and call it via the frontend once?

**Comment by Toutouwai** [comment]
> What still is a little confusing to me: When I edit an existing page with the newly added toggle inputfield – which per default highlights "Yes" – and hit save, the value is still is not saved to the database.

I can confirm that problem. It doesn't seem right that the selected value is not saved to existing pages. I think that on existing pages the default value is not being correctly detected as a changed value different than the existing value (which is no value at all) and is getting skipped because of this.

> How would I use the API to change a value for multiple existing pages at once?

I find that the easiest way to make bulk changes to pages is via the Tracy console: https://adrianbj.github.io/TracyDebugger/#/debug-bar?id=console

But another way is to put your API code into a template file and then load a page using that template once.

```php
// Find your existing pages that you want to apply the default value to
$items = $pages->find("template=your_template");
// Loop over the pages and set the toggle field value
foreach($items as $item) {
    $item->setAndSave('your_toggle_field', 1);
}
```

**Comment by ryancramerdesign** [comment]
@NilsWiere @Toutouwai You are right, it was not saving to the DB properly when a default value was selected. I have corrected the issue. Thanks.
