### ISSUE TITLE
$config->fileContentTypes not using up-to-date MIME types

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1065]
### Short description of the issue

Currently `$config->fileContentTypes` is:

```php
$config->fileContentTypes = array(
	'?' => '+application/octet-stream',
	'pdf' => '+application/pdf',
	'doc' => '+application/msword',
	'docx' => '+application/msword',
	'xls' => '+application/excel',
	'xlsx' => '+application/excel',
	'rtf' => '+application/rtf',
	'gif' => 'image/gif',
	'jpg' => 'image/jpeg',
	'jpeg' => 'image/jpeg',
	'png' => 'image/x-png',
	'svg' => 'image/svg+xml',
	'webp' => 'image/webp'
	);
```

But these MIME types seem to be out of date when compared with the list here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Complete_list_of_MIME_types

Specifically "image/x-png" and the items that start "+application". I discovered this when I attempted to use `$config->fileContentTypes` to map MIME types to file extensions in a module.

### Optional: Suggestion for a possible fix

```php
$config->fileContentTypes = array(
	'?' => 'application/octet-stream',
	'pdf' => 'application/pdf',
	'doc' => 'application/msword',
	'docx' => 'application/msword',
	'xls' => 'application/excel',
	'xlsx' => 'application/excel',
	'rtf' => 'application/rtf',
	'gif' => 'image/gif',
	'jpg' => 'image/jpeg',
	'jpeg' => 'image/jpeg',
	'png' => 'image/png',
	'svg' => 'image/svg+xml',
	'webp' => 'image/webp'
	);
```

### Setup/Environment

* ProcessWire version: 3.0.148

**Comment by matjazpotocnik** [comment]
+1

From the config.php: _Any content types that should be force-download should be preceded with a plus sign._ So perhaps that should be considered when checking?

What is the point of having the list so short? Eg. at least zip, rar, gz, gzip, tar, 7z, txt, ppt, pptx, bmp, tiff and possibly other "common" types could be added?

**Comment by Toutouwai** [comment]
> From the config.php: Any content types that should be force-download should be preceded with a plus sign.

Ah, I overlooked that part. I just noticed that when trying to map MIME types to file extensions using this array that the array values didn't correspond to the commonly used MIME types for some of the extensions, but I guess this array was not intended to be used in reverse like this.

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai @matjazpotocnik I've updated the `image/x-png` to be `image/png`. I'm not sure why I had x-png in there but that's definitely out of date. As for other types (zip, gz, gzip, ...) they would fallback to the general octet-stream force download. Just wanted a minimal set for the default config, but of course people can add more in their /site/config.php. 

If it turns out the lack of any particular fileContentTypes is causing issues somewhere (like a ZIP or TXT file that downloads but the computer doesn't recognize it as a ZIP or TXT), then we'd want to add more to the defaults. As far as I know, that's not the case, but don't think I've tried it recently. If either of you have a setup using `$config->pagefileSecure` handy, it might be worth testing just to see if things like zip, txt, tiff run into issues. (otherwise, I can test here soon). When I originally set this up, I seem to recall it was the file extension that dictated what my computer identified the file as and that the content-type was more useful in forcing it to open (i.e. images) vs. download (i.e. everything else).

**Comment by Toutouwai** [comment]
Thanks.

**Comment by matjazpotocnik** [comment]
@ryancramerdesign I would add 'txt' => 'text/plain' to the list. Right now I get:

> Resource interpreted as Document but transferred with MIME type application/octet-stream: "http://localhost/site/assets/files/1283/test.txt".

So, the file is downloaded (at least in Chrome) **and** also displayed in the browser.

With other extensions (zip, rar, xlsx), I also get similar warning in chrome:

> Resource interpreted as Document but transferred with MIME type application/excel: "http://localhost/site/assets/files/1283/ad_grupe.xlsx".

I added $config->pagefileSecure to /site/config.php and then I unpublished the page with id 1283. I hope this is ok for testing?

**Comment by ryancramerdesign** [comment]
@matjazpotocnik Sounds good, I will add the txt extension for text/plain. For the Chrome message that you are getting, I'm wondering if by "Document" it means HTML document, since that's how the browser usually refers to them? I think the issue may be that it's a generic excel mime type and not the more specific actual ones. I don't have MS Office/Excel to test, but the generic one seems to make my computer recognize it as a spreadsheet. Maybe I should switch it to the actual ones which are these (for Excel)?
~~~~
'xlsx' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
'xls' => 'application/vnd.ms-excel',
~~~~
If you still have that test setup, does changing them to these make it work better?

**Comment by matjazpotocnik** [comment]
@ryancramerdesign changing mime-type doesn't help. It looks like this is the Chrome issue, so I wouldn't bother with that anymore. Nevertheless here is the config I'm using:

```
$config->fileContentTypes = array(
	'?' => '+application/octet-stream',
	'pdf' => '+application/pdf',
	'doc' => '+application/msword',
	'docx' => '+application/vnd.openxmlformats-officedocument.wordprocessingml.document',
	'xls' => '+application/vnd.ms-excel',
	'xlsx' => '+application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
	'ppt' => '+application/vnd.ms-powerpoint',
	'pptx' => '+application/vnd.openxmlformats-officedocument.presentationml.presentation',
	'rtf' => '+application/rtf',
	'zip' => '+application/zip',
	'gz' => '+application/gzip',
	'z7' => '+application/x-7z-compressed',
	'rar' => '+application/x-rar-compressed',
	'tar' => '+application/x-tar',
	'txt' => 'text/plain',
	'gif' => 'image/gif',
	'jpg' => 'image/jpeg',
	'jpeg' => 'image/jpeg',
	'png' => 'image/png',
	'svg' => 'image/svg+xml',
	'webp' => 'image/webp',
	);
```

And while we are talking about headers, just a small remark: in several places in WireHttp.php you use headers in lowercase, like `content-type`, but in other core files, you use 'Content-Type'. I know headers are case-insensitive, so this is more cosmetics.

**Comment by ryancramerdesign** [comment]
@matjazpotocnik Thanks for testing. Now you've got me curious what it is that is needed to get it to download and recognize an Excel document without errors. Maybe it doesn't like the force-download option? (since it's likely going to do that anyway)

Btw, while I prefer readability of mixed case headers, WireHttp uses lowercase headers just to ensure that the same header doesn't get used multiple times as a result of case variations, i.e. content-type, Content-Type, Content-type, CONTENT-TYPE, etc. would all represent different indexes in a PHP associative array. By enforcing lowercase that ensures it doesn't end up with (and send out) multiple copies of the same headers.

**Comment by matjazpotocnik** [comment]
@ryancramerdesign I think this is something specific to Chrome as I don't see this warning in FF console. But as I said I wouldn't worry as this happens on all sites, with static HTML files not in any connection to PW. The file is downloaded and saved to disk, despite the warning. In the beginning, I thought that this warning is because of wrong? mime type set by PW, but after googling around I found it has nothing to with PW. I'm very sorry that this escalated so far and that I'm wasting your time, I should double check before writing. Thank you for the explanation about mixed case headers.

**Comment by matjazpotocnik** [comment]
@Toutouwai perhaps you could close this?
