### ISSUE TITLE
Admin search "help" issues

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1066]
### Short description of the issue

When typing "help" into the admin search, the dropdown shows the help info properly, but if the user hits Enter after typing "help" then there are three undefined index notices and the tab labels don't seem to be what is intended.

![2020-01-18_102138](https://user-images.githubusercontent.com/1538852/72647115-9eead580-39dc-11ea-91eb-747d9abc4660.png)

### Setup/Environment

* ProcessWire version: 3.0.149

**Comment by matjazpotocnik** [comment]
Nothing new: https://github.com/processwire/processwire/commit/6013f16c96549bb119d47bcf2061ea4cb19d07b3#comments

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai and @matjazpotocnik I've pushed a fix for this issue. I almost never hit enter in the search box because what I'm looking for always is in the ajax dropdown, and so I sometimes forget the option is even there. :) @matjazpotocnik looks like you reported this earlier and I missed it, sorry about that.

**Comment by matjazpotocnik** [comment]
@ryancramerdesign Yes, I did report it and even tried to fix, but your solution is much more elegant - as always :-) Thank you!

**Comment by Toutouwai** [comment]
Thanks.
