### ISSUE TITLE
page()->children('start=2, limit=1');  doesn't work as expected

### ISSUE THREAD

**Issue by rafaoski** [processwire/processwire-issues#1068]
### Short description of the issue

When I set start and limit in methods like get(), or find(), pagination and displaying posts do not display the correct paging results, although the url address segment page1, page2 etc. is suitable.

### Expected behavior
Pagination and displaying posts should start from the second position (start = 2).

### Optional: Screenshots/Links that demonstrate the issue
![blog-pagination](https://user-images.githubusercontent.com/12895367/72688838-862d0d80-3b0b-11ea-9f6e-e11c9ce9b123.gif)

### Setup/Environment

<strong>Server Details</strong>

|Software|Version|
|------:|:-------|
|ProcessWire|3.0.149|
|PHP|7.2.11|
|Webserver|Apache/2.4.35 (Win64) OpenSSL/1.1.0i |
|MySQL|5.7.24|
<details><summary><strong>Server Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|allow_url_fopen|1|
|max_execution_time|36000 (changeable)|
|max_input_nesting_level|64|
|max_input_time|60|
|max_input_vars|1000|
|memory_limit|512M|
|post_max_size|2G|
|upload_max_filesize|2G|
|xdebug||
|xdebug.max_nesting_level||
|mod_rewrite|1|
|mod_security|*confirmed off|
|EXIF Support||
|FreeType|1|
</details><details><summary><strong>GD Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|Version|bundled (2.1.0 compatible)|
|GIF|1|
|JPG|1|
|PNG|1|
|WebP|1|
</details><details><summary><strong>Module Details</strong></summary>

|Module ClassName|Version|
|------:|:-------|
|ProcessTracyAdminer|1.0.6|
|TracyDebugger|4.20.1|
</details>

**Comment by ryancramerdesign** [comment]
@rafaoski You may already know this, but just in case: When using pagination, you need to enable the Page Numbers setting for the template where you are using pagination. This can be found in Setup > Templates > [your template] > URLs (tab). Chances are you've already got that, but since it's a pre-requisite, I just wanted to mention it. 

When pagination is in use, and a selector has a "limit=n" in it, ProcessWire automatically sets the "start=n" part of any `$pages->find()` selector (or any other API method that uses it, like `$page->children`) so that the start always corresponds to the current pagination. So you don't need to (and shouldn't) specify your own "start=n" in the selector, unless you want to prevent pagination or are managing pagination completely on your own, and not using PW's pagination.

The only use case I can think of where you'd want to override pagination is when using "limit=n, start=0" selector (where you are forcing the start to be 0). When you are using pagination, but want to have a particular set of pages NOT paginate (like nav in a sidebar) then it's useful to put a "start=0" in your selector, because it will prevent that particular set of pages from paginating. Other than that use case, I don't think you'd want to use a "start=n" in a selector, unless managing pagination on your own, like you might do in web service output or something.

**Comment by rafaoski** [comment]
Thanks @ryancramerdesign for the quick reply ... 
I just wanted to exclude the initial pages of the blog to get the first few results from the blog in the first loop (a different grid view than the basic blog view) without pagination and then get the rest with pagination, I thought this way could be the easiest ... I know there are other ways but I wasn't sure about this case ...

Something like this:

```
<?php
// Blog Hero
$blogHero = page()->children("start=0, limit=6");
echo "<div class='grid'>";
foreach ($blogHero as $key => $item) {
	echo $item->title;
}
echo "</div>";

// Blog Posts
$blogPosts = page()->children("start=7, limit=12");

echo pagination($blogPosts);

echo "<div class='blog'>";
	foreach ($blogPosts as $item) {
		echo $item->title;
	}
echo "</div>";

echo pagination($blogPosts);
```
Thanks again for the clarification.
