### ISSUE TITLE
Hooks on classes with a namespace that extend `Wire` not working

### ISSUE THREAD

**Issue by owzim** [processwire/processwire-issues#109]
### Short description of the issue

Hooks on classes with a namespace that extend `Wire` are not working.

### Expected behavior

```php
$wire->addHookAfter('Foo\Bar::baz', null, function($e) {
    $e->return = 'qux from hook';
});

$bar = new \Foo\Bar();

// should return 'qux from hook'
$bar->baz();
```

### Actual behavior

Hooked method does not work, the original method value is returned. Tested with a class without namespaces, works there.

Note: `$wire->addHookAfter('\Foo\Bar::baz', null, function)` with leading backslash is not working neither.

### Screenshots/Links that demonstrate the issue

![screen shot 2016-12-04 at 21 31 03](https://cloud.githubusercontent.com/assets/1720088/20868977/fee3b14c-ba68-11e6-9b70-f7c8352f4b6f.png)

### Steps to reproduce the issue

1. Step 1

Create `site/templates/ClassWithNameSpace.php` with the following content:

```php
<?php
namespace Foo;
use \ProcessWire\Wire;

class Bar extends Wire
{
    public function ___baz()
    {
        return 'qux';
    }
}
```

2. Step 2

in `admin.php` prepend this code:

```php
include_once __DIR__ . '/ClassWithNameSpace.php';

$bar = new \Foo\Bar();

$wire->addHook('Foo\Bar::baz', null, function($e) {
    $e->return = 'qux from hook';
});

$session->message('$bar->baz(): "' . $bar->baz() . '" should be "qux from hook"');
```

3. Step 3

in `wire\core\WireHooks.php:167` add:

```php
if ($method == 'baz' && $className === 'Foo\Bar') {
    wire('session')->message('$namespace "' . $namespace . '"');

    // results in "Foo\"
    wire('session')->message('$_namespace "' . $_namespace . '"');

    // results in "Foo\Bar"
    wire('session')->message('$className "' . $className . '"');

    // results in "Foo\Foo\Bar"
    wire('session')->message('$_className "' . $_className . '" should be "\Foo\Bar"');
}
```

Since the following statement is not true, the loop will continue and the hook will not get executed:

```php
// $object is instance of "\Foo\Bar", but $_className holds "Foo\Foo\Bar"
if(!$object instanceof $_className && $method !== '*') {
    continue;
}
```

### Setup/Environment

* ProcessWire version: 3.0.42
* PHP version: 5.5.12
* MySQL version: 14.14 Distrib 5.6.17

**Comment by owzim** [comment]
Well this works:

```php
$wire->addHookAfter('Bar::baz', null, function($e) {
    $e->return = 'qux from hook';
});
```
But this false behaviour was not present in <PW3, additionally, what if I have a `Bar` class in different namespaces. I cannot target them separately with hooks.

**Comment by owzim** [comment]
Same goes for `addHook()`:

```php
$wire->addHook('Foo\Bar::someCustomMethod', null, function($e) {
    $e->return = 'someCustomMethod;
});

$bar = new \Foo\Bar();

// should return 'someCustomMethod'
$bar->someCustomMethod();
```

**Comment by LostKobrakai** [comment]
`addHookAfter/Before/Property` are just convenience functions, which ultimately call `addHook` with some predefined options. So that's expected.

**Comment by LostKobrakai** [comment]
Just another thing to clear up. `addHook` does use the classname of `Wire::className()`, which is by default the shortname of the class. You could of course alter this behaviour in your class `Bar`. But I really think using the FQCN should work just as well. Besides for BC for core classes using shortnames should probably be considered bad practice.

**Comment by owzim** [comment]
You think it's the behavior in the initial post is expected? It worked before PW3 and it should work in PW3 as well. I is not expected behavior at all.

BC? Thanks for pointing out the option to overwrite the `className` method. Doing so in `Foo` does nothing in this case, it is not called.

**Comment by LostKobrakai** [comment]
It's called here: https://github.com/processwire/processwire/blob/35df716082b779de0e53a3fcf7996403c49c9f8a/wire/core/WireHooks.php#L265-L300

And yes the behaviour is expected, because otherwise all documentation regarding hooks would need to be updated for 3.0 and I'm not sure how much work it would be to handle hook setups via the FileCompiler. "Pages::saved" just isn't the same as "ProcessWire\Pages::saved" or even "\ProcessWire\Pages::saved". That's why it's a backwards compatibility issue (for core classes). 

But I'm with you that hooking with the FQCN should work just as well as without. In case of name collisions for the short name there's always the option to customise className() as stated above.

**Comment by owzim** [comment]
It is called in `hasHook`, but `hasHook` in not called in the example of the orignal post.

**Comment by ryancramerdesign** [comment]
Hooks are their own namespace, so they aren't meant to be specific to PHP namespaces. You could think of the namespace as being "classes that extend Wire". Take modules for instance, which all exist in the same "modules" namespace regardless of what PHP namespace the module uses (ensuring we don't have overlapping module names). The same goes for hooks, which all exist in "Wire". A hook to `Page::render` should continue working regardless of what class or namespace the class extending `Page` uses. Since hooks were created as a system to hook into PW core classes and modules (core & 3rd party), the hook system is focused on that context. I'm interested in keeping the hooks system as simple to use as possible, so haven't seen the value in adding PHP namespaces to the mix even if we added them to PW3. We've never demonstrated anything like the syntax you are showing as non-working examples as part of our hooks documentation, so I don't consider this a bug since I've never seen that syntax mentioned or used before with hooks. :) Still if there's a strong need for it, it may be possible to support, but this would be more of a feature request. 

What is the scenario you've run into where using the hooks system as it's designed doesn't meet the need? Would it not work just to simply hook the class name (without namespaces in it) or hook the object instance(s) directly? (that would exclude all instances except the one you hooked). Of course, your hook function could always clarify exactly what it wants too: 
~~~~~
if($event->object->className(true) != "Owzim\\Page") return;
~~~~~
We might be able to implement something similar on the core side if there's a strong need for it.

**Comment by owzim** [comment]
Thanks @ryancramerdesign for the insight. I will have to investigate further.

A recent scenario would be [TemplateTwigReplace](https://github.com/marcostoll/processwire-template-twig-replace) hooking into `ChunkRenderer::render` of [TemplateDataProviders](https://github.com/marcostoll/processwire-template-data-providers):

https://github.com/marcostoll/processwire-template-twig-replace/blob/master/TemplateTwigReplace.module#L252

Which worked on PW2x. And this is also the reason why I consider(ed) a bug.

Do you suggest opening a separate feature request then?

**Comment by teppokoivula** [comment]
Hey @owzim, just checking: are you saying that hooking into `nw\ChunkRenderer::render` works in 2.x but not in 3.x, and hooking into `ChunkRenderer::render` works in 3.x but not in 2.x? I'm reading the reply from @ryancramerdesign like the non-namespaced version should work in both cases, but perhaps I'm misinterpreting him.

Either way I would expect there to be a way to hook into namespaced modules in a consistent way.

**Comment by ryancramerdesign** [comment]
I'm not sure why it would have worked in PW2, other than that we just never considered that syntax for adding hooks and perhaps it was just working because PW2 wasn't namespace aware at all. Did you find that just hooking `ChunkRenderer::render` (without the namespace in it) worked how you needed it to?

**Comment by owzim** [comment]
@ryancramerdesign 
> Did you find that just hooking ChunkRenderer::render (without the namespace in it) worked how you needed it to?

Yes, it works this way.

@teppokoivula 
> are you saying that hooking into nw\ChunkRenderer::render works in 2.x but not in 3.x, and hooking into ChunkRenderer::render works in 3.x but not in 2.x?

That's right, I just tested this. And in this case to make it compatible for PW2 and 3, I use both variants, as you see in the [source](https://github.com/marcostoll/processwire-template-twig-replace/blob/master/TemplateTwigReplace.module#L252).

> While it's a bit weird that you'd have to check for the namespace manually in a hook method ...

I also think it's weird and not intuitive as well.

Another thing that worries me:

Say I have a class `owzim\MyApp\Page` (Which I do in an intranet app currently in use) and I add say 20 hooks to it via 

```php
$wire->addHook('Page::foo', null, function($event) { /* ... */ });
```

 and I use the suggested method of checking the namespace in each hook, would that not induce a considerable overhead to any other Page-Class instance (mainly `\ProcessWire\Page` in this case)?

I do not know enough about the internals of the hooking system, but when I was debugging this issue, I logged out, what was happening in the `WireHook::getHooks` method, and I noticed that a lot was happening there, when many wire derived objects where in memory. I assume all wire objects go through all statically added hooks active on run-time.

So all Pages would call the added hooks, although I just cancel them with the suggested namespace check, although these hooks should  not be executed in the first place.

I don't know if I am making sense here.

**Comment by ryancramerdesign** [comment]
> That's right, I just tested this. And in this case to make it compatible for PW2 and 3, I use both variants, as you see in the source.

I wasn't aware that you *had* to do that in PW2 for a namespace'd class. I guess that was an unintentional feature (or drawback in this case), as it wasn't intended. I would guess there's also a good chance it wasn't firing on all cylinders either... like a hook to non-namespace'd class not applying to namespace'd class that extends it. But since it was at least partially working, let me see if there is something more I can do to duplicate the behavior. I'm not sure it's possible yet though (at least not without adding more overhead than we'd like). The hooks system is very fast, in part because it doesn't have to spent a lot of time figuring out what connects with what. I'll definitely look at this closer though.

> and I use the suggested method of checking the namespace in each hook, would that not induce a considerable overhead to any other Page-Class instance (mainly \ProcessWire\Page in this case)?

It doesn't matter. Either PW WireHooks class checks it, or your hook function does, but it's PHP either way. These checks and function calls can be quite fast though. 

>  I assume all wire objects go through all statically added hooks active on run-time.

It keeps a class name index, so that it's only checking added hooks that are potentially applicable. One thing that it does have to do is determine if one class extends another, and thus should still have hooks run (i.e. a hook to Page::something should also hook CustomPage::something). 

> So all Pages would call the added hooks, although I just cancel them with the suggested namespace check, although these hooks should not be executed in the first place.

Does your `owzim\MyApp\Page` extend `ProcessWire\Page`? If so, the intention is that hooks to `Page` should still run, either way. But if your class does not extend it, then it would have to perform that check at present. Though like I said, I'll look into this further to see if something else might be possible.

**Comment by netcarver** [comment]
@owzim Hi Christian, any update on this?

**Comment by netcarver** [comment]
@owzim Please could you update this issue.

**Comment by netcarver** [comment]
Closing as this has gone cold. @owzim If you need to, just post more here and it can be reviewed. Thanks!

**Comment by sebastiandittrich** [comment]
@ryancramerdesign, I just wanted to restart the discussion about namespaced hooks a bit. 

**The Problem**
I am currently developing a relatively large module for Processwire, with a lot of custom admin-pages (aka Processes) Since I want to keep the module files as clean as possible, I have one class for each Admin page, which contains all the logic this page needs. The admin pages are for manipulating resources, such as bookings, customers, and so on. A good method for structuring these classes is the following:
```
MyModule\
    Admin\
        Resource1\
            Create
            Edit
            Delete
        Resource2\
            Create
            Edit
            Delete
```

The Problem with this approach is that when trying to hook those classes, you can only specify the class name, not the namespace of this class.

For example, if I would like to hook the `Resource1\Edit::render` Method (which obviously renders the edit UI of the first resource), I can currently not do this: 
```php
// This hook gets never triggered
$this->addHookAfter('Resource1\\Edit::render', fn() => ...)
```

The only option is to only hook `Edit::render`, which would be triggered for EVERY `{Resource}\Edit::render` call, not only those calls to `Resource1\Edit::render`

Of course, I could flatten the Namespaces and define my classes like so:
```
MyModuleAdminResource1Edit
MyModuleAdminResource2Create
...
```

But in my opinion, this is an unclear and confusing structure and not something I would like to do. Instead, I think it would be very helpful in some situations to optionally specify the parent namespace(s) of the class you would like to hook. 

**A possible Solution**
My proposal is to allow users to optionally specify the last part of the namespace that has to match so that the following two code parts are equal

*Current way*
```php
$this->addHook('Edit::render', function(HookEvent $hook) {
    if(endsWith($hook->object::class, 'Resource1\\Edit'))
    {
        // Your code here
    }
})
```

*With namespaced hooks*
```php
$this->addHook('Resource1\\Edit::render', function() {
    // Your code here
})
```

Using this approach, we could also benefit from code-autocompletion using this syntax: 
```php
$this->addHook(Resource1\Edit::class . '::render', function() {
    // Your code here
})
```

What is your opinion on this problem and solution?

**Comment by teppokoivula** [comment]
Just wanted to mention that support for namespaced hooks would be awesome. I've been running into this issue more and more often lately: thanks to namespaces I can easily prevent clashes at code level without relying on weird and long class names... but I still have to use those for things that might get hooked into. It's kind of a bummer, to say the least.

Would love to see namespaced hooks in the core :)

**Comment by BernhardBaumrock** [comment]
Same here, would be great :)

**Comment by MrSnoozles** [comment]
Have to agree here too. Especially when writing more complex modules it doesn't feel right to have all the files in a single directory in the ProcessWire namespace.

Namespaced hooks would be such a huge win.
