### ISSUE TITLE
Object of class ProcessWire\Config could not be converted to int in /var/www/html/wire/core/WireShutdown.php:308

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1101]
### Short description of the issue

Getting that error when editing a page - not sure when or why. I don't see it all the time, and it was logged while someone else was editing, so not sure the cause, but it's pretty obvious why the error is being thrown:

https://github.com/processwire/processwire/blob/60d62ea3a108f0fb0454d16f358f6f70f3bd6613/wire/core/WireShutdown.php#L308

**Comment by adrianbj** [comment]
Actually, I think it occurred due to a "Fatal Error: Allowed memory size of 268435456 bytes exhausted" error. Not relevant to fixing this obviously, but I think it is a result of the circular reference issue.

**Comment by ryancramerdesign** [comment]
@adrianbj None of that code still remains, as this class was mostly rewritten several months back. Though I think it may have been occurring because the line had a `a=b?c:d` statement that likely needed a parenthesis around it. Since I don't think the error could occur anymore, I'll close this, though if you are still seeing it, please let me know.
