### ISSUE TITLE
Link abstraction feature creates incorrect links when URL segments in use

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1116]
### Short description of the issue

MarkupQA settings on body field:

![2020-03-13_180435](https://user-images.githubusercontent.com/1538852/76591394-1cead900-6555-11ea-92df-e4d32ce0fd70.png)

Page tree:

![2020-03-13_180607](https://user-images.githubusercontent.com/1538852/76591510-75ba7180-6555-11ea-9f4b-d6f55662d8da.png)

Screencast showing link being changed from correct path to incorrect path:

![link-change](https://user-images.githubusercontent.com/1538852/76591705-02fdc600-6556-11ea-9dd4-e59bfc7a04f9.gif)

### Setup/Environment

* ProcessWire version: 3.0.151

**Comment by Toutouwai** [comment]
I've traced this back to `PagesLoader::getByPath()`.

It seems that this method doesn't account for the possibility of URL segments. I think the method needs to return 0/NullPage if any of the parent pages in the path have URL segments enabled.

And specifically with regard to the MarkupQA link abstraction, I'd rather have a "I can't trace this link" response than have links incorrectly modified in way that's difficult to detect.

**Comment by adrianbj** [comment]
This one is making things confusing for my site editors as well.

Just for reference - my closed duplicate issue (https://github.com/processwire/processwire-issues/issues/1137)

**Comment by Toutouwai** [comment]
@ryancramerdesign mentioned in the [latest blog post](https://processwire.com/blog/posts/processwire-updates-and-additions-in-progress/#new-procache-version-with-built-in-crawler):

> The ProCache crawler is unique in that it’s a PW-specific crawler and knows about how PW handles multi-language, pagination and URL segments.

So hopefully these crawler features can soon be leveraged in the core to allow for smarter analysis of URLs/links to account for things like URL segments and page numbers.

**Comment by adrianbj** [comment]
This is a huge problem - it basically makes the link abstraction feature unusable for any site that utilizes urlsegments.

@ryancramerdesign - any chance of prioritizing this please?

> I'd rather have a "I can't trace this link" response than have links incorrectly modified in way that's difficult to detect.

I completely agree with @Toutouwai - having it break my perfectly valid link by converting it to link to the current page is a real problem.

**Comment by adrianbj** [comment]
It even breaks links entered into a Hannacode text field. I was hoping to at least support manual entry of links that way. The proper link with the urlsegment is maintained in the admin, but it's converted on the frontend when rendering the textarea field.

**Comment by adrianbj** [comment]
The only way I seem to be able to insert a link to a url with a urlsegment in it is to go into the DB directly and edit the entry in the `field_body` table to remove the existing `data-pwid=xxxx` tag. Then it will let me link to a urlsegment.

Please @ryancramerdesign - this is really critical functionality that needs to be fixed.

On a related note, if I run the "Apply HTML options now" process, I am seeing these warnings:

```
PHP Warning: Undefined array key "body" in .../wire/core/MarkupQA.php:244
PHP Warning: Undefined array key "internal" in .../wire/core/MarkupQA.php:431
```

**Comment by adrianbj** [comment]
Hi @ryancramerdesign - I am curious if you have any ideas a about how to fix this. This is causing all sorts of frustration on one of the biggest sites I manage because it means that I need to manually adjust links when site editors realize they aren't working.

Just wondering if I need to give up on the link abstraction feature and just leave things up to the Page Path History module to handle redirects. 

Thank you for any input on whether this might actually be fixable or not.

**Comment by ryancramerdesign** [comment]
@Toutouwai So far I can't seem to duplicate this one. I'm using a local copy of the processwire.com site and inserting links to `/api/ref/.../ `or `/modules/module-name/`, all of which are URL segment-based. Link abstraction is turned on and I'm adding the links in the body field using CKEditor.  The links don't get lost or changed after saving. Is there some other condition I need to setup in order to duplicate it? Like, did you have to rename your /membership/ page to /another-page/ first (and just wasn't in the GIF)? 

You mentioned an issue with the getByPath() method. That might be a simpler way to identify the issue. Can you tell me what input you are giving that method and what incorrect output it is giving you as a result?

**Comment by Toutouwai** [comment]
@ryancramerdesign, the key thing is that you need to have a page somewhere in your site that has the same name as the URL segment that you are trying to link to. The page can be miles from the link you are trying to create, which leads to crazy modifications of the link URL like the following...

This...
![2021-08-18_095337](https://user-images.githubusercontent.com/1538852/129806208-e4e38d65-cd28-42ad-8668-e001ceb03c7f.png)
...gets turned into this...
![2021-08-18_095409](https://user-images.githubusercontent.com/1538852/129806236-9dcedef5-10b0-4ef2-bbce-da9af271be00.png)
...without any warning.

![2021-08-18_095638](https://user-images.githubusercontent.com/1538852/129806247-34d77e40-2762-4b5d-9826-599721bcbe12.png)

**Comment by adrianbj** [comment]
Just to confirm what @Toutouwai said.

I get converted from /media-library/symbols/ to /options/blog-tags/symbols/ and of course the <a> tag looks like `data-pwid=1155` where 1155 is equal to the ID of the /options/blog-tags/symbols/ page.

**Comment by ryancramerdesign** [comment]
@Toutouwai @adrianbj Thanks, I was finally able to duplicate it. I had a little trouble at first because I think it's not just the presence of URL segments but a little more, such as a URL segment that maps 1 to 1 with a name of a page that only appears once in the entire site. I think I've got it fixed now, though I didn't see any simple fix for this as I'd either have to drop the partial path matching ability (which might break things that worked before) or add URL segment support to `$pages->getByPath()`. So I upgraded that getByPath() method to support an `allowUrlSegments` option which MarkupQA now uses, and falls back to the previous behavior if a URL segment match couldn't be found or the matching page’s template doesn't support URL segments. This should work going forward for newly abstracted links. It took more code than I'd like, so probably needs a good testing to make sure there's no issues. I've tested it with every CKEditor link the ProcessWire site and so far so good, but since I'd never run into the issue before, I'll feel better after I know it works for you guys too.

**Comment by Toutouwai** [comment]
Awesome, thanks @ryancramerdesign! It's working here for me, and the link updated perfectly when I moved the page that supports the URL segments (the "Membership" page in my example) so that's icing on the cake!

Will close this once @adrianbj confirms.

**Comment by adrianbj** [comment]
Thanks @ryancramerdesign and @Toutouwai - this looks good so far here, so please feel free to close.

**Comment by adrianbj** [comment]
@ryancramerdesign @Toutouwai - unfortunately I don't think this is fully fixed.

I have a setup where affiliates have direct urlsegment links, eg: https://mysite.com/companyname and I also have a page tree of affiliates with child pages with paths like `/affiliates/companyname/`

If a site editor accidentally inserts a link to `/affiliates/companyname/` and then tries to correct this to just `/companyname/` the change keeps being undone by the `data-pwid=xxxx` element on the `a` tag.

A possible contributing factor might be that the `/affiliates/companyname/` pages are also viewable.

**Comment by Toutouwai** [comment]
I can confirm what @adrianbj described, although I don't think it's related to trying to correct an existing link because I get the issue when creating a new link.

The `PagesLoader::getByPath` method [has a section](https://github.com/processwire/processwire/blob/c9fef983bcc9a3eddfe82de9d2ac23ad43237a34/wire/core/PagesLoader.php#L1662-L1691) that is intended to deal with URL segments but this section is not used if an [earlier section](https://github.com/processwire/processwire/blob/c9fef983bcc9a3eddfe82de9d2ac23ad43237a34/wire/core/PagesLoader.php#L1608-L1653) finds a page ID. That earlier section seems to be satisfied if there is an existing page anywhere in the site whose name matches the link, so in Adrian's example it finds the `/affiliates/companyname/` page and therefore never considers if `/companyname/` is a URL segment of the home page.

**Comment by adrianbj** [comment]
Thank you @Toutouwai for diving into the cause of the problem. This really is a major problem because it results in links to affiliates being completely broken.

**Comment by adrianbj** [comment]
@ryancramerdesign - just a reminder that this is definitely not properly fixed yet. I wish we could edit tags here, like being able to remove the "status: fixed-please confirm" so it's more clear to you that this is still an issue, rather than just not closed yet.

**Comment by adrianbj** [comment]
Thanks @matjazpotocnik for remove the fixed tag. 

@ryancramerdesign - this is still causing broken links on my site. Is there anything you need in addition to the above to reproduce the problem? Thanks!

**Comment by ryancramerdesign** [comment]
@adrianbj I'm not really sure how to solve this one because the system only knows about the names of pages, and it doesn't know about all the potential names that you might be using in URL segments. So it's coming up with a closest match based on the info it has access to, which is part of the purpose of this method, and I think is what is needed for this situation/environment most of the time.  Do you find that setting the `allowPartial` or `allowUrlSegments` options to false on a `getByPath()` method call enables you to get what you need? We could always make the options `$config`-urable (or maybe add new options), if that helps to get the result you are looking for.

**Comment by adrianbj** [comment]
Thanks for chiming in @ryancramerdesign - I know @Toutouwai mentioned he found problems not related to updating an existing link, but that is still the issue that seems to affect me.

When I correctly insert a link to: the `/couponname` url segment on the home page then I see a correct `data-pwid=1/couponname` but if I mistakenly link to a page, eg: `/coupons/couponname/` then I see `data-pwid=7259` where 7259 is the ID of the `/coupons/couponname/` page. 

Now the problem occurs when I change the link from that `/coupons/couponname/` to the correct `/couponname` url segment on the home page - the `data-pwid` doesn't get updated so it continues to serve up the page with ID 7259.

Do you think there might be an issue with updating that can be easily fixed?

I haven't played with those settings you suggested yet, but it appears they are already being set to `false` - https://github.com/processwire/processwire/blob/c9fef983bcc9a3eddfe82de9d2ac23ad43237a34/wire/core/PagesLoader.php#L1668-L1669 - or are you talking about somewhere else?

**Comment by ryancramerdesign** [comment]
I pushed some updates to this method on the dev branch this week which may potentially also resolve this issue. Though I'm not sure how to confirm, but wanted to mention it in case either of you have an installation that is exhibiting the issue.

**Comment by matjazpotocnik** [comment]
@Toutouwai Robin, can you please check if this issue can be closed?

**Comment by adrianbj** [comment]
The latest dev seems to solve this for me, although I haven't tested all scenarios thoroughly, so would definitely like @Toutouwai careful eyes to take a look.

**Comment by Toutouwai** [comment]
Working here, thanks.
