### ISSUE TITLE
"Unable to resolve link" should consider urlsegments

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1137]
### Short description of the issue

If you link to a URL with a URL segment, you get that error.

### Expected behavior

It should check to see if the link actually fails.

### Actual behavior

It returns the error noted in the title

### Steps to reproduce the issue

1. Add a link to a page with a URL segment in a RTE field
2. Save the page

**Comment by Toutouwai** [comment]
This issue occurs due to the link abstraction feature, so related to this issue: https://github.com/processwire/processwire-issues/issues/1116

As described in that issue, the problem is much worse if you happen to have a page in your site with the name of that URL segment - your link gets rewritten to the wrong URL with no warning.

**Comment by adrianbj** [comment]
Seems like you are always one step ahead of me reporting things these days :) Sorry, I need to search more thoroughly before posting.

**Comment by Toutouwai** [comment]
I realised after posting that your issue is a little bit different - I didn't mention the error notice in my issue (but did see it after I renamed my pages to avoid the link change). So thanks for adding the link in the other issue.
