### ISSUE TITLE
Sanitizer->selectorValue quotes value despite $options['useQuotes'] being false

### ISSUE THREAD

**Issue by JanRomero** [processwire/processwire-issues#1152]
### Short description of the issue

I’d like to save an untrusted value to the database and sanitize it with this, but I don’t want it to be wrapped in quotes. Setting `$options['useQuotes']` to `false` does the trick, but it is overriden when the value contains an exclamation point.

### Expected behavior

Setting `$options['useQuotes']` to `false` should never wrap the result in quotes.

### Actual behavior

[This line determines that quotes are needed if “!” is found](https://github.com/processwire/processwire/blob/f9337d77a5fc9ae0cdd9486261768b102347bfd0/wire/core/Sanitizer.php#L2002) and this isn’t checked against `$options['useQuotes']` later, resulting in double quotes being prepended as well as appended.

### Optional: Suggestion for a possible fix

Add `&& $options['useQuotes']` to [line 2009](https://github.com/processwire/processwire/blob/f9337d77a5fc9ae0cdd9486261768b102347bfd0/wire/core/Sanitizer.php#L2009)?

### Steps to reproduce the issue

1. Call `$sanitizer->selectorValue('my!very!exclamatory!test!value', ['useQuotes' => false])`
2. Observe the result.
3. [>Nice dubs](https://i.kym-cdn.com/photos/images/original/000/197/503/1320813769830.gif).

### Setup/Environment

* ProcessWire version: 3.0.152

Thanks :)

**Comment by ryancramerdesign** [comment]
@JanRomero I've pushed a fix for this (along with a rewrite of the method I've been working on). But I wanted to mention that you probably want to avoid disabling the useQuotes option because one of the primary reasons to use selectorValue() is so that it can make this determination. If you disable quotes, then any of those values that you use later you'll want to put quotes around every single one of them. It's best to use selectorValue() right alongside the method you are sending the value to, and you might instead want to DB store the value how it is prior to selectorValue(). Also note that if you give selectorValue() an array to represent OR values, then it's going to have to use quotes in some cases regardless of your setting. Thanks.
