### ISSUE TITLE
Get SQL Error after hooking in ProcessPageLister to set 'allowSystem'

### ISSUE THREAD

**Issue by kixe** [processwire/processwire-issues#1161]
### Short description of the issue

Hooking in **ProcessPageLister::execute()** to set 'allowSystem' property to true results in SQL error. With the hook the default selector includes 'title ... ' field + subselector, but subselector is not rendered/ set/ visible.

Hook is placed in **ready.php**
```
	wire()->addHookBefore('ProcessPageLister::execute', function($e) {
		$e->object->set('allowSystem', true); 
	});
```
Typing a value in the 'title ... ' selector (see screenshot below) results in SQL Error:

> SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'LIKE '%x%' ) )) WHERE ((pages.parent_id!=2 AND pages.parent_id NOT IN (SELECT p' at line 3

### Expected behavior

No errors. Title selector **without** subfield selector as default. 'Title ... ' selector (including subfield) should not be selectable.

### Optional: Screenshots/Links that demonstrate the issue

![Bildschirmfoto 2020-04-25 um 14 06 52](https://user-images.githubusercontent.com/4683120/80279805-1cbb2d00-8700-11ea-8015-b9e979ecbea5.png)

### Setup/Environment

* ProcessWire version: 3.0.154
* (Optional) PHP version: 7.2
* (Optional) MySQL version: 
* (Optional) Any 3rd party modules that are installed and could be related to the issue:

**Comment by kixe** [comment]
I figured out the following workaround to allow system templates without getting the error.

```
	wire()->addHookBefore('ProcessPageLister::execute', function($e) {
		$ppl = $e->object;
		$ifs = $ppl->getInputfieldSelector();
		$ifs->allowSystemTemplates = true;
		$ppl->set('inputfieldSelector',$ifs);
	});
```

**Comment by ryancramerdesign** [comment]
@kixe Any time you are using hooks you are hooking into back-end system processes. It's kind of like opening up some electronics and having a soldering iron. If something your hook is doing causes an error to occur, then it means you've got to find a different way to do it. And it looks like that's what you did (finding another way), so good work there. In this case, setting allowSystem before the execute method would be too late because allowSystem is also used during initialization, so a disconnect is created, causing an error.
