### ISSUE TITLE
Can't use $image->original after upgrading to from PHP 7.3 to PHP 7.4.5 

### ISSUE THREAD

**Issue by tiefenb** [processwire/processwire-issues#1162]
```
Fatal Error: Uncaught Error: Cannot access protected property Pageimage::$original in /wire/core/PageimageVariations.php:256 Stack trace:
1. /wire/core/Pageimage.php(1410): PageimageVariations->getInfo()
2. /wire/core/Wire.php(386): Pageimage->___isVariation()
3. /wire/core/WireHooks.php(823): Wire->_callMethod()
4. /wire/core/Wire.php(450): WireHooks->runHooks()
5. /wire/core/Pageimage.php(1452): Wire->__call()
6. /wire/core/Pageimage.php(400): Pageimage->getOriginal()
7. /wire/core/WireData.php(333): Pageimage->get()
8. /site/modules/BlueTomatoScene7ImageUpload/BlueTomatoScene7ImageUpload.module.php(87): WireData->__get()
9. /wire/core/WireHooks.php(924): BlueTomatoScene7ImageUpload->pointToBlueT
Line 256 of /wire/core/PageimageVariations.php
```
After Upgrading to PHP 7.4.5 I can't use $image->original any more.

Processwire Version: 3.0.155

**Comment by adrianbj** [comment]
Related to this:
https://github.com/processwire/processwire-issues/issues/1086

**Comment by ryancramerdesign** [comment]
@tiefenb @adrianbj This is a strange one, as original is definitely a property and I can see it in the get() method. But I think it must be hitting a circular reference and PHP is blocking it and giving us an error message that isn't quite accurate. I've pushed a fix that prevents the possibility of a circular reference occurring there. But since it's kind of an odd error here, I wonder if you can confirm it fixes it on that side? Thanks.

**Comment by adrianbj** [comment]
@ryancramerdesign - that commit seems to have fixed things for me - thanks.

**Comment by tiefenb** [comment]
Fixed, thanks!
