### ISSUE TITLE
inconsistent sort order output on frontend

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-issues#118]
### Short description of the issue

When outputting the child pages of a page, the order in which they appear is in the incorrect order about 10%-50% of the time.

### Optional: Screenshots/Links that demonstrate the issue

Correct:
![good](https://cloud.githubusercontent.com/assets/4558/21290637/4d3f7a20-c477-11e6-90e1-ffc57596b019.jpg)

Incorrect:
![bad](https://cloud.githubusercontent.com/assets/4558/21290641/5445d71a-c477-11e6-89e0-90bc63fa8ae4.jpg)

It's occurring on other parts of the website as well but I'd have to really dig to find them.

### Optional: Suggestion for a possible fix

My suspicion is that this weird bug has to do with how these pages were created (they were created using [PW's copy module](http://modules.processwire.com/modules/process-page-clone/)) in addition to some parent/child weirdness.

Not sure if it's also related to this issue:
https://github.com/ryancramerdesign/ProcessWire/issues/1942

### Steps to reproduce the issue

Simply go to [the website](https://zworkstations.com/) and refresh a bunch of times and you will see that occasionally the "Recommended" option under Z840 comes up first, which is incorrect.  Coincidentally when it happens to Z840, it also happens to Z820 directly below it.

### Setup/Environment
This is occurring on both my dev server and live server (running Ubuntu 16.10) and PHP 7.

It's NOT occurring when I'm logged in as an admin however. (!)

PW 3.0.40.  MySQL 5.7.15.

I'm not using any caching.

**Comment by jlahijani** [comment]
Another area of the website where it's occurring:
![bad2](https://cloud.githubusercontent.com/assets/4558/21290729/36229e0a-c47a-11e6-8ffe-289d36147074.jpg)

**Comment by jlahijani** [comment]
Here's how to reproduce this issue on a fresh PW installation.

1. Install PW using the blank template.
2. Create a child page of home called '1'.
3. Create a child page of home called '2'.
4. Install the Page Clone module.
5. Clone page '1'.  Title it '2'.  (since you cloned it, it should be the second page in terms of order).
6. Rename the original '2' to '3'.
7. Use the following code for home.php
```
<?php foreach($page->children as $p): ?>
<?php echo $p->title; ?>
<?php endforeach; ?>
```
8. Visit the home page while logged out of PW.  Refresh a bunch of times and you'll notice the incorrect page order.

**Comment by jlahijani** [comment]
So the 'fix' to the above is to re-order the pages around which I'm assuming forces PW to update any malformed page orders in the database.

**Comment by Toutouwai** [comment]
First guess would be that ProcessPageClone also clones the 'sort' property. If you check the Pages table in the DB do these pages that are getting mixed up have different values in the sort column or the same?

**Comment by LostKobrakai** [comment]
Also try this one: 

```sql
SELECT id, parent_id 
FROM pages 
WHERE id NOT IN (SELECT DISTINCT pages_id FROM pages_parents) 
AND id != 1 
ORDER BY id DESC
```

Cloning pages has in the past often lead to issues with the pages_parents table to get inconsistent. I've a 2.7.3 installation, where this happens regularly. By now I've just a simple fixing task running via lazy cron.

**Comment by ryancramerdesign** [comment]
I'm not aware of any 3.x issues with cloning and pages_parents, but I think this instead is very likely what @Toutouwai mentioned, as it does clone the sort property of the page along with everything else. If there are two pages being sorted among each other, and they have the same value for what it's being sorted on (whether that's the "sort" property, title, date or any kind of value on the page) then this behavior is expected. So by creating a clone, it's doing exactly what it should, but I can see how in this particular case it would be better if it could increment the sort rather than cloning it (along with incrementing all pages that follow it). 

When generating the output for a list of pages like those in the screenshot above, one way around it would be to add "sort=sort, sort=created" in your selector that finds the pages. Another way to fix it is to go into your page tree and drag the ambiguously sorted page above or below, then drag it back where you want it. However, I will look to see if there's a way we can automatically re-order all pages when cloning a page that exists on a parent having the manual sort option.

**Comment by LostKobrakai** [comment]
> However, I will look to see if there's a way we can automatically re-order all pages when cloning a page that exists on a parent having the manual sort option.

It would also be nice to have a pubic api for sorting operations.

**Comment by ryancramerdesign** [comment]
I will add a `$pages->reorder()` method to handle this, as it's something that would need to be accessible from the existing `$pages->clone()` method, and the ProcessPageSort module could potentially use it as well.

**Comment by jlahijani** [comment]
Thanks.  In the meantime I've fixed it by writing a script which sets/resets the 'sort' field on the pages.

**Comment by nettings** [comment]
I'm not sure if it's related, but I did see one third-level page change its place in the menu during some frantic editing. Always sprang back into its proper place when I tried to check. Could it be some race condition? My server is quite unresponsive at the moment because of a yet-untuned 4096-bit TSL setup, and that seems a nice way to bring some minor unpleasantness out in ProcessWire :-D
