### ISSUE TITLE
has_parent in OR-group gives wrong result

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1190]
### Short description of the issue

PW 3.0.148 (correct result):

![2020-06-06_202333](https://user-images.githubusercontent.com/1538852/83939796-ccbda300-a833-11ea-9fc0-09eaba21852a.png)

PW 3.0.159 (incorrect result):

![2020-06-06_202400](https://user-images.githubusercontent.com/1538852/83939804-d8a96500-a833-11ea-8c84-92bae77599ed.png)

### Setup/Environment

* ProcessWire version: 3.0.159

**Comment by noelboss** [comment]
I have probably the same error with queries Processwire after commit https://github.com/processwire/processwire/commit/88e04129c72c1702926543c8bef555a9f0d1043f

The commits after that refactoring the Database Classes probably introduced this. 

For me, this is a hot **breaking change**. My site does not work anymore because the selectors are used for validating access on pages and returning 0 results…

My Queries:

`include=all, template=PageBasic|PageHome, (parent.id=1017|3330|3410), (id=1253), (id=7841)`

`include=all, template=PageBasic|PageHome, (parent.id=1017|3330|3410), (id=1), (is_public=0)`

**Comment by noelboss** [comment]
Probably related to #1185

**Comment by ryancramerdesign** [comment]
@Toutouwai @noelboss I think that commit https://github.com/processwire/processwire/commit/857d5556aeead11f5719a201036de17f3a8f7d51 is likely to fix this issue, though please let me know if you find otherwise. Thanks.

**Comment by Toutouwai** [comment]
Fixed now, thanks.
