### ISSUE TITLE
PHP Fatal error:  Using $this when not in object context in ProcessWire.php on line 278

### ISSUE THREAD

**Issue by devsmo** [processwire/processwire-issues#123]
### Short description of the issue

When including ProcessWire 3.0.44 (and probably all other versions of the 3 branch) into a CLI script, an error occurs:

**PHP Fatal error:  Using $this when not in object context in /path/to/somewhere/wire/core/ProcessWire.php on line 278**

I've isolated the issue by just requiring ProcessWire index.php in an otherwise empty file.
This is an old script that worked fine under the 2.x branch.

I fixed this temporarily by commenting out line 278 and setting: 
$process = null;

### Expected behavior

It's not supposed to cause an error.

### Setup/Environment

PHP 5.3.10
This is my customers server and I can't update version..

**Comment by ryancramerdesign** [comment]
It looks like this is due to PHP 5.3 not supporting $this in anonymous functions. I don't have a PHP 5.3 installation available to me anymore, and was wondering if you could try replacing that line 278:
~~~~
$process = $this->wire('process');
~~~~
with this?
~~~
$process = isset($this) ? $this->wire('process') : wire('process');
~~~
Does that resolve the issue? Thanks.
