### ISSUE TITLE
New Page cannot be created if "one" is enabled for the template and a copy exists in Trash

### ISSUE THREAD

**Issue by clsource** [processwire/processwire-issues#1235]
# Short description of the issue

When creating a new page (with only one family restriction in template). 
If there is a page with the same template at the trash. It will throw error.

### Expected behavior

You can create a new page even if a previous page with the same template is in the trash.

### Actual behavior

Shows error on creating new page.

### Optional: Suggestion for a possible fix

Check if the conflicting page is on the trash, before throwing exception.

### Steps to reproduce the issue

1. Create a new template with the "one" modifier.
2. Create a new page with the template
3. Send the new page to the trash
4. Create a another new page with the same template.

ProcessWire version: latest dev

**Comment by ryancramerdesign** [comment]
@clsource I understand what you are requesting, and it makes sense to me. But the trash is still part of the overall page structure, even if not part of the front-end page structure. This "one" setting applies to the entire page structure. If we had a "one" setting on template "test", and two pages with that template (one in trash and one out) then pages.find("template=test, include=all") would match two pages. Pages in the trash can also be restored out of the trash. I'd rather just keep this "one" restriction simple rather than adding trash exceptions and supporting code to determine when "one" means 1, etc.... too complicated for me to keep track of. :)

**Comment by clsource** [comment]
Thanks @ryancramerdesign 
I now see that this may have unexpected consecuences. And I am Ok to keeping this simple as they are right now.

:)
