### ISSUE TITLE
Selector with or groups broken after upgrade from 3.0.153 to 3.0.165

### ISSUE THREAD

**Issue by ivangretsky** [processwire/processwire-issues#1243]
### Short description of the issue

I got this selector `parent=[page], condition=(pad_price|pad_percentage>=0.1), condition=(price_free.data1021!=''), range_start=(date_start=''), range_start=(date_start<=today), range_end=(date_end=''), range_end=(date_end>=today), parent.status<1024, sort=-modified`

It worked fine in 3.0.153 and doesn't (seems like it returns all children of a page) after upgrade to 3.0.165.
Please help!

**Comment by ryancramerdesign** [comment]
@ivangretsky I think that query may be a little too complex for me to duplicate here without having the database, which would reveal all the fieldtypes, data being matched, etc. As a result, I was wondering if you could try some simpler versions of your selector to narrow in on where the issue might be. The first thing I'd narrow in on is which of the OR-groups seems to be failing among these: condition, range_start and range_end. You could do this by leaving only one of the OR groups in per test. If it continues to match all the pages, remove one of the parenthesis expressions from the OR-group and test which one matches all and which doesn't. Double check that the OR-group names don't collide with field names. If your selector can match pages that use different templates that might not have all the fields you are referring to in the selector, I'd also suggest adding  a `template=...` part to your selector so that your blank/null matches aren't expanding the matched set.

**Comment by ivangretsky** [comment]
Thanks for the advice @ryancramerdesign !

I did what you suggested and narrowed it down to this part of the selector: `condition=(price_free.data1021!='')`. If it is present, the selector returns all children. And it worked fine in 3.0.153)

To test thing further down I modified the selector to a simple `parent=[page], price_free.data1021!='', sort=-modified`,  and it is already broken. So it is not or groups.

**Comment by ryancramerdesign** [comment]
@ivangretsky Thanks for testing. What kind of field is price_free (TextLanguage)? In Setup > Languages, can you check what language the ID 1021 refers to? Actually, I don't need to know what language, but just want to check that it's a non-default language and what state it is in (published or unpublished). Thanks.

**Comment by ivangretsky** [comment]
`price_free` is a Text (Multi-language) field.
1021 is an id of published non-default language.

**Comment by ryancramerdesign** [comment]
Thanks @ivangretsky I was able to duplicate it and have pushed a fix. When you get a chance, are you able to confirm it also fixes on your end? Thanks.

**Comment by ivangretsky** [comment]
Thanks, @ryancramerdesign ! The fix works!
