### ISSUE TITLE
Exception thrown for images when InputfieldCKEditor used independent of Page Edit

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1245]
### Short description of the issue

If InputfieldCKEditor is used outside of Page Edit (e.g. in a module config) and the standard CKEditor image plugin is used instead of the PWImage plugin, an exception is thrown when an image is double-clicked.

### Steps to reproduce the issue

1\. Install demo module:

```php
<?php namespace ProcessWire;

class TestModule extends WireData implements Module, ConfigurableModule {

	/**
	 * Module information
	 */
	public static function getModuleInfo() {
		return array(
			'title' => 'Test Module',
			'version' => '0.1.0',
		);
	}

	/**
	 * Config inputfields
	 *
	 * @param InputfieldWrapper $inputfields
	 */
	public function getModuleConfigInputfields($inputfields) {

		/** @var InputfieldCKEditor $cke */
		$cke = $this->wire('modules')->get('InputfieldCKEditor');
		$cke->name = 'test_cke';
		$cke->label = 'Test CKEditor';
		$cke->value = $this->test_cke;
		$cke->toolbar = 'Bold, Italic, Image';
		$cke->removePlugins = 'PWImage';
		$inputfields->add($cke);

	}

}
```

2\. Insert image via standard CKEditor image plugin.

3\. Double-click on image and note exception.

Screencast:

![ck](https://user-images.githubusercontent.com/1538852/92679318-33df7c00-f37c-11ea-8993-4124d3b79c03.gif)

### Setup/Environment

* ProcessWire version: 3.0.164

**Comment by ryancramerdesign** [comment]
@Toutouwai I think that the `$cke->removePlugins` are plugins to remove from CKE's defaults. The pwimage and pwlink plugins are not part of CKE's default plugins. Instead, they are added as part of `$cke->extraPlugins`, so I think they would need to be removed from that rather than added to removePlugins. This should accomplish what you are looking to do:
~~~~~
$cke->removePlugins = ''; // default is: image,magicline
$cke->extraPlugins = ''; // default is: pwimage,pwlink,sourcedialog
~~~~~

**Comment by Toutouwai** [comment]
Thanks @ryancramerdesign, that's working for me.
