### ISSUE TITLE
Search for words with dashes and other symbols does not work

### ISSUE THREAD

**Issue by endkampf** [processwire/processwire-issues#1248]
### Short description of the issue

Search for words with dashes and other symbols does not work for me. PW 3.0.165,  3.0.166.
![search1](https://user-images.githubusercontent.com/25553821/93715686-7fabd580-fb73-11ea-86ed-8663c194f22a.png)
![search2](https://user-images.githubusercontent.com/25553821/93715692-8a666a80-fb73-11ea-8b3a-4250a550465e.png)

**Comment by ryancramerdesign** [comment]
@endkampf It will depend on what search operator you are using. A hyphen doesn't matter, as it gets removed before the search gets it. The reason it's not matching is because of the word "tk" which falls below the minimum word length of a fulltext index. So if you are using a search operator that depends on a fulltext index, like `*=` or `~=` then it's not going to be able to match unless you adjust your database settings to support 2-character indexed words. For matching that particular phrase, you may want to use `%=` which doesn't depend on a fulltext index.

**Comment by endkampf** [comment]
Thank you very much, Ryan!  In PW 3.0.155 dev the search with ~= and words like "TK-1140" worked for me. I probably missed something.

**Comment by ryancramerdesign** [comment]
Really it worked before? Maybe I need to revisit this then. It should
depend on the DB min-word-length setting and which engine (InnoDB vs
MyISAM). But if I have it skip over the index for short words like "tk"
(falling back to using "like"), technically I think I could support it.

**Comment by endkampf** [comment]
> Really it worked before? Maybe I need to revisit this then. It should depend on the DB min-word-length setting and which engine (InnoDB vs MyISAM). But if I have it skip over the index for short words like "tk" (falling back to using "like"), technically I think I could support it.

Yes, it worked before.
Please look at the screenshots.
Here is the search result on my site (in Russian)
https://spstelz.com/search/?q=TK

![search3](https://user-images.githubusercontent.com/25553821/94038697-71f28c00-fdcf-11ea-9437-cba0fa430697.png)
![pw155](https://user-images.githubusercontent.com/25553821/94038745-8171d500-fdcf-11ea-8983-40ea89e74546.png)
