### ISSUE TITLE
Password not deleted when deleting a user

### ISSUE THREAD

**Issue by jmartsch** [processwire/processwire-issues#1251]
### Short description of the issue

When deleting a user, the according password in field_pass is not deleted. This could be a security risk.

For example I want to give a database to an external dev and so I deleted all users, so that he can not see which users were there. But he can still go through the database and find the hashes of the passwords.

### Expected behavior

Passwords should also be deleted.

### Setup/Environment

* ProcessWire version: 3.0.145

**Comment by ryancramerdesign** [comment]
@jmartsch I can't duplicate that one here. When I delete a user, the row in the field_pass table is also deleted. I'm not aware of any issues in past versions, but either way it might be good to upgrade your PW version since 3.0.145 is now pretty old. I would also suggest checking what site modules are installed, just in case one is somehow preventing the row from getting deleted with the user. 

As far as security risk, please note these are not passwords. They aren't even hashes of passwords. They are hashes of multiple things blowfish hashed alongside a password. There's no security risk to the passwords in having a copy of the database. The hash has nothing about the password, it can only be used for comparison with a known password, and only if you also have a copy of everything else included in the hash, which is intentionally disconnected from the database.

**Comment by jmartsch** [comment]
Thanks for your explanation. I will retest with another installation.
