### ISSUE TITLE
Invalid markup in example, default site profile (/site-default/templates/README.txt)

### ISSUE THREAD

**Issue by teppokoivula** [processwire/processwire-issues#1256]
Minor thing, stumbled upon this one while doing a sweep for potential accessibility issues. The README.txt file in default site profile templates directory contains following example:

```
     But we might also do something more like append some navigation 
     under the body copy or prepend a photo... the sky is the limit. 

     $content = "<img src='/photo.jpg'>" . $page->body;
```

I know this is just an example, but I still think it'd be good idea to use valid syntax: alt is necessary, so perhaps just change it to...

```
     $content = "<img src='/photo.jpg' alt=''>" . $page->body;
```

**Comment by ryancramerdesign** [comment]
Thanks @teppokoivula I've updated that example so that it includes an `alt` attribute. I sometimes leave things out when it comes to examples, just to keep it as short and focused as possible for the concept being demonstrated. You'll probably find a ton of examples like this from me, but don't worry, I still love `alt` attributes (or other omitted tag/attribute/etc.). :)

**Comment by teppokoivula** [comment]
Thanks, Ryan! :)

This one wouldn't have registered on my radar either if it wasn't for said automated test. It's a false positive since this code isn't _really_ code, but you know — it's nice not to have false positives, even if they are pretty easy to identify as such 👌
