### ISSUE TITLE
Page ID 1 does not render when user has no view access

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1262]
### Short description of the issue

I expected the template access settings shown below to render the Home page for users with no view access.

![2020-10-18_204421](https://user-images.githubusercontent.com/1538852/96361496-b7ae3480-1182-11eb-8815-9e01563dffea.png)

Instead, the PW admin login page is rendered.

### Setup/Environment

* ProcessWire version: 3.0.167

**Comment by ryancramerdesign** [comment]
@Toutouwai All the settings in your screenshot actually map to a single property, which is the `$template->redirectLogin` property. Value `0` means "show 404", value `1` means "show login page", value `>1` means "show page with this ID", or a URL value means "redirect to this URL". It's not possible to render the homepage with this setting. Though even if you could, it would be very problematic from an SEO standpoint, which is why I thought it fine to leave that option out. But if that's not applicable to your case and you still want to show the homepage, the best bet would be to create a new page/template that just does an `echo $pages->get('/')->render();` and use the ID of that page instead. Though if you are going to use this option, I would advise having it render or redirect to a dedicated login page if possible.

**Comment by Toutouwai** [comment]
In my case the whole site is restricted to logged in users only and the login form is on the Home page. And therefore there's no SEO to consider in this case. But I can use "/" as the redirect URL so will close this.
