### ISSUE TITLE
CKEditor layout shift on hover

### ISSUE THREAD

**Issue by Jehfen** [processwire/processwire-issues#1271]
### Short description of the issue

- in a multi-language installation, with language tabs enabled
- uikit theme
- on any ckeditor field

Hovering the ckeditor field the first time causes a layout shift, where the bottom margin of the textfield expands and then contracts again. It's quite anoying when having multiple textfields underneath eachother (like in a repeater).

### Expected behavior

No layout shift.

### Optional: Screenshots/Links that demonstrate the issue

https://imgur.com/a/e8Wpkvk

### Setup/Environment

* ProcessWire version: 3.0.165

**Comment by ryancramerdesign** [comment]
@Jehfen When using CKEditor "inline" type editors (like in your screencast), CKEditor isn't actually loaded into it until you hover it. So I think that might be what you are seeing there. The thing is, I can't duplicate the behavior in your screencast, except on CKE fields that are blank, and it's expected there since it has to grow enough to support a single line of text. But what's in your screencast (single line of text already present), I am not able to duplicate here. When I hover, there are no changes in margins/padding/size of the CKEditor. I'm wondering if it's possible you have any additional modules (admin enhancements, inputfields, etc.) installed that may be affecting the behavior?

**Comment by Jehfen** [comment]
~~Not visible in the screencast, but there was actually a 25% checkbox next to the 75% textfield in the screencast. When making them both 100% wide, so they fall underneath each other instead of next to each other, the layout shift was gone when hovering, even with a single line or no line of text at all.~~

**Comment by Jehfen** [comment]
After further investigation, I narrowed it down to the "langTabsNote detail" element. It switches between display none and inline when hovering a language tab. The issue is gone when ie. forcing it to display as block or not at all.

**Comment by matjazpotocnik** [comment]
@Jehfen I can't duplicate. Can you check with the latest dev version, on a clean install, if this is still an issue?

**Comment by matjazpotocnik** [comment]
@Jehfen, I'm closing this. Please let me know if you need it re-opening.
