### ISSUE TITLE
.htaccess 13A missing [OR]

### ISSUE THREAD

**Issue by cb2004** [processwire/processwire-issues#1276]
I recently came across this issue and I am not sure it effects all setups, but adding the [OR] seems to fix it:
```
# 13A. Redirect domain.com and *.domain.com to www.domain.com (do not combine with 13B): 
# -----------------------------------------------------------------------------------------------
RewriteCond %{HTTP_HOST} !^www\. [NC]
RewriteCond %{SERVER_ADDR} !=127.0.0.1 [OR]
RewriteCond %{SERVER_ADDR} !=::1
RewriteRule ^ %{ENV:PROTO}://www.%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
```
Although not sure it effects anything else?

**Comment by teppokoivula** [comment]
Just wondering: are `127.0.0.1` and/or `::1` checks here even necessary?

It looks to me like these might exist primarily so that one can avoid www redirect when developing locally (or something along those lines), and the fix you've applied here should result in "always truthy" state — i.e. if you're checking that SERVER_ADDR is not `127.0.0.1` OR it's not `::1`... isn't this always the case, unless it's somehow _both_ at the same time?

Maybe I'm missing something obvious :)

**Comment by cb2004** [comment]
So in my head the logic to my fix was if its not localhost IPv4 or localhost IPv6 then carry on with the rewrite, as you say it cant be both at the same time? Can it? Have I confused myself, or both of us :)

**Comment by eydun** [comment]
I always need to remove (comment out) the following line, to make it work on my servers:
`#  RewriteCond %{SERVER_ADDR} !=127.0.0.1`

**Comment by cb2004** [comment]
Finally had time to check out my change on WAMP and still attempts to redirect to www with the [OR], so your assumptions are no doubt correct @teppokoivula. So some servers don't support the default 4 lines, is there any way I can see what my server interprets SERVER_ADDR as?

**Comment by kixe** [comment]
Due to server configuration in front (e. g. proxy) it is possible that **SERVER_ADDR**  is set to localhost (127.0.0.1) and therefore the redirect is prevented. Have you already tried the following line of code?
`var_dump($_SERVER['SERVER_ADDR']);`
On the live server I would just comment out lines 2 and 3 and that's it. If you develop on your localhost you maybe need it 
(without [OR] condition of course).

This is not a bug. The Apache configuration should always be considered individually. The thread should be closed.

**Comment by cb2004** [comment]
You were spot on @kixe, my hosting was returning 127.0.0.1, so not a bug, but maybe something in the comments could be added to explain this. My hosting company obviously changed this (the rascals) so all my sites that were working, suddenly were not potentially causing duplicate content issues.

**Comment by ryancramerdesign** [comment]
@cb2004 I've updated the default .htaccess file to include the variation you've suggested without the SERVER_ADDR checks.
