### ISSUE TITLE
Adding a user from the page tree fails, though adding a user from the admin menu works fine.

### ISSUE THREAD

**Issue by solonmedia** [processwire/processwire-issues#1278]
### Short description of the issue

When adding a user from the top menu, the input template only shows a Name field and the user is added successfully.

When adding a user from the Pages > Home > Admin > Access > Users > New pathway, the input template shows a template selection field, a name field and a url field. When submitting this form, I get a 404 error and the URL follows the pattern:

    {domain.com}/processwire/access/users/edit/bookmarks/bookmarks/bookmarks/bookmarks/

I've tried removing site modules and get the same result. It is possible to add users without going this route, but I had a customer think the site was broken because she couldn't add users from the page tree.

### Expected behavior

Both methods of adding a user (from the top menu and the page tree) should be identical.

### Actual behavior

The two methods are not identical and one works properly while the other does not.

### Setup/Environment

* ProcessWire version: 3.0.168

**Comment by ryancramerdesign** [comment]
@solonmedia The superuser has access to the admin page structure, since they have access to everything, and might need to go in to adjust or fix something that can't be achieved elsewhere. But pages added or removed from it are managed by dedicated Process modules. So I wouldn't recommend modifying stuff directly in the admin page structure as it might cause issues since you are bypassing the dedicated Process module that manages a given type. It's kind of like the root user on unix going in and modifying the /etc/passwd file directly. I did look into this case though and found that I could force the add button to redirect to the Process module that manages users, so I have added that. But the best way to add users is to use the admin navigation navigation (Access > Users > Add).

**Comment by teppokoivula** [comment]
@ryancramerdesign, sorry to hijack this issue, but I just gave the "multiple templates/parents for users" feature a go and tried to add new user with a custom template under a public area of the site... and an identical issue showed up. Seems that I can only add the user via Admin > Users, not the page tree, even though the "new" button shows up in page tree.

I haven't tried with the latest dev branch yet, but do you know if this might've fixed that as well? Or is that an entirely different issue(/feature)? :)

Note that in that particular case the issue occurs for non-superusers as well.

**Comment by matjazpotocnik** [comment]
@solonmedia @teppokoivula I successfully added a new user in the page tree, though I didn't try with a custom user template. Just checking if this is still an issue?

**Comment by teppokoivula** [comment]
Hey @matjazpotocnik. The key was that the user had to be added to non-default location — not sure if that's what you did, or if you added it under admin.

https://github.com/processwire/processwire-issues/issues/1358 is now fixed and since that looks like a duplicate of this issue, I would assume that this one is also fine now. I don't have a test case for this anymore, though.

**Comment by ryancramerdesign** [comment]
@matjazpotocnik @teppokoivula I had a test case setup here and adding a user with non-default parent or template should work now in the page tree following last week's update. Though since there are a lot of different ways something can be set up, I was going to wait to hear back from Adrian to be sure.

**Comment by solonmedia** [comment]
This has been resolved per the other fixes mentioned.
