### ISSUE TITLE
Setting up a redirect with a file extension shows a / at the end

### ISSUE THREAD

**Issue by cb2004** [processwire/processwire-issues#1281]
In the settings tab, what other URLs redirect to this page, if I put in a URL with a file extension say .php, it adds a forward slash on the end of the list, so .php/

**Comment by ryancramerdesign** [comment]
@cb2004 As far as PW is concerned it doesn't matter whether there is a trailing slash or not, the redirect should work either way. But since it's a URL that PW will be handling (i.e. still considered a PW page path, even if not a real one), it'll notate them all in a consistent way. I don't recall for sure, but it might also depend on the template's trailing slash setting; but shouldn't affect the actual redirect when it occurs.

**Comment by cb2004** [comment]
No the redirect still works but its confusing to see. Also I noted that a redirect like ?page=123 doesn't work, so I am guessing this just plugs into page path history. Shame, woukd have loved to have setup all my redirects using a core module, but I know there are other modules for that.

**Comment by netcarver** [comment]
@cb2004 Is this closable in light of using another module or would it best be moved to the requests repo?
