### ISSUE TITLE
Dropdown issues InputfieldSubmit 

### ISSUE THREAD

**Issue by Da-Fecto** [processwire/processwire-issues#129]
### Short description of the issue

Removing a InputfieldSubmit button from a form (ProcessPageEdit::BuildForm) wil remove the button but not the dropdown. 

### Expected behavior

Remove the button (Inputfield) should remove the whole Inputfield, not just a part of it.

### Actual behavior

Removing the button will not remove the dropdown inside the button.

### Optional: Screenshots/Links that demonstrate the issue

![submit](https://cloud.githubusercontent.com/assets/2760993/21452454/46ded4b6-c907-11e6-84a8-4281a29dfc86.png)

### Steps to reproduce the issue
```
// hook after ProcessPageEdit::buildForm
public function afterBuildForm(HookEvent $event) {
	$form = $event->return;
	$fields = $form->children();
	$submitSave = $fields->get('name=submit_save');
	if ($submitSave) $form->remove($submitSave);
}
```

### Setup/Environment

* ProcessWire 3.0.42 © 2016:

**Comment by Da-Fecto** [comment]
typo

**Comment by ryancramerdesign** [comment]
Those dropdown links you see actually aren't connected with any specific submit button, but rather are a template of dropdown links that are applied to all *_save or *_publish submit buttons. Meaning, it won't matter what button(s) you remove, since there's an underlying assumption that in order to use the page editor, one has at least access to save edits they make. So for this case, rather than removing the submit_save button, the best bet might be to hide it with CSS or remove it with JS. Or if preferred you could hide/remove the "ul.pw-button-dropdown". 

I do think that your hook would work in other instances where submit button dropdowns are used, because ProcessPageEdit is the only case I know of where we are using a reusable "dropdown template" menu (that applies to all buttons), rather than bundling the actions directly into the InputfieldSubmit.

**Comment by Da-Fecto** [comment]
I do see your point, but at least I wish that I could remove the dropdown without additional CSS. 
Maybe an other option would be to make the protected $dropdownItems = array(); public, so I can empty the array so it won't render the dropdown.

**Comment by LostKobrakai** [comment]
Iirc there's by now no public (hookable) way to edit those dropdowns as well. Maybe this might be the opportunity to add that, so people can add their own options (or delete them if needed).

**Comment by mikerockett** [comment]
Off-topic: how'd the "36 minutes from now" happen? Timezone issue?

**Comment by Da-Fecto** [comment]
@mikerockett, lazy me not setting $config->timezone = 'Europe/Amsterdam';

**Comment by mikerockett** [comment]
@Da-Fecto - Ah, of course...

**Comment by netcarver** [comment]
As this is more of a feature request, I'm moving it over, we can continue the conversation over there.
