### ISSUE TITLE
Image actions can result in incorrect cropping of variations

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1301]
### Short description of the issue

The variation generated by...

```php
$variation = $pageimage->size(500, 500, ['cropping' => false]);
```

...should never be cropped - it should retain the aspect ratio of the original image. Likewise `$pageimage->maxSize(500, 500)` but there is an [additional problem with that](https://github.com/processwire/processwire-issues/issues/1277#issuecomment-755079601) so in this example I'll use `size()` with the cropping option set manually.

After an image action is applied (in the example I'm using "Rotate 90°") the variation is cropped. Perhaps something to do with an incorrect calculation of width and height due to the rotation that has taken place? Not sure. If you manually clear the incorrect variation then the next time it is generated it comes out correctly. So I guess the issue relates to the timing of the automatic clearing and regenerating of variations that occurs after an image action is applied.

Before image action:
![2021-01-06_181348](https://user-images.githubusercontent.com/1538852/103732121-9fe0a100-504b-11eb-912f-3c6ab009c35e.png)

After Rotate 90° image action:
![2021-01-06_181706](https://user-images.githubusercontent.com/1538852/103732137-a5d68200-504b-11eb-8145-344073d116a8.png)

After manually clearing the faulty variation and letting a new variation be generated:
![2021-01-06_181731](https://user-images.githubusercontent.com/1538852/103732155-ad962680-504b-11eb-927d-0218472067dc.png)

### Setup/Environment

* ProcessWire version: 3.0.170

**Comment by ryancramerdesign** [comment]
@Toutouwai I grabbed a screenshot of your photo to test with, but can't seem to duplicate either of the issues you've outlined here. Might this one have been already fixed since you reported it in 3.0.170? I don't recall working with this issue before though.

When I do a rotate 90 action, it rotates 90 degrees but doesn't lose any of image (nothing is cropped). When I do a `$image->size(500, 500, [ 'cropping' => false ])` again nothing gets cropped, but I get an image with dimensions 250x500.  I tried using both the base ImageSizerEngineGD and also tried with ImageSizerEngineImagick but got the same result for both.

Below is the screenshot photo I was testing with (grabbed from your first screenshot above), and I rotated 90 degrees so it was vertical before doing the size() test. 

<img width="498" alt="Screen Shot 2021-08-04 at 11 43 29 AM" src="https://user-images.githubusercontent.com/328272/128213376-4af37c9e-f288-4452-a766-396a1666703b.png">

**Comment by Toutouwai** [comment]
@ryancramerdesign, the issue is still occurring for me in v3.0.182. Here are some steps that hopefully let you reproduce it:

1\. Download the image file below.
https://user-images.githubusercontent.com/1538852/128266271-4bd44b4c-474a-497b-9869-f3d7fe3a2e47.jpg

2\. Upload the image file to an "images" field on a page using the basic-page template and save the page.

3\. Add the code below to the `basic-page.php` template file.
```html
<img src="<?= $page->images->first()->size(500, 500, ['cropping' => false])->url ?>" alt="">
```

4\. View the page on the front-end to generate the variation. You should see something like this:
![2021-08-05_110534](https://user-images.githubusercontent.com/1538852/128266598-beeff392-e0d2-4054-ae92-3b05a5ee77fc.png)

5\. In Page Edit, perform the "Rotate 90°" action on the image and save the page.

6\. Reload the page on the front-end. You should see something like this:
![2021-08-05_110814](https://user-images.githubusercontent.com/1538852/128266781-8ba43546-cf05-470c-825e-8945af655e78.png)

This variation is wrong. If you manually delete the variation file from `/site/assets/files/[pageid]/` and then reload the page once more the correct uncropped variation is created.

**Comment by matjazpotocnik** [comment]
I can replicate. Followed the steps, here are my observations. After image upload and save, there are 2 images: test.jpg (original, 1200x600) and test.0x260.jpg (API, 520x260). After page view on the frontend, test.500x500.jpg is created and it looks like this:

![image](https://user-images.githubusercontent.com/7663992/128292071-6835fd84-ccae-4716-a5e6-2687cff7749c.png)

The actual dimension of this image is 500x250px, but on the variation screen, it says it's 500x500. Is this correct behavior?

![2 after page view](https://user-images.githubusercontent.com/7663992/128291856-9051eea0-f767-4461-ab61-0619e10c4704.png)

Then I performed rotation and saved the page. The original image is rotated and now has dimension 600x1200, all thumbnail variations are recreated (looking at the image timestamp) with the correct dimensions, but test.500x500.jpg now has the wrong dimensions 500x500px instead of 250x500px. After deleting test.500x500.jpg and refreshing the page, the correct variation is created.

**Comment by ryancramerdesign** [comment]
@Toutouwai Okay I understand now, thanks for the additional info.  I can duplicate also. But this gets back to something I think we've looked at before, which is that the image file name can't reflect all possible image sizer options, and `cropping=false` would be an example of that. So when you are using non-default options it's a good idea to also use the 'suffix' option, enabling you to name your set of options for when variations might be created later. I believe there's a feature request for sidecar files to remember all the options in so that they can be used to re-create variations and cover scenarios like this. This is something I'd like to add, not in the next master version, but maybe after that. But for now it's preferable to use a suffix when going outside the default options. 

> The actual dimension of this image is 500x250px, but on the variation screen, it says it's 500x500. Is this correct behavior?

@matjazpotocnik Yes that's correct, the dimensions used in the filename reflect the dimensions used in the size() method call.

**Comment by Toutouwai** [comment]
Okay, I think the penny has dropped for me at last. 

I still think that trying to use a variation's filename as source of information for regenerating it is not a good approach so long as the all the parameters that might have been used to generate that variation cannot be decoded from the filename. 

But I understand now why this is done as opposed to what I'd rather the core did, which is just remove all variations when the original file has changed. The reason is that by default PW allows users to insert `img` tags into their CKEditor fields where the `src` attribute is just a static URL to a variation. I have never allowed this on my sites because from when I first started using PW it leapt out at me how fragile it is. I don't see an image variation as being a durable enough thing to be used like that. Instead I have always used a textformatter approach where the Pageimage is determined and then a variation is created dynamically via `$pageimage->size()` according to classes on the `img` tag. This way variations can be removed at no risk.

So for me it's much more reliable to remove variations when an image action is applied to an original image. And I can do that by replacing the `Pageimage::rebuildVariations` method using a hook:

```php
// Instead of rebuilding image variations, remove them and they'll be rebuilt when next requested
// Fix for: https://github.com/processwire/processwire-issues/issues/1301
// Also see: https://github.com/processwire/processwire-issues/issues/1277
$wire->addHookBefore('Pageimage::rebuildVariations', function(HookEvent $event) {
	/** @var Pageimage $pageimage */
	$pageimage = $event->object;
	$event->replace = true;
	$pageimage->removeVariations();
	// Return expected output
	$event->return =  [
		'rebuilt' => [],
		'skipped' => [],
		'reasons' => [],
		'errors' => [],
	];
});
```

This is working well for me so I'll close this issue and the [related one](https://github.com/processwire/processwire-issues/issues/1277).

**Comment by ryancramerdesign** [comment]
@Toutouwai If you find that strategy works, then perhaps the core could do the same thing, but just skip over the static images that are one-time created by ProcessPageEditImageSelect (i.e. for CKEditor), as I think those are the main issue? Those all have the suffix `is`, so if the removeVariations() could skip over images that have that suffix, then that might be a solution to the issue? I will add a `noSuffixes` option to the removeVariations method, as it could be useful either way.

**Comment by ryancramerdesign** [comment]
@Toutouwai Turns out there already are `noSuffix` (string) and `noSuffixes` (array) options supported by the removeVariations() method, but they just aren't documented. That's because they are instead options for the PageimageVariations::find() method, but since the removeVariations() gets its images from that find() method, the options should still work for removeVariations(). Does this seem like a potential solution here? If so, I can use that logic in the core. Though it's the morning and I've barely started my coffee, so I still be missing something.

**Comment by Toutouwai** [comment]
> If you find that strategy works, then perhaps the core could do the same thing, but just skip over the static images that are one-time created by ProcessPageEditImageSelect (i.e. for CKEditor), as I think those are the main issue? Those all have the suffix is, so if the removeVariations() could skip over images that have that suffix, then that might be a solution to the issue?

That sounds good _to me_, but I'm just not sure how other people are treating variations and whether they are creating static references to them in their sites (separate from ProcessPageEditImageSelect). If a user is treating variations as "safe" then they probably wouldn't like it if applying an action removed variations and created a broken reference (although those old variations would now be inconsistent with the source image).

For example, I created a module that lets users copy a Markdown string for images (including variations - maybe I shouldn't have included that feature) to the clipboard: https://processwire.com/modules/copy-markdown/
Personally I wouldn't reference a variation like that but maybe other people do.

I think the ideal solution would be to store all ImageSizer options that were used to create a variation in the filename of that variation in a way that can be decoded later if the variation needs to be rebuilt. I know that wouldn't be easy but it seems like it should be possible in principle. I've made a partial attempt at something like this with [Unique Image Variations](https://processwire.com/modules/unique-image-variations/). But this module doesn't provide a way of decoding the options, and I'm using the suffix to store the encoded options which isn't ideal but was the only avenue open to me in a third-party module. If the core was going to do something similar it would be better if the encoded options were separate from the suffix .

 So if you're thinking of tackling that feature later then maybe leave things as they are for now with the intention that eventually `PageimageVariations::rebuild()` will be able to correctly rebuild any variation no matter what options were used to create it, with or without any suffix.

**Comment by Toutouwai** [comment]
Heck, if was possible to rebuild a variation by decoding the options from the filename then it would be very cool if PW tried to automatically rebuild missing variations before thowing a 404. I'm imagining something like before the 404 PW checks the requested URL and if it looks like it's for an image variation and the original Pageimage exists it rebuilds the missing variation. I know a related MarkupQA feature exists for textarea fields but I'm thinking of something that works anywhere at the time an image is requested. Just dreaming out loud...

**Comment by ryancramerdesign** [comment]
@Toutouwai If I'm remembering correctly, the reason the "is" suffix was added was so that images created by ProcessPageEditImageSelect could easily be isolated from all the API generated variations. This would enable deletion of all API created variations while leaving the CKEditor ones alone. It was added many years ago, so I think it's now safe to put in use. The core at least doesn't use static images for anything else other than CKEditor. But sounds like maybe they are still possible, based on what you say. 

I think bundling all the options into the filename might be difficult at this point. On existing installations, it could force re-creation of images unnecessarily. On Tripsite (a site I work on), it would force re-creation of variations for likely more than 11k images, and when I count the number of variations of each plus the .webp versions, we're over 100k images that would be re-created. That could bring the server to its knees for days or weeks. So a feature like that can't just be introduced and made standard. I think it would probably have to use it only for files that have a filemtime greater than some date, or an option that only comes into play with some alternate named method that is otherwise the same as size().

> Heck, if was possible to rebuild a variation by decoding the options from the filename then it would be very cool if PW tried to automatically rebuild missing variations before thowing a 404. I'm imagining something like before the 404 PW checks the requested URL and if it looks like it's for an image variation and the original Pageimage exists it rebuilds the missing variation.

If the URL can dictate what size should be created, that's a security problem. Set a bot loose hitting URLs for all kinds of variations and fill up the hard drive or take over its CPU for a DOS attack. That's why the details of a variation have to originate from a code API call (or at least something on the server itself). 

>  I know a related MarkupQA feature exists for textarea fields but I'm thinking of something that works anywhere at the time an image is requested. 

It's okay in this instance because the requested variation is hard coded in the CKEditor markup, and originates from someone with page-edit permission.

**Comment by Toutouwai** [comment]
> I think bundling all the options into the filename might be difficult at this point. On existing installations, it could force re-creation of images unnecessarily.

Maybe Pageimage::size() could check if there exists a variation using the old naming before creating a variation with the new naming.

So at around [this line](https://github.com/processwire/processwire/blob/31524d7a5a06182614301d88bf0921fa171f6405/wire/core/Pageimage.php#L839) there would be something like:

```php

$filenameFinalExists = file_exists($filenameFinal);
// $oldFormatFilename is what the filename would have been using the old naming format
if(!$filenameFinalExists && file_exists($oldFormatFilename)) {
    $filenameFinal = $oldFormatFilename;
    $filenameFinalExists = true;
}
```


> If the URL can dictate what size should be created, that's a security problem. Set a bot loose hitting URLs for all kinds of variations and fill up the hard drive or take over its CPU for a DOS attack.

I feel like there would be solutions to this too, otherwise you wouldn't see such things used on high-profile sites like BBC and Washington Post. A couple of examples from their home pages right now...
https://www.washingtonpost.com/wp-apps/imrs.php?src=https%3A%2F%2Farc-anglerfish-washpost-prod-washpost%252Es3%252Eamazonaws%252Ecom%2Fpublic%2FJ6BPQBYOOVG6JHCGAHLM2IC7OQ%252Ejpg&w=232&h=130 (you can change "232" and "130" to whatever)
https://ichef.bbci.co.uk/news/240/cpsprodpb/379F/production/_119793241_gettyimages-1234311692.jpg (you can change "240" to whatever)
But I take your point and such a feature isn't really needed in PW.

**Comment by ryancramerdesign** [comment]
@Toutouwai 

> Maybe Pageimage::size() could check if there exists a variation using the old naming before creating a variation with the new naming.

That would collide with the most common resize scenario, which is a size(), width() or height() call with no custom options. Though it would work fine if one wasn't reusing the same dimensions between no-options calls and options calls, maybe that's good enough though, it's still an improvement.

> I feel like there would be solutions to this too, otherwise you wouldn't see such things used on high-profile sites like BBC and Washington Post. A couple of examples from their home pages right now...

They are likely using the AWS serverless image handler, which can do these kinds of on-the-fly resizes with little overhead and reasonable cost. But also it looks to me like someone didn't care enough to build a dimension whitelist or use the secrets system to generate URLs. Maybe they don't have to because budgets and resources are big enough for it to be a non issue. But for our case, image resizes using GD or ImageMagick take a lot of time and resources, so having URLs dictate any size would definitely be a security hole.

**Comment by Toutouwai** [comment]
> That would collide with the most common resize scenario, which is a size(), width() or height() call with no custom options.

I don't get why this would be a problem. If a variation filename using the new format is identical to an existing variation filename that uses the old format then it's fine to serve the old variation because it will be visually identical to any new variation that would have been created.

Just to elaborate a bit on how I imagine a new variation naming system would work....

Every imagesizer option that affects the visual appearance of an image would be represented in the filename of the variation: upscaling, cropping, sharpening, etc. I expect each option key would be abbreviated to a letter (ensuring uniqueness of encoded options) and a numeric value (true/false would be represented as 1/0, string values would be assigned a number, e.g. sharpening "medium" would be 2). So those options just mentioned might result in a filename portion such as "u0c0s2". 

Options that don't affect the appearance _could be_ represented in the filename, but they don't need to be. Because as I understand it the reasons for this new feature are:

1\. To ensure that where an existing variation file exists, if an imagesizer option is changed that will affect the appearance of the variation this new variation is actually served on the frontend. So for example, if I change `$image->size(300, 300)` to `$image->size(300, 300, ['cropping' => false])` I will generate a new variation file and see this new variation on the frontend.

2\. To allow for more accurate regeneration of variations when the core needs to do this (the image actions problem that this GitHub issue describes, MarkupQA regenerating missing variation files referenced in a textarea).

Some examples of options that don't affect the appearance: "webpAdd", "forceNew" and I think "autoRotation" should be applied to the original image at the time of upload rather than as a variation option, [see this issue](https://github.com/processwire/processwire-issues/issues/1154).

Each imagesizer option is represented in the variation filename _if it differs from the default value for that option as defined in the PW core_. So it doesn't matter if the option comes from the `$options` argument or from `$config->imageSizerOptions` in `/site/config.php`. An example:

$pageimage->size(300, 300, ['sharpening' => 'medium']);
Variation filename will include "s2" because the variation will have sharpening applied that is different that the PW core default.

$config->imageSizerOptions('sharpening', 'medium');
$pageimage->size(300, 300);
Variation filename will include "s2" because the variation will have sharpening applied that is different that the PW core default.

$pageimage->size(300, 300, ['sharpening' => 'soft']);
Variation filename will not include an "s" portion because the sharpening that is applied is identical the PW core default.

The reason for not including imagesizer options when they are at the default value is for future-proofing. It allows for the case that in the future PW introduces a new imagesizer option that affects the visual appearance, and we don't want all variations rebuilt unless the user is specifically using that new option differently to the default.

If this feature is introduced users will need to do a bit more thinking before they change a global imagesizer option in `$config->imageSizerOptions` because it will potentially result in all variations being recreated site-wide. But I would argue that this is the correct outcome because if I set `$config->imageSizerOptions('quality', 50)` then I am saying "I want every variation on this site to be created and served at quality 50".

**Comment by szabeszg** [comment]
> If this feature is introduced users will need to do a bit more thinking before they change a global imagesizer option in `$config->imageSizerOptions` because it will potentially result in all variations being recreated site-wide. But I would argue that this is the correct outcome because if I set `$config->imageSizerOptions('quality', 50)` then I am saying "I want every variation on this site to be created and served at quality 50".

This feature could be optional, so if someone want to opt out, why not?

**Comment by ryancramerdesign** [comment]
> I don't get why this would be a problem. If a variation filename using the new format is identical to an existing variation filename that uses the old format then it's fine to serve the old variation because it will be visually identical to any new variation that would have been created.

@Toutouwai What I was responding to is the statement from your previous message:

> Maybe Pageimage::size() could check if there exists a variation using the old naming before creating a variation with the new naming.

What I thought you were suggesting was a solution to the concern that I mentioned earlier: that I don't think we can force re-creation of images on existing sites. 

I mentioned one example, where a change to the filename via custom options would force re-creation of more than 100k images. I use custom options in `$config->imageSizerOptions` and in `size()` calls, but I don't want them reflected in the filename, on that site at least. It would kill the site for a week while it rebuilds all the images. But even if I was starting that site anew, I wouldn't need the options reflected in the filename, so it would be redundant in that case at least. Further, it would prevent me from ever changing options later because it would force everything to rebuild, when I might only want it to use the settings going forward. I mentioned that one example, but I think this is likely common. We can't very easily introduce a change like this without breaking a lot of sites. 

I would also say that I'm not sure everyone wants the options reflected in the filename. Likely most simply don't need it and won't ever run into the issues we're talking about. I work with images a lot but never needed anything other than the dimension reflected in the filename. Some may also consider options-in-filename unnecessary overhead, or even a drawback. When we add or change an option, we may want it "going forward", and not for everything that's already been created. I like the flexibility of being able to fine tune things over time without forcing everything before it to start over. If options were already reflected in the filename, personally I would likely never change the options for fear of doubling my disk space usage or taking down the server with expensive image resizes. 

Those are some downsides, but I know the upsides are also strong. People have different needs and are looking for different things. We'll want to add support for options-in-filename, it's a good feature for sure, but want to find a way to do it that doesn't exclude what is already working well for most. So it would have to be something that you choose to turn on, whether with an imageSizerOptions setting, a different method call, or something else. The default would have to be "off", especially considering existing sites. 

I agree with everything you mentioned about how options would translate into the filename. I'd like to work on this feature after the next master release a week or two.

**Comment by teppokoivula** [comment]
> I think the ideal solution would be to store all ImageSizer options that were used to create a variation in the filename of that variation in a way that can be decoded later if the variation needs to be rebuilt. I know that wouldn't be easy but it seems like it should be possible in principle. I've made a partial attempt at something like this with Unique Image Variations.

> I would also say that I'm not sure everyone wants the options reflected in the filename. Likely most simply don't need it and won't ever run into the issues we're talking about.

Been following this from the sidelines as I don't have much to add here, but thought I'd drop in to mention that in our case Unique Image Variations is one of the few must-have modules on all sites we build. I've been happy with what the module does — it solves most of my/our needs — but there's definitely value in having something similar baked in to the core :)

On a loosely (?) related note: in addition to enabling proper regeneration of variations, having options reflected in the filename itself helps _a lot_ with browser side caching issues.

**Comment by Toutouwai** [comment]
> What I thought you were suggesting was a solution to the concern that I mentioned earlier: that I don't think we can force re-creation of images on existing sites.

@ryancramerdesign, yes, that is what I was suggesting. That the size() method would calculate two potential variation filenames: the "old" filename which doesn't represent all the imagesizer options (i.e. the variation filename format that is used in PW now), and the "new" filename which does represent all the imagesizer options. There would be negligible overhead to doing those two filename calculations. If a variation file exists with the old filename then that variation is served, thereby avoiding the problem you raised of rebuilding all existing variations. But if no old variation exists then a new variation is created and served using the new naming.

You said: "That would collide with the most common resize scenario, which is a size(), width() or height() call with no custom options." But I think this solution works with any resizing scenario. I don't see how the absence of custom options causes a problem.

> The default would have to be "off", especially considering existing sites.

Sure, that's fine.

**Comment by BernhardBaumrock** [comment]
Added to RockAdminTweaks: https://github.com/baumrock/RockAdminTweaks/blob/main/tweaks/General/RemoveVariations/RemoveVariations.php
