### ISSUE TITLE
Strange missing module file notifications

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1307]
### Short description of the issue

@ryancramerdesign - seeing these error when upgrading to 3.0.170. I know it's a new feature to start highlighting missing module files, but these two are strange.

```
Found 2 module(s) missing file:
FieldtypeNumber => /site/modules/FieldtypeNumber/FieldtypeNumber.module
ProcessPage => /site/modules/ProcessPage/ProcessPage.module
```

I see that install.sql is supposed to add an entry into the modules DB table for FieldtypeNumber and ProcessPage but the system update for 3.0.170 is now removing ProcessPage, InputfieldWrapper, and FieldtypeNumber. Note that the install.sql files in the included site profiles are still adding these on install, so not sure if the updater kicks in on a new install, so these are probably being added, but then not removed as intended.

Also of note is that the errors report the files missing as being inside `/site/modules/` which is obviously incorrect.

**Comment by Toutouwai** [comment]
A couple of things related to the module notifications:

1. It's not clear what the user is supposed to do in response to missing module notifications. Is there some action the user is meant to take to fix the situation?
2. Missing module notifications and version change notifications seem to be persisting/recurring after every Modules > Refresh. I expected they would occur only once and then be cleared (unless as per number 1 above there is some action the user is supposed to take in response). 

Example: on one site I am seeing this with every Modules > Refresh...
![2021-01-19_155952](https://user-images.githubusercontent.com/1538852/104982387-6c503e80-5a6f-11eb-9fba-ef2fabb8f5eb.png)

**Comment by Toutouwai** [comment]
To answer my own question, I finally noticed the "Missing" tab that allows you to remove database records for modules that are missing their files.

**Comment by BernhardBaumrock** [comment]
I know this warning and I've solved it by deleting the record via RockMigrations: https://github.com/BernhardBaumrock/RockMigrations/blob/169724a62e608a6a63db9f50c58b20f56713fcbf/RockMigrations.module.php#L2050

Didn't know about the option of having a "Missing" tab - would be nice to add a note about that to the warning message:

> Found (2) module(s) missing file: Check the "Missing" tab if you want to remove them.

**Comment by ryancramerdesign** [comment]
The system updates run for new installations too, as the install.sql file also has its own system version, so system updates run relative to that for new installs. Meaning those old old module file references shouldn't stick around either way. This particular feature is for /site/modules/ only, FieldtypeNumber and ProcessPage are not core modules, and there never was an InputfieldWrapper module, so I think they must have been a development side effect from a long time ago and I just hadn't noticed earlier. 

It's not necessary to do anything with missing module files if you don't need the modules. But I think most people will encounter this message when they migrate a site or updates to a server and forget to migrate one or more site modules. (I seem to do that on occasion at least). So this message is primarily aimed at those people.

Module upgrade notifications are cleared once the module is actually upgraded. The module has to be loaded in order to be upgraded, so a repeat of "Found version changes" message for one module or another means that the listed modules may have upgraded files but they haven't been loaded yet in order for the upgrade to be applied. ProcessModule doesn't know what context and conditions are necessary for a particular module to be loaded, so it can't do that.

**Comment by virtualgadjo** [comment]
Hi all,
just a word to say that what Adrian describes happens on every fresh install of pw 3.0.184 (at least when using the site-blank as i often do or my personal site profile based on the blank one)
have a nice day

**Comment by matjazpotocnik** [comment]
@adrianbj @Toutouwai what's the status of this issue? @virtualgadjo Does this still happen on the new install using the latest dev?

**Comment by Toutouwai** [comment]
I still see the notices that @adrianbj mentioned in the issue description, usually when updating the PW version on an older site. 

And like he pointed out, the current `site-blank` install.sql creates rows for these things in the modules table...

https://github.com/processwire/processwire/blob/bde089afd35b41928c8432f25df402565952125c/site-blank/install/install.sql#L188
https://github.com/processwire/processwire/blob/bde089afd35b41928c8432f25df402565952125c/site-blank/install/install.sql#L221

...but there is currently no such core module as "FieldtypeNumber" or "ProcessPage".

**Comment by matjazpotocnik** [comment]
@Toutouwai Thanks for the update!

**Comment by virtualgadjo** [comment]
hi,
@matjazpotocnik
so far, having installed a lot of pw lately, the 3.0.210 master release eversince it exists, and updating my "translation ready" install with every new dev release (up to the last 3.0.222) i haven't seen the alert again
have a nice day

**Comment by ryancramerdesign** [comment]
Thanks, I have removed those unused module names from the two install.sql files that come with the core.  @Toutouwai @matjazpotocnik @virtualgadjo

**Comment by matjazpotocnik** [comment]
Update to the previous commit https://github.com/processwire/processwire/commit/2f60f9899274034f05e2d17d6a92d80d84613c1f

**Comment by matjazpotocnik** [comment]
@adrianbj, is it ok to close this issue now?

**Comment by adrianbj** [comment]
@matjazpotocnik  - seems ok here now.
