### ISSUE TITLE
Can't add new users to alternate parent/template via Users lister

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1308]
### Short description of the issue

When using Lister Pro, it's possible to config the Users Lister to change the parent for adding new users, but you can't change the template so you get an error something like this:

ProcessPageAdd: The template 'user' does not allow parents of type 'people'

Not sure if the lister config needs to have an option for specifying the template to be used. In reality, I think the Add New button is always going to be a problem when using the "alternate parent/template for users" approach so I have disabled it, but it's definitely a confusing situation.

**Comment by ryancramerdesign** [comment]
@adrianbj I can't duplicate this, but I think it may be because of the other issue you reported being fixed in the last week. The two are related and I believe a result of the same thing, so I'll close this one.

**Comment by adrianbj** [comment]
@ryancramerdesign - with the latest PW commits I am actually now seeing that same `ProcessPageAdd: The template 'user' does not allow parents of type 'people'` error when adding via the NEW button on the page tree of alternate users. If I revert back to 3.0.181 the error goes away, so it looks like the recent changes have broken something in terms of allowing a different user template. Note that this setup has a parent "People" with the "people" template and the child pages (users) have the "staff" template. The appropriate family settings are configured correctly in both directions.

**Comment by ryancramerdesign** [comment]
@adrianbj I found one thing related to the template `noMove` setting, which would prevent a regular 'user' template User from being created by ProcessPageAdd. But since you indicated it worked before, I'm guessing you already disabled that setting for your user template at some point. But I did just now update the PagesEditor class to ignore that setting for pages that don't yet have an id. 

My setup is that I have a /users2/ parent page for custom users, and it allows templates of either 'user' or 'user2' (and user2 is a custom user template). I'm able to create users in /users2/ that have template 'user2' or template 'user'. It sounds like in your case you are getting an error when attempting to add a regular 'user' template page to your equivalent of /users2/. 

Grab the latest dev branch just in case it's related to that noMove setting I mentioned. Go to Setup > Templates > user > Family (tab), and double check that "allowed templates for parents" is set to "admin" and "people". Double check it is the "user" template you are editing this setting for, and not your "staff" template or some other one. I know you said it already had that, but double check it because that's the only thing I can find that would produce the error you mentioned, unless there are some other hooks or something changing the conditions on the fly.

**Comment by adrianbj** [comment]
@ryancramerdesign - unfortunately that didn't help. 

> It sounds like in your case you are getting an error when attempting to add a regular 'user' template page to your equivalent of /users2/.

No, as i mentioned above, I am using the "NEW" button on the parent page and even though the parent page's template only allows users with the `staff` template as children, it still tries to create the children with the `user` template, hence the error. Make sense?

PS - yes my `noMove` setting has been unchecked the entire time.

**Comment by ryancramerdesign** [comment]
@adrianbj Between different parents and templates and different combinations of family settings, it looks like there are just naturally a lot of possible combinations to account for here. So I think it's just going to need logic specific to this multi parent/template users feature when it comes to adding users. I've attempted to do that by completely overriding the ProcessPageType::executeAdd method with a custom one focused just on users in ProcessUser::executeAdd.  This seems to be working for all the combinations I can put together here, though it may take more to cover everything, but I'm curious how this update works for your case?

**Comment by adrianbj** [comment]
@ryancramerdesign - in my really quick test, that seems to be working again now, so thanks for all the new logic.

**Comment by ryancramerdesign** [comment]
@adrianbj Great, thank for testing it out. Let me know if come across any issues.
