### ISSUE TITLE
Unable to get users via selector: 'roles.permissions' for non-superusers

### ISSUE THREAD

**Issue by kixe** [processwire/processwire-issues#1320]
### Short description of the issue

Unable to get expected result using selector 'roles.permissions' if user is non-superuser with permission to access roles.

### Optional: Suggestion for a possible fix

@see example below.

### Steps to reproduce the issue

The 2 following selectors should return the same result for non-superuser. 

```
	// wrong result
	$usersWithPermissionHelloWorld = $pages->find("template=user,check_access=0,include=all,roles.permissions=hello-world");
	var_dump($usersWithPermissionHelloWorld->each('id')); // array {}

	// right result
	$r = $roles->find('permissions=hello-world');
	$r = implode('|',$r->each('name'));
	$usersWithPermissionHelloWorld = $pages->find("template=user,check_access=0,include=all,roles=$r");
	var_dump($usersWithPermissionHelloWorld->each('id')); // array {10458, 10459, 10460}
```

### Setup/Environment

* ProcessWire version:
* (Optional) PHP version: 
* (Optional) MySQL version: 
* (Optional) Any 3rd party modules that are installed and could be related to the issue:

**Comment by ryancramerdesign** [comment]
@kixe This is more of a question of what should FieldtypePage support for inclusions when it needs to launch a separate PageFinder to figure things out specified in the selector (like converting a page name to an ID), as you'll see in this question posted in the code here: https://github.com/processwire/processwire/blob/master/wire/modules/Fieldtype/FieldtypePage.module#L937

I've never been sure, and don't think it's been brought up before this, so have left it for the field configuration to decide; and if the field configuration has nothing to say about it, then assume "include=hidden". 

Now that you've brought it up, I think maybe a better default would be for it to ask the PageFinder that initiated it, and then carry that include/check_access setting into the secondary PageFinder. And just use the "include=hidden" as a fallback rather than as an assumption. It's possible there will be unintended side effects, but I'm thinking most likely not. I've pushed some updates to support this in this commit: https://github.com/processwire/processwire/commit/a9b8d37c582537db45e013a165ee410b443ea106

**Comment by kixe** [comment]
Thanks
