### ISSUE TITLE
PHP Deprecated: array_key_exists(): Using array_key_exists() on objects is deprecated.

### ISSUE THREAD

**Issue by BernhardBaumrock** [processwire/processwire-issues#1321]
### Short description of the issue

I'm getting lots of these errors on PHP7.4

```
PHP Deprecated: array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in /wire/core/WireData.php:171
```

Didn't see any other reports other than this one https://processwire.com/talk/topic/21212-rockmigrations-easy-migrations-from-devstaging-to-live-server/?do=findComment&comment=204272 so I thought I report it :) 

### Setup/Environment
SERVER DETAILS
ProcessWire: 3.0.169
PHP: 7.4.3
Webserver: Apache
MySQL Server: 5.5.5-10.3.25-MariaDB-0ubuntu0.20.04.1
MySQL Client: mysqlnd 7.4.3

**Comment by ryancramerdesign** [comment]
Do you know what object it's referring to? The code in WireData is below.
There already is an object check for $key, and $this->data is an array. So
it's unclear to me what the source of the error is, unless maybe a
descending class has replaced the $this->data variable with an object?
~~~~~
if(is_object($key)) $key = "$key";
if(array_key_exists($key, $this->data)) return $this->data[$key];
~~~~~

**Comment by jmartsch** [comment]
I found the errors in Bernhards RockMigrations module. Will provide a fix next days with description what happened. The module was using `$this->templates->get()` but `$this` is not an instance of Process but WireData instead. That was one problem which I fixed by using `wire()->templates->get()` instead. Another one was that the module was trying to get a template, but the $name parameter in `$this->templates->get($name)` was already an instance of Template.

I made multiple fixes and now the code works flawless, at least the things I tested.

**Comment by BernhardBaumrock** [comment]
Thx @jmartsch if that issue is related to my module I'll close it here!

**Comment by teppokoivula** [comment]
Just a quick observation: I don't know the context, but IMHO you shouldn't (have to) use wire() in module code. This might not be reliable in multi-instance environment, etc. Assuming, of course, that my memory serves me right; only mention of multi-instance support I could find was a rather old blog post, not sure if there's anything about that in the docs.

In a module that extends Wire or WireData you would usually want to use $this->wire() instead.

... or, if it's not a module but rather some other Wire-derived class that you instantiate yourself, you probably should "wire" it when instantiating in order to inject the Wire dependency :)

**Comment by jmartsch** [comment]
@teppokoivula Thank you for that information. I will change the code accordingly.

**Comment by BernhardBaumrock** [comment]
@teppokoivula you are right and additionally to that I want to mention that usage of $this->wire() etc. had nothing to do with this issue. I was setting the `data` property of the migrations module to a WireData object and that was obviously a bad idea because the data property is needed internally by wire objects...

https://github.com/BernhardBaumrock/RockMigrations/commit/8d415f9545e6a1d4e44c8cb483fc0a54d85b4660
