### ISSUE TITLE
optionColumns fields don't collapse responsively

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1327]
### Short description of the issue

If you set up a field to use the `optionColumns` setting, it becomes a mess on narrow viewports

### Expected behavior

Columns should collapse responsively

### Actual behavior

They overlap making them fairly useless

### Optional: Screenshots/Links that demonstrate the issue

![image](https://user-images.githubusercontent.com/871211/107650671-955d8c80-6c33-11eb-862c-bf2bc3da0995.png)

**Comment by ryancramerdesign** [comment]
@adrianbj I'm not really sure what to do here because currently when one uses this setting, it is to define the value for the narrowest possible viewport. So a setting of "4" might be perfectly fine if they are choosing a letter or number or something. From your screenshot it looks to me like you are using it to define the number of columns for a wide desktop viewport instead. Maybe there needs to be a separate optionColumnsWide setting or something like that. But this gets into framework specific stuff like what the viewport breakpoints are going to be and such, and I think that might be more than an Inputfield should be dictating. Maybe the setting instructions just need to clarify that they need to choose a value that works with the narrowest possible viewport? (currently it doesn't say anything about it)

**Comment by Toutouwai** [comment]
Maybe there could be a `optionWidth` width setting that would accept any CSS width value, e.g. "180px", "15em". That way the items will never overlap and will wrap as needed according to the available width.

![cb](https://user-images.githubusercontent.com/1538852/128081011-4b285a15-1a72-4e1e-ad57-0dfef96cb8d6.gif)

**Comment by ryancramerdesign** [comment]
@Toutouwai I like that strategy, good solution.

**Comment by ryancramerdesign** [comment]
@adrianbj @Toutouwai I've upgraded the InputfieldCheckboxes and InputfieldRadios modules to support a `optionWidth` property in their configuration that works like Toutouwai suggested.

**Comment by adrianbj** [comment]
Thanks @ryancramerdesign and @Toutouwai - that solution seems to work quite well, although I would have assumed that you would use CSS's `column-count` and `column-width` , eg: https://css-tricks.com/guide-responsive-friendly-css-columns/
