### ISSUE TITLE
Page arrays limited to 1 get paginated

### ISSUE THREAD

**Issue by neonwired** [processwire/processwire-issues#1329]
### Short description of the issue

On pagination the docs say "ProcessWire will keep track of the page number and automatically adjust the results returned from any method that returns pages and has a limit greater than 1". However it does paginate page arrays of 1.

### Expected behavior

PageArrays limited to 1 don't get paginated

### Setup/Environment

* ProcessWire version: 3.0.148
* PHP version: 7.3

**Comment by ryancramerdesign** [comment]
@neonwired Can you point me to that part of the docs? It looks like it's out of date and I need to update it. At some point awhile back there was a request to support paginating 1-by-1, as it can be useful in some cases like slideshow type pages, etc. That feature was added some time ago. But it still uses the non-paginated behavior if you do any of the following:

1. pass in `[ 'findOne' => true ]` to the $options of the `$pages->find()` method. 
2. specify a `start=0` in your selector
3. Use `$pages->findOne()` or `$pages->get()` rather than `$pages->find()`.

**Comment by matjazpotocnik** [comment]
@ryancramerdesign, the docs are here: https://processwire.com/docs/front-end/markup-pager-nav/ (section named "Do I have to keep track of the page number?").

**Comment by ryancramerdesign** [comment]
@matjazpotocnik Thanks, I have updated that docs page to correct that.
