### ISSUE TITLE
ProCache: $config->urls->httpTemplates doesn't get cdn transformed (but $config->urls->templates does)

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-issues#1336]
When using ProCache with CDN, URLs built like this will get transformed correctly:

```
<img src="<?php echo $config->urls->templates; ?>images/test.png">
```

But this won't
```
<img src="<?php echo $config->urls->httpTemplates; ?>images/test.png">
```

**Comment by ryancramerdesign** [comment]
@jlahijani Neither of those settings are actually converted. ProCache does a replacement on the final markup before output and caching. It intentionally ignores any URLs that have a scheme in them (i.e. https://) so that you have greater control over which URLs hit the CDN and which URLs stay local. So, it's actually an intended feature, not a bug. :)
