### ISSUE TITLE
Nested sub-selectors broken in dev

### ISSUE THREAD

**Issue by niklam** [processwire/processwire-issues#134]
### Short description of the issue

Nested sub-selectors seems to be broken in dev branch (v3.0.46).

### Expected behavior

I expect selector `template=ss_athlete,entity_degree.id=[organization_ref=[template=ss_region,title_custom^=e]]` to return results as it does master branch.

### Actual behavior

Selector does not return results.

### Optional: Suggestion for a possible fix

I assume this has something to do with FieldtypePage::getMatchQuery() building `$query->where` to be `(field_assignment.data='organization_ref=[template=ss_region,title_custom^=e]')`.

### Setup/Environment

* ProcessWire version: 3.0.46
* PHP version: 5.5.9
* MySQL version: 5.6.33

I'm happy to gather more information about the issue if needed.

**Comment by ryancramerdesign** [comment]
Thanks, I couldn't find any applicable changes to code in PageFinder that should affect this, so pretty sure the issue is related to selector detection with recent changes to the `Selectors::stringHasSelector()`, as it was failing with the example selector you provided. I've just pushed a update that corrects that. Can you confirm it also fixes the issue you are seeing there?

**Comment by niklam** [comment]
The issue seems to be fixed. Thanks!
