### ISSUE TITLE
Dragging page out of trash doesn't automatically restore it

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-issues#135]
### Short description of the issue

Let's say you have a page in the trash.  If you drag it out of it into the general page tree area, it's not automatically restored in 3.0.46, however it is automatically restored in 3.0.44.

**Comment by ryancramerdesign** [comment]
Thanks, I think I've got this one fixed in the latest commit referenced here. Though it's possible I don't fully understand what you mean by "restore", so please let me know if you find it's not also fixed from what you were testing. My definition of restore for this case was restoring the "name" of the page, so that it doesn't continue to include the restore data in the page name.
