### ISSUE TITLE
maxUrlSegments in config.php influences admin navigation

### ISSUE THREAD

**Issue by tbba** [processwire/processwire-issues#1350]
There is a setting maxUrlSegments in /site/config.php 

Problem:
If I change this from 3 (default) to 1, it breaks some pages in /admin, where url segments are required to navigate.

Expected: 
this setting leaves the admin pages alone or there is a warning in the config.php about side effects when going too low.

// ProcessWire 3.0.174

**Comment by ryancramerdesign** [comment]
Thanks @tbba I've added a note about this in the configuration setting that they should not set it below 3. Unfortunately it can't apply one setting to the front-end and another to the admin because the Page is not known at the time it examines the URL segments (since the URL segments may determine what page is loaded).

**Comment by tbba** [comment]
Thank you
