### ISSUE TITLE
Do not add leading comma in InputfieldPageAutocomplete.js for its value

### ISSUE THREAD

**Issue by Lazerproof** [processwire/processwire-issues#1354]
### Short description of the issue

InputfieldPageAutocomplete.js adds a leading comma to its value that interfere to sanitize this value as CSV string using built-in 'array', 'intArray' methods of the sanitizer. 

### Expected behavior

![chrome_hoTjaSyDRZ](https://user-images.githubusercontent.com/5707348/111886335-aee1b900-89d5-11eb-95d8-51492afcfc19.png)

### Actual behavior

![chrome_K2zskET6FO](https://user-images.githubusercontent.com/5707348/111886337-af7a4f80-89d5-11eb-9542-ef2c118e6b28.png)

### Optional: Suggestion for a possible fix

https://github.com/processwire/processwire/blob/dev/wire/modules/Inputfield/InputfieldPageAutocomplete/InputfieldPageAutocomplete.js#L374

Change this part

```
$children.each(function() {
			var v = parseInt($(this).children('.itemValue').text());
			if(v > 0) {
				value += ',' + v; 
			} else if(v < 0) {
				value += ',' + v; 
				addValue += $(this).children('.itemLabel').text() + "\n";
			}
		}); 
```
to something like
```
$children.each(function(i) {
			var v = parseInt($(this).children('.itemValue').text());

			if(i === 0) {
				value += v;
			} else {
				value += ',' + v;
			}
			
			if(v < 0) {
				addValue += $(this).children('.itemLabel').text() + "\n";
			}
		});
```

**Comment by ryancramerdesign** [comment]
@Lazerproof Do you find that the extra comma as breaking something in the core? I often prepend and/or append commas to a value in order to optimize strpos or JS indexOf() checks for IDs in CSV strings. I don't recall if that's the reason for it here, but want to make sure I understand the issue being fixed before removing something that may be working as intended, as I don't see the array or intArray sanitizers being used in this module.

**Comment by matjazpotocnik** [comment]
@Lazerproof, can you provide additional information for Ryan?

**Comment by ryancramerdesign** [comment]
I'll close this since we've not heard back but please feel free to reopen if needed.
