### ISSUE TITLE
WireTempDir does not remove files older than maxAge

### ISSUE THREAD

**Issue by BernhardBaumrock** [processwire/processwire-issues#1356]
### Short description of the issue

Based on that forum question I tried to finally understand how tempDir maxAge works :) https://processwire.com/talk/topic/25306-using-wiretempdir/

Shouldn't it be as simple as that?

```php
$td = $files->tempDir('hello-world', 10);
$td->setRemove(false);
file_put_contents($td.'some-file.txt', 'Hello world');
```

### Expected behavior

some-file.txt should be removed after 10+ seconds.

### Actual behavior

The files seem to live forever?

### Optional: Suggestion for a possible fix

Adding `removeExpiredDirs()` to setRemove() seems to fix this problem.

```php
	/**
	 * Call this with 'false' to prevent temp dir from being removed automatically when object is destructed
	 *
	 * @param bool $remove
	 * @return $this
	 *
	 */
	public function setRemove($remove = true) {
		$this->autoRemove = (bool) $remove;
		$this->removeExpiredDirs($this->tempDirRoot, $this->tempDirMaxAge);
		return $this;
	}
```

This is another solution that seems to work (but is a workaround imho and not the usage that is stated in the docs https://processwire.com/api/ref/wire-file-tools/temp-dir/):

```php
$td = $files->tempDir('hello-world');
$td->setRemove(false);
$td->removeExpiredDirs(dirname($td), 10); // remove dirs older than 10 seconds
file_put_contents($td.'some-file.txt', 'Hello world');
```

### Steps to reproduce the issue

Without my fix:

1. Fire the first code example in tracy console several times
2. PW will create several temp directories in /site/assets/cache/WireTempDir/[0...n]
3. Wait 10+ seconds
4. Fire the code example again
5. Old temp directories will not be removed

With my fix:

1. Fire the first code example in tracy console several times
2. PW will create several temp directories in /site/assets/cache/WireTempDir/[0...n]
3. Wait 10+ seconds
4. Fire the code example again (once)
5. All old folders will be removed and only the fresh tempdir will exist

### Setup/Environment

PW 3.0.174

**Comment by BernhardBaumrock** [comment]
Maybe I'm misunderstanding how `maxAge` should be used or when files older than `maxAge` are removed?! I did not find any background magic that is run once a day or on modules refresh or the like...

**Comment by ryancramerdesign** [comment]
@BernhardBaumrock The WireTempDir behavior is setup for managing the considerations of temp dirs that are operated upon by multiple instances at the same time, but it makes it admittedly confusing sometimes, and the argument descriptions for the `$files->tempDir()` method are also very lacking I can see — I need to rewrite those. 

When you call setRemove(false) you are basically taking over responsibility for removing the temporary directory yourself. If you don't remove it, then PW will wait 24 hours, and then after that the next call to WireTempDir will remove abandoned temporary directories automatically. 

Temp dirs are deleted at the end of the request as the default behavior. The maxAge setting only comes into play for temp dirs that are shared among multiple instances, ensuring that dirs used by 2+ requests at the same time don't wipe each other out, and instead at least stick around as long as there's a file in there less than 120 seconds old (or whatever maxAge setting is). If only 1 request is involved, then it'll still get removed at the end of the request. (some can stick around longer if there aren't further WireTempDir calls). In reality, PW doesn't use anything other than the default maxAge setting, so I should probably just remove the setting since it does something different than most would think, it's difficult to describe, and it's not that useful to change the value of it.
