### ISSUE TITLE
Create tags/releases for new versions

### ISSUE THREAD

**Issue by saschanos** [processwire/processwire-issues#1364]
As I can see, the last version offically tagged was 3.0.165. Is there any reason for that? Would be very great to have the possibility to use fixed versions in our deployment. If there's any concerns, let me know.

**Comment by teppokoivula** [comment]
As for the reason: 3.0.165 is the latest master release, aka latest stable version. Dev versions are not tagged.

This is also related to the way ProcessWire release cycle works: after a major (stable) release there are usually some smaller fixes (which get tagged), but when a new cycle starts updates are _only_ applied to the dev branch... until there's a new "big merge" to the master branch.

I'm not saying that this is the perfect model. For an example this means that in order to get further fixes, you also need to subscribe to new features. This is also why many developers default to the dev branch.

To be fair the dev branch is often (at least) as stable as the master, apart from those occasions where a big feature update has just been added :)

**Comment by saschanos** [comment]
@teppokoivula, thank you for this explanation :). For me it looks like the other versions are not "real" dev versions because they also get a number like the other ones – but for now I'm fine with this.
