### ISSUE TITLE
Skype links do not show in ProcessPageEditLink modal

### ISSUE THREAD

**Issue by Atlant-Lektanov** [processwire/processwire-issues#1368]
### Short description of the issue

There is a bug in ProcessPageEditLink with the handling of skype links (for example `skype:username?chat`) in CKEditor. 

If you insert a skype link with the ProcessPageEditLink form and then reopen it, the link disappears (is not shown in the `link_page_url` field of the modal).

### Expected behavior

The ProcessPageEdit link should handle skype links so that they won't be removed from the modal after reopening it.

### Actual behavior

The ProcessPageEditLink gets link as URL and treats it as a link instead of plain text, and since this link doesn't contain slashes, it gets entirely removed from the field.

### Suggestion for a possible fix

It is possible to replace [line 147](https://github.com/processwire/processwire/blob/d8945198f4a6a60dab23bd0462e8a6285369dcb9/wire/modules/Process/ProcessPageEditLink/ProcessPageEditLink.module#L147) from 
`$currentValue = $this->wire('sanitizer')->url($this->wire('input')->get('href'), array(` 
to 
`$currentValue = $this->wire('sanitizer')->text($this->wire('input')->get('href'), array(`.
Or modify url sanitizer to handle skype links.

### Steps to reproduce the issue

1. Open modal window in ProcessPageEditLink.
1. Insert skype link into `link_page_url`.
2. Click "Insert Link".
3. Reopen modal window in ProcessPageEditLink.

### Setup/Environment

* ProcessWire version 3.0.174.

**Comment by ryancramerdesign** [comment]
Thanks @Clarity157 I think if this is a valid URL then it would be better to update `$sanitizer->url()` to support it rather than working around it by skipping over URL sanitization. I've put in an update that adds support for such URLs, though it appears it's PHP's built-in FILTER_VALIDATE_URL that doesn't support it unless the double slashes are added back into it, so I had to work around that by temporarily adding the slashes, validating, then removing them. (We've had to do similar for other cases that PHP's URL validation doesn't support). 

The thing is that something else still doesn't consider it a valid URL, because your example `skype:username?chat` still gets stripped out on page save in a CKEditor field, which I think means that HTMLPurifier doesn't consider it valid either. I'm less certain how to work around that, other than disabling HTML purifier when needed? Though please let me know if you've found something different.

**Comment by netcarver** [comment]
@Clarity157 Can this be closed now?

**Comment by Atlant-Lektanov** [comment]
@ryancramerdesign Thanks for fixing. I've tested it, and found the same.
@netcarver Yes, I think it can be closed unless it's possible to do something with HTMLPurifier.

**Comment by netcarver** [comment]
Ok, closing, please re-post here if this needs re-opening any time.
