### ISSUE TITLE
InputfieldTextTags throwing error in the admin panel

### ISSUE THREAD

**Issue by lesaff** [processwire/processwire-issues#1369]
### Short description of the issue
After updating core to 3.0.175, I've noticed this intermittent behavior (works on some sites but not others). When editing field or template, tabs and their content are not showing up on the page. Console is showing the following error:

```
Uncaught SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
    InputfieldTextTags https://localhost:3000/wire/modules/Inputfield/InputfieldTextTags/InputfieldTextTags.min.js?v=1-1619351998:42
    jQuery 2
    InputfieldTextTags https://localhost:3000/wire/modules/Inputfield/InputfieldTextTags/InputfieldTextTags.min.js?v=1-1619351998:40
    <anonymous> https://localhost:3000/wire/modules/Inputfield/InputfieldTextTags/InputfieldTextTags.js:101
    jQuery 11
```

### Expected behavior
Field details should show up (with all the tabs)

### Actual behavior
Field details are hidden 

This element was not triggered to show due to JS error
```
.pw-init #ProcessFieldEdit {
    display: none;
}
```
Looking at the error, it looks like JQuery is trying to find a nonexistent `data-opts` attribute during a foreach loop (executed by wire/modules/InputfieldTextTags/InputfieldTextTags.min.js) line 39-96, specifically line 42.

```
var o = JSON.parse($select.attr('data-opts'));
```

### Steps to reproduce the issue

1. Install 3.0.175
2. Edit any field or template

### Setup/Environment

Tested on both local environment (using Laravel Valet) and on a staging server running Ubuntu 20.x with RunCloud server manager.

* ProcessWire version:
* (Optional) PHP version: 7.4.x
* (Optional) MySQL version: 5.7.x

**Comment by lesaff** [comment]
Note: this issue just came out recently (2-3 days). I've updated some sites to 3.0.175 last week and they are fine.

**Comment by Toutouwai** [comment]
A Modules > Refresh may be required after the latest core update: https://processwire.com/talk/topic/25500-pw-30176-%E2%80%93-core-updates/?do=findComment&comment=213743

**Comment by lesaff** [comment]
@Toutouwai unfortunately module refresh did not work for my case. It is still returning JS error (see screenshot). The error 

<img width="913" alt="CleanShot 2021-04-26 at 20 53 54@2x" src="https://user-images.githubusercontent.com/1151181/116165235-d06b4a00-a6d1-11eb-822d-c8a7553dde38.png">

![CleanShot 2021-04-25 at 09 01 16](https://user-images.githubusercontent.com/1151181/116165366-1aecc680-a6d2-11eb-9ac7-889ccfddb1fb.png)

**Comment by Toutouwai** [comment]
I'm getting the same problem when debug mode is off. I think the problem might be in `InputfieldTextTags::renderReady()` [here](https://github.com/processwire/processwire/blob/94d8cae85a596e7d42e8909fde441f44ef111093/wire/modules/Inputfield/InputfieldTextTags/InputfieldTextTags.module#L473-L474):

```php
$config->scripts->add($url . 'InputfieldTextTags.js');
$config->styles->add($url . 'InputfieldTextTags.css');
```

These files named the same as the module don't need to be added because the parent `Inputfield::renderReady()` method is called which automatically adds those, minified or not according to the debug mode. Commenting out the two lines fixed the issue for me.

**Comment by cb2004** [comment]
Same issue for me

**Comment by csaggo** [comment]
+1 one, works on some sites, updated another one today not beeing able to edit field or template

**Comment by ryancramerdesign** [comment]
I can't duplicate the issue here, but it may be because the extra lines Toutouwai mentioned were removed earlier so maybe that was the issue, though please let me know if still experiencing it.

**Comment by lesaff** [comment]
@ryancramerdesign whatever changes in those last couple of commits surely fixed it. I am closing this issue. Thanks.

**Comment by lesaff** [comment]
FYI, the culprit of this particular issue is this module https://github.com/outflux3/SelectizeTemplateFieldTags

As soon as I uninstalled it, the JS error disappeared. I will reach out to @macrura about this.

**Comment by outflux3** [comment]
Yes, i posted a few days ago about this. You have to uninstall the module for now, until I work out how to make it compatible.

https://processwire.com/talk/topic/25531-pw-30177-%E2%80%93%C2%A0core-updates/?do=findComment&comment=214042

**Comment by ryancramerdesign** [comment]
@outflux3 Sorry about that, I wasn't aware of any of this when I added the module to the core, let me know if there's anything I can do on this end that would prevent the issue?

**Comment by outflux3** [comment]
Hi Ryan, thanks, not sure what can be done; The module initializes the tags field in the same basic way as the core, but the module allows users to enter a list of tags in the module settings, so that differs since the core collects these from the in-use tags (which the module also does); I just need to see how i can now use the core config setting to get those but maybe somehow extend it with the user's list of tags - probably a hook can be used and then the module no longer needs to selectize init that tags field.

**Comment by ryancramerdesign** [comment]
@outflux3 Sounds good, let me know if you can think of anything. It sounds like your module was already doing some of this stuff before the core module as added, so maybe it would be worthwhile to have any relevant parts of the core (field & template editors or more?) detect if it's present and delegate to your module when it is.

**Comment by outflux3** [comment]
If I could maybe hook into the getTags() for templates & fields, then I could add the pre-defined tags that users specify in the module, and from there the functionality of the what the module was doing should be identical now with the core tagging. 

Or, the other option is to have a place to add these tags as a core feature, and deprecate this part of the module. 

Or have the core detect if there are tags in the js config for the module and add those to the json in the inputfield's list of available tags.

The key thing here for admins is that when building a site, it is helpful (at least for me) to paste in a whole list of tags I want to use for the templates and fields, and then select them, instead of having to type them in and remember them, which introduces some risk of duplicate tags (e.g. with different capitalization). The core "add new tag" forces you to select stuff to put the tag on, so currently there is no way to just paste a long list of tags to store and then be able to select those for templates & fields. Also, the module allowed the user to have a separate label and value, like this:

File_and_Image_Fields, File and Image Fields, which would display the spaced version of the tag when selecting it, but store the underscored version.

**Comment by outflux3** [comment]
I have by the way pushed a temp fix for the module, so those JS errors won't occur now (prevented the module from attempting to init the tags fields on these newer versions).
https://github.com/outflux3/SelectizeTemplateFieldTags/issues/1#issuecomment-840594661

**Comment by ryancramerdesign** [comment]
@outflux3 

> If I could maybe hook into the getTags() for templates & fields, then I could add the pre-defined tags that users specify in the module, and from there the functionality of the what the module was doing should be identical now with the core tagging.

Making the getTags method hookable would be a simple change, if you'd like me to do that?

> The key thing here for admins is that when building a site, it is helpful (at least for me) to paste in a whole list of tags I want to use for the templates and fields, and then select them, instead of having to type them in and remember them, which introduces some risk of duplicate tags (e.g. with different capitalization). 

Maybe I don't fully understand, but I think you can do this already by pasting your list of tags into the "tags" input on any Field or Template. Once you save, all the tags are added to the field or template you added them to, but they also become "selectable" at that point for any other fields or templates, whether from each field/template's "tags" input or the "Manage Tags" section. Prior to 3.0.177 they weren't selectable from each template/field tags input though. 

> File_and_Image_Fields, File and Image Fields, which would display the spaced version of the tag when selecting it, but store the underscored version.

That's true, the core tags don't do that at present. Though it is supported by the recently added InputfieldTextTags module. But everywhere that the core uses tags for its own assets (files, images, templates, fields), it uses 1-word tags in page-name format, rather than separate 1-word-tag + label. So it's pretty basic, outside of multi-language considerations and identical between code use and admin, in the same way that a template or field name would be. It's nice to be able to expand these kinds of features with more options by way of available 3rd party modules.

**Comment by outflux3** [comment]
@ryancramerdesign 

thanks yes, if we can try the getTags hookable i will give it a try and see if this solves it.

> Maybe I don't fully understand, but I think you can do this already by pasting your list of tags into the "tags" input on any Field or Template. 

This would be a hack though because then that field or template would have those tags, whereas the module just stores the selectable tags without actually having to tag anything.

**Comment by outflux3** [comment]
I can also make it hookable here on my test install before you do that to the core, if you could just let me know what to change.

**Comment by outflux3** [comment]
I added the 3 underscores to the core Templates getTags() and then hooked (after) in the module init and so for it appears to work well; I can grab the user's tags and merge them with the in-user template tags. I'll need to do this for fields also; so i can confirm that if you make the getTags methods where they appear in templates and fields classes hookable, i will be able to keep the module working identically, in post 3.0.176 pw versions.

**Comment by outflux3** [comment]
@ryancramerdesign 
Just checking to see if the getTags method will be made hookable on the next dev release; When that is done, i'll be able to finalize the module for compatibility

**Comment by ryancramerdesign** [comment]
Thanks @outflux3 I have updated both Template and Fields so their getTags() methods are hookable.
