### ISSUE TITLE
$input->cookie API thoughts

### ISSUE THREAD

**Issue by pine3ree** [processwire/processwire-issues#1370]
Hello Ryan, while updating my webite code in order to support the now almost required SameSIte attribute I took a look at the `$input(->cookie)` api and a couple of questions/doubts came to my mind:

1. Semantically input cookies should be read-only, since request cookies are and only response SetCookie header can be set. So wouldn't it be better to have a different api object for that purpose (e.g. a global $cookies read/write api var `$cookies->get($name)` proxy to `$input->cookie->get($name)`, `$cookies->set($name, $value[,...])`, and forbid `$input->cookie->set/remove/removeAll()` calls). Or move cookie setting functionality into the existing WireHttp (`$http->cookie->set(...)`, or `$http->(send/set)Cookie)` and maybe having a global `$http` api var as well. I remember when I first used $input->cookie->remove() I thought I was removing the request value
2. Wouldn't it be more useful to have one class (api object) for setting response cookie headers and have the Session class forward calls to it. The only difference are the default configuration options.

kind regards,
maks

**Comment by ryancramerdesign** [comment]
@pine3ree Cookies can be kind of complicated for the reasons you mentioned, so the point of the cookie API is to simplify that and make them work more consistently with something like `$session`, rather than for people having to know about http headers and such. Something like if PHP's $_COOKIE superglobal was both readable and writable in a manner that persisted. I don't think it would be worthwhile for PW to have an API for setting cookies if it wasn't significantly simpler, and at minimum abstract away the technical details; so that's what `$input->cookie` does. I imagine people used to the technical details of cookies will use PHP's native cookie functions for cases where they prefer it. When using cookies the biggest thing to keep in mind is that they pass through input, which is why I thought all cookie functions should be accessible only from the `$input` API var, while otherwise working more similarly to `$session`.

**Comment by pine3ree** [comment]
Thanks for the explanation
