### ISSUE TITLE
if file not found: user->language changed to default.

### ISSUE THREAD

**Issue by flihub** [processwire/processwire-issues#1372]
### Short description of the issue
ProcessWire 3.0.175

wanted to save current language name to cookie. if processwire not found any file or image, user language fallback to default language.

```php
//init.php 
$input->cookie->set('lang', $user->language->name, time()); 

//main.php
$langCode = $user->language->name == "default" ? "en" : $user->language->name; // this works as expected but cookie set to default.
```

if put images to folder. cookie language set true.

**Comment by ryancramerdesign** [comment]
@flihub This occurs because the missing image results in a 404, and your 404 page is likely also powered by PW and uses your init.php and main.php files as well. See the .htaccess file in your web root which includes instructions on how to prevent PW from being your 404 handler for missing image files. Though you may also want to update your cookie logic to not set cookies on 404 requests:
~~~~~
if($page->id !== $config->http404PageID) {
  // set your cookie
}
~~~~~

**Comment by flihub** [comment]
thanks.
