### ISSUE TITLE
FieldType Options won't save its updated value under specific hook environment

### ISSUE THREAD

**Issue by er314** [processwire/processwire-issues#1375]
Below is :
- an explanation of the problem, and of the setup under which the problem occurs
- in attachment, the exported templates & fields of a minimal environment for reproducing the problem
- in attachement, a minimal ready.php hooks code for reproducing the problem

### short description of the environment

* Templates & fields configuration : 
Let's say that we have a main template (aa_template) which has :
. a text field : aa_text
. an Options field : aa_options
. a 1st PageTable field : aa_pgtable1 ; the template (aa_pgtable_template1) for its items has : just a text field
. a 2nd PageTable field : aa_pgtable2 ; the template (aa_pgtable_template2) for its items has : both a text field (aa_text) and an Options field (aa_options) 

* Hooks configuration : 
A. addHookBefore("Pages::save(0:template=aa_template)"
-> if aa_text or aa_options are changed by a backend user, then create a new PageTable item into pg_table1
B. addHookBefore("Pages::save(0:template=aa_pgtable_template2)"
-> if aa_text or aa_options are changed by a backend user, then also create a new PageTable item into pg_table1

### Expected behavior

A. When backend user changes the following contents of an existing page of main template (aa_template) : 
	text field contents + Options field contents, then he saves the page 
-> we expect that the saved page includes both changes performed to the text field + to the Options field for this page, and we expect that a new page is created in pg_table1

B. When backend user changes the following contents of an existing item of the 2nd PageTable (aa_pgtable_template2) :
	text field contents + Options field contents, then he saves the item page 
-> we expect that the saved PageTable item page includes both changes performed to the text field **+ to the Options field** for this PageTable item page, and we expect that a new page is created in pg_table1

### Actual behavior

A. Fully OK, as expected.

B. A new page is created in pg_table1, as expected. The saved PageTable item page contains the expected updated value for the text field ; but it contains the previous value for the Options field. In other words, **the Options field value has not been saved**.

After some (incomplete) investigation in the PW core code, it appears that the changed value is well retrieved in the POSTed data, it is well assigned to $page, then the hook is called for creating the new PageTable item for aa_pgtable1. But when the code "comes back" to processing the actual save of the updated aa_pgtable2 item, $page value for the Options field has "lost" the change, so this change is not saved in DB (while $page value for the text field has kept the change, so this change is saved in DB).

### Steps to reproduce the issue

Described above. 
In addition,
- Exported minimal templates config to reproduce : see attachment
- Exported minimal fields config to reproduce : see attachment
- Hooks minimal code to reproduce : see attachement
[exported_templates.txt](https://github.com/processwire/processwire-issues/files/6423598/exported_templates.txt)
[exported_fields.txt](https://github.com/processwire/processwire-issues/files/6423607/exported_fields.txt)
[ready.php.txt](https://github.com/processwire/processwire-issues/files/6423606/ready.php.txt)

### Setup/Environment

- Processwire v3.0.177

**Comment by ryancramerdesign** [comment]
@er314 This is a little over my head. :) So my reply might be stating some obvious things or I may be pointing to irrelevant things, but here goes. If we remove the custom/added hooks from this, are you able to observe an issue where an options field value is not saved with the page? The reason I ask is because in this environment, a page that has PageTable field doesn't know or save anything about it other than the IDs of the pages within it. If you need something more from it within a hook, it may be that you have to hook sometime later or that you have to load a fresh copy of the PageTable item that you are wanting to examine. Though admittedly I can't think of anything unique about the Options field that would make it behave differently from others, but my best guess is that it's just a matter of an item in the PageTable that is not the latest version because there is more than one instance of it in memory. ProcessWire caches a lot of things, and it doesn't do otherwise unless it internally needs to for one reason or another; it can't predict when a hook might have a different need. When working with hooks like this, you are hooking into low level system stuff and sometimes that also involves working around low level system stuff. Though I would suggest using a `Pages::saveReady()` hook rather than a before `Pages::save` hook. I'm not sure that matters here, but wanted to mention it just in case. Since you are also matching arguments with your addHook call, i.e. `0:template=aa_pgtable_template2` I would also suggest double checking that you are receiving a page having the template you expect. Once confirmed, you can remove the check, but I thought it might be worthwhile just in case, since I don't see many people using this more advanced feature/syntax when adding hooks, and I just want to rule out any potential bugs in there.

**Comment by er314** [comment]
Thanks for your reply,

_>> If we remove the custom/added hooks from this, are you able to observe an issue where an options field value is not saved with the page?_

No issue in that case ; as soon as I remove the hook, the field (new) value is saved.

_>> my best guess is that it's just a matter of an item in the PageTable that is not the latest version because there is more than one instance of it in memory. ProcessWire caches a lot of things, and it doesn't do otherwise unless it internally needs to for one reason or another; it can't predict when a hook might have a different need. When working with hooks like this, you are hooking into low level system stuff and sometimes that also involves working around low level system stuff. Though I would suggest using a Pages::saveReady() hook rather than a before Pages::save hook. I'm not sure that matters here, but wanted to mention it just in case._ 


Ok, I see. Yeah, I'll try that ! (not these days, as I'm currently hiking, rather away from the civilisation :-)
I've recently had to deal with Page caching in another context, so I see what you mean.

The thing is, in the mean time I have set a satisfactory workaround (= executing the 2 hooks sequentially - 1st before save, 2nd after save - , instead of "nested").

So, as on your side this thing doesn't ring you a bell, and on my side I've moved to an alternative approach, I propose that we close the issue for now.


FYI, 2 other subjects which I think would deserve your opinion :
- PageTable lacking view-only rendering -> #1274 
- Core support for some sort of concurrency check upon Page edit ? -> request 406 : https://github.com/processwire/processwire-requests/issues/406

thanks
