### ISSUE TITLE
PW internal live search (module ProcessPageSearch) not working properly with custom config?

### ISSUE THREAD

**Issue by CalleRosa40** [processwire/processwire-issues#1386]
I'm trying to configure PW 3.0.165 admin page search (top right-hand corner) to behave as follows:

- search in title field while typing
- search in body and title fields upon pressing enter

Module config clearly allows for that (settings "Page fields to search" and "Page fields to search if user hits 'enter'"). However, PW seems to consider the first setting only, meaning that upon pressing enter PW still only searches in title field. Only when I add body field to first setting it gets searched (on hitting enter as well). Same behavior on a clean install.

Btw, it would be great if the search results page would give some info about the search term(s) used.

**Comment by matjazpotocnik** [comment]
Would it be possible to add the "id" to the list of searchable fields?

**Comment by ryancramerdesign** [comment]
Thanks @CalleRosa40 I've pushed a fix for this. 

@matjazpotocnik The "id" property can only be matched with an exact match, so it's not one that can be mixed in with a search for "title", as an example. Since the search box is designed for partial text matching, a field such as "id" doesn't really work, as it's not stored as text, nor does it have a text matching index. However, you can match it by using a specific match query. For instance, typing `pages.id==9999` in the search box, replacing 9999 with the page ID you want to match should do it.

**Comment by adrianbj** [comment]
@matjazpotocnik - don't forgot that Tracy's PW Info panel as an AJAX powered ID search box. I use that multiple times a day when developing a site.

**Comment by matjazpotocnik** [comment]
@ryancramerdesign, thank you for the explanation. I was hoping for a solution like the one I currently use (provided by Robin):

```
$wire->addHookAfter('ProcessPageSearch::findReady', function(HookEvent $event) {
	$selector = $event->return;
	$q = $event->wire('input')->get('q');
	// If the admin search query is a number
	if(is_numeric($q)) {
		// Get the individual pieces of the selector
		$selector_pieces = explode(', ', $selector);
		// Modify the first piece so that it includes an ID clause in an OR-group
		$selector_pieces[0] = "({$selector_pieces[0]}), (id=$q)";
		// Replace the original selector
		$event->return = implode(', ', $selector_pieces);
	}
});
```

But it's fine, I'll continue to use the hook.

@adrianbj, thanks for the hint, but I don't use Tracy on the production site. I like to keep it "clean" (just required modules are installed).
