### ISSUE TITLE
Inputfield placeholders not working well in multi language

### ISSUE THREAD

**Issue by trk** [processwire/processwire-issues#139]
I am using ProcessWire 3.0.46 commit 208 on local. I have 3 language on this website.

- English (main)
- Deutsch
- Turkish

If the user profile language isn't main language, user can't see main language in placeholder, . Also this is same for front-end.

I am using admin panel in Turkish language and here is value for Turkish language :

![ekran resmi 2017-12-29 16 50 57](https://cloud.githubusercontent.com/assets/455983/21545336/9a75fd52-cddf-11e6-885f-7b9f027d2081.png)

If i change the profile language to the main (default) one :

![ekran resmi 2017-12-29 16 58 24](https://cloud.githubusercontent.com/assets/455983/21545353/c420a102-cddf-11e6-8ffb-934ce3efcd83.png)

Result for Deutsch language :

![ekran resmi 2017-12-29 16 59 42](https://cloud.githubusercontent.com/assets/455983/21545373/e1862ed8-cddf-11e6-8f23-67a1c659b9b4.png)

**Comment by trk** [comment]
This commit https://github.com/processwire/processwire/commit/51bda526eb637f86fc56694cc85f6d5a7fba306b fixed backend side.

Site language is : **English**
User language is :  **English**

I don't have this issue for other languages (Turkish, Deutsch). 

Problem appear in front-end :

![inputlabels](https://cloud.githubusercontent.com/assets/455983/21577457/bb96f128-cf63-11e6-8e2e-a530dec7ed14.jpg)

in my screenshot you can see back-end translations also.

**Comment by ryancramerdesign** [comment]
I'm not sure that I understand what you mean by front-end, as this setting is specific to PW Inputfield forms like used in the page editor. Though it would also apply to front-end forms in FormBuilder, which now supports the placeholder setting. However the form in your screenshot doesn't look like the page editor or a FormBuilder form (?). Outside of usage in the page editor or FormBuilder, you will have to add some of your own logic to the code in order to pull the correct placeholder value. For non-default languages, the placeholder values are stored in property "placeholder{id}" of the Field object, where you replace "{id}" with the language ID, i.e. 
~~~~~
$languageID = $user->language->isDefault() ? '' : $user->language->id;
$inputfield->attr('placeholder', $field->get("placeholder$languageID")); 
~~~~~

**Comment by trk** [comment]
I am using your module : http://modules.processwire.com/modules/form-template-processor/ for render form on front-end. Let me check your module, how is it create form from template file.

**Comment by trk** [comment]
Here is quick print_r($inputfield, true) result :

```php
echo "<pre>", print_r($inputfield, true), "</pre>";
ProcessWire\InputfieldText Object
(
    [hooks] => Array
        (
            [before InputField::processInput] => FieldtypeCroppableImage3->HookValidateSettingsInput() in FieldtypeCroppableImage3.module
            [before Inputfield::render] => LanguageSupport->hookInputfieldBeforeRender() in LanguageSupport.module
            [after Inputfield::render] => LanguageSupport->hookInputfieldAfterRender() in LanguageSupport.module
            [before Inputfield::renderValue] => LanguageSupport->hookInputfieldBeforeRender() in LanguageSupport.module
            [after Inputfield::renderValue] => LanguageSupport->hookInputfieldAfterRender() in LanguageSupport.module
            [after Inputfield::processInput] => LanguageSupport->hookInputfieldAfterProcessInput() in LanguageSupport.module
            [before Inputfield::processInput] => LanguageSupport->hookInputfieldBeforeProcessInput() in LanguageSupport.module
        )

    [data] => Array
        (
            [label] => First Name
            [description] => 
            [icon] => text-width
            [notes] => 
            [head] => 
            [required] => 1
            [requiredIf] => 
            [collapsed] => 0
            [showIf] => 
            [columnWidth] => 50
            [skipLabel] => 
            [wrapClass] => 
            [headerClass] => 
            [contentClass] => 
            [textFormat] => 4
            [renderValueFlags] => 0
            [requiredAttr] => 1
            [initValue] => 
            [stripTags] => 1
            [showCount] => 0
            [placeholder1057] => Name
            [placeholder1105] => İsim
            [hasFieldtype] => ProcessWire\FieldtypeText Object
                (
                    [hooks] => Array
                        (
                            [before Fieldtype::formatValue] => LanguageSupportFields->hookFieldtypeFormatValue() in LanguageSupportFields.module
                        )

                )

        )

)
```

**Comment by trk** [comment]
I can get true placeholder value with this method :
```php
$languageID = wire('user')->language->isDefault() ? '' : wire('user')->language->id;
$placeholder = wire('fields')->get($inputfield->name)->get("placeholder$languageID");
```
Do i need to hook inputfield for add true placeholder value to input ?

**Comment by ryancramerdesign** [comment]
The FormTemplateProcessor module was always intended just as a proof of
concept, and so it's good to modify it according to your needs. The module
was an example created for ProcessWire 2.0 and 2.1, so it's not going to
have support for anything beyond what was present in that version of PW
(which is probably good since it keeps it as a good simple proof of concept
without confusion). If you wanted to add placeholder support for instance,
there's a foreach() in that buildForm() method that would probably be the
best place to add it.
