### ISSUE TITLE
Issues relating to detecting field changes

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1399]
### Short description of the issue

Recently I've been working on a module that involves detecting changes to page fields and I encountered a couple of issues that I'd like to raise.

#### 1\. Pages::savedPageOrField()

The documentation for this method is pretty minimal but the second argument is named `$changes` and is an array of field names, so it seems reasonable to assume it that it contains the names of fields that have changed.

If I change the title of a page then `$changes` includes "title":

![2021-06-24_140802](https://user-images.githubusercontent.com/1538852/123191642-b2fe0500-d4f5-11eb-89c2-10e85fb81ab0.png)

And if I save the page without changing anything then `$changes` is empty:

![2021-06-24_140922](https://user-images.githubusercontent.com/1538852/123191765-d7f27800-d4f5-11eb-8c25-3354ad6d03a1.png)

So far, so good.

But if I populate the `$field` argument of `$page->save()` then this field is forced into the `$changes` array even if the field value has not changed.

![2021-06-24_141327](https://user-images.githubusercontent.com/1538852/123192109-61a24580-d4f6-11eb-9cfd-ba8b2886257a.png)

This means that the `$changes` argument doesn't necessarily contain the names of fields that have changed, which makes it unreliable and therefore much less useful. It would be great if PW could actually test for changes before including a field name in the `$changes` argument.

#### 2\. WireArray::isIdentical()

This method doesn't seem to be as useful as it could be for checking if two WireArrays are different. There are shortcomings with the `strict` argument set either true or false.

If `strict` is true then the method returns false for two WireArrays that have identical items in them:
 
![2021-06-24_150224](https://user-images.githubusercontent.com/1538852/123195996-38d17e80-d4fd-11eb-9d23-4c8b12a9bd1a.png)

But if `strict` is false then the method only compares the string values of the two WireArrays which isn't sufficient to tell if the items contained have any differences.

![2021-06-24_150508](https://user-images.githubusercontent.com/1538852/123196184-95349e00-d4fd-11eb-907c-283577b5d6f1.png)

I ended up needing to create a recursive version of getArray() to properly compare WireArrays (BTW, it would be useful to have a `getArrayRecursive()` method as part of the core).

### Setup/Environment

* ProcessWire version: 3.0.179

**Comment by ryancramerdesign** [comment]
@Toutouwai 

1. When you specify a `$field` you are forcing it to save and so a change to the field is implied by the call. It also needs to be in the changes list in order for PW to save it. 

2. For your strict call, they would need to be the same object instances in order to be considered identical. The non-strict just compares the string value of the WireArray, which is typically stuff like page IDs, field names, etc.. Both the strict and non-strict are intended to be very fast, and other types of comparisons would be quite a bit slower. Maybe there's value in an option in between those two, but I think it would likely be contextual to the case, so maybe something better for someone to implement according to their need, which sounds like what you may have done here.

**Comment by Toutouwai** [comment]
Thanks, fair enough.
