### ISSUE TITLE
Text Tags z-index issue

### ISSUE THREAD

**Issue by flihub** [processwire/processwire-issues#1403]
![image](https://user-images.githubusercontent.com/16720735/124244746-f4129c80-db27-11eb-96e5-460d2dd43efb.png)

**Comment by ryancramerdesign** [comment]
@flihub I can't seem to duplicate it here. I tried different kinds of fields and wrappers for where you have your "Company Information" field, but I'm not able to reproduce the z-index issue. Can you tell me more about what is in the Company Information field and what type it is? Maybe there's something unique about it that is interfering with the z-index. Also, please let me know if you are using any kinds of other admin enhancements/modules.

**Comment by flihub** [comment]
"Company Information" type is Fieldset (Page). It's wrapper has ".InputfieldRepeater" class which has "z-index: 1".  
"Languages you know" field also child of another "Fieldset (Page)".

ProcessWire 3.0.181
Tested with latest Edge and Firefox.

**Comment by matjazpotocnik** [comment]
@flihub @ryancramerdesign I can confirm the issue. I removed `.InputfieldRepeater {z-index:1}` from InputfieldRepeater.css (InputfieldRepeater.scss) and it looks like that fixes the issue. 

![image](https://user-images.githubusercontent.com/7663992/167341488-0396a643-7431-440f-bd10-032575ae63c3.png)

**Comment by Toutouwai** [comment]
The `z-index: 1` was added to fix a previous outline issue when the depth option is used: https://github.com/processwire/processwire/commit/ad9973ca33f2686b06c0c98e0b99bd950256904f

But perhaps another way to solve that depth issue is to apply the `position: relative` to the `ul.Inputfields` element instead of the `div.InputfieldContent`. So [here](https://github.com/processwire/processwire/blob/fa3fb8ec892cc7f4c0fcc2094b17c4bd19c1d004/wire/modules/Fieldtype/FieldtypeRepeater/InputfieldRepeater.js#L1062) change to:
```js
$inputfieldRepeater.children('.InputfieldContent').children('.Inputfields').css('position', 'relative');
```
Then the z-index wouldn't be needed to fix the outline.

**Comment by matjazpotocnik** [comment]
@flihub @Toutouwai does Ryan's fix work for you?
