### ISSUE TITLE
AdminThemeReno - Pressing the up arrow key in the autocomplete search results causes the search input to hide

### ISSUE THREAD

**Issue by gmclelland** [processwire/processwire-issues#141]
### Short description of the issue

In AdminThemeReno - Pressing the up arrow key in the autocomplete search results causes the search input to hide.

### Expected behavior

I should be able to press the up or down keys to focus the autocomplete search results items.

### Actual behavior

Pressing the down key works, but as soon as you press the up key the search input disappears.

### Optional: Screenshots/Links that demonstrate the issue
![setup processwire pwtwig dev 2016-12-29 11-27-19](https://cloud.githubusercontent.com/assets/40570/21549721/d9a010d8-cdb9-11e6-9ba1-8933326478d3.jpg)

### Optional: Suggestion for a possible fix
I think I see the problem.  I will try to submit a pull request.

### Steps to reproduce the issue

1. Click in the main site search input in the site's header
2. Start typing a keyword
3. Press the down key to navigate the autocomplete search results
4. Press the up key to navigate the autocomplete results.  Search results and search input disappear.

### Setup/Environment
Google Chrome on a Mac

* ProcessWire version: ProcessWire 3.0.44
* (Optional) PHP version: 5.6

**Comment by gmclelland** [comment]
This PR should fix the problem https://github.com/processwire/processwire/pull/48

**Comment by ryancramerdesign** [comment]
@gmclelland and @renobird it looks like the code that does this was intended as a means to close the menu, and the PR appears to break that. I don't want to remove something that was intended here. @renobird since this was something you built, I was wondering what your opinion is this? Perhaps we could accommodate both behaviors by just having the up-arrow-to-close only apply if a down arrow hasn't previously been pressed?

**Comment by gmclelland** [comment]
> it looks like the code that does this was intended as a means to close the menu, and the PR appears to break that.

Correct.  IMHO, pressing the up key when inside the search input doesn't seem like an important enough feature to keep.  I would guess most people don't even know about this feature.

> Perhaps we could accommodate both behaviors by just having the up-arrow-to-close only apply if a down arrow hasn't previously been pressed?

I don't think it is worth adding additional javascript to work around this.  Seems like that could be fragile.

**Comment by ryancramerdesign** [comment]
> Correct. IMHO, pressing the up key when inside the search input doesn't seem like an important enough feature to keep. I would guess most people don't even know about this feature.

I don't personally use the feature, but I've found that it's the little details like this that often matter to people a lot. Since @renobird built the theme and took the time to add this capability, I'm assuming it's important, even if it isn't to you or me. 

> I don't think it is worth adding additional javascript to work around this. Seems like that could be fragile.

As it turns out, it was very easy to accommodate the behavior so that it only uses the up-arrow-to-close behavior if they haven't already started using the keyboard to navigate the list. It was easier than I thought to support both behaviors. Thanks.

**Comment by gmclelland** [comment]
Closing.. This is committed at https://github.com/processwire/processwire/commit/928a399b8ae9e8629461b98c5579f4b99889197f
