### ISSUE TITLE
Hook ProcessPageView::pageNotFound not called in ready.php

### ISSUE THREAD

**Issue by gebeer** [processwire/processwire-issues#1410]
The hook [ProcessPageView::pageNotFound](https://github.com/processwire/processwire/blob/d8945198f4a6a60dab23bd0462e8a6285369dcb9/wire/modules/Process/ProcessPageView.module#L895) is not called when placed in site/ready.php. It needs to be in site/init.php

It would be nice if information was added to the methods documentation :-)

**Comment by ryancramerdesign** [comment]
@gebeer Whether referring to states or hooks, ProcessWire uses the term `ready` to say something is ready and is definitely going to proceed. For example, the ready state means the `$page` is known, it is viewable and it is going to be rendered. By nature, a pageNotFound hook would no longer apply by the time a ready state is reached, because the state implies that the page has already been found and is ready to use. I have updated the phpdoc for that method to clarify that it must be attached sometime before the ready state. Thanks.

**Comment by netcarver** [comment]
Closing as this is documented now.
