### ISSUE TITLE
RepeaterMatrix delete icon (fa-trash) appearing as bar icon (fa-bars)

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-issues#142]
### Short description of the issue

RepeaterMatrix delete icon (fa-trash) appearing as bar icon (fa-bars).  Not sure why this is occurring.  On 3.0.46.  Weirdly however, on another 3.0.46 installation it appears correctly, so I'm not sure if you'll be able to replicate this.  I tried clearing cache, Firefox vs. Chrome, etc.

### Optional: Screenshots/Links that demonstrate the issue

![2016-12-29_15-10-56](https://cloud.githubusercontent.com/assets/4558/21556885/a24aba28-cdd9-11e6-9c0a-9bffbb5d5bbf.jpg)

**Comment by ryancramerdesign** [comment]
I can't duplicate it, but since you actually see the "fa-bars" in the
inspector, I don't think it's a font glitch or anything like that. Chances
are something added it via javascript. I'm guessing a 3rd party module,
because neither RepeaterMatrix nor the core uses that icon anywhere, except
in one unrelated spot – the default admin theme uses an fa-lg version of it
when in mobile mode, but I'm confident that's not where it's coming from.
If you do a recursive grep on your /site/modules/ directory for "fa-bars"
or "bars" does it turn up anything?

On Thu, Dec 29, 2016 at 6:15 PM, Jonathan Lahijani <notifications@github.com

**Comment by jlahijani** [comment]
Weird... I guess I was running a slightly older version of RepeaterMatrix which contained fa-bars mistakenly.  Closing.
