### ISSUE TITLE
Markup RSS generates invalid XML due to entity encoding feed description

### ISSUE THREAD

**Issue by teppokoivula** [processwire/processwire-issues#1427]
Seems that since https://github.com/processwire/processwire/commit/db542b9ba2e1a17ff10ac4db43fbda985d2ea5b8 MarkupRSS has generated invalid markup in case description field has characters that get converted into entities.

I'm currently dealing with a case where description is "Viimeisimmät päivitykset" (latest updates) — this used to work in earlier versions, but now `ä` is converted to `&auml;` and the feed no longer shows up:

```
This page contains the following errors:
error on line 6 at column 31: Entity 'auml' not defined
Below is a rendering of the page up to the first error.
```

Technically this should be easy to solve by wrapping feed description with CDATA-element, but according to W3C validator that _could_ be a bad idea:

```
This feed is valid, but interoperability with the widest range of feed readers could be improved by implementing the following recommendations.

line 6, column 60: description should not contain HTML: &auml; (2 occurrences) [help]
```

I don't really use RSS myself, so no idea if that's a real concern. At the very least I would assume it to be better than generating invalid markup, which at least in my case means that the feed doesn't show up at all (in browser) :)

**Comment by teppokoivula** [comment]
Afterthought: is htmlentities() really required here, or would htmlspecialchars() suffice? Related discussion: https://stackoverflow.com/questions/2822774/is-htmlentities-sufficient-for-creating-xml-safe-values.

Seems to me that there's actually no need to encode _every character with entity equivalent_, and as such htmlspecialchars() + CDATA would seem like a good combination for the feed description. Item descriptions are, apparently, already all good with current behaviour.

**Comment by ryancramerdesign** [comment]
Thanks @teppokoivula I've pushed a fix for this, and completed some other updates that were in progress while in it. The htmlentities() isn't required here, the htmlspecialchars() should be fine so I switched to that, as well as now have it using the ENT_XML1 flag in the htmlspecialchars() call. The RSS feed validator is now also telling me it prefers hexadecimal encoded entities for some reason (rather than named or decimal entities) so I've added that as well. I tested with the example you gave me, but was wondering, if you get a chance, can you see if these updates seem to resolve the issue from there also? Thanks

**Comment by teppokoivula** [comment]
Thanks Ryan — fix works fine here!
