### ISSUE TITLE
Selector "(status=hidden), (status=unpublished)" not working as expected

### ISSUE THREAD

**Issue by CalleRosa40** [processwire/processwire-issues#1428]
I want to select all hidden and unpublished pages using one selector. I tried

`$pArr = pages("abc")->children("(status=hidden), (status=unpublished)");
// Returns nothing, althoug there definitely are hidden and unpublished children under abc`

and

`$pArr = pages("abc")->children("status=hidden|unpublished");
// Gives notice and 2 warnings (see below) and does not return any pages either`

Notice: Array to string conversion in C:\xampp\htdocs\xxx\wire\core\PageFinder.php on line 423

Warning: Illegal offset type in isset or empty in C:\xampp\htdocs\xxx\wire\core\PageFinder.php on line 426

Warning: Invalid argument supplied for foreach() in C:\xampp\htdocs\xxx\site\assets\cache\FileCompiler\site\templates\psdb_func.php on line 174

Can anyone confirm this behavior?

### Setup/Environment
<strong>Server Details</strong>

|Software|Version|
|------:|:-------|
|ProcessWire|3.0.165|
|PHP|7.3.25|
|Webserver|Apache/2.4.46 (Win64) OpenSSL/1.1.1h |
|MySQL Server|5.5.5-10.4.17-MariaDB|
|MySQL Client|mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $|
<details><summary><strong>Server Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|allow_url_fopen|1|
|max_execution_time|120 (changeable)|
|max_input_nesting_level|64|
|max_input_time|60|
|max_input_vars|1000|
|memory_limit|512M|
|post_max_size|40M|
|upload_max_filesize|40M|
|xdebug||
|xdebug.max_nesting_level||
|mod_rewrite|1|
|mod_security|*confirmed off|
|EXIF Support|1|
|FreeType|1|
</details><details><summary><strong>GD Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|Version|bundled (2.1.0 compatible)|
|GIF|1|
|JPG|1|
|PNG|1|
|WebP|1|
</details><details><summary><strong>Module Details</strong></summary>

|Module ClassName|Version|
|------:|:-------|
|AdminOnSteroids|2.0.21|
|CronjobDatabaseBackup|1.2.4|
|DebugModeSwitch|1.0.0|
|EmailObfuscation|1.2.5|
|FormBuilder|0.4.5|
|ImageFileDependencies|0.0.3|
|InputfieldFormBuilderFile|0.0.2|
|MarkupSitemapXML|1.1.0|
|ProcessDatabaseBackups|0.0.5|
|ProcessFormBuilder|0.4.5|
|ProcessHannaCode|0.3.0|
|ProcessJumplinks|1.5.61|
|ProcessTracyAdminer|1.1.3|
|ProcessWireUpgrade|0.1.1|
|ProcessWireUpgradeCheck|0.0.9|
|SearchEngine|0.30.0|
|TextformatterHannaCode|0.3.0|
|TextformatterSmartypantsGerman|0.0.1|
|TracyDebugger|4.22.5|
|TextformatterVideoEmbed|1.1.1|
</details>

**Comment by ryancramerdesign** [comment]
Thanks @CalleRosa40 the status property is a bitmask value with flags in an ascending order and what you will want to use to perform that match is this: `status>=hidden, status<trash` — that would match all hidden or unpublished pages. 

Currently PW does not support OR conditions for the native selector properties: status, include, check_access, limit, start, sort, get_total. I have added an exception that clarifies that, so that it will give you an error message saying it doesn't support it rather than silently failing or producing a PHP notice. 

While OR conditions don't make sense for most of the properties I mentioned above, I do really like the idea of being able to do `status=hidden|unpublished` so I've added a `@todo` to add support for that a little later when possible. 

We won't be able to support a selector like `(status=hidden), (status=unpublished)` on its own  for technical reasons unique to the 'status' property. However, it would work even now if you use `include=all, (status=hidden), (status=unpublished)` but this isn't an efficient use of OR-groups because they launch separate find operations for each (group) before merging them together, so I wouldn't recommend using them for matching something simple like this.

**Comment by adrianbj** [comment]
Just as a follow up, if you want to match pages that are both hidden and unpublished, you can do:
```
$hidden_unPublished = Page::statusUnpublished + Page::statusHidden;
$page->children("status>=$hidden_unPublished, status<trash");
```
Not sure if that is the most efficient option or not. @ryancramerdesign ?

**Comment by ryancramerdesign** [comment]
@adrianbj For both hidden and unpublished that seems like a good way to me. You could also do this: 
~~~~~
$page->children('status=hidden, status=unpublished');
~~~~~

The `status<trash` would not be necessary in either case, as presumably `$page` is not in the trash. But if you were doing a `$pages->find()` then you would want to add the `status<trash` if you wanted to exclude hidden+unpublished pages in the trash.

**Comment by adrianbj** [comment]
> $page->children('status=hidden, status=unpublished');

<s>That doesn't work though - it doesn't return any children.</s>

**Comment by adrianbj** [comment]
Sorry, my mistake, that does work - for some reason I thought I'd tried that, but I'd tried the `(status=hidden), (status=unpublished)` as per the OP.

**Comment by tiefenb** [comment]
@ryancramerdesign After this fix I get an exception for an already working selector I used:


```php
 $moreRecommendedJobs = $page->siblings("job_group={$page->job_group}, job_office_country={$page->job_office_country}, limit=10", false);

$moreJobs = [];
 if ($moreRecommendedJobs->count() < 10) {
     // filter already selected jobs
    $excludeIds = $moreRecommendedJobs->implode("|", "id");
     $limit = 10 - $moreRecommendedJobs->count();
// throws an exception now:
    $moreJobs = $page->siblings("id!=$excludeIds, sort=job_group|job_office_country, limit=$limit", false);
     $moreRecommendedJobs->add($moreJobs);
 }
````

**Comment by adrianbj** [comment]
Maybe something else related that needs to be investigated: https://processwire.com/talk/topic/26045-selectors-problem-or-condition-with-processwire-core-dev-update-to-30183-not-recognizing-pipe-separators/

**Comment by netcarver** [comment]
Re-opening due to @tiefenb Markus' post above.

**Comment by ryancramerdesign** [comment]
@tiefenb There was an error with what I added for this before, but it was fixed shortly after, so you shouldn't see that error anymore. But I wanted to mention, shouldn't your selector with the `sort` be this instead: `sort=job_group, sort=job_office_country`  ?  I don't remember adding support for `sort=a|b`, but I tested it out (just in case I'm forgetting something) and interestingly it works if you reverse the order, i.e. `b|a` instead of `a|b`, so maybe it would be easy to support with a small addition.

**Comment by tiefenb** [comment]
@ryancramerdesign thanks, works again!

I guess I read about sort=a|b|etc in the forum by searching in google: https://www.google.com/search?q=processwire+multiple+sort&rlz=1C5CHFA_enAT951AT951&oq=processwire+multiple+sort&aqs=chrome..69i57j69i64.6168j0j7&sourceid=chrome&ie=UTF-8

And tried it only once on this place.

**Comment by ryancramerdesign** [comment]
Closing this since support has been added for `status=unpubished|hidden` and `sort=a|b`

**Comment by iamwebrocker** [comment]
Sorry to re-open this, in the current master (3.0.184) I have the same warning when using latest listerPro (1.1.3):
![Bildschirmfoto 2021-09-23 um 12 08 35](https://user-images.githubusercontent.com/1223080/134489881-7835a87c-7db5-451b-923f-60a183a4b24e.png)

**Comment by ryancramerdesign** [comment]
Hi Tom, this feature was added in 3.0.185 (current dev branch). Prior
versions don't support that.

**Comment by iamwebrocker** [comment]
ah. thanks again, Ryan
