### ISSUE TITLE
TextformatterMarkdownExtra: flavorRCD

### ISSUE THREAD

**Issue by mikerockett** [processwire/processwire-issues#143]
### Short description of the issue

`TextformatterMarkdownExtra::flavorRCD` doesn't appear to be able to be set in the module config. I'd like to be able to set external `href`s to open in a new tab.

### Suggestion for a possible fix

The option should be added into the configuration, unless I'm misunderstanding something.

We could also make use of [ParsedownExtraPlugin](https://github.com/tovic/parsedown-extra-plugin), which is more configurable. If you're not up to including this, then I'm happy to create a new module for it.

The plugin utilises this for configuring external links:

```php
$md->links_external_attr = [
    'target' => '_blank',
];
```

We could set the module to add attributes as above.

**Comment by ryancramerdesign** [comment]
The flavorRCD was in there for internal purposes for use with core Inputfield description/notes properties in certain situations. But that's been moved to use the `$sanitizer->entitiesMarkdown()` method and options instead. The flavorRCD is left it for backwards compatibility, just in case anything from the past is referring to it, even if we aren't. I'd probably avoid using it if you can. I'll go ahead and add a deprecated tag to it just to make that more clear in case anyone else comes across it in the code. The ParsedownExtraPlugin you mentioned looks pretty fantastic (bookmarked, thanks). Still, I don't think it's good to add more 3rd party libraries to the core unless for something that's going to be used by the majority of users, or needed internally by the core. Otherwise it's probably best for 3rd party module territory.

**Comment by mikerockett** [comment]
Thanks for the clarification - makes sense indeed. I'll make a Textformatter for this - I'm sure there are Markdown lovers who would be happy with it.

**Comment by mikerockett** [comment]
I have gone ahead and pushed a new textformatter: https://github.com/rockettpw/textformatter-parsedownextraplugin
