### ISSUE TITLE
Inputfield password requirements are not stored in the database on new install

### ISSUE THREAD

**Issue by juergenweb** [processwire/processwire-issues#1430]
### Problem getting password requirements on new install 

On new install of PW, the requirements of the password field are not stored in the database. I have created a module which grabs the requirements from the 'pass' password field. 
Unfortunately on a new install, this data is not stored in the database.
I had to go directly to the pass field and have to save this field to store the requirements to the database. This should not be the default behavior.

If I save a new user including a password via API, I get the following error message:

Warning: in_array() expects parameter 2 to be array, null given in C:\xampp\htdocs\seite3\wire\modules\Inputfield\InputfieldPassword\InputfieldPassword.module on line 398

### Expected behavior

The default settings for the requirements should be stored in the DB by default without the extra saving of the field.

### Actual behavior

This is what is stored in the dabase inside the data field of the password field pass on a new install:

`{"collapsed":1,"size":50,"maxlength":128}`

After saving the field manually the requirements and other data are stored in the database:

`{"collapsed":1,"size":50,"maxlength":128,"requirements":["letter","digit"],"complexifyBanMode":"loose","complexifyFactor":0.7,"minlength":6,"requireOld":0,"unmask":0}`

### Steps to reproduce the issue

1. Install a new PW
2. Check DB entries for password field
3. Save the password field in the backend and check the DB entries once more

### Setup/Environment

* ProcessWire version: 3.0.183
* (Optional) PHP version:  7.4

**Comment by ryancramerdesign** [comment]
@juergenweb I think I need to better understand the case here because many Inputfield module defaults are not stored in PW's default DB or site profiles unless/until the user modifies and saves them. This is what enables a module to change and optimize its defaults for new and existing installations over time. The 2nd JSON string you indicated consists just of the module defaults, so they wouldn't be expected in the DB until you committed them (by configuring and saving the field in the admin). All of the defaults are set in the constructor of an Inputfield module and should only change if overridden by configuration. This is the case with many Inputfield modules, but also field and module configuration in general. 

Either way, it sounds like there's an error message here that needs further investigation. That error you mentioned indicates the 'requirements' value is null when it is expected to be an array. The value for 'requirements' is set to an array in the InputfieldPassword constructor, so it must have been changed to null by something afterwards. Though what's more strange is that adding a user via the API should not involve the InputfieldPassword module at all, since it would only be used for interactive input, and not API use. Are there any other 3rd party modules involved here? Would it be possible for you post the entire API code you are using? Thanks.

**Comment by juergenweb** [comment]
Hello Ryan,

Please forget this error ticket - it was a logical mistake of mine, but I want to tell you what was going on.

I have created a registration form which adds a new user including password.
Therefore I have created a validator which should check, if the password entered meets the requirements of the password field. With this little piece of code I have tried to get the password requirements:

`$passwordField = wire('fields')->get(‚pass);
$requirements = $passwordField->requirements;`

My mistake was that I have grabed the requirement values directly from the DB, but they are not actually there if no one has saved the password field.
So requirements are not found as property and therefore NULL. This code works only if someone saves the requirements to the DB (not on a new install).

So changing the code to take the default requirement values from the InputfieldPassword instead from the password field ‚pass‘ itself solves the problem.

`if(!$passwordField->requirements){
         $requirements = wire('modules')->get('InputfieldPassword')->requirements;      
} else {
         $requirements = $passwordField->requirements;     
  }
`

Now the error message is gone and everything works fine. So you can close this issue after reading.

Thanks and best regards

Jürgen

**Comment by ryancramerdesign** [comment]
@juergenweb Thanks for the additional info, your solution looks like a good one to me, glad everything is working now.
