### ISSUE TITLE
HTMLPurifier.standalone is overly complex and contains errors

### ISSUE THREAD

**Issue by jmartsch** [processwire/processwire-issues#1434]
I ran an automated test on https://www.codefactor.io/ and there are several issues.
It complains about the overall complexity of code and other things.
For example
* Function get_magic_quotes_gpc() has been deprecated 
* empty ELSEIF statements
* Variable assignment found within a condition. Did you mean to do a comparison ? There are much of these.
![image](https://user-images.githubusercontent.com/551551/131460610-d03eb24a-c145-44fe-9eed-5ab350bd9a36.png)
* many TODOs

There is much unreachable code
![image](https://user-images.githubusercontent.com/551551/131461645-0d8c87b0-0413-4747-b002-85233fb15de0.png)

Maybe this class can be optimized or refactored?

**Comment by ryancramerdesign** [comment]
@jmartsch HTMLPurifier is a 3rd party library and very good at what it does. It might be detected as overly complex because the standalone version merges much of the regular version into one file. I prefer fewer files for this library even if another tool detects it as complex. 

An empty else statement or variable assignment within an if are not errors and relatively common, those are inspections that I would ignore here. A get_magic_quotes_gpc call is not a problem if the caller checks for its existence or PHP version before calling it, which HTMLPurifier does. Code after a break or return statement is also not an error, but picked up by an inspection just to let the developer know in case they didn't intend it. Very often such code is for developer reference, future use, or documentation purposes, and I suspect that's the case here as well. 

I'll close this since I don't code for or maintain HTMLPurifier. But if you feel any of these are still a concern, the author of the library also has a repo for this on GitHub located here: https://github.com/ezyang/htmlpurifier
