### ISSUE TITLE
findJoin returns empty for images fields

### ISSUE THREAD

**Issue by Notanotherdotcom** [processwire/processwire-issues#1436]
### Short description of the issue

When using findJoin and specifying an images field (photos in my example) it gets the field object but it's empty even though there should be files in it

### Expected behavior

I would expect it to return the files :)

### Actual behavior

It returns an empty object with a count of zero

### Optional: Screenshots/Links that demonstrate the issue

Image removed due to showing which website it was for

### Setup/Environment

* ProcessWire version: 3.0.184
* (Optional) PHP version: 7.4

**Comment by ryancramerdesign** [comment]
Thanks @Notanotherdotcom good find, I've pushed a fix for this issue.

**Comment by Notanotherdotcom** [comment]
Hi Ryan,

So now it just doesn't return the photos field in the autoJoin data in my case - is that because it's not a type that works with findJoin? It's fine if not as it still displays them the "normal" way presumably by fetching them separately when required.

**Comment by ryancramerdesign** [comment]
Hi Pete, that's right that file fields don't support autojoin. Technically
it's possible in some instances. But since it depends on a lot of variables
(like how many files, what columns are in use, how many bytes they add up,
whether custom fields are in use, what mysql max concat chars is configured
as) it's far from reliable so I thought it best not to support autojoin for
these.

**Comment by Notanotherdotcom** [comment]
Thanks Ryan - just wanted to make sure :)
