### ISSUE TITLE
Checkbox fields are missing the field name link of hover of collapse toggle

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#144]
### Short description of the issue

Checkbox fields are missing the field name link of hover of collapse toggle

### Expected behavior

There should be a label for the name of the field appear when hovering on the toggle open/close arrow

### Actual behavior

There isn't one :)

### Optional: Screenshots/Links that demonstrate the issue

You can see why here - note the empty "for":
![screen shot 2016-12-30 at 7 48 14 am](https://cloud.githubusercontent.com/assets/871211/21567850/646cf7e4-ce64-11e6-89c2-4a40698a4e96.png)

That should read:
```
<label class="InputfieldHeader InputfieldStateToggle" for="dbBackup">Database Backup
```

That results in `text` on this line being empty:

https://github.com/processwire/processwire/blob/d935e9b6995124d76e6fda17fd47ab46dc4d3a3c/wire/templates-admin/scripts/inputfields.js#L1017 

### Setup/Environment

* ProcessWire version: 3.0.46

**Comment by ryancramerdesign** [comment]
Checkbox fields use the `Inputfield::skipLabelFor` setting. They have their own separate `<label>` that surrounds the checkbox + label combination, and that's the one that has the "for" attribute instead. Also, no InputfieldHeader is shown on checkbox fields that lack a description property, so that little debug mode hover tweak doesn't apply to single checkbox fields, or any field using the skipLabelFor option. There are other cases where it's not supported either. This is just one debug mode tweaks that's there in many cases, but not always going to be present.

**Comment by adrianbj** [comment]
> This is just one debug mode tweaks that's there in many cases, but not always going to be present.

That seems a shame - it's a handy dev feature. I know it's not going to be high on your priority list, but perhaps the method for populating the hover could be changed to pull the field name from somewhere else?
