### ISSUE TITLE
Pagination broken on latest dev (3.0185) with multilingual site

### ISSUE THREAD

**Issue by jacmaes** [processwire/processwire-issues#1447]
This bug report is not going to be very clear as there's nothing in the logs nor do I see anything with debug turned on. 

I have multilingual support enabled. When upgrading from 3.0.179, I get a page not found on "pagina2" (Spanish version), and on any subsequent pages. 

Should I install Tracy to try to pinpoint the issue, even though I've never really used it?

**Comment by berlin1066** [comment]
As described in the link below I have a similar problem:

I created a Real Estate CRM that runs with 4 languages. All my clients are okay with PW 3.0.184 but since I updated one to 3.0.185 the multi-language support for pagination names stopped working. 

Since 2 of those languages Español and Catalá use "pagina" instead of "page" for pagination, the system wasn't recognizing it and reset to "page2" without the get vars of the search query.

I fixed it setting all to "page" but I need it working as it was.

Here the fixed example and also a working example with PW 3.0.184 of a new client I'm implementing these days.

Pagination working with "page" for all languages:
https://www.zonahabitable.com/inmuebles/?buscar=1&orden=&operacion=1247&pais=1197&provincias[]=1204&preciomin=&preciomax=&habitaciones=&banios=&metros=&layout=list 

Pagination working with pagina and page for different languages:
https://web.brosrealestate.com/ca/immobles/?buscar=1&layout=list&operacion=venda&tipo=1117&provincia=&localidad=

https://web.brosrealestate.com/ca/immobles/pagina2?buscar=1&orden=&operacion=&pais=0&provincia=0&localidad=0&tipo=1117&preciomin=&preciomax=&habitaciones=&banios=&metros=&layout=list
-------
Post in PW Forum.
https://processwire.com/talk/topic/26233-problem-with-multilanguage-pagination-names-after-update-to-pw-30185

**Comment by berlin1066** [comment]
Update: I downgraded to PW 3.0.184 and the LanguageSupportPageNames.module file went from version 1.3 to 1.0 and it works fine again.

**Comment by ffoerster** [comment]
+1 

Having the same issue with multilingual pagination "page" names on 3.0.187. Going back to the default "page" fixes it for (me) now.

**Comment by csaggo** [comment]
+1
i wanted to mention that pagination is also not working in the page/lister module in backend if you are set to another (translated) language then english.

**Comment by jmartsch** [comment]
Hey folks, pls give a thumbs up on the original issue instead of writing +1, because then Ryan would see that this issue has big interest.

I also got the problem with a multilang page. The default language is german and I set the pagination prefix to "seite" which is german for "page". It worked before with core version 3.0.184. After upgrading to 3.0.187 if I am on the german page and request the URL https://www.p-jentschura.com/seite2 then a 404 is returned, instead of the previously working paginated page.
However if I use the prefix of the english pagination https://www.p-jentschura.com/page2, then a page is delivered.

**Comment by szabeszg** [comment]
> ...because then Ryan would see that this issue has big interest.

Ideally, this method is for feature requests only.

A bug like this should definitely be addressed before the next stable release, I think, no matter how many likes it gets.

**Comment by jmartsch** [comment]
Well yes, but maybe it can help setting priorities with the thumbs up. Anyways, thanks for upvoting

**Comment by ryancramerdesign** [comment]
Are you guys still running into this issue? I think all the multi-language/pagination related issues have been fixed, but let me know if any are still reproducible on the current dev branch. Thanks.

**Comment by tbba** [comment]
Actually, I run into kind of this on a specific site a few days ago:
https://www.deine-lakaien.com/de/blog/

Languages Support - Page Names

    the default language is GERMAN and the page number name "seite"
    The 2nd language is ENGLISH and the page number name is the default "page".

Now, pagination does not work. Changing all names to "page" makes it working.

ProcessWire dev | 3.0.189

**Comment by jmartsch** [comment]
The problem still persists. 
I have german as the default language.
Here you can see my settings and the error:
![image](https://user-images.githubusercontent.com/551551/142723736-9a9deeca-f81d-45ea-9288-9691cbc90fc4.png)

On my local development site with core 3.0.189 I have this button "Mehr laden (load more)" which leds to a 404 error if I use the german page number name "seite".

![image](https://user-images.githubusercontent.com/551551/142723762-97686226-8260-42ac-8b18-1d9732a650b6.png)

Chrome Dev Tools shows this:
![image](https://user-images.githubusercontent.com/551551/142723827-abf13948-00c6-4a3e-8dbf-569b7b15dc8b.png)

If I change the link of the button to use "page" instead of "seite" it works.

**Comment by tbba** [comment]
What both examples (thanks @jmartsch for the more in-depth example) have in common, is that the first (default) language is German, not English.

**Comment by jacmaes** [comment]
Same thing on my end: Spanish is the default language, and English second.

**Comment by snobjorn** [comment]
I have the same problem with my sites where I have LanguageSupport installed, and Norwegian as the default language.

I have the latest dev installed as of today (Dec 1, 2021).

**Comment by ryancramerdesign** [comment]
Thanks guys, I was able to duplicate that with the instructions above and have pushed a fix.

**Comment by jmartsch** [comment]
Will test it in the next few days. Thank you Ryan.

**Comment by tbba** [comment]
Works now:
https://www.deine-lakaien.com/de/blog/seite4
Thank you!

**Comment by jacmaes** [comment]
Works for me now too. Great. Closing this issue then.

**Comment by jmartsch** [comment]
Issue is also fixed for me
