### ISSUE TITLE
Xdebug makes processwire crash 

### ISSUE THREAD

**Issue by daymickcorr** [processwire/processwire-issues#1449]
### Short description of the issue

When I enable xdebug and call processwire index.php apache crashes, apache does not crash when calling other php scripts 

I am recieving nothing in apache, php, processwire, xdebug logs, I have messages in the event viewer not giving much information. 

### Expected behavior

processwire should bootstrap

### Actual behavior

apache crashes 

### Optional: Screenshots/Links that demonstrate the issue

This site can’t be reached The connection was reset.

ERR_CONNECTION_RESET

### Steps to reproduce the issue
on windows 

1. Install latest xampp 

2. Install latest processwire trough composer in C:\xampp\htdocs

3. In php.ini enable xdebug

[xdebug]
zend_extension=xdebug

4. restart apache 

5. access localhost/ or localhost/index.php 

### Setup/Environment

OS: Windows 10 Pro 21H1 
ProcessWire version: 3.0.184
PHP version: 8.0.11
Xampp version: 3.3.0
Xdebug version: 3.1.0

Event Logs errors:

Faulting application name: httpd.exe, version: 2.4.49.0, time stamp: 0x613db94b
Faulting module name: php_xdebug.dll, version: 3.1.0.1, time stamp: 0x615acc41
Exception code: 0xc0000005
Fault offset: 0x000000000000c840
Faulting process id: 0x1c64
Faulting application start time: 0x01d7bc54236e9a3a
Faulting application path: C:\xampp\apache\bin\httpd.exe
Faulting module path: C:\xampp\php\ext\php_xdebug.dll
Report Id: c7c6f402-5e26-43e7-9889-9fdb083e6b87
Faulting package full name: 
Faulting package-relative application ID: 

Fault bucket 1228007912784236086, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: httpd.exe
P2: 2.4.49.0
P3: 613db94b
P4: php_xdebug.dll
P5: 3.1.0.1
P6: 615acc41
P7: c0000005
P8: 000000000000c840
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7C5E.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7EE0.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7F00.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7F36.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7F56.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_httpd.exe_a05196145378ba8e1d43a1620f020b557390_96aac23f_ee628fb2-ce2e-4a13-8898-56071598fc3f

Analysis symbol: 
Rechecking for solution: 0
Report Id: c7c6f402-5e26-43e7-9889-9fdb083e6b87
Report Status: 268435456
Hashed bucket: 8d55a6742d8c73be810ac2b0bedf8e36
Cab Guid: 0

**Comment by teppokoivula** [comment]
It seems that xdebug issues on Windows are — or at least have been — relatively common. Technically ProcessWire doesn't do anything that should make a debugger crash, it's just that in most cases xdebug issues appear while debugging more complex application or library code (such as ProcessWire).

I would start by digging into some of the threads discussing these (such as https://stackoverflow.com/questions/1904138/cant-get-xdebug-to-work-on-windows-7), even if many of the ones you can find from SO are indeed a bit old.

> Like others have said, you need to match your xdebug version with your php version.

This, for one, seems to be a relatively common issues with XAMPP and xdebug: instead of `zend_extension=xdebug` you could try pointing it directly to the (correct) xdebug dll file for your PHP version.

**Comment by daymickcorr** [comment]
Thank you for the feedback!
