### ISSUE TITLE
Pagination doesn't work when combining multiple finds

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-issues#1477]
I'm not sure if this is a bug or just some sort of limitation with ProcessWire...

Let's say I do this:

```
$my_pages = $pages->find("title=x|y,limit=20");
$pagination = $my_pages->renderPager();
```

Pagination will work correctly.

Now let's say I do this (which I would do specifically to have results from $my_pages_1 to be first, then $my_pages_2 to be next):

```
$my_pages_1 = $pages->find("title=x");
$my_pages_2 = $pages->find("title=y");
$my_pages_combined = $my_pages_1->add($my_pages_2)->find("limit=20");
$pagination = $my_pages_combined->renderPager();
```

Pagination in this scenario will not work.

This was touched upon in this thread: https://processwire.com/talk/topic/21970-pages-find-get-by-id-and-maintain-order/

**Comment by ryancramerdesign** [comment]
@jlahijani Pagination is currently a function of the database. In your example, you are attempting to paginate things that are already loaded from the database and already in memory, so native pagination would no longer apply. Taking your example literally, here's how you'd want to do it instead: 
~~~~~
$my_pages = $pages->find("title=x|y, limit=20"); 
~~~~~
If you have a case where you still need to paginate in memory, note that there's no longer a  benefit to doing it (instead largely drawbacks), but here's how you could:
~~~~~
$limit = 20;
$start = ($input->pageNum - 1) * $limit;

$my_pages_paginated = $my_pages_combined
  ->slice($start, $limit)
  ->setStart($start)
  ->setLimit($limit)
  ->setTotal($my_pages_combined->count());

$pagination = $my_pages_paginated->renderPager();
~~~~~
Since the pages would already be loaded in memory, I'd suggest a JS-based pagination instead, otherwise you'll be reloading all those pages in memory on every single pagination, essentially magnifying the drawbacks to the server times number of paginations.

**Comment by jlahijani** [comment]
Thanks for the explanation and example @ryancramerdesign .

The bigger issue here is not pagination (sorry if I didn't make that more clear), but really being able to do this:
`$pages->find("id=2|1|3")`

... and have it return results **specifically** in that order (page 2, then page 1, then page 3).  Putting in a `sort` in the selector above won't yield the results we want in this situation.

Right now there's no way to do that with selectors (as far as I know), which is why I had to use 2 queries and which leads to the pagination issue I described.

I believe this question has come up a couple times in the forums and elsewhere.

Thinking this through further, I think this is a special situation, meaning if someone wanted to use `$pages->find` as I described, they would **have** to know the IDs of the pages beforehand and the selector would have to be just `id=` (and combined with a special `sort` option) or else it wouldn't make sense.

Is that possible?  Or is what I'm describing already possible in ProcessWire?

**Comment by ryancramerdesign** [comment]
@jlahijani There isn't anything like that at present. Though it sounds useful to me. Regular SQL doesn't have an option for this (as far as I know) but MySQL supports `ORDER BY FIELD(id, 2, 1, 3)` so I have added that support to the PageFinder. If you use this selector with the latest commit, it should work: `id.sort=2|1|3` (so long as you don't specify another `sort=` in the selector to override it.)

**Comment by jlahijani** [comment]
@ryancramerdesign This is absolutely amazing.  I can literally drop ElasticSearch as a dependency now on a project where, from my understanding based on its development history, it was mainly being utilized to overcome the limitation with sorting IDs.
