### ISSUE TITLE
Updating to 3.0.184 adds title field to custom field to image template

### ISSUE THREAD

**Issue by Klenkes** [processwire/processwire-issues#1501]
### Short description of the issue

An update from i.e. 3.0.145 to 3.0.184 added the standard title field to my custom template for an image field, if it didn't exist before. This is bad, because the title field is required and you receive errors for all images when saving.

### Expected behavior

No title field is added.

### Actual behavior

Title field is added which leads to errors.

**Comment by ryancramerdesign** [comment]
@Klenkes This happens because your 'title' field has the 'global' option checked, which means it gets automatically added to any templates. I've pushed an update which applies the 'noGlobal' option to newly created field/image templates, which should prevent that from happening. But for existing instances, I think you'd need to turn off the global checkbox on your title field. Or you could always edit the template, check the 'noGlobal' option and then remove the title field from it.
