### ISSUE TITLE
New File Compiler bug

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#151]
### Short description of the issue
```
$logInstance = new FileLog(wire('config')->paths->logs . $item['log'].'.txt');
```
results in: Fatal error: Call to undefined function wire()

### Expected behavior

proper adding of \ProcessWire\ to wire call so it looks like:
```
$logInstance = new FileLog(\ProcessWire\wire('config')->paths->logs . $item['log'].'.txt');
```

### Actual behavior

It's not getting compiled at all

### Setup/Environment

* ProcessWire version: 3.0.48

**Comment by adrianbj** [comment]
PS - this same line of code works just fine on 3.0.47, but I haven't tested which of the recent changes to the compiler broke it.

**Comment by trk** [comment]
After i update processwire (before 3.0.48 release) from this https://github.com/processwire/processwire/commit/c0ef1aea92cc1f2eb98efc3cdd1da96c675a1cc5 commit, started to get Fatal error: Call to undefined function wire(). If i change my FileCompiler with old 3.0.47 version, everything working.

After install 3.0.48, i didn't get same error, but before this update i can use template files without adding namespace ProcessWire; now i need to add namespace ProcessWire; to all files in my tempates folder.

**Comment by ryancramerdesign** [comment]
@adrianbj Thanks I've pushed a fix for this one. Looks like it ran into issues on lines that had both a PW classname and function call appearing on the same line. 

@trk I can't duplicate that one so far. My test environments all have non-namespace template files that get compiled. Meaning, you shouldn't have to add a namespace to your template files unless you want to. Try grabbing the latest commit just in case you were seeing the same issue as Adrian. Otherwise, I might need to get a look at one of those template files if possible.

**Comment by adrianbj** [comment]
Thanks @ryancramerdesign - I can confirm that fixes the issue I was having, so I'll close this.
