### ISSUE TITLE
Can add but not remove permanent field from template

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-issues#1526]
I accidentally added 'pass', 'process' and 'permissions' field to a template.  When I try to delete them from the template, ProcessWire won't let me do it because they are permanently flagged fields.

I think I did this accidentally a year or so ago and worked around it somehow (hacked something), but it's been a while and I feel like this is really a bug now that it's happened more than once to me.

**Comment by jlahijani** [comment]
(I worked around this for now by disabling the check of 'isFieldNotRemoveable' in the appropriate place.)

**Comment by adrianbj** [comment]
Definitely bit me more than once :)

**Comment by elabx** [comment]
Has happened to me too!

**Comment by BernhardBaumrock** [comment]
Where is the problem?

* create field "tmp" and check "permanent"
* add it to a template (eg "home")
* try to remove it --> fails
* edit field, remove "permanent" flag
* edit template, remove "tmp" field --> works

Would you expect it to work differently?

BTW:
```
$rockmigrations->removeFieldFromTemplate('tmp', 'home');
```

**Comment by adrianbj** [comment]
I think the biggest part of the problem is that you get this error even if you haven't saved the changes to the template. Same thing happens for non-permanent fields - if you add accidentally and then click the trash icon to remove it, you still get asked whether you want to remove it or not, even though it hasn't really been added yet - because the template wasn't saved.

I think once you save the template, then it's fair to have to expect to deal with changing the permanent flag (off, and then back on again).

**Comment by BernhardBaumrock** [comment]
Ah! Now I get it :) I understood that he added a field a year ago and now wants to remove it...

Ok so the process is this:
* create field "tmp", set flag "permanent"
* add field "tmp" to template "home", but DO NOT SAVE
* click on "trash" of field "tmp"
* now save the template

2 problems:
--> you'll need to confirm deletion of "tmp" (which is already wrong aka bug)
--> you'll not be able to remove "tmp" and the field will be part of "home" (also a bug)

Thx :)

**Comment by jlahijani** [comment]
If you add a field like the 'process' field accidentally, to remove it, you have to disable both 'Permanent' AND 'System' setting for that field.  If you just uncheck 'Permanent' and save, it won't work.

While I agree this is native functionality and it's working as intended, it does feel like you get trapped if you make a mistake.  It's not an issue for me since I can work around it, but it would be maddening to someone not as experienced.

**Comment by ryancramerdesign** [comment]
@jlahijani The system fields mentioned shouldn't be addable to a template unless you've got `$config->advanced=true`, and that is a mode intended for core or module development. In that mode there's plenty of things you can do that aren't easily reversible, which is why we have it hidden behind an advanced config setting. The issue that @adrianbj brought up seems like it can be improved though. I have updated the behavior for that so that it just removes the item rather than marking it for deletion when it's not an item that was already selected when the output was rendered. That way you can click to add a field and remove it without having it mark for deletion or go through any confirmation. But if it's a field that is already on the template then it'll mark for deletion and confirm, etc.

**Comment by jlahijani** [comment]
Thanks Ryan.  I always use advanced mode, so I'll be more careful.
