### ISSUE TITLE
Invalid textdomain when template files starts with "-" character

### ISSUE THREAD

**Issue by andreasottosson** [processwire/processwire-issues#1543]
### Short description of the issue

Ran into this when a customer had named some partial templates starting with a "-" character. For example `-normal.header.php`, when this gets turned into a textdomain in `/wire/modules/LanguageSupport/ProcessLanguageTranslator.module` it incorrectly picks up the textdomain from the filename, my assumption because there are now three "---" characters in a row. I solved this by just renaming the files to start with _ instead but perhaps this should be looked at anyway?

### Expected behavior

`ProcessLanguageTranslator.module` should load the file `-normal.header.php` from this textdomain `site--templates---normal-header-php`

### Actual behavior

"Textdomain not found" displayed in admin UI. Following error in logs, `2022-03-11 16:26:22	admin	http://localhost:8000/processwire/setup/language-translator/edit/?language_id=1389&textdomain=site--templates---normal-header-php	Unable to load textdomain (in /wire/modules/LanguageSupport/ProcessLanguageTranslator.module line 510)`

### Steps to reproduce the issue

1. Rename a template to start with a "-" character.
2. Install a second language on your site
3. Try to load this template for translation

### Setup/Environment

* ProcessWire version: 3.0.184
* (Optional) PHP version: 7.4
* (Optional) MySQL version: 5.7
* (Optional) Any 3rd party modules that are installed and could be related to the issue:

**Comment by ryancramerdesign** [comment]
Thanks @andreasottosson I've had a look and I don't think we can support filenames beginning with a `-` because there wouldn't be any way for the textdomain to differentiate between `/-value/` and `/value-/` and it would also create other potential filename-to-textdomain translation issues. Such filenames are also difficult to work with on the unix file system (at least) because the `-` can be confused as the beginning of a command line argument, so escaping rules come into play. But I'm glad you found this, as ideally the ProcessLanguageTranslator module should ignore such filenames, so I have updated that module so that it will no longer include them in the selectable list for translation files. 

Note that using an underscore at the beginning of your template include files like `_header.php` is the standard PW recognizes for include files supporting other template files, as it won't pick them up as page template files, but they are translatable, etc. For regular template files that map to templates in the system, it's best that they start with a letter (a-z).

**Comment by matjazpotocnik** [comment]
@andreasottosson please could you check this and close the issue if done?
