### ISSUE TITLE
Quetion: how to auto-format code to PW Coding Style Guide

### ISSUE THREAD

**Issue by ivangretsky** [processwire/processwire-issues#1545]
Good day, @ryancramerdesign !

I remember once you wrote somewhere on the forum in response to a request to move to PSR-2 styling for PW code that you can easily transform PSR-2 formatted code to a PW Coding Style Guide. Could you please explain, how do you do it? 

Thanks!

**Comment by ryancramerdesign** [comment]
@ivangretsky It's been a long time so I don't recall what that method might have been. The differences are probably easy to account for with a few regexp's, maybe that's what I was using at the time, I'm not sure. But isn't this something that most IDEs can do already? PhpStorm for instance lets you configure your code style preferences and it can apply those preferences to existing files, if I recall correctly.  Also, there may not necessarily be a reason to convert existing PSR-2 to PW unless you need it for some reason. it used to be that it was preferred to pull requests, but since I rarely do direct pulls it's not so important there either, as I format for PW code style automatically either way. Here's a link to the code style guide: https://processwire.com/docs/more/coding-style-guide/

**Comment by ivangretsky** [comment]
Thanks. I was thinking maybe there is some PW Coding Style Guide preset for some formatter / IDE with all  those preferences set for me. I am using VS Code, so will try to configure that in this editor. Thanks for reply.
