### ISSUE TITLE
The "Descriptions" label doesn't show up with "Disable multi-language descriptions?" unchecked.

### ISSUE THREAD

**Issue by danielzilli** [processwire/processwire-issues#155]
### Short description of the issue

The "Descriptions" label is missing when you edit an image from a page that made used of the image Fieldtype.

### Expected behavior

The label should be there for consistency. As you have "Tags" when "Use Tags?" is checked.

### Actual behavior

The "Descriptions" label is not there when "Disable multi-language descriptions?" is unchecked. If you check it, the "Description" label appears.

### Steps to reproduce the issue

1. Using a multi-language profile, create a field image type.
2. Add the field to any template with a template file associated. For example: home.
3. Edit the home page, and upload a picture.
4. Mouse over the picture and click Edit. 

### Setup/Environment

* ProcessWire version: 3.0.42
* (Optional) PHP version: 
* (Optional) MySQL version: 
* (Optional) Any 3rd party modules that are installed and could be related to the issue: Nope

**Comment by ryancramerdesign** [comment]
When multi-language is used, the label becomes the language names. This is intended for a couple of reasons. First is that it's the only way to describe the image, so the label is a bit redundant in the first place. While the tags field can appear below it, it always has a label, and doesn't support multi-language. The second reason is subjective–I just didn't like the way it looked, so opted to leave it out so that it didn't look too cluttered. However, one of the items on our 2017 roadmap is to support customizable field for images, so once we are there, labels will always be necessary since the presence of a description field will no longer be a native assumption to file/image fields. So while we don't make any changes to the description presentation now, I think you'll still get the result you are looking for a little later when we've completed the custom field updates for file/image fields.
