### ISSUE TITLE
'You dont have access to edit' in a repeater matrix field with images using latest 3.0.199

### ISSUE THREAD

**Issue by cb2004** [processwire/processwire-issues#1564]
I can add images as a superuser but other users cannot add images. I know there was this issue:

https://github.com/processwire/processwire-issues/issues/1561

I am using the latest dev as of right now and I still get this issue.

**Comment by ryancramerdesign** [comment]
@cb2004 Are you seeing it on an installation without extra modules installed? Or are other page-editor related modules (like ProDrafts) involved?

**Comment by cb2004** [comment]
@ryancramerdesign I do have ProDrafts running yes. Anything I can try other than switching lazy loading to false in config?

**Comment by ryancramerdesign** [comment]
@cb2004 Does the user that sees the "you don't have access to edit" message have a "Publish" button in the editor, or just a "Save Draft" button?

**Comment by cb2004** [comment]
@ryancramerdesign I have taken the setting out of config.php to remove lazy loading and they have Publish and Save + Keep Unpublished. They also have this with the setting in config.php. I am a bit worried about clicking anything when logged in as a user as the images are deleted.

**Comment by ryancramerdesign** [comment]
@cb2004 I think this is likely a ProDrafts issue rather than a core one, because ProDrafts initializes repeaters pretty early in the boot process and it may be too early for lazy loaded repeaters. 

I suspect it may be fixed by just initializing the repeater drafts a bit later. Try editing your ProDraftsRepeaters.php file and near the top you'll see an `init()` method that has this line at the end of it:
~~~~
$this->setupAjaxFileUpload(); 
~~~~
Move that line out of init() and into the `ready()` method that appears below it, so that it looks like this:
~~~~
public function ready() {
  $this->setupAjaxFileUpload(); 
}
~~~~
Does that fix it?

**Comment by cb2004** [comment]
@ryancramerdesign that fixed it, thanks. Is there a new version of ProDrafts coming out soon?

**Comment by ryancramerdesign** [comment]
@cb2004 Yes I've got a new version just about ready with a few small fixes like this.
