### ISSUE TITLE
Empty needle in Pageimages.php

### ISSUE THREAD

**Issue by tbba** [processwire/processwire-issues#1566]
Since the last few PW DEV updates I regularly see this new warning from Tracy:
**PHP Warning: strpos(): Empty needle in ---/wire/core/Pageimages.php:90**
I am on PHP 7.4 with this.

Apart from an eventual fix for empty needles:
If this is coming from a malfunctioning image, is there a way to find out what the problematic image is?

**Comment by ryancramerdesign** [comment]
@tbba I'm not exactly sure what issue might account for there being an empty needle there, but sounds like maybe a filename has a leading "." or is missing an extension, or something along those lines. I've pushed a fix that should prevent the PHP warning. Thanks.

**Comment by tbba** [comment]
Thank you for the quick fix. The error was not leading to problems (the website loads normally) but the warning blocked other errors from reporting in Tracy (Tracy only mails one error at the time for non-obvious reasons).

Thanks also for the hint where to look for possible damaged content. I could not find anything, but keep an eye on it.

**Comment by adrianbj** [comment]
> Tracy only mails one error at the time for non-obvious reasons

https://tracy.nette.org/en/configuring - I probably need to add a config option to allow changing the snooze setting.

**Comment by tbba** [comment]
@adrianbj  I did not know this was possible. This would be a very cool addition.

**Comment by adrianbj** [comment]
@tbba - the problem is the possibility of getting a LOT of emails if your site is live and users are triggering the same error over and over again. I feel like it should probably check to see if the error is the same before emailing it out, but that's probably something the Tracy core should handle, although maybe I might be able to implement it into the PW module. I couldn't find your PW forum profile, but DM there if you have any thoughts so we don't keep polluting this.
