### ISSUE TITLE
Edit Template: "create new field" doesn't add fieldset end to template

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1571]
### Short description of the issue

In the Edit Template screen, if you use the "create new field" link to add a FieldtypeFieldsetOpen field, when you click "Close And Add" (sidenote: [CSS button capitalisation request](https://github.com/processwire/processwire-requests/issues/152)) only the "open" part of the fieldset pair is added to the template.

### Expected behavior

Both open and close parts of the fieldset are added to the template.

### Setup/Environment

* ProcessWire version: 3.0.200

**Comment by matjazpotocnik** [comment]
@Toutouwai @ryancramerdesign The corresponding _END fieldset is added after saving a template, but then I get an error:

![image](https://github.com/processwire/processwire-issues/assets/7663992/6d88107d-20cf-42bf-90e4-a7a8d0d8fa5b)

This is how it looks just after saving a template (it looks fine to me):

![image](https://github.com/processwire/processwire-issues/assets/7663992/e3de0bb0-c9f8-44bd-8139-bb2a1b58725c)

After “fixing” it (I didn't change anything, just saved the template again), the error is gone.

The problem is, that _END field is added after the form is first saved, and thus not known to the asmselect on first page load. There is no ID of the _END field in the DOM, so it would need to be fetched using an Ajax call or we can make an assumption it would have ID incremented by one. Based on this I modified `/wire/modules/Inputfield/InputfieldAsmSelect/asmselect/jquery.asmselect.js` to support updating `fieldsetCloseItems` and added _END field in  `/wire/modules/Process/ProcessTemplate/ProcessTemplateFieldCreator.js` - please search for `//MP` comments.

[ProcessTemplateFieldCreator.zip](https://github.com/processwire/processwire-issues/files/12363669/ProcessTemplateFieldCreator.zip)
[jquery.asmselect.zip](https://github.com/processwire/processwire-issues/files/12363679/jquery.asmselect.zip)

**Comment by ryancramerdesign** [comment]
Thanks @matjazpotocnik @Toutouwai I've added Matjaz's suggested fix for this

**Comment by Toutouwai** [comment]
Thanks @matjazpotocnik and @ryancramerdesign
