### ISSUE TITLE
WireArray::sort issue with formatted date fields

### ISSUE THREAD

**Issue by romaincazier** [processwire/processwire-issues#1578]
### Short description of the issue

I have a WireArray containing dynamically populated events that I want to sort using their `end_date`. However, when using `$events->sort("-end_date")`, the order is false.

### Suggestion for a possible fix

This issue is occuring because the sort function is applied on [formatted values](https://github.com/processwire/processwire/blob/924f93214536a506babbce1bab5c6c9e2093fc1e/wire/core/WireArray.php#L1412) (I tested it by disabling the output formatting on the events and it worked). In my case, since the date is in the format "dd/mm/yyyy", the sorting is wrong. A fix would be to sort based on the unformatted values but I don't know the implications of this.

**Comment by ryancramerdesign** [comment]
@romaincazier WireArray is the most basic array type in PW and it doesn't know anything about pages or formatted vs. unformatted for pages. That would be the job of the PageArray type. It knows about pages and also to retrieve the unformatted value for that type of operation.  

So for this case I would recommend using a PageArray rather than a WireArray. However, if you want to stick with using a WireArray for some reason, then you could turn off output formatting before your sorting and then turn it back on afterwards. You'd have to do it for each page in the WireArray, i.e. `foreach($items) as $item) $item->of(false);`

**Comment by romaincazier** [comment]
Hi @ryancramerdesign, thanks for reaching back on this. Indeed looking back I don't know why I used WireArray instead of PageArray... In the meantime I did set `$item->of(false)` but I'll make the switch.

Sorry for opening the issue, I'll close it now.
