### ISSUE TITLE
Question/feature-request (not really an issue)

### ISSUE THREAD

**Issue by pine3ree** [processwire/processwire-issues#1583]
### Default language page-name

Hello Ryan, I took a "deeper" look at Language Support module's related code. Would it be possible to be able to rename the default language name to anything other than 'default' (I am using lowercase locale names 'en-us', so I can extrapolate other language features via the php Locale class). I see that 'default' is used as a fallback here https://github.com/processwire/processwire/blob/3acd7709c1cfc1817579db00c2f608235bdfb1e7/wire/modules/LanguageSupport/LanguageSupport.module#L163 after trying the module configured defaultLanguageID. I renamed it via direct query and everything seems to work just fine (I actually have a script that change all language pages/configuration related IDs as well, but that's another story)

Another doubt: I see that you disabled autojoin for language pages (even enforced again in the Languages file)
https://github.com/processwire/processwire/blob/3acd7709c1cfc1817579db00c2f608235bdfb1e7/wire/modules/LanguageSupport/LanguageSupport.module#L152
https://github.com/processwire/processwire/blob/3acd7709c1cfc1817579db00c2f608235bdfb1e7/wire/modules/LanguageSupport/Languages.php#L168

Is here a particular reason for that? I would prefer loading title and extra fields like (locale, iso-639-1, iso-639-2 fields - btw these would compensate for the need of  a custom default language page-name) with one query. Again, I commented the two lines and everything seems to work fine, but I am not sure, maybe it could break the installation phase?

Thanks for your patience...
maks

* ProcessWire version: 3.0.200

**Comment by ryancramerdesign** [comment]
@pine3ree For the default language name, there may be cases where the 'default'  page name is expected. I'm not sure how many of those cases there are (whether core or 3rd party), but to be safe I would keep the default name if you can and add a dedicated field to hold whatever value you wanted to use the name for. 

For the temporarily disabled autojoin, I suspect it was to avoid a circular reference. For instance, a fieldtype that requires languages might need to access the $languages API var, but the $languages API var is not ready to be accessed at that stage, since it's in the init() method. By preventing autojoin there, we prevent Fieldtypes from getting involved and potentially messing things up.

**Comment by pine3ree** [comment]
@ryancramerdesign , for the latest project I ended up with a different solution:

I set language names like the following: `default`, `en-us`, `de-de` and add a `$config->defaultLanguagName = 'it-it'`. I then use a custom function with iso-639 maps and the `Locale` php class to add via hooks (lazy-loaded) properties (iso-639 alpha2, alpha3, locale, displayName etc) to the `Language` instances. In this way I was able to avoid unwanted db queries.

kind regards
