### ISSUE TITLE
jQueryUI 1.10.5 Vulnerability CVE-2016-7103

### ISSUE THREAD

**Issue by ghost** [processwire/processwire-issues#1587]
For a website that my company hosts an outside company found the following vulnerability with ProcessWire v3.0.200. It contains a JavaScript library with the known vulnerability of CVE-2016-7103

[https://nvd.nist.gov/vuln/detail/CVE-2016-7103]
Cross-site scripting (XSS) vulnerability in jQuery UI before 1.12.0 might allow remote attackers to inject arbitrary web script or HTML via the closeText parameter of the dialog function.

The suggested fix is to upgrade jQueryUI; however, that doesn't work if we upgrade it ourselves. Can you upgrade to a version 1.12.0 of greater as that doesn't have the vulnerability?

**Comment by ryancramerdesign** [comment]
@hcaton-si I routinely go through the jQuery and jQuery UI security reports and test whether any would be those that would affect PW's usage, and have yet to find any that represent a concern in our usage. Though if you find you are able to reproduce some specific issue in PW's usage of a library please let me know. We are running a custom jQuery UI at this point so it doesn't exactly correspond to a specific version and likewise it's not just a matter of replacing the version.

**Comment by ghost** [comment]
@ryancramerdesign That's good to hear. The "vulnerability" was found with an outside testing company. They've given me details to recreate it with Burp Suite, but I'm unfamiliar with the software so even though I can run the test I am not seeing results or warnings.

**Comment by ryancramerdesign** [comment]
@hcaton-si They are just detecting the presence of the library rather than finding an actual usage vulnerability that can be exploited. Most of these things (such as the one you mentioned) I don't view as a library security issue because it requires a developer to place unsanitized user input in jQuery/jQuery UI method calls. I would presume that if we do that, we are going to create problems. Likewise, if we accept user input in PHP and echo it back to the user without validating/sanitizing it, it is going to create the same problem. But that's a developer created security issue rather than PHP security issue. The same goes for many of these jQuery/jQuery UI things. At some point someone decided it was the library's job to handle filtering these things, and I don't really agree with that. I suppose since I've been using jQuery as long as it's been around, I don't have those expectations, and sometimes prefer the flexibility of the earlier versions.
