### ISSUE TITLE
"Add New Templates" issue for template with numeric name

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1588]
### Short description of the issue

I have an existing template and template file named "404". Whenever I go to Setup > Templates > Add New the "404.php" template file is wrongly identified as a new template when it is actually an existing template.

![2022-06-22_153428](https://user-images.githubusercontent.com/1538852/174938297-33fb5d6d-a397-40ea-ad1d-8f66adc8e08b.png)

![2022-06-22_153717](https://user-images.githubusercontent.com/1538852/174938309-dd769c55-b0d2-4412-b6b9-73736c98f50d.png)

### Setup/Environment

* ProcessWire version: 3.0.201

**Comment by ryancramerdesign** [comment]
@Toutouwai I don't think we can support templates with numeric names because the $templates API var has methods that accept either and ID or name, and they determine which it is by whether it's numeric or not.  I have updated ProcessTemplate to skip over adding number-only templates which should hopefully prevent the case you ran into there.

**Comment by Toutouwai** [comment]
@matjazpotocnik, thanks for linking to that earlier issue - I missed that one.

@ryancramerdesign, this fix introduces new problems. If numeric template names are going to be disallowed going forward then I think this needs to be mentioned in the notes for "Create a new template without a file" and template names that are submitted in this field should be validated and the user notified if any names are invalid. 

![2022-06-25_115422](https://user-images.githubusercontent.com/1538852/175749673-f0de81de-89d9-46c6-a9a9-9ee9f5be4168.png)

After the latest commit if I enter a numeric template name in this field then no template is created and there isn't any feedback about why. And a PHP error occurs:

![2022-06-25_115513](https://user-images.githubusercontent.com/1538852/175749687-631e4380-1113-4d9d-9971-25f9b7d1f95d.png)

As @matjazpotocnik noted in the linked issue, this problem in ProcessTemplate began with the lazy loading of templates. The issue didn't occur before that was added and doesn't occur with `$config->useLazyLoading = false;`. Maybe this issue could be solved in a different way that doesn't mean numeric template names need to be forbidden, by ensuring that the "Add New Templates" part of ProcessTemplate first loads all templates. If I add...

```php
// Ensure all templates are loaded
$templates->getAll();
```
...near the start of `ProcessTemplate::executeAdd()` it seems to fix the issue.

**Comment by matjazpotocnik** [comment]
@ryancramerdesign disallowing numeric templates would be a breaking change so I would not go this route. In this commit https://github.com/processwire/processwire/commit/883b0ab438ec5e4f3b7bef9c8efbf1ffa7939b3a the line  `if(count($templates->find("name=$basename"))) continue;` is replaced with this: `if($templates->get($basename)) continue;`
The get() method returns null if lazy loading is enabled.

**Comment by ryancramerdesign** [comment]
@matjazpotocnik @Toutouwai I don't think it could be a breaking change because PW has never supported digit-only templates. I think the error was that it may have unintentionally let you add them before. But it would have broken somewhere else because passing digits to $templates->get(...); assumes that the digits are referring to a template ID rather than a name. Maybe it would fallback to checking as a name if the id did not exist, but sooner or later (whenever an id and template name share the same digits) the system would break, it would be quite fragile. This is why I don't think it's practical to have digit-only template names, even if it might appear to work when nothing collides.

@matjazpotocnik I wasn't able to duplicate that error you mentioned in the last message. The $templates->get() method is not returning null for me, though maybe I misunderstand what you are saying. If it did return null I think it would show all existing templates with checkboxes as addable?

**Comment by matjazpotocnik** [comment]
If it was possible to add digit-only templates, even unintentionally, and now it is not possible anymore, then this is, in my opinion, a breaking change. 404 is also a digit-only template, so one could think it's safe to enter the template with digits. Thanks to your explanation, I understand why you don't want to allow digit-only templates. And that's the rationale behind this change in ProcessTemplate.php?

```
// if(count($templates->find("name=$basename"))) continue;
if($templates->get($basename)) continue;
```

If the 404 template is somehow deleted, how can I add it back?

If digit-only templates are not allowed anymore, what do you think about replacing a regex pattern (currently `^[-_.a-zA-Z0-9 ]*$`) to disallow the first digit?

Not directly linked with this issue, but I found that if I enter "." (dot) as the template name, it's replaced with "-" (dash), and those notices are displayed:

_ProcessTemplate: Added template and fieldgroup: .
ProcessTemplate: Added field "title" to template/fieldgroup "-"_

Notice the difference in the template name in the first and the second notice. Are dots allowed?

**Comment by BernhardBaumrock** [comment]
@matjazpotocnik the 404 page is template "basic-page" in all my installations. Maybe you have been creating this template on your own? As ryan explained it was a bug that this was possible and his arguments make sense. Maybe just rename that template to http404?

**Comment by ryancramerdesign** [comment]
@matjazpotocnik The reason for the replacing of the find() line with the get() is just an optimization. The get() performs faster, since it doesn't have to instantiate the Selectors engine. 

If you need to have a template with a digit name, I don't think that the core will block existing templates that already have a digit name? Just be aware that it could collide if a template ID and name have the same number. But if you are using "404" for example, then hopefully you won't have 400+ templates where you would need to worry about that collision. Basically, if you already have a template named 404, maybe it's to leave it once the risks are known.

The intention is just to prevent new templates from being added interactively that have a digit-only name. What Bernhard mentioned above about "http404" is exactly the name I use for my 404 template, when not basic-page.

Templates with "." aren't supported. The "." gets sanitized to a "-" once it is set to the template name. I can update that notification to use $template->name rather than $basename.
