### ISSUE TITLE
Process Module + Lazy Loading - not getting expected values

### ISSUE THREAD

**Issue by chriswthomson** [processwire/processwire-issues#1589]
### Short description of the issue

```php
foreach($pages->get($id)->children as $p) {
	$labels = [];
	foreach([
		'title',
		'body',
	] as $key) {
		$labels[] = $p->getField($key)->label;
	}
}
```

When the above is run in a template it returns the field labels in the context of the page, as it should.

However, when it is run in a Process module, it does not, it returns the Field label.

I suspect this is related to the lazy loading implementation. I'm sure I encountered something similar in a Process module I was working on after lazy loading was introduced.

### Setup/Environment

* ProcessWire version: 3.0.200

**Comment by ryancramerdesign** [comment]
@chriswthomson The Page::getField() method only returns a field in context if the page's output formatting is on. [See API ref](https://processwire.com/api/ref/page/get-field/). That's why you get what you expect on the front-end but not in the back end (Process module). You can fix it by doing a `$p->of(true);` first, or you can get the field via `$p->fieldgroup->getFieldContext($key)->label`. Also for a module that may be used in more than just a single-language environment, I recommend using `getLabel()` method rather than the `label` property, so that your labels will be in the right language.

**Comment by chriswthomson** [comment]
Ah ha thanks @ryancramerdesign!
