### ISSUE TITLE
Allow CKEditor to be used in custom PageFile/Image fields

### ISSUE THREAD

**Issue by romaincazier** [processwire/processwire-issues#1597]
### Description of the issue
When trying to add a CKEditor as a custom field of a PageImage, I saw it was not allowed by [this line](https://github.com/processwire/processwire/blob/924f93214536a506babbce1bab5c6c9e2093fc1e/wire/modules/Inputfield/InputfieldFile/InputfieldFile.module#L1388) because of issues mentionned in this [blog post](https://processwire.com/blog/posts/pw-3.0.142/#considerations-in-the-page-editor). However when allowing the field in my local installation I don't see any issue using it, apart from a CKEditor error about how mystyles.js is already declared, but nothing blocking.

### Question / Suggestion
Is it an issue that is still relevant today or do you think in the meantime you made changes that might have helped getting this issue fixed ? Could there be a checkbox or a hook or something to bypass this and allow a CKEditor if it's working ok in specific contexts ?

(I have to point out that I'm not using advanced CKEditor features, only PWLink and Italic)

### Screenshot
<img width="1261" alt="Screenshot 2022-07-12 at 14 35 01" src="https://user-images.githubusercontent.com/6616448/178491121-9edcdefe-448b-4ffe-a3d1-d4a38632b994.png">

### Setup/Environment

* ProcessWire version: 3.0.200

**Comment by Toutouwai** [comment]
@ryancramerdesign, I sent you an email relating to this topic in December 2020, reproduced below for convenience:

I'm emailing about the issue of CKEditor not working within custom fields for file/image fields. In the introductory blog post you said you would like to get CKEditor working and invited anyone to contribute help. I did a bit of experimentation and thought I would share my learnings in case it's helpful.

The first issue is that CKEditor fields within the custom fields are not initialised when new images or files are uploaded, because the config data for those fields is not in the ProcessWire.config object. Looking at InputfieldCKEditor.js it seems like the solution to this will be to add the config JSON to a "data-configdata" attribute on the newly uploaded files/images. I didn't go any further with that because I think it's something that you'll be familiar with other cases where a CKEditor field is AJAX-loaded (repeaters?).

The other issue relates to non-editable CKEditor fields and JS errors in the console when trying to interact with a CKEditor field. I think this occurs when the textarea element that the CKEditor instance has been attached to is moved around the DOM. In relation to custom fields for files/images this happens in two situations:

1. When the custom fields for an image are moved from their original location into the ".InputfieldImageEdit__edit" div, i.e. when the edit link for a thumbnail is clicked.
2. When a file or image is drag sorted within its inputfield.

For situation 1, I edited InputfieldImage.js so that an "edit-image" event is triggered after the custom fields are moved into ".InputfieldImageEdit__edit". After [line 364](https://github.com/processwire/processwire/blob/d3b1ab2983108a0410f7c66997f0478e7f3e02e6/wire/modules/Inputfield/InputfieldImage/InputfieldImage.js#L364) I added:

```js
$edit.find('.InputfieldImageEdit__edit .Inputfield').trigger('image-edit');
```

And in InputfieldCKEditor.js, when that event occurs I destroy the CKEditor instance and then re-initialise it.

```js
$(document).on('image-edit', '.InputfieldCKEditor', function() {
    var $editor = $(this).find('.InputfieldCKEditorNormal');
    $editor.each(function() {
        var editorID = $(this).attr('id');
        if(typeof CKEDITOR.instances[editorID] !== 'undefined') CKEDITOR.instances[editorID].destroy();
        ckeInitNormal(editorID);
    });
});
```

I didn't look at inline CKEditor fields but hopefully something similar could be done for those.

For situation 2, one solution is to apply the same approach in InputfieldFile.js and InputfieldImage.js as is used in InputfieldRepeater.js. That is, when the jQuery UI Sortable interaction is initialised, use the "start" function to destroy the affected CKEditor instances and the "stop" function to re-initialise them. But it would be good to have all the JS code relating to CKEditor in InputfieldCKEditor.js, and there could be other inputfield types that need special treatment around sorting. So I think it would be better to trigger "sort-start" and "sort-stop" events on the affected inputfields in InputfieldFile.js and InputfieldImage.js (and in InputfieldRepeater.js too I guess) and then those events can be handled in the relevant JS file for CKEditor or any other inputfield type. For the current issue probably only the sort-stop event is needed, and CKEditor can be destroyed and re-initialised using the same function as shown above. So in the "stop" function there would be this:

```js
// Trigger sort-stop event for inputfields to handle as needed
ui.item.find('.Inputfield').trigger('sort-stop');
```

And in InputfieldCKEditor.js:

```js
// Destroy and re-initialise CKEditor instances on image-edit and sort-stop events
$(document).on('image-edit sort-stop', '.InputfieldCKEditor', function() {
    var $editor = $(this).find('.InputfieldCKEditorNormal');
    $editor.each(function() {
        var editorID = $(this).attr('id');
        if(typeof CKEDITOR.instances[editorID] !== 'undefined') CKEDITOR.instances[editorID].destroy();
        ckeInitNormal(editorID);
    });
});
```

This is working for me here.

**Comment by romaincazier** [comment]
Thanks Robin for your input.

(it doesn't really help but) I just wanted to add that I'm facing an issue when the custom field is displayed within a repeater. The field's CKEditor toolbar setting seems to not be respected.

<img width="1088" alt="Screenshot 2022-07-13 at 13 50 09" src="https://user-images.githubusercontent.com/6616448/178727428-c4c72906-ad57-45cf-ac82-49320edb3b99.png">

**Comment by ryancramerdesign** [comment]
@romaincazier I found that CKEditor is just pretty fragile when used in this context. While it does seem like it can work in some cases or with adjustments here and there, it's a little more complex than I currently understand or am comfortable supporting. Though it looks like maybe Robin S has a potential solution for it.

**Comment by ryancramerdesign** [comment]
@romaincazier @Toutouwai I just went to add this code that Toutouwai suggested and see that I had already added it some time ago, perhaps from that email in December 2020? Anyway, just wanted to let you know the suggested code is already in InputfieldImage.js and InputfieldCKEditor.js. What's not there is the code for situation 2, so I am adding that in the next commit.

**Comment by ryancramerdesign** [comment]
@romaincazier @Toutouwai FYI additional updates were added for this. I've tested it out and it seems to be working here: https://github.com/processwire/processwire/commit/93b88c6ec35d89623a3c0d2e85937f0bc3bae236

**Comment by matjazpotocnik** [comment]
@romaincazier @Toutouwai can you please confirm the fix is working?

**Comment by romaincazier** [comment]
Hi, I'm sorry I didn't get back to you on this but using the latest dev version it seems to work perfectly on my side! The CKEditor is now respecting my settings contrary to the screenshot I showed above.

**Comment by Toutouwai** [comment]
Yes, seems to be working well. Thanks.
