### ISSUE TITLE
Custom image fields in nested Repeater fields are not saved

### ISSUE THREAD

**Issue by mgriesbach14** [processwire/processwire-issues#1600]
### Short description of the issue

When custom image fields are used in Repeater items nested in a RepeaterMatrix field, their contents are saved when new Repeater items are created.  On subsequent save actions, the custom image field contents are lost and cannot be inserted again. A similar issue was resolved before in previous ProcessWire versions (https://github.com/processwire/processwire-issues/issues/1391) but occurs again in the current master version 3.0.200

### Expected behavior

Custom image fields in Repeaters belonging to RepeaterMatrix fields are saved on item creation and on subsequent page save actions.

### Actual behavior

Custom image fields in Repeaters belonging to RepeaterMatrix fields are saved on item creation. The field contents are removed on subsequent page save actions and are not being saved when entered again.

### Optional: Screenshots/Links that demonstrate the issue

![image](https://user-images.githubusercontent.com/9393079/180866659-5510fc4e-06bd-458c-886f-51e638f837ed.png)

### Steps to reproduce the issue

a) Test with fresh ProcessWire installation and my database dump:

1. Install ProcessWire 3.0.200 with the blank site profile.
2. Add modules FieldtypeRepeaterMatrix and ProcessDatabaseBackups.
3. Download and unzip
[bug-repeatermatrix-customfields.zip](https://github.com/processwire/processwire-issues/files/9184552/bug-repeatermatrix-customfields.zip). Put the sql file in site/assets/backups/database.
4. Go to [YOUR-URL]/processwire/setup/db-backups/ and restore the sql dump. (The admin user's credentials now are username "admin" and password "FixMe22!".)
5. Edit test page [YOUR-URL]/processwire/page/edit/?id=1018: Open all Repeater(Matrix) items and add some content to the "desc" and "copyright" fields.
6. Save the test page and open the Repeater(Matrix) items again. The custom image fields remain empty.

OR

b) Create all fields from scratch:

1. Install ProcessWire 3.0.200 with the blank site profile.
2. Add module FieldtypeRepeaterMatrix. Install Repeater module.
3. Create two text fields named "desc" and "copyright".
4. Create an image field named "picture", set max. number of files to 1 and add fields "desc" and "copyright" as custom fields.
5. Create a new Repeater called "teasers" with the "picture" field in it.
6. Create a new RepeaterMatrix field called "blocks". In it add a new matrix type called "tiles" having the "teasers" field.
7. Add the "blocks" field to the "basic-page" template.
8. Create a test page from template "basic-page". Add a "tiles" block and a "teasers" item within where you upload an image. Fill in some content for "desc" and "copyright" and save the page. The content persists until you save the page again and then disappears.

### Setup/Environment

* ProcessWire version: 3.0.200
* PHP version: 8.0.4
* Any 3rd party modules that are installed and could be related to the issue: FieldtypeRepeaterMatrix
* TracyDebugger shows no errors.

**Comment by ryancramerdesign** [comment]
@mgriesbach I will have to try this out, but first just wanted to mention that I'm not sure we've ever added support for custom fields within images, within repeaters; and also not sure to what extent it's even possible to support. I don't usually suggest mixing repeatable types with custom fields unless support has been specifically added for it. So for this case you may want to use another repeater type for those image custom fields, since we do support nested repeaters (a potential alternative).

**Comment by brttd** [comment]
@mgriesbach @ryancramerdesign 
I've just come across the same issue. Custom image fields within a repeater work, but not if that repeater is itself within another repeater.

From testing I think I've tracked down the source - [InputfieldFile.module](https://github.com/processwire/processwire/blob/master/wire/modules/Inputfield/InputfieldFile/InputfieldFile.module#L1342), the `getItemInputfields()` function attempts to get the context of the image field;

![image](https://user-images.githubusercontent.com/11886548/201386982-466e2fcd-925c-4757-9225-4109859bfddf.png)

If I'm understanding the code correctly, (and understanding what happens when PW runs), I think what happens is:

1. When _rendering_ the image field - within a nested repeater - it gets the repeater page as the context (as the AJAX render call for the nested repeater item has the repeater item as the "page" for that render call, and not the actual main edited page)
The custom field(s) then get assigned names something like this:
`customfield_imagefield_repeater123_repeater456_hash987`

3. But when this runs while _processing input_, it gets the main edited page as the context (as there's now a single PageEditor running to process input for all fields, and repeater sub-fields) - and so the custom field will get a different name, without the extra repeaterpage context added:
`customfield_imagefield_repeater123_hash987`

This means when the custom fields process their input, the name they have when processing doesn't match the name they had when renderering - and so they can't find the data that was submitted.

I've tested disabling the code which adds that extra `_repeater...` context to field names, and it fixes the issue when using nested repeaters. _So far_ I've not run into any issues with custom image fields elsewhere.
![image](https://user-images.githubusercontent.com/11886548/201390254-45bc5aa9-f44b-478f-b53d-9c4a942292aa.png)

**Comment by brttd** [comment]
> ....
> If I'm understanding the code correctly, (and understanding what happens when PW runs), I think what happens is:
> ...
> I've tested disabling the code which adds that extra `_repeater...` context to field names, and it fixes the issue when using nested repeaters. _So far_ I've not run into any issues with custom image fields elsewhere.

It appears that code is neccessary for _new_ file items added via AJAX to get the correct field names when they're first added (after the page has saved their names work fine, but when first rendered via AJAX, at time file is uploaded, that code assigns correct name).

So the code is required for _new_ items in repeaters (and in nested repeaters) - but causes an issue for _existing_ items in _nested_ repeaters.

**Comment by ryancramerdesign** [comment]
@brttd Thanks for the excellent debugging help. This helped a lot. I was able to find a solution that works (see commit above this), though was wondering if you can confirm that it also fixes it there? 

Note that there is a downside to this solution, which is that it prevents those custom image fields from being editable when the repeater page is navigated to in the admin and edited directly. However, I don't think anyone edits them that way, or at least, they shouldn't be.

**Comment by matjazpotocnik** [comment]
@mgriesbach @brttd can you confirm Ryan's fix?

**Comment by matjazpotocnik** [comment]
@mgriesbach @brttd Closing on the assumption this is fixed. Please comment again to reopen.
