### ISSUE TITLE
Uncaught TypeError in admin when editing a page having Page Reference

### ISSUE THREAD

**Issue by er314** [processwire/processwire-issues#1607]
### Short description of the issue

As non superuser, when editing a page having a Page Reference field (which has field-level access control), the rendering of the edit view fails, with :  

Fatal Error: Uncaught TypeError: Illegal offset type in isset or empty in C:\xampp\data\www_smh\www\wire\core\Page.php:978 Stack trace: #0 C:\xampp\data\www_smh\www\site\assets\cache\FileCompiler\site\modules\AdminPageFieldEditLinks\AdminPageFieldEditLinks.module(155): Page->get(Object(PageField)) #1 C:\xampp\data\www_smh\www\wire\core\WireHooks.php(1050): AdminPageFieldEditLinks->{closure}(Object(HookEvent))

This is Page.php, line 978 :  
		if(isset(PageProperties::$basePropertiesAlternates[$key])) {

By catching the exception, it appears that $key is an object, of type ProcessWire\PageField,
actually it's a Page Reference field.

As a temporary measure, if I add the condition 
     && !is_object($key)  
then the rendering succeeds (but I have no idea of the implications, in terms of access control etc)

Note : Same pattern & issue on line 1397 :  
		if($value !== null && isset($this->wakeupNameQueue[$key])) {

### Setup/Environment

* ProcessWire version: 3.0.203
* PHP version: 8.0.15

**Comment by JanRomero** [comment]
Hi, that error is caused by the module AdminPageFieldEditLinks [and was fixed in this commit](https://github.com/thetuningspoon/AdminPageFieldEditLinks/commit/846bbff4482e06767bd92f9f1b3d9395b78db8b9). Please download the current version of the module from [AdminPageFieldEditLinks/releases ](https://github.com/thetuningspoon/AdminPageFieldEditLinks/releases). Unfortunately the version numbe was not incremented, that’s why ProcessWire does not find the new version in the module section.

**Comment by er314** [comment]
Ah yes, sorry, I forgot that AdminPageFieldEditLinks was a third-party module.
Thanks a lot for directly pointing to the root cause ; I confirm that the module update fixes the error.
