### ISSUE TITLE
FieldtypePageTitleLanguage doesn't save data within repeaters if only one default language is setup. 

### ISSUE THREAD

**Issue by elabx** [processwire/processwire-issues#1611]
### Short description of the issue

When placing the title field in a repeater field and the field is setup as FieldtypePageTitleLanguage, saving the a page containing the repeater field doesn't save the repeater's title field data if set. 

![repeater_issue](https://user-images.githubusercontent.com/7674567/183971396-20ff43e3-91e1-42de-90fb-441acf2457c5.gif)

### Steps to reproduce the issue

1. Install minimum required language modules (including FieldtypePageTitleLanguage)
2. Change title field to use FieldtypePageTitleLanguage 
3. Create repeater field
4. Add field title to repeater field
5. Add repeater field to a template 
6. Create repeater in a page with the previously used template and fill title field
7. Save page

<strong>Server Details</strong>

|Software|Version|
|------:|:-------|
|ProcessWire|3.0.184|
|PHP|7.3.27|
|Webserver|Apache/2.4.46 (Unix) OpenSSL/1.0.2u mod_fastcgi/mod_fastcgi-SNAP-0910052141 mod_wsgi/3.5 Python/2.7.13 mod_perl/2.0.11 Perl/v5.30.1|
|MySQL Server|5.7.32|
|MySQL Client|mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $|
<details><summary><strong>Server Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|allow_url_fopen|1|
|max_execution_time|120 (changeable)|
|max_input_nesting_level|64|
|max_input_time|-1|
|max_input_vars|1000|
|memory_limit|1000M|
|post_max_size|128M|
|upload_max_filesize|128M|
|xdebug||
|xdebug.max_nesting_level||
|mod_rewrite||
|mod_security||
|EXIF Support|1|
|FreeType|1|
</details><details><summary><strong>GD Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|Version|bundled (2.1.0 compatible)|
|GIF|1|
|JPG|1|
|PNG|1|
|WebP|1|
</details><details><summary><strong>iMagick Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|Version|6.9.6|
|GIF|1|
|JPG|1|
|PNG|1|
|SVG|1|
|PDF|1|
|WebP|1|
</details><details><summary><strong>Module Details</strong></summary>

|Module ClassName|Version|
|------:|:-------|
|FieldtypeEvents|0.0.4|
|FieldtypeRecurringDates|0.0.1|
|InputfieldEvents|0.0.4|
|InputfieldRecurringDates|0.0.1|
|ProcessDatabaseBackups|0.0.6|
|ProcessTracyAdminer|1.1.3|
|TracyDebugger|4.22.11|
</details>

**Comment by ryancramerdesign** [comment]
Thanks @elabx I've pushed a fix for this issue

**Comment by elabx** [comment]
Tested on 3.0.204 dev and seems to be fixed, thanks!

**Comment by romaincazier** [comment]
Hi @ryancramerdesign,

Checking the blame view of [`InputfieldRepeater`](https://github.com/processwire/processwire/blame/2a84f1201815a9ad19b536c65a8df3d5c7e4febf/wire/modules/Fieldtype/FieldtypeRepeater/InputfieldRepeater.module#L1129-L1141) I saw your change and wanted to reuse this issue to ask if you could edit the linked part to match this similar one in [`PageFrontEdit`](https://github.com/processwire/processwire/blob/2a84f1201815a9ad19b536c65a8df3d5c7e4febf/wire/modules/Page/PageFrontEdit/PageFrontEdit.module#L1234-L1249).

I’m making a module where I’m processing the inputs on the front-end and thus, with languages, the value is formatted and returning a string instead of an object. Changing the code to match the one in `PageFrontEdit` solves my issue while keeping the fix for this one working.

Thanks for considering!
