### ISSUE TITLE
InputfieldWrapper ID and class attributes not rendered

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1613]
### Short description of the issue

If you add `id` or `class` attributes to an InputfieldWrapper they are not rendered in the markup.

![2022-08-16_105436](https://user-images.githubusercontent.com/1538852/184734497-8787abca-a486-4494-a105-ff089be3de93.png)

This makes it difficult to target a given InputfieldWrapper with CSS or JS.

Related forum topic: https://processwire.com/talk/topic/23430-add-class-to-inputfieldwrapper-editing-a-module/

### Setup/Environment

* ProcessWire version: 3.0.203

**Comment by ryancramerdesign** [comment]
@Toutouwai It's the parent Inputfield that handles the render of any wrapping attributes and markup (where the `id` attribute would be used). Since you have no parent Inputfield, you are only rendering the innerHTML of the wrapper and missing the outerHTML. I would recommend either replacing your InputfieldWrapper with an InputfieldForm, or adding your InputfieldWrapper to an InputfieldForm, and then render the InputfieldForm.

**Comment by Toutouwai** [comment]
Fair enough. I often use Inputfield elements as inputs for JavaScript in which case no wrapping form element is wanted but I can always add some custom wrapping markup that has the identifying class or ID I need.
