### ISSUE TITLE
images.first returns null for populated field

### ISSUE THREAD

**Issue by BernhardBaumrock** [processwire/processwire-issues#1629]
### Short description of the issue

I just hit an issue with an images field that was set to `FieldtypeFile::outputFormatSingle` where I uploaded one file and wanted to request that file with `$page->get('myfield.first')`

Surprisingly that returned null!

After debugging I realised that `myfield[0]` worked as expected (returning an PageImage object).

### Expected behavior

`myfield.first` should always return the first PageImage unless no image is uploaded.

**Comment by ryancramerdesign** [comment]
@BernhardBaumrock If you are using `outputFormatSingle` then it means that the value is either a Pagefile or null. Pagefile is a single file, not an array of them. So there is no `first` method/property, since that is a method/property of WireArray. If you've specified the value should just be a single file, you'd want to use `$page->get('myfield')` rather than `$page->get('myfield.first')` since `myfield` already represents the first.

**Comment by BernhardBaumrock** [comment]
Thx @ryancramerdesign I know that. But the whole purpose of my request (https://github.com/processwire/processwire-requests/issues/453) was to get an option to FORCE the return type, no matter what the outputformatting value is.

That is important when developing modules where the user could possibly change the settings of the field and the code should still work. Or when working in a team where one person changes field setting not thinking about code of another dev.

In the past I have used "getUnformatted" to force array syntax, but Robin found that this has temp files in it.

So IMHO `$page->get("myfield.first")` should always return `PageFile|null` (no matter what outputformatting is set to) and `$page->get("myfield[]")` should always return `PageFiles`.

**Comment by BernhardBaumrock** [comment]
@ryancramerdesign please also note that your description from the [weekly post](https://processwire.com/talk/topic/27528-weekly-update-%E2%80%93%C2%A02-september-2022/) is not correct:

> $file = $page->get('files[0]'); // get first file  (or null if files is empty)
> $file = $page->get('files.first'); // same as above

"same as above" is wrong. Because `[0]` works exactly like I'd expect it to work but `.first` works differently (and unexpected!).

**Comment by adrianbj** [comment]
@BernhardBaumrock - not the right solution, but as a workaround, can you do a `isTemp()` check on the Pagefile along with the `getUnformatted` call to exclude the temporary files?

**Comment by BernhardBaumrock** [comment]
@adrianbj sure, that's been the solution before @ryancramerdesign implemented the request linked above.

But the better solution now is to use this:

```
$page->get("myfield[0]");
```

But IMHO (and as stated by ryan in the weekly post) `$page->get("myfield.first")` should be the same, but is not :)

**Comment by ryancramerdesign** [comment]
@BernhardBaumrock Using a WireArray property/method name like "first" would require that the value is a WireArray, but I think so long as the non-WireArray value doesn't have a conflicting property name, we can map something like "first" so that it returns the value you expect. I've pushed an update that should enable this.

**Comment by BernhardBaumrock** [comment]
Great, thx!
