### ISSUE TITLE
frontend editor renders unencoded html

### ISSUE THREAD

**Issue by BernhardBaumrock** [processwire/processwire-issues#1631]
### Short description of the issue

![entities](https://user-images.githubusercontent.com/8488586/196925663-2af01bb7-b639-438d-9879-2a41d94262fb.gif)

### Expected behavior

The frontend editor should not make the text bold but show the html markup instead, just like the inputfield in the backend does:
![image](https://user-images.githubusercontent.com/8488586/196925851-8731d98c-d090-4f90-8c0a-7222deb20005.png)

**Comment by ryancramerdesign** [comment]
@BernhardBaumrock Do you have the Entity Encoding Textformatter enabled for that?

**Comment by BernhardBaumrock** [comment]
Hi @ryancramerdesign no it's a plain textfield without any textformatters.

I think my description was not good, sorry for that.

This is the field in the backend:
![image](https://user-images.githubusercontent.com/8488586/200062706-6c2aed7c-b557-45f6-95f0-fa7792481178.png)

This is how it renders on the frontend (that's good!):
![image](https://user-images.githubusercontent.com/8488586/200062793-815ffd7a-c849-4832-b271-e144aa302ce2.png)

This is how it renders when EDITING on the FRONTEND:
![image](https://user-images.githubusercontent.com/8488586/200062890-f2fe0e12-49bd-47a1-94d8-95fc0efe75a6.png)

The last screenshot is the problem. Shouldn't it show the code just like the backend field (first screenshot) does? So it should be `Spenden Sie jetzt <strong>test</strong>`, no?

**Comment by ryancramerdesign** [comment]
@BernhardBaumrock I see what you mean. Though I don't know of a way to make it safe to edit HTML in a non RTE field. It's not safe to allow direct input and editing of HTML tags. At minimum you'd want the HTML entity encoder enabled for that field, but if you needed to allow for some formatting (bold, italic, etc.) then enabling Markdown or Textile in safe mode (rather than entity encoding) would be a safe way to accomplish it (not to mention, simpler for the editors).

**Comment by BernhardBaumrock** [comment]
You are right, thank you very much!
