### ISSUE TITLE
Module upgrade method not getting called

### ISSUE THREAD

**Issue by mrjcgoodwin** [processwire/processwire-issues#1634]
### Short description of the issue

I'm not sure if this is a core bug or an error/misunderstanding on my part as to how this is meant to work.

I'm working on a module where I'm pretty sure the upgrade method never gets called.

I've tested with a simple message output (below) and changing the version numbers up and down but I can never get any output from it. I've tried with and without using the ___hookable prefix on both my own method and the ones I'm calling.

See the forum thread I posted here: https://processwire.com/talk/topic/27699-bug-upgrade-method-not-being-called-in-modules where it seems others are experiencing the same issue.

### Expected behavior

When a module with a different version name is installed the module's upgrade method is called.

### Actual behavior

Upgrade method is not called.

### Example method that is isn't working:

```
public function upgrade($fromVersion,$toVersion) {
        $this->___install();
        $this->wire()->message('Upgrade method called');
}
```

### Steps to reproduce the issue

1. Change version number in your module code.
2. Upload module to PW.
3. Refresh module cache.
4. See if upgrade method is called. Testable with the example method above. (Message should be displayed).

### Setup/Environment

* ProcessWire version: 3.0.184
* PHP version: 7.4

**Comment by mrjcgoodwin** [comment]
Not a bug as explained by Robin S here: https://processwire.com/talk/topic/27699-bug-upgrade-method-not-being-called-in-modules/#comment-227873

**Comment by Toutouwai** [comment]
I think there actually is a bug here, because the [Module docs](https://processwire.com/api/ref/module/) imply that it's optional to make the `upgrade()` method hookable. And even the core FieldtypeOptions module has an `upgrade()` method without the underscore prefix.

But [Modules.php](https://github.com/processwire/processwire/blob/701d24258c791d34dc7aea41881a8fb6f1ef6bc7/wire/core/Modules.php#L5033-L5035) has this code...

```php
if(method_exists($module, '___upgrade')) {
	$module->upgrade($fromVersion, $toVersion);
}
``` 

...meaning that if a module has an `upgrade()` method without the underscore prefix it's not going to be called when the module version number changes (unless it extends a class that includes an `___upgrade()` method, which is how the FieldtypeOptions module manages to still get its unprefixed upgrade method called).

So I think either the Module docs need to be updated to make it clear that it's essential the method name include the underscore prefix, or the code in Modules.php should be:

```php
if(method_exists($module, '___upgrade') || method_exists($module, 'upgrade')) {
	$module->upgrade($fromVersion, $toVersion);
}
```

**Comment by mrjcgoodwin** [comment]
Reopening as requested by @Toutouwai .

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai @mrjcgoodwin I've pushed a fix for that
