### ISSUE TITLE
Custom fields for image field

### ISSUE THREAD

**Issue by matjazpotocnik** [processwire/processwire-issues#1661]
When using a custom fields feature for an image field (eg. myimages), and a template defining fields for it (eg. field-myimage) contains a required field eg. title, AND this required field has set "Also use HTML5 Required attribute", I get this javascript error:

![image](https://user-images.githubusercontent.com/7663992/210153216-01c7f05a-ebce-43e1-adc2-da5081f4827f.png)

If I unset "Also use HTML5 Required attribute" then I get notices about missing required value, as expected.

On the latest jQuery I also get:

![image](https://user-images.githubusercontent.com/7663992/210153492-91b9ae1b-8af7-4feb-bbd7-a2b3a322593f.png)

**Comment by ryancramerdesign** [comment]
Thanks @matjazpotocnik I've pushed a fix. Required attributes aren't possible here since these inputs change dynamically according to selected image and only one is shown at a time, so I have updated the code to remove required attributes, leaving just the required state (the one that reports after submit).
