### ISSUE TITLE
Add new page url preview doesn't respect template's slashUrls settings

### ISSUE THREAD

**Issue by gmclelland** [processwire/processwire-issues#167]
### Short description of the enhancement

When I add a new page at /processwire/page/add/ and start typing the name of the page, a preview of the url is shown below.  This url preview doesn't respect the template's slashUrls setting.  It always shows a "/" at the end of the url even if the template doesn't use trailing slashes.

![image](https://cloud.githubusercontent.com/assets/40570/22184951/bb9f4cb6-e0a1-11e6-904a-f098bb5dca7c.png)

My page template is set to not use the trailing slash.
![image](https://cloud.githubusercontent.com/assets/40570/22184955/d9e8d5de-e0a1-11e6-831e-409a199233fe.png)

### Optional: Steps that explain the enhancement

1. Go to /processwire/page/add/ 
2. Start typing the name of the page
3. See that it always adds a trailing slash to the url preview

### Current vs. suggested behavior

Currently, it always shows a slash at the end of the url preview.  I want it to only show the slash if the new page's template's setting "Should page URLs end with a slash? = yes"

It looks like this is handled in /wire/modules/Inputfield/InputfieldPageName/InputfieldPageName.module, but I'm not sure how to add a check for the template's slashUrls setting.

**Comment by ryancramerdesign** [comment]
What you see in ProcessPageAdd is independent of any template, because the Page doesn't exist yet. PW's default setting is to have trailing slashes, which is why you see it there. Once you create the page, a template is assigned, and then a setting from that template can apply to the page you are editing. The purpose of the path preview is really more about showing how your title converts to a name in the URL.
