### ISSUE TITLE
OR groups broken in sub selectors

### ISSUE THREAD

**Issue by niklam** [processwire/processwire-issues#168]
### Short description of the issue

OR-groups are broken in sub selectors. Seems as the OR-groups in sub selectors broke in commit https://github.com/processwire/processwire/commit/ffde966920b2f50ab8b575e7ba90d31a6aef94ad.

### Expected behavior

I expect all these selectors to return a resultset. Field pt is a Page Table.

```php
$selector = "template=basic-page,or1=(id=1002),or1=(id=1016)"; // works
$selector = "template=basic-page,pt.id=[or1=(id=1002),or1=(id=1016)]"; // broken
$selector = "template=basic-page,pt.id=[title=hoohaa]"; // works
$selector = "template=basic-page,pt.id=[or1=(title=hoohaa)]"; // broken
```

### Actual behavior

Second and fourth selector return 0 results after commit mentioned before.

### Setup/Environment

* ProcessWire version: 3.0.43-3.0.50

**Comment by ryancramerdesign** [comment]
@niklam I think I've got this one fixed in the latest commit referenced here, but I don't have a good test case with PageTable field where I'm working from at the moment. Please let me know if you find this resolves this issue or if further adjustments may be needed? If there's more to it than this I'll try and setup a PageTable configured similarly to the one you have there. Thanks.

**Comment by niklam** [comment]
Thank you @ryancramerdesign. The issue seems to be fixed.
