### ISSUE TITLE
PagesType::get loadOptions broken

### ISSUE THREAD

**Issue by LostKobrakai** [processwire/processwire-issues#169]
### Short description of the issue

PagesType::get() does call $pages->get($selector, $loadOptions);

This was changed from `findOne()` to `get()` here: https://github.com/ryancramerdesign/ProcessWire/commit/1beb2afdc16127a17e94d7e53d66fc16a35afb8b

### Expected behavior

The options taking hold.

### Actual behavior

$pages->get() does not allow for $options.

### Steps to reproduce the issue

1. Set `$users->setPageClass(SomeOtherClass::class);`
2. Retrieve an user by `$user = $users->get("id>0");`
3. User is not of the supplied class.

### Setup/Environment

* ProcessWire version: 3.0.42

**Comment by ryancramerdesign** [comment]
This one was fixed awhile back on the dev branch:
https://github.com/processwire/processwire/commit/2b9a7adbcb64f14dae29629e0a02b0c8738c67e8#diff-d9fa5beba4b89af59bf56c3ac2d85e9bL323
There are a few other things from dev that need to find their way to master soon, so I'm focusing now on resolving any remaining dev branch issues so that it can replace the master branch soon.
