### ISSUE TITLE
$page->matches() not working correctly for repeater count

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1701]
### Short description of the issue

I have a page containing an empty Repeater Matrix field, i.e. the count is zero.

![2023-03-08_112248](https://user-images.githubusercontent.com/1538852/223567591-92965e90-6a5d-4ef6-9d9f-e8cdeca95601.png)

The field is named test_matrix.

This page is matched by a `$page->findOne()` selector, but `$page->matches()` returns false for the same selector.

Demonstrated below in the Tracy console:

![2023-03-08_112743](https://user-images.githubusercontent.com/1538852/223568223-7b13cfaf-1c0e-479e-9679-c2094bc0c4be.png)

I'm not sure if this issue is specific to Repeater Matrix, or Repeaters, or something more general.

### Setup/Environment

* ProcessWire version: 3.0.211

**Comment by ryancramerdesign** [comment]
@Toutouwai Unfortunately I can't seem to duplicate this yet. I'm getting the correct response from page.matches for `repeater_field.count=0`, and any other count and operator combination I send to the matches() method. I don't think it's anything specific to RepeaterMatrix or Repeater because the code used here falls back to that from the Page and PageArray classes, since neither Repeater or RepeaterMatrix implement their own logic for this stuff. I'm operating on the assumption that the $page in your example is id=1448 (the one you circled in your first screenshot).

In the process of trying to duplicate it, I added support for `$pages->find('repeater_field.count=0')` (and similar) to match even when the repeater field does not yet have a DB entry (with that `count` column).

**Comment by Toutouwai** [comment]
At first I couldn't reproduce this again but then I discovered that the mismatch occurs when there is a hidden unpublished "ready" repeater item (e.g. the "Add New" button was clicked in the repeater inputfield but then Page Edit is abandoned without saving).

The "ready" items have no effect on the count column in the database because this only records published repeater items. So the expectation is that "repeater_field.count=0" will still match the page, but it looks like $page->matches() doesn't actually query the database directly but instead loads the unformatted value for each field included in the selector. Seeing as the unformatted value of a repeater field includes unpublished pages the selector doesn't match.

Maybe there's no way around this, but is there a reason why $page->matches() doesn't handle selectors the same way as $pages->find()? I'm probably missing something but I thought it would be simpler and more accurate if $page->matches() did something like:

```php
$ids = $this->wire()->pages->findIDs($selector);
return in_array($page->id, $ids);
```

Or maybe add a "id=$page->id" clause to the selector for efficiency so it's not loading more IDs than necessary.

**Comment by teppokoivula** [comment]
> is there a reason why $page->matches() doesn't handle selectors the same way as $pages->find()

I may be missing something here, but isn't this the usual [issue with in-memory selectors vs. database selectors](https://processwire.com/talk/topic/5083-possible-bug-page-fieldtype-with-custom-selector-to-find-selectable-pages-returns-error-while-saving-page/#comment-50177)? At least I've assumed that $page->matches() would go into this category as well, since it's doing something with a Page that has already been fetched :)

**Comment by Toutouwai** [comment]
> I may be missing something here, but isn't this the usual [issue with in-memory selectors vs. database selectors](https://processwire.com/talk/topic/5083-possible-bug-page-fieldtype-with-custom-selector-to-find-selectable-pages-returns-error-while-saving-page/#comment-50177)?

Yes, I think you're right. This unformatted value vs the explicit database count value for Repeaters is another case I need to add to my list of in-memory selector gotchas.

An in-memory selectors wish-list:

1\. Please could we have a more prominent explanation in the official documentation that there is a distinction between PageFinder and in-memory selectors. The [selectors documentation](https://processwire.com/docs/selectors/) barely mentions that in-memory selectors are a thing - just a couple of tiny notes saying that OR-groups and sub-selectors aren't supported by in-memory selectors. It would be great to have a list of methods where `$selector` means PageFinder selector versus methods where `$selector` means in-memory selector.

2\. In the documentation could we have a list of the differences between PageFinder and in-memory selectors, so there's an authoritative source that users can refer to. It comes up again and again in the forums...
https://processwire.com/talk/topic/23649-selector-date-format/
https://processwire.com/talk/topic/20143-selector-is-case-sensitive/
https://processwire.com/talk/topic/18343-selector-filter-for-multiple-dates/
https://processwire.com/talk/topic/28424-selectors-differences-between-use-on-pages-and-pagearray-due-to-character-collations/
https://processwire.com/talk/topic/20126-or-group-in-selector/
https://processwire.com/talk/topic/21690-db-vs-in-memory-selectors-null-vs-nullpage/
...but the answers get lost in the mists of time. And if there was a prominent page in the docs about it maybe fewer people would be confused in the first place.

3\. I think it would be great to have a `useDatabase` option for at least some methods that are currently using the more limited in-memory selectors. Because although the core might have to consider the performance impact of calling a method repeatedly in a loop, when people are using the API methods in their own code the performance impact of going once to the database is likely to be negligible, and definitely worth the trade-off to get the accurate/expected result.

What I mean is, considering the issue described in this report if I want to check if $page matches $selector in a module or some site code then I'm better off doing...
```php
$matches = (bool) $pages->count("id=$page, $selector");
```
...than using `$page->matches($selector)`. But the problem is that each person who wants to avoid the in-memory selector gotchas has to reinvent the wheel.

If there was some code at the top of the matches() method like this...
```php
if($options['useDatabase']) {
    // This would actually need a bit more code to handle when $selector is a Selectors object or an array
    return (bool) $this->wire()->pages->count("id=$page, $selector");
}
```
...then a) it would raise awareness that by default this method has some limitations relating to in-memory selectors and b) it would save the user from having to come up with their own solution when they want to use some PageFinder selector features and the performance impact won't be a problem.

For $pagearray->find() it might be something like this:
```php
if($options['useDatabase']) {
    return $this->wire()->pages->find("id=$this, $selector");
}
```

**Comment by adrianbj** [comment]
Just adding my support for @Toutouwai's proposal. I also end up with code like this when `$selector` needs to include an OR group. I usually start with a `$page->matches()` and then realize it won't work and change to this.
```
$pages->has('id='.$page->id.', '. $selector)
```

**Comment by ryancramerdesign** [comment]
@Toutouwai I like where you are going with that. But I think that if we're going to provide the database option, then maybe it should just be a set-it-and-forget-it setting. Something like a `$config->selectorsUseDatabase=true;` setting, which would make it always query the database rather than use in-memory selectors, when there is an option to do so. That's because I think it might be too much work to decide whether to use a `useDatabase` option in the arguments each time you use a relevant method. 

For instance, before the foreach() in the `PageComparison::matches()` method it could have this (and something similar for all the PageArray methods that accept selectors):
~~~~~
if($page->wire()->config->selectorsUseDatabase) {
  $selectors->add(new SelectorEqual('id', $page->id));
  $selectors->add(new SelectorEqual('include', 'all'));
  return $page->wire()->pages->count($selectors) > 0;
}
~~~~~
It does get a little more tricky with the PageArray methods because the find() operations could potentially return different Page instances than what's in the PageArray, so we'd probably have to do it with findIDs() or findRaw() and then pull the matching Page instances out of the existing PageArray.

**Comment by BernhardBaumrock** [comment]
@ryancramerdesign maybe I'm missing something but that does not sound like a good idea to me. What if I wanted to develop a module that relies on some kind of $page->matches(...) query and it only works when using the database comparison. Should I instruct users that want to use my module that it only works if they place the correct config setting in config.php? What if another module only works with the opposite setting?

I've also read this old issue (that should be closed IMHO https://github.com/processwire/processwire-issues/issues/896 ) and I agree with you that we are talking about two different things. Nonetheless I understand that these things are confusing and I think we should try to make it as easy and clear to use as possible.

I'm not yet sure what that means or how that could look like, though. But I have some ideas and thoughts:

I think what this issue and the issue linked above show is that using selectors on the database and using them in-memory are two different things. Ryan was clear about that in 2019. But it is obviously still an issue. So I'm trying to find solutions to make it less of an issue. I think providing better docs and making the difference really clear would be one solution.

But maybe there are other solutions as well. I'm trying to think outside the box here. I have an idea for the other issue, but the concept might help to find a solution for this issue as well. Sorry, I need to elaborate here a little :)

Adrian talked about this problem:

<img src=https://user-images.githubusercontent.com/871211/59938876-19ce1c80-940b-11e9-984f-41682cacf609.png>

So the issue that I see here is that using different techniques (in-memory vs. db) can lead to different results. In other words one call could return `null` whereas another one could return a `NullPage`. Whether this is good or bad or necessary or not is not my intention to discuss here.

I understand it from a technical perspective. But I think what Adrian complains about is that it is an issue when working with these kind of situations. And I understand that as well and I've had these situations as well. So what if we had something, that made these differences less of an issue in our daily work? What if we didn't need to change the API or add breaking changes, but still find a solution that feels good?

Take this example:

```php
$p = $something->get("id=123");
```

Let's say we wanted to do something only if the page with id 123 does not exist. Quite common, right? But how would we do that, if we don't know what ->get() returns? I've sometimes done this whenever I was unsure:

```php
$p = $something->get("id=123");
if(!$p or !$p->id) {
  // create page and do something
}
```

What if we had something like this?

```php
$p = $something->get("id=123");
if(!$wire->isPage($p)) {
  // create page and do something
}
```

So no matter what `$something->get(...)` returns (null, false, NullPage, Page) we know exactly what we want to know and it looks nice and is easy to read and understand. What do you think about that? Maybe it adds even more obscurity and could cause even more issues, I'm not sure. But my feeling says that I've too often had to think about whether something returns `false` or `null` or a `NullPage` and whether I need to check for `if($foo) ...` or rather use `if($foo->id)` ...

I hope you don't see this too much off-topic. I think the underlying issue is the same. Unfortunately for the `$page->matches(...)` problem I don't have a good idea yet. I think that case is not so simple. I thought about adding something like `$page->matchesDB("foo=bar")` but I guess there are many situations and many methods that would need a DB companion method?

Another idea that came to my mind was that maybe we could add a switch to the API that tells PW to use a DB query or the in-memory version. Similar to the `$page->of()` switch or similar to `$pages->getFresh(...)` or also similar to the concept of `$pages->uncacheAll()` which also has an effect on the results of specific selectors.

```php
// match selector against the database
$page->useDB()->matches($selector);

// this would use in-memory again
$page->matches($selector);
```

Couldn't the `useDB() call set a flag on the in-memory object that tells PW to fire the next query of a selector against the DB rather than in-memory and then just return the object itself for chaining? I obviously don't know enough about the inner workings, so that might be nonsense, but maybe it pops up an idea for a solution in another head.

I also thought about having something like `$wire->useDB()`, but I still don't think having a global flag would be a good idea. We have to make sure that the code we write produces expected results no matter what anybody else's code does.

This got far too long, but I hope it was at least somehow useful. Thx for pushing PW forward everybody!

**Comment by ryancramerdesign** [comment]
When it comes to in-memory selectors, I almost never use them. Not that I'm trying to avoid them, just that when I find myself using them, it means I've loaded more pages into memory than I should have. And there aren't many cases where that's necessary. So any finding/filtering of pages ideally happens from your $pages->find() or other appropriate call, not after it, where it's really no longer efficient. 

The reason that filtering from a PageArray even exists is because WireArray has these methods like find(), filter(), not(), etc. which are general purpose for any data type you can store in a WireArray, and not anything to do with pages per se. They really are meant more for filtering things like templates, fields, or anything that is stored in a WireArray (things already in memory). Those methods work consistently no matter what type of WireArray it is. 

While WireArray::find() and Pages::find() are both named "find", the methods on $pages are all unique from others in that they query the database, so they have some database-specific features. The PageFinder has its own abilities on top of selectors, and any Fieldtype module can also add its own unique selector abilities for querying the database.

I think there's a case to be made for Page::matches() to query the database, because that method is exclusive to pages. For the WireArray methods, I'd estimate they should stay the way they are, and that they should be used rarely. But I do wonder if the option to have a $config variable (or equivalent) to fine tune how you want them to work, is something to consider. Though I'd still say that ideally folks should really limit post filtering things because it's unnecessary overhead no matter how it happens. 

> What if I wanted to develop a module that relies on some kind of $page->matches(...) query and it only works when using the database comparison. Should I instruct users that want to use my module that it only works if they place the correct config setting in config.php? What if another module only works with the opposite setting?

If there were to be an option, then it would be off by default. So it's something probably you wouldn't code to assume it would be on. But if you needed to, then you could always enable it, perform your method call, then restore it to the original setting. Though I'm thinking more of the matches() method. You do have me thinking that a DB option for the WireArray methods probably isn't good.

> if(!$wire->isPage($p)) {

You can do this: 
~~~~~
if(!$p instanceof Page) {
~~~~~

> I thought about adding something like $page->matchesDB("foo=bar")

The other option is to just switch the existing matches() method to query the DB. This seems feasible to me since it would only need to use count(), which should limit any performance penalty. Some other Page methods already query the DB (children, etc.). The WireArray methods are a different case, since they are not about pages and have no other methods that involve database queries.

**Comment by BernhardBaumrock** [comment]
Thx @ryancramerdesign 

Seems you either did not understand what I tried to say or your statement is just another example that shows that my idea could be helpful:

> if(!$wire->isPage($p)) {
> You can do this:
> if(!$p instanceof Page) {

<img width="517" alt="image" src="https://github.com/processwire/processwire-issues/assets/8488586/64231d02-e57a-4aef-9c63-c3ff60c964a3">

You are using `!$p instanceof Page` which is `true` for a `NullPage` but that's exactly what we do not want here.

My suggestion was a method that let's us quickly and easily check if the variable provided is an existing page with an id.

```php
$wire->isPage(null); // false
$wire->isPage(false); // false
$wire->isPage(123); // false

$p = $pages->get("name=doesnotexist"); // NullPage
$wire->isPage($p); // false

$p = $pages->get(1); // Page
$wire->isPage($p); // true
```

I don't think that we have such a check at the moment and I think it is very common to need this check in one way or another. And I think (like in your example above) it's not unlikely that mistakes happen. At the moment we often have to do two checks, like in your example it would have been:

```php
if(!$p instanceof Page or !$p->id) {
    // create page
}
```

For me even to write this check was not trivial. I have to think about how to combine the negation and I have to think about using `or` or `and` correctly to get the desired result. Someone reading that code maybe has the same problem. Whereas this is trivial:

```php
$p = $something->get($selector);
if(!$wire->isPage($p)) {
    // create page
}
```

Note how that simple change solves many problems:

- It does not matter what `$something` is! Is it an Array? Is it a PageArray? Is it the `$pages` API? We don't have to care and we don't have to think about that.
- It makes the code a lot easier to read and more robust

<img width="433" alt="image" src="https://github.com/processwire/processwire-issues/assets/8488586/ec01001c-e3bf-475a-b45c-85bb5d92ec75">

The addition is simple but can make a lot of code a lot cleaner in my opinion: 

```php
$wire->addHookMethod("isPage", function (HookEvent $event) {
  $page = $event->arguments(0);
  if ($page instanceof Page and $page->id) $event->return = true;
  else $event->return = false;
});
```

I think I found a good example:

<img width="392" alt="image" src="https://github.com/processwire/processwire-issues/assets/8488586/af805648-ec4b-47ce-a036-1c8e34242de2">

Here you see that you get 3 different results from 3 very similar `get()` calls. I know and I understand that this is ok and I also understand the reason. Nevertheless it is something that I have to think of whenever these situations come up during coding. And that happens often.

What I'm trying to say is that this technical complexity is not easy to solve with a technical solution (like making `->get(...)` always return a NullPage as adrian suggested.

What I'm trying to say is that if these situations were not annoying maybe the issue would then be no issue any more:

<img width="549" alt="image" src="https://github.com/processwire/processwire-issues/assets/8488586/d3bd110c-2f68-40fd-b488-c075b4923af3">

Maybe someone can come up with a better name, because `isPage()` might be misleading for one or another. On the other hand `isPageWithID` is clumsy and `hasID` is also not ideal. Maybe `hasPageID`?

**Comment by adrianbj** [comment]
> Maybe someone can come up with a better name, because isPage() might be misleading for one or another. On the other hand isPageWithID is clumsy and hasID is also not ideal. Maybe hasPageID?

Maybe `pageExists()` ?

BTW - I would love to see something like this.

**Comment by ryancramerdesign** [comment]
> You are using !$p instanceof Page which is true for a NullPage but that's exactly what we do not want here.

I think we might be off topic from the issue report but yes I definitely misunderstood what you were after there. NullPage is still a Page, it's just a Page that doesn't exist. You could do `if("$p")` which returns true for a Page with an ID and false for a NullPage. But if you also needed to confirm that it's an instanceof Page, then you are right you'd do `if($page instanceof Page && $page->id)`. I don't think I've come across a case where such a verbose check would be necessary, but if you have, I'm open to updating the existing `wirePage()` and `page()` functions (or adding new `wirePageId()` / `pageId()` functions) to accept a $page as the argument and return the page's ID, or false if not a Page. Returning the ID would be more logical in result since a NullPage is still a Page, reserving false for something that's not actually a page. But `if(!page($p))` would still follow the same path whether $p is a NullPage or null.

**Comment by BernhardBaumrock** [comment]
Thx @ryancramerdesign and sorry for getting off-topic. I thought it might be related or helpful for this issue as well, but I think it's not really the case, so I suggest to continue here: https://github.com/processwire/processwire-issues/issues/896#issuecomment-1664642248

**Comment by ryancramerdesign** [comment]
@Toutouwai I've updated the `$page->matches()` method to use the PageFinder/database rather than performing an in-memory comparison.

**Comment by Toutouwai** [comment]
@ryancramerdesign, I would defer to your judgement here because you know the core better than anyone. 

But my concern is: if a method that's relatively "fundamental" (in that other core methods might call it regularly) is changed so that it now involves a trip to the database then this could possibly degrade performance. And especially so if it was an across-the-board change for all methods that currently use an in-memory selector.

Even the single change you just made to `$page->matches()` happens in the `PageTraversal` class and I remember from past blog posts that you spent a lot of time optimising the traversal of pages to solve bottlenecks that had previously been reported. Looking in `PageTraversal` I can see many intances of things like `$parent->matches()`, `$sibling->matches()`, `$next->matches()`, etc, and these look like things that might occur over and over within a single page load.

This downside didn't occur to me when I opened this issue, but the more I think about it the more I'm inclined towards erring on the side of caution and just leave it up to the user in any given method call if they want to query the database for greater accuracy or to support more selector features. So while it would be nice to have a built-in option for some methods to use the database I'd rather choose that option on a case-by-case basis.

**Comment by ryancramerdesign** [comment]
@Toutouwai Memory matching isn't overhead-free either, and in this case memory matching may have more overhead because every comparison might have to load a field, triggering a potentially more expensive DB query to load data and then compare it, when it could have just been compared in the DB without loading anything. But I also think you make a good point. Honestly this needs testing and benchmarking to really know for sure. Most likely some selectors will benefit from memory while others will benefit from database, so it all just depends on the case. I will experiment more after the next main ver. I have updated it so that the database is instead an option rather than the default.

**Comment by ryancramerdesign** [comment]
@Toutouwai If it emailed you my previous reply, I wasn't quite finished, updated reply above.

**Comment by Toutouwai** [comment]
Thanks @ryancramerdesign

**Comment by matjazpotocnik** [comment]
@Toutouwai, did you see my comments on the commit?

**Comment by Toutouwai** [comment]
@matjazpotocnik, no I didn't. Will reopen because you're right that `$page->matches()` will need to be updated to pass through the options argument.

**Comment by ryancramerdesign** [comment]
The matches() method in Page won't have an $options argument because the method is implementing the WireMatchable interface which uses a single argument matches() method.  The one in PageComparison isn't following any predefined interface, so it has the $options argument. Later I'll either add a Page::matchesDatabase() method or a use_database=1 option for the selector of the matches() method.

**Comment by Toutouwai** [comment]
Okay, thanks for the explanation @ryancramerdesign
