### ISSUE TITLE
Error when the inputfield type of Profields:Textareas is set to Float

### ISSUE THREAD

**Issue by lanceosborne** [processwire/processwire-issues#1715]
### Short description of the issue

Error when the inputfield type of **Profields:Textareas** is set to **Float**.

### Expected behavior

Text settings accordion should disappear when inputfield type of **Profields:Textareas** is set to **Float**.

### Actual behavior

**Text settings** accordion does disappear; instead it does not display the **Text formatters** field, but continues to show the **Text settings** heading.

**Error message:** "InputfieldForm: Warning ('showIf' from 'Markup/HTML (Content Type)'): dependency field 'contentType' is not present in this form. - ProcessFieldEdit"

### Screenshots

[Screen capture](https://capture.dropbox.com/i2QHtmwR0m1QtNaQ)

### Steps to reproduce the issue

1. Create Profields:Textareas field.
2. Set Inputfield Type to Float.
3. Save field.
4. Error appears after Save.

### Setup/Environment

* ProcessWire version: 3.0.214 dev
* Profields:Textareas: 0.0.9
* PHP version: 7.4.21
* MySQL version: 5.7.34

**Comment by ryancramerdesign** [comment]
@lanceosborne The Textareas type was primarily designed for use with Text and Textarea fields, so it's possible for there to be warnings or notices when used with other types. This is largely because the other types don't know about the context that Textareas uses them in. But so long as they don't interfere with the operation of the field in the page editor, it's okay to ignore those warnings.

**Comment by matjazpotocnik** [comment]
@lanceosborne Any more thoughts? Are you satisfied with Ryan's answer? If yes, can you close the issue?

**Comment by matjazpotocnik** [comment]
@lanceosborne closing, reopen if needed.
