### ISSUE TITLE
$config->timezone: FieldtypeDatetime vs. ProcessWire page.created/modified

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-issues#1734]
I can do an elaborate write-up of this, but I wanted to point out what I believe to be an inconsistency and get your thoughts first.

Assume this timestamp (UTC is May 15, 2023 18:00): 1684173600

If my server is UTC and $config->timezone is UTC, when saving that value to a datetime field, the value will be:
2023-05-15 18:00:00

If my server is UTC and $config->timezone is America/Los_Angeles, when saving that value to a datetime field, the value will be:
2023-05-15 11:00:00

So $config->timezone influences the time that gets saved for date fields.  OK.

With that being said, the system created/modified dates of a page **do not get the same timezone shift** applied that a typical FieldtypeDatetime field does as I demonstrated above.  While this is not a big deal on a deep technical level, the output of relativeTimeStr (for example, on Page Listers that have created or modified columns showing), the verbiage will, in my case, be in the **future** because the of the timezone settings.  It will say "7 hours from now" for example.

Therefore, I believe when ProcessWire saves a page, the created/modified dates should also be saved with the timezone shifted like a normal Datetime field... right?

**Comment by adrianbj** [comment]
@jlahijani - not sure if this is the answer you're really looking for but I find the easiest option is to set the server's time and MYSQL's `time_zone` to all match what you set in `$config->timezone`.

Be sure you use `America/Los_Angeles` (not a + or - hours offset) in all cases and things should align.

Perhaps this is a workaround that shouldn't be necessary, but just thought I'd mention it in case it helps.

**Comment by ryancramerdesign** [comment]
@jlahijani I think it's because the page times at set automatically by MySQL. I do the same thing that Adrian mentioned, making sure that MySQL and server/PHP are using the same timezone.  Though on most servers, they would be, so it's usually just a matter of knowing what timezone the server uses and using that. The only thing is that setting MySQL's timezone requires root privileges I think, so not as simple to set.  I guess another way around it would be for PW to stop using MySQL timestamp columns and avoid using MySQL date functions, but that might be too much of a sacrifice.

**Comment by BernhardBaumrock** [comment]
@ryancramerdesign could PW check if both match and if not show a warning somewhere in the backend? Maybe that could be added to a dedicated "Health Check" module?

I'm not sure though if we need such a module, because we already have Tracy Diagnostics Panel:
<img width="1281" alt="image" src="https://github.com/processwire/processwire-issues/assets/8488586/5f565290-2045-4022-b34e-2441fbe734ef">

Nonetheless I could think of such a module being useful. For example it could be built in a way that other modules add their own checks if they wanted to.

Or as we had in a recent discussion the module could also warn the admin if logfiles grow too large (either by absolute amount of filesize or by growing too much by one day/week/month etc.). So it would be great to have some kind of "alarms".

Sorry for hijacking - just dreaming ... :D

**Comment by szabeszg** [comment]
> a dedicated "Health Check" module

+1 and it should be a core module for sure, I think.

**Comment by netcarver** [comment]
@BernhardBaumrock https://github.com/netcarver/PW-ProcessDiagnostics

In the forum: https://processwire.com/talk/topic/6480-processdiagnostics

![Image](https://processwire-forums.s3.us-west-2.amazonaws.com/monthly_05_2014/post-465-0-19487500-1401132201.png)

**Comment by matjazpotocnik** [comment]
@jlahijani Are you satisfied with the responses? Can we close this issue?

**Comment by matjazpotocnik** [comment]
@jlahijani  I'm closing this issue, please reopen it if needed.
