### ISSUE TITLE
webpOptions with useSrcExt set to true and cache buster uppercase URL doesnt work

### ISSUE THREAD

**Issue by cb2004** [processwire/processwire-issues#1749]
As the title says with:

`$config->webpOptions = array(`
`  'useSrcExt' => true,`
`);`

Somthing like:

`$image->webp->url`

Will return:

`/site/assets/files/1/filename.jpg.webp`

But:

`$image->webp->URL`

Will return:

`/site/assets/files/1/filename.RANDOM.webp`

Which doesn't work with .htaccess rules:

`RewriteCond %{HTTP_ACCEPT} !image/webp [OR]`
`RewriteCond %{REQUEST_FILENAME} !-f`
`RewriteCond %{REQUEST_URI} ^(.*)\.webp$`
`RewriteRule ^(.*)\.webp$ $1 [R=307,L]`

It is the uppercase URL to break cache which is not working correctly.

I am using the very latest 3.0.219.

**Comment by ryancramerdesign** [comment]
@cb2004 I can't duplicate this issue here, but if you are getting `filename.abcde.webp` rather than `filename.jpg.webp?abcde` then that's maybe coming from ProCache Buster Type=C or a different cache buster? If ProCache, I'd recommend using the Type=A Buster if you intend to use the `useSrcExt=true` webp option, as I don't currently know of a way to combine Type=C with useSrcExt. You can select type A in Setup > ProCache > Buster (tab).

**Comment by matjazpotocnik** [comment]
@cb2004, are you ok with Ryan's answer?

**Comment by cb2004** [comment]
@ryancramerdesign @matjazpotocnik I have gone to type A in ProCache and all is fine. I think type A or B used to lose points on Lighthouse but now it seems OK. Cant recall but there was a reason we used C.
