### ISSUE TITLE
HTML Purifier removing rel attributes on links

### ISSUE THREAD

**Issue by matjazpotocnik** [processwire/processwire-issues#1755]
I have textarea configured as CKEditor inputfield type with HTML Purifier enabled. Links with rel attribute like this:

`<a href="/target/" rel="nofollow noopener">Link text</a>`

become this after saving a page:

`<a href="/target/" rel="nofollow">Link text</a>`

while ProcessPageEditLink shows this:

`<a href="/target/">Link text</a>`

Below is the screenshot of how it looks when I enter a link for a first time:

![2023-06-15_13h21_38](https://github.com/processwire/processwire-issues/assets/7663992/a607c52a-2fec-49dc-8c8e-0173f32c001c)

And this is after save:

![2023-06-15_13h23_16](https://github.com/processwire/processwire-issues/assets/7663992/d784e3f0-bf59-4bd0-a857-1e7414352843)

Disabling HTML purifier allows me to enter rel attributes.

I added "noopener" to line line 81 in MarkupHTMLPurifier.module to be:

`$this->settings->set('Attr.AllowedRel', array('nofollow', 'noopener'));`

and this also work.

**Comment by ryancramerdesign** [comment]
@matjazpotocnik I can't duplicate this issue here, as my "rel" attribute options (nofollow, noreferrer, noopener) are retained with Purifier enabled, no matter how many times I modify it and save it. Not sure why that is. But I'm assuming there must be some conditions where the issue appears (or doesn't), and your suggestion makes sense, I have added it. Thanks.
