### ISSUE TITLE
Permission issue with images in repeaters when pagefileSecure is enabled

### ISSUE THREAD

**Issue by teppokoivula** [processwire/processwire-issues#1772]
### Short description of the issue

After updating some sites from 3.0.165 to 3.0.184 (or later versions) of the core, we've been running into issues with images in repeaters disappearing. Secure files are enabled (`$config->pagefileSecure = true`) and the repeater is located on a page with restricted access, viewable by users with admin or member roles.

### Expected behavior

Images in repeaters should be viewable if current user has permission to view the page said repeater is on.

### Actual behavior

With 3.0.165 images are viewable, but in 3.0.184 - 3.0.210 they disappear.

### Steps to reproduce the issue

Starting from a blank installation of ProcessWire:

1. Enable pagefileSecure (`$config->pagefileSecure = true`)
2. Create role "member" with only the "page-view" permission
3. Create template "members" and limit access to "member" users only
4. Create repeater field "my_repeater" and image field "image", add "image" to "my_repeater", add "my_repeater" to the "members" template
5. Add a page using "members" template, add a repeater item to said page, and add an image to said repeater item
6. Add `<?php foreach ($page->my_repeater as $r) echo "<img src='{$r->image->url}'>"; ?>` to the template file for "members" template
7. Create member user, log in, and try to view your members page — in recent ProcessWire versions the page should be viewable but image should result in 404

### Setup/Environment

* ProcessWire version: 3.0.184, 3.0.200, 3.0.210
* (Optional) PHP version: 7.4, 8.1
* (Optional) Any 3rd party modules that are installed and could be related to the issue: tested on blank setup, no non-core modules installed

**Comment by teppokoivula** [comment]
For the record, I had to hotfix this on one site by hooking to `User::hasPagePermission`. In case of a RepeaterPage I get the "uppermost" forPage with a while loop, and if user has view permission to that page, change event return value to `true`.

**Comment by ryancramerdesign** [comment]
@teppokoivula I'm testing in 3.0.221 here but am not able to duplicate it yet. I tried both with an existing user (adding 'member' role), and also creating a new user with just the member role. In both cases the image in the my_repeater appears in the output. So it's possible that this one was already fixed between 3.0.210 and 3.0.221, but I don't remember specifically, so here's a few other things to try:

1. Go to Access > Roles > Member. Double check that "members" is checked for page-view. Hit "save", even if it is checked, and then test again. The purpose here is just to force it to refresh the role settings in case anything is mixed up in there.

2. Go to Setup > Templates, and then set Filters > Show System Templates to Yes. Click on template System > "repeater_my_repeater" to edit it. On the Access tab, make sure that "Do you want to manage view and edit access" is set to "No". 

3. Go to Setup > Fields > "my_repeater" and also make sure access control is disabled for the field. Do the same for your "image" field. 

4. Check your .htaccess file, near the bottom is section 18, make sure the two indicated lines are commented out, as they are not compatible with pagefileSecure: 
~~~~~~~
  # -----------------------------------------------------------------------------------------------
  # 18. Optionally (O) prevent PW from attempting to serve images or anything in /site/assets/. 
  # Both of these lines are optional, but can help to reduce server load. However, they
  # are not compatible with the $config->pagefileSecure option (if enabled) and they 
  # may produce an Apache 404 rather than your regular 404. You may uncomment the two lines
  # below if you don't need to use the $config->pagefileSecure option. After uncommenting, test
  # a URL like domain.com/site/assets/files/test.jpg to make sure you are getting a 404 and not
  # your homepage. If getting your homepage, then either: do not use this option, or comment out 
  # section #2 above that makes ProcessWire the 404 handler. 
  # ----------------------------------------------------------------------------------------------- 

  # RewriteCond %{REQUEST_URI} !\.(jpg|jpeg|gif|png|ico|webp|svg|css|js)$ [NC]
  # RewriteCond %{REQUEST_FILENAME} !(^|/)site/assets/
~~~~~~~

**Comment by teppokoivula** [comment]
Hey @ryancramerdesign — looks like you are right, this issue is not present in the latest development branch version. Guess it was indeed fixed. I'll just hold off updating more sites until there's a new stable release out :)

**Comment by teppokoivula** [comment]
Just for reference, here's the commit that fixed it: https://github.com/processwire/processwire/commit/3094bd952a099271e9794e00a285cab7daf789ce. It was in 3.0.211.

**Comment by teppokoivula** [comment]
Actually it looks like this might've been fixed in this commit: https://github.com/processwire/processwire/commit/cc99fc3c92c8cdd09b6230197405bce77a2d9c18. Earlier versions don't reference getForPage or getForPageRoot.
