### ISSUE TITLE
Get cacheFile from $page

### ISSUE THREAD

**Issue by matjazpotocnik** [processwire/processwire-issues#1779]
I enabled template caching for guests on home template. In my home.php file I put this:

```
$cacheFile = wire('modules')->get('PageRender')->getCacheFile($page);
$cacheFileName = (string) $cacheFile;
echo $cacheFileName;
```
$cacheFileName is:

`C:/inetpub/SkyScrapers/site/assets/cache/Page/1/1.cache`

but the created cache file is actually

`C:/inetpub/SkyScrapers/site/assets/cache/Page/1/1e77cb3d817f91b9f6e0d274b351f0de.cache`

I know the file is created with this name because $config->prepend and $config->append are used. But why I'm getting the wrong $cacheFile/$cacheFileName? Dumping $filename in /wire/core/CacheFile.php in buildFilename() method shows correct name. Also the correct name is in /wire/core/PageRender.module in the ___pageRender() method.

**Comment by ryancramerdesign** [comment]
@matjazpotocnik It depends on a few factors. One is the $options provided to the getCacheFile method, and the others are runtime conditions when the given $page matches the current $page API variable. When that is the case, runtime factors like ajax, https, url segments, pagination and current user language (if not default) become part of the hash for the filename. So if $options are provided or the given Page matches the current $page, then it uses a hash for the filename that represents the runtime conditions, rather than just the page id for the filename. 

What is the use case? Maybe I can suggest ways to accomplish it.

**Comment by matjazpotocnik** [comment]
@ryancramerdesign thanks for the answer, I'm aware of this. I assumed I will always get the correct cache filename, whatever it is. Use case is that I would like to get the name of cache file that would be rendered :-) I just discovered that my caching module AIOM+ is not working if $config->prepend and $config->append are used. I always get just "basic" cachefile eg. /site/assets/cache/Page/1/1.cache instead of /site/assets/cache/Page/1/1e77cb3d817etc.cache

**Comment by ryancramerdesign** [comment]
> Use case is that I would like to get the name of cache file that would be rendered 

Your function call would have to exactly match the one used by the system when generating the cache file, and the runtime conditions would also have to be the same. So that might be hard to duplicate if using some Page other than the one being currently rendered. Though since each page has its own directory in the cache, you could just remove that directory to remove all instances of that page render (if that's what you needed, I'm not sure). 

>  just discovered that my caching module AIOM+ is not working if $config->prepend and $config->append are used.

Note that the options are named appendFile and prependFile (rather than append and prepend), and the `$config` property names are appendTemplateFile and prependTemplateFile.

**Comment by matjazpotocnik** [comment]
It's the same page, the same conditions, same options (i'm not passing any options to the getCacheFile() method) in the home.php template file.

**Comment by matjazpotocnik** [comment]
@ryancramerdesign I wrongly assumed that getCacheFile() handles configs prepend/append directives. Now I pass an options array to the call and get correct result. Sorry for taking your time. Closing.
