### ISSUE TITLE
User needs page-lister permission to enable user-admin permission

### ISSUE THREAD

**Issue by cb2004** [processwire/processwire-issues#178]
### Expected behavior

If a role has the permission user-admin they should be able to administrate users. Instead they also have to have page-lister permission as this area uses lister. But then this enables the Find section.

### Actual behavior

The user gets a message that they dont have permission to administrate users when just user-admin permission is selected.

### Setup/Environment

* ProcessWire version: 3.0.51

**Comment by ryancramerdesign** [comment]
Thanks @cb2004 I've pushed a fix for this issue. What it's supposed to do is fallback to the regular (non-Lister) type list when the user doesn't have permission to page-lister. It was showing that error message rather than falling back, so I've fixed that. Since a user with user-admin permission is pretty close to a superuser, I hadn't seen a case where a role had user-admin without page-lister. But I would enable page-lister permission for anyone that has any kind of page editing access if you can, because the admin search engine also relies on the default Find lister to show page search results.
