### ISSUE TITLE
FieldtypeOptions: page search by *required* option considers option is empty

### ISSUE THREAD

**Issue by hiboudev** [processwire/processwire-issues#1783]
A **required** field with 2 options, ID=1, ID=2:
![image](https://github.com/processwire/processwire-issues/assets/15386877/05cc145e-8e62-405d-ae93-6ac93774b7ab)

I have:
- 3 users with option ID=1
- 1 user with option ID=2

As you can see, I find 3 users with ID=0 (that doesn't exist) but none with ID=1. Only ID=2 works as expected.
I suppose 0 is an empty value? But the field is required, so no user has this option empty.

```
$field = $fields->get('membershipStatus');
$all_options = $field->type->getOptions($field);

foreach($all_options as $option) {
    echo "<li>The id for $option->title is: $option->id</li>";
}
/**
Foreach output:
The id for Non adhérent is: 1
The id for Adhérent is: 2
*/

// 1 user has membershipStatus=2 and 3 has membershipStatus=1.
// BUT :
echo $users->count("membershipStatus=1"); // 0 WHY ?
echo $users->count("membershipStatus=0"); // 3 WHY ?
echo $users->count("membershipStatus=2"); // 1
```

### Workaround

Add the empty option in search, even if field is required.
`echo $users->count("membershipStatus=1|0");`

### Setup/Environment

* ProcessWire version: 3.0.210
* (Optional) PHP version: 8.1

**Comment by ryancramerdesign** [comment]
@hiboudev So far I can't duplicate it here. But the behavior you are seeing there is what I'd expect to see if the 3 users with id=1 hadn't actually been saved since setting that pre-selected value in the field. Note that the pre-selected value is what's pre-selected in the editor, not what's actually in the database. Nothing is in the database until the page is actually saved with that value selected. The same would be true of any field, not just an options field. This would explain why the id=0 is matching those users. 

Also, you might consider using separate value and label so that you can refer to the value in your searches rather than the more anonymous IDs. You would still translate the label portion, but not the value portion.
~~~~~
1=non-member|Non member
2=member|Member
~~~~~
Then you could do this instead:
~~~~~
echo $users->count("membershipStatus=non-member");
~~~~~

**Comment by hiboudev** [comment]
OK. That's not a big issue then, in my production environnement users will be created after the field.
(but in fact I would suggest if possible to fix it, if one day someones adds this kind of field in an environnement where a lot of users exist)

> Also, you might consider using separate value and label so that you can refer to the value in your searches rather than the more anonymous IDs.

I use ID with an enum so this is readable and avoid mistakes when typing strings:
`echo $users->count("membershipStatus=" . MembershipStatus::NON_MEMBER->value);`

**Comment by hiboudev** [comment]
I closed it, but reopen. That should be fixed because it's a real issue when updating an existing site. Developer have to save each page using the template with the added field, that should not be necessary.

**Comment by ryancramerdesign** [comment]
@hiboudev I understand what you are saying, but what you describe is not the way that any field works in ProcessWire, as it's not practical or scalable. When you set a default, you are setting it for the Inputfield in the form, rather than saving changes to pages and the database. The data in the database should reflect the data that's on a loaded page, core runtime assumptions about defaults are a no go. So it would have to go and find all the pages using that field that don't currently have rows in the database, and then insert default values for those rows. That's not practical on any large scale site. Though if it was, and you later changed the default, it would corrupt the data as it would have no way to know which rows had intentional selections of a particular value versus those inherited from a default. At least not without getting really complicated. If you want to assume that a particular empty value should be something other than empty (such as a default fallback), you'd typically consider that at output time, i.e. 
~~~~~
echo $page->favorite_color ? $page->favorite_color  : 'Not specified';
~~~~~

**Comment by hiboudev** [comment]
OK I trust you, and I close it again. :)
