### ISSUE TITLE
$page->url() method renders incorrect when using data option

### ISSUE THREAD

**Issue by madebymats** [processwire/processwire-issues#1785]
### Expected behavior

Should render `?action=view&type=photos`

### Actual behavior

Renders  `?action=view&amp;type=photos`

### Optional: Screenshots/Links that demonstrate the issue

<img width="237" alt="image" src="https://github.com/processwire/processwire-issues/assets/1630407/d5a228af-21d5-4623-86db-700368150bfa">

### Setup/Environment
MAMP 

* ProcessWire version: 3.0.222 dev

**Comment by ryancramerdesign** [comment]
@madebymats I'm not sure I understand because your section for "expected" and "actual" appear to be identical? Are you talking about the presence of `&amp;` from your screenshot? (maybe GitHub filtered that out in one of your examples). If so, it is intended to use `&` when output formatting is off, and `&amp;` when output formatting is on.

**Comment by madebymats** [comment]
Thats right had $page->of(false) set. 👍
