### ISSUE TITLE
Selector dot-syntax (.first, .last) not working properly

### ISSUE THREAD

**Issue by BernhardBaumrock** [processwire/processwire-issues#1795]
### Short description of the issue

I have a page reference field with the following settings:

```php
        self::field_invoice => [
          'type' => 'page',
          'label' => 'Invoice',
          'derefAsPage' => FieldtypePage::derefAsPageOrFalse,
          'inputfield' => 'InputfieldPageListSelect',
          'findPagesSelector' => 'template=' . Invoice::tpl,
          'labelFieldName' => 'title',
          'collapsed' => Inputfield::collapsedHidden,
          'icon' => 'file-pdf-o',
        ],
```

The field is set to `PageOrFalse` but nonetheless I wanted to use dot-syntax to make sure I get the expected result. Unfortunately this does not work as expected:

<img width="556" alt="image" src="https://github.com/processwire/processwire-issues/assets/8488586/9a9c893a-05c6-4841-b701-5ae21c6a7b45">

### Expected behavior

The reason for the `.first` and `.last` selector is to 100% make sure that the returned value is a single page object or false no matter what the field's `derefAsPage` setting might be.

### Actual behavior

`.first` returns NULL on my field.

`[0]` properly returns the page object or false, but I can't use that syntax to get the last page. Personally I've never ever had the need for `.last` so it would be fine to just stick to `[0]` syntax but I think `.first` is far easier to read and I consider this as a bug which makes working with those multi-value fields even more complicated as there are too many things that one has to take into account or know to make sure his/her software doesn't suddenly break at some point.

### Setup/Environment

* ProcessWire version: 2.0.223
* (Optional) PHP version: 8.1

I've also tested this with version 2.0.205 from 16.9.2022 and the issue is the same there.

**Comment by ryancramerdesign** [comment]
@BernhardBaumrock There are no first() and last() methods or properties on Page objects, since those are WireArray methods. Since you've configured your field to be a single Page, I'm not sure it really makes sense, as it's configuring the value to be of one type, and then asking it to behave like another. But I understand you are looking for convenience, and I think that's worthwhile and possible to support without out much trouble. Though if you have a field named "first" or "last" then that would still have to have precedence. 

The only other concern is that first() and last() were always possible traversal methods for Page objects and they would refer to the first and last siblings, as we already have Page next() and prev() methods (and others) that refer to siblings. But I think they could probably co-exist since the case (FieldtypePage value) you are asking for seems specific enough.

**Comment by BernhardBaumrock** [comment]
Hey @ryancramerdesign thx for the quick "fix" - actually I have to apologise, because what you say makes sense and obviously the syntax has to behave differently for pages than for Pageimage objects!
