### ISSUE TITLE
Integer field returns a string when default value is zero and field value has not been defined

### ISSUE THREAD

**Issue by hiboudev** [processwire/processwire-issues#1797]
### Short description of the issue

A page has an Integer field, default value is set to zero but field value has not been defined.
var_dump($page->myIntegerField); // string(0) ""

Option "blank and zero have different meanings" doesn't change result.

I'm using strong typing in my code, and that throws an Exception. I could cast to int but I don't expect to have to cast an Integer field to an int.

### Expected behavior

Value should always be an integer, in this case : zero.

### Actual behavior

Value is string.

### Setup/Environment

* ProcessWire version: 3.0.210
* (Optional) PHP version: 8.1
* (Optional) MySQL version: 
* (Optional) Any 3rd party modules that are installed and could be related to the issue:

**Comment by matjazpotocnik** [comment]
@hiboudev I can't replicate it on PW 3.0.224. Under the field's Details tab, I have selected the option "No - Blank and 0 have different meanings" (zeroNotEmpty=1) and dumping my integer field return int 0.

![image](https://github.com/processwire/processwire-issues/assets/7663992/409caac0-eaee-4e75-8b08-1aa705ac28f4)

**Comment by hiboudev** [comment]
@matjazpotocnik  Testing in 3.0.224, if field has not be explicitly set to a zero value, its value is a string, even if setting "Default value" to zero.
Zero is displayed on the page in PW admin, but the API returns an empty string.

EDIT
To reproduce, delete the value of this field in admin page, save the page, you should see its value is now zero (default value must be set to zero, and "blank and zero are different") but from the API it's an empty string.

I updated title and issue description, it wasn't clear.

**Comment by matjazpotocnik** [comment]
You may want to check this: https://processwire.com/talk/topic/1593-how-can-i-specify-default-value-for-certain-input-field/

**Comment by hiboudev** [comment]
Default value is already set to zero in field admin.
Do you consider as expected that an Integer field is returning a string in some cases?

**Comment by hiboudev** [comment]
I'm looking quickly the code, I see that function in FieldtypeInteger:
```
public function getBlankValue(Page $page, Field $field) {
  return '';
}
```
Why is it returning an empty string and not taking into account the field option "default value"? This option is used when viewing the page in PW admin, but not when getting value.

**Comment by ryancramerdesign** [comment]
@hiboudev Blank string indicates no value has yet been saved for the field (for any number field in PW). Null would be the more common case for that, but since PW loads field values on request (rather than all at once), it uses null internally to identify whether a field value has been loaded yet. So blank string is our null in this case, to represent the non-presence of a value. I suppose we could use boolean false, but since values for fields nearly always end up in strings (output) blank string made more sense for this case. 

Default values in PW are used by the Inputfields (not the Fieldtypes) to populate a default to substitute when a non-value (blank string) is present in the editor. So you'd see this on the `<input>` but not on value of `$page->field`. If I understand correctly, you'd like it to also appear on `$page->field` where no value has yet been saved? 

While defaults don't work that way in PW, this is a case where it potentially could, but only if blank and 0 zero are equivalent and the default value is specifically set to 0. It wouldn't work with non-zero defaults because then the data in the DB would no longer be consistent with the field value. So I'm not really sure it's worthwhile to account for that specific case because then one would expect that to work for non-zero default values too, and perhaps for other fields. 

You mentioned needing to maintain a specific type (int), so if you consider 0 and blank to be the same, then the simplest solution would be just to typecast:
~~~~~
$value = (int) $page->kilometers; 
~~~~~
Or you could maintain your own condition for the non-presence of a value:
~~~~~
if(is_int($page->kilometers)) {
  echo "Distance: $page->kilometers km";
} else {
  echo "Distance not yet known";
}
~~~~~

**Comment by hiboudev** [comment]
OK for the behavior of default values, I think you already explained it to me but I forgot it's used only when displayed in admin. I find this a bit disturbing by the way, I would expect admin and API to give same result.

> While defaults don't work that way in PW, this is a case where it potentially could, but only if blank and 0 zero are equivalent and the default value is specifically set to 0.

That's what I expect at least.

I don't understand why in FieldtypeInteger.getBlankValue() you don't return a zero instead of a string. Zero is the default int value. How a string can be a default value for an integer?...

**Comment by ryancramerdesign** [comment]
> I don't understand why in FieldtypeInteger.getBlankValue() you don't return a zero instead of a string. Zero is the default int value. 

I'm not sure how many years old Matjaz is, so if you asked me what Matjaz's age is, should I tell you he is 0 years old, or should I tell you "I don't know'. 0 is a value that has meaning, it could be the age of a newborn, for instance. A blank value is is the "I don't know", the value that indicates no row is stored in the database.  Think of it the same way as NULL. So if PW encounters a non-blank value, it inserts the value into the database.  If it encounters a blank value, it deletes the row from the database. The getBlankValue() returns the value that should be used to determine if the row should be deleted from the database, and that's why it returns a blank string. No need to store a row for a non-existing value. 

> How a string can be a default value for an integer?...

In any SQL column, whether number of not, the non-presence of a value resolves to NULL. This is the same thing. The output of a blank string is... blank, as in, no value. Wheres the output of 0 is 0, a value. Values such as 0, 1, 2, -1, etc. are known integer values, whereas null, or blank string in this case, is an unknown value, a value that doesn't yet exist.

**Comment by hiboudev** [comment]
We have both different point of view. :)
I'm more of a Java dev where an integer can't be anything else than an integer. The "blank" value, if necessary, is decided depending of context, but is always an integer.
In MySQL I always define int default value: `sortOrder INT DEFAULT 0`. If zero has meaning I use -1 as default.

I understand that it's closely related to how you manage DB rows and blank values.
From my point of view, the problem is that field configuration is not used by API (default value and meaning of zero).
If I have to cast every usage of integer field I'll do it, but I fill bad about this, and that increases probability to code a bug since it's easy to forget.

**Comment by Toutouwai** [comment]
This issue occurs regardless of what the default value is (e.g. try setting the default value to 7) so I don't think it's specific to zero versus empty string.

@ryancramerdesign, I wonder if there is a bug in `PagesEditor::setupNew()`. Because [it checks](https://github.com/processwire/processwire/blob/5a50ca01d81edd0ac587d8c19d6027313be9efd6/wire/core/PagesEditor.php#L374) for `$field->get('defaultValue')` but then it never applies it to the field. Instead [it applies](https://github.com/processwire/processwire/blob/5a50ca01d81edd0ac587d8c19d6027313be9efd6/wire/core/PagesEditor.php#L378) `$field->type->getDefaultValue($page, $field)` which is not the same thing.

**Comment by ryancramerdesign** [comment]
@Toutouwai That's not really related to this particular case, as it was something for newly created pages. And those pages already get the default value from the Inputfield, so I think that bit of code must have been an old leftover or oversight.

**Comment by ryancramerdesign** [comment]
@hiboudev No problem, I understand. You can typecast if need be, but PW is most often used for data that will ultimately be output in HTML, and so a blank string value would usually be what you'd want (rather than a 0 or -1) for a value that has not been entered, as 0, 1 and -1 are all known integer values. Blank string is an unknown value, and the field must be able to represent both known and unknown. Something like a JS indexOf() function call might use -1 as "not present" but that's only because it's impossible for a string value to have a negative length. We can't make assumptions like that for a general purpose integer field, which is why we must use a non-integer for an unknown/non-present value.

**Comment by hiboudev** [comment]
> We can't make assumptions like that

No you can't, in that case it would be the default value defined by user in PW admin, if used by API.

Finally this issue report should be a feature request: "Use default values in API for blank fields", do you think that would be possible?

**Comment by ryancramerdesign** [comment]
Yes, it would be possible. But the data in the DB and the API would be inconsistent. So you'd have a page that has a particular value from the API, but doesn't match that value in a query. But maybe that's an okay compromise for this integer field, so long as its explained by the setting description.

**Comment by hiboudev** [comment]
I close this issue and won't ask for the feature, because I don't like the fact to make integer field behavior different than other field types.

**Comment by matjazpotocnik** [comment]
@hiboudev maybe [this new module](https://github.com/Toutouwai/FieldInitialValue) by Robin could be useful for you?

**Comment by hiboudev** [comment]
Thanks, I've bookmarked the link, maybe I'll take a look at it but this is still necessary to save the page to create the initial value. If I add a field to a template without saving the related pages the problem is still there.
So that's probably simpler to just consider these empty strings to be part of the game.

**Comment by hiboudev** [comment]
@ryancramerdesign It seems that locked field doesn't apply default value. If you plan to refactor things one day, that would be fine to also apply default value in that case.
