### ISSUE TITLE
cloning a tinymce

### ISSUE THREAD

**Issue by virtualgadjo** [processwire/processwire-issues#1799]
hi,
not really an issue but just funny (even if logical) when cloning/duplicating a tinymce field to get an "alert" suggesting to remove the html entities text formatter (now by default with text and textarea fields) due to its html content nature although, of course, we don't get this "alert" when creating the first tinymce field
once more, not an issue at all and i understand the reason as removing it would mean checking more of the field options when duplicating a textarea... just something i've noticed :)
have a nice day

**Comment by ryancramerdesign** [comment]
@virtualgadjo This will happen if you clone a TinyMCE or CKEditor field that has no Textformatters defined, or if you create a new Textarea field and then set TinyMCE/CKEditor as the input type. I thought it was safer for newly created text/textarea fields to add HTML Entity Encoder automatically when no Textformatters are present. At the time it happens, it doesn't know that it's a clone of another field, otherwise I'd have it skip adding it. So it's a little bit of redundancy.

The reason it doesn't happen if you create a TinyMCE/CKEditor field directly is because we now have predefined setups for Fieldtype/Inputfield combinations, which is why you see a "TinyMCE" option for "Type" when creating a new field. This is new, as in prior versions you would have to create a Textarea field and then select TinyMCE or CKEditor (and then remove the HTML Entity Encoder, like when doing a clone).

**Comment by virtualgadjo** [comment]
Hi @Ryan,

and thanks a lot for your answer
you're right, it only happens when duplicating a field, the funny thing is it never happened in the "ckeditor only days" (i use this clone feature quite often), but you're right, probably safer if ever a user cloned a field not knowing what exactly a textarea is :)

and of course, not a problem nor an issuel, as i said, i was just a littee surprised the first time i ran into this little alert but am already used to it :)

have a nice day

**Comment by matjazpotocnik** [comment]
@virtualgadjo, so, can this issue be closed?

**Comment by virtualgadjo** [comment]
Hi @matjazpotocnik
yes of course, not really an issue, i mentioned it because as it was not the case before i was just wondering if it were something forgotten here but, i should have known, not really the pw team type to forget things :D
have a nice day
