### ISSUE TITLE
pages::saveReady hook broken ProcessWire 3.0.51

### ISSUE THREAD

**Issue by Da-Fecto** [processwire/processwire-issues#180]
### pages::saveReady hook broken ProcessWire 3.0.51

pages::saveReady not called

### Expected behavior

pages::saveReady gets called when page is ready to save

### Actual behavior

Hook never triggered

### Steps to reproduce the issue

```
<?php namespace ProcessWire;

class SaveReady extends WireData implements Module {

	public static function getModuleInfo() {
		return array(
			'title' => 'SaveReady',
			'version' => '0.0.1',
			'autoload' => true,
			'singular' => true,
			);
	}

	public function init() {
		$this->addHookAfter('pages::saveReady', $this, 'afterPagesSaveReady');
	}

	public function afterPagesSaveReady(HookEvent $event) {
		throw new WireException('I will not be called.');
	}
}

```

### Setup/Environment

* ProcessWire version: 3.0.51

**Comment by ryancramerdesign** [comment]
I think the issue is that your addHookAfter() is using the wrong case. It
should be 'Pages::saveReady' not 'pages::saveReady'. These are case
sensitive.

**Comment by Da-Fecto** [comment]
But then there is a change in behaviour in ProcessWire between 3.0.40 or so and 3.0.51.

**Comment by ryancramerdesign** [comment]
Supporting a case different from the class being hooked was never intended for hooks, but am thinking the you are seeing a side effect of detection method and whether another hook previously was attached to the same method. PW hooks will try to determine if a hook is present in the quickest way possible, and what method it uses changes depending on the case, and whether another hook has already been attached. Ideally PW would throw an Exception if you tried to hook something the wrong way, but unfortunately that's not possible because PW needs to support the ability to add hooks to classes that aren't yet in memory, or might not be for the current request (like a ProcessPageEdit hook in ready.php). 

Some things in PHP are case sensitive while others aren't, so I'm pretty sure that pages::saveReady you mentioned is working because it went through an instance check rather than a token check, perhaps because it was the first hook attached to saveReady. But in any case it doesn't matter because case insensitivity was never intended for hooks. I want to avoid adding something that encourages people to use the wrong case with hooks, plus want to avoid extra case adjusting function calls on every single hook method call (which would be thousands of function calls on every request). I also get where you are coming from that if some hook was working before, you'd like it to keep working, even if it's got the wrong case. I can update our addHook() method to look for "pages" and adjust it to "Pages", if this would help?

**Comment by Da-Fecto** [comment]
I was doing a big refactoring of an existing module and updated ProcessWire.  I thought I messed up big time in that fairly complex module and I've never seen that I misspelled the hook :-).

Your comment is really appreciated and I totally agree with the case point. I should have spelled it correctly the first time. Case sensitive is the expected behaviour, so please avoid the 'overhead'.

Thanks again.
