### ISSUE TITLE
Incorrect User Activity trigger when uploading image

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1815]
### Short description of the issue

The User Activity module triggers a "Warning, you have modified this page in another window. Saving may overwrite changes." when you replace an existing image

### Expected behavior

I haven't that the page open in a separate window, so this error is incorrect.

### Actual behavior

I get the error mentioned above.

### Optional: Suggestion for a possible fix

Not sure, but the problem is that choosing "Continue editing" needs to be clicked because if you click "Reload this page" then you lose the change to the image that was uploaded.

### Steps to reproduce the issue

1. Edit page
2. Upload image
3. See User Activity error popup

### Setup/Environment

I have tested this on two different servers on both 3.0.221 and 3.0.227 and see the same issue.

Not really sure if this is a bug in the core, or the User Activity module, but I no longer have access to its forum board so reporting here anyway.

Here are my settings for the User Activity module, as exported via https://processwire.com/modules/module-settings-import-export/

```
{"UserActivity":{"version":6,"settings":{"lastMaint":1695153529,"features":["collide","collide-self","opened","modify","modify-self","logout","idle"],"activeSeconds":60,"refreshSeconds":30,"idleSeconds":600,"expireSeconds":180,"icon":"fa-circle-o-notch fa-spin","adminVars":"id name","frontVars":"","useLock":"0","idleEditor":"1","pageListSeconds":5,"changeClass":"InputfieldIsColor InputfieldIsPrimary"}}}
```

<strong>Server Details</strong>

|Software|Version|
|------:|:-------|
|ProcessWire|3.0.227|
|PHP|8.2.10|
|Webserver|Apache/2.4.57 (Unix) |
|MySQL Server|8.1.0|
|MySQL Client|mysqlnd 8.2.10|
<details><summary><strong>Server Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|allow_url_fopen|1|
|max_execution_time|300 (changeable)|
|max_input_nesting_level|64|
|max_input_time|60|
|max_input_vars|1000|
|memory_limit|128M|
|post_max_size|8M|
|upload_max_filesize|2M|
|xdebug||
|xdebug.max_nesting_level||
|mod_rewrite|1|
|mod_security|*confirmed off|
|EXIF Support|1|
|FreeType|1|
</details><details><summary><strong>GD Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|Version|2.3.3|
|GIF|1|
|JPG|1|
|PNG|1|
|WebP|1|
</details><details><summary><strong>Module Details</strong></summary>

|Module ClassName|Version|
|------:|:-------|
|AdminOnSteroids|2.0.21|
|AwTest|0.0.1|
|BatchChildEditor|1.8.25|
|CustomInputfieldDependencies|0.2.4|
|DynamicDescriptionNotes|0.1.9|
|FieldtypePhone|3.1.2|
|FieldtypeRuntimeOnly|0.1.8|
|FieldtypeTable|0.2.5|
|HannaCodeDialog|0.4.4|
|InputfieldPhone|3.1.2|
|InputfieldTable|0.2.5|
|ModuleSettingsImportExport|0.2.9|
|PageProtector|2.0.9|
|PageRenameOptions|2.0.2|
|ProcessAdminActions|0.8.13|
|ProcessChildrenCsvExport|1.8.24|
|ProcessCustomUploadNames|1.3.4|
|ProcessHannaCode|0.3.2|
|ProcessMigrator|0.7.8|
|ProcessModuleToolkit|0.2.5|
|ProcessPageFieldSelectCreator|0.5.11|
|ProcessTracyAdminer|1.1.3|
|ProcessUserActivity|0.0.6|
|ProcessWireUpgrade|0.1.1|
|ProcessWireUpgradeCheck|0.0.9|
|RestrictTabView|1.3.1|
|TextformatterHannaCode|0.3.2|
|TracyDebugger|4.25.9|
|UserActivity|0.0.6|
</details>

**Comment by mpsn** [comment]
This is possibly an issue with the ajax requests associated with file uploads.
I don't recall the exact version numbers, but i remember downgrading the previous version of useractivity (v5 back to v4?) because the notifications kept bugging me and could not be disabled. It got even weirder when you actually did use multiple tabs.
Currently using v6 with all *-self-warnings disabled.

**Comment by ryancramerdesign** [comment]
@adrianbj @mpsn It looks like this occurs if the modify-self option is enabled. I was able to fix it and will post an update, but the fix was to add the following in the UserActivityHooks.php file ready() method, around line ~91 (after this line):
~~~~~
$this->addHookBefore('ProcessPageEdit::execute', $this, 'hookProcessPageEditExecute');
~~~~~~
I added these lines, which seemed to do the trick:
~~~~~
if(isset($_SERVER['HTTP_X_FILENAME']) && $config->ajax && $this->useFeature('modify-self')) {
  // prevent file uploads from triggering modify-self notification
  $this->addHookBefore('ProcessPageEdit::ajaxSave', function(HookEvent $event) {
    $page = $event->arguments(0); /** @var Page $page */
    $event->addHookBefore('Pages::save, Pages::saveField', function(HookEvent $e) use($page) {
      $p = $e->arguments(0); /** @var Page $p */
      if($p->id != $page->id) return;
      $options = $e->arguments('options');
      $options['quiet'] = true; // tell it not to update modified time for ajax uploads
      $e->arguments('options', $options);
    });
  }); 
}

~~~~~

**Comment by adrianbj** [comment]
Thanks @ryancramerdesign - that does work, although I did need to add:
`$config = $this->wire()->config;` before this, otherwise `$config` was undefined and it didn't work.
