### ISSUE TITLE
$pages->count($selector) not working

### ISSUE THREAD

**Issue by trk** [processwire/processwire-issues#1822]
I have a filtered `PageArray`, and I have something like categories and I have number of pages attached to some of these categories. I want to know how many pages attached to these categories.

I am doing this, with this way:

```php
// Filtered pages
$products = $pages->find('template=product');

// get categories
$categories = $pages->find('template=category');
foreach ($categories as $category) {
     // count return wrong result
     bd($products->count("categories={$category}"));

     // this works, but its looking for pages. I need only count result
     bd($products->find("categories={$category}"));
}

```

<img width="182" alt="Ekran Resmi 2023-10-01 14 06 42" src="https://github.com/processwire/processwire-issues/assets/455983/eda71aa1-6b44-4551-86b6-673e404554d2">

**Comment by ryancramerdesign** [comment]
@trk The WireArray/PageArray [count method](https://processwire.com/api/ref/page-array/count/) does not accept any arguments because it's an implementation of PHP's Countable interface so that you can use PHP's `count()` function on any type of WireArray. If you want to count in memory, then you'd do this:
~~~~~
$products->find("categories=$category")->count();
~~~~~
or if you want to count in the database, you'd do this: 
~~~~~
$pages->count("template=product, categories=$category"); 
~~~~~

**Comment by trk** [comment]
I need to make re-search in filtered result and need count result for this. I already use this:
```php
$products->find("categories=$category")->count();
```
Thank you
