### ISSUE TITLE
FieldtypeFile and save hook: throw error in hook still saves the file

### ISSUE THREAD

**Issue by hiboudev** [processwire/processwire-issues#1835]
### Short description of the issue

I'm not sure I'm doing this in a proper way, but anyway there is an inconsistency between adding and removing a file.
In a save hook I throw an error to cancel the save, in this page there is a FieldtypeFile:

- If I deleted the file, it is not deleted, this is expected because of the error thrown that cancel the save,
- But if I add a file it is saved.

### Expected behavior

In both cases it should not save the changes on FieldtypeFile.
Or at least both cases should have the same behavior.

### Actual behavior

In one case the changes are saved (adding a file), and in other case the changes are not saved (removing file).

### Steps to reproduce the issue

1. Add this simplified hook, template "evening-race" must have a FieldtypeFile field:
```
$this->addHookBefore('Pages::save(template=evening-race)',
    function (HookEvent $event): void {
        wire()->error("test");
        throw new WireException("test");
    }
);
```
3. Upload a file and save page => the file has been added and saved.
4. Delete the file and save the page => the file is not removed.

### Setup/Environment

* ProcessWire version:
* (Optional) PHP version: 3.0.228
* (Optional) MySQL version: 8.1
* (Optional) Any 3rd party modules that are installed and could be related to the issue:

**Comment by ryancramerdesign** [comment]
@hiboudev If you cancelled the save with an exception, for the file that was uploaded, it should be in a "temporary" state where it's only accessible in the unformatted state, and it should be automatically removed the next time you try to edit that page. 

When a file is uploaded, this happens during the InputfieldFile::processInput() in a separate ajax request, which happens well before the Pages::save(). InputfieldFile gives it a "temporary" status, at least until you click "Save" in the page editor. 

Deleting files involve no ajax requests. When you delete a file, the deletion actually occurs in a hook after Pages::save(), once it's clear there were no other errors that might prevent the page from being saved. 

A hook before Pages::save can't prevent a file from being uploaded since it was already uploaded at that point. Ajax uploads are very much tied into the life cycle of the InputfieldFile/InputfieldImage by necessity. But if the page save is blocked then the uploaded file should be in a state where it is still temporary and will end up getting automatically deleted once clear it's not going to get saved in the page editor.

**Comment by hiboudev** [comment]
OK I understand. So it's not a bug, I close.
