### ISSUE TITLE
Non-stop Page Refresh of LoginForm

### ISSUE THREAD

**Issue by justojo** [processwire/processwire-issues#1839]
### Short description of the issue

The Processwire admin login form is endlessly doing a page refresh.

### Expected & Actual behavior

After reading the ProcessLogin.js code, I expect the page should only refresh every 300 seconds & not immediately and continuously--multiplying the page requests & making it difficult to login.

### Optional: Screenshots/Links that demonstrate the issue
![LoginFormEndlessRedirecting](https://github.com/processwire/processwire-issues/assets/55796772/9cf2ab30-ab8f-4bb5-9f9b-44eb75c7799f)

I would like to credit [Jay D and netcarver for posting](https://processwire.com/talk/topic/28498-new-site-install-admin-keeps-refreshing/) & pointing out that the server may have a clock time service (ntpd, chronyd or systemd) difference than that of the client side.

### Optional: Suggestion for a possible fix
A solution that seems to address the issue for me is by getting the difference between the server time and the client time and adding that to the maxSeconds in the script (see below), the page refresh problem stopped in my tests.

This issue would only happen if the difference is more than 300 seconds (5 minutes). Adjusting your clock would also solve the problem (or switching NTP servers, adjusting Group policy settings & domain controller). But I thought maybe that a broader solution might help improve the code & the Processwire community. Like:

ProcessLogin.js:
`var startTime = parseInt($('#login_start').val()); // GMT/UTC
// var maxSeconds = 300; // max age for login form before refreshing it (300=5min)
var clientStartTime = Math.floor(new Date().getTime() / 1000); 
var clockDifference = clientStartTime - startTime ;
var maxSeconds = 300 + clockDifference; 

### Steps to reproduce the issue (hypothetical)
1. Adjust your device clock to over 5 minutes
2. Go to your processwire admin login form page
3. Notice the page keeps reloading

### Setup/Environment where I experienced it
Ubuntu & FreeBSD
Apache & NGINX
PHP 8.1.*

* ProcessWire version(s): 3.210 & 3.299

**Comment by ryancramerdesign** [comment]
@justojo Good idea. I haven't come across this situation yet, but it makes sense that a clock could have the wrong UTC time in some cases. While it's supposed to be the same, I suppose we can't ever count on that between server and client. Your solution looks good to me but I'm worried about losing the  immediate refresh if it detects the #login_start is stale via cache, etc., which is one of the most important parts. I was wondering if you could try replacing those lines mentioned above with these to see if it also enables it to work properly? 
```javascript
var 
  maxSeconds = 300, // max age for login form before refreshing it (300=5min)
  queryMatch = location.search.toString().match(/[?&]r=(\d+)/), // match from query string
  queryTime = (queryMatch ? parseInt(queryMatch[1]) : 0), // query string time ?r=123456789
  clientTime = Math.floor(new Date().getTime() / 1000), // client UTC time
  serverTime = parseInt($('#login_start').val()), // server UTC time
  requestTime = (queryTime > serverTime ? queryTime : serverTime), // request time 
  startTime = (requestTime > clientTime ? clientTime : requestTime); // determined start time
```
Keep your browser cache off (dev tools open?) to test. Maybe there's a simpler solution, but the verbosity helped me logic it out. If you adjust the `maxSeconds` value down to 5 or lower, that makes it easier to test out since you can have it act in 5 seconds rather than 5 minutes. What it does is it only uses the server time at first, and then switches to using the client side time as pulled from the query string `r` value. So in your case where the UTC times are different between server and client, it may refresh immediately on the first access so that it can start using the `r` value and establish the baseline time, but then should behave as expected following that.

**Comment by justojo** [comment]
@ryancramerdesign Your version worked well! This is definitely a better approach. I was not even mindful of the cache getting stale part. If so, would an AJAX solution offer a more robust approach?

**Comment by ryancramerdesign** [comment]
@justojo Thanks for testing it out. I'll push that update then. I'm sure ajax would be fine too, but in terms of robust, the full refresh (as current) would be preferable imo.

**Comment by justojo** [comment]
Ok thanks. Issue is fixed & closed.
