### ISSUE TITLE
Current Page does not appear in Page field value

### ISSUE THREAD

**Issue by chriswthomson** [processwire/processwire-issues#1840]
I think this is possibly related to https://github.com/processwire/processwire-issues/issues/842. It seems an odd one to me. Here's the issue I'm seeing:

The **Page** is referenced in a multiple Page field on the homepage for selecting page links to show in the footer. When the **Page** is displayed, it doesn't appear in the footer list (displays on all other pages).

Furthermore, the **Page** is a 'type' selected by a multiple Page field, and on the **Page** we're looking for items that match that 'type'. (context: The **Page** is 'Properties for Sale'. On that page it is looking for areas that have 'Property For Sale' selected as a type. It doesn't appear, so no areas are found.)

I've gotten around this by using `Pages::getByIds()`, but this does seem like odd behaviour? Is this intended, a bug, or suggestive of something awry with my setup?

This is on 3.0.230. Possibly a bug in a recent version as this was only noticed recently, but then again this is on a complex development, so could easy be a bug in that. Will try and get it tested on a clean install soon.

**Comment by ryancramerdesign** [comment]
@chriswthomson I'm trying to duplicate this, but can't seem to. Though I think it's because I might not fully understand how to duplicate it. I added a multi-Page field on my homepage called nav_items. Then I edited the homepage and selected a bunch of pages in nav_items. I updated my _main.php to output them on every page.
~~~~~
<?=pages('/')->nav_items->implode(' / ', "<a href='{url}'>{title}</a>")?>
~~~~~
The output is the same whether I'm viewing a page selected in nav_items or not. But I think the key I'm missing is this part:

> ...and on the Page we're looking for items that match that 'type'. 

I'm not sure I understand this. Can you describe more about how I would duplicate that in terms of setup, code, selectors, API calls, or whatever it translates to?

The issue referred to in #842 is a self-referencing page field, where you edit a page, and select the page you are editing in the page field. PW blocks that since it can create a circular loop. But what you are describing doesn't sound like a self-referencing page field.

**Comment by chriswthomson** [comment]
Thanks @ryancramerdesign,

While debugging, I realised that I specified the first example incorrectly. The footer links were originally a Pages::find with an array of ids:

```
$pages->find([
  'template' => 'legal',
  'include' => 'hidden',
  'sort' => 'sort',
])
->prepend($pages->find([1441, 1569]))
->each('<li><a href="{url}">{title}</a></li>');
```

When visiting page ID 1441 or 1569, they disappear from the list. I've discovered that these pages, while on their page, have the status 'corrupted' and I assume this is from the range of temporary data that I'm assigning to the page object as part of its render. Pages::find is likely including the existing page object and because it sees the corrupted status, removes it from the result. This would explain the other example too.

Pages::getByIds must be fetching a fresh copy of the page.

I'll look further into what is causing the corrupted status and will close the ticket, thanks for taking a look at it.
