### ISSUE TITLE
open_basedir restriction in effect. File(ProcessWire\BasicPagePage.php) is not within the allowed path(s)

### ISSUE THREAD

**Issue by BernhardBaumrock** [processwire/processwire-issues#1862]
### Short description of the issue

Hey @ryancramerdesign could you please have a look at this thread in the forum where adrian and me don't know why PW checks for is_file(--some-pageclass-here-): https://processwire.com/talk/topic/29375-error-on-request-info-panel-on-fresh-installation-when-editing-the-home-page/#comment-238031

### Expected behavior

custom pageclass names should not end up in is_file()

### Actual behavior

I've installed several installations of PW on several servers today and all show the same behaviour

### Steps to reproduce the issue

- install pw
- install tracy debugger
- edit the home page
- see the error pop up in tracy's request info panel

### Setup/Environment

* ProcessWire version: 3.0.232
* (Optional) PHP version: 8.1

**Comment by adrianbj** [comment]
Just an FYI that I can't reproduce this. I don't have any open_basedir restrictions in place, but it might not be as simple to reproduce as just those listed steps.

**Comment by BernhardBaumrock** [comment]
Ok thx @adrianbj wasn't aware of this. I'm seeing this on fresh installations of PW with the blank profile!

**Comment by ryancramerdesign** [comment]
@BernhardBaumrock @adrianbj I can't duplicate the error either, but the is_file ProcessWire/BasicPagePage.php isn't the right kind of path, so it looks like WireClassLoader is getting an incorrect value from the ModulesInfo class, and I've just pushed a fix for that. An open_basedir error shouldn't be here even with the incorrect path, since it would still be relative inside PW's installation, but since it's got the wrong kind of slash, maybe it's something that only happens in some environments. Hopefully the fix will correct it but if still seeing the error please let me know. Thanks.

**Comment by BernhardBaumrock** [comment]
Hey @ryancramerdesign I'm still getting this error. I can create a test server for you if you want to have a look into that issue?

**Comment by ryancramerdesign** [comment]
@BernhardBaumrock If possible, I'd like to be able to duplicate it locally, otherwise I'm not in an environment where I have the tools to properly debug, and it becomes more about troubleshooting a server or individual installation. Since we did fix the issue I was able to duplicate, it might be good for us to first look at what's not working in your case. There should be an is_file() call, but it shouldn't be to a path outside of PW.  So what I'd suggest doing is overriding the is_file() call in a /test.php file in your PW installation root, like this:
~~~~~
<?php namespace ProcessWire;
include("./index.php");
error_reporting(E_ALL);
ini_set('display_errors', 1);
echo "<pre>";

function is_file($file) {
  echo "$file\n";
  return \is_file($file);
}

$p = $pages->get(1); // or ID for page using custom class
echo $p->className();
~~~~~
Access the test.php URL in your browser and that should give you a list of all files passed to is_file(). You should see an error next to the one where the issue is. Once you've found it, change the is_file() function:
~~~~~
function is_file($file) { 
  if(strpos($file, 'DefaultPage.php') !== false) { // match whatever is the problematic file
    echo Debug::backtrace([ 'getString' => true ]); 
  }
  return \is_file($file);
}
~~~~~
Please let me know of the problematic filename and the backtrace. Thanks.

**Comment by BernhardBaumrock** [comment]
Thx @ryancramerdesign that worked well, but I still don't know how to proceed.

I got several checks for pageclass names:

```
ProcessWire\MarkupSitemapXML.php
ProcessWire\ProcessJumplinks.php
ProcessWire\MagicPages.php
ProcessWire\DefaultPage.php
ProcessWire\HomePage.php
ProcessWire\AdminPage.php
ProcessWire\RolePage.php
ProcessWire\UserPage.php
ProcessWire\LanguagePage.php
ProcessWire\LanguagePage.php
ProcessWire\PermissionPage.php
ProcessWire\BasicPagePage.php
ProcessWire\ExhibitionsPage.php
ProcessWire\ExhibitionPage.php
ProcessWire\RocksettingsPage.php
ProcessWire\WorksPage.php
ProcessWire\WorkPage.php
ProcessWire\404Page.php
ProcessWire\BlogPage.php
ProcessWire\BlogPostPage.php
ProcessWire\CataloguesPage.php
ProcessWire\CataloguePage.php
ProcessWire\ProjectPage.php
ProcessWire\ProjectsPage.php
ProcessWire\RepeaterRocksettingsRedirectsPage.php
ProcessWire\RepeaterRpbChronologyRowsPage.php
ProcessWire\RepeaterVenuesPage.php
ProcessWire\RockpagebuilderDatapagePage.php
ProcessWire\RockpagebuilderblockChildrenPage.php
ProcessWire\RockpagebuilderblockChronologyPage.php
ProcessWire\RockpagebuilderblockContenttabsPage.php
ProcessWire\RockpagebuilderblockDownloadsPage.php
ProcessWire\RockpagebuilderblockGalleryPage.php
ProcessWire\RockpagebuilderblockHeadlinePage.php
ProcessWire\RockpagebuilderblockHeroPage.php
ProcessWire\RockpagebuilderblockNewsPage.php
ProcessWire\RockpagebuilderblockPageheadingPage.php
ProcessWire\RockpagebuilderblockTextPage.php
ProcessWire\RockpagebuilderblockVideoPage.php
ProcessWire\RockpagebuilderblockWidgetPage.php
```

And this is the backtrace:

```
Array
(
    [0] => Array
        (
            [file] => /wire/core/WireClassLoader.php:354
            [call] => ProcessWire\is_file("ProcessWire\DefaultPage.php")
        )

    [1] => Array
        (
            [file] => /wire/core/WireClassLoader.php:313
            [call] => WireClassLoader $classLoader->findClassInPaths("DefaultPage", [ 'ProcessWire\' ])
        )

    [2] => Array
        (
            [file] => /wire/core/Templates.php:862
            [call] => class_exists("ProcessWire\DefaultPage")
        )

    [3] => Array
        (
            [file] => /wire/core/Template.php:1441
            [call] => $templates->getPageClass(Template $obj, true)
        )

    [4] => Array
        (
            [file] => /wire/core/PagesLoader.php:1312
            [call] => Template->getPageClass()
        )

    [5] => Array
        (
            [file] => /wire/core/Pages.php:217
            [call] => PagesLoader->getById(array(8))
        )

    [6] => Array
        (
            [file] => /wire/core/ProcessWire.php:625
            [call] => $pages->init()
        )

    [7] => Array
        (
            [file] => /wire/core/ProcessWire.php:582
            [call] => ProcessWire $wire->initVar("pages", Pages $obj)
        )

    [8] => Array
        (
            [file] => /wire/core/ProcessWire.php:315
            [call] => ProcessWire $wire->load(Config $obj)
        )

    [9] => Array
        (
            [file] => /index.php:52
            [call] => ProcessWire $wire->__construct(Config $obj)
        )

    [10] => Array
        (
            [file] => /test.php:2
            [call] => include("....../release-7573966891-b71d4bf1/index.php")
        )

)
HomePage
```

I'm having this on all my servers and I'm having the same setup everywhere using RockMigrations to deploy everything with symlinks and due to the serverpanel having FollowSymlinksIfOwnerMatch. Can that mean anything?

Does all that make any sense to you?

This is the code I jused for debugging (just for reference):

```
<?php namespace ProcessWire;
include("./index.php");
error_reporting(E_ALL);
ini_set('display_errors', 1);
echo "<pre>";

// function is_file($file) {
//   echo "$file<br>\n";
//   return \is_file($file);
// }

function is_file($file) {
  if(strpos($file, 'ProcessWire\DefaultPage.php') !== false) { // match whatever is the problematic file
    echo "<pre>" . print_r(Debug::backtrace(), true) . "</pre>";
  }
  return \is_file($file);
}

$p = $pages->get(1); // or ID for page using custom class
echo $p->className();
```

**Comment by ryancramerdesign** [comment]
@BernhardBaumrock Thanks for running that. All those ones that start with `ProcessWire\` shouldn't be there, and aren't on  mine at least. They are behaving as if there were a `$classLoader->addNamespace('ProcessWire', '\ProcessWire')` call somewhere. Are all your installs Windows based? I'm wondering if it might be related to directory separator.

**Comment by ryancramerdesign** [comment]
@BernhardBaumrock I thought of something else to try. First, double check that line 1367 of /wire/core/ModulesInfo.php contains exactly this:
~~~~~
if($namespace === 'ProcessWire') return false;
~~~~~
If not, then that's the problem. But if it does already contain that, then on the next line try adding this:
~~~~~
echo "$namespace<br>";
~~~~~
Then run the script above again, but you can remove the is_file() function. I'm wondering if it ends up outputting something like `ProcessWire\` anywhere, rather than `ProcessWire` ?

**Comment by BernhardBaumrock** [comment]
Oh my god, Ryan. I was not on the latest core! Upgrading helped. I messed up the core versions because I'm working on 3 projects in parallel atm. So sorry for wasting your time! :( Thx for the fix!

**Comment by ryancramerdesign** [comment]
@BernhardBaumrock No problem, I'm glad that was it. :)
