### ISSUE TITLE
WireCache: filemtime(): stat failed for cache/WireCache.maint warning and custom error handlers

### ISSUE THREAD

**Issue by kooderi** [processwire/processwire-issues#1886]
### Short description of the issue

WireCache.php raises a PHP warning `filemtime(): stat failed` when checking the age/existence of WireCache.maint and the file does not exist. 

Even though this warning is suppressed with `@` operator in the function call, the warning is still sent to custom error handlers.

### Expected behavior

The `@filemtime(<...>)` call should not cause warnings because of the `@` operator

### Actual behavior

The warning is not displayed, but is still sent to custom error handler if one has been registered to handle warning-level errors.

### Suggestion for a possible fix

Instead of the error-control operator a check for file existence could be added.
File **/wire/core/WireCache.php:873**:

Current code:
```
if(@filemtime($filename) > (time() - 600)) return false;
```

Suggested change:
```
if(is_file($filename) && filemtime($filename) > (time() - 600)) return false;
```

### Setup/Environment

* ProcessWire version: 3.0.229
* PHP version: 8.1

**Comment by adrianbj** [comment]
I think given the changes to the `@` operator in PHP8 it really shouldn't be used anymore (not that it probably ever should have been used in production code).

**Comment by ryancramerdesign** [comment]
@kooderi I've added a file existence check prior to the `@filemtime().`

@adrianbj While the `@` is problematic in the wrong hands, it has some very worthwhile use cases when used properly. The purpose of a `@filemtime()` is both to identify that the file exists and get its modification time, in one function call. Without it, we have to poll the file system twice with two function calls to do the same thing, which is not great.

**Comment by BernhardBaumrock** [comment]
@adrianbj and @ryancramerdesign do you have any links for me to learn more about that topic?

**Comment by adrianbj** [comment]
@ryancramerdesign - I understand your point about good vs bad use of it, and I think that possibly a `filemtime()` call on a non-existant file should return `false` or `null` rather than an error, but that's not something we can change. 

I can't see any measurable increase in time using a `file_exists()` check - we are talking less than a millisecond for these operations. And in fact, in my testing a failed `@filemtime` is slower than a combined `file_exists()` and `filemtime()`. There is info online about why this happens and it's related to internally changing PHP's error reporting etc.

**Comment by ryancramerdesign** [comment]
@adrianbj This is a case where it's only called once in the request, so that's right it doesn't matter here, which is why I made the change here. I'm glad to hear that in your environment a file_exists before the filemtime works out better. In other server environments (like the one we use on the PW site) every function call hitting the file system has overhead associated with it, as the file system is geographically distributed. So I'll usually do everything I can to avoid unnecessary file system calls.

**Comment by kooderi** [comment]
Thank you @ryancramerdesign
