### ISSUE TITLE
Can't add Home to Page field via PageAutocomplete input.

### ISSUE THREAD

**Issue by jasonhuck** [processwire/processwire-issues#19]
### Short Description of the Issue
When using Page Autocomplete with a Page field, with no restrictions or filters on the results, the user cannot add the home page. Typing "Home" in the field does make the page appear in the autocomplete menu, but choosing it does not add it to the list of selected pages.

### Expected Behavior
Choosing the home page from the autocomplete menu should add it to the list of selected pages, just as it does for any other page.

### Actual Behavior
When the user chooses the home page from the autocomplete menu, nothing happens. There are no javascript errors in the console.

### Steps to Reproduce the Issue
1. Create a Page field with no restrictions or filters, using PageAutocomplete as the input type.
2. Add this field to any template.
3. Create a page using that template, and attempt to add the home page using that field.

### Setup/Environment
* ProcessWire version: Confirmed in 2.7 and 3.0
* PHP version: 5.4.16

Forum thread: https://processwire.com/talk/topic/14398-selecting-the-home-page-with-page-autocomplete/

**Comment by BitPoet** [comment]
This is likely a bug in InputfieldPageAutocomplete.js' duplicate checking (unless the exclusion of home was intentional).

I've posted an more detailed explanation in [this thread](https://processwire.com/talk/topic/14398-selecting-the-home-page-with-page-autocomplete/?do=findComment&comment=129579).

It boils down to changing the selector for the duplicate checking to exclude the template for new items, which is preset with a value of "1" (matching the id of "home").

Code in question in [InputfieldPageAutocomplete.js](https://github.com/processwire/processwire/blob/master/wire/modules/Inputfield/InputfieldPageAutocomplete/InputfieldPageAutocomplete.js#L290):
```$ol.children('li').each(function() {```
Fix:
```$ol.children('li:not(.itemTemplate)').each(function() {```

**Comment by jasonhuck** [comment]
I can confirm that BitPoet's suggested fix solves the issue for me in PW 2.7 with no apparent side effects thus far.

**Comment by ryancramerdesign** [comment]
Thanks I've pushed @BitPoet fix
