### ISSUE TITLE
NullPage that lacks ID in PageArray causes invalid selectors

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1904]
### Short description of the issue

The docs for [NullPage](https://processwire.com/api/ref/null-page/) state that:

> The id property will always be 0 for a NullPage.

But this doesn't seem to be the case and it can cause and invalid selector when a NullPage exists in a PageArray and that PageArray is then used in a selector string (making use of `PageArray::__toString`).

Demo case:

![2024-04-07_092938](https://github.com/processwire/processwire-issues/assets/1538852/11f660c7-97e2-4335-93aa-771b8cd49cb6)

The general point here is that it ought to be safe to use a PageArray in a selector without the user first needing to look for and remove any pages that lack an ID.

### Setup/Environment

* ProcessWire version: 3.0.236

**Comment by Toutouwai** [comment]
It looks like the issue is with `NullPage::__toString`. Why does it override `Page::__toString()`, which would otherwise return '0' and allow `PageArray::__toString` to work as expected in selectors?

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I've pushed a fix for this issue. I'm not sure PageArray should allow a NullPage to exist in it, but since it already does I don't think I should change it. The reason a NullPage string value is blank string rather than '0' string is because that differentiates it from a regular page that doesn't yet have an ID (i.e. a new Page that hasn't been saved yet.)

**Comment by Toutouwai** [comment]
Thanks
