### ISSUE TITLE
Images are clipped

### ISSUE THREAD

**Issue by cb2004** [processwire/processwire-issues#191]
### Short description of the issue

When images are uploaded like a logo that are cropped right to the edges, when they are resized on the frontend the images are clipped and lose pixels. This is not really noticeable on normal images, but with logos it is.

### Expected behavior

The image should just be resized without any cropping.

### Actual behavior

The image seems to lose pixels on the left and right on resize

### Optional: Suggestion for a possible fix

This is not a possible fix, but if the image field has max dimensions in the admin the image is resized correctly. It is just when something like the below is used it gets clipped:

`$page->image->width(360)->url;`

### Steps to reproduce the issue

There is a file attached which can be used to reproduce this issue

![pfizer](https://cloud.githubusercontent.com/assets/6205980/23125859/c1707d6e-f76b-11e6-89d7-2dde8cc1cce3.png)

### Setup/Environment

* ProcessWire version: 3.0.52

**Comment by ryancramerdesign** [comment]
I can't spot any visible clipping here after testing with the image above. How many pixels are you seeing get clipped? @horst-n are you able to reproduce?

**Comment by postscript-chris** [comment]
It ends up like this

![c1707d6e-f76b-11e6-89d7-2dde8cc1cce3 360x0](https://cloud.githubusercontent.com/assets/25509498/23665584/cb76ef0a-0350-11e7-8d82-48b399070182.png)

**Comment by adrianbj** [comment]
Just a quick observation - the attached image already looks to be clipped on the right side - it definitely isn't a complete sphere.

**Comment by cb2004** [comment]
It ends up like this:

![c1707d6e-f76b-11e6-89d7-2dde8cc1cce3 360x0](https://cloud.githubusercontent.com/assets/6205980/23665645/f665dbea-0350-11e7-9e2a-5a314ff9885d.png)

**Comment by cb2004** [comment]
@adrianbj yes, possibly not a perfect sphere, but it also happens with images that are not spheres. Upload in admin handles it just fine, the above was output with $page->image->width(360)->url;

**Comment by adrianbj** [comment]
I just did some testing and can confirm this. I tried a different image (attached).

Interestingly it depends on the size you set.

At 360 it clips on the right.
At 250 it looks correct.
At 200 it clips left and right.

![logotest](https://cloud.githubusercontent.com/assets/871211/23666616/5eecdb8c-0310-11e7-81d9-f8cdded10b9a.png)

**Comment by ryancramerdesign** [comment]
Thanks for testing Adrian, glad you found something there. That explains
why I didn't see it, as I was testing using PW default thumbnail size at
260px, and not seeing clipping there. I don't know the image resizing code
very well at this point, so I think we need the help of @horst-n for this.

**Comment by horst-n** [comment]
Hi,
sorry for the delay! I saw this just now, as I had have no time for anything else then family and working.
My first suggestion would be some sort of rounding issue. But I need to inspect this thoroughly. DOn't know when I will find time for it, so - if it takes to long, don't hesitate to ping me. :) (Best way is a PM via our forum!)

**Comment by horst-n** [comment]
short update: I have tested it, and with method width() we can have:
- no clipping, if there is no float result
- 1px clipped at right, if we have float result for new size OR new position (due to rounding)
- 1px clipped right + 1px clipped left if we have float results for new size AND new position (due to rounding)
Currently we don't have that effect with method height().
I will keep you updated.

**Comment by horst-n** [comment]
don't know what was going on with my pull request. (?)
So, just to clarify:
I have made 2 changes in file ImageSizerEngine:
https://github.com/horst-n/processwire-1/blob/898db699abb6f5e20534e41d3a20f75f115ff5b2/wire/core/ImageSizerEngine.php#L626-L629
and
https://github.com/horst-n/processwire-1/blob/898db699abb6f5e20534e41d3a20f75f115ff5b2/wire/core/ImageSizerEngine.php#L1413-L1416

This solved it for me in various testings.
Would be nice, if you, @adrianbj and @ryancramerdesign can cross check this please!

**Comment by adrianbj** [comment]
@horst-n and @ryancramerdesign - that change seems to be working great for me.

Of course users should be made aware that they will need to remove existing image variations from their site/assets/xxxx/ folders to ensure the new non-clipped version is re-created.

**Comment by ryancramerdesign** [comment]
This is great thanks @horst-n ! I have added your fix in the latest commit. 

Btw, I was curious if you'd seen the Guetzli, the new open source JPEG encoder by Google that apparently creates up-to 20-30% smaller jpegs. Do you think this has potential future in PW as an ImageSizerEngine option? 

- Blog post: https://research.googleblog.com/2017/03/announcing-guetzli-new-open-source-jpeg.html
- GitHub repo: https://github.com/google/guetzli

**Comment by horst-n** [comment]
Guetzli would be a perfect fit for every CLI image engine. With just adding one step to the end of the manipulation chain, we will get better compressed results.
Btw, I'm already using this approach with jpegOptim since years. What we should talk about, is to create a parent (single) ImageCompressionEngine, that handles some different compression tools like the above and possibly more. To invoke the compression, we should define a param that, when get passed with image-methods 
- a) set the quality temporarily to 100% for the regular image processing, 
- b) invoke the compression tool at the end, with the original quality setting (lesser than 100%)
It is like I'm saying for years now and as you can read in the blog post of the authors of Guetzli. They say exact the same, and they know what they are talking about. :)

Unfortunately I have not much time atm. I will contact you private in, maybe 2 month, when there is more time. But something like an embedded compression mechanism / image engine is definetly on my wish-list / todo-list. 👍

**Comment by teppokoivula** [comment]
There are a bunch of different modules floating around with the sole purpose of optimizing images, and some users are using a CDN or a non-PW server-side solution for that purpose. Clearly there's a market for these tools.

Sounds to me like this would be a new module class -- right? That way it could be enabled/disabled with ease, and one could use exactly the engine they need :)

**Comment by horst-n** [comment]
@teppokoivula yep. It should be something like we have now with the image engines, but with less complexity. The compression modules, each on its own, or a container module on its children, sets the hirarchicaly order, if there are multiple compressor modules.
Compressors are decoupled, - to invoke compression, images need to pass a param, like 'compress' or 'forceCompression', to get the things done right! The things done right means: when compression is requested, temporarily set all quality settings to 100%, so that the generated source for the compressors has best quality and therefore will result in lowest filesize!
The third-party compressor modules need to take the highquality source image, process their (remote-)compression and give back a return value like true|false. On true, the image is compressed and we are finished, on false the image is not compressed and we need to save it once with a lesser quality setting, as fallback for e.g. temporarily not reachable remote services, etc.
