### ISSUE TITLE
Inserting emojis in body text: text afterwards is deleted

### ISSUE THREAD

**Issue by beatep** [processwire/processwire-issues#192]
### Short description of the issue

I inserted a emoji on my firefox/mac with Edit->Emoji in my body field. Saved and the emoji and the text following the emoji was missing.

### Expected behavior

Text should not be deleted. If emoji could not be handled: delete the emoji but not the text.

### Actual behavior

Text is beeing deleted.

### Setup/Environment

* ProcessWire version: ProcessWire 3.0.52
* (Optional) PHP version: PHP Version 5.6.30
* (Optional) MySQL version: mysqlnd 5.0.11-dev

**Comment by ryancramerdesign** [comment]
Thanks, I've pushed a fix for this issue. It turns out it was MySQL that truncates the text because its implementation of UTF-8 does not cover 4-byte characters. Because the detection and replacement of emoji adds some overhead, I figured we should only enable it for those that need it. I put it under a `$config->dbStripMB4 = true;` setting that you'll want to add to your /site/config.php file. For future installations, you may want to choose the `utf8mb4` charset at installation time, as this one supports emoji.
