### ISSUE TITLE
Markup Regions: nested/recursive manipulations not working

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#195]
### Short description of the issue

Nested/recursive manipulation of elements is not working as per the blog post introduction.

### Expected behavior

From the [blog post](https://processwire.com/blog/posts/processwire-3.0.49-introduces-a-new-template-file-strategy/):

> By that token, the elements that you manipulate don't even have to be part of the main document markup. This template strategy can be nested and go recursive. Meaning you can manipulate something you added from a template file or some other include(), which could be useful in certain cases where you might want it.

And a comment by @ryancramerdesign:

> By nesting, I mean that you can do this (pretend this is HTML)
> 
> [div id=photo class=pw-append-sidebar]
> [img src='...']
> [/div]
> 
> [caption class='pw-append-photo']
> Caption added to photo div
> [/caption]

### Steps to reproduce the issue

In _main.php...
```
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title><?= $page->title ?></title>
</head>
<body>

<div id="main">
	<p>Default main content.</p>
</div>

</body>
</html>
```

In home.php...
```
<div id="box" pw-append="main">
	<p>Paragraph 1</p>
</div>

<p pw-append="box">Paragraph 2</p>
```

The #box div and Paragraph 1 are appended to #main, but Paragraph 2 is not included at all in the compiled output.

### Setup/Environment

* ProcessWire version: 3.0.52
* (Optional) PHP version: 7

**Comment by ryancramerdesign** [comment]
I ended up removing the recursive/nested support several weeks back. First reason was that it could consume a whole lot of overhead in some cases. Secondly is, whenever I used it, it seemed to add confusion and seemed more straightforward without it. Markup regions are supposed to be about making things simpler, and the recursive stuff seemed counter to that. It just didn't seem that useful relative to the overhead it added.

**Comment by Toutouwai** [comment]
> I ended up removing the recursive/nested support several weeks back.

Right, good to know.

I know you must be super busy, but it would be great if you could comment on some of the other issues regarding Markup Regions that have been raised here in GitHub and the forums. The Markup Regions feature got a prominent launch in two blog posts and it seems like a good number of people have adopted it, but there are questions around its use that could do with some follow up.

I have several sites under development currently where I am using Markup Regions but I need to make a call about whether I will continue with the feature or go back to my previous approach. And that sort of depends on if the Markup Regions feature is something that is still under active development and will be enhanced based on user feedback, or if it will essentially stay as-is and people can decide if they want to use it or not based on its current form (which would be fine). 

For me the most important issue is the fact that the regions must be determined by an HTML element that will remain in the final output. You can't create a 'placeholder' element in _main.php that serves to identify a markup region but will not itself appear in the output. I [raised this in an existing GitHub request](https://github.com/processwire/processwire-requests/issues/78#issuecomment-281182114) but it's actually a different proposal so I have opened a new request here:

https://github.com/processwire/processwire-requests/issues/82

Would be great to get your thoughts on this proposal.

**Comment by ryancramerdesign** [comment]
Yes of course markup regions will definitely continue to be developed, and it's what I'm using for the new site profiles. But they are intended to work with the document markup and I've been trying to avoid a system where you create markup tags that aren't actually used for output. When it comes to a placeholder approach, PHP variables are definitely a preferable and more efficient route. The wireRegion() / region() functions are good for this as well. Though in the end we'll adapt markup regions to however people want to use it, and if that includes placeholders then maybe that's okay. My current opinion is just that I think markup regions kind of lose their differentiation and benefit if used only as a placeholder system. 

You may already know this, but you can also do this below. Though this is only part of what you are talking about, since the id attribute references an element in the document markup `<head id='html-head'>` and not a placeholder: 
~~~~
<pw-region id='html-head' pw-append>
  <link ...>
  <link ...>
  <script>...</script>
</pw-region>
~~~~
The "pw-region" tag name can be anything, since using a boolean attribute here suppresses the wrapping "pw-region" (or whatever you name it) from appearing in the markup. From what I understand, iyou'd like there to be a special tag name like "pw-region" that would always be removed from the markup, while leaving anything within it still there?

**Comment by Toutouwai** [comment]
> You may already know this, but you can also do this below.

Thanks, yes, I'm doing that already. The thing is that doing this places the appended stylesheets below scripts that are part of the default `<head>` in _main.php. My preference is to have all stylesheets load before any scripts.

> The "pw-region" tag name can be anything, since using a boolean attribute here suppresses the wrapping "pw-region" (or whatever you name it) from appearing in the markup.

It would be great if that were true across the board (using a boolean attribute suppresses the wrapping element from appearing in the markup). But it is not the case for `pw-before` and `pw-after`, where you may want to insert multiple elements before or after but if you use a wrapping element then it gets included in the markup. In fact, if you do this in a template file...
```
<div id="main" pw-after>
	<p>Paragraph 1</p>
	<p>Paragraph 2</p>
</div>
```
...you end up with invalid markup because you get the existing div#main in _main.php plus a second div#main from the template.

I am proposing the `<pw-region>` placeholder as a way around these two issues - but only as an addition to the existing behaviour, not as a replacement of it.

Further discussion should probably go under the [new request](https://github.com/processwire/processwire-requests/issues/82).

**Comment by ryancramerdesign** [comment]
> It would be great if that were true across the board (using a boolean attribute suppresses the wrapping element from appearing in the markup).

That was an error–just pushed a fix. It should now behave the same with the before/after versions.

> I am proposing the `<pw-region>` placeholder as a way around these two issues - but only as an addition to the existing behaviour, not as a replacement of it.

I understand now and agree it makes sense. I have added support for this in the latest commit. You can use either `<region id=something>` or `<pw-region id=something>`. Thanks.
