### ISSUE TITLE
Animated gif can't be resized

### ISSUE THREAD

**Issue by PawelGIX** [processwire/processwire-issues#1967]
### Short description of the issue
Animated gif can't be resized.
I got error in logs.
```
Index invalid or out of range
In /wire/modules/Image/ImageSizerEngineAnimatedGif/gif_decoder.php line 194
```
Without ImageSizerEngineAnimatedGif installed animation disappers.

Here is gif.
[title.gif.zip](https://github.com/user-attachments/files/16887976/title.gif.zip)

![title](https://github.com/user-attachments/assets/04ac979d-d961-485f-9440-c8d0efd3d5bf)

* ProcessWire version: 3.0.229
* (Optional) PHP version: 8
* (Optional) MySQL version: 5

**Comment by gideonso** [comment]
@PawelGIX 

The error occurs when enabling jit with parameters in php 8.0-8.1:
opcache.jit_buffer_size=512M
opcache.jit=tracing

The error does not occurs when enabling jit with parameters in php 8.0-8.1:
opcache.jit_buffer_size=512M
opcache.jit=function

This is a PHP  8 bug. You can upgrade to PHP PHP 8.3, 8.2.12 and 8.1.25 in which the bug is fixed.

Or you can change opcache.jit=tracing to opcache.jit=function in your php.ini.
