### ISSUE TITLE
$pagearray->add() and $pagearray->remove() inconsistent in support for page ID

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1973]
### Short description of the issue

I expected `$pagearray->add()` and `$pagearray->remove()` to be similar but opposite methods supporting the same argument types.

But `$pagearray->add($page_id)` works whereas `$pagearray->remove($page_id)` does not.

![2024-09-18_164940](https://github.com/user-attachments/assets/d6190101-674c-4968-a728-561b9091b837)

Is this expected? Can they be made consistent with each other by adding support for `$pagearray->remove($page_id)`?

### Setup/Environment

* ProcessWire version: 3.0.241

**Comment by ryancramerdesign** [comment]
@Toutouwai I think that would be a breaking change because the remove() method accepts an item or an index number, and PageArray does not use IDs as indexes. In this case, PageArray doesn't actually implement its own remove() method and instead just uses the WireArray::remove() method. If building from scratch, supporting the ID in remove() sounds good, but it's very possible that existing code somewhere else relies upon the behavior of remove() being consistent across WireArray types. This is not an issue for the add() method since the index doesn't apply until after the item is added.

**Comment by Toutouwai** [comment]
That makes sense, thanks for the explanation.
