### ISSUE TITLE
Can't upload images after converting InputfieldFile to InputfieldImage

### ISSUE THREAD

**Issue by timohausmann** [processwire/processwire-issues#199]
### Short description of the issue

Given an InputfieldFile, I tried to upload images and was wondering about missing thumbnails. I then changed the  _Inputfield Type_ in the _Details Settings_ from "File" to "Image", only to find that I couldn't upload any images at all anymore.

### Expected behavior

After changing the _Inputfield Type_  from "File" to "Image", I would expect it to be able to upload images to this field. 

### Actual behavior

After changing the _Inputfield Type_, uploading images will fail with the error message "Invalid Image".

### Optional: Suggestion for a possible fix

Maybe the Option _Inputfield Type_ should not be visible in the _Details Settings_, so it's clear to the user to use a "Image"-Field instead from the beginning on, and not convert a File-Field to Image.

### Steps to reproduce the issue

1. Create new "File" Field
2. Change _Details_ -> _Inputfield Type_ from "File" to "image"
3. Try to upload an image - it will fail

### Setup/Environment

* ProcessWire version: 3.0.42

**Comment by ryancramerdesign** [comment]
Thanks Timo I've pushed an update for this and added a note to it "Do not change this setting unless instructed to do so by a 3rd party Inputfield module" (which is what that setting is for). 

I think what you were intending to do is change the field type, and this is something you'd want to do from the main tab in the field editor. Though rather than changing the type of an existing field, it's usually preferable to just create a new field and delete the old one. Only change the type if you need to maintain some data already present in the field. After changing the type, you'll need to go through all the settings to make sure none present are still specific to the old type.
