### ISSUE TITLE
Alternative secure chmod for WireDatabaseBackup files

### ISSUE THREAD

**Issue by hettiger** [processwire/processwire-issues#20]
### Short description of the issue

Using `$config->chmodFile` for .sql files is a bad idea on some shared hosting environments.

### Real world example

My Host recommends __chmod 640__ for .htaccess-, __.html-__, .txt and __image files__ etc.
Therefore I've set `$config->chmodFile = '0640';`

When it comes to __directories__ they suggest __chmod 710__.
Therefore I've set `$config->chmodDir = '0710';`

Now for __PHP scripts__ (guess that also applies to __SQL files__) they suggest __chmod 600__.
Unfortunately I have not found any matching `$config` property for this case.

#### Conclusion

__I think using chmod 640 for SQL files in this case is insecure and this needs to be fixed.__

I'd even say ProcessDatabaseBackups, WireDatabaseBackup and all modules that rely on these must be considered insecure on shared hosting environments.

### Solution

Make `ProcessDatabaseBackups` a `ConfigurableModule`.

__OR__

Introduce a new config property `$config->chmodSensitiveFile` and use this instead.

_I think a new config property is better because of 3rd party modules that may rely on `WireDatabaseBackup`. (It may be helpful in other scenarios as well ...)_

__ProcessWire version: 3.0.35__

**Comment by LostKobrakai** [comment]
In a shared hosting environment no other user should be able to read your files, no matter which files they are. So if 0640 is enough for your data files it's enough for your sql files.

The reason for your host to suggest php scripts  to have a chmod of 0600 is probably, so that the webserver cannot modify those files in case you fucked up and a hacker got access to modify your php files via your website. But for such an attack to be useful the modifiable files need to be executable, which only your php files are. Sql files are essentially as useful to modify as any .txt file with sensitive data in it.

**Comment by ryancramerdesign** [comment]
Most shared hosts run with Apache running as the user. If instead
Apache/PHP is running as same user for all, there really is no way I know
for certain to protect your files from other users (not even 0600), while
still being read/write to PW, unless the host has implemented some other
kind of protection. Assuming Apache is user, and we don't know what group
is, I probably wouldn't use anything but 0600 for your chmodFile and 0700
for chmodDir. While one could add more chmod config properties, it would
likely be redundant because they'd have the same values.

**Comment by hettiger** [comment]
@LostKobrakai You seem to be more experienced in the matter of file permissions and shared hosting environment setups than I am. I happily accept that answer feeling a bit more secure now.

Do you think a new config property like `$config->chmodSensitiveFile` is completely pointless then? (What about module upgrades for example. These will eventually write new PHP files to the system ...)

**Comment by hettiger** [comment]
@ryancramerdesign Thank you for the detailed explanation Ryan. I think this issue should be closed without further action. Sorry for the mess thought :-/

**Comment by ryancramerdesign** [comment]
Thanks, but it's not a mess thought at all, it's quite a good one. You are
thinking the right way. I've had similar thoughts many occasions, but
always come back to finding out the permission choices would end up the
same as what would be right for the existing properties. It's always a bit
tough when it comes to shared hosts, security gets a lot more complicated
depending on how things are setup at the host. But if you can stick with
0600   and have it still work for the website, and you can still modify
those same files via ftp, I would stick with that.
