### ISSUE TITLE
PagefileSecure = true with Page::isPublic() hook not working as expected

### ISSUE THREAD

**Issue by thetuningspoon** [processwire/processwire-issues#204]
### Short description of the issue

Please see https://processwire.com/talk/topic/15622-pagefilesecure-and-pageispublic-hook-not-working/ 

### Expected behavior

I expected that when Config::pagefileSecure = true, setting the return value of Page::isPublic() to false using an after hook would prevent direct access of files in /site/assets/. 

### Actual behavior

Files are still accessible.

### Steps to reproduce the issue

See https://processwire.com/talk/topic/15622-pagefilesecure-and-pageispublic-hook-not-working/

### Setup/Environment

PW 3.0.42

**Comment by ryancramerdesign** [comment]
This behavior is not something that you can change with a runtime hook because it involves a physical renaming of the file directory. If it were responding to the hook in that way, it would create chaos on the file system, especially when more than one person might be accessing a file. What I would suggest instead is making the pages protected by default (ensuring the files are not directly accessible), and then using a Page::viewable hook to selectively allow access to the page as you see fit. Though what might be better: since your need sounds a little different from what pagefileSecure is meant to do, you may want to consider the other Fieldtype mentioned in the listed thread (FieldtypeFileSecure), as that sounds potentially more consistent with your need here?
