### ISSUE TITLE
Uploading a module via zip should not break PW

### ISSUE THREAD

**Issue by beatep** [processwire/processwire-issues#210]
### Short description of the issue

I had a PW 3.0.48 running on PHP 5.3.14 smoothly. After I installed the module [FrontendUser](https://bitbucket.org/pwFoo/frontenduser/overview), which seems to need PHP 5.4 because it uses brackets, via a zip file, an parser error occured, I couldn't delete the module from the site folder as the files belonging to the web server user and my PW was broken.

### Expected behavior

I would have expected that installation says "could not be installed because of outdated php version."

**Comment by LostKobrakai** [comment]
PW should already do that if a minimal php version for the module is supplied, otherwise there's probably not much we can do. Syntax errors are nothing we can recover from more gracefully.

**Comment by ryancramerdesign** [comment]
Unfortunately things like parse errors occur from PHP prior to PW seeing a file, so there's no way that we can detect that. Something that can help though is if the module author uses a ModuleName.info.php or ModuleName.info.json file rather than a getModuleInfo() method in the module file. When that's the case, PW can know the module's requirements without PHP executing the module's file, because the requirements are contained in a separate PHP or JSON file. This is what I recommend if a module has requirements that are different from PW's core. 

Another thing is that when it comes to production servers, I avoid installing modules using automated methods (like ZIP upload or by URL). The automated methods are handy for development and staging, but when it comes to production, it's better to copy (FTP, etc) the files into the /site/modules/ directory yourself for safety. 

I'm going to close this issue since it's something that is out of our hands, but please reply with any other questions you have. Thanks.

**Comment by teppokoivula** [comment]
@ryancramerdesign: just for the record, that's a really good argument for using separate info file, I for one hadn't even thought of that. IMHO the benefits of each separate method should be clearly documented somewhere.

Oh, and sorry if they already are -- I can't find such documentation, but that obviously doesn't mean it doesn't exist :)
