### ISSUE TITLE
All buttons are hidden when Table visibility is locked (not editable)

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#218]
### Short description of the issue

I think this will likely affect other field types as well. When a Table field's visibility is Locked (not editable), all buttons (InputfieldButton) are hidden. This affects my Table CSV Import/Export module - the Export button is hidden.

### Expected behavior

Not all buttons should be universally hidden - there needs to be logic to determine which ones.

### Actual behavior

All buttons are hidden.

### Optional: Suggestion for a possible fix

Not really a fix suggestion, but here is the css that is causing the problem:
```
.InputfieldRenderValueMode .InputfieldSubmit, .InputfieldRenderValueMode .InputfieldButton {
    display: none;
}
```
I haven't tried to find the code that adds the InputfieldRenderValueMode class to all buttons when field is locked though, but AFAIK that will be where this needs fixing.

### Setup/Environment

* ProcessWire version: 3.0.56
* Table 15

**Comment by adrianbj** [comment]
PS I am not sure when this started, but I noticed it after upgrading a site from PW 2.7.3 with an older version of Table where it was working fine.

**Comment by adrianbj** [comment]
Hey @ryancramerdesign - looks like my hack to my TableCSVImportExport module doesn't work for the UiKit theme. I could adjust it, but I'd rather see this issue fixed properly in the core or the Profields Table module. Would you mind taking a look please?

Thank you!

**Comment by netcarver** [comment]
@ryancramerdesign Any ideas about this one?

**Comment by ryancramerdesign** [comment]
@netcarver @adrianbj Locked fields aren't supposed to have any interactive elements (no inputs, buttons, etc.). As I understand it, the module mentioned here needs to show an interactive button in a locked field, overriding what a locked Inputfield does. That's fine, sounds useful for this particular case. But since this is not something that the core or the Table field have knowledge of, I guess I think the module that needs that behavior should override whatever CSS styles it needs to to achieve it. Though if something in the core or Table field makes that impossible, let me know what and I can revisit it.

**Comment by adrianbj** [comment]
Thanks for the input - now that I know this won't be tackled in the core, I have updated the hack in my module and it now also works with the UiKit theme.
