### ISSUE TITLE
Sanitizing leading ! does not work

### ISSUE THREAD

**Issue by LostKobrakai** [processwire/processwire-issues#227]
### Short description of the issue

I'm using ProcessWire's Password class to generate temp. login tokens, but leading ! are not sanitized correctly when trying to find the saved token.

### Expected behavior

Having leading ! simply masked/escaped for selectors.

### Actual behavior

They are stripped, which leads to an incorrect selector not able to find the searched page.

### Setup/Environment

* ProcessWire version: 3.0.42
* (Optional) PHP version: 7

**Comment by ryancramerdesign** [comment]
PW's selectorValue() method strips any chars that appear in operators from the beginning and ending of selector values. Since "!" is a character that appears in "!=", as well as a character that specifies NOT at the beginning of a selector, it gets stripped. However, I don't think this behavior needs to remain for quoted values. I'll look into see, as I think we should be able to support it.

**Comment by ryancramerdesign** [comment]
I've pushed an update to Sanitizer::selectorValue() that fixes this. Thanks.
