### ISSUE TITLE
Hook function is called twice if provided as property and method

### ISSUE THREAD

**Issue by kixe** [processwire/processwire-issues#232]
### Short description of the issue
Hook function is called twice if provided as property and method (same name). If the hook is called as property it is called as method as well. Same the other way round. In the example the return of the hook is not affected.
I have got unexpected returns after using functions for data manipulation within the hook function.

### Expected behavior

only one call

#### Module
```
<?php namespace ProcessWire;

class MyModule extends WireData implements Module {

	/**
	 *
	 * @return array
	 *
	 */
	public static function getModuleInfo() {

		return array(
			'singular' => true, 
			'autoload' => true
			);
	}

	/**
	 * Initialize, attach hooks 
	 *
	 */
	public function init() {
		$this->addHookProperty('Page::hello', $this, 'hello');
		$this->addHookMethod('Page::hello', $this, 'hello');
	}

	/**
	 * @param HookEvent $event
	 *
	 */
	public function hello(HookEvent $event) {
		var_dump(date('m:i:s'));
		$event->return = "Hello World";
	}

	// ...
}
```
#### Template
`<? echo $page->hello; ?>`
or
`<? echo $page->hello(); ?>`

#### Output
> string(15) "04:17:40" string(15) "04:17:40" Hello World

**Comment by ryancramerdesign** [comment]
All hooks are actually hook methods. Using the `addHookProperty()` for adding a hook just adds an extra attribute that tells Wire to also “check this if an unknown property is accessed”. But behind the scenes, they are exactly the same thing. If you add a hook property, it can also be accessed as a method. Property is just a syntax convenience. The result you are seeing is expected because what you've done is attach two hooks with the same name `Page::hello`. So a call to `$page->hello()` (whether accessed as property or method) will call both of the hooks you attached. If you'd like, I may be able to have it throw an Exception if you attempt to collide a method and property hook like this.

**Comment by teppokoivula** [comment]
@ryancramerdesign: could this be mentioned in the phpdoc block for `addHookProperty()` too?

The docs specifically claim that this method adds "a new accessible property" and make no mention of it actually being a method that can *also* be accessed as a property.

This may indeed be expected once you know the implementation well enough, but it's not one would expect based on docs or common logic alone (latter is, obviously, just my opinion) :)

**Comment by ryancramerdesign** [comment]
Sure I can add that. Behind the scenes, there are only methods, as a hook implementation can only be a method. So the addHookProperty() just makes it possible to call it as a property too.

**Comment by kixe** [comment]
If I attach the hook via  `addHookProperty()` an exception is thrown if I call `$page->hello();`
> Exception: Method Page::hello does not exist or is not callable in this context

The other way round attaching the hook as method `addHook()`and call as property `$page->hello;` I get
> NULL

I would like to provide both property and method. The method with optional argument.
It would be great if the following API calls could be assigned to one single hook function.
```
$page->hello; // OR
$page->hello(); // OR
$page->hello(false);
```
Currently I use this hack as a workaround
```
public function hookPageHello(HookEvent $event) {
  if (substr($event->options['priority'],-1) != '0') return; // prevent double call
  $who = (count($event->arguments) && $event->arguments(0) === true)?  $this->wire('user')->name : 'World';
  $event->return = "Hello $who";
}
```

**Comment by ryancramerdesign** [comment]
The WireHooks class has been redone quite a bit since this issue report, so I'm not sure how much of this still applies. But I have made updates to ensure that method/property hooks are isolated as requested here, as well as added the ability to add hooks that will respond to both method or property calls, by using the 'either' type in the hook options:
~~~~~
$wire->addHook('ClassName::hookName', function($e) { ... }, [ 'type' => 'either' ]); 
~~~~~

**Comment by kixe** [comment]
Tried 'either'. But does not work if called as method.
```
$wire->addHook('Page::hello', function($e) {$e->return = "Hello World";}, [ 'type' => 'either' ]);
echo $page->hello();
// Error: Exception: Method Page::hello does not exist or is not callable in this context ...
```

**Comment by ryancramerdesign** [comment]
Hmm, the same thing is working here other than that my hook name is
different. I'll run through it once again to see what I can find.

**Comment by ryancramerdesign** [comment]
@kixe Are you still seeing this issue after 3.0.128?

**Comment by kixe** [comment]
@ryancramerdesign 
Simple answer: NO.
Fixed. Thanks. Closed.
