### ISSUE TITLE
Cross-Domain Sessions are not working

### ISSUE THREAD

**Issue by dennisspohr** [processwire/processwire-issues#237]
### Short description of the issue

If I set $config->sessionCookieDomain = '.mydomain.net'; session are still not working through all subdomains.

### Expected behavior

If a users logs in on Subdomain A, this user/session should be available on Subdomain B as well.

### Optional: Screenshots/Links that demonstrate the issue

More details and all things I've already tried:
https://processwire.com/talk/topic/15984-same-session-on-subdomains/

### Setup/Environment
* ProcessWire version: 3.0.42
* (Optional) PHP version: 7.0.14
* (Optional) MySQL version: 5.7.15
* Using https: Yes, but same issue even without an ssl-certificate

**Comment by ryancramerdesign** [comment]
I think you might need to use the dev branch for this. The person that submitted the original `$config->sessionCookieDomain` addition as a PR, later added another PR to correct some issue with it. The PR that person added was a couple of weeks ago, so it's not yet on master, but is on dev. So I'm assuming the dev branch might fix the issue you are observing. If you want you can also try to apply the change manually, as it's just one line: https://github.com/processwire/processwire/pull/58/files

**Comment by Toutouwai** [comment]
I tested this in 3.0.59 and initially couldn't get it to work. But with some more testing it looks like it does work, but the value defined for $config->sessionCookieDomain must start with a dot. I originally tried

    $config->sessionCookieDomain = 'mydomain.com';

and this doesn't work. But when I changed to

    $config->sessionCookieDomain = '.mydomain.com';

it did work.

One minor issue though: If you are logged out one on subdomain and visit this address in the other subdomain

    subdomain.mydomain.com/processwire/page/?login=1

you get a browser error due to an endless redirect loop.

**Comment by dennisspohr** [comment]
Hi have added that line in Session.php, but still it doesn't work for me. But to be honest I haven't the time yet to go deeper in it again. Looks like it doesn't fix it. (Tried it with ssl on)

**Comment by ryancramerdesign** [comment]
I don't have an environment to test this at present. @derixithy any tips on using cross domain sessions?

**Comment by ryancramerdesign** [comment]
@dennisspohr just to confirm, you are now using the ProcessWire dev branch to test this, correct? (PW 3.0.59). It won't work on the master branch per what I mentioned earlier.

**Comment by dennisspohr** [comment]
@ryancramerdesign No I test it with PW 3.0.42, but with the correction in Session.php (https://github.com/processwire/processwire/pull/58/files).

**Comment by derixithy** [comment]
I tested it on 3.0.42, and it worked with the following code.
`
$config->sessionCookieDomain = '.usershare.nl';
ini_set('session.cookie_domain', $config->sessionCookieDomain);
`
I used bitnami to test: https://bitnami.com/stack/processwire/installer
Adding or removing a dot in front of the domain did not seem to change much, although the dot seems to be recommended.

**Comment by ryancramerdesign** [comment]
Thanks for the follow-up @derixithy, glad to hear your test worked with 3.0.42. 

If needing to share the same session between http and https, this should work:
~~~~~
$config->sessionCookieSecure = true; 
$config->sessionName = 'something';
$config->sessionNameSecure = $config->sessionName;
~~~~~

> While testing i had problems with the 'old' cookies, so make sure to remove all the cookies from all domains before you login again.

That's also a good point. An alternative is just to do your testing with an Incognito window, which is what I usually do for most testing, since it starts you from a blank slate in terms of cookies, etc.

**Comment by netcarver** [comment]
@dennisspohr Dennis, is this issue still live? Have recent updates to PW allowed this to be closed?

**Comment by dennisspohr** [comment]
Honestly I don't know exactly. I remember that I will had issues and found a workaround. But I can't test it in a live environment anymore.

**Comment by netcarver** [comment]
@dennisspohr Ok, thanks Dennis. Closing this now - you can re-open if needed or others can open a new issue if they need to. Thank you!

**Comment by yellowmastodon** [comment]
I know this is an old thread, just want to share, what worked for me.

I have managed to get this working on localhost (sub1.domain.localhost, sub2.domain.localhost), but could not make it work on shared hosting on live site. So I compared the phpinfo() on local and live site. Turns out the difference was that the site on shared hosting was storing php session in memcache. 

This solved it for me:
<pre>$config->sessionCookieDomain = '.domain.tld';
$config->sessionCookiePath = '/';
ini_set('session.save_handler', 'files');
ini_set('session.save_path', __DIR__ . '/assets/sessions');
ini_set('session.cookie_domain', $config->sessionCookieDomain);</pre>

**Comment by BernhardBaumrock** [comment]
Thx for sharing!

Would this only work for subdomains or also for top level domains?

For example would it be possible to share one session across several multi-sites that are all coming from the same processwire instance and are on the same server.

eg
mysite1.com
mysite2.com

session domain mysite.com ?

**Comment by yellowmastodon** [comment]
I think this setup is not sufficient for top level domains. The cookie_domain restricts this to the specified top level domain (the dot includes subdomains) and as far as I understand you cannot specify multiple domains for cookie. It might be possible with `session.cookie_samesite, 'none'` and `session.cookie_secure, 1`, but I honestly I have no idea if that would work, which domain to specify for session.cookie_domain and if that would introduce some security issues,

**Comment by BernhardBaumrock** [comment]
Ok thx, I'm kinda happy about that because I implemented a different solution already and if that worked it would have meant that all my previous research and all my work had been for nothing :D
