### ISSUE TITLE
InputfieldPassword: description becomes notes, notes not rendered.

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#239]
### Short description of the issue

If you define a description for a Password field, that description is rendered below the inputfields as a note. Any notes you define for the field are ignored and not rendered.

I can understand why this is being done: the description is being used to display the minimum password requirements. But it would be preferable if a description is defined for the field that it be appended or prepended to the minimum requirements and any notes defined be rendered as expected. Being above or below the inputfield does make a difference to how and when the information is read.

### Expected behavior

Description is rendered as description and notes is rendered as notes :)

### Actual behavior

Description becomes notes, notes not rendered.

### Setup/Environment

* ProcessWire version: 3.0.59

**Comment by adrianbj** [comment]
This is interesting because you can generated notes with a hook on InputfieldPassword::render although I also see that if you try to add a description, it overrides any notes that are set.

**Comment by ryancramerdesign** [comment]
@Toutouwai Thanks, I've pushed a fix for this issue so that it displays the description and notes in the correct location.

**Comment by matjazpotocnik** [comment]
@ryancramerdesign Thanks for the fix regarding relaxing some of the strict password requirements. It was me commenting this in another issue. Though, I wonder why you set minimum password length to 3 when before it was 0?

**Comment by ryancramerdesign** [comment]
@matjazpotocnik Sure, no problem. Regarding the min value, I noticed it was missing that before, and thought there was potential for issues having no minimum, so adjusted it while I was in there making updates. I don't recall exactly what the potential issues were but always try and err on the side of safety when it comes to something like a password field.

**Comment by matjazpotocnik** [comment]
I agree that we should play safe, but I've set the minimum value to 1 in my test environment (not something that would be used in the production of course) and had to set this to 3 to be able to save the password field. But not a big deal. FYI, the reason why complexify didin't work with minimum value set to 0 was that `var minlength = parseInt($input.attr('data-minlength'));` in InputfieldPassword.js was returning NaN since data-minlength attribute was not present. I fixed this with `if(!minlength) minlength = 0;`

**Comment by ryancramerdesign** [comment]
Okay sounds good, that makes sense. If you think we should support a
minlength=0 (or minlength=1) let me know and I can adjust it.

**Comment by matjazpotocnik** [comment]
Well, I would definitely fix the issue with minlength in InputfieldPassword.js, just in case we don't step on it sometime in the future. 

I'm not sure what should I think about minlength :-) I would remove this minlength restriction as it's not backward compatible. If you want to stay with number 3 or whatever value because of potential security issues, I would make a note on that fact.

Windows allows the user to set an empty password, even for the administrative account. You can log in to the computer using an account with empty password only localy, not remotely.
