### ISSUE TITLE
PageAutocomplete shows results disallowed by custom selector

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#24]
### Short description of the issue

The PageAutocomplete inputfield shows (and allows selection of) pages that are disallowed by the custom selector defined for the field.

This is my custom selector...
`id!=page.id`
...and the current page is still selectable in the inputfield.

### Expected behavior

Inputfield does not show pages that are disallowed by custom selector.

### Actual behavior
Inputfield shows and allows selection of the disallowed page. When the page is saved there is no warning, but the value of the disallowed page is not stored in the field.

### Steps to reproduce the issue

1. Create Page field using PageAutocomplete inputfield, with custom selector set to `id!=page.id`
2. In Edit Page, try selecting the current page in the PageAutocomplete inputfield.

### Setup/Environment

* ProcessWire version: 3.0.35
* PHP version: 7

**Comment by ryancramerdesign** [comment]
Thanks I have pushed a fix for this. The purpose of the "page.[something]" property was originally for supporting dependent selects, so it wasn't really designed for much beyond that. Though it seems like a worthwhile usage you've proposed. Looking closer, it was a very simple matter to make it support what you are trying to do, so this opens a few more doors for it as well. Note also that PW won't allow page references that reference themselves either way but the selector you are using at least prevents the pages from appearing selectable in an autocomplete, so that's good.
