### ISSUE TITLE
Markup Regions: max execution time exceeded when large number of divs present

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#245]
### Short description of the issue

I have a template containing a markup region 'main-content' that replaces the default main-content in _main.php. In the template I foreach 693 pages, echoing one div per page (the divs represent 1 hectare grid squares on a map). When a page with this template is rendered I get a max execution time exceeded error, which seems to be related to Markup Regions:

![2017-04-14_173047](https://cloud.githubusercontent.com/assets/1538852/25034094/28457602-2138-11e7-9e23-5cb12218bb68.png)

But interestingly if I echo paragraphs instead of divs the page renders fine.

So this gives the error
```
<div id="main-content">
	<div class="title-bar">
		<h1 class="page-width"><?= $page_title ?></h1>
	</div>
	<div class="sponsorship-map">
		<img src="/site/templates/images/map-bg.jpg" alt="Aerial photo">
		<div class="sponsorable-area">
			<?php
			$hectares = $pages->find("parent=1504"); // finds 693 pages
			foreach($hectares as $hectare) {
				$class = 'hectare';
				if($hectare->template == 'hectare') $class .= ' sponsorable';
				if($hectare->sponsor) $class .= ' sponsored';
				echo "<div class='$class'></div>";
			}
			?>
		</div>
	</div>
</div>
```

But this works (the only thing changed is `<p>` instead of `<div>`)
```
<div id="main-content">
	<div class="title-bar">
		<h1 class="page-width"><?= $page_title ?></h1>
	</div>
	<div class="sponsorship-map">
		<img src="/site/templates/images/map-bg.jpg" alt="Aerial photo">
		<div class="sponsorable-area">
			<?php
			$hectares = $pages->find("parent=1504"); // finds 693 pages
			foreach($hectares as $hectare) {
				$class = 'hectare';
				if($hectare->template == 'hectare') $class .= ' sponsorable';
				if($hectare->sponsor) $class .= ' sponsored';
				echo "<p class='$class'></p>";
			}
			?>
		</div>
	</div>
</div>
```

### Setup/Environment

* ProcessWire version: 3.0.59
* (Optional) PHP version: 7.0

**Comment by ryancramerdesign** [comment]
I think this is probably happening because all of those new `</div>` tags are creating a lot more work for MarkupRegions to figure out where the `#main-content` ends. I'm guessing it's not stuck in an infinite loop, but just taking a long time to figure things out. Maybe there's something we can do to optimize this so that it's not so slow with that, I will experiment. Does it eventually finish if you `set_time_limit(600)`? I secretly hope it's an infinite loop somewhere that I missed, as that would be a simpler fix no doubt. This might be a good use case for those `<region>` tags too, as using one here would likely cut out all the overhead since it only has to find the right closing `</region>` tag.

**Comment by Toutouwai** [comment]
It times out at 600 seconds too.

**Comment by Toutouwai** [comment]
200 divs seems to the magic number - less than that and the page renders.
Maybe related to [this line](https://github.com/processwire/processwire/blob/223b80d6859af9d259caa0f34a0d9bc9f71e210c/wire/core/WireMarkupRegions.php#L488)?
```
} while($doCnt < 200 && $testStart < strlen($region));
```

**Comment by ryancramerdesign** [comment]
Thanks for testing it. You are right, that's where the issue is (reproduced locally). I've just bumped the number way up along with a couple other minor tweaks. Please let me know if you continue to experience issues with it.

**Comment by Toutouwai** [comment]
Thanks.
