### ISSUE TITLE
Link abstraction for url segments

### ISSUE THREAD

**Issue by ivangretsky** [processwire/processwire-issues#251]
### Short description of the issue

I have a page with url segments enabled. When accessing those url segments the content is being loaded from other pages. The problem is when I reference this url segment from elsewhere in the textarea with link abstraction on, my links get transformed to reference the page, the content is being loaded from.

### Expected behavior

The links should be left untouched.

### Setup/Environment

* ProcessWire version: 3.0.39

**Comment by ryancramerdesign** [comment]
Unfortunately it's not possible for link abstraction to know anything about how URL segments map because they are something that's known only at runtime, and not actually part of the page structure. Your best bet may be to disable link abstraction for this case. Though just to make sure I understand, can you tell me more what the linked and actual URLs are, and specifically what transformation you are seeing take place during link abstraction?

**Comment by ivangretsky** [comment]
I write
`<a href="/proekty-domov-iz-brusa/odnoetazhnye/">`
and after save I see
`<a href="/catalogue/razrezy-proektov/odnoetazhnye/">`

**Comment by netcarver** [comment]
@ryancramerdesign Is this a candidate for "not a bug?"

**Comment by ivangretsky** [comment]
Just maybe there could be a way  invented to tell link abstractor to skip checking certain link?

**Comment by ryancramerdesign** [comment]
Here's one way you can do it below, in your /site/config.php file. Any
paths that begin with the ones you specify will be ignored by the link
abstraction. It was added recently, so I think requires the dev branch:
~~~~~
$config->markupQA = [
'ignorePaths' => [ '/path/to/ignore/', '/another/path/to/ignore/' ]
];
~~~~~

**Comment by ivangretsky** [comment]
Thanks! Closing it! 
Just a thought... Should we also make it possible to make it possible to turn off link abstraction on link per link basis, so content managers will be able to cope themselves?
