### ISSUE TITLE
Change invalid date format (0000-00-00 00:00:00) to current timestamp (Site Profile Exporter)

### ISSUE THREAD

**Issue by thetuningspoon** [processwire/processwire-issues#260]
### Short description of the issue

I am not sure if this issue (https://github.com/ryancramerdesign/ProcessWire/issues/1559) was ever resolved in core, but it is still an issue when installing site profiles exported using the latest version of the site profile exporter.

### Expected behavior

ProcessWire is installed.

### Actual behavior

Numerous invalid date format error messages in a scary red color :)

### Optional: Suggestion for a possible fix

Doing a search & replace with CURRENT_TIMESTAMP in the install.sql file fixes it.

* ProcessWire version: 3.0.61

**Comment by ryancramerdesign** [comment]
Whether the "0000-00-00" dates are valid depends on the SQL modes. The current timestamp has a different meaning from such a date, since the zero-dates indicate something where a date is not present, but the row should still be considered in some querying operations. Whereas CURRENT_TIMESTAMP indicates "now", which would mean something different. 

I'm pretty sure ProcessWire core no longer uses zero dates, but they may still be present if they originated in earlier versions of PW. The profile exporter maintains what's present in the database. If importing the profile on another system that uses a different SQL mode, the error messages would be expected. But so long as it doesn't prevent the profile from importing (?) I think it's best for it to export the profile accurately and maintain whatever dates are present, rather than attempting to replace them with something having a different meaning. 

If it's for a public profile you want to share and ensure those error messages are suppressed, you could pull the resulting install.sql file into your text editor and remove the INSERT lines having the zero-dates, as simply excluding the rows would probably be the most accurate representation of the data. This will work for FieldtypeDatetime data. But if you are seeing other tables with zero dates that you don't want (like pages table), then replacing with NULL might be better. If it's for a case where the date is completely inconsequential, then of course CURRENT_TIMESTAMP is fine too.

**Comment by thetuningspoon** [comment]
Makes perfect sense. Thanks Ryan.

**Comment by kixe** [comment]
A related post from the forum:
https://processwire.com/talk/topic/16302-sql-errors-while-installing/#comment-144611
I have been running in similar issues using ProcessDatabaseBackups.
I am not sure if it would be a good solution to modify the sql settings for the session?
`SET @@session.sql_mode ="";`

**Comment by ryancramerdesign** [comment]
@kixe See the `$config->dbSqlModes` setting, which my provide what you are looking for– https://github.com/processwire/processwire/blob/master/wire/config.php#L879

**Comment by kixe** [comment]
@ryancramerdesign 
Thanks for the hint. This solution perfectly fits my needs.
