### ISSUE TITLE
Misleading comments pageFinder returnVerbose

### ISSUE THREAD

**Issue by Da-Fecto** [processwire/processwire-issues#262]
### Short description of the issue

In PageFinder::$defaultOptions there's the explanation of returnVerbose:

When true, this function returns array of arrays containing page ID, parent ID, template ID and score. When false, returns only an array of page IDs. returnVerbose=true is required by most usage from Pages class. False is only for specific cases. 

But when a selector is combined with the sub field count like fieldname.count, a second column is returned prefixed with num.  

### Expected behavior

A mention about this behaviour in the comments. See behaviour in the code below.

### Optional: Screenshots/Links that demonstrate the issue

```php
/**
 * When true, this function returns array of arrays containing page ID, parent ID, template ID and score.
 * When false, returns only an array of page IDs. returnVerbose=true is required by most usage from Pages
 * class. False is only for specific cases.
 *
 */

$pageFinder = $pages->getPageFinder();
$options = array(
	'returnQuery' => true,
	'returnVerbose' => false,
);


$query = $pageFinder->find('template=user, roles.count>1', $options)->getQuery();

/**
 * Results
 *  
 * SELECT pages.id,
 *        field_roles_1.num_field_roles_1 AS num_field_roles_1
 * FROM `pages`
 * LEFT JOIN
 *   (SELECT FieldtypePage_1.pages_id,
 *           COUNT(FieldtypePage_1.pages_id) AS num_field_roles_1
 *    FROM field_roles AS FieldtypePage_1
 *    GROUP BY FieldtypePage_1.pages_id) field_roles_1 ON field_roles_1.pages_id=pages.id
 * LEFT JOIN field_roles AS field_roles ON field_roles.pages_id=pages.id
 * AND (((num_field_roles_1>1
 *        AND pages.templates_id IN(3))))
 * WHERE (pages.templates_id=3)
 *   AND (pages.status<1024)
 *   AND (((num_field_roles_1>1
 *          AND pages.templates_id IN(3))))
 * GROUP BY pages.id
 * 
*/

echo $query;

```

**Comment by ryancramerdesign** [comment]
I'm not sure that I follow 100%, I think because your example above uses the `returnQuery` option, which is is an internal system option specific to PageFinder instantiating itself. Its purpose is to that the PageFinder can merge parts of queries when it needs to. The `returnVerbose` phpdoc is speaking to the expected array return value of the find() method, which seems to be working correctly as far as I can tell: 
~~~~~
$pageFinder = $pages->getPageFinder();
$options = array('returnVerbose' => false);
echo "<pre>";
print_r($pageFinder->find('template=user, roles.count>1', $options)); 
~~~~~
Result:
~~~~~
Array
(
    [0] => 41
    [1] => 1025
)
~~~~~
0 is "admin", and 1 is "ryan", both of which have roles "superuser" and "guest". Let me know if I've misunderstood? Thanks.

**Comment by netcarver** [comment]
@Da-Fecto Any thoughts on Ryan's comment above? Is this issue still live?

**Comment by netcarver** [comment]
Closing as this seems to be cold. @Da-Fecto Feel free to post here again if needed. Thanks!
