### ISSUE TITLE
Issue with Options field + Radios controlling Inputfield (Image?) visibility

### ISSUE THREAD

**Issue by szabeszg** [processwire/processwire-issues#271]
### Short description of the issue

What we see on the screen-grab:
- Type Of Article (**article_type**): Options field with Radios
- Lede: Column width: 50%
- Featured Image: image field, Column width: 50%, Show if: **article_type=normal**
- Badge: image field, Column width: 50%, Show if: **article_type!=normal**

![options-field-radios-show-if](https://cloud.githubusercontent.com/assets/7194945/26374732/a791bd84-4006-11e7-95cf-fa84274d8480.gif)

### Expected behavior

I would expect the image field titled Badge to appear next to the field titled Lede, since both image fields and Lede are set to 50% column width.

### Actual behavior

The field titled Badge does not take the place of Featured Image, instead both Lede and Badge become full width (100%).

### Steps to reproduce the issue

1. Set up all three field as described above
2. Use the Radios to test

### Setup/Environment

Same happens in both ProcessWire 3.0.60 and 3.0.62

**Comment by ryancramerdesign** [comment]
I understand what you are saying. Unfortunately that's not a case that's supported at present with the core admin themes, because there are field(s) in-between the ones you want to stack horizontally, even if not visible once the transition is complete. Plus both collapsing and revealing happening at the same time, so order comes into play. You may be able to get close by moving your badge field before your lede field. Also, I think we might already support more situations like this in the new AdminThemeUikit though, but not positive if it covers this particular scenario.

**Comment by szabeszg** [comment]
Thanks for the tip Ryan, however reordering the fields did not help, so I reverted to using full width Inputfields. It would be great to support such situations with AdminThemeUikit.
Can I open an "issue" as a feature request of this at https://github.com/ryancramerdesign/AdminThemeUikit/issues ?

**Comment by kixe** [comment]
@szabeszg 
The sum of the column widths in a row can not be greater than 100%, regardless of whether the columns are visible or not. To get what you expect it should work with the following settings:
Lede: 50%, Badge and Featured Image: 25%. The empty space of 25% will be filled up to 50%.

![screencast](https://cloud.githubusercontent.com/assets/4683120/26517982/73c2d55a-42a5-11e7-979c-67f76fe3c996.gif)

**Comment by szabeszg** [comment]
@kixe Thank you very much! Why didn't I think of it, I wonder? Works fine :)
