### ISSUE TITLE
Incorrect image placement with latest version of CKEditor (Inline Version)

### ISSUE THREAD

**Issue by chriswthomson** [processwire/processwire-issues#279]
### Short description of the issue

On updating to the latest versions of PW (3.0.62 & 2.8.62), adding images to a CKEditor field in Inline mode always places them to the top of the field, not where the cursor is. Placement is correct in Regular mode.

### Expected behavior

Image should be inserted where the cursor is.

### Actual behavior

Image inserted at beginning of field.

### Steps to reproduce the issue

1. Edit a page with a CKEditor Textarea field in Inline mode
2. Place the cursor after a paragraph or two / the beginning of a paragraph that isn't the first one
3. Use the pwimage module to add an image to the field

### Setup/Environment

* ProcessWire version: 3.0.62 / 2.8.62
I installed a fresh copy of 3.0.62 to confirm this behaviour.

**Comment by ryancramerdesign** [comment]
Thanks @chriswthomson I've pushed a fix for this issue, along with a CKE version upgrade.

**Comment by netcarver** [comment]
@chriswthomson Hello again Chris. Could you close this issue if it is resolved to your satisfaction, otherwise post a reply so we know to keep it open and on the radar. Thank you!

**Comment by chriswthomson** [comment]
Hi,

This was fixed on the 3 branch last year, but I'm pretty sure it's still on the 2.8.62 branch, which was last updated prior to this ticket.

Cheers,

Chris

**Comment by netcarver** [comment]
@chriswthomson  Hi Chris, thanks for the reply. I guess this is over to @ryancramerdesign to consider adding the update to 2.8.62 then. Thank you!

**Comment by netcarver** [comment]
Ok, I'm removing the fixed label to allow this to be seen by @ryancramerdesign again.

**Comment by Toutouwai** [comment]
I see that 2.8.x is gone from the download page on the new site: https://processwire.com/download/core/

I'm thinking this means that 2.8.x is no longer being developed and no new fixes will be provided, but I guess we need an official declaration from @ryancramerdesign

**Comment by ryancramerdesign** [comment]
I expect there will be one or two more updates to 2.8.x, and actually have
been meaning to do one here soon. However, I'm just not advertising that
version anywhere, as I don't think it's useful for anything other than
existing 2.8.x installs at this point. It was a useful transition version
for a period of time, but I think that time has passed. Version 3.x is now
the standard and has been for awhile. So I don't think anyone but existing
users of 2.8.x need updates to it. While I plan to make another update or
two to it, I don't want to promote it on the download page.

**Comment by teppokoivula** [comment]
Thanks for the update, @ryancramerdesign!

Just wanted to say that in my opinion these things really should be communicated clearly somewhere: I updated some projects from 2.7 to 2.8 back in the days, and that worked out great, but since updates to that branch suddenly stopped – there was no word from you, no answer when this was brought up, and 2.8.x was lagging behind in terms of bug fixes and such – eventually I had to jump through some hoops to get these legacy projects upgraded to 3.x anyway.

It's all good now, but again: I really wish that the status of that branch had been communicated clearly somewhere :)

**Comment by netcarver** [comment]
Should this be labelled as "ongoing - leave open" for now?

**Comment by ryancramerdesign** [comment]
@teppokoivula I don't really know these things ahead of time. Very few seemed interested in the 2.8.x versions, so stopped dedicating time there. This was one of the few issue reports that ever mentioned a 2.8 version. If I found there was reasonable interest in it, I'd start including it in the regular updates again. It there were some major issue to resolve in it I would update it it either way, but I'm not aware of any major issues in the current 2.8.x version, just minor things like the one here. I personally like using the 2.8 version on some of my old 2.x sites. I'd like to give it at least another update or two. Since the 2.8 version is simply an export of the 3.x version, then any fixes in 3.x automatically apply. As a result, @netcarver I think it's okay to close this issue?

**Comment by teppokoivula** [comment]
Thanks again for the reply, @ryancramerdesign. I do remember asking / pointing out on a couple of occasions that some fix probably should be applied to 2.8.x as well, but never got an answer, so wasn't sure what was going on. At this point I'm thinking that those messages must've been lost in transit, so that's really no big deal – communications glitches happen sometimes.

Regardless, when 2.8 was announced (and in some later posts) it was explained that it would be automatically kept up to date with 3.x, and I seem to recall that you had some kind of automated process set up for that. Since that's the latest official announcement (via blog posts), and we now know that it's probably _not_ going to be kept fully up to date, I would suggest that we document (at processwire.com) clearly two things:

a) what the 2.8 (legacy) branch is and who it is for, and
b) what to expect if you're currently using it, or planning to migrate to it from an earlier version (including a proper discouragement for new users, obviously).

I'd call that managing expectations :)

**Comment by ryancramerdesign** [comment]
The updating of it is still an automated thing, though I do like to thoroughly test it out on my own before committing updates. So the updating of it takes literally no time, while the testing of it takes a lot. Since other people talking about 2.8 has been nearly non-existent, I've thought I should be investing that time in 3.x instead. Another thing is that the whole FileCompiler solution ended up working out a lot better than originally expected. I didn't expect it to go as smooth as it did, which is in part why 2.8 was there, to be that buffer. Yet, the whole 2.x to 3.x migration ended up being a non-issue for the vast majority of cases. But this is the most I've heard about 2.8 since it was released, and maybe that's an indication there is still some interest in this version (?). I certainly could start up regular updates to it again. I'd be interested in hearing if anyone else is using 2.8?

**Comment by netcarver** [comment]
/remind me to review this issue in 1 week

**Comment by teppokoivula** [comment]
@ryancramerdesign, I'm afraid I might've given you the wrong impression, so to summarise: personally I'm perfectly fine with 2.8.x no longer being updated. My point is that it should be communicated clearly.

Latest "official" announcement was that 2.8 is going to be always up to date with 3.x development – and that's clearly no longer the case, and hasn't been for a long time now. 

I'm sure you're right that there's relatively small audience for the legacy branch, so unless someone else has different opinion, my suggestion would be to add a big, impossible-to-miss note to the 2.8 (legacy) repository explaining that it will no longer be updated.

Also, it would be nice to provide existing 2.8.x users this same information at processwire.com, perhaps on the [upgrade page](https://processwire.com/docs/start/install/upgrade/), so that anyone looking for new 2.8.x versions or information about this branch there can easily spot it.

Thanks, and sorry for dragging this issue on and on :)

**Comment by chriswthomson** [comment]
> I'd be interested in hearing if anyone else is using 2.8?

Hi @ryancramerdesign - we've still got 25 sites on 2.8.62 branch, some of them quite large sites that we probably wouldn't be looking to upgrade to 3 unless as part of a redevelopment project, so a new version of the 2.8 branch with all the goodies (and bug fixes) from the latest 3 master would be brilliant.

However, all the sites have been stable (apart from this CKEditor issue) since 2.8.62 was released, so a new 2.8 version was never something we'd thought much about - just assumed that it would appear sometime after the latest 3 master. If 2.8.62 ends up being the end of the line for the 2 branch, that's OK.

Cheers,

Chris
NB

**Comment by netcarver** [comment]
@chriswthomson @teppokoivula @ryancramerdesign Thanks for the feedback on this issue one and all. 

Ryan, if you've considered Teppo's ideas...

> I'm sure you're right that there's relatively small audience for the legacy branch, so unless someone else has different opinion, my suggestion would be to add a big, impossible-to-miss note to the 2.8 (legacy) repository explaining that it will no longer be updated.

> Also, it would be nice to provide existing 2.8.x users this same information at processwire.com, perhaps on the [upgrade page](https://processwire.com/docs/start/install/upgrade/), so that anyone looking for new 2.8.x versions or information about this branch there can easily spot it.

then I'd like to close this issue next week as it seems to have come to a semi-conclusion here.

**Comment by netcarver** [comment]
Closing this now.
