### ISSUE TITLE
Fields disappear in PageEdit

### ISSUE THREAD

**Issue by karltdev** [processwire/processwire-issues#291]
### Short description of the issue

Fields disappear in Page Edit when wrong value is saved.

### Expected behavior

Fields stay but save nothing.

### Actual behavior

Affected fields disappeared.

### Steps to reproduce the issue

1. create a field with "float"
2. edit the field > input > visibility > set "Open when populated + Closed when blank + Locked (not editable)" > save
3. add the field into template
4. inside the template add the following 
`$page->of(false);
$page->test = "abc";
$page->save();`
5. browse the page and check page edit of the page

### Setup/Environment

* ProcessWire version: 3.0.63

**Comment by ryancramerdesign** [comment]
I might be reading this wrong, but what you've described, setting the string value "abc" to a float field, is exhibiting the intended behavior. When you set the value of the field, it gets sanitized according to the type. If you pass a non-float/non-numeric string to a float field, sanitization will interpret that as empty, since it's not a number.

**Comment by karltaidev** [comment]
Sorry, I have missed one step. I have added to the first post as point 2.

This normally happens when I was developing the site and some errors were saving into the field. Then I have to remove the page and rebuild it to bring the disappeared field back.

**Comment by ryancramerdesign** [comment]
Thanks for the report. The behavior described here is consistent with what it's written to do. Populating a string of letters to a float field is going to make the value blank/null because letters are not numbers, so it's not a valid value for the field. You would have to specify a numeric value. Since the field is also locked, and it's been populated with something invalid, and there is no input element, it is essentially null at that point and will have nothing to render or see. Though if you think I've misunderstood, please re-open. Thanks.
