### ISSUE TITLE
FieldtypePage with Page Auto Complete cannot have custom PHP code

### ISSUE THREAD

**Issue by Rayden** [processwire/processwire-issues#300]
### Short description of the issue

A Page Reference field (FieldtypePage) with Multiple Pages (PageArray) and page Auto Complete (InpufieldPageAutocomplete) does not support custom PHP code (ready.php InputfieldPage::getSelectablePages hook) anymore.

### Expected behavior

Im not sure if this is a bug or just an feature which is not supported anymore (and thus a feature request). But i would expect that a field of the type FieldtypePage with Multiple Pages and InputfieldPageAutocomplete as Input field type selected, would support a selector with custom PHP code (by hook in ready.php)

~~back when the custom PHP code could still be entered in a textare field in the field settings it seemed to work as expected.~~

update: way back (PW 2.5.9) when the custom PHP code could still be entered in a textarea field in the field settings it was possible to assign custom PHP code. Altough it didnt work and didnt use this code but instead returned alist of 'all' pages.

### Actual behavior

Custom PHP code added to the InputfieldPage::getSelectablePages for this field is not used as selector PageArray

### Steps to reproduce the issue

1. Make a new field of type Page Reference
2. Set the page field value type to Multiple pages (PageArray)
3. Make sure InpufieldPageAutocomplete is installed and select it as Input field type
4. Custom PHP code is hidden from list of Selectable pages

### Setup/Environment

* ProcessWire 3.0.62
* FieldtypeRepeaterMatrix 0.0.3
* FieldtypeRepeater 1.0.6
* PHP 5.5.8
* MySQL mysqlnd 5.0.11-dev

**Comment by Toutouwai** [comment]
The Page Autocomplete field has not officially supported the custom PHP option for as long as I can remember. Maybe it worked in some circumstances, but see for instance the disclaimer in 2.7.2 (the oldest version I have running):

![2017-06-27_122856](https://user-images.githubusercontent.com/1538852/27565762-66309114-5b34-11e7-8cb7-e270288f8d3f.png)

**Comment by Rayden** [comment]
@Toutouwai thanks for clearing this up. Then please consider my bug report as feature request instead.

Is there a particular reason why custom PHP in conjunction with AutoComplete is supported? as in impossible? 

Is there a work around, for example to hook into the AutoComplete and manipulate the returning PageArray my self?

**Comment by LostKobrakai** [comment]
The inputfield does use the functionality of ProcessSearch with a custom selector. So it can only work with an selector string and not an in memory pagearray as base.

Also as it's using ajax and potentially lots of calls loading all potentially possible pages into memory for each check is quite a wasteful operation.

**Comment by Rayden** [comment]
Ok, thanks for the explinations. I will close this issue now

**Comment by Toutouwai** [comment]
@Rayden, I had a look at how it might be possible to limit the results returned by InputfieldPageAutocomplete. Two options below that I think would work as long so you are not dealing with very large numbers of pages in your "allowed" PageArray.

The idea is that you first configure the selectable pages for your Page Reference field using a selector that would match any of the pages you want to allow, but is still as specific as possible. In my testing I just used "has_parent!=2" because my test site does not have a lot of pages, but you would probably want to be more specific than that.

In my examples below I'm just using another Page Reference field to define the allowed pages as a matter of convenience when testing.

The first approach is to use a hook to modify the selector used for selectable pages. You define your PageArray of allowed pages and then append it to the selector. Of the two approaches I think this is the better, but one catch is that your PageArray (when in the form of a bar separated string of IDs) will be subject to the selector value limit of 500 characters.

```php
$wire->addHookAfter('Field::getInputfield', function(HookEvent $event) {
    // Only for ProcessPageEdit
    if($this->process != 'ProcessPageEdit') return;
    $field = $event->object;
    $inputfield = $event->return;

    // Only for this one Page Reference field
    if($field->name !== 'test_page_2') return;

    // Define the PageArray of allowed pages
    $allowed = $this->pages->get(1)->test_page;

    // Modify findPagesSelector (or findPagesSelect if you used that)
    $inputfield->findPagesSelector .= ", id=$allowed";
    $event->return = $inputfield;
});
```

The other approach is to hook after `ProcessPageSearch::executeFor` and manipulate the returned JSON results. This works okay if you only have only a single Autocomplete field in your project, but if you have more than one with different allowed pages I'm not sure how you could go about distinguishing between them within the hook.

```php
$wire->addHookAfter('ProcessPageSearch::executeFor', function(HookEvent $event) {
    // Return if this is the admin search
    if($this->input->get->get === 'template_label,title') return;

    // Define the PageArray of allowed pages
    $allowed = $this->pages->get(1)->test_page;
    $allowed_ids = $allowed->explode('id');

    // Filter the results
    $json = $event->return;
    $decoded = wireDecodeJSON($json);
    foreach($decoded['matches'] as $key => $value) {
        if(!in_array($value['id'], $allowed_ids)) unset($decoded['matches'][$key]);
    }
    $event->return = wireEncodeJSON($decoded);
});
```

**Comment by Rayden** [comment]
@Toutouwai Thanks for writing up these examples. Your first example is the one i was looking for and it works like a charm. I have modified it a little and using it instead of the InputfieldPage::getSelectablePages hook. (thumbsup)

**Comment by LostKobrakai** [comment]
Just keep in mind to not use it on large sets of possible pages or with lots of traffic, as those pages will get loaded for each ajax request again and again.

**Comment by NikoTechnik** [comment]
When selecting "Page Autocomplete" the field for "Custom PHP code" really should be removed. 
Took me about two hours to find out that ist simply not implemented. At least a big fat warning sign would be helpfull.   :-(

**Comment by adrianbj** [comment]
When you choose the "Multiple" page autocomplete option it is actually removed and when you choose the single version, the php code option seems to work just fine.
