### ISSUE TITLE
check for unsaved changes before closing panels

### ISSUE THREAD

**Issue by BernhardBaumrock** [processwire/processwire-issues#301]
### Short description of the issue

I'm using the pw-panels a lot to edit pages in my project. Today i encountered that closing the panel does NOT check if there are some unsaved changes.

### Expected behavior

It should check if there are unsaved changes and prefent the panel from being closed. Just like it happens in regular page-edit-forms when one tries to close the browser tab. Maybe also modals should implement this (if not already there)?

### Actual behavior

It just closes the panel without asking.

### Steps to reproduce the issue

1. Open any ProcessPageEdit form in a panel
2. modify the value of any inputfield
3. close the modal

### Setup/Environment

* ProcessWire version: 3.0.39

**Comment by ryancramerdesign** [comment]
Looking at step 1 there, how are you opening a ProcessPageEdit form in a panel?

**Comment by BernhardBaumrock** [comment]
basically by adding the pw-panel class to an icon with a link in my custom process modules.

in detail it is a javascript function that does it for all of my table rows (though i don't think thats related to the problem?)
```
var editLink = function(options) {
    var cls = (typeof options.class !== 'undefined') ? options.class : 'pw-panel pw-panel-reload';
    var target = options.target ? options.target : '';
    var icon = options.icon ? options.icon : 'search';
    var hide = options.hidden === false ? '' : ' hidden';
    var out;

    out = '<span class="editlink'+hide+'">';
    /* create link */
    if(options.href) out += '<a href="'+options.href+'" class="'+cls+'" target="'+target+'">';
    else {
        if(!options.id) return '';
        out += '<a href="/admin/page/edit/?id='+options.id+'" class="'+cls+'" target="'+target+'">';
    }

    out += '<i class="fa fa-'+icon+'"></i>';
    out += '</a>';
    out += '</span>';
    return out;
}
```

**Comment by netcarver** [comment]
@ryancramerdesign Do you need any more information from @BernhardBaumrock in order to progress this issue?

**Comment by ryancramerdesign** [comment]
@BernhardBaumrock @netcarver I'm not really sure what to do with this one as panels are offcanvas elements than can be opened and closed, but they only load once. So closing a panel doesn't unload it, it just collapses it, while it's technically still present in the background. We aren't using panels for editors in the core, so there's no code related to monitor form errors in panels. If a form is in a panel, navigating away from the page should still report an error I'd think. But since the form is being loaded dynamically via JS, then PW isn't going to know its there and none of its events will have been attached to it. From the JS side you could call `InputfieldsInit('#your_form_id');` to initialize it and that might provide the needed behavior, though you'd need to add a `window.addEventListener("beforeunload", function() { ... } );`call somewhere to pop the panel back open, unless it's already obvious to the user how to do so.

**Comment by BernhardBaumrock** [comment]
Thx again. yeah I think this is not worth the effort.
