### ISSUE TITLE
images are lost when a page is saved

### ISSUE THREAD

**Issue by nettings** [processwire/processwire-issues#312]
I have created my own templates with an Images field, with the images to be used in an CKEditor-editable textarea. Sometimes, the images are lost when the page is saved. This can be seen in the green system message: rather than seeing "1 change" when, say, the title field was edited, it says "2 changes". After that, the images are missing from the assets "id" subdirectory and are no longer seen in the Images field in the editing environment. The textarea field with CKEditor still displays them, but nothing is rendered outside of it.

![missing image](https://user-images.githubusercontent.com/6558129/27990039-ec62ee76-6449-11e7-8f7e-40f1905a17d5.jpg)

### Steps to reproduce the issue

Can't say, happened during a busy editing session. Not always, but after a long day 10% of all text-area images went missing.
Maybe editor-related. I have another image gallery field in another template that allows no editing, and AFAICS no images went missing from there.

### Setup/Environment
* ProcessWire version: 57b297fd1d828961b20ef29782012f75957d6886
(bump to 3.0.62)
* PHP version: 7
* MySQL version: MariaDB 10.0.30-2.8

**Comment by nettings** [comment]
It might be due to my activating the experimental "Fix broken images" option in "EditFields->Details->Markup/HTML". I'll leave that switched off for now...

**Comment by ryancramerdesign** [comment]
I'm thinking it's unlikely the "fix broken images" is the source, because it doesn't modify the images field, and it looks like you are seeing an image lost from the images field. But let me know if you find it makes any difference when turning it off. I think we need to find someone else that can duplicate it or some steps on how to duplicate it consistently before we can attempt anything here, as I'm not aware that anyone else has ever experienced this issue. But here's a few things to look out for: 

- Uploading an image doesn't save it, you still have to save the page after uploading the image, before it's considered part of the page. 
- If you are editing the same page in multiple tabs, you may be overwriting your own changes.
- The issue you describe sounds a lot like what we'd see on a load balancer where the client isn't locked to the node/server. If you are using a load balancer, make sure your admin always hits the same node/server. 

Lastly, what method did you use to upload the images that disappeared? Were they uploaded in the page editor, or in the modal/dialog that pops up from CKEditor when clicking the image icon?

**Comment by nettings** [comment]
Sorry for the late reply. The site has now been deployed successfully, and after updating from git I wasn't able to reproduce the problem. There is no load balancer involved, so I'm tending to suspect something stupid like the "multiple tabs" thing you suggested, or not having saved the page during the initial editing frenzy. Thanks for your help, and for your great work! ProcessWire is a pleasure to use!

**Comment by netcarver** [comment]
@nettings I'm going to close this here. Please feel free to re-open if this happens again.
