### ISSUE TITLE
non well formed numeric value in Database.php

### ISSUE THREAD

**Issue by tbba** [processwire/processwire-issues#316]
Backend - Notice: A non well formed numeric value encountered in /wire/core/Database.php on line 118

MAMP, PHP 7.1.1, PW 3.066

If you cannot duplicate this right away, I send the list of installed modules and more info

**Comment by ryancramerdesign** [comment]
I've pushed an update that I think should fix it. I think it's due to debug timers that are float strings, so I specifically cast them to floats. I'm guessing it only happens in PHP 7.1 and due to a notice that previous versions didn't display. 

However, since you are seeing that notice, it indicates you've got something that is using the old $db API variable. The error message is happening in Database.php which is the old Mysqli that is deprecated. Ideally, you don't want anything using Mysqli since the PDO driver ($database API var) is what's standard now and has been for a few years. I'm guessing there's a 3rd party module in there somewhere that is using that old DB driver. You might check and see if there's an upgrade available to it. Not really a problem if there isn't, but it just means that your system is having to make two separate database connections with different drivers, which isn't as efficient.

**Comment by tbba** [comment]
Thank you for the in-depth explanation. The Notice is gone.
- It was only showing in PHP 7.1 (not 7.0)
- I was able to identify and remove an old backend module (with an old DB driver).
