### ISSUE TITLE
Module settings exceeding limits of db "text" field type.

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#321]
### Short description of the issue

"String data, right truncated: 1406 Data too long for column 'data' at row 1" when a module's config settings are long. This was just reported for my Batch Child Editor module because it allows individual settings for each page on a site: https://processwire.com/talk/topic/6102-batch-child-editor/?do=findComment&comment=147848

### Optional: Suggestion for a possible fix

Would you mind changing the "modules" table's "data" field from `text` to `mediumtext` ?

It would also be helpful if this change was included in the upgrade process.

**Comment by ryancramerdesign** [comment]
I'm reluctant about this because module settings are not meant for storing huge amounts of data. Whatever is in the module settings has to be loaded into memory every time the module is accessed. If it's an autoload module, then that means loading all that data loads every time PW boots. So storing lots of data in module settings could be a real drag on the system and I'm not sure we should encourage that. I think if a module needs to store such a large amount of data, it's probably better for it to store it in the file, or it's own DB table. Some better error reporting would definitely help here though, so let me look into that while thinking more about it. DB schema change on that column may be fine to prevent the error, but probably need to warn when sizes get large like this.

**Comment by horst-n** [comment]
+1 for short module settings data and external storages!

**Comment by adrianbj** [comment]
Thanks Ryan - I definitely see you desire to not encourage large module config settings. In my case for BatchChildEditor the config settings for a normal setup are around 6kb, but in certain cases it can ramp up to much greater which is what is described in the forum post linked above. I feel it would be an unnecessary complication to this module to add a separate DB table for a situation that is so unlikely - this is the first report I have had of this in the 3 years that this module has been around. I feel like it would be possible to significantly reduce the size of module settings by having shorter variable names (some of mine tend to be long and descriptive) - these can add up in the settings json when they are repeated many times for multiple page settings. Of course changing those now would be a breaking change.

**Comment by teppokoivula** [comment]
@adrianbj: this might not be an ideal solution either, but if variable naming would help but changing that is a problem because of BC, you could probably introduce a schema version check and update routine into your module. In a nutshell, when the module is loaded check if the config settings are stored using an old schema and update them if necessary.

Changelog makes use of [a similar approach](https://github.com/teppokoivula/ProcessChangelog/blob/master/ProcessChangelogHooks.module), except that in that case it's for database schema.

**Comment by adrianbj** [comment]
Hi @teppokoivula - yeah, something like that is definitely an option. I don't think I'll worry about it for now, but if others come up against the limits of `text`, I might reconsider.
I will close this issue for now.
