### ISSUE TITLE
Multi-instance not working if init.php, ready.php, and finished.php exist

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-issues#327]
Let's say I have two sites on my server: site1.com and site2.com.  They are both running ProcessWire 3.0.68.

I create a script in the PW root of site2.com called 'test.php' which grabs content from site1.com:

```
<?php namespace ProcessWire;
include(dirname(__FILE__).'/index.php');

$site1 = new ProcessWire('/path/to/site1.com/');

echo $site1->pages->find("template=basic-page")->count;
```

When running that script, it just hangs, as if something is infinitely looping.

After troubleshooting, I determined that if I remove ALL the following files from site1.com:

1. /site/init.php
2. /site/ready.php
3. /site/finished.php

... then the script runs correctly.  I must remove all of those three files, not just one.  Even if the three files are empty, it still hangs.

### Setup/Environment
* ProcessWire version: 3.0.68
* (Optional) PHP version: 7.0.15

**Comment by ryancramerdesign** [comment]
I can't seem to duplicate it here. I've got all 3 files present, but it's booting and running as normal. Something to test would be to make the top of your test.php file like the following (below), and then let it run and timeout. What error does it show? It might point to where the issue is. 
~~~~~
<?php namespace ProcessWire;
include("./index.php");
error_reporting(E_ALL);
ini_set('display_errors', 1);
~~~~~

**Comment by jlahijani** [comment]
Hmm... it seems to be working today without problems.  I swear it was an issue when I posted it. :)

Although one thing to note is that it takes 20 seconds to load the script the first time via command line (to count only 40 pages), then nearly instant when running the script a second time, although this is most likely attributable to other things.

**Comment by LostKobrakai** [comment]
Probably the filecompiler at work.
