### ISSUE TITLE
Image replacement doesn't work

### ISSUE THREAD

**Issue by apeisa** [processwire/processwire-issues#330]
### Short description of the issue

ProcessWire allows replacing images also in multi-image fields. While UI shows that image is replaced, the old image will still be there after page save (as is new image also).

### Expected behavior

Replaced image should be gone after page save and new image should have filename of the old image.

### Actual behavior

New image is added just like any new image, and the replaced image stays there (first it is gone, but will re-appear after page save). Also new image will be saved with new filename and the old image keeps old filename. So currently there isn't any way to replace image in multi-image field.

### Optional: Screenshots/Links that demonstrate the issue

Step 1: one image that I want to replace:
![image](https://user-images.githubusercontent.com/131855/28715491-eebe8822-73a0-11e7-94ff-5a94e2f961e8.png)

Step 2: clicked "edit" and next will drag and drop image to replace old one as suggested:
![image](https://user-images.githubusercontent.com/131855/28715542-1a7cc0d2-73a1-11e7-89b8-97934aa5659a.png)

Step 3: image seems to be replaced (although it has new filename, not old one as one would expect in case of replace):
![image](https://user-images.githubusercontent.com/131855/28715569-3f26723e-73a1-11e7-8e50-555777c1f465.png)

Step 4: after page save, both images are visible:
![image](https://user-images.githubusercontent.com/131855/28715610-77115f06-73a1-11e7-8535-b6ec34f3bd8f.png)

### Setup/Environment

* ProcessWire version: 3.0.68
* (Optional) PHP version: PHP 5.5.9-1ubuntu4.11
* (Optional) MySQL version:  Ver 14.14 Distrib 5.5.43, for debian-linux-gnu (i686) using readline 6.3
* (Optional) Any 3rd party modules that are installed and could be related to the issue: None, vanilla default installation

**Comment by ryancramerdesign** [comment]
Thanks Antti, I've pushed a fix for this.

**Comment by apeisa** [comment]
Thanks Ryan. It works now. Although it works different on what I thought it would. If I replace image, I expect new image to get the old filename, no matter what the old filename was. 

If I have used image in ckeditor and replace it with image with different filename, then all those img tags will be broken.

**Comment by apeisa** [comment]
Ryan, eager to hear your opinion on this one? If I replace image, I believe it should use the new image everywhere (keeping the old files filename). Now replacing images ends up in missing images inside ckeditor.

**Comment by ryancramerdesign** [comment]
Wasn't intending for it to keep the same filename, but I can see how that could be useful in the situation you mention (images in CKEditor). Only thing I'm worried about is that this behavior is less desirable outside of CKEditor, like if you are retrieving images by index, first, or tags ... suddenly browser caching will be an issue for any front-end image replacement. But maybe it's an okay compromise, so lets try it out and see how it goes. I've pushed an update that makes it keep the same filename when you do the drop-in replace. 

Btw, for your CKEditor field, details tab, make sure you check the box to "fix broken images" (in the Markup/HTML options). Otherwise keeping the same filename won't help much, unless you are only using full-size/unmodified images in CKE.

**Comment by apeisa** [comment]
Thank you Ryan, now it works exactly as (at least) I believe it should!
