### ISSUE TITLE
Values from WireData objects not populated on InputfieldWrapper

### ISSUE THREAD

**Issue by wanze** [processwire/processwire-issues#339]
### Short description of the issue

`InputfieldWrapper::populateValues()` does not populate values if a WireData object is passed.

### Expected behavior

Values are populated, e.g. when one wants to set all values of a form.

### Suggestion for a possible fix

See pull request: https://github.com/processwire/processwire/pull/81

### Setup/Environment

* ProcessWire version: 3.0.70 (latest dev)

**Comment by ryancramerdesign** [comment]
I looked at the PR, but the line of code that's in populateValues() is what's intended: 
~~~~~
$value = $data->data($name);
~~~~~
Changing that to a `$data->get($name)` means that it can then return more than just the data stored in WireData... it can return API variables and such. So the `data()` call is the one we want here, because it's possible for Inputfield objects to have names that collide with API variables. Meaning, `$data->get($name)` is problematic here. 

Any idea why it wasn't working in your case? Is it possible it was a WireData object that had the value populated some other way, or extended WireData and changed the behavior or something?

**Comment by wanze** [comment]
@ryancramerdesign 
You are right, I'm sorry for not checking this further. In my case I am passing a `Page` object which is derived from `WireData`. But since field values are not stored in the `$data` array, it does not work (logically). I assumed a typo (data vs. get) and did not investigate further.

I will just wrap the page in a plain `WireData` object, then it will work. Thanks anyway for looking into it, I close this issue and also the pull request :)

Best regards
