### ISSUE TITLE
Image/file tags disappear on field reload

### ISSUE THREAD

**Issue by outflux3** [processwire/processwire-issues#340]
### Short description of the issue

For image or file fields with Selectize tags enabled – when uploading a new item, all tags disappear after the field refreshes/reloads.

### Expected behavior

Tags should not disappear

### Actual behavior

Tags all disappear

### Optional: Screenshots/Links that demonstrate the issue

https://processwire.com/talk/topic/16756-pw-3067-upgrades-to-fileimage-tags/?do=findComment&comment=148987

### Optional: Suggestion for a possible fix

No idea

### Steps to reproduce the issue

- add some files or images
- tag them
- upload a new item
- see the tags vanish

### Setup/Environment

* ProcessWire version: 3.0.70
* (Optional) PHP version:  
* (Optional) MySQL version: 
* (Optional) Any 3rd party modules that are installed and could be related to the issue:

**Comment by ryancramerdesign** [comment]
Thanks, I've pushed a fix for this. Looks like the issue is the Selectize is moving the classes from the `<input>` element to some other `<div>`, when using it without predefined tags. I was able to fix it by targeting `input.InputfieldFileTagsInput` for the `selectize()` init, rather than `.InputfieldFileTagsInput`.

**Comment by outflux3** [comment]
great!
