### ISSUE TITLE
The ZIP Archive created by wireZipFile has missing files

### ISSUE THREAD

**Issue by karltaidev** [processwire/processwire-issues#343]
### Short description of the issue

The ZIP Archive created by wireZipFile has missing files.

### Expected behavior

All files should be included inside the ZIP.

### Actual behavior

Some files are missing inside the ZIP.

### Steps to reproduce the issue

I do not have a precise steps to reproduce. I encounter this issue 1. when I am using Site Profile Exporter module. After choosing ZIP method, not all the files exist inside the ZIP file (I have over 10000 pages ID, but the files stop at 9xxx). Using the directory method do not have issues. All files listed as it is. 2. when I use my own page action module to zip files for listerpro. The module is referencing the same way as Site Profile Exporter module but my module loops through the selected items and add the files into archive one by one. Files are missing randomly inside the ZIP file. I would like to help debug but have no idea how to.

### Setup/Environment

* ProcessWire version: 3.0.63

**Comment by ryancramerdesign** [comment]
The ProfileExporter is for exporting relatively small profiles for sharing, and I don't think you could use it for a site with 10k+ pages and files. You'd definitely have to generate a ZIP of that manually from the command line, as I'm pretty sure PHP and ZipArchive will run up against resources well before it gets to such a large number of pages and files. It's also possible ZipArchive has a limit of 9999 entries per dir, which would not surprise me. You could try to increase your PHP memory_limit and set_time_limit(), but I think it's unlikely to work – such a big site should be migrated the normal way. The profile exporter wasn't meant for this (nor built in zip/unzip functions), and even if it could export all of that, there's little chance it could be imported, as that takes even more horsepower. I say that because I think it's probably not worth trying to create a profile manually, as it couldn't be imported. But a traditional site migration should be just fine regardless of scale.

**Comment by karltaidev** [comment]
Thank you for the suggestions. I would check out the memory limit and time limit. 

For your information, I have no issue when importing this around 15000 pages site through the installer. It just take a little bit longer when importing the DB.

I close this one first. If I found the clue I would post here.

**Comment by ryancramerdesign** [comment]
Wow I'm impressed you were able to import 15000 pages through the
installer. Though I suppose that does make sense now that I think about it,
because we're just dealing with SQL queries here rather than instantiated
Page objects. No doubt there's going to be an upper limit to how much you
can do, but clearly it's higher than I thought. Creating a ZIP file of it
all is a different matter though. But if you skip over the ZIP part and
just use the uncompressed profile, maybe it can work.

Different file systems have different max files per directory limits. I'm
guessing this might be what happened with the ZIP file (though could also
have been memory or time limit). But one thing you can do use use the
`$config->pagefileExtendedPaths = true;` option in your /site/config.php
file. This makes PW create no more than 2k files/dirs in one path (which
seems to be a safe limit everywhere). Though it does change the
/site/assets/files/ URLs quite a bit, so it's likely something you'd only
want to set on a new installation.
