### ISSUE TITLE
Can't delete item from repeater with min/max set when nested inside another repeater

### ISSUE THREAD

**Issue by CaelanStewart** [processwire/processwire-issues#362]
### Short description of the issue

I have a repeater with a min/max count set, with any number of items in (the count doesn't seem to matter in this case). When this repeater is nested within another repeater, I am unable to delete any items from the nested repeater, and am presented with the following message upon clicking delete:

> This action is disabled per min and/or max item settings.

The same problem occurs with repeater matrix, too.

### Expected behavior

I should able to delete items as long as there are more than the minimum number of allowed items. 

### Actual behavior

I am presented with an error message and cannot delete.

### Steps to reproduce the issue

1. Create a repeater
2. Create another repeater inside first repeater and assign min/max values
3. Add item to outer repeater
4. Add item to inner repeater
5. Try to delete item from inner repeater

### Setup/Environment

* ProcessWire version: 3.0.62

**Comment by ryancramerdesign** [comment]
I wasn't able to duplicate this one. I setup a nested repeater with min 1 and max 3, added 3 items and saved them. Then deleted two of them and saved. No errors appeared. Admittedly there have been a lot of repeater updates since 3.0.62. Maybe this issue was related to another and likewise fixed when the other was. Please let me know if you continue to see issues with it. Also, if you still see the issue, let me know if the error is one that pops up (javascript) or one that you see after saving.

**Comment by netcarver** [comment]
@CaelanStewart Hello Caelan, following up on Ryan's reply above, can you let us know if this issue still exists on a recent release of ProcessWire? Thank you.

**Comment by CaelanStewart** [comment]
@netcarver, I can't reproduce this now. I think it must have been fixed, as I do remember a bunch of other repeater bugs were fixed too.

Or maybe I somehow misconceived the issue and was mistaken. Who knows. It's not an issue anymore.
