### ISSUE TITLE
localName empty if page name is the same as in default lang (multilang)

### ISSUE THREAD

**Issue by rolandtoth** [processwire/processwire-issues#373]
### Short description of the issue

On a multilanguage setup if a non-default language's name is the same as the default page name, localName($language) returns an empty string (because it's not saved to the DB). This is obviously wrong because pages must have names.

It's a nuissance because one need to check manually if it's empty everytime when using localName(), especially when using urlSegments.

This has been come up earlier too:
https://github.com/ryancramerdesign/ProcessWire/issues/427

### Expected behavior

localName($language) should return the default langauge' s name if it's the same as the default language's name.

### Actual behavior

localName($language) returns an empty string.

* ProcessWire version: 3
* (Optional) PHP version: 7

**Comment by ryancramerdesign** [comment]
Returning blank if the local name is not set is intentional. The method states the return value as "Localized language name or blank if not set". But I understand the confusion that arises since the value won't get set if it's the same as the default. I've updated the method so that you can now specify boolean true as either the first or second argument, and it will fall-back to the default page name where it would otherwise return blank. That should avoid the need for any additional logic after calling the localName method.

**Comment by rolandtoth** [comment]
Sounds great, thanks!

**Comment by rolandtoth** [comment]
Sorry, it was by mistake.
