### ISSUE TITLE
Add official ProcessWire mail address to the code of conduct file

### ISSUE THREAD

**Issue by isellsoap** [processwire/processwire-issues#4]

**Comment by isellsoap** [comment]
Done. https://github.com/processwire/processwire-issues/commit/de92f55fb8b718965313b70e46b5186669a5bd59

**Comment by teppokoivula** [comment]
@isellsoap: whoa, we have a code of conduct? 😮 

Note: not complaining, just a bit surprised. Code of conduct is a pretty big deal (if you take it seriously, otherwise it's pointless), so a bit surprised that this hasn't been mentioned anywhere else (as far as I can tell).

Does this only apply to this repository, or to the whole ProcessWire project like the document itself claims? If it's intended for the whole project, this should be explained on the forums too. Can't really expect everyone to look for such a thing here.

**Comment by isellsoap** [comment]
I’m in contact with @ryancramerdesign regarding this topic. Thanks for your input!
