### ISSUE TITLE
Bug with selector "or" values?

### ISSUE THREAD

**Issue by thetuningspoon** [processwire/processwire-issues#401]
### Short description of the issue

I found what appears to be a bug with or values in selectors. I am on 3.0.62, so I apologize if this may have already been addressed.

I tried to use the following selector to get all BillRates where the client is either blank or a specific page id, and the service is either blank or a specific page id:

$pages->find("template=BillRate, client=2271|, service=1295|");

Strangely, this returned some results where the client or the service were neither the page ID specified or empty.

In order to get the selector to work properly, I had to wrap each of the conditions in a different named OR group:

$pages->find("template=BillRate, c=(client=2271|), s=(service=1295|)")

### Expected behavior

Only pages where the client select field was empty or had the id of 2271 would be returned, and the service was either the page with id of 1295 or empty.

### Actual behavior

Not completely certain... but it included pages that clearly conflicted with the selector parameters.

### Optional: Suggestion for a possible fix

Hopefully my OR group workaround provides some hints as to what's going on under the hood.

### Steps to reproduce the issue

1. Create a template with two page fields
2. Create pages for selection in the page fields
3. Craft a selector similar to the one above, where the condition is empty|1234

### Setup/Environment

* ProcessWire version: 3.0.62

**Comment by ryancramerdesign** [comment]
When you use an OR group, there has to be something in it because a plain "|" with nothing after it (or before it) likely would be considered a potential match value rather than an OR group by the Selectors engine. So I think you'd have to be more specific with this. See if you can get it working as intended with values like `2271|0` or `2271|''` ? Not really sure why it's working with the ones surrounded by parenthesis, but let me know if using 0 or blank quoted string doesn't solve it.

**Comment by thetuningspoon** [comment]
Interesting. I did not realize that '' could be used, or that 0 would work for a Page field. Good to know, thanks!
