### ISSUE TITLE
Hooks on base classes not applied to child classes if different namespace

### ISSUE THREAD

**Issue by owzim** [processwire/processwire-issues#405]
### Short description of the issue

Hooks on base classes not applied to child classes if different namespace

### Expected behavior

Hooks should be applied to all child classes, no matter what namespace

##### `Example1.php`

```php
<?php
namespace Example1SharedNamespace;
class Example1Base extends \ProcessWire\WireData {}
class Example1 extends Example1Base {}
```

##### Usage Example:

```php
// Add hook to the base class
$this->addHook('Example1Base::foo', null, function($e) {
    $e->return = 'foo';
});

require_once __DIR__ . '/Example1.php';

$ex1 = new \Example1SharedNamespace\Example1();
// call foo() on child class
$ex1->foo(); // outputs 'foo'
```

##### `Example2Base.php`

```php
<?php
namespace Example2Namespace1;
class Example2Base extends \ProcessWire\WireData {}
```

##### `Example2.php`

```php
<?php
namespace Example2Namespace2;
class Example2 extends \Example2Namespace1\Example2Base {}
```

##### Usage Example:

```php
// Add hook to the base class
$this->addHook('Example2Base::foo', null, function($e) {
    $e->return = 'foo';
}); // also tried options: array('allInstances' => true), no effect on this issue

require_once __DIR__ . '/Example2Base.php';
require_once __DIR__ . '/Example2.php';

$ex2 = new \Example2Namespace2\Example2();
// call foo() on child class
$ex2->foo(); // Method Example2::foo does not exist or is not callable in this context
```

### Setup/Environment

* ProcessWire version: 3.0.62
* PHP version: 5.5.38

**Comment by ryancramerdesign** [comment]
I hadn't planned to support this since hooks aren't really in the business of namespaces and instead isolated to ProcessWire and root (legacy) namespace, but your examples were so good, I had to try and see about supporting this. After experimenting a bit I think I've got it working now, thanks. Just note that attaching hooks is not namespace aware. But now you should be able to extend as much as you like in other namespaces and it should still work so long as it originates with a Wire class.

**Comment by netcarver** [comment]
Hi @owzim Could you close this if it's fixed. Thank you!

**Comment by owzim** [comment]
Thanks for the effort @ryancramerdesign 
Sorry for not closing this earlier. /cc @netcarver
