### ISSUE TITLE
Multiple Page Reference fields lead to JS errors

### ISSUE THREAD

**Issue by dreerr** [processwire/processwire-issues#411]
### Short description of the issue

With multiple page reference fields the select button fades in and out again.

### Expected behavior

select button should only fade in.

### Actual behavior

select button fades in and then out again.

### Optional: Screenshots/Links that demonstrate the issue

https://processwire.com/talk/applications/core/interface/file/attachment.php?id=12288

### Steps to reproduce the issue

Create multiple page refs with different options

### Setup/Environment

<details><summary><strong>Server Details</strong></summary>ProcessWire: 3.0.80 <br />
PHP: 7.1.4 <br />
Webserver: Apache/2.4.18 (Unix)  <br />
MySQL: 5.7.17 <br />
 <br />
<details><summary><strong>Server Settings</strong></summary> allow_url_fopen: 1 <br />
max_execution_time: 120 (changeable) <br />
max_input_nesting_level: 64 <br />
max_input_time: 60 <br />
max_input_vars: 1000 <br />
memory_limit: 256M <br />
post_max_size: 8M <br />
upload_max_filesize: 2M <br />
xdebug:  <br />
xdebug.max_nesting_level: 256 <br />
 <br />
mod_rewrite: 1 <br />
mod_security: *confirmed off <br />
 <br />
GD: bundled (2.1.0 compatible) <br />
GIF: 1 <br />
JPG: 1 <br />
PNG: 1 <br />
 <br />
EXIF Support: 1 <br />
FreeType: 1 <br />
Imagick Extension:  <br />
 <br />
</details><details><summary><strong>Module Details</strong></summary> AdminOnSteroids: 1.6.1 <br />
AutodetectLanguage: 1.0.3 <br />
AvbImage: 0.0.4 <br />
CronjobDatabaseBackup: 1.1.5 <br />
CroppableImage3: 1.1.15 <br />
DiagnoseDatabase: 0.0.2 <br />
DiagnoseFiles: 0.0.1 <br />
DiagnosePhp: 0.0.7 <br />
DiagnoseWebserver: 0.0.1 <br />
EmailObfuscation: 1.1.0 <br />
FieldtypeAdminCustomPagesSelect: 1.0.0 <br />
FieldtypeCroppableImage3: 1.1.7 <br />
FieldtypeFunctional: 0.0.1 <br />
FieldtypeMultiplier: 0.1.1 <br />
FieldtypePadNotes: 0.0.3 <br />
FieldtypeRepeaterMatrix: 0.0.4 <br />
FieldtypeTable: 0.1.7 <br />
FieldtypeTextareas: 0.0.7 <br />
HannaCodeHelper: 0.5.0 <br />
ImageExtra: 1.0.6 <br />
InputfieldCroppableImage3: 1.1.8 <br />
InputfieldFunctional: 0.0.1 <br />
InputfieldMultiplier: 0.1.1 <br />
InputfieldPadNotes: 0.0.3 <br />
InputfieldRepeaterMatrix: 0.0.4 <br />
InputfieldTable: 0.1.7 <br />
InputfieldTextareas: 0.0.7 <br />
MarkupJsonLDSchema: 0.0.2 <br />
MarkupSimpleNavigation: 1.3.4 <br />
MarkupSrcSet: 0.1.2 <br />
PadCart: 0.0.2 <br />
PadCheckout: 0.0.1 <br />
PadDownloads: 0.0.1 <br />
PadLoper: 1.2.0 <br />
PadOnePageCheckout: 0.0.1 <br />
PadProcess: 0.0.2 <br />
PadProcessDownloads: 0.0.1 <br />
PadProcessShipping: 0.0.1 <br />
PadRender: 0.0.1 <br />
PageCleanEmptyDirs: 0.0.3 <br />
PageProtector: 1.0.6 <br />
PageSnapshot: 1.1.20 <br />
PageimageRemoveVariations: 0.0.4 <br />
PaymentInvoice: 0.0.1 <br />
PaymentModule: 0.0.1 <br />
ProCache: 3.1.6 <br />
ProcessAdminActions: 0.6.1 <br />
ProcessAdminCustomPages: 1.1.1 <br />
ProcessCroppableImage3: 1.1.10 <br />
ProcessDiagnostics: 0.2.2 <br />
ProcessHannaCode: 0.2.0 <br />
ProcessJumplinks: 1.5.48 <br />
ProcessProCache: 3.1.6 <br />
ProcessVersionControl: 1.2.4 <br />
ProcessWireUpgrade: 0.0.7 <br />
ProcessWireUpgradeCheck: 0.0.7 <br />
ShippingFixed: 0.0.1 <br />
TextformatterHannaCode: 0.2.0 <br />
TextformatterHeadline: 1.0.0 <br />
TracyDebugger: 4.6.20 <br />
VersionControl: 1.2.9 <br />
</details></details>

**Comment by Toutouwai** [comment]
This issue affects both PageListSelect and PageListSelectMultiple when there is more that one inputfield of those types on a page.

A screen capture that is a bit easier to view than the video linked to above:
![page-list](https://user-images.githubusercontent.com/1538852/32131276-b3f1e730-bc06-11e7-84e2-dd764e1b0be2.gif)

### Suggestion for a possible fix

The issue occurs because some of the jQuery selectors are too broad, matching elements right across the DOM instead of only within the container of that inputfield.

I made the following changes to ProcessPageList.js that seem to resolve the issue, but I haven't gone through in detail to see if there are other selectors that are too broad.

Added after [line 152](https://github.com/processwire/processwire/blob/c90fc3f8726861c6b565409272ad409dd16adc21/wire/modules/Process/ProcessPageList/ProcessPageList.js#L152):
````js
var $outer = $container.is(":input") ? $container.parents('.InputfieldPageListSelectMultiple, .InputfieldPageListSelect') : $container;
````

Changed [line 226](https://github.com/processwire/processwire/blob/c90fc3f8726861c6b565409272ad409dd16adc21/wire/modules/Process/ProcessPageList/ProcessPageList.js#L226):
````js
$outer.on('keydown', '.PageListItem', function(e) {
````

Changed [line 241](https://github.com/processwire/processwire/blob/c90fc3f8726861c6b565409272ad409dd16adc21/wire/modules/Process/ProcessPageList/ProcessPageList.js#L241):
````js
$outer.on('mouseover', '.PageListItem', function(e) {
````

Changed [line 262](https://github.com/processwire/processwire/blob/c90fc3f8726861c6b565409272ad409dd16adc21/wire/modules/Process/ProcessPageList/ProcessPageList.js#L262):
````js
var $hideItems = $outer.find(".PageListItemHover");
````

**Comment by ryancramerdesign** [comment]
Thanks for the report @dreerr and thanks for the fix @Toutouwai, I've pushed this to the dev branch.
