### ISSUE TITLE
Trash restore icon is trashcan

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#412]
### Short description of the issue

Trash restore icon is trashcan

### Expected behavior

I think it should be a different icon because this suggests deleting, not restoring.

### Optional: Screenshots/Links that demonstrate the issue

![screen shot 2017-10-23 at 9 35 00 am](https://user-images.githubusercontent.com/871211/31901155-80733056-b7d5-11e7-919b-f14767258dbb.png)

**Comment by szabeszg** [comment]
suggestions:
- Recycle
- Thumps-up
- Reply

**Comment by matjazpotocnik** [comment]
Or no icon at all. Just Trash/Restore.

**Comment by szabeszg** [comment]
It is an important action so I support keeping it prominent by using an icon it's just the trash can which is misleading a bit.

**Comment by matjazpotocnik** [comment]
Are you saying that other actions are not important? :-)

**Comment by szabeszg** [comment]
I mean under Admin > Trash, that is where you can undo the trashing operation, it is good to be able to spot this one easily.

**Comment by teppokoivula** [comment]
> Are you saying that other actions are not important? :-)

Probably not more important, but rather different. It's the only action that I'd describe as "destructive", so definitely worth making it stand out.

**Comment by matjazpotocnik** [comment]
You can restore from trash, so trash is not that destructive, or is it? If trash action is destructive, is restore action also destructive? Is unpublish action destructive? It might be, because you are potentially "removing" the content form the site. But that action can be reversed easily. Is save action destructive? Well, it could be, since there is no easy way of reversing the content of page. I'm not against the trash/restore icon, just thinking out loud. And of course, trashbin icon is inappropriate for restore action, no doubt about that.

**Comment by teppokoivula** [comment]
Good points :)

I see trash as a more destructive action mainly because restoring a page is somewhat more tedious than, say, publishing a page that was accidentally unpublished. Page "disappears" into trash, and it can take a while to relocate it. Restoring trashed pages is also out of bounds for non-superusers, but then again I believe the page tree action is also (unless somehow overridden).

**Comment by ryancramerdesign** [comment]
I don't think the Restore button is clear enough without the trash icon, because then it's just "Restore", and what does that mean? The label could be "Trash Restore" or "Restore from Trash", but I think that's just too long. If font-awesome had a `trash-slash` or `trash-arrow-up` icon, no doubt it would be preferable. But there isn't anything like that. Another option might be a different label using a made-up word "untrash".

**Comment by teppokoivula** [comment]
Just dropping this here in case someone wants to add their vote: https://github.com/FortAwesome/Font-Awesome/issues/4090.

**Comment by matjazpotocnik** [comment]
> because then it's just "Restore", and what does that mean? The label could be "Trash Restore" or "Restore from Trash",

Since we are already in Trash, there is no need for words "...from Trash". Also it would be too long. But I think we have more important issues to deal with so the best option right now, as I see it, is that we wait for un-trash icon.

**Comment by adrianbj** [comment]
> Since we are already in Trash, there is no need for words "...from Trash".

I completely agree - you're in the trash section - if you can't figure out what "restore" means, there's a problem :)

I don't honestly see the problem with using the `reply` icon and keeping the "Restore" text just as it is. Yes, the proposed new icon that @teppokoivula linked to would be better, but for now I think `reply` would be fine. 

But, I also agree that this isn't a huge deal - I never expected so much conversation on it.

**Comment by matjazpotocnik** [comment]
Works with fa-stack: https://github.com/FortAwesome/Font-Awesome/issues/4090#issuecomment-369160198
Demo: https://codepen.io/fxmt/pen/vdvdKy

**Comment by adrianbj** [comment]
FontAwesome now has a free trash restore icon:
https://fontawesome.com/icons?d=gallery&q=trash-restore&m=free

@ryancramerdesign - any chance of a FA upgrade and including this new icon?

**Comment by netcarver** [comment]
@ryancramerdesign Bumping for your consideration.

**Comment by ryancramerdesign** [comment]
@netcarver @adrianbj I think the previous two mentioned options above both require Font Awesome 5.x, which is not compatible with version 4.7 that we are using. Actually 5.x is like a different product, using different icon names in many cases and requiring different class names. Looks like a painful upgrade, short of applying a compatibility hack on top of it. When we upgrade to it, it'll likely be tied to a major PW version.

**Comment by netcarver** [comment]
Ok, I'll transfer this to the requests repo in that case.
