### ISSUE TITLE
Link abtraction on textarea language field (Ckeditor) the alternative language don't get saved

### ISSUE THREAD

**Issue by somatonic** [processwire/processwire-issues#426]
### Short description of the issue

Link Abstraction on textarea language field enabled. As soon as the default language has some links in the text that get abstrated, the alternative language of that field doesn't get saved (stays empty). As soon as I remove the default links in the text, the alternative language gets saved correctly.

### Steps to reproduce the issue

1. Step on a site with two languages. create textarea language ckeditor field with link abstractor enabled
2. Step enter some text in the default language and some links to pages
3. Step enter text in the alternative language and save

### Setup/Environment

* ProcessWire version: 3.0.62
* (Optional) PHP version: 5.5.9

**Comment by somatonic** [comment]
There seems to be two options on textarea fields for link abstraction I realized. One is the experimental and the old one is also there in 3.0.62:

![image](https://user-images.githubusercontent.com/370148/33317827-b653bb30-d438-11e7-9bf8-0f4b76b84b07.png)

If the one on the bottom is active, text on alternative language is empty when in the default language there is a link inserted which gets abstracted. Oddly enough the text recovers when the link abstraction is turned off.

**Comment by ryancramerdesign** [comment]
I can't duplicate the issue here, but I think I know what the issue is—you've got competing link abstraction, like you mentioned above. One is from the old 3rd party module, while the other is in the core. You'd want to choose one or the other, and they are likely colliding with each other. 

The other possibility is just that the old Page Link Abstractor might not support languages or PW3 (it's been so long I don't remember). There's not really a need for the 3rd party PageLinkAbstractor module anymore since it's now built into the core. The only reason to keep using it is if your links have already been abstracted with it (like on an older site).
