### ISSUE TITLE
Large file upload stuck at 100%

### ISSUE THREAD

**Issue by PWaddict** [processwire/processwire-issues#429]
### Short description of the issue

Uploading a 90MB zip file using the Files field the progress stuck at 100% and then the following error appears on Chrome's console:

_Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Function.parseJSON (JqueryCore.js:2)
    at XMLHttpRequest.<anonymous> (InputfieldFile.js?v=125-1510158791:277)_

**Note:** Uploading the exact same file on "[Padloper Downloads](https://www.padloper.pw/)" is working properly. The process there is more old-school without AJAX.

### Optional: Screenshots/Links that demonstrate the issue

![file_upload](https://user-images.githubusercontent.com/23142666/32571853-87387dd4-c4d1-11e7-8780-aa070165e4e2.jpg)

### Setup/Environment

* ProcessWire version: 3.0.82

**Comment by adrianbj** [comment]
Same with any of these ajax upload errors - you need to select the upload script from the dev console and click on the response tab so you can see the actuall php error.

**Comment by Toutouwai** [comment]
This looks like something that should be posted in the forums in the first instance. There should be an attempt to confirm that something is an actual bug before creating an issue here.

**Comment by PWaddict** [comment]
@adrianbj Thanks for the info. It was memory exhausted error. I've increased the memory_limit through cpanel and the problem fixed.

@Toutouwai You're right. I don't know why I posted here first.

**Comment by adrianbj** [comment]
Glad you got it sorted!

The other thing that is very handy is to enable "Strict" mode in Tracy - you can do this in the module config settings, but I probably recommend doing it via the button on the Panel Selector. With this enabled, the php error message will actually be captured by the AJAX bar in Tracy - makes it easier to see/find. 

I don't like having it enabled all the time though, especially because it means that AJAX requests will work when they shouldn't - the error will show up, but you might not notice it, so best to leave off until you have a problem and just enable for debugging.
