### ISSUE TITLE
Field not saving, have to set twice to save.

### ISSUE THREAD

**Issue by TomS-** [processwire/processwire-issues#434]
### Short description of the issue
As I have mentioned, I'm building an eCommerce system for ProcessWire which I will be releasing open source. However I have discovered this issue. 

I couldn't tell you why this is happening, I have no idea. Basically here is a video showing the problem. 
https://www.youtube.com/watch?v=GMrwd6TeHSg

Here is the code which is causing the problem: 
```
$options = wirecommerce_get_all_variations($page);
$variations = $page->wirecommerce_variations;

// Detect added
$added = 0;

foreach($options as $option) {
   if(!$variations->has("wirecommerce_variation_value='$option'")) {
      $new_option = $variations->getNewItem();
      $new_option->wirecommerce_variation_value = $option;
      $new_option->save();

      $added++;
  }
}
if($added > 0) $this->message("$added variations added.");
```
Here is what $options outputs 
```
Array
(
    [0] => Size=Small,Colour=Green
    [1] => Size=Small,Colour=Blue
    [2] => Size=Medium,Colour=Green
    [3] => Size=Medium,Colour=Blue
)
```
**If I don't use $new_option->save(); it works fine, however I can only added one at a time and you have to keep clicking save.** 

Is this a mod_security being hit? Script timeout? Or something bigger?

### Expected behavior

It should create and save all options while also making sure the other repeater field saves. 

### Actual behavior

The repeater above does not save. 

### Optional: Screenshots/Links that demonstrate the issue

https://www.youtube.com/watch?v=GMrwd6TeHSg

### Steps to reproduce the issue

1. Create a template. 
2. Add two repeaters to the template. 
3. Add repeaters to one of the repeaters on hooking Pages::save (this bug occurs when using $page->save() or in my case $new_page->save() see: https://github.com/processwire/processwire-issues/issues/434).
4. The repeater in which doesn't add content via the api doesn't get saved, or the reference case the PageReference. 

I believe these two issues are linked. There is a more in depth step by step here - https://processwire.com/talk/topic/17720-field-only-saving-when-set-twice/?tab=comments#comment-156013

### Setup/Environment

* ProcessWire version: 3.0.82

**Comment by TomS-** [comment]
Note: Few things that were raised in the forum, Mod_Security is turned off, $page->of(false) and $new_option->of(false) does nothing, $variations->add($new_option); does nothing.

**Comment by ryancramerdesign** [comment]
Having a save() in a loop can be problematic because PW has to clear page caches after a save has occurred. For that reason, I try and avoid save()'s in loops. But when that's not possible, I usually supply the uncacheAll=false option to the save(), so that nothing gets uncached until I want it to. In your case, I can see why that bit of code is not going to work. Try these things to see if it helps:

After your loops, populate $variations back to $page->wirecommerce_variations and make sure that the page gets saved (if it isn't already). 

If that doesn't do it, try $page->trackChange('wirecommerce_variations'); before it gets saved. 

Finally, if that doesn't do it, try to get a fresh copy of $page and populate $variations back to $page->wirecommerce_variations, and then save. 

If the above simple solutions don't work, try splitting your getting of new items from the saves:
~~~~~
$new_options = array();
foreach($options as $option) {
   if(!$variations->has("wirecommerce_variation_value='$option'")) {
      $new_option = $variations->getNewItem();
      $new_option->wirecommerce_variation_value = $option;
      $new_options[] = $new_option; 
      $added++;
  }
}
foreach($new_options as $new_option) {
  $new_option->save([ 'uncacheAll' => false]); 
}
$page->wirecommerce_variations = $variations; 
$page->save();
~~~~~
There's one remaining issue, which is that FieldtypeRepeater::getNextReadyPage() has a save() in it, and it doesn't have an uncacheAll option. For your case, it might need it. Try changing the $readyPage->save(); in that method with $readyPage->save([ 'uncacheAll' => false ]); If that helps, I can add an option to the getNextReadyPage() method to support it. So long all the saves are uncached, it might also be okay if it's done in a single loop, like in your original example.

**Comment by TomS-** [comment]
Thanks for all your feedback Ryan, actually just adding `["uncacheAll" => false]` worked:

     $options = wirecommerce_get_all_variations($page);
     $variations = $page->wirecommerce_variations;

    // Detect added
    $added = 0;

    foreach($options as $option) {
        if(!$variations->has("wirecommerce_variation_value='$option'")) {
            $new_option = $variations->getNewItem();
            $new_option->wirecommerce_variation_value = $option;
            $new_option->save(["uncacheAll" => false]);

            $added++;
       }
    }
    if($added > 0) $this->message("$added variations added.");

Thank you very much, might be worth putting that somewhere in the documentation as with Repeaters and Repeater Matrix being so useful, I imagine someone will come across this in the future. (Same for Page Reference).

**Comment by Toutouwai** [comment]
> Having a save() in a loop can be problematic because PW has to clear page caches after a save has occurred. For that reason, I try and avoid save()'s in loops.

It's not just loops - it's any page save inside a hook before `Pages::save()` or before or after `Pages::saveReady()`. What I don't understand is why the issue seems to only affect fields whose value is a PageArray (see related issue #430). For instance, why is the new value of a text field not lost but the new value of a Page Reference field is lost when `uncacheAll` is true?

**Comment by TomS-** [comment]
@Toutouwai sounds like there could still be a problem somewhere? I don't understand enough about `uncacheAll` to know it's effects when saving via the API.

**Comment by ryancramerdesign** [comment]
> For instance, why is the new value of a text field not lost but the new value of a Page Reference field is lost when uncacheAll is true?

Because the cache that uncacheAll affects only Page and PageArray objects in it and that's all that it stores. When a save() occurs, all the cached references to pages (and arrays of them) in memory are removed so that they are forced to be reloaded whenever something requests them. When you've got some Page object (or PageArray from a find), what you've actually got is a reference (pointer) to to an object (that is kept in a cache by the $pages API var), and any further requests for that page will return a reference to that same object, rather than another version of it. At least until that cache is cleared. Things like text fields aren't reference based... meaning it's not just a pointer to a value, it's the actual value itself.

**Comment by thetuningspoon** [comment]
@ryancramerdesign Could you clarify why uncaching is necessary after saving a page? I'd like to know better when it is safe to call a save with uncacheAll and when it's not. I'm finding myself needing to disable uncacheAll a lot (for example, editing 2 pages at once), and it makes me wonder why it's not the default.

I'm also still a bit confused as to why primitive fields are not uncached, since they are part of pages, which are uncached. I'm not sure how it would be possible to uncache an object but somehow preserve its primitive properties.
