### ISSUE TITLE
PHP 7.2 removes mcrypt extension

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#447]
### Short description of the issue

PHP 7.2 is now the new stable and it removes the mcrypt extension. Maybe it's ok to leave that `mcrypt_create_iv()` call in Password.php because you do have the `openssl_random_pseudo_bytes` fallback, but maybe it should be restructured to prioritize a currently valid function?

**Comment by adrianbj** [comment]
PS - might be worth having a read here: http://us2.php.net/archive/2017.php#id2017-11-30-1 for other relevant changes to PHP 7.2

**Comment by ryancramerdesign** [comment]
I think the current order is probably good to keep in place, using mcrypt_create_iv if it's present, otherwise falling back to openssl_random_pseudo_bytes (or further as needed). That maintains consistency with where it's been, without causing any problems in PHP 7.2. Though I will look to see if there's anything new in PHP 7+ that we can also benefit from here in terms of this function. The reality is it takes web hosts a long time to get up-to-speed with PHP versions, and especially with PHP 7+ having several breaking compatibility changes, so I've got to be careful about assumptions with PHP versions. I still don't yet see nearly as much PHP 7 on production servers as I do previous versions.

**Comment by adrianbj** [comment]
The Sodium crypto library is included in PHP7.2 -  I think that is what you need to be using going forward. Remember that mcrypt hasn't been updated since 2007. I am sure it's not that relevant given that PW is only using `mcrypt_create_iv` for creating a random string.

Perhaps this is a useful starting point for you:

```
/**
 * 
 * @link https://stackoverflow.com/a/31498051/2224584
 * 
 * @param int $length How long should the string be?
 * @param string $alphabet Contains all of the allowed characters
 * 
 * @return string
 */
function sodium_random_str($length, $alphabet = 'abcdefghijklmnopqrstuvwxyz')
{
    $buf = '';
    $alphabetSize = strlen($alphabet);
    for ($i = 0; $i < $length; ++$i) {
        $buf .= $alphabet[\Sodium\randombytes_uniform($alphabetSize)];
    }
    return $buf;
}
```

Also, not the comment in that linked SO post:
> Also, openssl_random_pseudo_bytes() might not be reliable under extreme conditions or exotic setups.

Not sure how accurate that is, but might be worth considering?

**Comment by ryancramerdesign** [comment]
As far as I've been able to tell, mcrypt_create_iv should still have preference when it's present, but for the times it's not going to be present PHP7 (all versions) adds a random_bytes() function which generates cryptographically secure pseudo-random bytes, and sounds like a good replacement. And that's great about PHP7.2 having libsodium, as that will be even better. I'm going to wait a bit on adding that till I can experiment with it a bit more, but will probably add support for that random_bytes function today.

**Comment by adrianbj** [comment]
Thanks Ryan - I'll let you close this one when you're ready. Not sure if you want to keep it open as a reminder to take a look at libsodium.

**Comment by netcarver** [comment]
@ryancramerdesign Can this be closed now?

**Comment by ryancramerdesign** [comment]
@netcarver Sure, I will go ahead and close it.

**Comment by adrianbj** [comment]
Sorry, so does this mean you're not planning on implementing libsodium's encryption then?
