### ISSUE TITLE
Log viewer  can't handle log files not using \t delimiter, even though the save method lets you specify a custom delimiter.

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#45]
### Short description of the issue

The `lineToEntry()` method used by the log viewer (Setup > Logs) can only parse files with a tab as the delimiter (https://github.com/processwire/processwire/blob/bac5b0de5d95b5a10c09f48ba5e63b419ee68799/wire/core/WireLog.php#L301), but the `WireLog::save` method supports custom delimiters (https://github.com/processwire/processwire/blob/bac5b0de5d95b5a10c09f48ba5e63b419ee68799/wire/core/WireLog.php#L105).

### Expected behavior

Not sure :)

### Actual behavior

A log file using another delimiter wouldn't be parsed correctly.

### Optional: Suggestion for a possible fix

Maybe the simplest / only option is to remove the delimiter option when saving to a custom log file, but I am really not sure.

**Comment by ryancramerdesign** [comment]
The custom delimiter option is there in case someone needs to produce log files for some other parser that requires a different delimiter, or maybe someone wants to use the class somewhere else at some point. However, since that's a granular options argument to a function, and not a PW $config option, I think it's probably best to leave as-is.
