### ISSUE TITLE
Title field HTML Entity Encoder textformatter breaks various things when there is an ampersand

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#455]
### Short description of the issue

If you select the HTML Entity Encoder textformatter on the Title field and your page title has an ampersand in it, the "View" PageListAction no longer appears. Interestingly, the "View" when editing the page was still there.

Obviously calling `$page->title` returns: `This &amp; That`

Also, I received a property of non-object error when calling this page when it is selected in a Page Reference field.

Turning off the textformatter fixed all these issues.

### Optional: Suggestion for a possible fix

I know the simple answer is to not select this textformatter on the title field. This happened on a colleagues site. He is fairly new to PW and I guess thought this option would add safety. The problem is that the side-effects in case of the title field are much worse than a regular field, so I am wondering if there should be some warning, or if it shouldn't be available as an option for the title field? Not sure ...

**Comment by adrianbj** [comment]
Sorry, I just remembered that textformatter is on by default for the title field. So I guess the question now is how to handle pages with an ampersand in the title without breaking the "view" page list action button and also the issue with Page Reference fields.

Let me know if you have any trouble reproducing.

**Comment by ryancramerdesign** [comment]
If you are talking about in the PageList, or in PageLister, I can't reproduce. It's very common to use ampersands in page titles. It shouldn't matter what textformatters are selected for your title field, because whatever is output for page labels has to be entity encoded either way (would not be safe otherwise). Are you using a custom page label format (template advanced settings)? Any other modules installed that affect the PageList? Also curious if you have any ideas why "View" isn't shown, but presumably the other actions are? The only reason I could think that "View" wouldn't be shown would be if there was no template file present for the page... but that of course wouldn't have any relation to textformatters or page labels.

**Comment by adrianbj** [comment]
I am talking about the normal PageList.

It's reproducible for me on several sites/servers. As soon as I either remove the textformatter or remove the ampersand, the View action returns and the Page Reference field error goes away.

Yes, it's the only action button that is affected - all the others are fine.

Guess I'll have to investigate some more :)

**Comment by ryancramerdesign** [comment]
If you inspect the markup behind it (you might need to look at the ajax response on the browser dev tools Network tab), does it seem like it's not displaying as a result of some problem with the markup, or does it appear to be literally excluding the View action from the response? 

Also curious if you are using a custom page label format, either in the ProcessPageList module settings, or on the template settings (for template used by pages where you are seeing the issue).

**Comment by adrianbj** [comment]
It looks like it is somehow affecting the `status`

With the textformatter on, the page status is: `131073` and with it off, it is `1`

I checked this by dumping the status on line 512 of PagePermissions.module. If I check the status of the page anywhere else, it always returns `1` as expected.

**Comment by adrianbj** [comment]
> Also curious if you are using a custom page label format, either in the ProcessPageList module settings, or on the template settings (for template used by pages where you are seeing the issue).

No - nothing in either of these.

**Comment by adrianbj** [comment]
Also, nothing hooking into: `ProcessPageListActions::getActions()` and the only hook for `Page::viewable()` is coming from `PagePermissions::viewable()`

**Comment by ryancramerdesign** [comment]
That status indicates the page is runtime corrupted, which isn't anything bad—it's just means it cannot be saved, because it's got a formatted value set in the page data, which shouldn't be committed to the DB. But if something performs an access control "viewable" check with `status < something` (rather than using bitmask operation) then that could feasibly prevent the view action from being shown. The `status <` checks are okay to do on status stored in DB queries though.

**Comment by ryancramerdesign** [comment]
Are the pages having the issue under any kind of access control? (core or otherwise) In my test case, they are not.

**Comment by adrianbj** [comment]
No access control settings on the template (and it is repeatable on different templates).

If I remove this line https://github.com/processwire/processwire/blob/ded6476832188cf57dd6eef630131e75e09127d1/wire/modules/PagePermissions.module#L512 or set $viewable to true on that line, then everything works again.

**Comment by ryancramerdesign** [comment]
Great, I think you found it there. This is enough that I can fix it, as I can add a check for corrupted status there. Thanks. That does leave the question of why it has a corrupted status though. Corrupted status happens when a formatted value is set back to the page (stored with it, rather than the correct unformatted value). It's not a problem, but a curiosity, because it seems to be different than what's happening here.

**Comment by adrianbj** [comment]
> That does leave the question of why it has a corrupted status though. Corrupted status happens when a formatted value is set back to the page

Let me know if there is something I can do to debug why that might happen - I am sure you can point me to it quicker than I'll find it :)

Glad you think you can fix regardless!

**Comment by ryancramerdesign** [comment]
I just pushed a fix. Does this seem to resolve it? 

Regarding why the pages are getting corrupted, here's a good place to start, if you want to experiment: Go to the ProcessPageList module settings (Modules > Configure > ProcessPageList), and change the Page List Label Field from "title" to "title status". Now browse the PageList and see which pages have that corrupted status, rather than just "1". Maybe it will help to point us towards something. Try disabling or uninstalling modules to see if it changes that in the PageList. There is something setting values back to the $page object. Is this something that Tracy does, perhaps as part of an inspection of some sort?

**Comment by adrianbj** [comment]
This does fix it - thanks very much!

It's not an issue with Tracy.

I actually just reverted to 3.0.84 and it also seems to be fixed there. Any ideas what might have changed? Keep in mind that I was running the very latest commit (not the one that was released as 3.0.85).

Let me know if I can help track it down to a specific commit from this week.

**Comment by adrianbj** [comment]
Just to confirm - definitely works fine with 3.0.84 and works again now with your fix - so something changed since 3.0.84

**Comment by ryancramerdesign** [comment]
Hmm, maybe related to some changes in the way autojoin works. If you show status in the PageList, does it still show the page with the "&" in it as having the corrupted status?

**Comment by adrianbj** [comment]
> does it still show the page with the "&" in it as having the corrupted status?

3.0.84 -> 1
3.085 -> 131073
latest commit -> 1

**Comment by ryancramerdesign** [comment]
Okay that's weird because the latest commit doesn't do anything to the page status... it just disregards corrupted status in the access control check. So I expected that the Page should still have that corrupted status, and wanted to pursue where it might have came from... but now it's not there. :) I think that's probably good though, it seems like things are back in order, one way or another.

**Comment by adrianbj** [comment]
> So I expected that the Page should still have that corrupted status, and wanted to pursue where it might have came from... but now it's not there.

Ok, this is weird. Your fix isn't necessary. What actually fixed it was this commit:
https://github.com/processwire/processwire/commit/04b7dd040498e3cef84c1f65717e451defc6bb54

I haven't checked exactly which commit broke it, but this one fixes it. Does that help to explain why?

**Comment by ryancramerdesign** [comment]
Ah that makes sense. That must be it. I'd fixed something different in that particular commit, but it looks like the issue fixed there was a little broader scope than I realized.

**Comment by adrianbj** [comment]
Ok, I'll close this - sorry that you already had a fix in place. I guess my timing was perfect - between bug introduced and inadvertently being fixed :)

Not sure if you want to remove that last addition to the viewable() method? I guess it can't cause any harm so still might be a useful check?

**Comment by ryancramerdesign** [comment]
I'm think we'll leave that update there, as it should probably be there
either way.
