### ISSUE TITLE
Can't Upload file named in Arabic!

### ISSUE THREAD

**Issue by Mu9tafa-Online** [processwire/processwire-issues#462]
**Error**: Unable to move uploaded file to ...
**PW**: v3.0.86
**PHP**: 7.2

![error_file](https://user-images.githubusercontent.com/5323832/34310484-7bde6d16-e760-11e7-83b8-4f424b9ee6e0.PNG)

**Comment by ryancramerdesign** [comment]
It looks like this occurs because PHP's iconv() cannot translate the given Arabic text to ascii. It's possible that a different locale setting and/or server language settings may enable it to work. However, I think it's still good for us to have a fallback. I have updated it so that if an ascii translation of the filename fails, it falls back to the field name, and generates numbered filenames based upon it. If you uploaded a PDF file with an Arabic name and your field was named "resume_list" and the filename could not be translated by iconv(), then it would name your file resume_list.pdf (resume_list-1.pdf, resume_list-2.pdf, etc.)

**Comment by Mu9tafa-Online** [comment]
This is Brilliant, Thaanks :) - Works Fine.

**Comment by adrianbj** [comment]
@Mu9tafa-Online - if you'd like more control over what the filenames end up being, take a look at: http://modules.processwire.com/modules/process-custom-upload-names/

**Comment by Mu9tafa-Online** [comment]
@adrianbj - I Will Definitely Try It, Many Thaaaanks 🥇
