### ISSUE TITLE
Single-language page throws 404 when accessed via multi-language parent

### ISSUE THREAD

**Issue by philippdaun** [processwire/processwire-issues#463]
### Short description of the issue

When verifying access to multi-language pages, templates with disabled multi-language functionality are not handled correctly. Viewing a page in a non-default language results in a 404 error if

1. that page's template has multi-language **disabled**
2. its parent page's template has multi-language **enabled**

### Use case

Example: a site with multiple news trees, one for each language, each containing only news items in that particular language.

The news list template technically needs to be multi-language in order to have consistent URLs with prepended language names throughout the site (`/en/`). The news item template can however be single-language since we already made sure the language name is prepended by having a multi-language parent. Multi-language capabilities for the child template have therefore been disabled via `$template->noLang = 1`.

#### Templates

- Parent template `news-list`, multi-language
- Child template  `news-item`, single-language

#### Page tree example

- Neuigkeiten   [`news-list`]
  -  Erste Nachricht   [`news-item`]
- News   [`news-list`]
  - First news item   [`news-item`]

### Expected behavior

Accessing a child page in a non-default language at `/en/news/first-news-item/` should render the page for all users with proper view permissions.

### Actual behavior

Guest users get a 404 error accessing the page.

Logged-in users can however see the page since they have edit access.

### Reason for that behaviour

The 404 error gets thrown in `LanguageSupportPageNames.module`. In `verifyPath()` we are checking if the page has a positive status for the language that was determined from the URL.

Since the child page in question has no status for that particular non-default language (multi-language support was disabled for that template), the status returns negative. That means that even though the page is published, `verifyPath()` will throw a 404.

### Suggestion for a possible fix

The fix is pretty straightforward: in addition to checking for language status, we'll make sure the template doesn't happen to have multi-language disabled: `$page->template->noLang`

So line 270:

    $active = $page->get("status$setLanguage") > 0; 

becomes:

    $active = $page->get("status$setLanguage") > 0 || $page->template->noLang;

It might be necessary to apply the same fix in line 265.

The fix does not affect other status checks: unpublished pages will continue to result in a 404 since their global status is still taken into account.

### Setup/Environment

* ProcessWire version: 3.85 (dev branch)

**Comment by ryancramerdesign** [comment]
If I understand what you are stating correctly, this isn't the intended behavior. When you disable multi-language for a given template, that means that it behaves as if multi-language support was not installed (leaving only default). So accessing it at a multi-language URL should return a 404. At that point the page would only be available at the default URL and default language, whatever that happens to be. 

If I understand correctly, you are wanting the page to keep working at multi-language URLs, even when multi-language is turned off? So multi-language is disabled on the back-end (fields), but can still render at multi-language URLs on the front-end? There would be a couple of problems there. PW wouldn't know what language it's in, and as a result wouldn't know when it's allowed to be included in find() results (lists of pages). At present, when multi-language is disabled, PW knows the page can be included in default language search results, but excludes it from non-default. Secondly would be duplicate content, since the page would keep rendering at multi-language URLs, despite only being available in one language. Though let me know if I've misunderstood. I may be able to suggest an alternative strategy to accomplish what you are trying to do, though not 100% positive I understand the full scope of your need.

**Comment by philippdaun** [comment]
I do agree that root parent pages should result in a 404 if they have multi-language disabled and are accessed through a multi-language URL. After all, there is no content for that language.

For the specific use case I'm addressing, however, I would have expected different behaviour: if the root parent has multi-language enabled, but a child page has it disabled, there should be a way to display the single-language child without forcing the guest user back into the default language. That way, there is no mixing of single-language and multi-language URLs across the site.

The main advantage of what I'm trying to do (as you guessed) relates to the page editor in the admin. Since the single-language news items are separated into different-language trees (there's no 1:1 translation for news content, but a tree for each language with single-language news items beneath), it would be confusing for content editors to have language tabs displayed above the fields. Duplicating all fields to have a single-language next to a multi-language field seems to over-complicate things a bit.

I could of course also make the parent single-language, but then there's no way for the site to declare a content language via `<html lang="xx">` — keeping the parent multi-language has a few of those advantages. 

Maybe there's a simpler way to accomplish this? If you could point me in another direction, I'd be happy to explore.

**Comment by juruus** [comment]
I actually also thought that this would be the use case for template that has multi-language disabled. 

Let's say i have ads in two languages, but none of them are actually translated. I have 2000 ad-item pages in default language and 40 in secondary language. And inside ad-item template i have a custom field lang_code that knows the language of the ad-item page. 

Now i can search for the ads with $pages->find("template=ad-item, lang_code=$user->language") and get the results in /default/ad-list/ and /secondary/ad-list/ for user's language (or user's chosen languages = filtering). And i can access the default language ad pages with /default/ad-list/ad-url but not the secondary language /secondary/ad-list/ad-url. 

This would be very useful for ajax-driven site. And very very useful for ajax-driven site that uses app shell approach and only loads the application frame once and relies on processwire urls for it's content. 

So any ideas on how to get around of this restriction, would be appreciated.

**Comment by philippdaun** [comment]
I ended up maintaining a fork of `LanguageSupportPageNames.module` in my `/site/` folder. Since ProcessWire lets you choose a preferred file if it finds a module twice, this has worked so far. Not an ideal solution, but there was no other way to implement the intended behaviour.

@ryancramerdesign Can you think of a more appropriate solution for that use case? Meaning, multi-language site with children that are not translated 1:1, but rather each child page has content in a specific language and can only be entered in that single language.

**Comment by juruus** [comment]
At least that's a maintainable and updateable solution. Thanks for that.

**Comment by netcarver** [comment]
@ryancramerdesign @juruus @philippdaun Can this issue be closed soon? Is there more to discuss here?

**Comment by philippdaun** [comment]
Unless there are plans to support such a scenario in ProcessWire, we're all done here ٩(◕‿◕｡)۶

**Comment by ryancramerdesign** [comment]
@philippdaun You mentioned that you are maintaining a fork of the LanguageSupportPageNames.module, that sounds like a good solution. But I'm curious what you changed to get the behavior you were after here? Reading the above, I think I understand, but admittedly still a little confused by specifics of it, and maybe if I knew what changes were necessary it might be more clear. Thanks.

**Comment by philippdaun** [comment]
@ryancramerdesign The only change I made is the one line detailed in the issue description above. It disables the language-status check for pages that have the `noLang` flag set, allowing scenarios where child pages are single-language, but must be accessible through a language URL (`/fr/`) since the parent is multi-language. Right now, this is not allowed: setting `noLang` on a template disables the language prefix completely.

While I found it to be a non-hacky solution making use of defined ProcessWire behaviour, I can't say with any confidence it won't break existing code or defy other users' expectations. Luckily, ProcessWire makes forking core modules really easy. And I've only had this requirement come up once in 20+ multi-language projects. It's likely too much of an edge case.

**Comment by ryancramerdesign** [comment]
@philippdaun Thanks for reporting back. I've put a note in the file with a link back to this thread so that if the need arises again we can maybe come up with a configurable solution. One potential problem with supporting this is just having the same content delivered at multiple URLs, which is usually something to be avoided (search engine penalties), and something ProcessWire is largely designed to prevent. When identical content is appearing at more than one URL, it requires the developer to do more work and maintain canonical link tags in their document head markup to point to the primary URL. So on your site that is using this solution, you may want to double check that you are doing that, just to play it safe.

**Comment by daun** [comment]
@ryancramerdesign Sounds good! And you're right, the site in question did need a bit more work to get the canonical links and XML sitemaps working. This is probably a good sign one is working against the framework if the "solution" makes things harder than usual.
