### ISSUE TITLE
How To "RTL" AdminTheme Core Files?

### ISSUE THREAD

**Issue by Mu9tafa-Online** [processwire/processwire-issues#464]
I'm Developing an **"RTL"** Language Website & I Use "**AdminThemeUiKit**" Which i can RTL Easily, 
The Problem is With jQuery-Ui CSS Files + Other Core Modules (Each Module Has It's Own CSS Files),

What is The Best Way To Accomplish What I Want ?? Please Help :(

**Comment by ryancramerdesign** [comment]
I'm not sure I fully understand the question. Can you explain in more detail what the issue is with the CSS files? If there is something in those CSS files you want to override, that is possible to do. You would just need to append your own CSS file to the admin theme output. One way to do this would be at the top of the /site/templates/admin.php file: 
~~~~~~
<?php namespace ProcessWire;
$link = "<link rel='stylesheet' type='text/css/ ' href='/path/to/your/file.css'>";
$adminTheme->addExtraMarkup('head', $link); 
~~~~~~

**Comment by Mu9tafa-Online** [comment]
Yes I Know How To Add "CSS" File To Admin .. But "AdminThemeUiKit" Depends On Core CSS Files, I Dont Know Where To Start :( Do I Need To Override CSS File By File ??  
.
For Example: What I need to do To **RTL** "**Pages Tree**" ?
