### ISSUE TITLE
processInput() throws PHP Warning if upload field has destinationPath property set

### ISSUE THREAD

**Issue by processwired** [processwire/processwire-issues#476]
### Short description of the issue
I'm currently writing a Process module which should upload a file to a custom path (essentially I would like to make sure that the file never touches the according `/site/assets/files/1198/` directory in order to avoid the public access to the file in any circumstances). I created a form with an upload field `$f`. The upload field has the property `$f->destinationPath` set. If I submit the form and process the submitted form server side, the method `processInput()` is used like this: `$form->processInput($this->input->post);` That's the moment when PHP throws a warning:
`PHP Warning: filemtime(): stat failed for /site/assets/files/1198/file.zip in /wire/core/Pagefile.php:444`

Note: „1198“ is the page id of my custom admin page here. It could be any other page id in your case. 

### Steps to reproduce the issue
Concrete example: the warning is thrown with the „ProcessPagesExportImport.module“ (in core) too. Just try to import an zip file with something other than json inside and you will get the same warning. I guess processInput() expects the file in `/site/assets/files/1198/` and doesn't follow `$f->destinationPath` properly.

### Setup/Environment
* ProcessWire version: 3.0.88

**Comment by processwired** [comment]
I think the issue creeps in at line 537 of Pagefile.php:
```
/**
* Hookable version of filename() method
*
*/
protected function ___filename() {
	return $this->pagefiles->path . $this->basename;
}
```
This sets the path in disregard of the file field's `destinationPath` property. Luckily, this method is hookable, so there can be a workaround:
```
$this->addHookAfter('Pagefile::filename', function (HookEvent $event) {
    $path_parts    = pathinfo($event->return);
    $event->return = $this->config->paths->assets . 'my/custom/path/' . $path_parts['basename'];
});
```
ProcessWire's flexibility is great! :)
I think that issue should be considered to be better fixed in core, though.

**Comment by ryancramerdesign** [comment]
The Pagefile (and Pagefiles) classes are meant only to handle files connected with a Page (in /site/assets/files/id/). The InputfieldFile module is built to work with Pagefiles only. However, it can also be used for uploads if you set the destinationPath yourself, *do not* specify the value attribute, and *do* specify what extensions are allowed. Meaning you would have to use it purely as an upload field, without an existing value. Once you've got an existing value, that's a Pagefiles value, which is connected to a Page and files that can only live in /site/assets/files/id/. Is it possible this is why you are seeing the warning, because you are populating the InputfieldFile's "value" attribute with something? Or maybe the allowed file extensions aren't specified? I didn't see the warning in testing with other ZIP files in ProcessPagesExportImport, and also tried to duplicate with ProcessDatabaseBackups, but no luck.

**Comment by tbba** [comment]
Just to mention it, during the PW update on existing sites I got some of those exceptions:
_Exception: Field xxxxxx is not saveable because it is in a specific context_ 
I thought that the errors were a bit misleading because a simple refresh of the page cured the problem, no errors after that refresh. 
(Probably the server was too busy with redrawing all the images at the same time)

**Comment by processwired** [comment]
Dear Ryan, thanks for taking care. I tried again with a clean install of PW 3.0.92 and the ProcessPagesExportImport module installed. In addition, I installed the (superb!) TracyDebugger. I took a small screen record what's happening if I try to upload a zip file with _no_ valid json inside - Tracy shows the filemtime() warning then.

May I ask you to try again with Tracy enabled? It works best with "Force superusers into DEVELOPMENT mode" setting activated.

![upload](https://user-images.githubusercontent.com/8448399/36424284-119e4054-1643-11e8-9273-eaf4069eb31a.gif)

**Comment by KeeneState** [comment]
@tbba, I'm seeing the same errors on core update, but I don't believe it is related to the parent issue. I get one fatal error per field, and as you mention, it self-heals. I diff'ed the database before and after, and it seems like a sort of schema turbulence. Post-error, my file-based fields have a new column: `filedata` mediumtext DEFAULT NULL.

**Comment by zeb600** [comment]
@tbba @KeeneState i'm getting the same errors upgrading a page from 0.75 to 0.93. Seems to "self heal" after a refresh as well and in my case only seems to occur on image fields (some of these images are pretty large intially). Only tried it on a test server so far - feeling a bit skittish about putting it on the live site. Did you guys experience any problems after the inital errors?

**Comment by KeeneState** [comment]
@zeb600 We've not rolled to production, I saw the errors in a dev environment only. I spent a while trying to track the errors to source--it's a slippery one. Near as I can tell it's related to an image (filetype) field in a repeater, with some connection to field permissions. Does that sound familiar? 

I was considering opening a new github issue, but I'm afraid that I don't have a hard case. That is, I can't recreate it on fresh 3.0.62 instance of Processwire, upgrading to 3.0.93 dev, with various repeater/image/permissions configurations.

**Comment by zeb600** [comment]
@KeeneState To be honest I didn't really dig in (yet). What i'm curious about is the self-healing aspect, that's a bit unusual and also makes debugging difficult. All I can say right now is that it's happening on image filetype fields, *not* necessarily in a repeater, and the images in question are large-ish (about 2500x1000 initially). Also there's nothing fancy going on wrt field permissions.

**Comment by tbba** [comment]
@zeb600 I had no problems with it since. The identified pages hold a list of image fields (thumbnails) and file fields (PDF files) - and work.

**Comment by KeeneState** [comment]
@zeb600 @tbba I've created a new issue, if you're interested. #512

**Comment by zeb600** [comment]
thanks!

**Comment by netcarver** [comment]
@processwired Does the fix that Ryan pushed in #512 solve your initial issue? If so, can this issue be closed now?

**Comment by netcarver** [comment]
Closing as this seems to have gone cold. Please post more data if you have it. Many thanks.

**Comment by BernhardBaumrock** [comment]
@netcarver could you please reopen this issue? It still exists:

* create a clean pw install with tracy + processdatabasebackups
* go to setup > db backups > upload
* upload any sql or zip file

See the error:
![img](https://i.imgur.com/pIi0RBn.png)

https://github.com/processwire/processwire/blob/master/wire/core/Pagefile.php#L524
This line fails because $this->filename() points to /site/assets/files/###/ and not to the set destinationpath. A simple is_file check could prevent this warning from showing up and I guess it should be ok to return NULL in that case without any warning (as the field is used upload-only and no-value as @ryancramerdesign mentioned above).

**Comment by matjazpotocnik** [comment]
@BernhardBaumrock I can't replicate this. I successfully uploaded a SQL file. Could you confirm it's fixed?

**Comment by BernhardBaumrock** [comment]
I can't confirm that but I'm happy if you close that issue until it pops up again and I can investigate.

**Comment by netcarver** [comment]
Ok, closing. Just post again if you need it re-opening.
