### ISSUE TITLE
Special characters not allowed in emailadress

### ISSUE THREAD

**Issue by kalmarlansmuseum** [processwire/processwire-issues#477]
### Short description of the issue
Special characters are not allowed in FieldtypeEmail. They should be according to this: https://stackoverflow.com/questions/8527180/can-there-be-an-apostrophe-in-an-email-address

### Expected behavior
Email should be validated.

### Actual behavior
Email is not validated.

### Steps to reproduce the issue
1. Type in a valid email adress in an FieldtypeEmail 
2. Submit
3. Email not validated

* ProcessWire version: 3.0.62

**Comment by teppokoivula** [comment]
Just tested this, but couldn't reproduce the issue: email with an apostrophe is saved as expected, at least. Could you provide an example of an email address that doesn't work as expected?

Note also this possibly related issue: https://github.com/ryancramerdesign/ProcessWire/issues/1862. Since ProcessWire uses PHP's built-in features for validating email addresses, this could depend on local environment too.

**Comment by kalmarlansmuseum** [comment]
You're right i got things mixed up. Seems like the $sanitizer->email() removes special characters and wireMail fails to send an email with special characters.
