### ISSUE TITLE
Upgrade HTML Purifier

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#483]
HTML Purifier 4.9.3 is a bugfix release, which works around an infinite loop in PHP 7.1 that occurs when the opcode cache is enabled.

Be aware that looking at some of the commits after 4.9.3 was released, they have removed support for PHP 5.3. Personally though I'd like to see PW's min PHP version upped to 5.4, so maybe it is OK to upgrade HTMLPurifier to 4.9.4 when it is released. Of other note in the recent commits is some PHP 7.2 fixes, which I think we also want in PW.

Thanks!

**Comment by teppokoivula** [comment]
A bit OT, but regarding PHP 5.3: it has been [unsupported](http://php.net/eol.php) for a few years now, and now that Ubuntu 12.04 LTS – the last major distro I knew of which still included PHP 5.3 – is also EOL'd, I don't think that there are (m)any sensible reasons to stick with it.

I'd suggest officially moving the minimum version to PHP 5.5, partly because no one should be using 5.3 anymore. If ProcessWire requiring 5.5 is the push they need, all the better :)

For the record: 5.5 is also officially unsupported, but major distros (such as Ubuntu) are backporting security fixes to it. It's the default PHP version for Ubuntu 14.04 LTS, which is going to be supported until April 2019.

**Comment by matjazpotocnik** [comment]
Also OT, but we should upgrade jquery too. See https://processwire.com/talk/topic/17806-old-jquery/

**Comment by ryancramerdesign** [comment]
Thanks, I have upgraded the htmlpurifier version to 4.9.3. I am fine with removing support for PHP 5.3, and I don't think anyone is using it at this stage. Though don't see any reason state it until there is actually some code present in the core that doesn't work with 5.3. If the next htmlpurifier update requires PHP 5.4 or 5.5 then I think it's fine for us to state the same with the core. Probably won't upgrade jQuery used by the admin until after the next master version because jQuery upgrades tend to break various things here and there (and often not immediately obvious), and we're at a good stable spot with the front-end JS at present.

**Comment by adrianbj** [comment]
@ryancramerdesign - it doesn't look like all the changes from 4.9.2 to 4.9.3 were applied.

For example:

https://github.com/ezyang/htmlpurifier/commit/cb4871f4464659918e0c59b914d359a8874ea62a

-        $current_li = false;
+        $current_li = new stdClass();

doesn't appear to have made it to:
https://github.com/processwire/processwire/blob/dev/wire/modules/Markup/MarkupHTMLPurifier/htmlpurifier/HTMLPurifier.standalone.php#L14727

Not sure if there are others or not, but that one stood out.

**Comment by adrianbj** [comment]
Sorry to bump this @ryancramerdesign but I am hesitant to close without knowing whether you saw my last comment or not. Maybe you intentionally didn't include that change, but I have no idea.

**Comment by adrianbj** [comment]
Thanks for the followup!
