### ISSUE TITLE
Different url-segment handling depending on the setting of $config->pageNameCharset

### ISSUE THREAD

**Issue by weberhofer** [processwire/processwire-issues#488]
Processwire Version: 3.0.89

### Short description of the issue

 issue arises resulting of a problem in WireInput->setUrlSegment. My setup allows a URL Segment "logIn" (uppercase "i") which works nicely as long as I don't set pageNameCharset to UTF8.

Switching to UTF8 makes processwire send me an redirect from .../logIn to .../login which is not defined as an allowed segment.

### Optional: Suggestion for a possible fix

Processwire Version: 3.0.89

A issue arises resulting of a problem in WireInput->setUrlSegment. My setup allows a URL Segment "logIn" (uppercase "i") which works nicely as long as I don't set pageNameCharset.

WireInput (around line 295) uses **Sanitizer->name()** to clean up the segment's name. As soon as I set $config->pageNameCharset='UTF8', Sanitizer->pageNameUTF8() is called.
As there are no "special" characters in the given segment, it hands over to **Sanitizer->pageName()** on line 473.
So different methods are used for cleaning up the string: In the regular case Sanitizer->name(), in the UTF8 case it's Sanitizer->pageName(). 

The results of the two functions differ: In my case the "logIn" is translated to "login" and the client is redirected to this page. As the "login" segment doesn't exist the redirect results into an error page.

I see the following possibilities:
- Let Sanitizer->pageNameUTF8() call $this->name() on line 473. Let Sanitizer->name() respect the $config->pageNameCharset correctly.
- remove the conversion to lower case at the end of Sanitizer->pageName()
- add another parameter to sanitizer->pageName() which allows the invoking method to decide if a lowercase conversion should be done.
- Create a single point for doing the filtering of (UTF8) characters and access this from different methods.

I don't understand why there are different functions name() and pageName() - shouldn't they do the same?
I have also seen some "punycode" handling in there: punycode is only relevant for hostnames - so why is there a punycode handling in the pageName() sanitizer?

I could submit patches but I'd like to know which way do go before I implement something, so please get in contact with me.

**Comment by Lazerproof** [comment]
I'm not sure, but it looks like URL Segments is intended to use be used in lowercase as they are sanitized by default as page names and page names by default support lowercase ASCII letters and not uppercase.

**Comment by weberhofer** [comment]
URL Segments can also be mixed case. But the behaviour changes when $config->pageNameCharset is set to UTF8. IMHO this behaviour should not change.

**Comment by Toutouwai** [comment]
> URL Segments can also be mixed case.

Seems like they can be, but I'm surprised about this because the API [documentation](https://processwire.com/api/ref/input/url-segment/) for URL Segments says that they are sanitized as page names and $sanitizer->pageName() does not allow uppercase characters.

Looking at the [WireInput.php](https://github.com/processwire/processwire/blob/cf292363ca51433e51c37da448feccca3ea83b33/wire/core/WireInput.php#L292-L298), URL Segments are sanitized with $sanitizer->pageNameUTF8() if $config->pageNameCharset is UTF8, and sanitized with $sanitizer->name() if it isn't. @ryancramerdesign, should that be changed to $sanitizer->pageName()? Or will you correct the documentation to state that URL Segments are sanitized as names and not page names?

**Comment by weberhofer** [comment]
I think changing that behaviour for the default case will break several PW instances. I'm using the segments for offering downloads of files which can be mixed case, too.

**Comment by ryancramerdesign** [comment]
URL segments can have U&LC, and I've pushed an update that should correct this. Thanks.

> I don't understand why there are different functions name() and pageName() - shouldn't they do the same?

They are not the same. Leaving out UTF-8, ProcessWire has 3 different standard name formats, which are: name, pageName and fieldName. Each has a different purpose, and the "name" one is the most general purpose. 

> punycode is only relevant for hostnames - so why is there a punycode handling in the pageName() sanitizer?

Punycode is a type of bootstring algorithm that is handy for conversion between ascii and UTF-8. Use cases are not limited to hostnames (IDNs), though that's their most common one. Punycode is useful in our case because it is consistent with PW's pageName format, which enables us to support UTF-8 in page names while remaining compatible with PW's pageName format.

**Comment by weberhofer** [comment]
Thank you! Changing to UTF8 now works without breaking anything!
