### ISSUE TITLE
ProcessPageEditLink - accept spaces in external rel to allow for rel="nofollow noopener"

### ISSUE THREAD

**Issue by tbba** [processwire/processwire-issues#490]
PW3 - latest beta

See the admin settings here:
/admin/module/edit?name=ProcessPageEditLink

Right now it is not possible to set the standard rel content for an external link to 
rel="nofollow noopener", for example. (Security fix for vulnerability for target=”_blank” tag)

Behavior of the settings field casing problems with multiple elements:
_nofollow noopener_ gets replaced by _nofollow_noopener_ (with underline instead of a space)

**Comment by ryancramerdesign** [comment]
Thanks, I've pushed a fix for this issue.

**Comment by tbba** [comment]
Thank you for the fix, 

just thinking loud now:

My test setup is: 
<img width="1185" alt="bildschirmfoto 41" src="https://user-images.githubusercontent.com/652879/35995770-ac82b466-0d14-11e8-853f-a6c07826a3cf.png">

The 3 steps grouped hierarchy was needed because they are not selectable as checkboxes but as a selection menu:

_noopener nofollow noreferrer
noopener nofollow
noopener_

which then works like this:

<img width="983" alt="bildschirmfoto 42" src="https://user-images.githubusercontent.com/652879/35995922-29fafcc8-0d15-11e8-87a6-85c862cb3aa8.png">

OK, the the link now works 100% as intended.

--------------------

Alternatively there could be single entities instead of groups 

_noopener
 nofollow
noreferrer_

and checkboxes at the other end to select them. 

--------------------

Either way it would be helpful if the field comments/instructions in the backend reflected the changes (how to treat multiple values best):

**either (excuse my English):**
" the value must be one row you have predefined above."
**or if you are going the other direction with the checkboxes:**
If you add more entities, divide them by a space. Examples: Specifying "nofollow" would make external links default to be not followed by search engines. For a target "_blank" link a rel="noopener" is recommended for security, so you in this case could set "nofollow noopener" to additionally protect that link.

**Comment by tbba** [comment]
@ryancramerdesign just a "bump" that your solution works but is not ready for primetime yet, i.m.h.o.

**Comment by tbba** [comment]
just another "bump"

**Comment by netcarver** [comment]
@ryancramerdesign Just trying to bring this back on your radar.

**Comment by netcarver** [comment]
@ryancramerdesign Can this be considered here, or do you want it to be moved to the requests repo for consideration there? If no action is likely in either repo, I'd prefer to close it here.

**Comment by ryancramerdesign** [comment]
@netcarver @tbba I know checkboxes would be preferable here, but I don't see a way to switch these to use checkboxes in a way that would be backwards compatible. It's going from single select to multi-select. The current setup enables one to achieve the same end result, and accurately configure the default for external links too. This particular issue report had to do with allowing spaces for this rel attribute, which it now does. Since we fixed the outlined issue I think it's okay to close it. Changing it to checkboxes would be a more major change (or rewrite of it), which would also have to accommodate past selections in a different format. I don't think it's practical to make that change right now, but I agree with the request for checkboxes so it's fine for it to go in as a feature request.

**Comment by netcarver** [comment]
Ok, thanks @ryancramerdesign. @tbba Carl, we can continue the conversation in the requests repo.
