### ISSUE TITLE
Impossible to match by sort in selector

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#496]
### Short description of the issue

When trying to match the sort property of pages in a selector the wrong result is returned, perhaps because "sort" is interpreted as always meaning "order by" instead of meaning the actual sort property of pages.

The examples below illustrate the problem:
![2018-02-14_175505](https://user-images.githubusercontent.com/1538852/36188325-495f937c-11b0-11e8-8d29-8fff084f5b45.png)

### Suggestion for a possible fix

My guess is that the problem is due to the same word "sort" being used both as an "order by" keyword in selectors and as the name of a page property (likewise a column in the pages table of the database). Probably not possible to change the name of either of these now, but maybe some new syntax could be added to indicate when you want to match against the sort property in a selector.

### Setup/Environment

* ProcessWire version: 3.0.90

**Comment by ryancramerdesign** [comment]
The "sort" in a selector is a reserved word that refers to the column you want to sort the results by. It is not meant to be a selectable element, and wouldn't be worthwhile as one because there are no guarantees about sort values other than that they will be in order, if the parent is configured to sort children manually. There may be gaps in the sort values too, which is why you wouldn't want to query pages (or anything else in PW) by a the "sort" column, as it should only be used for sorting. 

I think what you might be looking for is an index rather than a sort. If your value is a WireArray or PageArray, the index(), eq() or slice() methods might be what you want. If you are using a selector with a $pages method or similar, you'd want to make use of the "start=n, limit=1" selector to get by an index.

**Comment by Toutouwai** [comment]
> It is not meant to be a selectable element, and wouldn't be worthwhile as one...

It's a bit of a guessing game saying will and wont be worthwhile for all developers in all situations. "Sort" is meaningful page data, it's a column in the database and it's less than ideal to have page data that cannot be queried directly by PW's selectors. 

The example of getting a page by it's sort value using an = operator was just to demonstrate the issue. A more likely scenario involves using < or > operators. Suppose you have a page $p with a large number of siblings where the sort order of those siblings has some significance. You want to match only pages that occur after $p in the sort order. So you might want to use a selector like this:

```php
$items = $pages->find("parent={$p->parent}, foo=bar, sort>{$p->sort}");
```

You say it's not a bug, but the fact that it's not possible to use a selector like this seems like an unintended side-effect of using the same word for two different meanings (i.e. the issue would have been avoided if either the database column or the reserved word had been "order" for example instead of "sort"). Of course we can't wind back the clock on that now, but if it's possible to add some way of indicating when "sort" is intended as the page property inside a selector then it would be good to add support for that, to keep PW selectors as flexible as possible. It would be desirable just on general principle alone, but besides that I believe there can be real-world applications as per the example above.

**Comment by netcarver** [comment]
How about allowing a special mapping of "_sort" for this case?

**Comment by teppokoivula** [comment]
Is this the first implementation of underscore-prefixed values in selectors? If so, I'd rather prefer we avoid it, as it's likely going to be a one-off case you just have to know to be able to use – not very good in terms of API design.

How about something like `page.sort`? A bit more verbose, but in my opinion more readable / consistent too.

**Comment by netcarver** [comment]
@ryancramerdesign Bumping this for your consideration.

**Comment by ryancramerdesign** [comment]
I've added support for `page.sort` per @teppokoivula suggestion above, though `_sort` might actually be more consistent with our special cases since we already use underscore like in `_custom`. But I agree that `page.sort` feels more consistent, whether it is or not. Also, I noticed that just using just `sort` already provided the behavior requested here when using any operator other than `=` . So you could already do something like `sort>3`, but the problem was the results may have been correct in matching the selector, but were also completely unsorted. So they now appear in the correct order now too when having the same parent.

**Comment by Toutouwai** [comment]
Working great here, thanks.
