### ISSUE TITLE
Logic Errors with Null Coalescing

### ISSUE THREAD

**Issue by ddwwcruz** [processwire/processwire-issues#501]
### Short description of the issue

Using the code below, `$pageImage` is always the value of `$substituteImage` even if `$page->page_image->url` does have a value

```php
$pageImage = $page->page_image->url ?? $substituteImage;
```

### Expected behavior

`$pageImage` should only be `$substituteImage` if `$page->page_image->url` has no set value

### Actual behavior

`$pageImage` is always set to `$substituteImage`

### Steps to reproduce the issue

1. Use Null coalescing on processwire values

### Setup/Environment

* ProcessWire version:
* (Optional) PHP version: 7.2.2
* (Optional) MySQL version: 
* (Optional) Any 3rd party modules that are installed and could be related to the issue:

**Comment by ryancramerdesign** [comment]
I personally never use it so I might be wrong, but I don't think you can use null coalescing here. The page_image would not be an object if there's no image (and it's configured that way), so accessing a url method off of it isn't going to work unless null coalescing suppresses access of non-object method/property errors and considers it the same as null. Even if it does do that, accessing methods/properties off of non objects isn't a good practice, so you'd want to check $page->page_image first, unless you've configured the field to have an automatic fallback to another image. Also note that url is not a property that can be set or unset, it is a method. It can be accessed as a property for convenience, but because it is a method and behaves as one, it's very likely not something that can be used with null coalescing either way. I recommend this instead:
~~~~~~
if($page->page_image) {
  $url = $page->page_image->url();
} else {
  $url = 'sub image URL';
}

// or shorter if preferred
$url = $page->page_image ? $page->page_image->url() : 'sub image URL';
~~~~~~
Image fields already include the ability to automatically substitute another image (see image field settings), so that would be an even simpler solution.

**Comment by netcarver** [comment]
@ddwwcruz Hi Wayne, did Ryan's suggestion above allow you to solve the issue? If so, please could you close this. If not, could you let us know. Thank you!

**Comment by netcarver** [comment]
@ddwwcruz Closing this as there has been no reply. Please post more if needed. Thank you.
