### ISSUE TITLE
Can't add field to fieldset when adding to template from field's "Actions" tab

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#510]
### Short description of the issue

If you use the Actions tab to add a field to a template, when you need to choose what field it goes after on the next screen, there is no option to add it after a fieldsetopen or before the _END version.

### Expected behavior

I should be able to add the field somwhere inside the fieldset.

### Actual behavior

The fieldset open/end options are not available from the dropdown.

* ProcessWire version: 3.0.94

**Comment by ryancramerdesign** [comment]
That option was [intentionally left out](https://github.com/processwire/processwire/blob/master/wire/modules/Process/ProcessField/ProcessField.module#L1909) because I thought it would be confusing here. This dropdown is for adding fields before or after another field, and if a Fieldset is there, then it adds a layer of confusion about whether before/after refer to within the fieldset or outside of it. I decided it was best to leave those kinds of edits to dedicated editor in ProcessTemplate.

**Comment by adrianbj** [comment]
It's only really an issue if the fieldset doesn't already have any fields inside it, but no worries I guess.
