### ISSUE TITLE
AdminTheme Selection Issue!

### ISSUE THREAD

**Issue by Mu9tafa-Online** [processwire/processwire-issues#523]
I remove all admin themes from core but not "UiKit" - and when creating a new user and selecting "Uikit" as his/her default theme and log-in everything seems broken :( 

**Expected Behavior** : Uikit should be the default admin theme after login

**Current Behavior**: no matter the selected theme, "DefaultAdminTheme" is enabled for non-superadmin users.

![pw_user](https://user-images.githubusercontent.com/5323832/37238862-51eecc5c-2438-11e8-95aa-a3a2057cec7f.png)

![pw-default](https://user-images.githubusercontent.com/5323832/37238870-610c65aa-2438-11e8-9282-541fdb87bca7.png)

**Running System:**
**PW**: 3.0.93
**PHP**: 5.6 (Optional)

**Comment by horst-n** [comment]
seems to be the same issue:
https://github.com/processwire/processwire-issues/issues/514

**Comment by gmclelland** [comment]
I think I have seen this happen when the starting default theme was something other than Uikit.  I think I fixed it by adding $config->defaultAdminTheme = 'AdminThemeUikit' in /site/config.php.  After that change, I could switch themes on the user's profile.

The newer versions of Processwire sets the Uikit as the default theme on installation.  Older versions that are upgraded would have a different admin theme installed by default.  Maybe that is why Ryan didn't see a problem?  Maybe he was testing on a newer installation?

**Comment by ryancramerdesign** [comment]
The value of `$config->defaultAdminTheme` is AdminThemeDefault on existing installations, and AdminThemeUikit on new installations. If you uninstall the admin theme that setting is pointing to, then you'll need to update that setting to point to whatever you want the new default admin theme to be. I've pushed an update so that it forces you to do this before uninstalling an admin theme that is default as the defaultAdminTheme.

**Comment by Mu9tafa-Online** [comment]
Yeah That's Fixed My Issue ,, Many Thanx :) @ryancramerdesign / @gmclelland
