### ISSUE TITLE
RepeaterMatrix Fieldset Indentation Issue

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-issues#529]
When editing a repeatermatrix field, with a matrix-type that has a fieldset field, the fields contained within the fieldset don't properly indent.  However "touching" the field will make it indent.

Video:
http://www.youtube.com/watch?v=SoHNz9qoxS8

PW Latest as of 3/13/2018, Chrome latest, Windows 10

**Comment by ryancramerdesign** [comment]
That indenting is a feature of ProcessTemplate, and we don't support that anywhere else. Though that's interesting and unexpected that touching it made it indent. Maybe supporting it will be a little simpler than I'd previously though. But I hadn't really intended to support it in repeaters since fieldsets aren't very common in them. I will definitely take a closer look a little later, after the next master version.

**Comment by Toutouwai** [comment]
Ryan has provided the change that is needed in a forum post: https://processwire.com/talk/topic/20317-minor-issues-fieldsets-not-handled-as-per-fieldtyperepeater/?do=findComment&comment=176184

> Edit the config.php file in your FieldtypeRepeaterMatrix directory and around line 283 you'll see this:
> $select->setAsmSelectOption('sortable', true);
> Add this line right after it to enable the fieldset feature in AsmSelect:
> $select->setAsmSelectOption('fieldset', true);

**Comment by netcarver** [comment]
Looks like this is fixed in the development version. Closing here. @jlahijani please post more here if needed. Thank you.
