### ISSUE TITLE
Repeater within RepeaterMatrix Whitespace issue

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-issues#530]
Video:
https://www.youtube.com/watch?v=6B9fD25P0iQ

PW Latest as of 3/13/2018, Chrome latest, Windows 10

Actually, it seems all Repeater fields in general have the gray-ish background as opposed to white.  Shouldn't it be white to be consistent with other fields?

**Comment by ryancramerdesign** [comment]
Fields with lists of items in them (like files, images, repeaters, etc.) default to a slightly grey background rather than white, so this is normal. Usually it's desirable, but there are certain cases where it might look better to alternate it (like nested repeaters or the like). The CSS just got a little more complex than it was worth to do this, so I have been giving preference to maintainability in the short term. Longer term we'll optimize and tweak more and more details like this. For now want to leave this as-is, but I agree there's room for improvement.
