### ISSUE TITLE
Unable to switch to Admin UiKIT on latest dev

### ISSUE THREAD

**Issue by jacmaes** [processwire/processwire-issues#537]
### Short description of the issue

After upgrading from 3.0.84 to 3.0.95, I can't switch to the new Admin UiKIT: when I select it in my profile, the save button has no effect and stays in active state (view screenshot). There are no JS errors in the console on Firefox. Logging out and logging back in again, restarting the browser, clearing the cache: no effect. My adblocker is disabled, and so is Firefox's tracking protection. 

### Expected behavior

I should be able to switch to the new Admin theme. 

### Actual behavior

I'm forced to abandon the page. My changes are not saved. 

### Optional: Screenshots/Links that demonstrate the issue

![uikit](https://user-images.githubusercontent.com/1206842/37463672-46615554-2856-11e8-807a-e6be85327671.png)

### Setup/Environment

* ProcessWire version: 3.095
* (Optional) PHP version: 7 
* (Optional) Any 3rd party modules that are installed and could be related to the issue: Soma's HiddenAdminPages module: https://gist.github.com/somatonic/5595081

**Comment by ryancramerdesign** [comment]
I can't duplicate the issue here, but testing in Firefox I did run into a different issue, which I'm thinking is possibly related. For whatever reason, Firefox ignores the autocomplete setting on password fields, so it attempts to populate the password field (if one is stored in Firefox) either way. That means you've got a partially complete password change occurring, when using Firefox. In my case, it meant that it told me "you have unsaved changes" whenever I tried to navigate way from the user profile editor. But maybe in your case, there is an error message in the password field, which is collapsed. I made a small update to our InputfieldPassword.js file, which corrected it for me. Can you check if it also corrects it for you?

Also, your screenshot looks like you are in ProcessUser rather than ProcessProfile (there are no dropdown button actions in ProcessProfile). It should work in either of course, but if you find it's working in one and not the other, please let me know too.

**Comment by jacmaes** [comment]
The fix works, thanks! Closing the issue.

**Comment by adrianbj** [comment]
Hey @ryancramerdesign - unfortunately this change broke my EmailNewUser module. I think I have a fix though. Would you consider replacing:

```
if($(this).val().length < 1) return;
```

with:

```
if($(this).val().length < 1 || $(this).attr('value').length > 0) return;
```

This checks the actual value attribute to see if the password is already populated (which is what my module does when creating a new user). This way the `InputfieldStateChanged` class won't be removed and my module will work and user pages will still be updatable. 

More details here: https://processwire.com/talk/topic/7051-email-new-user/?do=findComment&comment=165951

You might also be interested in reading a few posts above as well.

Thanks for considering this change, or some other approach to allow my module to continue to work.
