### ISSUE TITLE
View-only user has no way to logout or edit profile with AdminThemeUikit 

### ISSUE THREAD

**Issue by theo222** [processwire/processwire-issues#539]
### Short description of the issue

User with page-view only role (no page-edit) has no access to logout and profile settings.
Maybe a CSS issue.

### Expected behavior

Same as with default theme

### Optional: Screenshots/Links that demonstrate the issue

https://processwire.com/talk/topic/18720-how-can-a-preview-user-log-out/

* ProcessWire version: PW 3.0.95

Thank you.

**Comment by ryancramerdesign** [comment]
Page-edit permission is prerequisite in order to use anything in the admin, but the profile editor is the one thing that it'll let you access if you have profile-edit permission. I would still suggest using your own front-end profile editor, as you don't want non-editor users in the admin at all. But there are cases where it can still be convenient, so I've added an "Edit profile" button to appear after login (if user has profile-edit permission), rather than the existing "Continue" link.

**Comment by theo222** [comment]
Wow, you are fast! :-)
It is great to have the "Edit Profile" button. 
But the default theme had a simple "Logout" link on that page. This was my main point.
Is it possible to get this one back?
Please see Soma's screenshot of the old theme https://processwire.com/talk/topic/18720-how-can-a-preview-user-log-out/
Thank you.

**Comment by ryancramerdesign** [comment]
It sounds like you might be using PW's admin login for something non-admin related, and I don't recommend using the admin login for this purpose. If you don't need to give the user some kind of administrative permission, it's best to keep them out of the admin completely (and also not reveal your admin URL). Instead, use a front-end login form. You can even use ProcessLogin for that purpose if you want to, by executing it from your own code. 

However, I'm going to assume there is some other reason why you want to use the admin login, so if you want to do that, use a hook in /site/templates/admin.php to direct them to the right place after a successful login (which should be somewhere on the front-end of your site, not in the admin): 
~~~~~
$wire->addHookAfter('ProcessLogin::afterLoginURL', function($event) {
  if(!$event->wire('user')->hasPermission('page-edit')) {
    $event->return = $event->wire('pages')->get('/')->url(); // homepage
  }
}); 
~~~~~
If you also want to use PW's admin to handle your logout, then just link to it:
~~~~~~
$url = $config->urls->admin . 'login/logout/';
echo "<a href='$url'>Logout</a>";
~~~~~~
(though it's just as simple to make your own logout on the front-end):
~~~~~~
if($input->get('logout')) {
  $session->logout(); 
} else if($user->isLoggedin()) {
  echo "<a href='./?logout=1'>Logout</a>";
} else {
  echo "Please login";
}
~~~~~~

**Comment by theo222** [comment]
Thank you. I can explain it.
The site is in "Maintenance Mode" using the module "MaintenanceMode".
This module has an option to "allow specific roles to bypass maintenance mode".
For this, I have configured a "previewrole" (page-view only) and a "preview" user.
So the preview user (future owner) can see the site while it is in maintenance mode.

Probably there is a misunderstanding.
I don't need anything new, I just would like to have the options of AdminThemeDefault in AdminThemeUikit.
Please look: Everything is there in "AdminThemeDefault" the  "Continue" Button, the "Logout" link, and 
the Wrench Symbol for the profile settings.
https://processwire.com/talk/uploads/monthly_2018_03/image.png.82798f4ca1fe1fc099c35c3ce9546b67.png

This is what I need in AdminThemeUikit too. 
Nothing new.

Thank you!

**Comment by theo222** [comment]
@ryancramerdesign 

Just to avoid a misunderstanding.
I am talking about this: http://theowp.bplaced.net/upload/uikit-login.png
Everything is actually there, but hidden by CSS "display: none;" rules.
Why? Can we have this in the official "AdminThemeUikit" please?
The screenshots above were taken after changing some rules in 
wire/modules/AdminTheme/AdminThemeUikit/uikit/dist/css/uikit.pw.min.css

Thank you.

**Comment by theo222** [comment]
@ryancramerdesign  
I found out that what I need is possible, it is just very well hidden.
In Modules -> Configure -> AdminThemeUikit under "Masthead and Navigation" change "Masthead logo click action" to "Open offcanvas navigation". Then you will get the option to log out after clicking the PW logo and then your login name. Screeshots here:

https://processwire.com/talk/topic/18720-how-can-a-preview-user-log-out/?tab=comments#comment-163584

Imho, the Logout option should be visible by default.

Thank you.

**Comment by netcarver** [comment]
@theo222 Hello there. Given the recent changes in the core, and in the UIKit theme, can you verify if this is still an open issue?

**Comment by theo222** [comment]
@netcarver  It is still not possible for preview users to log out with the default setup afaics.

**Comment by Toutouwai** [comment]
Looks like this issue is a consequence of forcing the mobile version of the masthead in ProcessLogin at all widths. This seems like a strange thing to do, and also means that at wider-than-mobile viewport widths the user cannot see the button to open the mobile menu (hence they cannot find the logout link).

Couldn't ProcessLogin use the desktop masthead at desktop widths? Is the mobile masthead used just to achieve a centered PW logo? The centered login/forgot-password layout is not ideal IMHO but I've raised that elsewhere: https://github.com/processwire/processwire-requests/issues/180

**Comment by netcarver** [comment]
Sounds like this isn't quite fixed. @theo222 @Toutouwai @ryancramerdesign I'm removing the "fixed" label and adding the "discussion" label.

**Comment by netcarver** [comment]
/remind me to review this issue in 2 weeks

**Comment by ryancramerdesign** [comment]
@netcarver I've been a little confused about this issue because the admin login isn't designed for users without page-edit permission, so didn't want to make ProcessLogin go outside of that, at least in the context of a bug report (would be okay as a requests repo item). But what @Toutouwai mentioned sounds different and a CSS thing, so I went ahead and changed that. I'm not sure if that resolves what was being asked for here, but if not maybe we should move into the requests repo.

**Comment by netcarver** [comment]
@theo222 Can you confirm if the code Ryan just pushed fixes this issue for you? I'll revisit this issue in a couple of weeks to review.

**Comment by theo222** [comment]
Yes, now the view-only user has a possibility to log out to log in again with another user account.
Thank you!

**Comment by netcarver** [comment]
Closing. Please post more if needed.
