### ISSUE TITLE
Field parameters do not save when creating new template

### ISSUE THREAD

**Issue by neosin** [processwire/processwire-issues#540]
### Short description of the issue

Creating new templates and adding new fields with parameters (such as required, tags, etc) does not save the parameters.
So after saving the new template with the new fields you must open each field and again set the parameters.

### Expected behavior

When creating a new template with fields that you have set parameters for, the parameters will save.

### Actual behavior

Creating new templates and adding new fields with parameters (such as required, tags, etc) does not save the parameters.
So after saving the new template with the new fields you must open each field and again set the parameters.

### Steps to reproduce the issue

1. create new template
2. add new field such as text (this opens in a modal window)
3. set input tab > field parameter "required" to true, in advanced tab - assign field to a tag group
4. Save the template
5. Open the template
6. click the new field to edit it
7. you will see it did not save your settings: required = not set, tab group = empty

### Setup/Environment
Windows 8
Xampp latest version

* ProcessWire version: PW 3.0.95
* (Optional) PHP version: 7.1.11 
* (Optional) MySQL version: 10.1.28-MariaDB

**Comment by neosin** [comment]
so it turns out you have to click "save" before you can click "close and add".
perhaps only enable "close and add" after the save button is clicked?
or just have one button that does both actions?

**Comment by adrianbj** [comment]
@neosin - the Close And Add button doesn't appear until the field is created. After that it's up to you to save changes before you close and add to the template. This is because some fields require only one save to set everything up, but others require 2 or more, so there is no way to know so the buttons have the be separate. I suppose the Close & Add could always save, but I like the option to not save changes when adding the field, so I think the current approach has the most flexibility.
