### ISSUE TITLE
Link abstraction turns output formatting on

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#546]
### Short description of the issue

This is a weird issue and was quite difficult to isolate. I can reproduce it on a clean PW 3.0.96 installation by following specific steps but I have no idea what the cause is.

The issue is that _in certain circumstances_ when the Link Abstraction option is activated for a CKEditor field, simply getting the value of that field turns on output formatting for the page, even when it has been turned off in the line above.

The screenshot demo uses Tracy Debugger's console panel, but I expect the issue could be demonstrated using PW's $log also.

![2018-03-21_113742](https://user-images.githubusercontent.com/1538852/37686446-5f593ee6-2cfc-11e8-82ad-c55d1402ae8a.png)

Console code for easy copy/paste:
```php
// Get some items
// The selector must match both the page containing the link and the page being linked to
$items = $pages->find("template=home|basic-page");
foreach($items as $item) {
    // Dump the page title to verify which page we are dealing with
    d($item->title, 'title');
    // Turn off output formatting
    $item->of(false);
    // Dump to verify
    d($item->of(), 'output formatting');
    // Get the value of the field with link abstraction activated
    // Field value must include a link to an internal page matched by the $items selector
    $test = $item->body;
    // Now output formatting is on!
    d($item->of(), 'output formatting');
    // No need to go any further
    break;
}
``` 

### Expected behavior

Output formatting does not get switched on unexpectedly.

### Steps to reproduce the issue

1. Install PW 3.0.96 with blank profile.
2. Create 'body' CKEditor field. Activate Link Abstraction feature for the field, and add field to home and basic-page templates.
3. Create and publish page "Basic page" using basic-page template.
4. Edit the Home page, and in the body field create a link to "Basic page". Save.
5. Install Tracy Debugger if you will use the console to test the issue.
5. Execute the code shown above. Note that it is important that the $pages->find() selector matches both the page containing the link and the page being linked to.

If any of the following applies then the issue does not occur:

* link abstraction not activated for the body field
* no internal link in the body field
* you do not get the value of the body field in your code
* the $pages->find() selector does not match both the page containing the link and the page being linked to

I can provide access to the demo site if needed.

### Setup/Environment

* ProcessWire version: 3.0.96
* (Optional) PHP version: 7.1

**Comment by ryancramerdesign** [comment]
This occurs because when a page is loaded, $pages first checks to see if it's already loaded (runtime cache) so that it doesn't have to do so again. $pages always returns pages consistent with the current output formatting state that is set on the $pages API var, regardless of whether loaded from DB or from memory cache. Part of link abstraction is loading pages to check the URL. URLs are created at runtime, and thus one page loading triggers loading of parents. In this case, the homepage is one of those parents. This is why the output formatting state is getting adjusted—because something else (link abstraction in this case) has asked $pages for the homepage, and $pages is set to return pages with the output formatting state on. 

So long as PW is using a runtime cache for pages, I don't think there's a way to avoid that behind-the-scenes. But if you've found it's causing an issue for your case, there are a couple of ways you can easily avoid it. Option 1 would be to follow your `$item->of(false);` call with a `$pages->of(false);` call. This would ensure that any pages loaded (as a result) maintain your intended output formatting state. Option 2 would be to `$item = clone $item;` so that you've got a copy that's independent of the version present in the pages cache.

**Comment by Toutouwai** [comment]
Thanks for the explanation. 

Using $pages->of(false) is a good solution - I can just use that once before I find my pages.
