### ISSUE TITLE
setAndSave('name', 'test') in ready.php error 500

### ISSUE THREAD

**Issue by cb2004** [processwire/processwire-issues#547]
### Short description of the issue

A hook is not working correctly, the name is changed but there is an error 500

```
$pages->addHookAfter('save', function($event) {
	$page = $event->arguments(0);
	$page->setAndSave('name', 'test');
});
```

### Expected behavior

There should not be an error

### Actual behavior

Switching to Wamp with debug set to true we have:

Fatal error: Maximum function nesting level of '256' reached, aborting! in C:\FOLDERS\wire\core\Field.php on line 1053

### Setup/Environment

* ProcessWire version: 3.0.96

**Comment by ryancramerdesign** [comment]
What you've got there is a recursive hook. By that I mean you are hooking into a method, and then your hook calls the method again, which results in an infinite loop. (setAndSave is the same as save when it comes to what hooks are called). That's not something ProcessWire can protect you from. You would need to add some code to prevent your hook from going recursive. For instance:
~~~~~
$pages->addHookAfter('save', function($event) {
  static $recursive = false;
  if($recursive) return;
  $recursive = true;
  $page = $event->arguments(0);
  $page->setAndSave('name', 'test');
  $recursive = false;
});
~~~~~
Alternative way to accomplish it:
~~~~~
$pages->addHookAfter('save', function($event) {
  $page = $event->arguments(0);
  if($page->get('_is_saving')) return;
  $page->setQuietly('_is_saving', true);  
  $page->setAndSave('name', 'test');
  $page->setQuietly('_is_saving', false); 
});
~~~~~
Also, not that it matters that much, but I wanted to recommend using the `Pages::saved` hook rather than after `Pages::save`. OR if possible, hook `Pages::saveReady` and set your `name=test` from there, so that everything can be accomplished without having to trigger and extra save() call.

**Comment by cb2004** [comment]
@ryancramerdesign thanks as always, this is why I choose ProcessWire for all my projects, you really do go the extra mile.

**Comment by BitPoet** [comment]
This is expected behavior. setAndSave triggers the save hook since the page is being saved. You should either do your modifications in a saveReady hook (preferred) or at least use a flag to avoid calling setAndSave again. Example (and perfect application for static variables):
```php
$pages->addHookAfter('save', function($event) {
	static $insideHook = false;
	$page = $event->arguments(0);
	if(! $insideHook) {
		$insideHook = true;
		$page->setAndSave('name', 'test3');
	}
	$insideHook = false;
});
```

**Comment by Toutouwai** [comment]
Just wanted to add that a hook like this doesn't go recursive if you are saving a single field with setAndSave(), because in that case the field is ultimately set with $pages->saveField() and which doesn't trigger a $pages->save() hook.

But if you are using setAndSave() with a property that isn't a field (such as name) or an array of fields then it will go recursive.
