### ISSUE TITLE
Urls of non-default, not active languages not throw 404 error

### ISSUE THREAD

**Issue by Lazerproof** [processwire/processwire-issues#56]
### Short description of the issue
In typical multilanguage setup some pages can have translation only for one (default) language. It means that checkboxes for other languages are non selected (not active). In this case only default language url should render a page, urls for other languages should throw 404 error. 

### Expected behavior

site.com/about-us - active ( render page in default language ) 
site.com/en/about-us - 404 error
site.com/es/about-us - 404 error

### Actual behavior

site.com/about-us - active ( render page in default language ) 
site.com/en/about-us - active ( render page in default language ) 
site.com/es/about-us - active ( render page in default language ) 

### Optional: Suggestion for a possible fix

Currently in init.php I use 
```
$currentLang = $user->language;
$pageLanguages = $page->getLanguages();
if(!$pageLanguages->has($currentLang)) {
    throw new Wire404Exception();
}
```

### Setup/Environment

* ProcessWire version: 3.0.37

**Comment by ryancramerdesign** [comment]
The intended behavior is that URLs like site.com/es/about-us, where the language "es" is unpublished, should 301 **redirect** to the default language (not render). That's also the behavior I observe when testing here. Likewise, if requesting a published language page with the wrong URL (like an extra leading /en/ or having some segment in the wrong language), it will redirect to the correct page *if* it can determine what the correct page would be. You mentioned rendering rather than redirecting–can you double check that you aren't just observing a redirect instead? When it redirects, the address bar in your browser should reflect the correct URL rather than the incorrect one.

**Comment by Lazerproof** [comment]
@ryancramerdesign thanks for attention for this issue. 
I think that it can be closed. The described behavior is actual just for superuser, guests get 404 page where it should be.
