### ISSUE TITLE
Permission 'user-admin' Causes 404

### ISSUE THREAD

**Issue by ethanbeyer** [processwire/processwire-issues#560]
### Short description of the issue

A user with a role that contains "user-admin" permissions is shown a 404 for a page they're supposed to have Page-View access to.

### Expected behavior

User should be able to see page.

### Actual behavior

Added "user-admin" to a role. Any users with this role are unable to view pages that are also Users.

With `$config->debug = true` set, this Notice is displayed:

`Notice: Trying to get property of non-object in /wire/modules/PagePermissions.module on line 245`

I determined that `$this->wire('pages')` was `NULL`. Not sure if this is the root of the problem, or part of it.

### Setup/Environment

* ProcessWire version: 3.0.97

**Comment by ethanbeyer** [comment]
I didn't have the ability to create a screengrab of this until now:

![https://i.imgur.com/R3vMUMO.gif](https://i.imgur.com/R3vMUMO.gif)

**Comment by ethanbeyer** [comment]
![screen shot 2018-04-09 at 09 45 04-fullpage](https://user-images.githubusercontent.com/6864684/38501474-1b0b6096-3bdb-11e8-8345-9870032364e4.png)

**Comment by ryancramerdesign** [comment]
I'm not sure I completely understand, because user pages aren't viewable by anybody. I suppose you could make a user.php file in /site/templates/ and superuser might be able to view it, but the user-admin permission is purely about administering users (as in editing, creating, deleting). It's not connected with any view permissions, as we don't consider user, role or permission templates to represent viewable pages in a website, since they are part of the admin page structure. 

If you do want to have some kind of front-end view for users in your site, this is fairly simple, and I setup something like this for one of the blog profiles awhile back if I recall. You need to setup a new template for that purpose, and enable URL segments on it. If you want it to be access controlled, then enable access control for the template as well. Then in the code, you'd do something like this:
~~~~~
$userName = $sanitizer->pageName($input->urlSegment1);
if(!$userName) {
  // no URL segment present: throw 404, or maybe render a list of users?
  throw new Wire404Exception();
}

$u = $users->get($userName);
if(!$u->id) {
  // user not found
  throw new Wire404Exception();
}

if(!$u->hasRole('member')) {
  // optional, if you want to limit viewable users to having a specific role
  throw new Wire404Exception(); 
}

// output the user
echo "<h1>$u->name</h1>";
// and so on
~~~~

**Comment by ethanbeyer** [comment]
Sorry, I should have stated said that I created a new user type, `directory-member`. (Sorry I keep badgering the community about this whole thing, but it's a directory site where the Users of this type are the site's front-end content -- related to #538.)

`directory-member` does have a front-end template, and is viewable by everyone who is logged in to the site *unless* that logged-in user has the `user-admin` permission. It's super weird, and it doesn't make sense. I thought that the error might be the result of giving that permission to a user of the `directory-member` type, but it doesn't seem to matter if it's a User or a Directory Member.

Maybe this will help. All the `directory-members` are nested beneath `region`s as parents.

There are several regions, and so in `config.php`, I have it set up like this:

```php
$config->userTemplateIDs = array(3, 37); // users and directory-member
$config->usersPageIDs = array(1061, 1062, 1063, 1064, 1065, 1066, 1067, 1264, 1265, 1849, 29); // All the Regions and /admin/access/users
```

Is it possible that the `user-admin` permission assumes the path to the user in question? That's literally the only thing I can think it might be.

Anyhow, I understand that the `user-admin` permission doesn't do anything regarding the

**Comment by ethanbeyer** [comment]
Also - creating this new user type has resulted in the "Add New" user link not working, which I am endeavoring to patch myself.

**Comment by ethanbeyer** [comment]
If it would be helpful to have a copy of all the code and database (because it's very possible I have misconfigured something), I would be happy to email that to you separately, @ryancramerdesign.

**Comment by Toutouwai** [comment]
@ethanbeyer, if these user pages are in the page tree outside of Admin > Access > Users and they are edited via ProcessPageEdit rather than ProcessUser, do you actually need to give any roles the "user-admin" permission?

Wouldn't you just give them edit access to that template the same as you would with any other non-user template?

**Comment by ethanbeyer** [comment]
@Toutouwai (cc @ryancramerdesign)

> if these user pages are in the page tree outside of Admin > Access > Users and they are edited via ProcessPageEdit rather than ProcessUser, do you actually need to give any roles the "user-admin" permission?
> Wouldn't you just give them (or not give them) edit access to that template the same as you would with any other non-user template?

I was thrilled to try this out, because I was pretty sure you were right and this was a tremendous oversight on my part. But the answer is no. Here's what happens for a user that has Page Edit but not User Admin permissions:

[![https://gyazo.com/adbd763e4906194c0bd3b89455203d20](https://i.gyazo.com/adbd763e4906194c0bd3b89455203d20.gif)](https://gyazo.com/adbd763e4906194c0bd3b89455203d20)

That person is sent (via `$page->editUrl()`) to `/admin/access/users/edit/?id=XXXX`. This results in an "Unrecognized Path". This error is only set in [*one place* in all of ProcessWire](https://github.com/processwire/processwire/blob/master/wire/core/ProcessController.php#L277). So that's weird. And I think it's because the Core changes the Edit URL of a User from `/admin/page/edit/?id=XXXX` to '/admin/access/users/edit/?id=XXXX` - but without `user-admin` permissions, the admin templates don't believe the user should be there. So that's part of the problem - that a Page === a User is not viewed as so by these permissions.

Once `user-admin` is added to the Role, all pages with this template result in a 404, as set by the template editor.

**Comment by Toutouwai** [comment]
I tested this and can confirm the issue. When using [alternate templates/parents for users](https://processwire.com/blog/posts/processwire-core-updates-2.5.14/#multiple-templates-or-parents-for-users), the user pages become non-viewable on the front-end to a logged-in user having the user-admin permission.

When logged in as the role with user-admin permission I was able to edit the user page though - via the page tree or via Access > Users (both routes open the user page in ProcessUser rather than ProcessPageEdit).

To be honest, when I first read the blog post that introduced alternate template/parents my instinct was that the feature was a bit experimental with the potential for unforeseen issues. For most features I like to be an early adopter and finding a few bugs is no big deal - that's the only way bugs will get fixed. But when it comes to users I don't like to take any chances, so I have always stuck with the approach that Ryan outlines above, leaving user pages in their default location. I think most PW devs have done the same, which perhaps explains why it has taken more than 3 years for issues like this to come to light.

**Comment by ryancramerdesign** [comment]
The viewable issue is occurring because PW delegates the viewable permission to the editable permission, when the user has user-admin permission. And for user-admin permission, editable becomes contextual to what the current process is. For instance, if they are in ProcessUser, then the user is editable, but if they are elsewhere, then the user isn't. I pushed an update just now that removes that contextual part of the logic when performing a viewable check. I've not yet setup the same user environment you've got there, so I don't know for sure if it corrects the issue, but please let me know what you find. 

Also, when it comes to users and access control, I really try and lock it down for safety, and that probably creates hurdles for people that are trying to open it up, like you are here. The best route might be to just override ProcessWire's viewable check for users with a hook, so that you can have full control over the logic. Here's a simple example that might go in your /site/ready.php:
~~~~~~~
$wire->addHookAfter('Page::viewable', function($event) {
  $viewable = $event->return;
  if($viewable) return; // use PW's existing logic, since it said it was viewable
  $page = $event->object;
  if(!$page instanceof User) return; 
  if(whatever logic you decide that $page is viewable) {
    $viewable = true;
    $event->return = $viewable;
  }
}); 
~~~~~~~

**Comment by ethanbeyer** [comment]
You're a wizard, @ryancramerdesign! Thank you so much. I will pull in the changes to that file and test.

The hook might be another way to go as well. I wasn't sure enough what the problem's root was to know where to hook, but it looks like you have untangled it for me, so again, thank you so much! I will report back ASAP.

**Comment by ethanbeyer** [comment]
This looks to be fixed, thanks to commit 2a49fe1. Really, I appreciate it so much that you made this change. I know it was a weird one. Will this lead to instability in other areas?

**Comment by netcarver** [comment]
@ethanbeyer Ethan, can you close this issue if it is fixed to your satisfaction. Thank you!

**Comment by ethanbeyer** [comment]
Missed this, thanks!
