### ISSUE TITLE
Emoji in field labels don't work 😣

### ISSUE THREAD

**Issue by noelboss** [processwire/processwire-issues#561]
### Short description of the issue

Adding an emojy to a fieldlabel works in other languages but not in the default language

### Expected behavior

It should work in all languages to increase usability. Example

Default Label: Documents [🇩🇪]
German Label: Dokumente [🇩🇪]

### Actual behaviour

Label is cut of where the emoji starts;

Default Label: Documents [
German Label: Dokumente [🇩🇪]

### Optional: Screenshots/Links that demonstrate the issue

![default label](https://user-images.githubusercontent.com/114080/38487879-f8cab084-3be1-11e8-8629-0a6fc6ff935b.png)
![german label](https://user-images.githubusercontent.com/114080/38487881-f8e380d2-3be1-11e8-827b-5603958138e0.png)

### Steps to reproduce the issue

1. Add an emojy to a fiel label somewhere in between
2. Save
3. Label gets cut off where the emoji starts
4. Try the same in an other language > Works

### Setup/Environment

<details><summary><strong>Server Details</strong></summary>ProcessWire: 3.0.97 <br />
PHP: 7.1.16 <br />
Webserver: Apache <br />
MySQL: 5.5.56-MariaDB <br />
 <br />
</details><details><summary><strong>Server Settings</strong></summary> allow_url_fopen: 1 <br />
max_execution_time: 120 (changeable) <br />
max_input_nesting_level: 64 <br />
max_input_time: 120 <br />
max_input_vars: 20000 <br />
memory_limit: 256M <br />
post_max_size: 1G <br />
upload_max_filesize: 1G <br />
xdebug:  <br />
xdebug.max_nesting_level:  <br />
 <br />
mod_rewrite: 1 <br />
mod_security:  <br />
 <br />
GD: bundled (2.1.0 compatible) <br />
GIF: 1 <br />
JPG: 1 <br />
PNG: 1 <br />
 <br />
EXIF Support: 1 <br />
FreeType: 1 <br />
Imagick Extension: 1 <br />
 <br />
</details><details><summary><strong>Module Details</strong></summary> AdminOnSteroids: 1.8.9 <br />
AdminPageFieldEditLinks: 3.1.1 <br />
CronjobDatabaseBackup: 1.1.5 <br />
FieldDescriptionsExtended: 1.0.2 <br />
FieldtypeAssistedURL: 1.0.0 <br />
FieldtypeFieldsetGroup: 0.0.2 <br />
FieldtypeFunctional: 0.0.1 <br />
FieldtypeMultiplier: 0.1.1 <br />
FieldtypeRepeaterMatrix: 0.0.4 <br />
FieldtypeRuntimeMarkup: 0.0.2 <br />
FieldtypeTable: 0.1.5 <br />
FieldtypeTextareas: 0.0.7 <br />
FrontEndEditLightbox: 1.3.6 <br />
IcfAttachments: 0.0.1 <br />
IcfAuth: 0.0.1 <br />
IcfDownloads: 0.0.1 <br />
IcfFeaturedImage: 0.0.2 <br />
IcfRangeDownload: 0.0.1 <br />
IcfTemplateTranslations: 0.0.1 <br />
IcfUnsplash: 0.0.2 <br />
IcfUtil: 0.0.1 <br />
InputfieldAssistedURL: 1.0.1 <br />
InputfieldChosenSelect: 1.2.3 <br />
InputfieldChosenSelectMultiple: 1.1.9 <br />
InputfieldFunctional: 0.0.1 <br />
InputfieldMultiplier: 0.1.1 <br />
InputfieldRepeaterMatrix: 0.0.4 <br />
InputfieldRuntimeMarkup: 0.0.2 <br />
InputfieldTable: 0.1.5 <br />
InputfieldTextareas: 0.0.7 <br />
LoginRegister: 0.0.2 <br />
LoginWithEmail: 0.0.3 <br />
Oauth2Login: 0.1.0 <br />
ProcessForgotPassword: 1.0.2 <br />
ProcessSwitchUser: 0.0.6 <br />
ProcessTagParserTest: 1.0.0 <br />
ProcessWireUpgrade: 0.0.7 <br />
ProcessWireUpgradeCheck: 0.0.7 <br />
TextformatterMakeLinks: 1.0.0 <br />
TextformatterOEmbed: 2.0.2 <br />
TextformatterTagParser: 2.1.0 <br />
TextformatterVideoEmbedOptions: 0.3.5 <br />
TracyDebugger: 4.9.37 <br />
WireMailMandrill: 0.0.1 <br />
</details>

**Comment by ryancramerdesign** [comment]
It seems to work here. I tested in both multi-language and non-language sites. Is it possible that you don't have utf8mb4 as your database charset? That would be a requirement for emoji support. Since this is not the default charset in PW, you would have had to have chosen it at install time in order to have emoji support.

**Comment by ryancramerdesign** [comment]
Technically emojis shouldn't work if not using utf8mb4. I don't know why it works in your case, but maybe that particular emoji also maps to a 3-byte character in the same way. Or maybe because multi-language labels get encoded into a field's JSON data, that somehow allows the 4-byte character to survive. In any case, your best bet is to switch to utf8mb4 so that you can support it properly. You can do this by exporting your DB to an SQL file, and updating a few things (charset=utf8 to charset=utf8mb4, and adjusting max key lengths for some fields), then re-importing. Let me know if I can provide further instructions.

**Comment by netcarver** [comment]
@noelboss Did Ryan's suggestion above resolve this issue for you? Please update us.

**Comment by netcarver** [comment]
Closing this as it has gone cold. @noelboss Please post more if needed and it can be reviewed. Thank you!
