### ISSUE TITLE
Long running query on multiple page reference field selectors with same name pages

### ISSUE THREAD

**Issue by 14pixels** [processwire/processwire-issues#563]
### Short description of the issue

When having a page selector which is querying multiple fields of type "Page Reference" with OR and there are multiple pages existing with the same name, like the name queried on the selector, the query takes very long (multiple hours).

### Expected behavior

The find query should just return the results

### Actual behavior

A mysql query is executed which takes multiple hours

### Steps to reproduce the issue
1. Create a template with the name "templateA" (the fields of this template do not matter)

2. Create Multiple pages with the same name (example_page) of template "templateA" under different parents (the templates of the parent pages do not matter)
/parent1/example_page
/parent2/example_page
/parent3/example_page
... like 10-20 of them

3. Create a template "templateB" (the fields of this template do not matter)

4. Create one page with the name "example_page" under the root (or somewhere else, does not matter), with template "templateB"

5. Create 5 fields of type "Page Reference" (Single Page select) with selectable pages "templateB" named b1, b2, b3, b4, b5

6. Use the selector `$pages->find('b1.name|b2.name|b3.name|b4.name|b5.name=example_page');` somewhere

7. When calling the page a query with many joins is produced that takes multiple hours

This is the query from my site (there were a few more selectors inside as in the example, but the error occurs also only with the stuff explained above):
`
SELECT pages.id,pages.parent_id,pages.templates_id 
FROM `pages`
JOIN pages AS _fieldtypepage1 ON _fieldtypepage1.name='seitensprung' 
JOIN pages AS _fieldtypepage2 ON _fieldtypepage2.name='seitensprung' 
JOIN pages AS _fieldtypepage3 ON _fieldtypepage3.name='seitensprung' 
JOIN pages AS _fieldtypepage4 ON _fieldtypepage4.name='seitensprung' 
JOIN pages AS _fieldtypepage5 ON _fieldtypepage5.name='seitensprung' 
JOIN field_api_provider_status AS field_api_provider_status ON field_api_provider_status.pages_id=pages.id AND (((field_api_provider_status.data='ACTIVE' ) )) 
LEFT JOIN pages_access ON (pages_access.pages_id=pages.id AND pages_access.templates_id IN(2,3)) 
LEFT JOIN field_api_main_category AS field_api_main_category ON field_api_main_category.pages_id=pages.id AND ((((field_api_main_category.data=_fieldtypepage1.id) ) )) 
LEFT JOIN field_api_category2 AS field_api_category2 ON field_api_category2.pages_id=pages.id AND ((((field_api_category2.data=_fieldtypepage2.id) ) )) 
LEFT JOIN field_api_category3 AS field_api_category3 ON field_api_category3.pages_id=pages.id AND ((((field_api_category3.data=_fieldtypepage3.id) ) )) 
LEFT JOIN field_api_category4 AS field_api_category4 ON field_api_category4.pages_id=pages.id AND ((((field_api_category4.data=_fieldtypepage4.id) ) )) 
LEFT JOIN field_api_category5 AS field_api_category5 ON field_api_category5.pages_id=pages.id AND ((((field_api_category5.data=_fieldtypepage5.id) ) )) 
WHERE (pages.templates_id=46) 
AND (pages.status<2048) 
AND ((((field_api_main_category.data=_fieldtypepage1.id) ) )
   OR (((field_api_category2.data=_fieldtypepage2.id) ) )
   OR (((field_api_category3.data=_fieldtypepage3.id) ) )
   OR (((field_api_category4.data=_fieldtypepage4.id) ) )
   OR (((field_api_category5.data=_fieldtypepage5.id) ) ) ) 
AND pages_access.pages_id IS NULL 
AND pages.templates_id NOT IN(2,3) 
GROUP BY pages.id
`

* ProcessWire version: 3.0.80
* (Optional) PHP version: 7.0
* (Optional) MySQL version: MySQL 5.7.16

**Comment by ryancramerdesign** [comment]
Thanks for the report. I can roughly duplicate this. While I'm not getting hour long queries, I am getting some that take a few seconds, which is slow. The more field.subfield OR conditions I add on to a selector, the longer the query takes. And at some point the quantity of OR conditions makes the query too slow to be useful. This is happening in MySQL and you are running up against a limitation of what can be handled reasonably in one query, while still being fast. 

Most ProcessWire selectors translate to fast DB queries, but it's also possible for one to create selectors that will give MySQL a workout. Particularly when there are OR conditions and subfields involved, which means it's going to have to perform a lot of joins. There are limitations to what you can do in a single MySQL query, and likewise with a single selector. I'm not sure there's anything ProcessWire can do to make MySQL perform better with that type of query. The simplicity of PW selectors sometimes hides the fact that it may not be so simple once it gets to actually querying the database. You may be able to adjust your MySQL settings to make it perform better, but I would suggest instead simplifying your selector or breaking it down into two separate finds. This is what I do when I sometimes run across a pages find() situation that is not performing as quickly as I'd want it to. 

The type of query below should do the same thing and be a lot faster, because it doesn't have to repeatedly join the pages table to check the name of pages in every page reference field. Instead it finds the pages having name "example_page", grabs those IDs, and then checks which of your listed Page reference fields point to those IDs: 
~~~~~
$pages->find('b1|b2|b3|b4|b5=[name=example_page]');
~~~~~
Here's another way to basically do the same thing, but splitting it into two. It also helps to describe what the example above is doing (in using a subselector): 
~~~~~
$a = $pages->find("name=example_page"); 
$pages->find("b1|b2|b3|b4|b5=$a"); 
~~~~~

**Comment by netcarver** [comment]
@14pixels Did Ryan's reply allow you to sort out the slow query? Can this issue now be closed?

**Comment by netcarver** [comment]
Closing as this seems to have gone cold. @14pixels please post more if you require more assistance. Thank you.
