### ISSUE TITLE
AdminThemeUikit: select is missing UIKit styling

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#564]
### Short description of the issue

The select form control is currently "odd man out" when it comes to styling in AdminThemeUikit. Other key form controls (text, textarea, checkbox, radio) get UIkit styling but not select.

The [UIkit documentation](https://getuikit.com/docs/form) shows how the select control should be rendered the same height as a text control:
![2018-04-13_124652](https://user-images.githubusercontent.com/1538852/38711273-db1d4382-3f18-11e8-9410-6f7ea4ac7fd7.jpg)

But in AdminThemeUikit there is a significant difference in height:
![2018-04-13_123825](https://user-images.githubusercontent.com/1538852/38711100-c59e6cda-3f17-11e8-85e5-5325b084e0ef.jpg)

This makes for an ugly appearance when a select control is placed next to a text input on the same row (in a custom module UI for instance).

If UIkit is to be the basis for the default core admin theme going forward we should be going "all in" on its styling.

### Setup/Environment

* ProcessWire version: 3.0.98

**Comment by Toutouwai** [comment]
I totally agree that the width of the select should be auto rather than 100%, and it's good having a bit more visual difference between selects and text inputs than in the UIkit default. But I don't think they should look as foreign to each other as they do currently.

If the basic browser select is used, could the height be set to match text inputs? This Table field appearance for example looks pretty untidy...
![2018-04-14_173952](https://user-images.githubusercontent.com/1538852/38764854-e9bc31da-400a-11e8-8846-ad6b1292c110.jpg)

I think that screenshot also shows that the default height of text inputs in UIkit is excessive. My preference would be to reduce the height of text inputs a bit and have the select height match...

![2018-04-14_174734](https://user-images.githubusercontent.com/1538852/38764909-086b21e4-400c-11e8-86af-ae450c113f16.jpg)

**Comment by ryancramerdesign** [comment]
> But I don't think they should look as foreign to each other as they do currently.

Thanks, your screenshot clarifies it. I agree they don't look good here. I don't often see this, because selects look nothing like that in OS X. In your screenshot, the selects already look like little text inputs, so the uk-select starts to make more sense if/when they are going to look like your screenshot.

> If the basic browser select is used, could the height be set to match text inputs? 

Maybe so, but I think there are some significant limitations here. Selects are a bit strange when it comes to styling if I recall, since they are rendered based on client side factors (platform, browser).  Maybe your original suggestion of just using the uk-select is the best available solution for us. But since I think it's also kind of problematic, I guess it should be a toggle in the Uikit module config as to whether or not they are used.

**Comment by Toutouwai** [comment]
> Selects are a bit strange when it comes to styling if I recall, since they are rendered based on client side factors (platform, browser).

Not sure about other OSs, but all Windows browsers that I have used respect height and font-family styles for selects. You could take a peek at the Uikit styles for selects as I expect they have made an effort for cross-platform consistency and use that as a starting point for a custom style that would suit PW usages.

**Comment by teppokoivula** [comment]
Selects have always been difficult to style, but "appearance: none" helps a lot, if you don't mind doing all the styling yourself. I'm not entirely sure how well it is supported, though: Chrome and Firefox use prefixed versions (-webkit-appearance etc.) but I have no idea about IE/Edge.

Based on a very quick test, Chrome on OS X allows me to style most regular properties of a select, except for padding and border-radius, even without touching "appearance". Height and width, for an example, work just fine here. Again, there are no doubt platform/browser specific differences.

**Comment by ryancramerdesign** [comment]
See the latest update on the core dev branch—it adds Uikit styled selects. I modified the styling of them from the base Uikit select styling so that they don't look quite so much like text fields (a little border-radius). Hopefully this change means we have a select that looks the same across platforms and browsers. 

> I think that screenshot also shows that the default height of text inputs in UIkit is excessive. My preference would be to reduce the height of text inputs a bit and have the select height match (and set the same font-family for all form controls too)...

While I personally like the defaults on Uikit in this regard, I know it's subjective and they are above average in terms of size. Uikit does support a uk-form-small class that makes it use smaller size inputs. I've added support for this in the latest version on the dev branch. You'll see it in the module config under the "Forms and Input" fieldset (if you want to adjust all sizes), or you can adjust it on a per-field basis (or field/template context) for any field on the Input tab > Admin theme settings (Uikit). Also added support for uk-form-width-[size] and uk-form-blank classes, which affect the appearance of text inputs.

**Comment by ryancramerdesign** [comment]
No, I still have to add those. Hope to have most covered by Friday

On Apr 18, 2018 2:22 PM, "Matjaž Potočnik" <notifications@github.com> wrote:

If I select "Small" as "Default Input Size" then the integer, float, date,
email fields (and maybe others) are still rendered as "default" size:

[image: screenshot 2018-04-18 20 01 46_cr]
<https://user-images.githubusercontent.com/7663992/38950425-c60545b8-4345-11e8-866c-9140664488e0.jpg>

This is how it should be?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/processwire/processwire-issues/issues/564#issuecomment-382482446>,
or mute the thread

**Comment by Toutouwai** [comment]
Looking good, thanks.

**Comment by adrianbj** [comment]
@ryancramerdesign - I am really liking the new styling for selects, but it doesn't seem to apply to ASM selects

Select on the left, ASM on the right:

![image](https://user-images.githubusercontent.com/871211/39073014-316b5d72-44a1-11e8-9f6b-2a8aafd0584b.png)

**Comment by adrianbj** [comment]
Just one more comment - not sure about the rounded corners - is that intentional? Seems to me they should imitate the square corners of regular text inputs.

**Comment by Toutouwai** [comment]
> I am really liking the new styling for selects, but it doesn't seem to apply to ASM selects

In Windows Chrome an AsmSelect and Select have the same styling apart from height (would be good to make that consistent).

![2018-04-21_113222](https://user-images.githubusercontent.com/1538852/39077669-cabe2d72-4557-11e8-806d-2a52d033c8de.png)


> not sure about the rounded corners - is that intentional?

Ryan [mentions above](https://github.com/processwire/processwire-issues/issues/564#issuecomment-382385413) that it is intentional, although I must admit I am removing the radius in my custom admin CSS.

**Comment by ryancramerdesign** [comment]
The rounded corner are intentional, only because I thought there wasn't enough difference between text inputs and selects, as they both look like text inputs without the rounded corners. But I don't feel that strongly about it. If more people prefer no rounded corners (?), I can remove them. 

Regarding asmSelect, that's also intentional that those always use the small selects. The asmSelect isn't just a select, but a closely connected list of items — the select and the items it selects are supposed to be close in visual height, and the small option does that. Anything bigger breaks the visual connection. I understand that when no options are selected, it just looks like a smaller select, but decided it was important for this case.

**Comment by fijha** [comment]
Would be nice to have an option to disable this new styling of select elements. Now I think it looks more inconsistent/imperfect… or maybe they should just all have the same height and auto width as before without styling.

**Comment by szabeszg** [comment]
Why can't a Select has the same height as AsmSelect?
