### ISSUE TITLE
ProcessProfile::processInput

### ISSUE THREAD

**Issue by kixe** [processwire/processwire-issues#566]
### Short description of the issue

Getting Server Error 500 (Live Server)
or PDO failure (Local Server)
when trying to save the Profile for Non-superuser roles.

### Expected behavior

No Error

### Actual behavior

The error occurs if a non superuser save his profile.
The Error is not logged. No Exception is thrown in debug mode
The error could be prevented after commenting out line 297 function processInput() of ProcessProfile

`$user->of(true);`

* ProcessWire version: 3.0.98
* PHP version: 7.1
* MySQL version: 
* Any 3rd party modules that are installed and could be related to the issue: Error persists after uninstalling all 3d party modules.
* AdminThemeUikit

**Comment by ryancramerdesign** [comment]
I can't duplicate this one. Can anyone else?

**Comment by ryancramerdesign** [comment]
The stack and logic that comes before the redirect looks correct to me. Calling the ProcessProfile::execute() method is what it should do. It's what happens in that method that matters here, as that's where it determines whether or not to do either 1) render; or 2) save+redirect. In order for it to do a save+redirect in there, the form had to be submitted first (POST request) with a "submit_save_profile" variable present in the POST data, OR an HTTP_X_FIELDNAME header had to be provided by the client. Redirects are not POST requests, nor do they include that HTTP header. So it's unclear to me how an endless redirect could come about. Do you have any other modules installed in /site/modules/? Just wondering if anything might be hooking into the logic that could be affecting it.

**Comment by ryancramerdesign** [comment]
Are you talking about `Field::flagAccess`? (this has value=32). I tried assigning that to my roles field, but it seems to work fine. Is it possible you've removed view access to roles? If so, that would do it (PW can't identify user access if it can't read the roles). When changing things in ProcessWire's system fields and templates it is possible to break things, which is why we identify them as system and isolate them from other fields/templates.

**Comment by kixe** [comment]
In the database the value is stored as **flagsAdd**
> Is it possible you've removed view access to roles?

Exactly that's what I did.
It's clear now that user roles should always stay accessible via API. I added **Field::flagAccessAPI** which results in **flagsAdd = 160** in the DB. (128 + 32 = 160). I did this template based and it works fine too.

The problem is, there is no exception thrown by the core class, if `$this->wire('user')->roles` returns **null**. It was difficult to figure out the reason for this uncatched error in **PagePermissions** and **ProcessProfile** class.

**Comment by ryancramerdesign** [comment]
flagsAdd manipulates field flags, but is just assigned at the field/template context level. I recommend not using field/template context here, because this is a system field. Are you using the "roles" field on multiple templates where you would need field/template context? If you want to be safe, create your own separate roles field for the non-user templates if possible. Edit the roles field directly rather than through field/template context, as there should only be one context for roles (user). 

Modifying system templates and fields is kind of like jailbreaking/rooting your phone, in that you are in a space where you are modifying aspects of the core system and things can be broken, and PW can't really protect from this. ProcessWire needs to assume that its system is there. It wouldn't be practical if PW had to conditionally check if system fields, API variables and templates were present on every access. 

I would suggest avoiding access control for ProcessWire's system fields when possible, but I understand your use case here, and if you find it works, then it should be okay. But If you enable access control for a system field like roles, better to make it globally viewable (box for guest checked). I'm thinking the "Make accessible from API" may not be enough for this case since it is a system field, so test thoroughly to make sure.

**Comment by netcarver** [comment]
@kixe, @ryancramerdesign Can this issue be closed now?

**Comment by kixe** [comment]
@netcarver, @ryancramerdesign 
Since I know the reason for the problem, I can handle it. Debugging was not very easy, so I still vote for catching that error and throw a corresponding exception. Apart from this the issue can be closed.

**Comment by netcarver** [comment]
@kixe Thanks Christoph, closing the issue here. Perhaps you could open an issue on the requests repository for the improvement you are suggesting?
