### ISSUE TITLE
404 error on saving fields with a specific content

### ISSUE THREAD

**Issue by wojciech-sulewski** [processwire/processwire-issues#573]
### Short description of the issue
When trying to save a field with content 

> 'union

I get redirected to 404 error page and the field is not saved.
I tried with following field types:
- Text
- Textarea
- and Multi-language versions

Changing any letter in the union word makes it work again. Also ' char is necessary to reproduce this error. So far I have not found any other field content to cause this error.

My page has already a lot of content and multiple fields but no direct code or DB changes were made. I was not able to reproduce this error on a fresh PW install. Page was upgraded to 3.0.98 from 3.0.42 and error is still present.
What can I do to further investigate this issue?

### Setup/Environment
* ProcessWire version: 3.0.98
* PHP version: 7.1

**Comment by Toutouwai** [comment]
> What can I do to further investigate this issue?

You can try disabling mod_security at your host:
https://stackoverflow.com/a/12928404
https://www.ecenica.com/support/answer/disable-mod_security-domains-cpanel/

**Comment by ryancramerdesign** [comment]
I agree with @Toutouwai that this sounds like a mod_security issue. The behavior you are observing is consistent with a server-side security software (whether mod_security, suhosin or another) inspecting input variables and cancelling the request when it sees something that looks potentially malicious. It's seeing your `'union` in the POST data as a problem because it's a reserved SQL word. This is really over-aggressive security and you'd want to contact your host to see about fixing this.

**Comment by wojciech-sulewski** [comment]
After disabling mod_security it works again.
Thank you for help.
