### ISSUE TITLE
Fatal Error if a user with limited user-admin permission tries to edit another user

### ISSUE THREAD

**Issue by kixe** [processwire/processwire-issues#578]
### Short description of the issue

A loggedin user with role **editor** tried to access the user edit screen via provided menu in the admin. The menu shows a list of users with the role **client**. After clicking a user a fatal error occurs.
The user with role **editor** is not allowed to edit roles.
The template **user** and the field **roles** as well has access control enabled. User with role editor has permission 'page-edit' and 'page-add' related to template **user** for limited roles. But he is not allowed to edit the field 'roles' (access control set via template settings [fieldgroup_fields]).

### Expected behavior

Aibility to edit users with role client for users with role editor, even if the field roles is not editable/accessible.

### Actual behavior

Fatal Error trying to edit another user.
Endless redirect trying to edit himself.

```
Page: https://example.org/admin/access/users/
User: x

Error: 
Uncaught Error: Call to a member function has() on null in .../wire/modules/PagePermissions.module:258
Stack trace:
#0 .../wire/modules/PagePermissions.module(521): ProcessWire\PagePermissions->userEditable(Object(ProcessWire\User))
#1 .../wire/core/WireHooks.php(822): ProcessWire\PagePermissions->viewable(Object(ProcessWire\HookEvent))
#2 .../wire/core/Wire.php(442): ProcessWire\WireHooks->runHooks(Object(ProcessWire\User), 'viewable', Array)
#3 .../wire/core/Page.php(1323): ProcessWire\Wire->__call('viewable', Array)
#4 .../wire/core/User.php(429): ProcessWire\Page->getFieldValue('roles', '')
#5 .../wire/core/Page.php(1089): ProcessWire\User->getFieldValue('roles')
#6 .../wire/core/Page.php(1587): ProcessWire\Page->get('roles')
#7 ... (line 258 of .../wire/modules/PagePermissions.module)
```

### Setup/Environment

* ProcessWire version: 3.0.99
* (Optional) PHP version: 7.1

**Comment by kixe** [comment]
Maybe related: #566

**Comment by ryancramerdesign** [comment]
I can't duplicate any of the behaviors you mentioned, though I'm not sure I'm understanding everything. Can you confirm that your "editor" role has "user-admin" permission?  ProcessWire has system templates and fields, which are hidden by default, because manipulating the settings of them can potentially break things. You mentioned that you were assigning permissions to the user template, which is one example of how it might break the access control model, since user-admin permission is what is intended for managing users. For managing access to your "roles" field, I think this should be fine, but access control is prior to additional layers, so avoid using field/template context for this—just edit the roles field directly. And make sure that the "guest" role has view access (which should make it apply to all roles), as ProcessWire always needs to be able to access a users roles, regardless of who is logged in.

**Comment by kixe** [comment]
I close this. The error has the same cause as the error in ProcessProfile described in #566
