### ISSUE TITLE
Image actions don't do what they should

### ISSUE THREAD

**Issue by somatonic** [processwire/processwire-issues#581]
### Short description of the issue

The new Image actions don't all work or do what they say. 
Ie. 90° does rotate it -180°. 
Flip vert/horiz/both doesn't do anything at all.

### Setup/Environment

* ProcessWire version: 3.0.96
* (Optional) PHP version: 5.6.10 - GD 2.1.0

**Comment by ryancramerdesign** [comment]
I can't duplicate this. Rotate 90 rotates 90 degrees for me, and flip vert/horiz/both all seem to be working properly. Can anyone else duplicate positive degree rotation or flips not working properly?

However, in trying to duplicate your issue, I did find that the *negative* degrees (i.e. -90) were not working property—they were getting converted to positive degrees due to input sanitization. So I'm pushing a fix for that now. Thanks.

**Comment by netcarver** [comment]
@somatonic I've tried all the image action options just now in a PW3.0.108 install (PHP7.2) and they are all working as expected for me too. Any other clues about your setup? How is your image field configured?

**Comment by somatonic** [comment]
It seems to work now. 

But my suggestion would be to remove

"+-270" as that can be archived just by rotating it -+90.

Also the -180 isn't needed as it does the same as +180 obviously.
