### ISSUE TITLE
Image not upload. mb_strpos error

### ISSUE THREAD

**Issue by ivanscm** [processwire/processwire-issues#599]
Image not upload is in php.ini set mbstring.func_overload = 2
If valuer = 4 - good work

core\ImageInspector.php return 
```
Warning</b>:  mb_strpos(): Empty delimiter in ...
<JSON ANSWER HERE>
```

sorry bad issue, i not talk in eng language

**Comment by ryancramerdesign** [comment]
I wasn't aware of this mbstring function overloading before. But after looking at it, this looks like it could be problematic throughout PW, because we use an mb_string function when we intend multibyte, and a non-mb_string function when we intend to work at the byte level. So I can see this function overloading causing a lot of issues, and would suggest disabling it. It looks like PHP has deprecated it and says its use is highly discouraged: http://php.net/manual/en/mbstring.overload.php

But for the error in question here, I think that may be something we can adjust for. The thing is, I don't understand why we are trying to match NULL in a string, so going to ping @horst-n for this. The line in question is here: 
~~~~~
$appmarker[$k] = substr($v, 0, strpos($v, null));
~~~~~
If I understand correctly, it sounds like when strpos() is overloaded to mb_strpos(), the mb_strpos() won't accept NULL as a second argument. @horst-n is there something else that can be used for this, like a null character, i.e. `chr(0)`?

**Comment by horst-n** [comment]
@ryancramerdesign  the ```chr(0)``` is working fine! We can change to use it.

**Comment by netcarver** [comment]
@ryancramerdesign Any further thoughts on this?

**Comment by netcarver** [comment]
@ryancramerdesign Bumping this for your consideration.

**Comment by ryancramerdesign** [comment]
@netcarver Thanks for the bump. It looks like I'd changed it to `chr(null)` at some point, as it was no longer `null`. But technically it should be chr(0), so I have updated it.

**Comment by netcarver** [comment]
Thank you Ryan. @ivanscm I intend to close this issue in 2 weeks unless you or anyone else finds a problem with the code fix.

/remind me to review and close if needed in 2 weeks

**Comment by netcarver** [comment]
Closing as no feedback. If anyone can confirm this has not fixed the issue, please post here and the issue will be re-opened.
