### ISSUE TITLE
user-admins cant create new user-admins

### ISSUE THREAD

**Issue by johhny13** [processwire/processwire-issues#607]
### Short description of the issue

Users with user-admin role cant create new users with administrative role. More info can be found here https://processwire.com/talk/topic/18398-user-with-user-admin-all-cant-make-another-user-an-editor/

### Expected behavior

users with user-admin permission should have ability to create another users with this ability.

**Comment by ryancramerdesign** [comment]
The intention is that only superuser can do that. After all, this is the most powerful permission that can be assigned. It's the sort of thing that superuser is for. On my installations at least, I wouldn't want user-admin users to go creating new ones or assigning that permission to other users. If there's a strong need for it, perhaps the ability would fit better under the user-admin-all permission?

**Comment by adrianbj** [comment]
I think this would actually be a very useful addition to the right for the user-admin-all permission. I have had several requests for this at the agencies I work with - they want their in-house marketing / SEO staff to be able to handle this but because these folks often aren't particularly technical, they don't want to give them superuser status.

**Comment by teppokoivula** [comment]
Hey @ryancramerdesign, another vote for this one from here.

The thing is that so far I've been using ProcessWire 2.7 for client sites, and just released the first 3.x client site. Having only used 2.8/3.0 for my own projects I wasn't aware of this limitation (something must've changed along the way, since in 2.7 user-admins *can* create new user-admins?) and right now this is a major issue for us.

Simply put we really can't grant the superuser role for user-admins, but we need them to be able to create new user-admins. Superuser role gives access to a ton of stuff that we really don't want non-technical folks to be able to do (including, but not limited to, installing modules, modifying fields and templates, and so on), so that's definitely out of the question.

Long story short, I'd very much appreciate if you could reconsider this. Thanks in advance!

**Comment by rogersarrasin** [comment]
I agree with both @adrianbj and @teppokoivula.
It would be a great addition for many projects I work on.

We are currently on our third client site using PW. Making the shift from some of the more "popular" CMS/CMF out there. It has been a very positive experience in many ways for both the agency I work for and our clients.

Two use cases for us are:

1. To allow our less technical in house team (marketing / non developers) to create equal user roles without requiring a developer to do so.

2. Allowing our bigger clients (Destination Marketing Organizations), who have sufficient experience and require a few of their key team members the ability to create an equal user role within their organization without the need to contact us to accomplish this task.

With other CMS/CMF we have at times created a specific user role, with the sole purpose of being able to create new users with equal or lesser user role capabilities (user-manager). This allows this 'user-manager' role to be assigned to one person vs another who may have the same User Role.

Thank for you considering the idea.

**Comment by ryancramerdesign** [comment]
Thanks for the feedback, sounds like a lot of people need it. I'll make sure it gets added to the next dev branch version 3.0.106

**Comment by rogersarrasin** [comment]
Fantastic,

Thanks Ryan!

Roger

**Comment by szabeszg** [comment]
> sounds like a lot of people need it.
I'm late to the party but I need it too. Thanks in advance Ryan!

**Comment by netcarver** [comment]
@johhny13 Looks like this code has been added. Could you please test the latest version and close this issue if that confirms the fix for you. Many thanks!

**Comment by netcarver** [comment]
@johhny13 @teppokoivula @szabeszg @adrianbj @rogersarrasin  I intend closing this issue in a week or so if I've not heard anything back from Johhny12 - or anyone else - about it by then.

Johhny can always re-open this issue later if needed.
