### ISSUE TITLE
AdminThemeUikit: Visible If textfield not respecting column width

### ISSUE THREAD

**Issue by TomS-** [processwire/processwire-issues#619]
### Short description of the issue

If you use "Visible if" in conjunction with column width on a text field, the width is not respected. 

### Expected behavior

The width should be respected

### Actual behavior

The width is 100%

### Optional: Screenshots/Links that demonstrate the issue

```
<li class="Inputfield InputfieldURL Inputfield_link_external InputfieldStateShowIf InputfieldColumnWidth InputfieldColumnWidthFirst uk-first-column      InputfieldColumnWidthLast uk-width-expand" data-show-if="link_type=2" data-colwidth="50%" id="wrap_Inputfield_link_external" style="display: block;"><label class="InputfieldHeader uk-form-label InputfieldStateToggle" for="Inputfield_link_external"><i class="fa fa-fw fa-link"></i> External Link<i title="Toggle open/close" class="toggle-icon fa fa-fw fa-angle-down" data-to="fa-angle-down fa-angle-right"></i></label><div class="InputfieldContent uk-form-controls"><input id="Inputfield_link_external" class="uk-input InputfieldMaxWidth" name="link_external" type="text" maxlength="1024"></div></li>
```
As you can see it has `data-colwidth="50%"` and `.width-expand`

### Steps to reproduce the issue

1. Create a select field
2. Create a text field that will be visible based on the select
3. Set the select and text field to 50% width
4. You'll notice that the 50% width is not respected

### Setup/Environment

* ProcessWire version: 3.0.105
* (Optional) PHP version: 
* (Optional) MySQL version: 
* (Optional) Any 3rd party modules that are installed and could be related to the issue:

**Comment by ryancramerdesign** [comment]
I can't seem to duplicate this one. See my attached screenshot. When any other option is selected, then the select field is expands to 100% width as it should. When option 1 is selected, both are 50%. Below is the screenshot and Inputfields definition. 

<img width="926" alt="screen shot 2018-06-12 at 10 47 55 am" src="https://user-images.githubusercontent.com/328272/41297960-53a6b3d0-6e2e-11e8-9f70-a9555a638938.png">

~~~~~~
$f = $modules->get('InputfieldSelect');
$f->attr('name', 'test_select');
$f->label = 'Col 1/2';
$f->description = 'Select option to reveal column(s)';
$f->addOption(1, 'Option 1');
$f->addOption(2, 'Option 2');
$f->addOption(3, 'Option 3');
$f->columnWidth = 50;
$inputfields->add($f);

$f = $modules->get('InputfieldText');
$f->attr('name', 'test_text');
$f->label = 'Col 2/2';
$f->description = 'Shown only if option 1 is selected.';
$f->columnWidth = 50;
$f->showIf = 'test_select=1';
$inputfields->add($f);
~~~~~~

**Comment by TomS-** [comment]
Hi Ryan,

Apologies, it will be a URL field, does that have any effect?

**Comment by ryancramerdesign** [comment]
I'm not seeing any difference by switching the InputfieldText to an InpufieldURL field. Is it possible you've got some other non-visible Inputfield(s) in-between your select and the URL field? PW will reserve space for non-visible fields by expanding the last visible one.

**Comment by TomS-** [comment]
Ah yeah, the select field switches between two 1/2 fields, however the first 1/2 exists before it. Is there any technical reason why it couldn't display at 1/2? As it will always only display one 1/2 field.

It's not a big issue, just trying to keep the control panel looking neat.

**Comment by ryancramerdesign** [comment]
There have been requests to have an alternate Inputfield rendering option where rows aren't fixed by width (reserving space for non-visible Inputfields), and instead flow according to visible percentages. I think that's the option you would be looking for here. That option is desirable in some cases and not in others. That's something we may have to add as an option for specific cases, and I can support it in AdminThemeUikit, but not sure about the other two admin themes, so I've not dived into it. The goal with AdminThemeUikit has been just to get the Inputfield rendering as consistent as possible with the other two admin themes. Given that, something that should produce the result you want in any admin theme is just to use a width of 25% rather than 50% for your two showIf Inputfields, so that you end up with this in your row: 50% (always visible select), 25% (showIf), 25% (different showIf). The 25% ones will expand to 50% when revealed, since the last visible column always expands to fill out the row. And PW will still identify it as a single row since the total adds up to 100%, meaning it won't try to throw one of them down on the next row, and you should always see it as 50% 50%, so long as the two showIf columns aren't visible at the same time.

**Comment by TomS-** [comment]
Thanks Ryan! I think 25% and 25% will work for me in this case. Shall I leave this open to keep track of the alternative input rendering or shall I close it?

**Comment by ryancramerdesign** [comment]
Thanks. It's okay to close it. There's already another issue or request
open where the idea was brought up.
