### ISSUE TITLE
Replace "getcwd()" with "dirname(realpath(__FILE__))"

### ISSUE THREAD

**Issue by processwired** [processwire/processwire-issues#632]
I have difficulties to run ProcessWire with a cron job on a Linux server properly. I was puzzled because I was getting warnings like "PHP Warning: chdir(): Permission denied (errno 13) in /var/www/web/wire/core/TemplateFile.php:305".

 It turned out that getcwd() used in wire/core/ProcessWire.php and wire/core/TemplateFile.php does not always give a consistant behaviour - in my case, it returned the "/root"-directory, which is certainly not writable by Apache and thus results in the warning.

Usually it's better to use "dirname(realpath(__FILE__))" as a drop-in replacement. See [more info at stackoverflow](https://stackoverflow.com/questions/13103083/how-do-i-push-to-github-under-a-different-username).

Maybe it's a good idea to replace getcwd() completely? It's just used three times at all in the code base.

* ProcessWire version: 3.0.107

**Comment by ryancramerdesign** [comment]
The getcwd() is there so that ProcessWire can return to the directory it was executed from. It does not matter if that directory is writable. It doesn't do anything with that directory other than return to it once finished running. This is a matter of good housekeeping for anything that can be executed from the command line, or anything that can be included as an API from another application (ProcessWire accommodates both). It might even be crucial that it does so, depending on the case. 

Maybe I don't understand exactly what you mean, and the stackoverflow link you posted doesn't seem to have any info about this as far as I can tell? But the "dirname(realpath(__FILE__))" is not a drop-in replacement for getcwd() because that would return the path of the currently executed file (like /wire/core), not the directory ProcessWire was originally executed from. They are very different things.

For your cron job, it sounds like it's executing from /root/ and whatever user cron runs as does not have permission to open that directory. So you'd ideally want your cron job to start from a directory that the cron process at least has open "rx" permissions to (maybe /tmp/ or your web root?) However, the warning you get is likely inconsequential, as in your case, unless you are running other commands after ProcessWire, it probably doesn't matter if it returns to that directory or not.

**Comment by netcarver** [comment]
@processwired I've looked at the stack overflow thread you linked to, and it doesn't appear related to replacing _getcwd()_ with _dirname(realpath(FILE))_. Are you sure you posted the right link? If so, please can you point me to information on that page that we should be looking at.

Also, have you had a chance to consider if Ryan's suggestion is of any use to you?

**Comment by netcarver** [comment]
@processwired Could you please review the two comments above and see if that allows you to progress your issue.
