### ISSUE TITLE
touch() in FileCompiler fails due to PHP process not being the owner of the file

### ISSUE THREAD

**Issue by teppokoivula** [processwire/processwire-issues#635]
### Short description of the issue

It seems that when FileCompiler updates compiled files that were originally created by another user, owner of said files doesn't change, and thus [subsequent touch() fails](https://processwire.com/talk/topic/14825-error-on-new-server-warning-touch-utime-failed/?do=findComment&comment=133045). This, in turn, can result in other issues – such as in my case, where a PHP warning is triggered during the execution of a cron script, where it's common practice to raise an alert for any unexpected output.

In my case the original (compiled) file was created by the Apache user when ProcessWire was initiated via HTTP request (PHP running as the Apache user), and the subsequent request was initiated by bootstrapping ProcessWire as another local user (PHP is running as said local user).

### Expected behavior

No PHP warnings should be raised in this situation.

### Actual behavior

Following PHP warning is raised:

```
PHP Warning:  touch(): Utime failed: Operation not permitted in /path/to/wire/core/FileCompiler.php on line 1120
```

Specific row numbers I've seen so far in error messages are 391 and 1120.

### Optional: Suggestion for a possible fix

For the time being I've "fixed" this by suppressing errors from touch() commands in FileCompiler, but that doesn't seem like a good long-term solution.

### Setup/Environment

* ProcessWire version: 3.0.98
* PHP version: 5.5.9

**Comment by ryancramerdesign** [comment]
I think the touch() errors might be a side effect of a file permissions issue, which is a much bigger issue than a PHP warning. If that's the case, I don't think it's good to suppress the touch warnings, because they are just an indicator of a bigger problem. ProcessWire is limited by the permissions it is executed under, so I'm not sure there's anything we can do about this from the PHP side. Though I'm also speculating as to what the issue is since I don't have a live case to look at.

You've got ProcessWire running under two different user processes and permissions that don't allow one to write to the other's? I think this'll be an issue not just for cache files, but anything that gets written on the file system (log files, for example). It's possible that 777 dir/666 file permissions might fix it, but of course that's something you want to avoid unless this is an isolated environment that only you control (or other admins with equal rights). Though personally, I'd want all writable files to be under the same user myself, either way. 

This strategy might be better: ensure that the cron job runs under the same process as apache. For instance, your cron job could hit a private URL with wget or curl to trigger the event(s) you need to run in PW. That way it would still be running under Apache, even if triggered by a different user. I'm guessing there are other ways to make a cron job run under apache, but I don't know much about unix administration.

**Comment by teppokoivula** [comment]
New version of FileCompiler seems to work great. I'll report back if anything new pops up, but so far I'd say that this is resolved.

Thanks again! :)
