### ISSUE TITLE
InputfieldColumnWidths() fires needlessly in AdminThemeUikit

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#638]
### Short description of the issue

Not really a bug but perhaps an opportunity to improve Javascript performance a bit. 

I noticed that a fairly lengthy section of JS code [here](https://github.com/processwire/processwire/blob/dev/wire/templates-admin/scripts/inputfields.js#L645-L893) in the InputfieldColumnWidths() function fires regularly - several times when form markup is loaded, on every show-if change, and on viewport resize. From what I can see this function is not needed in AdminThemeUikit. I removed the code in the function and column widths continued to work normally in AdminThemeUikit. I think the column widths are handled separately in this theme in [main.js](https://github.com/processwire/processwire/blob/411fedf7859e9e6cd11f988d1bbc3cdeea57ced2/wire/modules/AdminTheme/AdminThemeUikit/scripts/main.js).

Maybe InputfieldColumnWidths() should be moved to a separate file that is only included in the admin themes that need it?

### Setup/Environment

* ProcessWire version: 3.0.108

**Comment by rolandtoth** [comment]
Perhaps that's the reason why I feel the uikit admin theme slower than the others.

**Comment by matjazpotocnik** [comment]
I also find AdminThemUikit somehow sluggish, like there is a lot of js processing behind the scene. It's also annoying when top menu (Pages, Setup, etc.) is shown with a delay (or maybe it's just me).

**Comment by ryancramerdesign** [comment]
> I noticed that a fairly lengthy section of JS code here in the InputfieldColumnWidths() function fires regularly - several times when form markup is loaded, on every show-if change, and on viewport resize. From what I can see this function is not needed in AdminThemeUikit. I removed the code in the function and column widths continued to work normally in AdminThemeUikit. I think the column widths are handled separately in this theme in main.js.

This is correct, except that most of the code in InputfieldColumnWidths() is skipped over because AdminThemeUikit adds "InputfieldFormNoWidths" class to all .InputfieldForm elements. That's the class that tells that function that it does not have to manage column widths. So any calls to it amount only to this: `if($form.hasClass('InputfieldColumnWidths')) return;`. The Uikit admin theme is the only one I know of that manages its own column widths, and the InputfieldColumnWidths() function is already built to allow for that, via that class name on the form element. 

> I also find AdminThemUikit somehow sluggish, like there is a lot of js processing behind the scene.

What sort of sluggishness? I haven't noticed anything significant here. Though Uikit is a pretty full featured front-end framework, and the other themes have no framework at all, so there would have to be some difference based on that factor alone, even if I've not personally felt it.  I'm constantly switching between the 3 themes because any time I develop something, I test it in the 3 core themes. Though Uikit is my default theme, and I use the default layout (no sidebars). There is some extra overhead with the sidebar(s) layouts, if using that. My environment is in OS X on a 2013 mbp w/8 gb ram and in Chrome most of the time. What environment are you noticing slowness in? If you can pinpoint any specific issues I'm happy to look at them. There were one or two instances where we had specific cases of slowness (a big table field was one of them if I recall), but those were resolved as they came up.

**Comment by joshuagatcke** [comment]
I have noticed that UIKIT does a ton of repaints and invalidates layout when you move the mouse over the page. The reason for this is some heavy hitting event watchers in the framework. This is the cost for having a "react style" Dom watcher and cannot be avoided in this case. I have noted some performance losses on slower machines directly related to this. But Shouldn't be a big deal or even noticeable on most regular hardware.

**Comment by Toutouwai** [comment]
Closing this, as the early return means the function will have only very minor performance impact.
