### ISSUE TITLE
Why does the Sanitizer::translate beautify option convert to lowercase?

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#643]
### Short description of the issue

Using the `Sanitizer::translate` option converts the string to lowercase

### Expected behavior

I think this should only translate characters, eg. `é` to `e`

### Actual behavior

It converts all characters to lowercase, eg: `Résumés` to `resumes`

Surely the sanitizer method itself (eg pageName) should take care of the lowercase conversion, rather than the beautify option?

Maybe I am missing something though - I haven't looked into this too thoroughly.

**Comment by ryancramerdesign** [comment]
Page names are required to be lowercase, so anything returned by pageName is lowercase. The method description also states that page names are lowercase. The only exception would be if you are using UTF-8 mode and have prepared a whitelist that includes uppercase characters, but in that case you'd probably want to use pageNameUTF8() sanitizer instead. For your case, if you want a similar sanitizer that supports mixed case, then use the regular `$sanitizer->name()` instead.

**Comment by adrianbj** [comment]
Here's another example where I want to translate the `é` character, but I want to keep the uppercase for the templateName which is allowed. How would one cleanly achieve this combination?

![image](https://user-images.githubusercontent.com/871211/43776607-389f1c0a-9a05-11e8-8a41-7dd0b26e876d.png)

**Comment by ryancramerdesign** [comment]
The Sanitizer::translate constant was created for page names. You are using it on sanitizer methods that have nothing to do with page names. That's perfectly fine (and there are use cases), but if it doesn't suit your purpose, then you shouldn't use it. When you do, you are telling it to use the translations definitions specified in InpufieldPageName. Part of the page name format is that it is exclusive to lowercase. All the definitions for the translate constant are in lowercase. So if you need mixed case, then that particular constant is not the one you want to use for the $beautify argument. 

Just use boolean true for the $beautify argument, rather than using a constant for translating page names, on methods that are not for page names. Boolean true for $beautify is designed to work on any method that has a $beautify argument, and it will still translate (assuming iconv is available) and I think is likely to produce the result and mixed case you are looking for.

**Comment by adrianbj** [comment]
Thanks @ryancramerdesign - I had no idea that true would work like that, but it certainly does.

![image](https://user-images.githubusercontent.com/871211/43845995-23176922-9ae2-11e8-839f-5b044fca3755.png)

I still think it's confusing that `Sanitizer::translate` converts to lowercase. You say that it was created for use with page names, but the `pageName` sanitizer already does the lowercase conversion without any beautify argument. I guess I don't understand why `Sanitizer::translate` does it again:

![image](https://user-images.githubusercontent.com/871211/43846193-955b4184-9ae2-11e8-9cea-e218fea79488.png)

**Comment by ryancramerdesign** [comment]
Because the translations it uses are all defined in lowercase. If uppercase characters were present, they would not get converted by the conversion table being asked for with that translate constant. Using Sanitizer::translate tells it specifically to focus on the conversions configured in InputfieldPageName, which has a context of page names—lowercase.

**Comment by adrianbj** [comment]
Thanks for the explanation - I guess I just find it strange that `Sanitizer::translate` works with other sanitizer methods, but not really as I would expect it to work. Good to know that `alpha` with true actually translates `É` to `E` keeping its uppercase status:

![image](https://user-images.githubusercontent.com/871211/43848857-c51ae694-9ae8-11e8-9564-8a67dab4d44d.png)
 
I guess `true` is using iconv rather than the table of replacements configured in InputfieldPageName ?

Anyway, I don't really have a need for this - I was just trying to help make things a little more consistent and semantic - so I'll close this now :)
