### ISSUE TITLE
PageName sanitizer with special characters causing extra hyphens around ampersands

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#644]
### Short description of the issue

![image](https://user-images.githubusercontent.com/871211/42966793-1870c3b8-8b53-11e8-8dd5-3895f72c0bd8.png)

### Expected behavior

I would have thought that you wouldn't need the translate beautifier to result in just one hypen/dash

**Comment by netcarver** [comment]
@adrianbj Hi Adrian. Just want to clarify something: Are you suggesting that "rsums-jobs" is your expected output from line 1 of the example?

**Comment by adrianbj** [comment]
Hi @netcarver - yes, that's correct.

**Comment by ryancramerdesign** [comment]
This looks like the correct output to me. Calling a `$sanitizer->pageName()` with only a value means it is doing nothing but sanitizing. That means removing anything it doesn't recognize, and converting any separations to hyphens. If you want it to perform any kind of beautification, then you have to specify something for the $beautify argument. If you don't specify a $beautify argument, then it is not doing anything to try and make the value pretty, it is simply sanitizing it. In your case, you can also specify boolean true for the beautify argument.

**Comment by adrianbj** [comment]
I just checked this:

![image](https://user-images.githubusercontent.com/871211/43774805-46bc428c-99ff-11e8-84aa-0823e5d64bb5.png)

and was surprised that it also returned the three hyphens. I thought it was related to the other special characters, but apparently not.

I do find it strange that a `pageName` sanitizer doesn't automatically completely return a string which would be used for a page name.

I am seeing other inconsistencies here as well. For example, is there a reason for this:

![image](https://user-images.githubusercontent.com/871211/43775218-d036b550-9a00-11e8-9adf-a9157931db66.png)

Why isn't the beautify argument working for `fieldName` to remove the extra underscores?

**Comment by Toutouwai** [comment]
> I do find it strange that a pageName sanitizer doesn't automatically completely return a string which would be used for a page name.

When you say "would be used for a page name" are you meaning what would occur if you typed the string into InputfieldPageName (or the Title field on the first step of adding a new page)?

Sorry if this is going off topic, but as far as I know there is no $sanitizer method that returns a string that is identical to the conversions done by InputfieldPageName. This is a bit of a problem IMO because it means that you can't reliably work out from the API what page name would result from a given string entered into InputfieldPageName. I think the conversions done in JS by InputfieldPageName should be matched to some API method that delivers identical conversions.

To illustrate, see the difference in the screenshot below:
 
![2018-08-08_101807](https://user-images.githubusercontent.com/1538852/43805579-6da636fa-9af4-11e8-9abb-f7a25ef2f1e8.png)

The point isn't that InputfieldPageName is not converting the macronised "ā" - I know that I could enter character replacement for that in the InputfieldPageName config (although I think that entering a huge list of replacements is not an ideal way for the character conversion to be done - but that's another story). The point is that even with the `Sanitizer::translate` constant `$sanitizer->pageName()` doesn't correctly match the conversion done by InputfieldPageName.

**Comment by adrianbj** [comment]
> When you say "would be used for a page name" are you meaning what would occur if you typed the string into InputfieldPageName (or the Title field on the first step of adding a new page)?

Yes, that is probably what I mean - certainly at least a cleanup of extra hyphens. But I do agree with you that we should have an API option for matching exactly what InputfieldPageName does via JS.

In general I think there are just a few too many inconsistencies in behavior - this one (https://github.com/processwire/processwire-issues/issues/643) is particularly disconcerting in my opinion. Unfortunately I think Ryan misunderstood my initial report - hopefully my more recent comments have helped to clarify the problem.

**Comment by ryancramerdesign** [comment]
The code you are talking about in InputfieldPageName is not a sanitizer. It is a live interactive helper (purely JS) to help during user input. It ensures that what's seen in the field won't need to change again when saved at the server side (except in rare cases), avoiding surprises. 

The server-side $sanitizer, when used with the Sanitizer::translate option, also uses whatever conversions you configured with InputfieldPageName. But if any invalid characters remain in the string after doing that conversion, it also has the ability to use PHP's iconv() functions. That option isn't available on the JS side, because there is no iconv() in JS. But you can benefit from this ability if you are creating pages from the API, like importing, etc. It doesn't come into play for pages created interactively because InputfieldPageName JS already produces a result that will validate without needing server side translation. 

I think we're getting side tracked though. Regarding the topic of this issue report: “PageName sanitizer with special characters causing extra hyphens around ampersands” — to reiterate, if you don't specify any beautify option then it is doing nothing but sanitization of characters. It is not trying to make it pretty in any way. If it was trying to do anything more than sanitize the string, it would potentially break any code that is using the pageName() sanitizer specifically for the purpose of sanitization (rather than conversion or validation). Use the second argument ($beautify) if your intention is to do something more.

**Comment by adrianbj** [comment]
Reality is that the title of this issue is actually incorrect. However, I do think it's confusing that `Sanitizer::translate` removes the extra hyphens though. Surely "translate" should just take of converting characters like `é` into `e` and there should be a separate beautify argument to cleanup the extra hyphens etc.

Still, I'll close this because I don't see you adjusting the behavior that much anyway because there would be too many side-effects for users relying on the current behavior.

I think that @Toutouwai should open another issue / request to discuss working towards having a way to make JS and API generated names match.
