### ISSUE TITLE
ProcessPageAdd gives incorrect warning when page name set in hook

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#648]
### Short description of the issue

If a page name is set in a hook after `Pages::added` then ProcessPageAdd incorrectly gives a warning about the name being changed because it was aleady in use.

### Steps to reproduce the issue

Create the following hook in /site/ready.php:

```php
$pages->addHookAfter('added', function(HookEvent $event) {
    $page = $event->arguments(0);
    $page->name = uniqid();
    $page->save();
});
```

Add a new page under Home, giving it some unique page name that doesn't already exist under Home.

Note the incorrect warning:
![2018-07-25_130908](https://user-images.githubusercontent.com/1538852/43174084-6294f33e-900c-11e8-96f4-0af3f2668b25.png)

Interestingly, even if the last line in the hook is commented out so that the page name is not actually saved in the hook the incorrect warning still occurs.

### Optional: Suggestion for a possible fix

The relevant part of ProcessPageAdd is [here](https://github.com/processwire/processwire/blob/c01289edb7ad650bb635e412b490e8db8fe91989/wire/modules/Process/ProcessPageAdd/ProcessPageAdd.module#L1157-L1162). Maybe instead of this conditional a custom property could be set to $page (e.g. `nameAdjusted`) in the event that the name has been automatically adjusted to avoid a clash, and ProcessPageAdd could check for that property.

### Setup/Environment

* ProcessWire version: 3.0.108

**Comment by teppokoivula** [comment]
Thanks for reporting this issue, @Toutouwai. This has been a bit of a nuisance for a long time, particularly since I seem to be needing this kind of behaviour quite often.

In fact I was sure that I had already reported this, but apparently not :)

**Comment by szabeszg** [comment]
I can also confirm this. In my case I rename usernames and keep getting the warning that they have already been in use which they are not.

**Comment by kongondo** [comment]
Note also it is not just about the warning. It also gives the created page a URL with a unique ID attached to the parent, e.g.:
/home5b622b33107ac/some-unique-name/

Note the integers after *home*.

**Comment by kongondo** [comment]
Ignore my previous comment :-). But yes, I can reproduce...

**Comment by ryancramerdesign** [comment]
As I understand it, the problem is that the "was already in use" part of the warning message is no longer correct, because a 3rd party hook has gone in behind the scenes and manipulated the page's name, changing the conditions of what's expected by an PW core process? This kind of thing should be expected when doing this. But in this case, I think we can add some more options to give you more control over it—I have updated the warning message to be a more general warning that the name changed, rather than giving the reason why it changed. I've also placed that warning in a hook so that you can optionally modify it (or remove it) if you want to.

**Comment by Toutouwai** [comment]
@ryancramerdesign, thanks for looking into this.

> I have updated the warning message to be a more general warning that the name changed, rather than giving the reason why it changed.

Not sure about this as a solution. The previous warning was good, the problem was that the warning was about a specific thing (PW renaming the page due to a name clash with an existing sibling) and it was occurring in situations where there was no name clash and but rather the name had been deliberately changed for a different reason.

So making the warning message broader is one way of dealing with it - now the warning isn't wrong, but it provides less information about the situation it was designed for (i.e. PW's automatic adjustment of page names when they clash with a sibling).

Personally I'd rather have the previous warning but have the test be more specific so it isn't triggered by name changes that aren't related a sibling name clash. And if a name is being deliberately changed in a hook for some reason or other just let the developer decide if the user needs to be notified with a message, warning, etc.

But if others are happy with this solution then I can close the issue. Maybe others who have commented above could chime in?

**Comment by adrianbj** [comment]
> Personally I'd rather have the previous warning but have the test be more specific so it isn't triggered by name changes that aren't related a sibling name clash. And if a name is being deliberately changed in a hook for some reason or other just let the developer decide if the user needs to be notified with a message, warning, etc.

I agree with this for sure.

**Comment by teppokoivula** [comment]
> As I understand it, the problem is that the "was already in use" part of the warning message is no longer correct, because a 3rd party hook has gone in behind the scenes and manipulated the page's name, changing the conditions of what's expected by an PW core process? This kind of thing should be expected when doing this.

Changing the name to avoid a name collision is a valid core use case, and I absolutely get that it's not possible to predict every single workflow change that could've been implemented by hooks, but in my opinion that's also why (both core and third party) modules should avoid assuming that the "regular" workflow applies.

I've been using these hooks on numerous occasions for modifying page names – and judging from the comments here, others are doing the same thing as well. At least in my case most of those situations have been ones where content editors shouldn't be aware that something "out of ordinary" happened. A warning signals that something went wrong, when things in fact worked as expected.

While the current solution already allows us to add another hook to suppress said warning (or set up a custom one if that makes more sense), it seems to add a (possibly?) unnecessary layer of complexity:  when changing page name with a hook during save, in most cases one should also hook into this method. Trivial task for sure, but avoidable and a bit unexpected – at least in my opinion.

Personally I'd prefer delegating the task of keeping track of automatic name adjustments to the core: instead of each piece of code that alters page name checking why the name was changed and then silencing it if the reason seems to be due to adjustName behaviour, it seems that the "clean" solution would involve storing a bit of metadata when this happens and checking for that in ProcessPageAdd.

**Comment by Toutouwai** [comment]
Just adding some code to flesh out my suggested fix in the first post...

In `PagesEditor::savePageQueryException`, after [line 608](https://github.com/processwire/processwire/blob/839d9325cccb44e8bd4931047c8173a7990356e4/wire/core/PagesEditor.php#L608):
```php
$page->nameAdjusted = true;
```

In `ProcessPageAdd::processInput`, replacing [these lines](https://github.com/processwire/processwire/blob/839d9325cccb44e8bd4931047c8173a7990356e4/wire/modules/Process/ProcessPageAdd/ProcessPageAdd.module#L1189-L1192):
```php
if($this->page->nameAdjusted) {
    $this->error(sprintf(
        $this->_('Warning, the name you selected "%1$s" was already in use and has been changed to "%2$s".'),
        $pageName, $this->page->name
    ));
}
```
(and the new method introduced in [this commit](https://github.com/processwire/processwire/commit/683e24e0102d064cc506d9b167932f7b513c5c4a) would not be needed)

**Comment by netcarver** [comment]
/remind me to review this issue in 2 weeks

**Comment by ryancramerdesign** [comment]
@Toutouwai I have added your suggested fix above, though thought the hook might still have potential value at some point (and it's not adding any overhead) so have left that in place.

**Comment by Toutouwai** [comment]
Thanks @ryancramerdesign. Could the default warning message go back to the previous default, which was more descriptive of what has happened?

'Warning, the name you selected "%1$s" was already in use and has been changed to "%2$s".'

**Comment by ryancramerdesign** [comment]
@Toutouwai Sure, I've changed it just . now, and I'll bundle it into whatever is the next commit.

**Comment by matjazpotocnik** [comment]
@Toutouwai wording is changed in this commit: https://github.com/processwire/processwire/commit/fc88d64a031568ab2bf0292b006c520ee1cbc4aa

**Comment by Toutouwai** [comment]
Thanks.

**Comment by adrianbj** [comment]
Hi all - I just came across this again using the latest dev version of PW. I am still getting this warning when I hook into `Pages::saveReady`

Changed page URL name to "xxxxx" because requested name was already taken.

Do I still need to hook into something to prevent this warning?

**Comment by teppokoivula** [comment]
Hey @adrianbj  – based on a quick look at the code, you shouldn't have to.

That warning should only be displayed in case PagesNames::hasAdjustedName() returns `true` for the page in question, and that in turn should only happen if PagesEditor::savePageQueryException() has been triggered.

That being said I'm not particularly familiar with what's actually happening here – that's just based on a cursory glance at the changes here. If you've got a setup where this is currently happening, I'd start by checking if _hasAdjustedName is indeed true at that point for this page, and if so, why.

**Comment by adrianbj** [comment]
Thanks for chiming in @teppokoivula - from a quick look around, it seems like the recent changes only handle ProcessPageAdd. I am hooking into `Pages::saveReady` because I want to update the page name whenever a field on the page is updated.

I get these warnings which users are very confused about:

![image](https://user-images.githubusercontent.com/871211/61494046-0363a400-a96a-11e9-8af7-cdef1bef68a6.png)

@ryancramerdesign - any chance of also applying the `hasAdjustedName` check in this scenario as well?
