### ISSUE TITLE
HTML tags from fields with Markdown textformatter are encoded in Lister

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#651]
### Short description of the issue

If a field has `TextformatterMarkdownExtra` applied and that field is shown in a Lister column, the markdown is converted to HTML tags but those tags are entity-encoded.

![2018-08-01_125939](https://user-images.githubusercontent.com/1538852/43495739-df47f666-958d-11e8-9489-95ed5d395fdf.png)

The expectation is that either the HTML tags from the markdown textformatter are not entity-encoded (best) or that the textformatter is not applied within Lister (not ideal but better than seeing HTML tags in Lister).

I am working around this for now by hooking `FieldtypeText::markupValue`:

```php
$wire->addHookAfter('FieldtypeText::markupValue', function(HookEvent $event) {
    $field = $event->arguments(1);
    $value = $event->arguments(2);
    if(!in_array('TextformatterMarkdownExtra', $field->textformatters)) return;
    $event->return = $value;
});
```

### Setup/Environment

* ProcessWire version: 3.0.108

**Comment by ryancramerdesign** [comment]
This is a tricky one because while it may be okay in this particular instance, we don't want to allow HTML here unless it's entity encoded to make it safe. Markdown can support a mixture of HTML and markdown, and one could populate some malicious markup. Allowing the HTML to pass-through like in the hook you are using would open it up to XSS injection. Lister is doing what it should and encoding the markup to ensure that it is safe. But I understand that output is not ideal in your case. I could have Lister strip markup on the value before entity encoding it, which would at least prevent the encoded HTML tags from appearing?

**Comment by Toutouwai** [comment]
I see what you mean. What would be great would be if Lister (or maybe Fieldtype::markupValue) could check if the Markdown textformatter is applied and if so use $sanitizer->entitiesMarkdown rather than $sanitizer->entities, to allow through only safe HTML. Like the way inputfield descriptions and notes are sanitized.

For a quick test I added the following near the start of the if/else chain where the value is sanitized in ProcessPageLister.module:

```php
// ...
if($field && in_array('TextformatterMarkdownExtra', $field->textformatters)) {
    $value = $this->wire()->sanitizer->entitiesMarkdown($p->getUnformatted($name));
} else 
//...
```

**Comment by Toutouwai** [comment]
My previous idea is no good because getting the unformatted value would remove any other textformatters that might be wanted in the output.

I think it's not something that can be solved in the core. Instead I'll make a new textformatter module that just applies $sanitizer->entitiesMarkdown (I only ever need strong and emphasis anyway) and then use a `FieldtypeText::markupValue` hook similar to the one above since I know the formatted value will be safe.
