### ISSUE TITLE
Create new template doesn't note allowed characters

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#657]
### Short description of the issue

When you go to create a new template it doesn't tell you what characters are allowed

### Expected behavior

There should be a note explaining what characters are allowed

### Actual behavior

No note :)

### Optional: Screenshots/Links that demonstrate the issue

Your screenshots/links go here.
![image](https://user-images.githubusercontent.com/871211/43776191-e9722f92-9a03-11e8-8466-fee511d08001.png)

### Optional: Suggestion for a possible fix

Match the note that is shown when you go to rename a template

![image](https://user-images.githubusercontent.com/871211/43776226-0a40edc6-9a04-11e8-9f56-1b1b6b620b29.png)

Actually, I am a little confused about the requirements for a template name. The note shown when renaming suggests lowercase only because of `(a-z)` rather than `(A-Za-z)`. It seems that uppercase are allowed, but not specified in this note.

**Comment by ryancramerdesign** [comment]
Thanks @adrianbj I have updated this to clarify what characters are allowed. `-_a-z-A-Z0-9` are the characters that are allowed, but lowercase is preferred. That's because template names map to filenames, and PW runs on servers that may or may not have case sensitive file systems. Technically periods are also supported in template names (backwards compatibility), but not recommended, and thus I don't include those in the the notes about allowed characters.
