### ISSUE TITLE
AdminThemeUikit: selects have 100% width when inputfield has column width

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#662]
### Short description of the issue

Generally select inputs have had an "auto" width. Screenshots below of select in AdminThemeUikit when column width is 100%, and AdminThemeDefault when column width is less than 100% (and AdminThemeReno is the same).

![2018-08-10_100201](https://user-images.githubusercontent.com/1538852/43928383-cf8deade-9c84-11e8-802d-44387f7b0f45.png)

![2018-08-10_100056](https://user-images.githubusercontent.com/1538852/43928394-d923297e-9c84-11e8-9279-e7698f345b50.png)

But in AdminThemeUikit if the inputfield has a column width of less than 100% the select is shown at 100% width. 

![2018-08-10_100119](https://user-images.githubusercontent.com/1538852/43928385-d267c478-9c84-11e8-8661-e1d99b093926.png)

This looks off to me. Could selects stay at auto width regardless of inputfield column width, as per AdminThemeDefault and AdminThemeReno?

AsmSelect does not have this issue in AdminThemeUikit and always has auto width regardless of inputfield column width.

### Setup/Environment

* ProcessWire version: 3.0.109

**Comment by ryancramerdesign** [comment]
When we switched to the Uikit selects, I noticed the default Uikit behavior for the select elements was for them to be 100% width, so that's the standard of the framework. I thought that was undesirable in almost all cases when columnWidth settings weren't being used, so I adjusted that so that they are auto width when not already constrained by a column width. While we certainly could make them all auto width, I wanted to delegate to the framework behavior as much as possible where we could. I also thought it looked better in most of the multi-column layouts I tested in, since the text fields already default to full width. Also, I seem to recall that there were issues with Uikit selects at auto width not behaving like unstyled selects when it came to being contained in a small width, and this might be why the Uikit default is to have them be 100%. I'd need to confirm that again though because I don't remember exactly what the issue was.

**Comment by Toutouwai** [comment]
Looking at other front-end frameworks like Bootstrap and Foundation it seems that it's quite common to give selects 100% width by default. I'm not sure what the reason for that is - maybe they just think it looks "tidier"? But Apple/Microsoft have from the beginning given selects auto width by default and I figure there must be a reason for that. I guess it depends whose UX knowledge you defer to.

I think regardless of whether 100% or auto width is preferred it would be good to make it consistent. When a column width is given to an inputfield it doesn't necessarily mean the inputfield will be narrow - 50% width is one that I commonly use and that means the select will almost always be much wider than the option widths on a desktop device.

And on narrower devices the column widths are forced to 100% which results in selects of different widths even though their inputfield containers are rendering at the same width.

Desktop device:
![2018-08-13_110835](https://user-images.githubusercontent.com/1538852/44007427-55d71d70-9ee9-11e8-97eb-4eaab33f8665.png)

Narrower device:
![2018-08-13_110855](https://user-images.githubusercontent.com/1538852/44007432-5dd3d946-9ee9-11e8-89c7-1f48a6f47b55.png)

Maybe rather than the select width being dependent on the column width it could be dependent on the viewport width? So selects have auto width generally but 100% width on mobile devices?

**Comment by netcarver** [comment]
@Toutouwai Robin, can this be closed now?

**Comment by Toutouwai** [comment]
Okay, I will close and adjust this locally to my tastes.

```css
/* Select - auto width on desktop, 100% width on mobile  */
.Inputfield.InputfieldColumnWidth>.InputfieldContent .uk-select:not(.InputfieldSetWidth) { width:auto; }
@media screen and (max-width:767px) {
    .uk-select { width:100% !important; }
}
```
