### ISSUE TITLE
Multilanguage fields don't show value for default language

### ISSUE THREAD

**Issue by tobaco** [processwire/processwire-issues#668]
### Short description of the issue

When using multilanguage fields and a multilanguage backend (users can select the preferred language for editing), the fields don't display the value of the default language and instead show always the other language. If I switch my profile to the default language, everything works as expected.
See the screencast for a better understanding.

### Expected behavior

The fields should display the correct value for the language.

### Actual behavior

The fields always display the same values for all languages.

### Screencast that demonstrate the issue

https://cl.ly/0E261s0L0d0k

### Steps to reproduce the issue

1. Set up a multilanguage installation
2. Switch language in user profile

### Setup/Environment

* ProcessWire version: 3.0.110
* PHP version: 7.1
* MySQL version: 5.6.38
* 3rd party modules:
  AdminOnSteroids
CronjobDatabaseBackup
FieldtypeAssistedURL
FieldtypeEmailLanguage
FieldtypeFieldsetGroup
FieldtypeFunctional
FieldtypeImageMarker
FieldtypeRepeaterMatrix
FieldtypeTextareas
FieldtypeURLLanguage
GeneralSettings
ImageFileDependencies
ImportExternalImages
InputfieldAssistedURL
InputfieldFunctional
InputfieldImageMarker
InputfieldRepeaterMatrix
InputfieldSelectize
InputfieldSelectizeMultiple
InputfieldTextareas
JqueryDataTables
JquerySelectize
MarkupMenuBuilder
MarkupSEO
MarkupSitemapXML
ModuleReleaseNotes
ModuleSettingsImportExport
ModulesManager
PageCleanEmptyDirs
ProcessAdminActions
ProcessDatabaseBackups
ProcessGeneralSettings
ProcessMenuBuilder
ProcessSetupPageName
ProcessWireUpgrade
ProcessWireUpgradeCheck
SchedulePages
TextformatterSrcset
TextformatterSuperSmartypants

**Comment by ryancramerdesign** [comment]
@tobaco I can't duplicate that issue here. You've got a lot of 3rd party modules installed, and I'm wondering if one of them might be interfering somehow. Because there are a lot, rather than uninstalling them, it might be simpler to test from a default multi-language install as included with PW. Also, since the switching is handled by JS, another possibility is that there is some JS error—do you see anything in your JS console?

**Comment by adrianbj** [comment]
> rather than uninstalling them

Don't forget that Tracy has a Module Disabler panel that makes this really easy for testing possible module conflicts. Definitely a good first step to try this.

**Comment by tobaco** [comment]
@ryancramerdesign 

I don't know if this is useful for narrowing down the problem, but I tried to debug this issue with Tracy and found out, that the unformatted value of a field is always blank in the default language:

*user language = en*
![bildschirmfoto 2018-09-26 um 09 43 20](https://user-images.githubusercontent.com/68937/46064899-f5d9f500-c170-11e8-9a61-3e13a342e411.png)

*user language = de*
![default is blank](https://user-images.githubusercontent.com/68937/46064643-3d13b600-c170-11e8-9d81-9ceef218c05f.png)

Is this the right behaviour?

Thanks!

**Comment by ryancramerdesign** [comment]
The value of "default" definitely shouldn't be blank, as your first screenshot shows it populated with "About Us", so that's what should also appear elsewhere. So it must be getting lost somewhere, but that's a mystery so far. I did just try to duplicate here again, but still not seeing it. Since other modules are now uninstalled, I'm wondering if you can check if you've got any hooks present in /site/ready.php, /site/init.php or /site/templates/admin.php ? Also, might be worth trying to duplicate from the default multi-language profile just as a test, which would tell us if it might be something site specific.

**Comment by szabeszg** [comment]
I have a site with a very similar issue, except that in my case it does not matter what language is set in the user profile, the tabs do not work at all. "Languages Support - Tabs" is unable to switch to the default languge so I had to disable it and that way I can populate both inputs.

Note that my default language is not English but "Magyar" as seen in the screenshot:
![pw-languages-list](https://user-images.githubusercontent.com/7194945/53488675-4a223180-3a8f-11e9-8b79-6c2c5027f35e.png)

I cannot see any JS errors in the Console and it does not matter which admin theme I use.

@ryancramerdesign if it helps, I can send you the whole site zipped up. It is an almost empty site (regarding content data) as I have just started working on it.

**Comment by szabeszg** [comment]
I have just bumped into this forum topic:
https://processwire.com/talk/topic/20165-language-tabs-messy-after-upgrade/

> ...changing the order of the language pages in Admin > Setup > Languages caused the problem... As soon as I moved the default languag﻿e (english) back to the first position, the ta﻿bs looked ok again.﻿ 

I also changed the order and the tabs do work again. Note that in my case the layout did not change and looked perfectly ok, it was only the click event which did not result in switching the tabs. It is PW 3.0.126 BTW.

Another thing to note that I do not remember changing the order before. I think in my case I got the reversed order because of the way I initially setup the languages, I am not sure though as I did it months ago.

**Comment by ryancramerdesign** [comment]
@szabeszg Just to confirm, you've determined that the issue only appears if you change the order of the languages so that the default language is not first? It's true that the default language is supposed to be first (since it is the default), but I didn't realize it was required. I can look into see if I can change the need for that, but just wanted to double check that I was understanding right first?

**Comment by szabeszg** [comment]
> Just to confirm, you've determined that the issue only appears if you change the order of the languages so that the default language is not first?

Yes, this is what I was experiencing (note that I did no do extensive testing whatsoever).

> I can look into see if I can change the need for that

Thank you! If it cannot be done, as a last resort preventing the order change with additional message if someone tries to do it could also be an option, I guess.

**Comment by ryancramerdesign** [comment]
@szabeszg @tobaco I think I tracked down the issue here in the commit referenced above. Can you confirm it also fixes the issue for you? Thanks.

**Comment by tobaco** [comment]
@ryancramerdesign 

Sorry, I didn't had the time to pursue the issue further, as it happens in only of my installations and the project is done (apart from this issue) and other projects are waiting.

But I just updated my local version of this project with the newest PW-dev-version and my issue is still there.  😕

I think the issue @szabeszg is seeing, is not related to mine. But if it's fixed for him, you can close this issue. If i ever see my problem again, I will report back.

Thanks!

**Comment by szabeszg** [comment]
> Can you confirm it also fixes the issue for you? Thanks.

Thanks Ryan, the fix solves the issue I was having.

**Comment by netcarver** [comment]
@tobaco Hi Torsten. Please go ahead and close this issue; if you close it, you will be able to open it again should you hit the problem again.
