### ISSUE TITLE
Image sizer resizes image when it is already at the requested size

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#678]
### Short description of the issue

Suppose you upload an optimised image at a particular size: 1600 x 1000 pixels.
If you request the image at that size...

```php
$url = $page->image->size(1600,1000)->url;
```
...no resizing should take place because none is necessary - you should receive the original uploaded image data.

But PW does resize the image, which results in poorer image quality and can result in a larger file size than the original. Setting upscaling to false in `$config->imageSizerOptions` or in an `$options` argument has no effect on this issue, but I think it should because the intention for people setting upscaling to false is to avoid the unnecessary resizing of images that will only lose quality.

This is particularly problematic in scenarios where you are uploading a pre-optimised image that does not need resizing but still want to give users the option to replace that image with another which may need resizing.

### Expected behavior

Image sizer only resizes images that are requested at a different size than the original. Or at least an option to make that so - perhaps via the upscaling option.

### Actual behavior

Images are resized when requested at the dimensions of the original image.

### Setup/Environment

* ProcessWire version: 3.0.110

**Comment by horst-n** [comment]
This is not a bug, this is intended! 
Because the intended way to use original images for creation of variations is to NOT upload optimized images. You have to upload images in the best quality you can. Therefor, when requested an image in the equal dimensions, it has to be recreated so that the (default) quality settings get applied. If you look at the code, you also will see that in this cases any sharpening setting is disabled.
So, to take it from the other side: If you upload optimized images as source to generate variations from it, this is plain wrong. This will result in pour variations with to high filesize everytime.
If you want to upload optimized images and use them as originals, you have not to use resize methods but to call them simply by their urls!

**Comment by szabeszg** [comment]
> If you want to upload optimized images and use them as originals, you have not to use resize methods but to call them simply by their urls!

I agree. When using a resize method, I expect ProcessWire to always deal with it in the same way no matter what dimensions are set as parameters.

**Comment by horst-n** [comment]
@szabeszg  To be true, in the early days, when I started enhancing the imagesizer, I first forgott to recreate a variation with applied default settings. Instead I had done what @Toutouwai suggested: I served the unmodified original image, what raised multiple reports and requests to change it the way it is now. :)

**Comment by netcarver** [comment]
@horst-n If I've labelled this incorrectly just let me know.

**Comment by Toutouwai** [comment]
I take your point, thanks.

I still think there are valid use cases for "resize if needed", but this can easily be done in a method added by a hook rather than supported by the size() method. I'll share my solution in the forums later on.
