### ISSUE TITLE
DirectoryIterator error in ProcessLanguageTranslator

### ISSUE THREAD

**Issue by karltdev** [processwire/processwire-issues#679]
### Short description of the issue

Fatal error caused by DirectoryIterator inside module [ProcessLanguageTranslator](https://github.com/processwire/processwire/blob/master/wire/modules/LanguageSupport/ProcessLanguageTranslator.module#L662). This happends when "Find Fils to Translate" button is clicked in Language edit page.

### Optional: Suggestion for a possible fix

The error is caused by the complex file structure or too long file name I guess. I tried to debug and found that the issue is due to many nested the sub-directories inside node_modules folder which I placed inside /site/templates folder.
`Example: site\templates\node_modules\npm\node_modules\libnpmhook\node_modules\npm-registry-fetch\....`

 I managed to fix this error by adding a try and catch block wrapping the DirectoryIterator.

### Setup/Environment

* ProcessWire version: 3.0.106

**Comment by ryancramerdesign** [comment]
I can't duplicate it here, but I think it might be that I don't have your environment and that deep of directory nesting. However, since you already indicated what fixed it, I have gone ahead and added that try/catch you mentioned. Note that further down in the same function there's also a max directory nesting number (currently 20) and manipulating that to a smaller number might also resolve it.

**Comment by somatonic** [comment]
An issue with the current code to check $dirIterator

if(!$dirIterator) return array();

is that it throws and fatal error in PHP 5.5-5.6. It cannot convert a object to a bool...

**Comment by netcarver** [comment]
Thanks @somatonic. Re-labelling this as work-in-progress.

**Comment by matjazpotocnik** [comment]
https://processwire.com/talk/topic/20939-cant-find-files-to-translate-returns-object-of-class-directoryiterator-could-not-be-converted-to-boolean-error-solved/

**Comment by netcarver** [comment]
@matjazpotocnik Thank you, adding the "includes suggest fix" label.

**Comment by ryancramerdesign** [comment]
It sounds like this one is due to a PHP bug, but a really strange one. The suggested fix in the linked thread actually breaks the method entirely, but I got the gist of it and made it `if($dirIterator === false) return array();` instead. That should force those buggy PHP versions to enforce a boolean type check on the variable first.

**Comment by matjazpotocnik** [comment]
The link I provided was not meant to be a suggested fix, it was just to confirm that Soma isn't the only one affected by this bug. But this is not important, what matters is that it's fixed. Thank you.

**Comment by netcarver** [comment]
@matjazpotocnik My mistake then - I thought you were suggesting a fix there :)

**Comment by netcarver** [comment]
Closing this now. Please post more if this proves premature.
