### ISSUE TITLE
The folder /site/assets/cache/WireTempDir/.ProcessModuleInstall is never deleted

### ISSUE THREAD

**Issue by matjazpotocnik** [processwire/processwire-issues#704]
### Short description of the issue
When you install or upgrade a module, the folder _/site/assets/cache/WireTempDir/.ProcessModuleInstall_ is created. After module installation, the temporary folder should be deleted in my opinion, or at least I think this is intended? Instead, I get a log entry

"Unable to remove: C:/inetpub/wwwroot/site/assets/cache/WireTempDir/.ProcessModuleInstall/" in _/site/assets/logs/wire-temp-dir.txt_. 

Error message is issued in WireTempDir.php in line 290 when calling $this->rmdir() method. The folder is not deleted as rmdir() is returning false if there is no .wtd file present in .ProcessModuleInstall folder.

And while there, in rmdir() method this line:

`$dir = rtrim($dir, "/\\") . DIRECTORY_SEPARATOR;`

should (in my opinion) be:

`$dir = rtrim($dir, "/\\") . "/";`

as $dir contains all forward slashes.

And in WireFileTools.php in rmdir() method, this:

```
$files = @scandir($path);
if(is_array($files)) foreach($files as $file) {
    if($file == '.' || $file == '..') continue;
    ...
```
could be simplified:

```
$files = array_diff(@scandir($path), array('.', '..')); // array_diff removes . and ..
if(is_array($files)) foreach($files as $file) {
   //if($file == '.' || $file == '..') continue; this line not needed
    ...
```

### Expected behavior

The mentioned folder should get deleted.

### Actual behavior

The mentioned folder is not deleted.

### Steps to reproduce the issue

1. Delete /site/assets/cache/WireTempDir
2. Install any module
3. /site/assets/cache/WireTempDir/.ProcessModuleInstall is created, but not deleted
4. Create (empty) .wtd file in /site/assets/cache/WireTempDir/.ProcessModuleInstall 
5. Again, install any module and observe that /site/assets/cache/WireTempDir/.ProcessModuleInstall is deleted (WireTempDir is also deleted)

### Setup/Environment

* ProcessWire version: 3.0.111

**Comment by ryancramerdesign** [comment]
I'm not seeing this particular issue on any of my installations. Though they are all on unix, so I'm wondering if it might be isolated to windows. Perhaps a slash that needs to be a DIRECTORY_SEPARATOR constant? It's not a problem if an empty .ProcessModuleInstall directory sticks around, as it's not a one time use thing and can be reused. What I'd be concerned about though is if it's leaving files in that directory—are you finding that it's leaving files in there?

**Comment by matjazpotocnik** [comment]
I'm not sure if it's Windows related or not as php handles forward and backward slashes without a problem. Are you saying that you don't get the warning in wire-temp-dir.txt? I have no problem if .ProcessModuleInstall directory sticks around, but then why you try to delete it? It's not a big deal after all.

**Comment by adrianbj** [comment]
On MacOS and I have lots of empty folders there as well:

![image](https://user-images.githubusercontent.com/871211/45933617-63094280-bf45-11e8-846d-f2fe18b07ba9.png)

**Comment by ryancramerdesign** [comment]
It's not unusual to see temporary directories in cache/WireTempDir/, but you shouldn't be seeing errors in wire-temp-dir.txt log file. So I think there is some issue there, but appears to be Windows-specific (?), as I'm not observing it here. It's no problem if the .ProcessModuleInstall directory sticks around, so long as it's not abandoning files within it. I will try and figure out why the error message is getting reported and see if we can prevent it from doing so.

**Comment by adrianbj** [comment]
> It's not unusual to see temporary directories in cache/WireTempDir/

I have dirs in there from a year ago. Not the end of the world, but is there a reason they are not cleaned up when they are finished with?

**Comment by ryancramerdesign** [comment]
@adrianbj Most likely an Exception occurred or execution halted or something. It could also be that something removed the ".wtd" file from the directory independently of WireTempDir. If there's no .wtd file in a directory, WireTempDir won't touch it. That's because it creates a .wtd file in any directory that it creates, so that's how it knows what it owns. 

It's okay to remove the WireTempDir directory entirely to empty it (it'll get re-created automatically). But if you continue to see those directories within it getting created and remaining, despite no Exception or something halting execution, let me know. Maybe there's another issue within that needs a look. On the site I'm working on right now, I see six .PFM directories that look like they should have been deleted, so going to watch this.

**Comment by adrianbj** [comment]
Thanks Ryan, the .wtd file is still in place.

I'll remove the entire directory and see how's thing progress from now on.

**Comment by matjazpotocnik** [comment]
It's a case (A). Some logs inside various functions:

```
2018-09-18 17:03:09	admin	http://localhost/processwire/module/	inWireTempDir->mkdir: created C:/inetpub/wwwroot/site/assets/cache/WireTempDir/.ProcessModuleInstall/0\.wtd time=1537282989
2018-09-18 17:03:09	admin	http://localhost/processwire/module/	inside rmdir, dir=C:/inetpub/wwwroot/site/assets/cache/WireTempDir/.ProcessModuleInstall/0/, recursive=1
2018-09-18 17:03:09	admin	http://localhost/processwire/module/	inside rmdir, unlinking file C:/inetpub/wwwroot/site/assets/cache/WireTempDir/.ProcessModuleInstall/0\.wtd
2018-09-18 17:03:09	admin	http://localhost/processwire/module/	inside rmdir, calling files->rmdir with C:/inetpub/wwwroot/site/assets/cache/WireTempDir/.ProcessModuleInstall/0\, return status = 1
2018-09-18 17:03:09	admin	http://localhost/processwire/module/	calling rmdir C:/inetpub/wwwroot/site/assets/cache/WireTempDir/.ProcessModuleInstall/
2018-09-18 17:03:09	admin	http://localhost/processwire/module/	inside rmdir, dir=C:/inetpub/wwwroot/site/assets/cache/WireTempDir/.ProcessModuleInstall/, recursive=1
2018-09-18 17:03:09	admin	http://localhost/processwire/module/	Unable to remove (A): C:/inetpub/wwwroot/site/assets/cache/WireTempDir/.ProcessModuleInstall/
```

I think the problem is that .wtd file is deleted (unlinked) and next call to rmdir() is returning false causing the error message in the log.

**Comment by ryancramerdesign** [comment]
@matjazpotocnik Thanks for the log. This helped me to see what's going on. I'm thinking now the issue is the recursive mkdir() calls. Since it relies on `$files->mkdir()` to execute the recursive part, the .wtd files don't get created when it has to go recursive, except in the last part of the created path. And looking closer at that .ProcessModuleInstall directory, that's not going to get created unless you are installing modules using the admin tools. I rarely install modules that way, which explains why I wasn't seeing it. I'm working on a fix here now.

**Comment by ryancramerdesign** [comment]
@matjazpotocnik I've pushed a fix for the issue. Please let me know if it clears things out properly there. Thanks.

**Comment by matjazpotocnik** [comment]
@ryancramerdesign thanks for digging into this. .ProcessModuleInstall folder is now removed, WireTempDir is left behind with .wtd file (as expected), but in the log there is now:

`2018-09-28 21:31:09	admin	http://localhost/processwire/module/	Unable to remove (A): C:/inetpub/wwwroot/site/assets/cache/WireTempDir/`

**Comment by gingebaker** [comment]
Hi guys.
I have the same problem as stated in Matjaž last comment above on my pw 3.0.118 running on a linux system (php 7.0.32).

`Unable to remove (A): ..... /site/assets/cache/WireTempDir/`

This is happening around the time this fix was applied:
https://github.com/processwire/processwire/commit/42ec0e3cf4091a452344ad29057a9ddf478ad287

In my case I create a custom temp path:
```php
$tempPath = $this->files->tempDir("used-vehicle-pdf");
```
This calls the WireTempDir::remove() after it is destructed.
In the remove() method WireTempDir::removeExpiredDirs() is called two times and one time from the !$classRuns if clause here: 
https://github.com/processwire/processwire/blob/dev/wire/core/WireTempDir.php#L223

This is the one call where ::removeExpiredDirs() tries to delete the /site/assets/cache/WireTempDir/ directory in my case, because there are no subdirs in it anymore.
( https://github.com/processwire/processwire/blob/dev/wire/core/WireTempDir.php#L279 )

BUT, the call of the rmdir() method fails, because of this line:
```php
if(!$this->isTempDir($dir)) return false;
```
This happens due a string comparison in WireFileTools::fileInPath()
https://github.com/processwire/processwire/blob/dev/wire/core/WireFileTools.php#L1306

I have to say I don´t know if this is desired behaviour to not delete the rootTempDir, but at least the Log Entry should not be there, because the RootDir can never be deleted... or am I missing something?

On my site I am heavily using the tempDir in my custom code. Because this temp files are often recreated, I get a big number of these log entries every day.

Thanks for any informationen.

**Comment by Sebiworld** [comment]
I stumbled over @gingebaker 's issue as well. Multiple of our instances of ProcessWire have a log "Wire-temp-dir" where these "Unable to remove (A): "-Logs show up regulary.

We use the tempDir-function for our custom functions as well. Regulary we create a custom temp-folder, generate data in it and then save it to a page. After this the temp-folder will be automatically removed via __destruct.

I think, manipulating the `WireTempDir->isTempDir()` - function would be the easiest fix, if the deletion of `site/assets/cache/WireTempDir/` is intended:
```php
	protected function isTempDir($dir) {
		if(!strlen($dir) || !is_dir($dir)) {
			// if given a non-directory return false
			return false;
		} else if($this->classRoot && $this->wire('files')->fileInPath($dir, $this->classRoot)) {
			return true;
		} else if($this->classRoot && $this->wire('files')->unixDirName($dir) === $this->wire('files')->unixDirName($this->classRoot))){
			return true;
		}
		return false;
	}
```

@ryancramerdesign Should the directory `site/assets/cache/WireTempDir/` be removed if it is empty?

**Comment by matjazpotocnik** [comment]
Even with this change, I get:
```
2018-11-21 14:59:53	admin	http://localhost/processwire/module/download/	Unable to remove temp dir: C:/inetpub/wwwroot/site/assets/cache/WireTempDir/.ProcessModuleInstall/0/
2018-11-22 04:57:09	admin	http://localhost/processwire/module/download/	Unable to remove temp dir: C:/inetpub/wwwroot/site/assets/cache/WireTempDir/.ProcessModuleInstall/1/
2018-11-22 04:57:09	admin	http://localhost/processwire/module/download/	Unable to remove (B): C:/inetpub/wwwroot/site/assets/cache/WireTempDir/.ProcessModuleInstall/0/
```

**Comment by matjazpotocnik** [comment]
I added `$pathname = str_replace("//", "/", $pathname);` after `$pathname = "$path/$file";` and together with Sebiworld now I don't get any errors in log file. I don't mind if WireTempDir is deleted, but not sure if this is what Ryan wants...

**Comment by ryancramerdesign** [comment]
I think the original intent was to remove WireTempDir, but looking at our usage now I think it's best that it leaves the root WireTempDir in place. I've pushed a couple of updates that I'm hoping might correct the issue. That's a good find in WireFileTools::rmdir(), thanks I've corrected that.

**Comment by matjazpotocnik** [comment]
Thanks. While I haven't tested it yet, it looks like it will solve the issue with rmdir(), but I find it rather odd calling rtrim() in a foreach loop, on a variable that doesn't change inside the loop. This is why I put rtrim just before scandir function.

**Comment by gingebaker** [comment]
Hi. I tested version 3.0.120 on my installation where I got these log messages before.
The log messages are gone. Everything works as expected. Thank you!

**Comment by netcarver** [comment]
@matjazpotocnik Can this be closed now?

**Comment by matjazpotocnik** [comment]
While I think this is fixed, I would like to see it fixed in a more performant way that's why I left it open. Please see comments at https://github.com/processwire/processwire/commit/fcc353bc3cb4ebb3b38de5d89f220ddd7dab937c#comments

**Comment by netcarver** [comment]
@ryancramerdesign Ryan, would you consider the comments there from Teppo and Matjaž in the above link, I think a small edit is all that is keeping Matjaž from closing this issue. Thank you!

**Comment by netcarver** [comment]
/remind me to review this in 1 week

**Comment by adrianbj** [comment]
Just a follow that after deleting those files, I haven't seen any new ones appear, but perhaps an exception or similar might result in others being kept?

**Comment by ryancramerdesign** [comment]
@netcarver Moving the trim() out of the loop is fine, though would be micro optimization, as in it will never result in any measurable difference. While I agree with it, it's not worth ongoing messages, and another change and commit. However, the linked message referred back to this thread where the suggestion was trimming both forward and back-slashes, so that seems more consequential. But I'm not sure if that's what's being requested?

**Comment by teppokoivula** [comment]
For the record, I agree with Ryan here – it's a very minor detail.

While I somewhat disagree with the conclusion (in my opinion moving a single line is such a trivial change that replying here probably took longer than it would've taken to fix it, and even if it's trivial it's also so obvious that I would rather prefer not seeing it left in the core), I would like to see this issue put to rest unless there are other problems here.

That being said, I'm not sure what linked message we're talking about here :)

**Comment by matjazpotocnik** [comment]
I also agree with Ryan and Teppo that it's micro-optimization. My simple tests (that also include array_diff call, that's more important) show a gain of 0.02 seconds on wire folder, containing 1811 files and 234 folders.

But, I also wonder why there is so much talk about that rather than just fixing it. It's not just about microseconds, it's about the code quality too. But, if Ryan is satisfied with that, I/we also have to be satisfied.
