### ISSUE TITLE
$sanitizer->filename() does not match the sanitizing done by InputfieldFile/InputfieldImage

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#705]
### Short description of the issue

`$sanitizer->filename()` allows periods within the filename, but InputfieldFile and InputfieldImage replace periods with underscores. I expected `$sanitizer->filename()` to produce the same result as a file uploaded to a field.

![2018-09-19_152640](https://user-images.githubusercontent.com/1538852/45729493-c717c800-bc20-11e8-900d-496d210bd2df.png)

Is it safe to add files with periods in the names to file and image fields using the API? I know a period is used in the filename of image variations - will additional periods cause any issue there?

If periods are not okay in filenames then of course `$sanitizer->filename()` should not allow them, but if they are okay then perhaps InputfieldFile/InputfieldImage should use `$sanitizer->filename()` and not replace periods?

### Setup/Environment

* ProcessWire version: 3.0.113

**Comment by ryancramerdesign** [comment]
The `$sanitizer->filename()` is a general purpose filename sanitizer. Pagefile/Pageimage files use a built-in, specific purpose filename sanitizer. We don't allow periods in original-name portion of the Pagefile/Pageimage names because the period is used to separate the original name from meta-data in the filename (like what we use for variation dimensions on images). Pagefile/Pageimage files that lack meta data likewise must lack the period. Of course, the resulting the Pagefile/Pageimage format can still be sanitized by `$sanitizer->filename()`. But since Pagefile/Pageimage are the only files in PW that isolate name from meta data with a period, there's no reason for the general purpose filename sanitizer to impose that restriction everywhere else. Plus, if it did, then the resulting filenames created by Pagefile/Pageimage would be broken by `$sanitize->filename()`.

**Comment by Toutouwai** [comment]
Okay, understood, thanks. 

Maybe at some point there could be a sanitizer method to prepare filenames to the standard used for a Pagefile? Personally I'd find that more useful in the majority of cases than the existing filename sanitizer.
