### ISSUE TITLE
No way to allow space characters in URL segments

### ISSUE THREAD

**Issue by weberhofer** [processwire/processwire-issues#720]
### Short description of the issue
Currently there is now way to allow space characters in URL segments.

### Expected behavior
All characters allowed in $config->pageNameWhitelist should be useable as part of the URL.

### Actual behavior
Allowing all characters and enabling URL segements for a site cause a 404 error page whenever a space character occurs.

### Optional: Suggestion for a possible fix
There is no technical issue against allowing spaces in URL segments.

* ProcessWire version: 3.0.115
* (Optional) PHP version: 5.6.38
* (Optional) MySQL version: 10.0.35-MariaDB

**Comment by jlahijani** [comment]
+1

**Comment by Klenkes** [comment]
I am struggling with this issue for days...

**Comment by ryancramerdesign** [comment]
The page name format doesn't allow whitespace, regardless of charset/whitelist. URL segments stay consistent with page names in terms of format. You'd instead want to use separators such as "-" or "_" when working with URL paths. If you need input that's part of the URL to contain whitespace, I'd recommend using the query string instead. Query strings using `%20` or `+` to represent the space and that should translate to a literal space in the input value.

**Comment by weberhofer** [comment]
@ryancramerdesign thanks for your accurate work on developing Processwire and for analyzing all the issues so carefully.
I'm using URL segments for downloading files by their name from an external system. The files can by definition contain space characters; my workaround for now is to re-map the file name on a reverse proxy which transforms the filename into a URL parameter which is processed by Processwire.
As I don't really see the reason for not allowing spaces in the segments I have created this ticket. I think that at least this behavior should be documented (maybe on the page which allows the definition of segments): I have defined regular expressions and spent much time on debugging down into processwire's core to find out that it doesn't work...

**Comment by ethanbeyer** [comment]
If you have to have the spaces in the name, you might try something like [Example 2 on PHP's `urlencode()`](http://php.net/manual/en/function.urlencode.php) page. If the filename has a space and that's the only way to map it, your template can receive the input as a GET variable (does it have to be a URL parameter?) and `urldecode()` it to get the filename.

**Comment by weberhofer** [comment]
@ethanbeyer, yes I currently do it via URL/GET parameter, but it would be very nice to directly use spaces in the segment's, too.

**Comment by ethanbeyer** [comment]
Sorry, I reread your comment after I wrote mine and realized I was probably suggesting precisely what you're doing already. My bad!

As this is an edge case, and while it might make your job easier, the fact is that spaces in URLs provide a lot of opportunities for errors depending on browser, web-host, device, etc. The safest way to prevent those errors is by encoding them (which is to say not allowing them). Eventually, spaces being allowed in the URLs (which I'm really yet to see in any web framework, whether it'ss PHP, Python or otherwise) mean other characters need to be planned for as well - which I don't see happening.

It's probably best to continue on the route you're currently on with encoding and decoding.

**Comment by weberhofer** [comment]
@ethanbeyer, you might be right. However it would be good to document it, so that you know, that a regex /[A-Z ]*/ will never match (currenly it silently resulty in an error page whenever a space is in the path)

**Comment by ethanbeyer** [comment]
I think documentation is one of @ryancramerdesign's biggest projects right now as he works on rebuilding the @processwire site. Hopefully this makes it into the docs, too!

**Comment by weberhofer** [comment]
IMHO the exact behavior regarding the space (and possibly some other characters) is not documented. It only tells me about the defaults.

**Comment by netcarver** [comment]
@weberhofer Johannes, can you suggest a paragraph for the documentation that would clarify it?

**Comment by weberhofer** [comment]
@netcarver thanks for taking that up again. I'll suggest to add the following sentence in https://processwire.com/api/ref/sanitizer/page-name/ and https://processwire.com/docs/admin/setup/templates/#which-url-segments-do-you-want-to-allow

"URL segments can never contain whitespaces or slashes."

@ryancramerdesign are there more characters which can never be set to be valid? Maybe question marks or asterisks or stuff like that?

**Comment by ryancramerdesign** [comment]
Regarding slashes and question marks, of course you can already use them in URLs, but they mean specific things already reserved in URLs, unrelated to PW. But when it comes to spaces, I had another look at this and found that I can support spaces in URL segments. Though since spaces aren't technically allowed in in any URLs on the internet, that means spaces in URLs must be encoded as `%20`. But most browsers will do that for you if you type/paste in a URL with spaces. 

To use spaces in URLs with the latest commit, you'll need to follow the instructions for the config.pageNameCharset UTF8 option: 
https://processwire.com/blog/posts/page-name-charset-utf8/

Take the same steps as in the instructions above, but add a space character " " (not encoded) to your config.pageNameWhitelist and in your .htaccess file. If you produce any links to URLs having spaces, I recommend running them through urlencode() before outputting them, so that the spaces are converted to the proper `%20` characters.

**Comment by weberhofer** [comment]
Thank's a lot @ryancramerdesign! I'll give it a try when the next devel-version is released and come back if I still experience issues.

**Comment by Toutouwai** [comment]
This could be seen as a breaking change and will need an update in the documentation. I'm pretty sure I have a few sites where my code expects the (previously) built-in sanitizing to page name format for URL segments.

**Comment by Toutouwai** [comment]
Sorry, I only skim-read the comments and didn't notice that nothing changes unless you specifically add the space character to config.pageNameWhitelist. Please disregard my last comment.
