### ISSUE TITLE
numChildren inaccurate after Pages::clone operation

### ISSUE THREAD

**Issue by thetuningspoon** [processwire/processwire-issues#723]
### Short description of the issue

After cloning a tree of pages, checking the numChildren property on the cloned page (during the same page load) shows a number higher than the actual number of children. On the next page load, the numChildren property shows the correct number of children.

### Expected behavior

numChildren would reflect the number of child pages under the clone.

### Actual behavior

The number is higher. I'm not sure exactly where it's coming from.

### Steps to reproduce the issue

1. Create a page with children in the page tree
2. Call $clone = $pages->clone($page) for the parent page
3. echo $clone->numChildren

### Setup/Environment

* ProcessWire version: 3.0.104
* PHP version: 7

**Comment by BitPoet** [comment]
I can confirm that. The cause is that ```PagesEditor::_clone``` clones the page together with its numChildren setting, but every cloned child page increments that numChildren value again in ```PagesEditor::savePageFinished```.

The solution is to reset numChildren after [clone $page](https://github.com/processwire/processwire/blob/d7b7acb8e5b8619a207823dc38bb5f2115404534/wire/core/PagesEditor.php#L1110) is called.

Should be an easy fix for @ryancramerdesign.

**Comment by netcarver** [comment]
@thetuningspoon Michael, can this be closed now?

**Comment by thetuningspoon** [comment]
Yes, thanks.
