### ISSUE TITLE
PW 3.0.117 and Profield Table conflict?

### ISSUE THREAD

**Issue by tbba** [processwire/processwire-issues#729]
PW 3.0.117 and Profield Table conflict?

Warning: Declaration of ProcessWire\TableRows::___new(array $data = Array) should be compatible with ProcessWire\WireArray::___new($items = NULL) in /.../site/modules/FieldtypeTable/TableRows.php on line 449

**Comment by kixe** [comment]
Since the last update the error is gone. But it remains an inconsistency.

The function **___new()** in the **WireArray** derived class **TableRows** does not create a new object of the class like the parent class does calling new statically. Instead of this a new item is created and added to the already instantiated object.

I would recommend to rename this function from **___new()** to **___newItem()** since this reflects the functionality better.

**Comment by tbba** [comment]
yes, fixed. Can the thread be closed in despite of kixe's additional suggestions?

**Comment by tbba** [comment]
I close this now.
 @kixe please reopen the threat if needed.
