### ISSUE TITLE
Click + hold does not affect multilanguage fields in ProTable field.

### ISSUE THREAD

**Issue by Lazerproof** [processwire/processwire-issues#73]
### Short description of the issue

Short description goes here.

### Expected behavior

It should change language tabs as in normal fields and it especially important for ProTable field as it commonly has a lot of data.

### Actual behavior

Does not change language tabs. 

### Optional: Suggestion for a possible fix

`a` tags in language tabs are missing `data-lang` attribute

### Setup/Environment

* ProcessWire version: 3.0.39
* ProTable 0.1.3

**Comment by ryancramerdesign** [comment]
Thanks, I have fixed this in the InputfieldTable.module and will make sure it's included in the next version. If you'd like to apply the fix to your current copy do the following replacement in InputfieldTable.module:

Replace this (line 436):
~~~~~
if(empty($_value)) $class = " class='langTabEmpty'";
$tab .= "<li><a$class href='#$name'>" . $language->get('title|name') . "</a></li>";
~~~~~
with this:
~~~~~~
$class = "langTab$language->id";
if(empty($_value)) $class .= " langTabEmpty";
$tab .= "<li><a class='$class' data-lang='$language->id' href='#$name'>" . $language->get('title|name') . "</a></li>";
~~~~~~
That covers half of it so that if you longclick a language tab outside of the table, it will update the table tabs too. The other half is making a longclick of the table tabs affect more than just the one. I had to make a core adjustment for that, and it'll be on the dev branch tomorrow.
