### ISSUE TITLE
Persistent locale warnings when logging in ("Warning: your server locale is undefined and may cause issues.")

### ISSUE THREAD

**Issue by teppokoivula** [processwire/processwire-issues#732]
After updating a couple of sites to PW3 I've been running into this message: "Warning: your server locale is undefined and may cause issues."

This may be a misunderstanding on my part, but since the message states that "Please translate the “C” locale setting for each language to the proper locale in %s", and I have already done that, shouldn't that message go away? Currently it doesn't, and instead re-appears every time I log in.

If not, it should be clarified exactly _why_ I need to translate the "C" locale setting if it doesn't solve the issue – the way that message currently reads gives me the impression that this is the preferred fix, and thus the message not going away feels like a bug.

Either way, current situation is quite confusing.

**Comment by LostKobrakai** [comment]
Afaik the warning is only supposed to be shown on new sessions for superusers (a.k.a once on login). At least that's what it did for me recently.

**Comment by teppokoivula** [comment]
@LostKobrakai, that's correct: it's displayed only for superusers, but it's still confusing. By "persistent" I meant that it returns every time I login – now that I re-read the title I see that it might've sounded like this message remained while browsing the admin as well.

Sorry for any confusion :)

**Comment by teppokoivula** [comment]
Hey @ryancramerdesign, any chance you could take a look at this? Obviously this is not critical, mainly just "slightly annoying", but it would be great if you could confirm whether this is a bug or a feature :)

**Comment by jmartsch** [comment]
I experience the same thing on some sites

**Comment by ryancramerdesign** [comment]
This message is triggered by a failure of the `basename('§')` call: 
~~~~~
// warning about servers with locales that break UTF-8 strings called by basename
// and other file functions, due to a long running PHP bug 
if(basename("§") === "") {
  $msg = $this->_('Warning: your server locale is undefined and may cause issues.') 
  ...
~~~~~
This indicates there's something wrong with the locale setting on the server, and the the "C" locale (or whatever it happens to be set at) is breaking UTF-8 strings. To be honest, I don't really understand the issue that well, and the code here was submitted in another issue report a few years back in order to warn users about the locale issue. I've found that translating the locale per the instructions always solves it whenever I've seen the notice. If the notice continues to appear, that means that whatever locale was specified is still producing the error. If you SSH into the server and type `locale -a` that should give you a list of locales available on the server, and you'd want to choose a UTF-8 compatible locale for ProcessWire settings.

**Comment by teppokoivula** [comment]
Thanks @ryancramerdesign! While I don't have access to the server that originally generated the issue, on another machine the defined locale didn't exist. Looks like a mishap on my side, not sure why I thought it'd be available – might've checked the list of locales on wrong machine or something along those lines.

In this case your comment was extremely helpful in debugging the issue, while the error message was mainly confusing. Any chance that we could implement an additional check there, for cases where the locale is already translated, but still doesn't work?

Current message just asks to translate the locale setting, but if the user has already done that and the message reappears, it's unclear what they should do next. In my opinion the best thing to do would be to check if the locale string is translated and output a different message, perhaps something like this:

> Warning: the "C" locale setting has been translated for current language, but the provided value doesn't work as expected. Please translate the “C” locale setting for each language to the proper locale in /wire/modules/LanguageSupport/LanguageSupport.module (shortcuts provided below):

**Comment by ryancramerdesign** [comment]
Thanks @teppokoivula I have updated the locale warning message to be more descriptive and also indicate the current locale setting.

**Comment by teppokoivula** [comment]
Thanks @ryancramerdesign!
