### ISSUE TITLE
Wrong paths in cache/FileCompiler

### ISSUE THREAD

**Issue by pwplatko** [processwire/processwire-issues#737]
### Short description of the issue

Wrong paths in cache/FileCompiler for directories under site/templates

As a consequence, Translation fails because of the path conversion in wire/modules/LanguageSupport/LanguageTranslator.php, line 229:
` if($pos) $filename = substr($filename, $pos+20);`

My temporary workaround to make translations happen is to replace this line with
`if($pos) $filename = preg_replace("@^.*?cache/FileCompiler/@", wire('config')->urls->templates, $filename);` 

### Expected behavior
find site/assets/cache/FileCompiler/ -type f
...
site/assets/cache/FileCompiler/site/templates/_main.php
...
site/assets/cache/FileCompiler/site/templates/subdir/sub.php

### Actual behavior

find site/assets/cache/FileCompiler/ -type f
...
site/assets/cache/FileCompiler/site/templates/_main.php
...
site/assets/cache/FileCompiler/subdir/sub.php

### Steps to reproduce the issue

1. Step 1
create multilanguage install
2. Step 2
create directory templates/subdir
create file templates/subdir/sub.php containing this:
```
<?php
echo __('original text');
```
replace file templates/_main.php with this:
```
<?php 
include "subdir/sub.php" ;
```
3. Step 3
navigate to site in browser
check directory assets/cache/FileCompiler
find site/assets/cache/FileCompiler/ -type f
 

### Setup/Environment

* ProcessWire version: 3.0.98
* (Optional) PHP version: 5.6.38-0+deb8u1
* (Optional) MySQL version: 
* (Optional) Any 3rd party modules that are installed and could be related to the issue:

**Comment by netcarver** [comment]
@ryancramerdesign Bumping for your consideration.

**Comment by ryancramerdesign** [comment]
@pwplatko I can't duplicate the issue here. I tested on a live site that's already using translation files with subdirectory off of /site/templates/, as well as on a fresh installation of the site-languages default profile. All of my multi-language installations use either a partials/ or includes/ directory off of site/templates/, which I use to include various common pieces of markup, most of which have translatable phrases. In both cases that I tested just now, the FileCompiler created the /site/assets/cache/FileCompiler/site/templates/includes/ directory and file, and phrases in them translated correctly. 

It's not clear to me why it's not working in your case, though the temporary workaround you are using will not work for sites that aren't running off the domain root, and it will also break any translations for phrases that aren't in /site/templates/. Is there anything different/unusual about your file system paths that might account for the behavior you are seeing? It looks like you are on linux, so it's not going to be a directory_separator issue like we might observe in Windows or something. 

I'm guessing this call is failing in your installation for some reason: `$pos = stripos($filename, '/cache/FileCompiler/');`. The only way could see that failing is if the "/cache/FileCompiler/" string somehow appeared twice in filenameToTextdomain() call (or didn't appear at all). It might be interesting to get a look at what the $filename argument is passed to that method when you are observing it to fail. The other thing I would suggest is to upgrade your PW version to the current master, as there's always a possibility this was a bug in the version you are using (though I'm not aware of this particular issue occurring before, as it would have broken many of my client sites).
