### ISSUE TITLE
Session login throws Warning in PHP 7.x

### ISSUE THREAD

**Issue by clsource** [processwire/processwire-issues#738]
### Short description of the issue

In some ocassions when using `$session->login($user, $pass)` PHP 7.x throws a warning.
Similar to this
```
session_regenerate_id(): Cannot regenerate session id - session is not active 
{"exception":"[object] (
ErrorException(code: 0): session_regenerate_id(): 
Cannot regenerate session id - session is not active at
 /var/www/html/vendor/processwire/processwire/wire/core/Session.php:818)
```

### Expected behavior

Session is created without warning.

### Actual behavior
Session is created but throws warning.

### Optional: Suggestion for a possible fix
Create session object if is not present already. 
Lines `818` and `1007` of `wire/core/Session.php`

```php
if (!isset($_SESSION)) 
{ 
  session_start(); 
}
session_regenerate_id(true);
```

### Steps to reproduce the issue

Execute this sample code

```php
<?php

// if no session is created before it will throw warnings in PHP 7.x
//session_start();
session_regenerate_id(true);

if (!isset($_SESSION)) 
{ 
    session_start(); 
}
session_regenerate_id(true);

echo "ok";
```

It will throw warning in PHP 7.x but not in 5.6 (Test here https://3v4l.org/lhIQ1)

![imagen](https://user-images.githubusercontent.com/292738/47746152-5377ca80-dc64-11e8-85e6-a85094beede1.png)

### Setup/Environment

* ProcessWire version: 3.0.116
* (Optional) PHP version: 7.2

**Comment by ryancramerdesign** [comment]
> In some ocassions when using $session->login($user, $pass) PHP 7.x throws a warning.
Similar to this

Thanks for the report. Can you describe the occasions where you observe this? I've been using PHP 7.x for quite a long time now and haven't observed this error yet, so want a better idea of how to reproduce it in ProcessWire. It looks to me like in order for this to occur, it would have to happen from a login() call before the Session has initialized and before PW has reached API ready() state? PW's session_start() happens in the ___init() method of the Session class and has a lot of things in that same method that must precede it. If we were to just call a session_start() without those prerequisites it would be a generic PHP session rather than a ProcessWire one.

**Comment by clsource** [comment]
I tried to replicate this error in a new environment but I was unable to.
Maybe it was some weird configuration or permission problem.

I would close this for now 👍 

Thanks 😄
