### ISSUE TITLE
pages->find("template=x, sort=sort") is not playing as it should

### ISSUE THREAD

**Issue by postscript-chris** [processwire/processwire-issues#752]
### Short description of the issue

Here is my page tree:

- Awards
  - Winners
    - Winner 1
    - Winner 2
    - Winner 3
    - Winner 4
    - Winner 5
  - Finalists
    - Finalist 1

Any thing with a number after it has a template id of 69, so we have:

$awards = $pages->find("template=69, limit=5, sort=sort");

### Expected behavior

Winner 1
Winner 2
Winner 3
Winner 4
Winner 5

### Actual behavior

Finalist 1
Winner 1
Winner 2
Winner 3
Winner 4

* ProcessWire version: 3.0.119

**Comment by LostKobrakai** [comment]
There's no global sort order. There's just a sort order within the same parent.

**Comment by teppokoivula** [comment]
AFAIK [sort is only applicable within same parent](https://github.com/processwire/processwire/blob/dev/wire/core/Page.php#L68), so this is more or less expected behaviour. I may be wrong, or @ryancramerdesign may be able to solve this in some other way, but I'd recommend using some other criteria to sort results by parent.

**Comment by Toutouwai** [comment]
@postscript-chris, to explain it another way, "sort" is literally a number that exists for every page in the `pages` database table.

![2018-11-22_092051](https://user-images.githubusercontent.com/1538852/48866631-5ebfaf80-ee38-11e8-895b-52430bf39607.png)

When you use `sort=sort` in a selector you are saying "sort by that number". Generally speaking when your selector matches pages under multiple parents then you can expect the first child under Parent A to be followed by the first child under Parent B because they will both have sort value 0.

Often the sort value for child pages under a given parent corresponds to the sort order you see in the page tree, but not always (e.g. if you set a sort order for children on the parent template or page then the sort order of child pages likely won't correspond with the sort values in the database).

Maybe what you want for your selector is:

```php
$awards = $pages->find("template=69, limit=5, sort=parent.sort, sort=sort");
```

**Comment by ryancramerdesign** [comment]
These guys already explained it better than I could, but it looks like your expected sort order excludes the "Finalist" pages, so you could solve this just by asking for items from the parent rather than a template. 
~~~~~
$awards = $pages->get("/awards/winners/")->children("limit=5"); 
~~~~~

**Comment by postscript-chris** [comment]
Understood.
