### ISSUE TITLE
CKEditor & choose a document bug

### ISSUE THREAD

**Issue by jonathanschiffner** [processwire/processwire-issues#756]
### Short description of the issue

I came across a bug in the CKEditor. I want to add a link to a document from another template.  If I go on _choose a page_ and then _choose a document_ it automatically goes back to the original page and does not give me the documents from the page I first chose. In the attachment, you can see that I chose the page /uploads/ but under documents, it shows me the page /medien/. (I'm sorry this is in German.)

### Optional: Screenshots/Links that demonstrate the issue

![image](https://user-images.githubusercontent.com/42658538/49188244-db61fa80-f31e-11e8-82cb-88d2db7aceef.png)

### Setup/Environment

* ProcessWire version:  3.0.119
* (Optional) PHP version:
* (Optional) MySQL version: 
* (Optional) Any 3rd party modules that are installed and could be related to the issue:

**Comment by ryancramerdesign** [comment]
I can't seem to duplicate this one, though I'm not exactly sure what I'm looking at in your screenshot because I see two "Select page" fields rather than one (?). After selecting a page, you can usually click on the "Select file" and it'll show you files from the page you selected. That's how it works for me at least just testing now.  But I can see from your screenshot that it does appear to be showing the wrong thing in your case. That's why I'm wondering about there seeming to be 2-page selection boxes rather than one? (though I don't know how to read German so am just seeing the sitemap icon). I'm guessing whatever that is, it might be the reason why the file selection isn't working. Do you see any JS errors?

**Comment by Toutouwai** [comment]
Not sure if this is the same issue as described in the first comment, but it seems that "Select File" field is only updated to show files on the selected page if Select File is open and not collapsed (as it is by default).

Field open (working):
![select](https://user-images.githubusercontent.com/1538852/49678653-b02f9600-faea-11e8-89f6-051609aad815.gif)

Field collapsed (not working):
![select2](https://user-images.githubusercontent.com/1538852/49678655-b887d100-faea-11e8-9da8-d884f754f81c.gif)

**Comment by jonathanschiffner** [comment]
Ya, @Toutouwai , that is exactly the issue I've been having. Is there any fix for this?

**Comment by ryancramerdesign** [comment]
@Toutouwai Thanks that helps me to understand. This behavior was intended, as one would have to see the instructions in the opened "Select file" field before you'd know the option was there. So opening the file field was the way that you state your intention is to link a file. That way it doesn't have to do the work of retrieving the files after page selection if it doesn't look like you'll need them. However, if there's any confusion on that point, I think it's fine to have it populate the file field after page selection even if it's not open. I have updated it so that it populates it either way.

**Comment by netcarver** [comment]
@jonathanschiffner Can this be closed now?
