### ISSUE TITLE
@since tags no more?

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#759]
@ryancramerdesign - just wondering if you are planning on continuing to make use of `@since` to highlight when new methods/parameters etc are added. It seems like lately these are not being implemented which seems a shame.

**Comment by Toutouwai** [comment]
On the subject of `@since` tags: I noticed that in the Inputfield class there are a number of new methods marked "since 3.0.110".

![2018-12-03_104506](https://user-images.githubusercontent.com/1538852/49345369-a07a1100-f6e8-11e8-934c-7046233bcb3a.png)

Because there is only a single entry in the docs for items that are both methods and properties, do you think there needs to be something to clarify that the `@since` only applies to the method? Because a person new to PW looking at the entry above might think that they cannot use the `label` property in < 3.0.110.

**Comment by matjazpotocnik** [comment]
I guess it's very tedious going back in history and adding @since. It takes time. Would it help if a list of changes would be supplied to you, Ryan, so you would have to just add @since to the appropriate places, not having to look back and searching when new features were added? Would it help if we (community) would create and maintain changelog.md?

**Comment by netcarver** [comment]
@adrianbj @matjazpotocnik Sounds like a candidate for automation via scanning of the git log and diffing between commits for new functions. There might be existing tools to do this. Would either of you be able to investigate?

**Comment by netcarver** [comment]
Now treating this as a feature request and moving to the requests repo.

@adrianbj @matjazpotocnik we can continue any discussion over there.

/move to requests
