### ISSUE TITLE
Setting page-add and page-create permissions for a new Role

### ISSUE THREAD

**Issue by takaras** [processwire/processwire-issues#763]
Short description of the issue
Create a new Role and give it page-add and page-create permissions. Then assign the role to a user. The user can't create a new Page. 
When you create the new Role and update or give the "Create Pages" and "Add Children" permissions from the homepage template for this role it works.

Steps to reproduce the issue
1. Add a new role.
2. Give it page-edit, page-add and page-create permissions.
3. Assign the role to a user.
4. Login as the user.
5. Try to create new pages.

Expected behavior
The user with the new role should be able to create new pages.

Setup/Environment
ProcessWire version: 3.0.118
* (Optional) PHP version:  7.2.11

**Comment by ryancramerdesign** [comment]
Having page-edit related permissions on a role is just half the job. It merely enables the potential of being able to do those things. The other half is telling it where those roles apply. This is done on any templates where you've enabled access control. This is how you'd be able to do things like enable the user to create new blog posts, but not create new categories. 

I don't recommend adding those roles the homepage template because that enables the access globally for all templates inheriting access, which usually is not desirable. Instead, edit the template where you want them to have these permissions, click the Access tab to enable access control, then check the boxes for the roles that you want to enable for that template.

**Comment by ryancramerdesign** [comment]
Thanks for the additional steps and screenshot, that clarifies it and I was able to duplicate it. I have pushed a fix for the issue. Thanks.

**Comment by takaras** [comment]
Yes, ProcessWire version 3.0.122 fixes the issue. 
Thanks Ryan.
