### ISSUE TITLE
WireArray "forgets" keys if values are identical

### ISSUE THREAD

**Issue by hgassen** [processwire/processwire-issues#767]
### Short description of the issue 

```
$var = WireArray([
	'key1' => 'value',
	'key2' => 'value',
]);
print_r($var);
```

### Expected behavior

```
ProcessWire\WireArray Object
(
    [count] => 2
    [items] => Array
        (
            [key1] => value
            [key2] => value
        )
)
```

### Actual behavior

```
ProcessWire\WireArray Object
(
    [count] => 1
    [items] => Array
        (
            [key1] => value
        )

)
```

### Optional: Suggestion for a possible fix

Problem seems to be in WireArray::import()

`if(($k = $this->getItemKey($value)) !== null) $key = $k;`

getItemKey﻿() uses array_search() and returns the key of the first value found, so the second﻿, identical value is missed..﻿.

### Steps to reproduce the issue
Above code in any template

### Setup/Environment

* ProcessWire version: Processwire 3.0.121﻿﻿﻿ (dev branch only!)

**Comment by kixe** [comment]
Function **import()** which is used here is meant to create a WireArray with **unique** values. The description of function **import()** says:
_- Skips over any items already present in the WireArray._
This is important to prevent duplicates of objects (WireData, Wire) in the WireArray.

**setArray()** does what is expected.

```
$data = ['key1' => 'value', 'key2' => 'value'];
$obj = new WireArray();
$obj->setArray($data);
print_r($obj);

// ProcessWire\WireArray Object ( [count] => 2 [items] => Array ( [key1] => value [key2] => value ) ) 
```

In case of creation a WireArray from array it might be better to use **setArray()** instead of **import()** within the static function **newInstance()**

**Comment by hgassen** [comment]
Thank you, Ryan.

After the fix, the output of the above code is:

```
ProcessWire\WireArray Object
(
    [count] => 2
    [items] => Array
        (
            0 => value
            1 => value
        )
)
```

The array keys are lost. Is this intended behavior?

**Comment by teppokoivula** [comment]
Currently with duplicateChecking enabled import() prevents accidentally overwriting existing keys, so it can keep all keys as-is. If it's disabled, it automatically creates unique keys for all imported items.

Unless I'm missing something obvious here, it cannot _reliably_ stick to old keys – i.e. if there's a duplicate key, it has to be changed – so current behaviour seems like a reasonable compromise.

Another option would be sticking to old key if possible, and providing a new one if the old one was already reserved. To me it seems like this could create false expectations: if you expect your keys to remain as-is, you may run into issues when suddenly they're not :)

**Comment by hgassen** [comment]
I'll try to clarify:

Ryan's fix in 3.0.122 solves the problem with non-unique values (!), but the array keys are lost.

When using the WireArray() function, I get the following result (in 3.0.122):

```
$var = WireArray([
	'key1' => 'value',
	'key2' => 'value',
]);
print_r($var);

// Output

ProcessWire\WireArray Object
(
    [count] => 2
    [items] => Array
        (
            0 => value
            1 => value
        )
)
```

When creating a new WireArray() instance directly, I get the following:

```
$var = WireArray::new()->setArray([
	'key1' => 'value',
	'key2' => 'value',
]);
print_r($var);

// Output

ProcessWire\WireArray Object
(
    [count] => 2
    [items] => Array
        (
            [key1] => value
            [key2] => value
        )
)
```

Shouldn't both ways of creating a WireArray instance produce the same result and preserve the keys? Maybe the WireArray() function should use the setArray() method, as suggested by @kixe ?

**Comment by ryancramerdesign** [comment]
WireArray types aren't really designed to be used like a PHP associative array. Technically I suppose they can (using that setArray like you indicated) but the associative type in PW would be WireData rather than WireArray. That's because in most WireArray derived types, the key is dictated by the value. For instance, Page objects are indexed by their ID. Now that WireArray is opened up for more general purpose usage, I suppose we should accommodate more options as the need arises. I've updated the newInstance() method used by the WireArray() function to detect if it's receiving an associative array and use setArray() rather than import() when it detects it. However, if you need an associative array I'd still suggest using WireData or just a regular PHP associative array instead.

**Comment by hgassen** [comment]
Makes sense, thank you, Ryan.

**Comment by Lazerproof** [comment]
@ryancramerdesign I like functions API and found it very convenient. WireArray() is good addition to it, but I'm courious is there any reason why we don't have WireData() function?

**Comment by ryancramerdesign** [comment]
@Lazerproof Admittedly I've not had the need for creating new WireData objects before in this manner, but what you say makes sense—if there's a WireArray() then why not have a WireData() too... I'll look into it.

**Comment by netcarver** [comment]
@ryancramerdesign Ryan, does this need the "fixed" label changing to keep it on the radar?

**Comment by netcarver** [comment]
@ryancramerdesign Bumping this for your further consideration.

**Comment by ryancramerdesign** [comment]
@Lazerproof A WireData() function was added back in 3.0.126 (see bottom of /wire/core/Functions.php). I'm not sure how useful it really is, so haven't highlighted it in the blog or anything, but I think it's still good to have just for consistency with the WireArray() function. 

@netcarver I think this one is okay to close so I'll go ahead and close now.
