### ISSUE TITLE
$input->url querystring when called before ready doesn't work

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#776]
### Short description of the issue

If you try to get the querystring from `$input->url` from a module's `init()` (or any other situation before `ready()`) it doesn't work

### Expected behavior

It should work :)

### Optional: Suggestion for a possible fix

This WireInput `url` method handles the url before `ready()` by making use of `$_SERVER['REQUEST_URI']`. I think the querystring part needs a similar fallback. Something like this:

```
$info = parse_url($_SERVER['REQUEST_URI']);
$queryString = isset($info['query']) ? $info['query'] : '';
```
I feel like I might have reported this before because I discovered it around the same time I put together this PR: https://github.com/processwire/processwire/pull/46 but maybe I forgot this part :)

**Comment by ryancramerdesign** [comment]
API variables are not considered ready to use until the API ready state, this is the primary purpose of the ready state (to indicate that API variables are ready to use). But I can see what you are saying, that the `$input->url()` method seems to work in the init state, so if the method otherwise works then why not have its `$querystring` argument work as well. But in testing here `$input->url(true)` (where true is the querystring argument) is also working correctly here in the init state. I tried from /site/init.php as well as an autoload module's init() method. Can you clarify how to reproduce the issue?

**Comment by adrianbj** [comment]
Sorry, I can't reproduce now either. I'll keep an eye out for it and reopen if I can reproduce it.
