### ISSUE TITLE
FunctionsAPI.php: array syntax not compatible with PHP 5.3.8

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#777]
### Short description of the issue

[This line](https://github.com/processwire/processwire/blob/649d2569abc10bac43e98ca98db474dd3d6603ca/wire/core/FunctionsAPI.php#L469) uses the short array syntax not supported by PHP 5.3.8, which is the minimum required version stated for PW.

Related forum topic: https://processwire.com/talk/topic/20571-install-functionsapiphp-error/

BTW, is there a timeline for updating the minimum PHP version required for PW? PHP 5.3.8 is ancient now.

### Setup/Environment

* ProcessWire version: 3.0.123

**Comment by horst-n** [comment]
minimum PHP 5.6 for PW 3.0.123+ would be my favourite.

**Comment by ryancramerdesign** [comment]
I don't think this issue is present anymore, as it looks like when I moved the function to the FunctionsWireAPI.php file I must have also changed the `[]` to `array()` at the same time. I still prefer the older array syntax, in part because I type it faster as a result of habit (which isn't a very good reason), but also because it's more consistent with the argument type hinting, type casting, and most array function names. As far as minimum required PHP version, I don't currently have any other code in the core (that I'm aware of) that would require a higher version. Of course people should use newer PHP versions for other reasons. I see no problem with bumping it to 5.4 or even 5.6, but until it's technically required by the code in the core, I'm not sure there's a good reason to do so.

**Comment by teppokoivula** [comment]
Hey @ryancramerdesign, I just wanted to cross-link something that might be (?) of interest. WordPress 5.1 is going to ship soon with what they call the "PHP Site Health Mechanism". This will (at first) display a warning to users with PHP < 5.6. Some time later the bar will apparently be raised to 7.0 or 7.1: https://make.wordpress.org/core/2019/01/14/php-site-health-mechanisms-in-5-1/.

Obviously this is more relevant in their context, but since PHP 7.1 is the lowest version currently getting security updates, I do think that it would be reasonable to bump our requirements a bit even if **we** can technically deal with lower versions.

1) If this can persuade a few more people to upgrade from ancient (and possibly insecure, unless they're using a version with backported security fixes, such as the one in old Ubuntu LTS releases) versions then that's awesome.

2) Even if older versions do technically work, PHP 5.6 has benefits over earlier versions, and starting with 7.0 the performance benefits are a major factor. Again, ProcessWire may work with 5.3 or 5.4 just fine, but our requirements might be the nudge (or push) someone needs to move on to a more up-to-date version, in which case everyone benefits.

Also: these days one could even see a very low version requirement as a negative thing, as it signals that we're unable to make proper use of the various beneficial features introduced by later versions, and as such have to rely on certain arguably outdated features (in my opinion improvements in the typing system are already a good reason not to support anything below 7.0.)

I get it if you're not willing to up our requirements just for these reasons, and I know better than to expect that we'd do something just because someone else does it – but overall I think that we should be good web citizens and take every chance to lead our users towards modern PHP versions :)

**Comment by netcarver** [comment]
/remind me to review this issue and close if needed in 1 week

**Comment by Toutouwai** [comment]
Upping the minimum PHP requirements would be beneficial to module authors I think.

For devs who are using PHP 7.x for everything now it's just a bit of extra mental friction/hassle to have to bear in mind all the limitations of ancient PHP versions when I'd rather be freeing up that brain space for something else :-)

**Comment by adrianbj** [comment]
> Upping the minimum PHP requirements would be beneficial to module authors I think.

I agree - the Tracy core is now PHP 7+ so at the moment I have been sticking with an older release so I don't have to maintain two versions.

**Comment by ryancramerdesign** [comment]
> Obviously this is more relevant in their context, but since PHP 7.1 is
the lowest version currently getting security updates, I do think that it
would be reasonable to bump our requirements a bit even if *we* can
technically deal with lower versions

I agree with the above. Anything that supports added security is something
I can get behind. Rather than having a minimum required version, I think
maybe perhaps we'll have a minimum recommended version of 5.6.

**Comment by netcarver** [comment]
@ryancramerdesign Can I go ahead and close this issue following your last post about bumping the minimum recommended version?

**Comment by netcarver** [comment]
/remind me to review this is 1 week

**Comment by netcarver** [comment]
/remind me to review this issue in 1 week

**Comment by ryancramerdesign** [comment]
Closing because reminders re-opened it
