### ISSUE TITLE
WireCache maintenancePage method generates a lot of DB connections

### ISSUE THREAD

**Issue by karltdev** [processwire/processwire-issues#783]
### Short description of the issue

If there are many pages that use $cache with the same expire selector, e.g. "template=home", WireCache maintenancePage method will generate a lot of DB connections, which crashes the database due to max_connections limit, after saving the relative page, e.g. home. 

### Expected behavior

The cache amount increase should not crash the database.

### Actual behavior

In my case, there are around 300 pages using the same expire selector and each page has 5 caches and The site has 2 languages. So there are around 3000 caches that will be removed every time the relative page is saved. My database started to crash (Error: Too many connections) after the amount of cache grew to a certain level. After I remove all the WireCache, the crash stopped.

### Setup/Environment

* ProcessWire version: 3.0.112
* (Optional) PHP version: 7.2
* MariaDB version: 10.2.15

**Comment by ryancramerdesign** [comment]
That's just a whole lot of caches to be maintaining and expiring, and you are running up against the limits of what your server will allow. I don't think there's anything we can do about that from this side. If there is any similarity among those 300 pages, I would suggest just maintaining one single cache for all of them and str_replace() placeholders where necessary from the cache so that you don't have to maintain so many independent caches. Another option is that you could try using MarkupCache, though I think you might hit up against similar issues. If your caches are entire page renders, I would suggest using the page cache that you configure from the Template editor Cache tab (or better yet ProCache if you've got it, but either will work).

**Comment by karltdev** [comment]
Thank you Ryan. I am not quite familiar with Database actually, but I get your point. I have no idea which server or db limitation I had hit. I have twisted some of the limits but no luck. And the database crashed due to Too many connections make me think if it is the WireCache code that matters.

**Comment by teppokoivula** [comment]
@karltdev, "too many connections" is the error that MySQL outputs when `max_connections` has been exceeded: https://dev.mysql.com/doc/refman/8.0/en/too-many-connections.html.

You may try to adjust this setting in your config, but at some point it'll probably make your whole system slow – so not really something you'd typically want to do either :)

**Comment by netcarver** [comment]
@karltdev Hello Karl, can this issue be closed?

**Comment by netcarver** [comment]
Closing as there's been no feedback. @karltdev Karl, please post more/re-open this if you need to.

**Comment by karltdev** [comment]
I understand this cannot be solved and this happens due to the special usage of WireCache. I will try to figure out a solution and post it back if I can find any. Thanks for the feedback.
