### ISSUE TITLE
SQL error in selector id|has_parent=1234

### ISSUE THREAD

**Issue by matjazpotocnik** [processwire/processwire-issues#786]
This selector works:

`$pages->find( "has_parent|id=1234");`

while this one:

`$pages->find( "id|has_parent=1234");`

fails with

`Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'pages.has_parent' in 'where clause' on line: 416 in C:\inetpub\wwwroot\wire\core\PageFinder.php`

Possible solution: add this to arrangeFields() to force has_parent (and probably hasParent) at the beginning of $native array

```
if(in_array('has_parent', $native)) {
	$native = array_diff($native, array('has_parent'));
	array_unshift($native, 'has_parent');	
}
```

**Comment by ryancramerdesign** [comment]
@matjazpotocnik The issue here is that has_parent cannot be OR'd with other fields. The "id" is getting silently thrown out in your working find, so actually neither should be working. What we need is a PageFinderSyntaxException to be thrown when either case is here, so I have pushed an update to do that. Thanks.

**Comment by matjazpotocnik** [comment]
Thanks for the info.
