### ISSUE TITLE
Impossible to make the right translation for strings inside relativeTimeStr function for languages that have different word declinations 

### ISSUE THREAD

**Issue by Lazerproof** [processwire/processwire-issues#793]
Actualy it's not a bug, but implimentation of the relativeTimeStr function that not gives a way how to
translate strings in langauges that have different word declinations depending on the number.
For example in Ukrainian word 'week' can have three variant неділю, неділь, неділі.
There is a pattern:
```
1 неділю
2-4 неділі
5-20 неділь
21 неділю
22-24 неділі
```
It's not an issue to use some other library or custom function on the frontend, but there is no way to change this behavior for example in ProcessLogger module.

**Comment by ryancramerdesign** [comment]
I think the logic described probably goes outside the scope of what we could cover with this function, as it does not seem to be very common among various languages as far as I can tell. Though I could be wrong, but I've not come across it yet in the several years that we've had this function. But I understand it probably reads incorrect, and that's something we want to account for. So one possible solution might be that we could provide a translation option that forces it to use a more traditional date() or strftime() format rather than a relative time string? While it would no longer be producing a relative time result, at least it would be producing a properly formatted date/time for the language.

**Comment by LostKobrakai** [comment]
For localization to the detail of the grade you're explaining you might want to look into an implementation of cldr in php, which is imho the only proper solution to localization (without redoing all the translation work in each project over and over again).

**Comment by Lazerproof** [comment]
@ryancramerdesign Maybe this function could be hookable, so it would be easier to support different variation that may occur in the future for different languages?

**Comment by ryancramerdesign** [comment]
@Lazerproof Good idea, I have gone ahead and make it hookable.

**Comment by netcarver** [comment]
@Lazerproof Please go ahead and close this issue if Ryan's commit allows you to solve the issue.

**Comment by Lazerproof** [comment]
@ryancramerdesign Thanks!
