### ISSUE TITLE
Parallel Fileupload broken with Sessions in Redis or Memcached

### ISSUE THREAD

**Issue by tiefenb** [processwire/processwire-issues#798]
### Description of the issue
When using Redis, memcached or SessionHandlerRedis-Module as PHP Session store, the uploading of multiple images at once are not working correct.

I.e. I have two images abc.jpg (2000KB) and xyz.jpg (200KB).
Both images will be uploaded in the frontend. After saving the page only the image which was bigger in size is actually saved in the field.
While uploading I see in my database table the xyz.jpg finished. After the abc.jpg is finished the xyz.jpg is gone and only the abc.jpg is saved in the database.

### Setup/Environment

* ProcessWire version: 3.0.124
* PHP version: 5.6.40 and 7.0.31 and 7.3.1

* Module SessionHandlerRedis OR session.save_handler = redis OR session.save_handler = memcached

**Comment by tiefenb** [comment]
<img width="1440" alt="bildschirmfoto 2019-01-22 um 11 04 12" src="https://user-images.githubusercontent.com/488163/51527785-81b91080-1e35-11e9-8069-b50f5f0d8ced.png">

<img width="1440" alt="bildschirmfoto 2019-01-22 um 11 04 21" src="https://user-images.githubusercontent.com/488163/51527792-8382d400-1e35-11e9-8e98-112636f5f853.png">

It looks like, that the Session for the 2nd uploaded image is lost and because of this the login-form is outputed in the upload response?

**Comment by tiefenb** [comment]
The really strange thing is that with redis both image are successfully uploaded BUT in the response with the same ID so the 2nd overrides the 1st in the database. In memcached the 2nd failed because of the invalid json response.

**Comment by tiefenb** [comment]
Hi @ryancramerdesign!

yes I opened an issue at @netcarver 's module, but after I saw, that the issue is also with native php redis/memcached session support I thought it isn't a problem in the module. Maybe some core bug or an bug in PHP (or the redis/memcached extension) itself.

**FYI how this native redis/memcached session works:**

You can run on your server redis or memcached and than you can add in your php.ini following:

For Redis:
```
session.save_handler = redis
session.save_path = "tcp://127.0.0.1:6379"
```

For memcached:
```
session.save_handler = memcached
session.save_path = "127.0.0.1:11211"
```

With this settings instead of saving your session to assets/session, they will be saved to redis or memcached. A more detailed tutorial can you find here: https://www.digitalocean.com/community/tutorials/how-to-set-up-a-redis-server-as-a-session-handler-for-php-on-ubuntu-14-04

I like the idea, because redis and memcached are very performant in large scale environments and cloud hosted providers with more multi server instances. And everything works well, only the upload of multiple files at once are buggy.

**Comment by ryancramerdesign** [comment]
When using native PHP sessions (i.e. SessionHandlerDB module not installed), we let PHP handle all session matters, so haven't built anything on top of it. Is it possible there is some configurable setting in redis or memcached that is placing some limit on requests related to the session? 

@netcarver since you've worked with this before, do you have any idea on this? I just checked and don't have access to a server running redis or memcached. But since it appears that PHP sessions behave differently with these as the save handlers, I'm curious to know if there is any documentation on what these different behaviors are and how to code around them?

**Comment by tiefenb** [comment]
Yes could be - since I'm not the expert in this session handling topic. I tried to switch on/off session locking but that didn't help.

If someone is interested, I have created for this issue two docker instances with fresh processwire and redis/memcached for testing. I can upload it somewhere soon.

**Comment by netcarver** [comment]
@ryancramerdesign @tiefenb Hi Ryan, Markus.

Parallel file uploads isn't something I ever tried out with redis, despite using it for various projects in the past. Sorry to say, I really don't have bandwidth to look into this now.

Closest I can find to this with a quick search is [this](https://www.reddit.com/r/PHP/comments/1oz6tc/redis_php_session_handler/ccyh826/) from reddit.

@ryancramerdesign , does PW write the id of uploading images into the session at all?

**Comment by netcarver** [comment]
I'm unfamiliar with parallel file uploads; how they are differentiated in normal PHP sessions that work? 

Found [this](https://secure.php.net/manual/en/session.configuration.php), and wonder if each upload should be switching the session.upload_progress.prefix setting?

**Comment by ryancramerdesign** [comment]
@netcarver Thanks for the response. 

> does PW write the id of uploading images into the session at all?

No, not as far as I know. 

> I'm unfamiliar with parallel file uploads; how they are differentiated in normal PHP sessions that work?

Rather than one file uploading at a time in one request, there can be more than one request uploading at a time. It's the same thing as when you access any webpage and it spawns other requests to load the assets (css, js, images, etc.) and those each happen in independent parallel requests (parallel meaning they are running at the same time). 

As far as PW is concerned, it is just dealing with one file upload per request at a time. An ajax uploaded file is different from a regular uploaded file in that it doesn't come through `$_FILES` and instead comes through the standard input. So you save an ajax-uploaded file like this: `file_put_contents($filename, file_get_contents('php://input'));`

My thought was that maybe these other session handlers only allow one input request at a time, perhaps due to some setting or security feature, and are discarding the others. 

> Found [this](https://secure.php.net/manual/en/session.configuration.php), and wonder if each upload should be switching the session.upload_progress.prefix setting?

From what I understand that setting is for regular, traditional (non-ajax) file uploads that use $_FILES.  In our case, we're just reading from the PHP input stream and writing it to a file.

**Comment by ethanbeyer** [comment]
Hey @ryancramerdesign I just noticed that all the commits to processwire/processwire are from you but not your Github user. Is that intended?

**Comment by tiefenb** [comment]
Great news: I found a solution.
After reading some issue-report about session locking with phpredis I added follwoing to my php.ini and it works now:

`redis.session.locking_enabled = 1
redis.session.lock_expire = 60
redis.session.lock_retries = -1`

Default redis.session.lock_retries was set to 10 and -1 means infinite retries. redis.session.lock_expire was set per default to max_execution_time what was 30

**Comment by ryancramerdesign** [comment]
That's great! Thanks for reporting back on the solution, glad you found it
and I'll make note of this for the next time it comes up.
