### ISSUE TITLE
$config->sessionAllow with PHP 7.3

### ISSUE THREAD

**Issue by kixe** [processwire/processwire-issues#803]
1. Getting PHP 7.3 warning using` $config->sessionAllow` as callable function.
2. Unexpected behaviour with session cookies. A cookie shouldn't be set if `$config->sessionAllow` returns false, **even under admin urls**.

### Short description of the issue
Getting PHP 7.3 warning using` $config->sessionAllow` as callable function.

_Code in /site/config.php_
```
$config->sessionAllow = function($session) {
	if(strpos($_SERVER['REQUEST_URI'], $session->config->urls->admin) === 0) return true;
	// ...
return false;
}
```
### Expected behavior

no warnings.

### Actual behavior

I get the following **warning**, because inside _/site/config.php_ `$session->config->urls->admin` returns _NULL_

> Deprecated: strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior in .../site/config.php on line 25

---

### Short description of the issue

Unexpected behaviour with session cookies. A cookie shouldn't be set if `$config->sessionAllow` returns false, **even under admin urls**.

_Setup_
`$config->sessionAllow = false;`

### Expected behavior

No session cookie is set.

### Actual behavior

A session cookie is set if the requested url is part of the admin.

### Setup/Environment

* ProcessWire version: 3.0.124
* PHP version: 7.3

**Comment by ryancramerdesign** [comment]
For item 1, the error message is occurring in the code in your /site/config.php file. It appears to be because `$config->urls->admin` property is not yet available for whatever reason (maybe because it lacks the `hasCookie()` call before it?). I would suggest changing your `$session->config-urls->admin` to the actual URL to your admin, like `'/processwire/'` or whatever it might be, and I think that would fix it. I'll update that example code in our /wire/config.php to reflect the same, as using a static URL here would be more reliable. 

For item 2, a session cookie is required for admin URLs, otherwise you would not be able to login. You may be able to prevent the session from starting by setting `$config->protectCSRF=false;` but I wouldn't recommend it.

**Comment by kixe** [comment]
@ryancramerdesign 
thanks. closed.
