### ISSUE TITLE
$pages->findIds() and findMany() very slow

### ISSUE THREAD

**Issue by noelboss** [processwire/processwire-issues#804]
### Short description of the issue

Using $pages->findIds() and findMany() is much slower in my test than find() – I would have ecpected the other way arround…

### Expected behavior

Should be faster…

### Actual behavior

Is slower ;) 

### Screenshots that demonstrate the issue

<img width="1295" alt="screenshot 2019-01-31 at 16 32 24" src="https://user-images.githubusercontent.com/114080/52064909-cfd8bd00-2575-11e9-874c-1a749ce6df0c.png">

### Steps to reproduce the issue
Code I used:

```
d($accessSelector);
t('findIds');
for ($i = 1000; $i > 0; --$i) {
	// code...
	$this->accessibleIds = $this->pages->findIds($accessSelector);
}
dump(t('findIds'));
dump($this->accessibleIds);
t('find');
for ($i = 1000; $i > 0; --$i) {
	// code...
	$this->accessibleIds = $this->pages->find($accessSelector);
}
dump(t('find'));
dump($this->accessibleIds);

t('findMany');
for ($i = 1000; $i > 0; --$i) {
	// code...
	$this->accessibleIds = $this->pages->findMany($accessSelector);
}
dump(t('findMany'));
dump($this->accessibleIds);
die();
```

### Setup/Environment
<strong>Server Details</strong>

|Software|Version|
|------:|:-------|
|ProcessWire|3.0.125|
|PHP|7.0.30-1+ubuntu14.04.1+deb.sury.org+1|
|Webserver|Apache/2.4.7 (Ubuntu)|
|MySQL|5.5.60-0ubuntu0.14.04.1|
<details><summary><strong>Server Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|allow_url_fopen|1|
|max_execution_time|120 (changeable)|
|max_input_nesting_level|64|
|max_input_time|120|
|max_input_vars|1000|
|memory_limit|256M|
|post_max_size|120M|
|upload_max_filesize|500M|
|xdebug||
|xdebug.max_nesting_level||
|mod_rewrite|1|
|mod_security|*confirmed off|
|GD|2.2.5|
|GIF|1|
|JPG|1|
|PNG|1|
|EXIF Support|1|
|FreeType|1|
|Imagick Extension|1|
</details><details><summary><strong>Module Details</strong></summary>

|Module ClassName|Version|
|------:|:-------|
|AdminHelp|1.0.9|
|AdminHelpTab|1.0.8|
|AdminOnSteroids|2.0.11|
|AdminPageFieldEditLinks|3.1.2|
|AdminRestrictBranch|1.0.9|
|AdminThemeBoss|0.5.5|
|BatchChildEditor|1.8.15|
|BreadcrumbDropdowns|0.1.15|
|ConnectPageFields|0.2.2|
|CronjobDatabaseBackup|1.1.5|
|CustomInputfieldDependencies|0.1.9|
|DynamicRoleSupport|0.0.7|
|FieldtypeAssistedURL|1.0.0|
|FieldtypeFieldsetGroup|0.0.4|
|FieldtypeFunctional|0.0.2|
|FieldtypeMultiplier|0.1.3|
|FieldtypePageHitCounter|1.2.2|
|FieldtypeRepeaterMatrix|0.0.4|
|FieldtypeRuntimeMarkup|0.0.2|
|FieldtypeTable|0.1.5|
|FieldtypeTemplates|1.0.0|
|FieldtypeTextareas|0.0.7|
|FormBuilder|0.3.4|
|FrontEndEditLightbox|1.4.0|
|IcfAttachments|0.0.1|
|IcfAuthor|0.0.1|
|IcfDownloads|0.0.1|
|IcfFeaturedImage|0.0.2|
|IcfFormFeedback|0.0.1|
|IcfFormSec|0.0.1|
|IcfInvite|0.0.1|
|IcfOauth2Login|0.1.0|
|IcfProcessInvite|0.0.1|
|IcfProcessInviteRequest|0.0.1|
|IcfRangeDownload|0.0.1|
|IcfTemplate|0.0.1|
|IcfUtil|0.0.1|
|InputfieldAssistedURL|1.0.1|
|InputfieldChosenSelect|1.2.4|
|InputfieldChosenSelectMultiple|1.2.0|
|InputfieldFormBuilderFile|0.0.2|
|InputfieldFunctional|0.0.2|
|InputfieldMultiplier|0.1.1|
|InputfieldRepeaterMatrix|0.0.4|
|InputfieldRuntimeMarkup|0.0.2|
|InputfieldTable|0.1.5|
|InputfieldTextareas|0.0.7|
|LoginRegister|0.0.2|
|LoginWithEmail|0.0.3|
|Migrations|0.3.1|
|ModuleSettingsImportExport|0.2.9|
|PageHitCounter|1.2.3|
|PageimageRemoveVariations|0.0.4|
|ProDrafts|0.0.7|
|ProcessAdminHelp|1.0.8|
|ProcessChildrenCsvExport|1.8.14|
|ProcessDynamicRole|0.0.6|
|ProcessForgotPassword|1.0.2|
|ProcessFormBuilder|0.3.4|
|ProcessMigrations|0.1.3|
|ProcessPageListerPro|1.1.1|
|ProcessProDrafts|0.0.6|
|ProcessSetupPageName|2.1.3|
|ProcessTracyAdminer|1.0.6|
|ProcessWireUpgrade|0.0.7|
|ProcessWireUpgradeCheck|0.0.7|
|TemplateAccessController|0.0.1|
|TemplateCategoryEntry|0.0.1|
|TemplateChurchEntry|0.0.1|
|TemplateCollectionEntry|0.0.1|
|TemplateDenominationEntry|0.0.1|
|TemplateFieldWidths|0.1.9|
|TemplateHelper|0.0.1|
|TemplatePage|0.0.1|
|TemplateResourceEntry|0.0.1|
|TemplateUser|0.0.1|
|TextformatterMakeLinks|1.0.0|
|TextformatterOEmbed|2.0.2|
|TextformatterTagParser|2.2.0|
|TextformatterVideoEmbedOptions|0.3.6|
|TracyDebugger|4.17.10|
|WireMailMandrill|0.0.1|
|IcfAuth|0.0.2|
</details>

**Comment by ryancramerdesign** [comment]
@noelboss You are seeing this behavior because you are running the same selector through these functions a thousand times each. This is not an accurate way to test because it doesn't account for caching or the intended use of the functions. If you time just one execution, you'll find both findMany() and findIDs() to be a whole lot faster than find(). If you wanted to measure a thousand executions, you would find the same, but each iteration would need to have a unique selector matching a unique set of pages without overlap. 

The reason for this is that `$pages->find()` caches its results. So on your 1000 calls to it, only one of them is actually running. Further, it also caches the pages that match the results, so any further calls to find(), get(), children(), etc. that include any of the matched pages can pull from the cache.

The `$pages->findIDs()` and `$pages->findMany()` do not cache their results, as they aren't typically called more than once with the same arguments. So those calls in your test are actually executing a thousand times, unlike the find(). The findMany() and findIDs() are typically used to conserve memory and reduce overhead (caches consume memory and add overhead). In real-world cases and when their use is appropriate, the findIDs() and findMany() have major performance and scale benefits relative to find().

**Comment by netcarver** [comment]
@noelboss Given Ryan's explanation, can this be closed?

**Comment by netcarver** [comment]
/remind me to review this issue in 1 week

**Comment by netcarver** [comment]
Closing. Feel free to leave comments or open new issue if needed.
