### ISSUE TITLE
PW 3.0.123: using WireCache when debug mode is on causes admin pages to timeout

### ISSUE THREAD

**Issue by renpw** [processwire/processwire-issues#813]
### Short description of the issue

Using WireCache when debug mode is on and debugTools includes 'cache' (the default) causes admin page load times to increase more than linearly with the number of items in the cache. In contrast, PW 3.0.98 load times show a small linear increase.

### Expected behavior

PW 3.0.98 admin page load times:

No cache: 3s
500 items: 3.5s
1,000 items: 4.5s
1,500 items: 5s
2,000 items: 6s
2,500 items: 6.5s
3,000 items: 7s
3,500 items: 8s
4,000 items: 9s

### Actual behaviour

PW 3.0.123 admin page load times:

No cache: 3.5s
500 items: 6s
1,000 items: 9s
1,500 items: 15s
2,000 items: 23s
2,500 items: 33s
3,000 items: 45s
3,500 items: 60s
4,000 items: > 60s timeout

### Steps to reproduce the issue

1. config.php:

`$config->debug = true;`

2. In Tracy console or a template file:

`for ($i = 1; $i < 4000; $i++) {
	$cache->save($i, $i);
}`

3. Refresh any admin page

### Setup/Environment

* ProcessWire version: 3.0.123
* PHP version: 7.2.8
* MySQL version: 10.0.35
* Database type: InnoDb
* Zend opcache: disabled
* CPU: single core VPS
* RAM: 2 GB
* OS: Slackware 14.2

### Notes

The behaviour occurs regardless of whether TracyDebugger is enabled or disabled.

CPU and RAM usage stay within normal limits.

Timers show nothing unusual.

**Comment by matjazpotocnik** [comment]
I tested on 3.0.127:

```
for ($i = 1; $i < 4000; $i++) { $cache->save("test_".$i, $i, 240); }
d($cache->getInfo());
```
Array(4090), took 3 sec. Then I reloaded a page. It took Chrome cca 20 seconds to render the page, cpu usage 30%, but this is Chrome, not a web server. Win 8.1, 8 GB RAM, i5-4200 @ 2.5GHz. Nothing unexpected here. Also I can't find changes in debug.inc or WireCache.php since 3.0.98 to be important or would have influence on the result.

**Comment by ryancramerdesign** [comment]
That's just a whole lot of caches, more than I think is good idea to be using, unless they are all completely unique. The admin theme debug.inc file renders a summary of all of them, so that's what's slowing down your admin. With so many caches, you may want to avoid running the site in debug mode. Though I might also want to update that debug.inc file to skip over the caches section of debug when there are so many. When it comes to caches, it's not very efficient to have so many, unless they really are completely different things. For instance, if you are caching primary or section navigation, use the same cache for them all, and str_replace() the current nav item class on the returned cache value, rather than keeping many slightly different cached copies of the nearly same thing. Another option is that you could use the MarkupCache module, which is included with the core, but is not summarized in the debug info, and thus won't slow down your admin when in debug mode.

**Comment by adrianbj** [comment]
Would it also help to define this with cache excluded?

```
$config->debugTools = array(
	'pages',
	'api',
	'session',
	'modules',
	'hooks',
	'database', // PDO
	'db', // mysqli
	'timers',
	'user',
	'input',
	/*'cache',*/
	'autoload',
);
```

Also, if you are running Tracy keep in mind that Tracy's debug mode panel also includes caches so you may want to consider unchecking the cache option in the module's panel sections settings.

**Comment by netcarver** [comment]
@renpw Did any of the above comments help resolve this for you?  Can this issue now be closed?

**Comment by netcarver** [comment]
/remind me to review this issue in 1 week

**Comment by netcarver** [comment]
@renpw I'm closing this now. If you need it re-opened just post here again.
