### ISSUE TITLE
Live search doesn't use custom user fields unless specified in query

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#814]
### Short description of the issue

If you set up ProcessPageSearch to search users and the `first_name` field, no results are returned.

`Diane` doesn't return any matches, but `users.first_name=Diane` does work as expected. 

Note that a search string that matches the user's name does work, so if Diane's email was `diane@gmail.com`, then in this case, `diane` as a search string would work, so make sure you test a user where the email address doesn't contain their first name.

### Expected behavior

Custom fields on the user template should work with simple queries

### Actual behavior

No match is returned.

**Comment by Toutouwai** [comment]
I guess this is due to the restriction noted in the module config...

![2019-02-16_104737](https://user-images.githubusercontent.com/1538852/52886195-66dd8000-31d8-11e9-8062-c30d5c1b9434.png)

...where "users" are a separate category to "pages".

I agree it would be good to be able to search user fields though.

**Comment by adrianbj** [comment]
Nice catch @Toutouwai - but I think user fields need to be included. You can't expect a client (with user admin permissions) to type:
```
users.first_name=Diane
```
It needs to be simple for them.

**Comment by ryancramerdesign** [comment]
For all types other than pages (as well as those in trash), ProcessPageSearch lets the Process::search() method determine what fields to search when none are specified. The only searchable text property common to all pages is the "name", so that is what ProcessPageType uses (if you don't specify a field). ProcessPageType is the foundation of Process modules that manage Users, Roles, Permissions, Languages. 

The purpose of the live search is more to be fast than to be comprehensive. Especially for users, where we have a dedicated Lister-powered Users list that lets you search any property. But a feature we could add is the ability to specify what properties/fields are used for live-search in the ProcessPageType::getModuleConfigInputfields() method, so one could configure them individually for Users, Roles, Permissions, Languages. However, this would be a little bit counter to the purpose of the live search emphasizing speed over being comprehensive, but I think it'd be worthwhile for the specific cases where people might desire it.

**Comment by adrianbj** [comment]
@ryancramerdesign - I think it's important to have this option - for some sites, searching users is just as common as searching regular pages.

Also, the argument that we have a user lister doesn't make much sense to me - we have a page lister as well, but most of the time the live search is all that is needed.

Thanks for considering adding this ability.

**Comment by ryancramerdesign** [comment]
@netcarver is it possible for you to move this to feature requests? ('m not exactly sure how to do that). Thanks.
