### ISSUE TITLE
Setting Page Class Name makes the "Save + Unpublished" button disappear

### ISSUE THREAD

**Issue by karltdev** [processwire/processwire-issues#819]
### Short description of the issue

Setting Page Class Name makes the "Save + Unpublished" button disappear.

### Expected behavior

Changing the page class name should not make any change for the save/publish button as the page is still an instance of Page.

### Actual behavior

Setting Page Class Name makes the "Save + Unpublished" button disappear. My common use case for this is to add extra functions to Page, e.g. Product with price formatting output. I have to change the "Page Class Name" to "Product" to make my code functional. Due to this issue, users are forced to publish the page, and instantly go to setting tab to check unpublish to unpub it.

### Optional: Suggestion for a possible fix

This [**if block**](https://github.com/processwire/processwire/blob/c80ae0acd8687fc06e183d84ef7a42efb8f6a0cc/wire/modules/Process/ProcessPageEdit/ProcessPageEdit.module#L911-L923) is the cause of this issue. I guess the reason for having this if block is that changing the class name has possibilities that make the page becoming not an instance of Page. I think it could be changed to check `instanceof Page` first ?

### Steps to reproduce the issue

1. Go to Template Edit
2. Go to System tab and put some text in "Page Class Name" and save
3. Go to Page Edit pf any pages with that template. The button disappears.

### Setup/Environment

* ProcessWire version: 3.0.111

**Comment by ryancramerdesign** [comment]
Thanks @karltdev that's a good point. It only allows publishing if the class is Page because all the other core Page-derived classes are not allowed to have unpublished versions. When I wrote that if() statement I guess I wasn't thinking about non-core Page classes. I have updated it so that it should now work with non-core page classes and show a "Save and keep unpublished" button when appropriate, though please let me know if you find it does not work. Thanks.

**Comment by netcarver** [comment]
@karltdev Hi Karl, could you review the update and close the issue, if appropriate. Thank you!

**Comment by karltdev** [comment]
Yes. I close the issue now. Thanks for reminding.
