### ISSUE TITLE
Inconsistent AsmSelect styling

### ISSUE THREAD

**Issue by LostKobrakai** [processwire/processwire-issues#82]
### Short description of the issue

Different icons and spacing between ajax loaded and standard asm-select.

### Expected behavior

Same Icons

### Optional: Screenshots/Links that demonstrate the issue

![screenshot 2016-11-14 13 10 11](https://cloud.githubusercontent.com/assets/2489835/20264439/d807883a-aa6b-11e6-93ae-0071fff478df.png)

### Setup/Environment

* ProcessWire version: 2.7.2

**Comment by ryancramerdesign** [comment]
Are you seeing this on 3.x too or just 2.7.x? The first asmSelect in your screenshot is using the Font Awesome icons, while the second is using the jQuery UI ones. The InputfieldAsmSelect module makes it use the Font Awesome icons if an $adminTheme API variable is present (as we know our admin themes support it). Our admin themes do not have styles for jQuery UI icons, which is why you see messed up margins on those. For whatever reason, there was no $adminTheme present when your second asmSelect was rendered.  Is that the ajax-loaded one (the 2nd one?)

**Comment by LostKobrakai** [comment]
Yeah, the second one is the ajax loaded one. I'll try to later setup a 3.x installations to see if it's present there as well.

**Comment by ryancramerdesign** [comment]
I'll close this one out for now since I've not heard of this appearing anywhere else, but if you are still running into this on 3.x dev branch versions please feel free to re-open. Thanks.
