### ISSUE TITLE
Does not follow ANY PSR

### ISSUE THREAD

**Issue by nicdavies** [processwire/processwire-issues#823]
### Short description of the issue
I'm surprised that a popular PHP project does NOT follow any PSR style guide, or any PSR for that matter.

Things like this class [here](https://github.com/processwire/processwire/blob/master/wire/core/Exceptions.php) should NOT be done. Having multiple classes defined in one file hideous. Not to mention the fact that the namespace is defined on the same line as the PHP file opening. But at least the namespace thing is consistent.

### Expected behavior
n/a

### Actual behavior
n/a

### Optional: Screenshots/Links that demonstrate the issue
https://github.com/processwire/processwire/blob/master/wire/core/Exceptions.php

### Optional: Suggestion for a possible fix
Install a CS tool like squizlabs/php_codesniffer to tidy up the code to follow psr1 and psr2. And then enforce this tool to be used before any PR is merged into master.

https://www.php-fig.org/psr/psr-1/
https://www.php-fig.org/psr/psr-2/

### Steps to reproduce the issue
n/a

**Comment by LostKobrakai** [comment]
While I can certainly support a push to a more standards driven development I'm not sure if you're slightly aggressive undertone will help here. Also given that most PHP projects older than the standards you linked took time to be ported over or never are it's not at all surprising for processwire to not follow them.

**Comment by nicdavies** [comment]
Apologies if I came across as aggressive, I'm just genuinely surprised is all. Could we get a CS tool set up within this repository and start taking on small chunks to refactor?

**Comment by LostKobrakai** [comment]
We have a written down [styleguide](https://processwire.com/docs/more/coding-style-guide/) for ProcessWire, so we'd need an implementation for that coding style. Without a major version jump coming up I doubt it would be a good idea to change the coding style to another one at the moment.

**Comment by nicdavies** [comment]
> Without a major version jump coming up I doubt it would be a good idea

I agree, I'll close this issue.

**Comment by ryancramerdesign** [comment]
LostKobrakai already linked the style guide, but wanted to add that the purpose of one-file-per-class is largely specific to autoloading classes. ProcessWire uses a PSR-4 compatible class loader, but ProcessWire's standard is that it does not require one-file-per-class unless the class needs to be loaded by the autoloader, requires a self-contained documentation page, or contains some significant implementation of its own. 

Nevertheless, I usually prefer one class per file, so that's the way it is 99% of the time. But there are some cases where it's best not to do that. Standards like PSRs understandably can't get into that, as they must remain tangible and portable to any PHP project and audience. For PW, related classes that don't need autoloading and don't have any substantial implementations of their own, it is better to group them in a logical manner and avoid multiple files when possible. Likewise, if there's a class that should not be instantiated independently of another (and likewise should not never pass through the autoloader), has little code of its own, and needs no independent doc page, it is preferable to define that class in the same file as the class that is allowed to instantiate it. 

This is a matter of organization, efficiency and optimization. You suggested it was "hideous", but I would suggest our approach is a quite a bit cleaner for our context. While there are a lot of similarities between PW's style guide and that of PSRs, there is no intention or plan to use a PSR style guide on this project, as we've already established our own that's quite a bit more refined to the needs of this project. Our style guide is very much specific to PW, and not intended for general purpose PHP projects like PSR-1 or 2 are.
