### ISSUE TITLE
Background gradients in ProcessLister table rows

### ISSUE THREAD

**Issue by gadgetto** [processwire/processwire-issues#824]
### Short description of the issue

Not sure if this is an issue or intended but ProcessLister has IMHO strange/ugly background gradients since PW 3.0.127. Especially the contrast (black on dark-grey) is not very easy on the eyes.

### Optional: Screenshots/Links that demonstrate the issue

<img width="1087" alt="bildschirmfoto 2019-03-04 um 14 04 24" src="https://user-images.githubusercontent.com/876737/53735534-766ef100-3e87-11e9-8155-5d0756524573.png">

### Optional: Suggestion for a possible fix

Revert back to previous subtle background transition.

### Setup/Environment

* ProcessWire version: 3.0.127

**Comment by adrianbj** [comment]
I believe this is a Safari only issue - I reported it almost a year ago: https://github.com/processwire/processwire-issues/issues/480#issuecomment-386669090

**Comment by ryancramerdesign** [comment]
@gadgetto That's definitely not intended. I can duplicate in Safari as well. I've narrowed it down to an apparent bug in Safari where a background style applied to the `<tr>` instead applies it individually to each of its `<td>` children as well as the `<tr>`. I've modified the style slightly so that it doesn't look as bad on Safari.

**Comment by gadgetto** [comment]
Looks better now but still weird if you have many fields:

![bildschirmfoto 2019-03-04 um 18 05 57](https://user-images.githubusercontent.com/876737/53749701-3cfaad80-3ea8-11e9-8042-d0e07cb58247.png)

**Why not simply change to a solid background like this:**

![bildschirmfoto 2019-03-04 um 18 08 22](https://user-images.githubusercontent.com/876737/53749820-8a771a80-3ea8-11e9-99bf-360c2654ddc6.png)

**Comment by gadgetto** [comment]
Or if gradient is really needed use this method:

https://stackoverflow.com/questions/13872860/gradient-applied-to-tr-renders-at-each-td-separately-how-to-create-horizontal-g

Set the gradient to the full table and only let it be visible in `tr.open` - all other rows could have background #fff

**Comment by ryancramerdesign** [comment]
I don't want to break the intended appearance here in other browsers just to accommodate a Safari bug. The intent here is to find something that is tolerable in Safari for the time being, without introducing hacks into the CSS.

**Comment by gadgetto** [comment]
I understand - to be honest I would do the same :)
It looks like this Safari bug exists since 2012. Probably will be never fixed :(

**Comment by Toutouwai** [comment]
Just want to second the idea that the row highlight style should be a solid background colour and not a gradient. The way the gradient fades to white makes it almost impossible to detect selected rows when you scan your eye down the leftmost column in the lister. In the screenshot below the "Can view system logs" row is selected but you wouldn't know it.

![2019-03-05_105623](https://user-images.githubusercontent.com/1538852/53765627-6f9eb780-3f35-11e9-8b39-1c3c7ddac322.png)

This is one the things that I "fix" in my custom CSS overrides for the admin.

**Comment by adrianbj** [comment]
I agree with @Toutouwai - I don't get the reason for the gradient. In general I think gradients don't provide any advantage and tend to look dated.

**Comment by szabeszg** [comment]
> gradients don't provide any advantage

This is a valid argument.

> and tend to look dated

This one is not a valid argument. You see, what is dated today will be trendy again tomorrow ;)

**Comment by adrianbj** [comment]
I would also make the argument that gradients in the lister are not consistent - in the main page tree we have a solid background on selection of a page.

**Comment by ryancramerdesign** [comment]
Look at this in any browser other than Safari and you'll see the reason for the gradient (which isn't really even visible as a gradient since it is very gradual). The entire purpose is to indicate the row is selected without having any hard edges on the left side, which is already highlighted by the opened page actions. If a solid color were to be used then the page label butts up right against the edge of the background color on the left which just looks bad. Yet horizontal space is extremely valuable here, I don't want to add 20px of padding there to accommodate a solid background color. Not only would I lose horizontal space but then I'd have double emphasis (a pet peeve of mine). The gradient makes it possible to indicate a selected row without consuming more horizontal space or adding double emphasis. 

I agree the fact that Safari has this bug makes it not the perfect output there, but like I mentioned before the intention here was to make it tolerable in Safari rather than letting Safari drive the entire approach.

**Comment by adrianbj** [comment]
I guess I don't understand why you're ok with the hard left edge and padding before the title in the main page tree, but not in the Page Lister?

![image](https://user-images.githubusercontent.com/871211/53813173-e1650a00-3f11-11e9-8c7d-ce5e7a712634.png)

**Comment by ryancramerdesign** [comment]
@adrianbj 

One is a `<table>` and the other is a list. Very different contexts. 

In Lister the opened page actions indicate the row is selected, in PageList they don't, as visibility is a hover state. Plus, PageList is labels, not rows. 

In PageList there is no hard edge with text butting up against it. In Lister there is (if solid background color). Before the gradient I originally started with a solid background color in Lister but couldn't live with it. 

In Lister, horizontal space is a valuable commodity. In PageList it isn't, padding is just fine.
