### ISSUE TITLE
Selector error with nested FieldsetPage

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#826]
### Short description of the issue

For Text field text_1 inside FieldsetPage field fsp_1 inside FieldsetPage field fsp_2...

![2019-03-07_144044](https://user-images.githubusercontent.com/1538852/53926150-46258d80-40e7-11e9-8a86-e9876ff54c7e.png)

Related forum topic: https://processwire.com/talk/topic/20995-inputfieldfieldset-inside-a-inputfieldfieldset-and-how-find-pages/

### Setup/Environment

* ProcessWire version: 3.0.127

**Comment by BitPoet** [comment]
I did a bit of digging since I stumbled over this as well. For nested FieldsetPages, FieldtypeRepeater::getMatchQuery is called for the exact page id with operator "=". In the conditional block [here](https://github.com/processwire/processwire/blob/dev/wire/modules/Fieldtype/FieldtypeRepeater/FieldtypeRepeater.module#L1397) PW rewrites the operator "=" to "~=", then a little [further down](https://github.com/processwire/processwire/blob/dev/wire/modules/Fieldtype/FieldtypeRepeater/FieldtypeRepeater.module#L1408) it throws because that operator is disabled in single page mode.

To my understanding, the operator substitution shouldn't happen at all in single page mode. I changed the condition in [Line 1397](https://github.com/processwire/processwire/blob/a7c3b001ce53c902d9f03e40373be041fd961131/wire/modules/Fieldtype/FieldtypeRepeater/FieldtypeRepeater.module#L1397) to
```php
			if(ctype_digit("$value") && !empty($value) && !$singlePageMode) {
```
This fixed it, and I spotted no immediate issues, but then I'm not that fluent in Repeater'ish.

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai and @BitPoet I've actually been meaning to get rid of that singlePageMode and let FieldsetPage have its own getMatchQuery() method (making it simpler), so went ahead and did that, which I think should fix this, though please let me know if you still observe any issues with it. Thanks.

**Comment by Toutouwai** [comment]
Thanks, it's working here.
