### ISSUE TITLE
ASMselect Modal and Firefox

### ISSUE THREAD

**Issue by tbba** [processwire/processwire-issues#833]
### Short description of the issue

On Firefox (latest version Mac) only, if I open a modal from a ASMselect Entry, and change anything there, that is not saved. It works on Safari and Chrome.

Anyone else having this too?

### Expected behavior

Should save things inside of the modal, when hitting save

### Actual behavior

Not saving

### Optional: Screenshots/Links that demonstrate the issue

![pw-bug](https://user-images.githubusercontent.com/652879/54744418-3e75e680-4bc7-11e9-9424-b2781858cdbc.gif)

(I hope the Gif is playing)

### Setup/Environment

* ProcessWire version: 3.0.127
* (Optional) PHP version: 7.2

**Comment by ryancramerdesign** [comment]
I just tried in Firefox 65 and Firefox 66 (latest version) but can't duplicate the issue here. Also testing on a Mac. Are you also running FF 66? Any other factors, 3rd party modules, etc., you can think of?

**Comment by tbba** [comment]
If it is not reproducible already, i search further now.

**Comment by tbba** [comment]
I tracked it down to a conflict with "PageEditFoldStatus" one of my basic set of modules which had installed on every instance from the beginnings.

_That brings me to the already known problem that it can be difficult in PW to track down module conflicts as they only can be deinstalled (thus forgetting their settings) and in some cases cannot even be deinstalled because they are used in fields. The WordPress way of activating/deactivating plug-ins without consequences are much easier for me for troubleshooting tasks. I will file a request in "requests"._ 

I can close this in a few days but I want the plug-in conflict to be recognized first.

**Comment by ryancramerdesign** [comment]
@tbba Glad you found the issue. Regarding disabling PW modules, they can't really be compared to WordPress plugins as they are completely different. PW modules aren't "active" unless some code asks for them. So the closest thing to an "active" state might be a module option in PW called "autoload", which means a module is automatically loaded and active on every request. Modules that attach hooks are typically autoload modules. There already is an option to temporarily disable an "autoload" module, but you must be in advanced mode for it to appear (`$config->advanced=true;`). Once advanced mode is enabled, you'll see a checkbox in the module info/config screen to disable a module. The reason it only appears in advanced mode is because there are some dangers with disabling modules, one being that PW supports module dependencies where one module may be dependent upon another. If a dependency is broken due to a disabled module, that could result in a fatal error. So while the option is already there (in advanced mode), I just recommend being careful with it.

**Comment by adrianbj** [comment]
>  If a dependency is broken due to a disabled module, that could result in a fatal error. 

Which is why Tracy's Module Disabler automatically generates an SQL file and restore.php script to get your system up and running again if disabling a module breaks things.

**Comment by tbba** [comment]
@ryancramerdesign - thank you for the explanation. The discussion about disabling modules was moved over to "Requests" which I thought was a better place - I will copy your explanation there so the people there get the latest feedback there too.
https://github.com/processwire/processwire-requests/issues/287
