### ISSUE TITLE
Don't assume a touch-capable device has no mouse

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#84]
### Short description of the issue

There are several instances in the PW core where a check is made to `$this->wire('session')->get('touch')` or `$this->wire('session')->touch` and the admin functionality changes as a result. I have (as do many people) a large-screen mouse-driven desktop device that happens to have touch capability. There's no need to force a different admin experience for such devices.

### Expected behavior

If admin behaviour must change for some devices the test should be for presence of a mouse, not touch capability.

### Actual behavior

Touch-capable mouse-driven devices unnecessarily get limited admin functionality.

### Optional: Suggestion for a possible fix

I'm not sure of the best way to test for mouse presence, but I'm sure there is some solution.

Edit: there's lots of discussion around about this. Different solutions are proposed, but one common agreement is that detecting touch _capability_ is not a good way of determining if a device is touch _driven_.

This is one proposed solution: https://coderwall.com/p/vo0bua/detecting-user-interaction-type-mouse-or-touch

---

Related issues in the old repository: 
https://github.com/ryancramerdesign/ProcessWire/issues/1425
https://github.com/ryancramerdesign/ProcessWire/issues/1386

* ProcessWire version: 3.0.40

**Comment by Toutouwai** [comment]
I had a look through the core for places where admin functionality changes for touch. 

(1) Debug and Quick Tree icons in breadcrumb.
Can't see why these need to be disabled for touch devices.

(2) Dropdown menus on Submit buttons.
Maybe this dates back to before the split button was implemented? With the split button the dropdowns should work on touch devices so no need to remove the functionality.

(3) Dropdown menus for top-level items in the default admin theme menu.
I've been using a slightly modified version of [Bernhard's solution](https://gitlab.com/snippets/20195%C2%A0) for front-end menus for a while now and it's great. It's a better way to go because it looks at mouse movement rather than touch capability. The version I use is below - not hard to adapt for the default admin theme.
```
// Menu hover for touch devices
var hoverLink = $('.desktop-nav .level-1.has_children > a');
hoverLink.click(function(e) {
	// prevent click when delay is too small
	var delay = Date.now() - $(this).data('hovered');
	if(delay < 100) e.preventDefault();
});
hoverLink.mouseover(function(e) {
	var time = Date.now();
	$(this).data('hovered', time);
});
```

(4) Page List hover actions.
Could use same JS solution as (3).

(5) Long-click actions in Page List
Not sure why these need to be explicitly removed for touch devices. I haven't tested but I would expect the long-click to either not work (so no different from not implementing it for touch devices - the current approach) or work (great).

**Comment by ryancramerdesign** [comment]
Thanks for the testing. The purpose of the touch-device class wasn't to remove capabilities from touch devices, but rather to make them work property on the touch devices that I have access to (which includes 2 Android phones and an old iPhone). If there's a check for touch-device, then that's because a particular feature needed it in order to work properly on a touch device, or in some cases, needed to be disabled because I couldn't get it to work properly on a touch device. If I were to just remove the touch detection, then I'd be breaking things on the touch-only devices it was added for, which I'm guessing are more widely used than touch+mouse devices. 

I don't have access to a device that supports both touch and mouse, so don't currently have any way to code and test for this. As a result, I'm not sure I can feasibly do much here except provide a config option ($config->detectTouch) where you can dictate whether it should attempt touch detection? 

The library that you linked to looks interesting–thanks. Maybe this will provide a workable strategy long term. Right now I'm not sure it's there yet, because it wasn't detecting my computer properly. But I will definitely keep an eye on it.

**Comment by Toutouwai** [comment]
I understand it's not easy to test on a broad range of devices - I'm in the same boat because I've got Android and iOS phones and an iPad, but no Android or Windows tablet to test on.

I do think touch testing should extend beyond phones though - tablets are a big part of the market.

I will remove all the touch-specific admin changes and test on my touch devices. Will report back, maybe with some pull requests incorporating my suggestions above.

**Comment by adrianbj** [comment]
I have to agree with this. My partner has a touchscreen laptop and there are issues with PW admin navigation. Not sure how many are critical, but it's weird for example that the page list action buttons only work on click, not on mouseover even though she uses a mouse/trackpad.

**Comment by pwFoo** [comment]
I have a Surface Pro 4 with two external displays using the SP4 dock. The "Pages" link (or any other top level admin link) isn't clickable. Same if I use the touchscreen. It's a little bit confusing.

Workaround to reach the page tree or click "Pages -> Find" and then "Pages" at the breadcrumb to find the page tree. Or just "Admin" at the breadcrumb navigation. Drop down title should be clickable or add "Pages" / "Tree" to the "Pages drop down.

**Comment by Toutouwai** [comment]
A couple of things to report...

-----

Firstly, I set up an installation for testing touch issues in PW, where I did nothing else but remove all the touch-specific admin behaviour that I could find. Below are the results of testing on an iPad and iPhone (I have an Android tablet on order and can borrow an Android phone so will test those later).

### (1) Debug and Quick Tree icons in breadcrumb

These work fine.

### (2) Dropdown menus on Submit buttons (split buttons)

These work fine. There are minor CSS layout issues on the bottom submit buttons (the top buttons render fine - not sure why there is a difference). On some buttons (wider ones?) the caret portion of the button renders on a new line, and on others the caret portion moves down slightly when touched.

### (3) Main admin dropdown menus.

One of the annoyances of the default behaviour for touch devices is that it's impossible to navigate to the top-level items. For example, clicking the 'Setup' tab will open the dropdown but you cannot navigate to the 'Setup' page (particularly annoying for the 'Pages' tab). Also, in the first dropdown you cannot open any of the submenus (Templates, Fields, etc).

Turning off the touch tests solves the first issue, in iOS at least. The first touch on a tab opens the dropdown, the second touch navigates to the page associated with the tab. Not sure if Android implements the same 'two touch' behaviour though, and will test when I'm able. The second issue remains and I'll look at that some more.

### (4) Page List hover actions

For touch + mouse devices the change is an improvement (the actions show on hover) but for touch-only devices the change is not ideal: now the first touch shows the hover actions and the second touch activates/expands the branch. It would be better if these occurred simultaneously on touch-only devices (which they do with the default behaviour).

### (5) Long-click actions in Page List

These don't work on touch-only devices, which is to be expected. But it seems there's no need to explicitly remove long-click actions for touch devices as they don't cause any errors that I noticed. 

I'm not sure the existing touch test actually works anyway as the long-click attributes are rendered even on touch devices. I think the [check to the body class](https://github.com/processwire/processwire/blob/d935e9b6995124d76e6fda17fd47ab46dc4d3a3c/wire/modules/Process/ProcessPageList/ProcessPageList.js#L132) is wrong:

`var isTouch = $("body").hasClass("touch");`

The class added for touch devices is 'touch-device' not 'touch'.

-----

Secondly, I think there is a simple solution to the touch + mouse vs touch-only situation.

Currently the main test for touch devices occurs in [ProcessLogin.js](https://github.com/processwire/processwire/blob/d935e9b6995124d76e6fda17fd47ab46dc4d3a3c/wire/modules/Process/ProcessLogin/ProcessLogin.js#L17):

`var touch = (('ontouchstart' in window) || (navigator.MaxTouchPoints > 0) || (navigator.msMaxTouchPoints > 0));
$("#login_touch").val(touch ? 1 : 0);`

Then ProcessLogin.module checks `login_touch` and sets the 'touch' session variable accordingly which the other touch-specific behaviours flow on from.

I propose a different test in ProcessLogin.js to distinguish between mouse users and touch users:

```
var $login_touch = $('#login_touch');
var $submit_btn = $('#Inputfield_login_submit');
$login_touch.val(0);
$submit_btn.mouseover(function() {
    var time = Date.now();
    $(this).data('hovered', time);
});
$submit_btn.click(function() {
    var delay = Date.now() - $(this).data('hovered');
    if(delay < 100) $login_touch.val(1);
});
```

In my testing this has proved very reliable. It is impossible (or close to it) for a mouse user to click the submit button less than 100ms after their mouse enters the button. And touch users have no way to login apart from touching the submit button so the test will always catch them.

-----

So to conclude, I think:

- The touch-specific behaviours for (1), (2), (3) and (5) can be removed as they are not necessary and negatively impact touch + mouse users.

- The new touch-only test would solve issue (4) for both touch + mouse and touch-only users.

- (2) needs a CSS fix for iOS devices. I'll look into this.

- (3) needs a solution for accessing submenus on touch-only devices. I'll look into this. IMHO these main menus would be more manageable if they were simple nested `<ul>`s rather than appended to the body and positioned with Javascript as they are currently. Maybe the admin menu system could move to this?

@ryancramerdesign, I'm happy to make pull requests for any of this if you like.

**Comment by adrianbj** [comment]
@Toutouwai - I am excited to see what you have achieved, but I was also wondering if you have seen this library: https://github.com/ten1seven/what-input

This was mentioned in the PW weekly because the Site of the Week uses it - looks like it might be a decent option?

**Comment by Toutouwai** [comment]
Thanks @adrianbj - that library is new to me and looks good. Will wait to see what @ryancramerdesign thinks about all this.

**Comment by ryancramerdesign** [comment]
@Toutouwai thanks for all the research and testing you did here. I've been working with some stuff here and have pushed this commit which may solve some of it:
https://github.com/processwire/processwire/commit/b8e51db1767b2bad6abb8d15ef10020df866c2d9

I did try using the ProcessLogin.js update you mentioned, but it wasn't detecting touch devices for me. Turns out it's because there was no touchstart event triggered on the login page because I jumped between login/pass fields with tab, and submitted with enter (or whatever the arrow thing is on a mobile device keyboard). So it looks like in order for that bit of code to work, one would have to touch the fields and submit button, rather than doing it all with the mobile keyboard. As a result, I thought we were better off sticking with the current touch detection, but changing the way that we use it.

For most of the stuff that affects touch, I change it so that it basically waits for a touchstart event to occur before it changes the way that it works with things. That way, hopefully with the Microsoft touch screen devices, it won't interfere with anything unless you start using it as a touch screen. 

I used Chrome dev tools to test between iPhone6, iPad and Nexus6 (Android), and get everything working exactly the same between iOS and Android. What I found was that things have changed in iOS – stuff that used to need code to work properly no longer needs it. So it looks like they've fixed some things in Safari since the touch code in PW was originally written. I did still have to code around Chrome mobile though. Rather than do messy browser detection, I just kept working till I could get the same code to work the same way between both platforms. Though this has all been in Chrome's dev tools, so it remains to be seen whether this plays out correctly on the real devices. If you get a chance to test it out, please let me know. 

> IMHO these main menus would be more manageable if they were simple nested <ul>s rather than appended to the body and positioned with Javascript as they are currently. Maybe the admin menu system could move to this?

I would also prefer that it nested them in with the existing menu, but this is the way that jQuery ui-menu works, so I don't have a choice about this one.

**Comment by Toutouwai** [comment]
@ryancramerdesign, many thanks for the changes in the recent commit! Things are working great for me now on both touch+mouse and touch-only devices.

Of the things I raised above, the only thing I noticed remaining is the layout of the bottom split submit buttons in iOS. I tested in Safari and Chrome and the result is as per the screenshot below. The first broken button is obvious but also note the slight misalignment of the caret portion of the second button. The top submit buttons display normally.

![img_0546b](https://cloud.githubusercontent.com/assets/1538852/20821240/cf4d051a-b8a5-11e6-939d-3db8137af9a1.png)

**Comment by ryancramerdesign** [comment]
Thank for testing, glad to hear it sounds like we've got most of the issues fixed. 

Regarding the lower buttons, this is the only thing I can't reproduce using Chome's developer tools. I tested for iPad and iPhone6, but the buttons appear normally. Though if I drag the screen to be narrow enough I can see the button wrap at the top (and also a little different from screenshot), and strangely only at the top, not the bottom. Still, maybe that issue is related. I think the "Save + Keep Unpublished" label is just too long for narrow displays. I've added an option that makes it instead use a shorter "Save" label when you login with a narrow viewport. I have no idea if this will solve the issue you are seeing there, but it's one of those things that I thought I should add either way. Please let me know if you find it helps at all. Thanks.

**Comment by Toutouwai** [comment]
The screenshot I posted is from an iPad, so it's not a viewport width issue - I just cropped the screenshot down to show the relevant part. 

It's difficult debugging device browser issues without dev tools on the device, but I did make some progress:

The minor alignment issue of the caret button can be resolved by:

`.InputfieldSubmit button { vertical-align:top; }`

The breakage of the first button is quite weird. I prevented the line break and coloured the background of the Inputfield `<li>` to better see what's going on:

`.InputfieldSubmit { background:red !important; white-space:nowrap; }`

From the screenshot below, it's like the containing element doesn't allow space for the caret button, but only for the Publish inputfield. The adjacent Save button and inputfield has the same markup so I don't see what the difference is. Might be some weird iOS WebKit bug.

![img_0547b](https://cloud.githubusercontent.com/assets/1538852/20855952/5ea96a3c-b969-11e6-9be6-417a12d75ce0.png)

What worked was floating the submit buttons, and if that is done the vertical align rule isn't needed:

`.InputfieldSubmit button { float:left; }`

![img_0548b](https://cloud.githubusercontent.com/assets/1538852/20855954/648aa34e-b969-11e6-8f96-a48c9d689c97.png)

**Comment by Toutouwai** [comment]
A time-consuming investigation into why the FormBuilder field editor was not opening in a modal window has put this issue back on the radar for me.

I think that the usage of the 'touch' session variable needs to be looked at. Some things I have been pondering:

- What is the reasoning behind the 'touch' session variable? 
- When that variable is checked in the core or a module is the test really about the ability for the user's device to respond to touch, or is it being used in an attempt to answer some other question about the user and their device? Such as: Does it have a small screen? Does it have a mouse attached, and if so is it being used for input? 
- If it's the latter and there are good reasons why the core/modules need to respond differently to various device attributes, should a more complete set of device attributes be stored in $session? Perhaps some Modernizr-style array of device attributes and capabilities.
- Is a single check of device attributes at login sufficient? What if I login with my touch-capable device but then I plug in my mouse? Probably not a major concern, but something to think about.

In the meantime, to get FormBuilder behaving the way I want I have made a simple module using the [What Input](https://github.com/ten1seven/what-input) utility @adrianbj mentioned above. The module hooks ProcessLogin and uses What Input's more sophisticated device detection to override the default touch detection.
https://github.com/Toutouwai/InputDetect

**Comment by ryancramerdesign** [comment]
Maybe your module would make sense as a core addition to ProcessLogin? (where that session variable is set). 

The touch property is there to indicate whether the user is using a touch device for input. What one uses that for is at discretion, but I thought it useful to provide. Definitely don't use it for detecting screen size though. In my case, I use it to disable things that may be problematic with that kind of input, or enable things that may benefit for it. 

I think a single check at login is sufficient to determine these kinds of things about the client. I wouldn't want to add the overhead of checking these things on every request.

**Comment by Toutouwai** [comment]
> Maybe your module would make sense as a core addition to ProcessLogin? 

Yes, I think What Input would be a better way to test for touch input in ProcessLogin.

Regarding the use of the 'touch' session variable to change interface behaviour: my impression is that in the past most of the changes applied for touch devices have been unnecessary, i.e. touch devices handle the default interface behaviour just fine. I covered some of that [above](https://github.com/processwire/processwire-issues/issues/84#issuecomment-262865534). And for the recent situation with FormBuilder and modals: if I force the 'touch' variable to 0 and test the modals in touch-only devices they work great - even on phones.

I regularly use touch devices on the web, especially an iPad, and I rarely come across an interface anywhere that doesn't work with touch. So in general I think that a conservative approach to changing the PW admin interface behaviour for touch would be good: only change it if there's general agreement that there's a real problem with the default behaviour.

**Comment by gmclelland** [comment]
I noticed that https://github.com/ten1seven/what-input is included with Zurb Foundation 6.  See http://foundation.zurb.com/sites/docs/accessibility.html#foundation-and-accessibility

**Comment by Toutouwai** [comment]
@ryancramerdesign, you mentioned potentially integrating [What Input](https://github.com/ten1seven/what-input) into ProcessLogin.

I'm still keen to see that - then I can drop my [custom module](https://github.com/Toutouwai/InputDetect).

**Comment by ryancramerdesign** [comment]
Thanks for the reminder @Toutouwai I have just added this.

**Comment by Toutouwai** [comment]
Thanks!
