### ISSUE TITLE
WireArray::sort() should use SORT_LOCALE_STRING

### ISSUE THREAD

**Issue by hgassen** [processwire/processwire-issues#841]
### Short description of the issue

WireArray::sort() should use the flag SORT_LOCALE_STRING instead of the default flag (SORT_REGULAR).

### Expected behavior
When sorting a PageArray by one of the -- possibly multilingual -- page fields (e.g. title), I expected the result to honor the current locale.

### Actual behavior
WireArray::stableSort() (called by WireArray::sort()) uses the default flag (SORT_REGULAR) that ignores the current locale.

### Optional: Suggestion for a possible fix
Specify SORT_LOCALE_STRING for ksort() and krsort() in WireArray::stableSort() or let the user request a flag when calling WireArray::sort()

### Setup/Environment

* ProcessWire version: 3.0.127

**Comment by ryancramerdesign** [comment]
Thanks @hgassen good idea, I have added support for PHP SORT_* constants to the WireArray::sort() method, as well as a sortFlags() method for setting a default for future calls. However the core must use SORT_REGULAR as its original default since we can't make any assumptions about what will be sorted, but now it can be overridden according to your needs.

**Comment by hgassen** [comment]
Thank you, @ryancramerdesign, very useful!

FYI, class Fieldtypes complains that the signature has changed:

`Warning: Declaration of ProcessWire\Fieldtypes::sort($properties) should be compatible with ProcessWire\WireArray::sort($properties, $flags = NULL) in […]/wire/core/Fieldtypes.php on line 156
`

**Comment by ryancramerdesign** [comment]
Thanks @hgassen I have updated that Fieldtypes method. Also ran a global search to if there were any more that needed a similar update but doesn't look like it.
