### ISSUE TITLE
PW 3.0.129: active tab when page is loaded gets muted style

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#847]
### Short description of the issue

A very minor issue - not sure if it's intentional or not. In PW 3.0.129, AdminThemeUikit, the tab that is active when the page is loaded gets a "pw-tab-muted" style that gives it a grey background.

PW 3.0.129
![2019-04-10_231325](https://user-images.githubusercontent.com/1538852/55874482-9a3ff800-5be6-11e9-9a57-91ea9aab2a57.png)

PW 3.0.128
![2019-04-10_231358](https://user-images.githubusercontent.com/1538852/55874495-a4fa8d00-5be6-11e9-90e6-8ee8455fb5f9.png)

Page Edit is not affected for some reason. Is the style deliberate? It doesn't seem to add much in terms of meaning or usability and it's a bit odd that is doesn't apply to other tabs as they made active - so it's like it doesn't mean "active" but "active and was active when the page was loaded". But what is the significance of that to the user?

**Comment by matjazpotocnik** [comment]
I don't think it's deliberate, it's possible a bug in main.js in wireTabClick function not properly recognizing the background color of the tab content.

**Comment by matjazpotocnik** [comment]
It happens on template edit too. Related to this: https://github.com/processwire/processwire/commit/45d6158be1f91dbc1082d731ec63019fd7cd491e 

Lines 108-112, looks like wiretabclick is triggered too soon. It doesn't happen in ProcessPageEdit, because wiretabs are already there using new renderTabList() method, while ProcessFields is using the "old" method. I fixed it by wrapping the trigger in 500ms timeout...

There is a lot of javascript processing in admin theme(s). It would be good if we could reduce this processing and jumping and fouc and settimeouts and clicking and ...

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I've pushed a fix for this

**Comment by Toutouwai** [comment]
Thanks.
