### ISSUE TITLE
Cached 301 redirects make adding new pages impossible

### ISSUE THREAD

**Issue by daun** [processwire/processwire-issues#848]
### Short description of the issue

When adding a new page under an existing page from the PageList (hover over a page and click the »New« button on it), the user is then redirected to the newly created page:

`/page/add/?parent_id=1234` »»» `/page/edit/?id=1235&new=1`

This redirect is happening as a 301 and causes issues with aggressive browser caching. In certain cases, the browser won't ever request the first URL and just redirect to the second URL from its cache. The new page is never created and the user is redirected to an old page (maybe even in the trash or non-existing).

The only solution I found was telling people to disable their browser cache completely which is not viable for non-developers.

### Expected behavior

Redirect with a 302 so the redirect can't be cached.

### Actual behavior

Redirect with a 301, risking browsers caching a temporary redirect.

### Optional: Suggestion for a possible fix

Use the 302 flag on `session()->redirect($url, true)` for internal redirects with dynamic parameters like IDs or role-based config.

### Setup/Environment

* ProcessWire version: 3.0.123

**Comment by ryancramerdesign** [comment]
I can't duplicate this one. Can you provide instructions on how to duplicate it and any necessary configuration? (along with browser and platform). Thanks.

**Comment by daun** [comment]
The issue appears in certain networks where HTML (and therefore 301) responses are cache-able. So it's a network/proxy config issue, but seeing how using 302s completely solves the problem for all users, we should probably be using those. Are there any drawbacks to 302s I can't think of?

The below screenshot is from Chrome on MacOS.

<img width="821" alt="Screenshot 2019-04-11 at 18 25 13" src="https://user-images.githubusercontent.com/22225348/55974710-8f3da400-5c88-11e9-83d3-ffcbac101688.png">

You can see that the 301 response comes from the disk cache — it was cached from the previous page-add. When clicking the "New" button again, instead of requesting the add-new page again and being redirected to the new page, the user is redirected to the page that was created on the previous page-add. The response (a 301) was cached by the browser, so the new page is never created.

**Comment by ryancramerdesign** [comment]
@philippdaun PHP sends cache control headers that prevents this kind of caching, so as far as I know, it should not matter to the browser if it's a 301 or a 302 redirect since the browser is not allowed to cache. Is it possible your cache control headers are overridden in PHP's config, or something like that? If that's the case, I think a better solution may be for us to override the cache control headers in the admin (by sending our own) since using `$session->redirect()` with default arguments is common for pretty much every Process module, both core and 3rd party.

**Comment by daun** [comment]
@ryancramerdesign Good idea! That sounds like the solution to me. In this particular case a `.htaccess` is sending cache headers for all `text/html` responses (including the admin panel) and I feel like ProcessWire should be able to work in such an environment as well, e.g. by explicitly setting cache control headers as suggested by you. Let me know if I can be of any help in implementing this.

**Comment by ryancramerdesign** [comment]
@philippdaun PHP by default sends cache control headers that would override those set in the .htaccess file. That's why I was wondering if maybe that behavior is disabled or overridden in your PHP config. You could try adding the following to your /site/templates/admin.php file after the `namespace ProcessWire;` line to see if this makes a difference?
~~~~~
header('Cache-Control: no-store, no-cache, must-revalidate');
header('Expires: Thu, 19 Nov 1981 08:52:00 GMT');
header('Pragma: no-cache'); 
~~~~~
The above are just the headers that I noticed the copy of PHP on this computer is sending automatically, so not positive all of them would be necessary.

**Comment by daun** [comment]
@ryancramerdesign Yes, that's what I currently do on servers that seem to cache the redirects — add the no-cache headers manually in `admin.php`.

Do you think this will have an impact on performance? I'd guess the `no-cache` headers are the desired behaviour for PW's admin anyway.

How do you feel about adding this to the core? I will move those header declarations into my boilerplate project, but just wondering if we can avoid the issue for others as well.

**Comment by ryancramerdesign** [comment]
@philippdaun No concern about impact on performance. As for adding to the core, we'd definitely want to do that if this were a common thing, but yours is the first instance I've come across where this occurs. I'm going to be keeping my eyes out for this one though. If it pops up with anyone else, then I think a change may be warranted. If we were to make a change, likely we'd do a [session_cache_limiter](https://www.php.net/manual/en/function.session-cache-limiter.php) call in our Session class, rather than doing header() calls manually. But in your case, you are only seeing issues on the admin side, so I think the header calls in your admin.php makes sense here.

**Comment by daun** [comment]
@ryancramerdesign Sounds good! Closing.
