### ISSUE TITLE
WireHttp: curl_setopt not compatible with PHP 5.4

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#849]
### Short description of the issue

WireHttp contains [this line](https://github.com/processwire/processwire/blob/da309f335b3f4bef4a4c8709647757b5080f5781/wire/core/WireHttp.php#L637):

```php
curl_setopt($curl, CURLOPT_SAFE_UPLOAD, true);
```

But this option was [added in PHP 5.5.0](https://www.php.net/manual/en/function.curl-setopt.php) and so gives an error in PHP 5.4.

### Setup/Environment

* ProcessWire version: 3.0.129

**Comment by teppokoivula** [comment]
This is one of those cases where I'd seriously consider raising the minimum version to 5.5 instead of removing a security feature, or even adding a version check around it.

This option is (for a good reason) causing deprecation notices as of 5.5, enabled by default as of 5.6, and technically always enabled (option to disable it is removed altogether) as of 7.0.

**Comment by ryancramerdesign** [comment]
Thanks I've pushed an update for this, allowing CURL for the send() method only in PHP 5.5+. I don't think we need to change the required PHP version since it can be easily coded around. sendCURL() method is a fallback method that we don't really even need, but just wanted it for the specific times when both fopen and sockets might not be available for one reason or another.

**Comment by teppokoivula** [comment]
>  I don't think we need to change the required PHP version since it can be easily coded around.

That's true, it can be easily coded around.

This is related to an earlier discussion we had regarding recommended/required PHP version, so no need to go too deep into it (again), but in my opinion it's a good idea to clearly signal users that they should not use insecure features and versions – and dropping support for legacy PHP versions is one way to do that.

In other words the core *shouldn't* make it easy to stick with potentially insecure PHP versions, even if it *can* :)
