### ISSUE TITLE
$sanitizer->pageName returns empty string

### ISSUE THREAD

**Issue by Lazerproof** [processwire/processwire-issues#854]
### Short description of the issue

When string that is passed to sanizer method begins from some special characters $sanitizer->pageName returns empty string instead of sanitized value. 

### Expected behavior

Get sanitized value.

### Actual behavior

Empty string.

### Optional: Screenshots/Links that demonstrate the issue

![sanitizer-test](https://user-images.githubusercontent.com/5707348/56100539-a8fa1800-5f22-11e9-86f8-92bcf1acba9b.png)

### Setup/Environment

* ProcessWire version: 3.0.130
* (Optional) PHP version: 7.2.4

**Comment by ryancramerdesign** [comment]
Thanks @Lazerproof I've pushed a fix for this issue.

**Comment by Lazerproof** [comment]
@ryancramerdesign Thanks, but the commit fixes the issue partially. Now sanitizer trims everything between «» and <>. 
![image](https://user-images.githubusercontent.com/5707348/56280063-1d46de00-6112-11e9-8351-e2987f03783a.png)

**Comment by ryancramerdesign** [comment]
@Lazerproof That's correct, it's because a strip_tags() is run on the value, as name sanitizers can encounter HTML tags. We don't want those tags to be part of the returned name, except as a fallback. This ensures that given input like `foo <strong>bar</strong>` it resolves to `foo-bar` and not `foo-strong-bar-strong`. So if there's something that looks like it's opening an HTML tag or there is a full HTML tag, it's not going to use the apparent tag name unless there's nothing else it can use in the string. The error in the behavior before was that it was returning a blank string when it didn't need to, so I fixed that. Why PHP's strip_tags() considers a character like `«` to be equivalent to `<` as opening an HTML tag, I don't really know, but I'll trust they have a good reason.

**Comment by Lazerproof** [comment]
@ryancramerdesign 
That all sound reasonable, but, honestly, I don't think that the pageName method should act in such a way. What you have described is more like 'markupToText' method which is intended to strip tags, where pageName is intended to generate page names which become pages URLs that's why it should save all meaningful part of the text.
The combination of pageNameTranslate and selectorValue methods gives, as for me, more expected result.
![image](https://user-images.githubusercontent.com/5707348/56308212-5e111800-614f-11e9-860c-3e6c4f1fd1f4.png)
Also, could you please confirm that behavior with dots in my exaples is not a issue? Or should I open an issue for that case?
