### ISSUE TITLE
UIkit admin theme - field/fieldgroup not collapsing when clicking on label

### ISSUE THREAD

**Issue by gadgetto** [processwire/processwire-issues#855]
### Short description of the issue

If you click on field/fieldgroup label in UIkit admin theme, the field/group is not  collapsing. If you click on the toggle icon the field/fieldgroup is collapsing as expected.

**From now on you can also collapse the field/fieldgroup by clicking on the label.**

### Expected behavior

The field/fieldgroup should collapse/expand by clicking on its label. 

### Actual behavior

The field/fieldgroup does not collapse/expand by clicking on its label. (only if previously collapsed by clicking on the toggle icon)

### Screen recording that demonstrates the issue

![fieldset-header-collapse](https://user-images.githubusercontent.com/876737/56272938-0b5a4080-60fc-11e9-8ed7-fb45f141e7e3.gif)

### Optional: Suggestion for a possible fix

If you look at the screen recording you can see a strange calculation happening for opacity property on toggle icon. If you once click on the toggle icon this calc is gone.

### Setup/Environment

<strong>Server Details</strong>

|Software|Version|
|------:|:-------|
|ProcessWire|3.0.129|
|PHP|7.2.14|
|Webserver|Apache|
|MySQL|5.7.25|
<details><summary><strong>Server Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|allow_url_fopen|1|
|max_execution_time|30 (changeable)|
|max_input_nesting_level|64|
|max_input_time|60|
|max_input_vars|1000|
|memory_limit|128M|
|post_max_size|8M|
|upload_max_filesize|32M|
|xdebug||
|xdebug.max_nesting_level||
|mod_rewrite|1|
|mod_security|*confirmed off|
|GD|bundled (2.1.0 compatible)|
|GIF|1|
|JPG|1|
|PNG|1|
|EXIF Support|1|
|FreeType|1|
|Imagick Extension|1|
</details><details><summary><strong>Module Details</strong></summary>

|Module ClassName|Version|
|------:|:-------|
|FieldtypeMessageMeta|0.0.1|
|InputfieldMessageMeta|0.0.1|
|MarkupSnipWire|0.0.1|
|ProMailer|0.0.7|
|ProcessGroupMailer|0.0.1|
|ProcessMessageLister|0.0.1|
|ProcessProMailer|0.0.7|
|ProcessSnipWire|0.0.1|
|ProcessTracyAdminer|1.0.6|
|ProcessWireUpgrade|0.0.7|
|ProcessWireUpgradeCheck|0.0.7|
|SnipWire|0.0.1|
|TracyDebugger|4.19.11|
</details>

**Comment by ryancramerdesign** [comment]
Hi, this is the way it is designed to work (and always has been), not just in the Uikit admin but all of the admin themes.

**Comment by gadgetto** [comment]
Really? Collapsing fields/fieldgroups by clicking on its label should only be able if the field/fieldgroup was at least once collapsed by clicking on the toggle icon?
I don't understand the point.

**Comment by ryancramerdesign** [comment]
This is the intended behavior, and true for all Inputfields (not just Fieldsets). When not setup as a collapsed Inputfield, clicking a field label is supposed to focus the input within it (text, textarea or select). This is basically standard behavior for any HTML form using label elements with "for" attributes that point to the input. Inputfield headers are `<label>` elements with "for" attributes. 

However, unlike a standard HTML form, any field in our forms can be open or collapsed. So if you've got an Inputfield that is collapsed, then it has to be opened before it can be focused or used. A collapsed Inputfield shows the label, but there is no visible input to focus on. So we must open the Inputfield before it can be focused or interacted with. As a result, clicking on the label opens the Inputfield, so that it can complete the focus. Once the label is used in that manner, there's a good chance you might repeat the action to close it, so the behavior sticks. Either way, the right-side toggle icon is the universal way to open/close any Inputfield. We're trying to be consistent with HTML forms while also supporting open/collapsed fields. Maybe it would be more clear if the label never opened the field, but I would also find that a lot less convenient. Since this is true of all Inputfields, it's also true of Fieldsets as a matter of consistency (since they are also a type of Inputfield).

**Comment by gadgetto** [comment]
Thanks Ryan, now I understand and it's logical. I'll close this issue.
