### ISSUE TITLE
FileCompiler issue with @include

### ISSUE THREAD

**Issue by rolandtoth** [processwire/processwire-issues#86]
### Short description of the issue

A "@include" causes the FileCompiler to compile file with syntax error (space after "@"):

`
if (!$this->isExpired($file, $name) && (@ include(\ProcessWire\wire('files')->compile($file) !== FALSE) {
	return;
}
`

### Expected behavior

Compile to `@include` instead `@ include`

### Link to file (third-party)

https://github.com/nette/latte/blob/70ac0c8782f4ba8ae7bafd3097fcadc63d954aeb/src/Latte/Engine.php#L171

* ProcessWire version: 3.0.40
* (Optional) PHP version 7.012

**Comment by ryancramerdesign** [comment]
The "@include" vs "@ include" is stylistic, I'm pretty sure that doesn't matter to PHP. But the issue you'll run into with the code you mentioned is that it's an include statement in an if() statement. That's a scenario that FileCompiler isn't able to support at present. It needs for the include/require statements to be on their own in order to work property. If possible I'd suggest doing this instead:

~~~~~
if(!$this->isExpired($file, $name)) {
  $result = @include($file); 
  if($result !== false) return;
}
~~~~~
or this
~~~~~
if(!$this->isExpired($file, $name) && file_exists($file)) {
  include($file);
  return;
}
~~~~~

**Comment by rolandtoth** [comment]
Thanks for the info. Unfortunately this file is 3rd party so I can't edit it. But it's not a big deal, I use it in one of my modules and I can manually edit the file when I update that file.

**Comment by ryancramerdesign** [comment]
For a 3rd party library like this, I would probably just tell FileCompiler to keep out of it, because there's no need for that stuff to be compiled, since it's totally independent of ProcessWire. Rather than including those libraries from your main file, setup a separate file that includes the other libraries, and add a `// FileCompiler=0` comment at the top of it. 

library-include.php
~~~~~
<?php
// FileCompiler=0
include(__DIR__ . '/SomeLibrary.php'); 
~~~~~
This is one way to do it anyway. You could also just add the `// FileCompiler=0` to the top of the file you linked to earlier, but the you'd have to add it every time you upgraded the library, which wouldn't be as desirable.

**Comment by rolandtoth** [comment]
Good tip, unfortunately I couldn't use. I include an "autoload.php" and that includes another file and so on, and it seems the FileCompiler=0 is not in effect. However I bypassed the autoload.php and directly included the file I need and the error is gone, without disabling the filecompiler.

**Comment by mikerockett** [comment]
@ryancramerdesign - Does this solve my issue mentioned before where I want to exclude the vendor directory? Would it work as intended if I had the main module file call `bootstrap.php` with `FileCompiler=0` which then includes the Composer autoloader?

**Comment by ryancramerdesign** [comment]
@rolandtoth you could probably just put the FileCompiler=0 in that autoload.php file. 

@mikerockett yes I think it would, but didn't we already talk about this? (I can't remember). Either way I'm still planning to add the additional exclusion options.

**Comment by rolandtoth** [comment]
> you could probably just put the FileCompiler=0 in that autoload.php file

Yes, but that's identical to what I have done before (autoload.php is part of the library).

**Comment by mikerockett** [comment]
@ryancramerdesign - I have tried, it appears to run through all the files anyway, where as I'm looking for a [per-directory exclusion](/processwire/processwire-requests/issues/18) ([PR](https://github.com/mikerockett/processwire/commit/b6bb69698aff8607375d1ad9f8a5edf9f62a02ad)).

**Comment by ryancramerdesign** [comment]
@rolandtoth Another exclusion option was added which lets you exclude the files from the include() or require() statements that include them by just specifying the `/*NoCompile*/` PHP comment somewhere in the include/require function call: 
~~~~
include(/*NoCompile*/' __DIR . '/file.php'); 
~~~~
