### ISSUE TITLE
Markup Regions execution in non-template file not working (bug or by design?)

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-issues#861]
Assume your _main.php file (which is included by ```$config->appendTemplateFile```) is like this (I've simplified here for the sake of demonstration):
```
<?php namespace ProcessWire; ?>
<!doctype html>
<html>
  <head>
    <pw-region pw-id='css-files'></pw-region>
  </head>
  <body>
    <link rel='stylesheet' href='<?php echo $config->urls->templates; ?>app.css' pw-append='css-files'>
  </body>
</html>
```

Notice how I have a region called 'css-files' in ```<head>```.  Also notice how in ```<body>```, I'm trying to append to that region.  Unfortunately it does not execute.  If that injection line was in a template file like home.php instead, it will work.

I believe this is either by design OR a bug.

I made a video that walks through it a little bit more with my thoughts and an example use case:
https://www.youtube.com/watch?v=BT71C4_6Zk4

(note: in the video I erroneously said the region disappears, but that's proper functionality if a region is blank; sorry about that).

**Comment by Toutouwai** [comment]
I don't think this is a bug because the [Markup Regions documentation](https://processwire.com/docs/front-end/output/markup-regions/#technical-details-of-how-markup-regions-work) explains that markup region _definitions_ must occur after the `<html>` tag and markup region _actions_ (populate or modify) must occur before the `<html>` tag.

In your example you are trying to populate a markup region with an action that occurs after the `<html>` tag, which won't work.

A question: why are you using an action to populate a markup region within the same file that defines the markup region? Can't you just put the CSS link inside the `<pw-region>`?

```php
<?php namespace ProcessWire; ?>
<!doctype html>
<html>
  <head>
    <pw-region pw-id='css-files'>
      <link rel='stylesheet' href='<?php echo $config->urls->templates; ?>app.css'>
    </pw-region>
  </head>
  <body>
  </body>
</html>
```

**Comment by jlahijani** [comment]
OK that makes sense.  I was thinking about it the wrong way yesterday.

The example I posted was heavily simplified but to demonstrate a point that what may go in a region up may be determined later on in the same partial (_main.php) based on other processing.  Regardless, I've come up with a work-around.
