### ISSUE TITLE
Allow anchor/id links in CKEditor will be deleted

### ISSUE THREAD

**Issue by tiefenb** [processwire/processwire-issues#865]
### Short description of the issue

Regarding this post wo wbertl
https://processwire.com/talk/topic/19575-cant-get-ck-editor-to-allow-an-id/?tab=comments#comment-177389

In a field with following settings
- Textarea (Mult-language, default body field) 
- CKEditor
- ACF and HTML Purifier is on
- Custom Config Options: 
- - allowedContent: "p{text-align};h2[id];h3[id];a[href];ul;ol;li;strong;i;table;thead;tbody;tr;th[scope];td"

My anchor links are still deleted

### Optional: Suggestion for a possible fix

I found the root cause.

I disabled in my CKEditor the anchor plugin. If you take a look into the InputfieldCKEditor.module file you can see there is a check if the anchor plugin is disabled the HTML Purifier option "Attr.EnableID" is also disabled. 

`self::$purifier->set('Attr.EnableID', stripos($this->toolbar, 'anchor') !== false); // for anchor plugin use of id and name attributes
`
 Is there a possibility to override that configuration, or must it be changed directly in the InputfieldCKEditor.module file?

* ProcessWire version: 3.0.130
* PHP version: 7.3.3

**Comment by Toutouwai** [comment]
It's working for me with your allowedContent string - I can save h2 or h3 with an ID attribute no problem:

![2019-04-29_224156](https://user-images.githubusercontent.com/1538852/56891312-28b1e600-6ad0-11e9-8cdf-fde37b99ed7b.png)

![2019-04-29_224240](https://user-images.githubusercontent.com/1538852/56891315-2b144000-6ad0-11e9-9c5e-52b0ce80e641.png)

**Comment by Toutouwai** [comment]
Sorry, I take that back - the Anchor button was still in the toolbar when I tested.

**Comment by ryancramerdesign** [comment]
Thanks @tiefenb I've pushed a fix for this issue. Please use the "extra allowed content" input setting to specify your allowedContent rather than "custom config options" because using custom config with allowedContent is likely to overwrite things that shouldn't be, whereas using extra allowed content manages this safely. 

@Toutouwai It works in your case because you likely still have the Anchor plugin in your toolbar. Once you remove it, the id attributes won't work anymore because the conditional for whether to allow id attributes was specific to whether the Anchor plugin was active. It's now been updated to also check the extraAllowedContent setting.

**Comment by tiefenb** [comment]
thanks :-)
