### ISSUE TITLE
Nested selectors don't work with selector arrays

### ISSUE THREAD

**Issue by thetuningspoon** [processwire/processwire-issues#87]
### Short description of the issue

Nested selectors are not working with selector arrays. Please see https://processwire.com/talk/topic/14794-nested-selectors-with-selector-arrays/  for a detailed example.

### Expected behavior

Using a selector formatted as an array for the value in another selector array should work the same way that nested (bracketed) selector strings work in the selector string format.

### Actual behavior

See https://processwire.com/talk/topic/14794-nested-selectors-with-selector-arrays/

### Steps to reproduce the issue
Create an associative selector array with a nested selector array for its parent, children, or page value :)

### Setup/Environment

* ProcessWire version: 3.0.30
* (Optional) PHP version: 
* (Optional) MySQL version: 
* (Optional) Any 3rd party modules that are installed and could be related to the issue:

**Comment by ryancramerdesign** [comment]
The only way you can use a nested selector in a selector array is by using the a verbose selector array. Otherwise there's no way for PW to tell the difference between an array of values or a selector array. Something has to be there that says "this is another selector", and that's what the "find" property in a verbose array selector does. So what I think you are looking for is this:
~~~~~
$selector = array(
  array(
    'field' => 'template', 
    'value' => 'Tour'
  ),
  array(
    'field' => 'sort', 
    'value' => 'Title'
  ), 
  array(
    'field' => 'children', 
    'find' => array(
      'template' => 'departure',
      'departure_date>=' => $startDate,
    ) 
  )
);
~~~~~
Rather than specifying a "value", you specify a "find". The "find" can be a string selector, a verbose array selector, or a simple array selector (like we did above). 

Also worth mentioning is that there's not a speed advantage to this approach relative to the one you ended up using in the post you linked. So I would just stick with what you are doing.

**Comment by thetuningspoon** [comment]
Thanks Ryan. I did not know about the verbose array. Looks like the docs still need to be updated for selector arrays at some point. 

So does this mean that there is no efficiency advantage to using nested selectors, even in selector strings? And if so, does that mean that all of the pages that match the subselector are loaded into memory even if they do not match the parent selector?

**Comment by ryancramerdesign** [comment]
> So does this mean that there is no efficiency advantage to using nested selectors, even in selector strings? And if so, does that mean that all of the pages that match the subselector are loaded into memory even if they do not match the parent selector?

I think I misspoke earlier–there actually is some efficiency advantage as it doesn't load the nested pages, but rather the IDs (integers rather than Page objects). Though a Page prior to having any fields accessed on it isn't much more than an object with an ID. So the quantities would have to be large before it would matter. But still, you are right there is an efficiency advantage.
