### ISSUE TITLE
InputfieldButton: value attribute should not be forced as button caption

### ISSUE THREAD

**Issue by gadgetto** [processwire/processwire-issues#877]
### Short description of the issue

Currently an `InputfieldButton` element uses the value attribute as button caption. A HTML button element can have a value attribute and a different button caption.

**For example - this is not possible with InputfieldButton:**

```html
$markup = '
<small>
    <button type="submit" name="range" value="lastmonth" class="ui-button ui-priority-secondary">
        <span class="ui-button-text">' . wireIconMarkup('calendar') . ' ' . $this->_('Last Month') . '</span>' .
    '</button>
</small>
<small>
    <button type="submit" name="range" value="lastweek" class="ui-button ui-priority-secondary">
        <span class="ui-button-text">' . wireIconMarkup('calendar') . ' ' . $this->_('Last Week') . '</span>' .
    '</button>
</small>
<small>
    <button type="submit" name="range" value="today" class="ui-button ui-priority-secondary">
        <span class="ui-button-text">' . wireIconMarkup('calendar') . ' ' . $this->_('Today') . '</span>' .
    '</button>
</small>';
```
```php
if ($_POST['range'] == 'lastmonth') {
    //action
} else if ($_POST['range'] == 'lastweek') {
    //action
} else if ($_POST['range'] == 'today') {
    //action
} else {
    //invalid action!
}
```

### Expected behavior

`InputfieldButton` should have different attributes for `value` and `caption`.

### Actual behavior

InputfieldButton uses `value` attribute for button `caption`.

### Optional: Suggestion for a possible fix

Provide: `$this->attr('caption', '');` property and if set use this as button caption instead of value.

### Setup/Environment

* ProcessWire version: 3.0.131

**Comment by ryancramerdesign** [comment]
@gadgetto The existing behavior is because ProcessWire does not use or process the button values — they are only used for output. It's also consistent with how input[type=submit] works. So there's been no need to have independent value attribute from button text thus far. However, the scenario you described seems useful for some API-side usages of this Inputfield, and if we can make it support more use cases that seems worthwhile. I have gone ahead and added support via `text` or `html` properties that can define the button text. Thanks.

**Comment by BernhardBaumrock** [comment]
@ryancramerdesign I've sometimes realized that buttons in PW always use uppercase for all words (is it called sentence case?) - or to be more precice it is always the case and sometimes it's annoying (wrong). Not sure if the just added implementation also uses it, but it would be great to have at least an option to disable it, because in german we don't have this kind of uppercase usage!

**Comment by ryancramerdesign** [comment]
There is another issue open for this and I've given it a todo tag to fix
this for non-en languages. It'll be in place by next week.

**Comment by gadgetto** [comment]
This is perfect! Thanks!
