### ISSUE TITLE
Behaviour of PageArray::get and Pages::get inconsistent

### ISSUE THREAD

**Issue by owzim** [processwire/processwire-issues#89]
### Short description of the issue

`$anyPageArray->get('name=i-dont-exist')` does not return a `NullPage` like `$pages->get('name=i-dont-exist')` does.

### Expected behavior

`$anyPageArray->get('name=i-dont-exist')` returns a `NullPage`

### Actual behavior

`$anyPageArray->get('name=i-dont-exist')` returns `null`

### Steps to reproduce the issue

Get a non existent page from the homepage's children.

`$pages->get('/')->children->get('name=i-dont-exist')`

### Setup/Environment

* ProcessWire version: 3.0.39

**Comment by ryancramerdesign** [comment]
These aren't meant to have the same behavior. PageArray is a type of WireArray, and so it must behave consistently with other WireArray types, otherwise it would no longer be compatible with things that accept a WireArray. Here's more details on these methods:

- [$pages->get()](http://processwire.com/api/ref/pages/get/)
- [PageArray::get()](http://processwire.com/api/ref/page-array/get/)

**Comment by owzim** [comment]
That makes sense, thanks!
