### ISSUE TITLE
Log permissons missing in docs

### ISSUE THREAD

**Issue by jmartsch** [processwire/processwire-issues#894]
The [documentation for permissions](https://processwire.com/docs/user-access/permissions/) is missing logs-edit and logs-view permissions.

**Comment by ryancramerdesign** [comment]
@jmartsch That particular page isn't comprehensive and just covers the most commonly used permissions. There's not really anything else to say about logs-view and logs-edit beyond what's already listed with the permissions in the admin. I was thinking about dropping these permissions since really only the superuser should be able to do anything with the logs, so would like to leave them off the docs page for now. Thanks.

**Comment by jmartsch** [comment]
For one customer I use logs, to show them what was done by whom, and other things like sent emails also. I gave the logs-view permission to their group and think it should not be only for superusers. Maybe you would overthink this?

**Comment by ryancramerdesign** [comment]
Okay that does seem like a good use case. But some logs contain things that
really should be superuser only. Maybe more specific (log-level) permission
is what would be worthwhile here.

**Comment by szabeszg** [comment]
> Maybe more specific (log-level) permission is what would be worthwhile here.

This would be a welcome addition. Currently I rely on sending emails to site managers to notify them of actions mentioned by @jmartsch but these emails are not something clients can look up later on as clients are usually bad at searching for old emails.

It would be great to be able to specify which log files they can list and since it is possible to create custom log files it would be very handy to let clients view what they need to know about.

**Comment by BernhardBaumrock** [comment]
> Maybe more specific (log-level) permission is what would be worthwhile here.

+1

**Comment by gebeer** [comment]
Has a more granular control been implemented yet? Also logs-view and logs-edit are still not documented at https://processwire.com/docs/user-access/permissions/
