### ISSUE TITLE
Is webp a variation?

### ISSUE THREAD

**Issue by matjazpotocnik** [processwire/processwire-issues#895]
The results form $image->getVariations() and $image->removeVariations() differs when webp image is created/present. If removeVariations() method treats webp as a variation, shouldn't then getVariations() also show webp as a variation?

![Screenshot 2019-05-30 06 47 10_cr](https://user-images.githubusercontent.com/7663992/58609240-31503480-82a7-11e9-9bfe-4b3ac3590d57.jpg)

**Comment by ryancramerdesign** [comment]
Webp images are not variations, but rather than are like an attachment to a
particular variation. They aren't Pageimage objects, instead they are
PageimageExtra objects, which are extras on top of an Pageimage
(variation). Because they are an attachment of a variation, they must be
deleted when the variation is deleted. But they shouldn't be returned by a
getVariations() call because they are part of an existing
Pageimage/variation rather than being one on their own.

**Comment by adrianbj** [comment]
I still don't like the inconsistency with this. I feel like the need to remove the webp "attachments" / PageimageExtra objects needs its own dedicated method (maybe `removeAttachments()`) that is automatically called when you delete a base / main image, rather than relying on what feels like a hacky use of `removeVariations()`.

Sorry if this is not a popular opinion, but I feel like the current behavior is unexpected and confusing.

I do understand that there are pros and cons with both approaches and maybe this is an indicator that webp files need to be handled or stored differently - maybe they could be stored in a cache folder, rather than in the page assets / files folder? I haven't thought this approach through at all, so maybe not a good idea, but just trying to brainstorm other possibilities.

**Comment by teppokoivula** [comment]
Admittedly I hadn't even considered about how variation methods would affect WebP images, but the way Ryan explained it above seems to make sense: if they are indeed additions (extras) of variations, much like the variations are additions to the original source image, they should be removed when the variation is removed. This is is also why removeVariations() removing them makes sense to me.

Only thing that I find strange here is what is visible in the screenshot above: removeVariations() removes not only the variation and any WebP files connected to that, but also a WebP image called tree_at_lake_2560_1440.webp. This extra image is actually not connected to a variation, so according to Ryan's explanation above I wouldn't have expected removeVariations() to remove it.

Perhaps this is done so that removeVariations() doesn't get unnecessarily complex?

Anyway, if there are real world issues caused by the behaviour spelled out in this issue, then describing them here would be helpful – otherwise I'd say that this is a design detail that has a slight quirkiness to it, but more importantly _gets the job done with least amount of effort_. It's also completely backwards compatible, and doesn't require tweaks to existing code, which is a good thing in itself.

As such, I'd suggest letting this pass :)

**Comment by ryancramerdesign** [comment]
Okay this is a weird analogy, but think of it like this. PagefileExtra objects (like webp images) are parasites, and Pageimage objects (like variations) are hosts. Any host can have parasites, for example a tree (host) can have mistletoe (parasite). So think of the webp image as a parasite (mistletoe) that's attached to a host (tree or Pageimage). The hosts are not themselves parasites, and if you ask for a group of them (i.e. getVariations) then you are asking for hosts, not parasites. But if the host dies, so does the parasite. When the trees falls, the mistletoe dies. When the hosts go, so do the parasites. If a Pagefile is deleted, its PagefileExtra objects (parasites) must also be deleted. Thus, if a Pageimage/variation is deleted, then its webp must also be deleted, no exceptions. The relationship doesn't allow further division, nor should the code.

**Comment by LostKobrakai** [comment]
If those webp files are not variation maybe just their path shouldn't be returned / or only when a certain flag is also set.

**Comment by ryancramerdesign** [comment]
@LostKobrakai I don't understand?

**Comment by LostKobrakai** [comment]
I think the problem here is not that much the fact that webp files are removed, but rather that `removeVariations` lists them as well, which is inconsistent to other api handling variations. Maybe the webp files could only be listed with a certain flag enabled. Because any code, which uses the function and is only aware of variations shouldn't be concerned with webp files anyways.

**Comment by ryancramerdesign** [comment]
The purpose of removeVariations() is to remove all files having to do with the variations. There is a separate method for getting variations (getVariations). The webp files may not be variations on their own, but they are still a part of a variation (i.e. the host/parasite thing mentioned above), and they may not exist on their own without the variation. While the method provides the option to do a dry run, returning the list of files that will be removed, we wouldn't want that list to exclude the webp files, because they are definitely part of the list of files that will be removed as part of the variations. Though if you are aware of some module or something that is using this method for some other purpose and might need something more here, let me know. But I can't currently think of any situation where removeVariations should exclude anything that will be removed.
