### ISSUE TITLE
Page Path History no longer seems to work in 3.0.132

### ISSUE THREAD

**Issue by jacmaes** [processwire/processwire-issues#898]
### Short description of the issue

I've relied on this core module for a long time to track the changes in my URLs when I manually change them. I've just realized that it no longer seems to work on 3.0.132 as I'm getting a "404 page not found". 

### Steps to reproduce the issue

1. Change a page URL in Settings > Name
2. View the page and it's not redirected to the new URL.

### Setup/Environment

* ProcessWire version: 3.0.132
* PHP version: 7.3
* (Optional) Any 3rd party modules that are installed and could be related to the issue: I had JumpLinks installed, but I've removed it and tried again, just to be sure. Same behavior.

**Comment by jacmaes** [comment]
Mmmh, strange, I've tried on another site running PHP 7.2.18 on another server, with the same PW version, and it works correctly. Could this be related to PHP 7.3, or a misconfiguration in Apache somewhere?

**Comment by ryancramerdesign** [comment]
@jacmaes I can't duplicate this one here. I'm not aware of any issues related to this in PHP 7.3, and I don't think the apache configuration should matter. If you find ithe PHP version is the only difference between the two installations, it would be surprising for that to account for it, but it's not impossible. If you click on the settings tab of the non-redirecting page, click on the "What other URLs redirect to this page" fieldset, what does it say?

**Comment by jacmaes** [comment]
>  If you click on the settings tab of the non-redirecting page, click on the "What other URLs redirect to this page" fieldset, what does it say?

Nothing, it's blank:

![redirect](https://user-images.githubusercontent.com/1206842/60271332-6f666580-98f2-11e9-89e5-fb1cac84c8d7.png)

The reason I'm suspicious about being related to an Apache configuration is that I had an incident after a failed update of a package on Ubuntu 18, which somehow messed up PHP 7.2. I had to do a "sudo a2enmod php7.3" to activate a newer version. And it looks like my php.ini file was reset to default.

**Comment by ryancramerdesign** [comment]
@jacmaes If it's got nothing recorded in that "What other URLs..." field then it looks like the page is just not aware of the move. I don't think Apache anything could be the issue here. I would double check that PagePathHistory is installed first because it's not a core module that is required to be installed. If you think it might be PHP 7.3, then it would be worth having Tracy Debugger installed while moving/renaming a page and see if there are any PHP notices/warnings appearing in the process. Lastly, I would double check that your rename is unique and not colliding with another existing redirect that might already be present.

**Comment by jacmaes** [comment]
I'm closing this issue because I've moved to another server, and I can no longer reproduce the error on the new setup.
