### ISSUE TITLE
Field collapsing is glitchy if inside a repeater

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-issues#900]
By default, a field's visibility is set to "open".  When a field has been assigned to a template, you can easily collapse it by clicking anywhere in the header area of the field (or the "toggle open/close" icon on the right).

However when adding a field to a repeater, the ease of toggling it becomes glitchy.  If you click in the header area, the field does not collapse and it acts glitchy.  To collapse to the field, you must click directly on the "toggle open/close" arrow on the right.  Doing so seems to resolve the glitchyness and henceforth you can then open and close the field by clicking in the header area.

Note: if the field's visibility is set to "closed", the issue will not occur.

PW 3.0.132

**Comment by Toutouwai** [comment]
> To collapse to the field, you must click directly on the "toggle open/close" arrow on the right

I agree that the expand/collapse behaviour is a bit quirky, but Ryan has explained the thinking behind it here: https://github.com/processwire/processwire-issues/issues/855#issuecomment-484149856

**Comment by jlahijani** [comment]
Hmm... I can work-around this with some jQuery overrides, however I can't figure out how to make it work correctly with fields that are "Closed, Load only Ajax".

I wonder if this is something for AdminOnSteriods.

**Comment by ryancramerdesign** [comment]
Clicking the header area of it is supposed to focus the field (if it supports a focus event). That's because field headers are `<label>` elements with `for` attributes, and clicking a label is supposed to focus the input that it is for, as a matter of accessibility standards. 

PW also supports collapsed fields. In order to focus a collapsed field, it first has to be opened. That's why a field opens when you click its header, and then it focuses (if supported by the field). Once you've used the header to open the field, it'll also let you use the header to collapse it, which is expected at that point. But the actual control for opening/closing fields is the arrow on the right side of the field. 

The behavior here should be the same whether in repeater items or outside of them. It sounds like you might be seeing some different behavior for fields contained in repeater items? I'm not sure because your description of how fields behave outside the repeater is not how PW is designed to behave, whereas your description of fields inside the repeater sounds more consistent with what it's supposed to do. Is it possible you've got any modules present that change the behavior?
