### ISSUE TITLE
PageFinder SQL syntax error

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#910]
### Short description of the issue

The example below is a simplified version of a more complex real-world selector. I realise that in this example there is no need to use OR-groups, but the point is that it should be possible to use this selector without an SQL error.

This code...
```php
$term_1 = $sanitizer->selectorValue('foo');
$term_2 = $sanitizer->selectorValue('(bar');
$items = $pages->find("(title=$term_1), (title=$term_2), limit=10");
```
...gives the following error...

![2019-06-22_110000](https://user-images.githubusercontent.com/1538852/59955182-e956b300-94dc-11e9-8971-d675749851fa.png)

The issue seems to be related to the open parenthesis without a closing parenthesis in `$term_2`. If I add a closing parenthesis there is no error:

![2019-06-22_110038](https://user-images.githubusercontent.com/1538852/59955207-0a1f0880-94dd-11e9-825a-a6e45775eb22.png)

Alternatively, if I remove the limit from the selector there is no error:

![2019-06-22_110056](https://user-images.githubusercontent.com/1538852/59955211-0ee3bc80-94dd-11e9-8c7a-567ae396c075.png)

It's like the parenthesis in the search term is being wrongly interpreted as part of the SQL syntax, even though it has been passed through `$sanitizer->selectorValue()`.

### Setup/Environment

* ProcessWire version: 3.0.133

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I've pushed a fix for this issue. It wasn't that it was getting interpreted as part of SQL syntax but rather that the selector engine was interpreting the "limit=10" as part of the OR group rather than outside of it, and it looks like MySQL or versions of MySQL don't support IN() and LIMIT statements combined in a subquery (which is how PW handles OR groups).

**Comment by Toutouwai** [comment]
Thanks!
