### ISSUE TITLE
Datetime field won't save in other languages

### ISSUE THREAD

**Issue by Klenkes** [processwire/processwire-issues#914]
### Setup:
Spotted behavior in PW 3.0.98 up to 3.0.123
Multilanguage Website - Default language is german, second language english
(to make german default EN translation files overwritten)
Create a Datetime field with Datepicker on focus

### Still works:
Switch backend languages and edit the Datetime field.
Since no settings have changed, everthing works as expected.

### Won't work:
Now change on Input Tab **Date Input Format** to 8 April 2016(in my case all editors are german)
Date Input Format Code is both DE and EN: j F Y
Datetime field won't save a selected value in one of the backend languages(DE or EN)!
This is tricky because I have 2 websites with different behavior. On one site it works on backend DE but not EN, on the other site it saves in EN but not in DE.

### Workaround:
If I leave **Date Input Format** alone(default value) and only change **Date Input Format Code**  german: d-m-Y and english to: j F Y it works.

* ProcessWire version: spotted on 3.0.98 and 3.0.123
* (Optional) PHP version: 5 to 7

**Comment by Klenkes** [comment]
Related forum post:
[https://processwire.com/talk/topic/21838-datetime-field-wont-save-in-other-languages/](url)

**Comment by ryancramerdesign** [comment]
@Klenkes When it comes to a date input format, I don't think you'll be able to use literal month names as part of the input, especially when the language uses month names that PHP's strtotime() is not going to recognize. (Though it sounds like it might be able to recognize it on one of your installs, but I definitely wouldn't count on that). Using spelled out month names is fine for date output formats, but for date input format I'd recommend sticking to numbered month since these are common across languages.

**Comment by Klenkes** [comment]
Now that you explained it... literal month names as an input format make no sense.
But then again, in all my PW projects that are single language websites, it works perfectly.
As you suspected already I think it depend on the server configuration.

But if literal month names are problematic why offer them in the field config?
![datetime-select](https://user-images.githubusercontent.com/5174937/60244195-2abed800-98ba-11e9-8af5-db41800e4bef.png)

**Comment by BernhardBaumrock** [comment]
A little offtopic, but if you happen to change those example dates it would be great to change them to a format that can not be misleading as the current examples can be:

8.4.2016 --> change to 25.10.2016 (day bigger than 12 so it is instantly clear it is a day and not a month)

I'm used to it now, but I can remember I had a bug once when I started with PW because of this :)

**Comment by ryancramerdesign** [comment]
@Klenkes It looks like month names for input are only problematic in some multi-language environments. I think it might be a matter of the locale setting for the language (in the language pack). 

This is the first I've heard of an issue related to this, though I'm thinking it's also not that common to use full month names for input. It seems like in a multi-language environment it's probably safer to avoid month names unless you know your locale setting will recognize them. But there are also cases where people may want or need them, or already be using them, so I also don't want to prevent the option from being used. 

If you'd like to experiment with it, you can try adjusting the locale setting in your translation file for /wire/modules/LanguageSupport/LanguageSupport.module on the translation item labeled "Value to pass to PHP's setlocale(...)". However, since month names aren't ideal for input in the first place, I would probably just stick with using numbers for month input instead.

**Comment by netcarver** [comment]
@Klenkes Any further thoughts on Ryan's reply?

**Comment by Klenkes** [comment]
@netcarver Localized month names are always a mess... and I try to avoid them whenever I can. I came to the conclusion that I have to use expressions like:  
`$postdate = wire('user')->language->name == 'default' ? strftime("%e. %B %Y", $item->getUnformatted("postdate")) : strftime("%B. %e. %Y", $item->getUnformatted("postdate"));
echo $postdate;`
More work but works!

**Comment by netcarver** [comment]
Ok, if you are happy to do so, could you close this issue now?
