### ISSUE TITLE
Urgent need to revert the support of PNG8 for Imagick Engine!

### ISSUE THREAD

**Issue by horst-n** [processwire/processwire-issues#921]
@ryancramerdesign Sorry for previously posting into a closed thread. That's why I open this new issue report here.

### Short description of the issue

A change with the allowed image formats for the imagick engine must be reverted back. 
See: https://github.com/processwire/processwire/pull/141#issuecomment-499918590
and: https://processwire.com/talk/topic/21645-pw-30132-–%C2%A0core-updates/?tab=comments#comment-186879
and: https://processwire.com/talk/topic/21645-pw-30132-–%C2%A0core-updates/?tab=comments#comment-186892

### Optional: Suggestion for a possible fix

Remove PNG8 from the support list of the Imagick Engine. (As it was before the update!)

### Setup/Environment
* ProcessWire version: >= 3.0.132

**Comment by ryancramerdesign** [comment]
Hi Horst, I did remove "PNG8" from that supported formats list in the
Imagick image sizer engine, back in early June as soon as I saw your
message about it. So currently it just has PNG24 and PNG. Should the
regular "PNG" (without the 8 or 24 appended) be removed?

**Comment by horst-n** [comment]
@ryancramerdesign Oh, thanks for the update!
It was @AndZyk who has posted a reminder and I acted upon this. So we need to ask him if there is something not working as expected.

**Comment by ghost** [comment]
Hello @ryancramerdesign,

thank you for the update, but unfortunately I still have some issues with the generated image variations.

I have updated to ProcessWire 3.0.135 and want to generate variations of this PNG of a logo exported with Sketch:

![original](https://user-images.githubusercontent.com/9403850/60813593-5d0ee600-a194-11e9-9a83-3246d296e24d.png)

The variations generated with the GD library are fine:

![gd 0x260](https://user-images.githubusercontent.com/9403850/60813611-6304c700-a194-11e9-8a5e-61aa6f2ab17b.png)

But the variations generated with the IMagick Image Sizer module have a soft blur around the edges:

![im 0x260](https://user-images.githubusercontent.com/9403850/60813628-7021b600-a194-11e9-8525-bbcd9fc13f38.png)

Previously those variations had some [artefacts](https://processwire.com/talk/topic/21645-pw-30132-%E2%80%93%C2%A0core-updates/?do=findComment&comment=186879).

I am on a MacOS 10.13.6 and have tested this locally with MAMP and Imagick 3.4.4 installed via Pecl:

`MAMP_Imagick_MAMPextension=/Applications/MAMP/bin/php/php7.2.14/lib/php/extensions/no-debug-non-zts-20170718/imagick.so`

Maybe its just my Imagick? But those soft blur around the edges of variations should not be there in my opinion.

I would appreciate some help. 😉 

Regards, Andreas

**Comment by horst-n** [comment]
Hi @AndZyk , what we want to know is how is the outcome if you have imagick installed as prioritized engine and do a simple variation call without forcing a special engine. Does it looks like the GD one or does it have some artefacts?

**Comment by ghost** [comment]
Hi @horst-n, this is exactly what I described above, but if it helps I can provide another example:

Original PNG (1280 x 720) exported with Sketch:

![babel](https://user-images.githubusercontent.com/9403850/60879923-ebda3c00-a242-11e9-800b-1c606178f906.png)

Variation with GD Library (1024 x 576) and standard settings:

![gd-babel 1024x576](https://user-images.githubusercontent.com/9403850/60879924-ebda3c00-a242-11e9-957c-ff97e913079c.png)

Variation with Imagick Image Sizer (1024 x 576), sharpening **none** and quality **90**: 

![im-babel 1024x576](https://user-images.githubusercontent.com/9403850/60879925-ebda3c00-a242-11e9-9288-fcf1950a39e8.png)

This variation looks fine, but in comparison with the GD Library generated variation there is a soft blur around the edges, which shouldn't be there in my opinion. 😉 

I generated the variations like this

`<?=page()->image->size(1024, 768)->url?>`

My local ImageMagick version doesn't seem to be the issue, because it happens with the manual installed version with Pecl and the packaged version with MAMP.

I hope that was helpful, but if not I can try to provide some more information.

Can you try to reproduce this?

Regards, Andreas

**Comment by netcarver** [comment]
@horst-n @AndZyk Any progress here? Can this issue be updated, or even closed?
