### ISSUE TITLE
Unspecific message 'Server error' when trying to duplicate Repeater Matrix field

### ISSUE THREAD

**Issue by fitzliputz** [processwire/processwire-issues#923]
Full error message is 'Server Error. We're sorry! The server encountered an internal error and was unable to complete your request. Please try again later.'

I suppose, intended was to handle the clone trial like the one to duplicate a core repeater field, where you receive a proper specific message.

**Comment by ryancramerdesign** [comment]
@fitzliputz Repeater and RepeaterMatrix do not support field cloning. If you try to do it, you will get an error, though the error specifically says that the field does not support cloning. The "server error" message you are receiving is not coming from ProcessWire. It sounds like maybe one coming from an Apache module like mod_security or similar. If you haven't already, you might also try enabling debug mode, though since cloning isn't supported for this fieldtype it's not going to help with that. 

I did just try to duplicate the error you received, but I receive an error stating that the fieldtype does not support cloning. If you want to try and investigate why your error message is different, make sure you are running on the ProcessWire dev branch (3.0.135 or newer), test again to confirm the issue still occurs, and please list the Apache modules and ProcessWire modules that you have installed. Thanks.

**Comment by fitzliputz** [comment]
Okay Ryan, thanks. As I can live quite well with the unclonability of (Matrix) Repeaters, I see no use to investigate in such extremely subordinated questions. I was just that Horst asked me to open the issue and do I did. That said, I will close it now.
