### ISSUE TITLE
ASM Select doesn't display all selected options if Autojoin is enabled

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-issues#928]
I have an ASM select field on my site and autojoin is disabled for the field.

If I select a lot of options for this field... like over 100, it saves it just fine.

However if I enable autojoin for the field, all the selected options will not be displayed, even though the data is technically saved.  As a result, if you don't notice that, re-saving the page will then wipe out data.

Video:
https://www.youtube.com/watch?v=MS5MCrECOlM

**Comment by ryancramerdesign** [comment]
@jlahijani For a multi-value field like that, there's a limit to how many items MySQL can join into the result with a single query. What that limit is will depend on MySQL settings, but if you want to try experimenting with the setting in your MySQL installation you can adjust the `group_concat_max_len` MySQL setting. However, I would suggest just avoiding autojoin for this case because this is not an efficient use case for autojoin, even without any limit. Autojoin is good for small things that you will access on every loaded instance of the page. For example: title, summary, date. But for other cases, it can sometimes hurt more than help. I don't often use autojoin for Page fields at all. But if necessary, you might use it  for a single page selection or at least a very small set of category type pages, but definitely not for something with dozens of selections. That's the sort of thing that's better to load on demand. Keep in mind, even simply browsing the page in the admin page list will trigger all autojoin field values to load on those pages, so it's good to be selective about when/where to use it.

**Comment by tuomassalo** [comment]
This bug can theoretically be quite severe. In addition to dropping some of the expected page ids, an incorrect page id can be returned.

Mysql truncates the string created by `GROUP_CONCAT` to the exact length of `group_concat_max_len`. For example, when the string should end in `...12345,12346,12347`, it can end up ending in `...12345,123`, thus incorrectly referencing page id `123`.

The bug is not only triggered with autojoin, but also with `joinFields`.

Unfortunately I'm not aware of any easy way to detect the overflow. Mysql does set a warning (`Row x was cut by GROUP_CONCAT()`), but PDO does not expose warnings to the caller, so a pricey `SHOW WARNINGS` query would be needed. Definitely a no-no.

I'm considering raising an error if we detect an overflow. I would replace all instances of `explode(FieldtypeMulti::multiValueSeparator, $something)` with something like`explodeAndDetectOverflow($something)`:

```php
function explodeAndDetectOverflow($value) {
  if(strlen($value) == $GROUP_CONCAT_MAX_LEN) {
    ... fail the query loudly
  }
  return explode(FieldtypeMulti::multiValueSeparator, $value);
}
```

But without extra queries, there is no way to detect the current value of `group_concat_max_len`. We could default it to the mysql default `1024` and make it configurable.

I consider this approach better than silently giving incorrect responses.

But we should make sure that current installations are not affected: they should retain the current behaviour as `group_concat_max_len` is unknown.

**Comment by adrianbj** [comment]
@tuomassalo - thanks for all your recent posts about findJoin - I was really excited when it came along, but I haven't been able to trust it at all so removed all usage of it.
