### ISSUE TITLE
ProcessPageLister - wrong URLs in MarkupPagerNav if used in "executeSomething" method

### ISSUE THREAD

**Issue by gadgetto** [processwire/processwire-issues#936]
### Short description of the issue

I'm using a **ProcessPageLister** in a "sub-page" of a **ProcessModule**. By "sub-page" I mean `executeSomething` method.

Let's say the URL to the **executeSomething** output is
`/processwire/setup/mymodule/something/`

The problem is, the **MarkupPagerNav** output has wrong URLs! Instead of `/processwire/setup/mymodule/something/page2`
it has
`/processwire/setup/mymodule/page2`

### Expected behavior

The URLs generated by **MarkupPagerNav** should respect the the current URL path:
`/processwire/setup/mymodule/something/page2`

### Actual behavior

The **MarkupPagerNav** output generates a wrong URL paths:
`/processwire/setup/mymodule/page2`

### Steps to reproduce the issue

Here is a (shortened) code part to reproduce the issue:

```php
class ProcessMymodule extends Process implements Module {

    public static function getModuleInfo() {
        return array(
            'title' => __('My Module'),
            'summary' => __('My module summary...'),
            'version' => 1, 
            'page' => array(
                'name' => 'mymodule',
                'title' => 'My Module',
                'parent' => 'setup',
            ),
            'nav' => array(
                array(
                    'url' => 'something/', 
                    'label' => __('Something'), 
                ),
            ),
        );
    }

    protected $myLister = null;

    public function ___execute() {
        ....
    }

    public function ___executeSomething() {
        $modules = $this->wire('modules');
        $config = $this->wire('config');
        $ajax = $config->ajax;
        
        $this->browserTitle($this->_('Something'));
        $this->headline($this->_('Something'));
        
        if (!$lister = $this->getMyLister()) return '';

        if ($ajax) return $lister->execute();
        
        $lister->defaultSelector = 'template=my-template';
        $lister->columns = array(
            'title',
            'parent',
            'modified',
        );
        
        return $lister->execute();
    }

    protected function getMyLister() {
        if ($this->myLister) return $this->myLister;
        
        $this->myLister = $this->wire('modules')->get('ProcessPageLister');
        $this->myLister->defaultLimit = 10;

        return $this->myLister;
    }

```

### Setup/Environment

<strong>Server Details</strong>

|Software|Version|
|------:|:-------|
|ProcessWire|3.0.135|
|PHP|7.2.14|
|Webserver|Apache|
|MySQL|5.7.25|
<details><summary><strong>Server Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|allow_url_fopen|1|
|max_execution_time|30 (changeable)|
|max_input_nesting_level|64|
|max_input_time|60|
|max_input_vars|1000|
|memory_limit|128M|
|post_max_size|8M|
|upload_max_filesize|32M|
|xdebug||
|xdebug.max_nesting_level||
|mod_rewrite|1|
|mod_security|*confirmed off|
|EXIF Support|1|
|FreeType|1|
</details><details><summary><strong>GD Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|Version|bundled (2.1.0 compatible)|
|GIF|1|
|JPG|1|
|PNG|1|
|WebP||
</details><details><summary><strong>iMagick Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|Version|6.9.6|
|GIF|1|
|JPG|1|
|PNG|1|
|SVG|1|
|PDF|1|
|WebP||
</details><details><summary><strong>Module Details</strong></summary>

|Module ClassName|Version|
|------:|:-------|
|FieldtypeMessageMeta|0.0.1|
|FieldtypeSnipWireTaxSelector|0.0.1|
|InputfieldMessageMeta|0.0.1|
|MarkupSnipWire|0.0.1|
|ProMailer|0.0.7|
|ProcessGroupMailer|0.0.1|
|ProcessMessageLister|0.0.1|
|ProcessProMailer|0.0.7|
|ProcessSnipWire|0.0.1|
|ProcessTracyAdminer|1.0.6|
|ProcessWireUpgrade|0.0.7|
|ProcessWireUpgradeCheck|0.0.7|
|SnipWire|0.0.1|
|TracyDebugger|4.19.26|
</details>

**Comment by ryancramerdesign** [comment]
@gadgetto MarkupPagerNav is an independent module that doesn't know what are valid URL segments and such, so it has a `baseUrl` property that it expects the caller to set. If not set, then it defaults to the current page URL, not including URL segments (since it has no way to know which are valid). This is fine for Lister since it is designed to run as the page Process, but in your case, you are using Lister in a case where it isn't the current page Process, and admittedly it's not designed for that. However, if it otherwise works, and the only issue seems to be the pagination URLs, then I think the following may enable you to achieve what you are trying to do. I think this could go at the end of your getMyLister() method, or somewhere before calling $lister->execute() in your executeSomething method: 
~~~~~
$this->addHookBefore('MarkupPagerNav::render', function($event) {
  $pager = $event->object; /** @var MarkupPagerNav $pager */
  $url = $event->page->url() . 'something/';
  // or this: $url = $event->input->url(); 
  $pager->setBaseUrl($url);
}); 
~~~~~

**Comment by gadgetto** [comment]
Thank you Ryan for your explanation and hint! As this is not a bug I'll close this issue now.
