### ISSUE TITLE
Custom admin page - InputfieldButton with dropdown = messy HTML

### ISSUE THREAD

**Issue by gadgetto** [processwire/processwire-issues#948]
### Short description of the issue

1. Using an InputfieldButton + Dropdown `addActionLink()` in a custom admin page, leads to messy HTML code. Therefore the button dropdown renders wrong.

2. and If additionally using `showInHeader()` - the button element is rendered twice in header.

### Expected behavior

ad 1)
**The button dropdown should render like this:**

<img width="469" alt="Bildschirmfoto 2019-08-01 um 13 15 31" src="https://user-images.githubusercontent.com/876737/62289683-a08d0500-b45f-11e9-888c-2168b0497905.png">

**This is the expected HTML output (I manually corrected it):**

```html
<ul id="refresh-data_dropdown" class="pw-button-dropdown pw-dropdown-menu pw-dropdown-menu-rounded pw-button-dropdown-init pw-button-dropdown-1 pw-dropdown-ready ui-menu ui-widget ui-widget-content ui-corner-all" data-my="left top" data-at="left bottom+1" style="position: absolute; top: 2197.19px; left: 175.766px; z-index: 200; display: none;" role="menu" tabindex="0" aria-activedescendant="ui-id-4">
	<li class="ui-menu-item" role="presentation">
		<a href="./?action=refresh_all" id="ui-id-4" class="ui-corner-all" tabindex="-1" role="menuitem">
			<i class="fa fa-fw fa-refresh"></i>Refresh Complete Snipcart Cache
		</a>
	</li>
</ul>
```

ad 2)
The button shouldn't be rendered twice in header.

### Actual behavior

ad 1)
see screenshot and HTML output below:

<img width="496" alt="Bildschirmfoto 2019-08-01 um 13 12 39" src="https://user-images.githubusercontent.com/876737/62289803-f82b7080-b45f-11e9-9ae0-14f6cb03777d.png">

```html
<ul id="refresh-data_dropdown" class="pw-button-dropdown pw-dropdown-menu pw-dropdown-menu-rounded pw-button-dropdown-init pw-button-dropdown-1 pw-dropdown-ready ui-menu ui-widget ui-widget-content ui-corner-all" data-my="left top" data-at="left bottom+1" style="position: absolute; top: 2197.19px; left: 175.766px; z-index: 200; display: none;" role="menu" tabindex="0">
	<a class="InputfieldButtonLink ui-widget-content ui-menu-divider" href="./?action=refresh"></a>
	<li class="ui-menu-item" role="presentation">
		<a class="InputfieldButtonLink ui-corner-all" href="./?action=refresh" id="ui-id-3" tabindex="-1" role="menuitem"></a>
		<a href="./?action=refresh_all" id="ui-id-4" class="ui-corner-all" tabindex="-1" role="menuitem">
			<i class="fa fa-fw fa-refresh"></i>Refresh Complete Snipcart Cache
		</a>
	</li>
</ul>
```

ad 2)
see screenshot:

<img width="431" alt="Bildschirmfoto 2019-08-01 um 13 22 28" src="https://user-images.githubusercontent.com/876737/62289876-290ba580-b460-11e9-9307-ce5d7580a457.png">

### Steps to reproduce the issue

```php
        /** @var InputfieldButton $btn */
        $btn = $modules->get('InputfieldButton');
        $btn->id = 'refresh-data';
        $btn->href = './?action=refresh';
        $btn->value = $this->_('Refresh');
        $btn->icon = 'refresh';
        $btn->addActionLink(
            './?action=refresh_all', 
            'Refresh Complete Cache',
            'refresh'
        );
        $btn->showInHeader();

        $out .= $btn->render();
```

### Setup/Environment

<strong>Server Details</strong>

|Software|Version|
|------:|:-------|
|ProcessWire|3.0.136|
|PHP|7.2.14|
|Webserver|Apache|
|MySQL|5.7.25|
<details><summary><strong>Server Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|allow_url_fopen|1|
|max_execution_time|30 (changeable)|
|max_input_nesting_level|64|
|max_input_time|60|
|max_input_vars|1000|
|memory_limit|128M|
|post_max_size|8M|
|upload_max_filesize|32M|
|xdebug||
|xdebug.max_nesting_level||
|mod_rewrite|1|
|mod_security|*confirmed off|
|EXIF Support|1|
|FreeType|1|
</details><details><summary><strong>GD Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|Version|bundled (2.1.0 compatible)|
|GIF|1|
|JPG|1|
|PNG|1|
|WebP||
</details><details><summary><strong>iMagick Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|Version|6.9.6|
|GIF|1|
|JPG|1|
|PNG|1|
|SVG|1|
|PDF|1|
|WebP||
</details><details><summary><strong>Module Details</strong></summary>

|Module ClassName|Version|
|------:|:-------|
|FieldtypeMessageMeta|0.0.1|
|FieldtypeSnipWireTaxSelector|0.0.1|
|InputfieldMessageMeta|0.0.1|
|MarkupSnipWire|0.0.1|
|ProMailer|0.0.7|
|ProcessGroupMailer|0.0.1|
|ProcessMessageLister|0.0.1|
|ProcessProMailer|0.0.7|
|ProcessSnipWire|0.0.1|
|ProcessTracyAdminer|1.0.6|
|ProcessWireUpgrade|0.0.7|
|ProcessWireUpgradeCheck|0.0.7|
|SnipWire|0.0.1|
|TracyDebugger|4.19.26|
</details>

**Comment by ryancramerdesign** [comment]
@gadgetto An InputfieldButton (or InputfieldSubmit) is an Inputfield module that usually must have a parent InputfieldForm. The same goes for all Inputfield modules. I can't tell for sure, but since you are rendering the button on it's own (rather than a form with a button as one of its items) it looks like maybe you are using this Inputfield separately from a form? 

I understand a `<button>` element doesn't technically require a form, but Inputfield modules are designed for building forms in PW and not as direct replacements for HTML elements. Maybe this could still work with InputfieldButton (it looks like it's mostly there from what you indicated), but I think your mileage may vary since PW doesn't use them in this way, as far as I can remember. Much CSS/JS for Inputfields has parent element requirements, so I think that may be related to what you are seeing here, at least with the showInHeader() not working. 

I think another potential issue is that you are calling the `$inputfield->render()` method on its own. That just renders the Inputfield's `div.InputfieldContent` inner HTML, and not the rest of the Inputfield. Lots of Inputfield JS/CSS requires the entire Inputfield rather than just the inner HTML. Here's how you would usually render an Inputfield:
~~~~~
$form = $modules->get('InputfieldForm');
$f = $modules->get('InputfieldButton');
// ...
$form->add($f); 
echo $form->render(); 
~~~~~
Note we render the parent $form rather than the Inputfield. If you want to render only the Inputfield, it's possible you might be able to get away with this:
~~~~~
$fs = new InpufieldWrapper();
$f = $modules->get('InputfieldButton');
// ...
$fs->add($f);
echo $fs->renderInputfield($f);
// echo $fs->render(); // or this
~~~~~
....or it's possible you can get away with calling the `$button->render()` directly, like you are. The above is just the way Inputfield modules are intended to be used, but there may be exceptions where they will work outside the planned for pattern, and I think that's fine to do on your own, but I have to stick to supporting them within the intended guidelines. 

Regarding the drop down issue, that's because the drop down capability is part of InputfieldSubmit, and not InputfieldButton. While the InputfieldButton inherits it from InputfieldSubmit just by nature of PHP inheritance, I've not given thought to using these dropdowns in InputfieldButton before. Maybe it can work (it seems mostly there?), but I don't think you'll be able to use both the `href` and dropdown options at the same time, since they would clash with one another. The messy markup you are seeing I think is browser-inspector translated markup rather than the actual markup, as InputfieldButton just wraps the entire Inputfield markup with a link. Maybe an `onclick` event to your button element would be a potential alternative?

**Comment by gadgetto** [comment]
Thanks @ryancramerdesign for your detailed response!
You are right - I thought I could use a button element for it's own.
I'll try to find a way around this based on your samples.
