### ISSUE TITLE
Fatal error - Allowed memory size exhausted (WireHooks)

### ISSUE THREAD

**Issue by tbba** [processwire/processwire-issues#953]
After Updating from 3.0.136 to 3.0.137 I get memory errors:
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in /wire/core/WireHooks.php (line number varies, for example 709)

Am I the only one getting that? 
Can this be a module - or own hooks that need to be altered to adhere to the latest update?

PHP 7.2 or PHP 7.3
PW 3.0.137

**Comment by ryancramerdesign** [comment]
@tbba I haven't had any other reports of this particular error. But the line number you mention is in the newly added addHooks() method in the WireHooks class, which means you've got an addHook*() call somewhere in one of your init files (/site/ready.php, /site/init.php), modules, or somewhere else, that is triggering this method to be called. The method gets called if either an array OR CSV list of method names gets passed to the addHook() method. Since neither of those were previously supported, I'm guessing there might be a problematic addHook() call somewhere in your site and that just wasn't apparent until this version. That's my best guess. A good way to find it might be to edit that /wire/core/WireHooks.php file and `throw new WireException('gotcha');` at the top of the addHooks() method (line 700), and that should leave you with a debug backtrace that points to the source. Feel free to paste in here if it's not clear what the source might be.

**Comment by noelboss** [comment]
I have a similar issue, reverting WireHooks to 3.0.104 solved the issue for me...

`Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes) in /Users/noel/Development/icf-equip/wire/core/WireHooks.php on line 727 Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes) in /Users/noel/Development/icf-equip/vendor/sentry/sentry/src/ErrorHandler.php on line 385 Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 24576 bytes) in Unknown on line 0`

<strong>Server Details</strong>

|Software|Version|
|------:|:-------|
|ProcessWire|3.0.137|
|PHP|7.2.16|
|Webserver|Apache|
|MySQL|5.7.25|
<details><summary><strong>Server Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|allow_url_fopen|1|
|max_execution_time|120 (changeable)|
|max_input_nesting_level|64|
|max_input_time|60|
|max_input_vars|1000|
|memory_limit|1G|
|post_max_size|8M|
|upload_max_filesize|32M|
|xdebug||
|xdebug.max_nesting_level||
|mod_rewrite|1|
|mod_security|*confirmed off|
|EXIF Support|1|
|FreeType|1|
</details><details><summary><strong>GD Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|Version|bundled (2.1.0 compatible)|
|GIF|1|
|JPG|1|
|PNG|1|
|WebP||
</details><details><summary><strong>iMagick Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|Version|6.9.6|
|GIF|1|
|JPG|1|
|PNG|1|
|SVG|1|
|PDF|1|
|WebP||
</details><details><summary><strong>Module Details</strong></summary>

|Module ClassName|Version|
|------:|:-------|
|AccessController|0.0.1|
|AdminHelp|1.0.9|
|AdminOnSteroids|2.0.18|
|AdminPageFieldEditLinks|3.1.2|
|AdminThemeBoss|0.5.5|
|BatchChildEditor|1.8.18|
|BreadcrumbDropdowns|0.1.21|
|ConnectPageFields|0.2.3|
|CronjobDatabaseBackup|1.1.5|
|CustomInputfieldDependencies|0.1.9|
|FieldtypeAssistedURL|1.0.0|
|FieldtypeFieldsetGroup|0.0.4|
|FieldtypeFunctional|0.0.2|
|FieldtypeMultiplier|0.1.3|
|FieldtypeRepeaterMatrix|0.0.5|
|FieldtypeRuntimeMarkup|0.0.6|
|FieldtypeTable|0.1.9|
|FieldtypeTemplates|1.0.0|
|FieldtypeTextareas|0.0.7|
|FormBuilder|0.3.4|
|FrontEndEditLightbox|1.4.0|
|HelperAbTest|0.0.1|
|HelperAuthor|0.0.1|
|HelperCache|0.0.1|
|HelperLanguage|0.0.1|
|HelperPageLinkRedirect|0.0.1|
|HelperPageTitle|0.0.1|
|HelperTimedPublish|0.0.1|
|HideUneditablePages|0.0.1|
|IcfAttachments|0.0.1|
|IcfFormFeedback|0.0.1|
|IcfFormSec|0.0.1|
|IcfOauth2Login|0.1.0|
|IcfRangeDownload|0.0.1|
|IcfRestApi|0.0.5|
|IcfTemplate|0.0.1|
|IcfUtil|0.0.1|
|InputfieldAssistedURL|1.0.1|
|InputfieldChosenSelect|1.2.5|
|InputfieldChosenSelectMultiple|1.2.2|
|InputfieldFormBuilderFile|0.0.2|
|InputfieldFunctional|0.0.2|
|InputfieldMultiplier|0.1.1|
|InputfieldRepeaterMatrix|0.0.5|
|InputfieldRuntimeMarkup|0.0.6|
|InputfieldTable|0.1.9|
|InputfieldTextareas|0.0.7|
|LoginRegister|0.0.2|
|LoginWithEmail|0.0.3|
|Migrations|0.3.1|
|MinimalFieldset|0.1.5|
|ModuleDependencies|0.0.3|
|ModuleSettingsImportExport|0.2.9|
|PageimageRemoveVariations|0.0.4|
|ProDrafts|0.0.8|
|ProcessAdminHelp|1.0.8|
|ProcessChildrenCsvExport|1.8.18|
|ProcessForgotPassword|1.0.2|
|ProcessFormBuilder|0.3.4|
|ProcessMigrations|0.1.3|
|ProcessPageListerPro|1.1.2|
|ProcessProDrafts|0.0.8|
|ProcessSetupPageName|2.1.3|
|ProcessWireUpgrade|0.0.7|
|ProcessWireUpgradeCheck|0.0.7|
|ProviderFeatured|0.0.1|
|ProviderInvite|0.0.1|
|ProviderInviteList|0.0.1|
|ProviderPageImages|0.0.1|
|ProviderRelated|0.0.1|
|ProviderUserAdmin|0.0.1|
|TemplateCategoryEntry|0.0.1|
|TemplateChurchEntry|0.0.1|
|TemplateCollectionEntry|0.0.1|
|TemplateDenominationEntry|0.0.1|
|TemplateFieldWidths|0.1.9|
|TemplateInviteEntry|0.0.1|
|TemplateInviteEntryHelper|0.0.1|
|TemplatePage|0.0.1|
|TemplateResourceContentEntry|0.0.1|
|TemplateResourceContentEntryHelper|0.0.1|
|TemplateResourceEntry|0.0.1|
|TemplateResourceEntryHelper|0.0.1|
|TemplateUser|0.0.1|
|TemplateUserHelper|0.0.1|
|TextformatterMakeLinks|1.0.1|
|TextformatterOEmbed|2.0.2|
|TextformatterTagParser|2.2.0|
|TextformatterVideoEmbedOptions|0.3.6|
|TracyDebugger|4.19.21|
|WireMailMandrill|0.0.1|
</details>

**Comment by noelboss** [comment]
Might most probably happens because of line 706 & 722 when using or conditions with | character like on a selector for the hook:

$this->addHookAfter('Page(template=home|basic)::viewable', $this, 'viewable');

**Comment by ryancramerdesign** [comment]
Thanks @noelboss and @tbba I wasn't able to duplicate it with the addHook call mentioned above, but kept trying variations of it and found this one enabled me to duplicate (and fix) the error when viewing /about/ or children of it. It seemed to be triggered by having more than one argument in the parenthesis (i.e. "template" *and* "name" rather than just template): 
~~~~~
$wire->addHookAfter('Page(template=basic-page|home, name=about)::viewable', 
  function($e) {
    // intentionally blank
  }
); 
~~~~~
Do you find that the fix I committed also corrects it in your environment? Thanks.

**Comment by tbba** [comment]
It was not something in ready.php - probably it was one of an older module.
But I do not need to dig further, I can confirm that **your update fixed it**.
Thank you very much.
