### ISSUE TITLE
Textarea and CKEditor max/min length issues

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#96]
### Short description of the issue

There are several issues with this - more details below

### Expected behavior

All limits enforced by client and server side.

### Actual behavior and possible fixes

1. textarea fields insert `data-maxlength` rather than simply `maxlength` which means there is no client-side validation. `maxlength` does seem to work fine in a textarea (tested with Chrome). There is a note in the InputfieldTextarea.module that suggests maybe this is intentional, but I am surprised that text fields get truncated client side, but textarea fields don't.

2. Here (https://processwire.com/blog/posts/pw-3.0.32/#core-updates-in-this-version) you mention that Ckeditor inputfields should work in regular mode, but it seems like even server-side validation is not working in regular mode. If I add the maxlength validation code from the `InputfieldTextarea::processInput` method to the `InputfieldCKEditor::processInput` method then it works as expected.

3. Also, the minlength check doesn't work on CkEditor fields. It seems that the processInput methods for Textarea and CkEditor need the addition of `		parent::___processInput($input);` to bring the minlength check through from the `InputfieldText::processInput` method and the maxlength check from the InputfieldTextarea::processInput method. You do need to be careful though because that on its own will double the maxlength check because of the non-truncating version in the Texarea version.

I hope that all makes sense :)

PS - even though this post (https://processwire.com/talk/topic/14899-textfield-max-length-still-allows-saving-page-past-max/#comment-133594) mentions "a text field", I think they are likely talking about a textarea field. I will clarify.

**Comment by ryancramerdesign** [comment]
Adrian, those min/max lengths in a textarea are meant to be combined with the character counter feature that was added at the same time. When it comes to CKEditor, we're talking about HTML and text, and it's not clear what the actual length is except the one known by CKEditor (which isn't available to the server side). Tags forming HTML don't count as characters in calculating min/max lengths. Any server side truncation could be problematic since it may be cutting into HTML and breaking tags. For regular textarea fields, it's considered an error state if the text is too long, but the editor can modify (rather than lose) the text they submitted. If a textarea field is used separately from a Fieldtype (like in an InputfieldForm) then the maxlength is enforced both client and server side. But for a trusted user editing a Page, I thought it was better to let them know rather than deleting their text. And of course minlength has to work the same way. 

Related code blocks are here:
https://github.com/processwire/processwire/blob/master/wire/modules/Inputfield/InputfieldTextarea.module#L50
https://github.com/processwire/processwire/blob/master/wire/modules/Inputfield/InputfieldTextarea.module#L107
https://github.com/processwire/processwire/blob/master/wire/modules/Inputfield/InputfieldTextarea.module#L132
