### ISSUE TITLE
Request for clarification: $pages->newPageArray(), part of the public API or not?

### ISSUE THREAD

**Issue by teppokoivula** [processwire/processwire-issues#960]
`Pages::newPageArray()` is tagged with `#pw-internal`, so I've assumed that it's not meant to be a part of the "public API". That being said, I just realised that PageArray class documentation actually contains following note:

> The recommended way to create a new PageArray is to use the `$pages->newPageArray()` method:

Is this method internal, or is it part of the public API – and even the recommended way for creating PageArrays? Currently it seems that aforementioned comments are contradictory. 

Note that the same thing _might_ apply to `Pages::newPage()` – if `Pages::newPageArray()` is indeed the recommended way to create PageArrays, is `Pages::newPage()` the recommended way to create pages? Just making a wild guess here – I haven't seen anything pointing to that direction, but I guess it would make sense from API consistency point of view.

**Comment by ryancramerdesign** [comment]
Thanks @teppokoivula, `$pages->newPageArray();` is the way the core should create new PageArrays, just because it automatically injects the current ProcessWire instance. But for everyone else I think doing `$a = new PageArray();` or `$a = PageArray();` is simpler and preferable. I have updated the phpdoc in PageArray to reflect this.

**Comment by teppokoivula** [comment]
Thanks for clarifying the comments :)
