### ISSUE TITLE
Inconsistancy with multi-language textarea field

### ISSUE THREAD

**Issue by BernhardBaumrock** [processwire/processwire-issues#963]
### Short description of the issue

When using a multi-lang textarea inputfield on a template that has no language support (noLang = 1), the field is displayed as single-language textarea but via the API it is still treated as multi-lang field.

This can cause severe inconsistancies, because the content of the field get's dependent on the users language.

### Expected behavior

The field should just behave like an ordinary single-language textarea field.

### Actual behavior

See this example:
![img](https://i.imgur.com/kIRaJzv.png)

The field value was set via API (I think via setAndSave) because I create this page via the API. The reason why I need a multi-lang field is that I use this field for storing multi-lang email body texts on my settings page (EN = hello world, DE = hallo welt).

Once a new page is created, it decides wheter the english or german text is copied to that page and because the template is single-language only (I can only send the email in one language), the field should just be able to be set via setAndSave('myfield', 'myValue') and get via getFormatted('myField').

I realized something is wrong, because during DEV I used the tracy console to test my method that was added via hook ( $page->sendMail() ); Everything worked, but using this method call in a simple Pages::saved() hook I had an empty E-Mail body.

Again using tracy debugger helped me to see, that the field value is still a multi-lang value. That COULD be fine, if there where no inconsistancies with that approach. For example if the contents would always be stored in the default language and not in the current language (that is english and non-default in the screenshot, as you can see).

My current fix is that I created two separate fields for this sole purpose. Would be great to get a fix for this. I think #916 is related: The problem there is similar: Multi-lang fields should behave as single-lang fields but they actualy behave like multi-lang fields!

### Setup/Environment

* ProcessWire version: 3.0.137
* (Optional) PHP version: 7.2
* (Optional) MySQL version: 5.7

**Comment by ryancramerdesign** [comment]
A multi-language field is still a multi-language field regardless of that template setting. Single vs. multi-language fields literally use different Fieldtypes and database schemas, and a Fieldtype is not something that can dynamically change on a given field. The template setting just turns off the multi-language options in the page editor, and likewise makes it accessible only at the default language URL. But the fields on the page are still of the same type that they are elsewhere on your site. If PW literally changed the Fieldtype for the same field depending on the template setting, it'd be a problem writing reusable code or hooks for the same field because you couldn't count on a consistent API for a field... sometimes "body" would be a string, and other times it would be a LanguagesPageFIeldValue object. If you've got a field that is using one of the multi-language FIeldtypes, code one writes for the field should reflect that... as far as getting and outputting values, a LanguagesPageFieldValue can behave as a string, so the code is generally the same for front-end output cases. But setting values is where you have to consider language. If you don't want to use other languages, then stick to setting the default language value for it. Another alternative (which sounds like what you are doing) is to just use a non-multi-language field for the cases where you don't want a multi-language field, and I think that's a good route as well.

**Comment by netcarver** [comment]
@BernhardBaumrock Does Ryan's reply above allow for this to be closed?

**Comment by BernhardBaumrock** [comment]
Yes, thank you, I think that makes sense.
