### ISSUE TITLE
$users->find() vs $pages->find('template=user') and check_access requirement for non-superusers

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#986]
### Short description of the issue

If you use `$users->find()` as a non-superuser everything works as expected, but if you use `$pages->find('template=user')` you need to add `check_access=0`

I feel like this has been discussed before, but I don't really understand why one works and the other doesn't. On one particular project, I need to use distinguish `hidden` users. I know I could use `array("findAll" => false)` but in reality I actually need `findMany()` for my application, so `$users->find()` is not really an option anyway.

### Optional: Screenshots/Links that demonstrate the issue

As a non-superuser - note `n=0` in the second one.

![image](https://user-images.githubusercontent.com/871211/65741472-033a0000-e0a1-11e9-9afd-00376d0458f0.png)

**Comment by ryancramerdesign** [comment]
Any PagesType class has the findAll=true option specified as the default, whereas $pages->find() does not, and that's an intended behavior. That's because the pages managed by PagesType ($users, $roles, $permissions, etc.) aren't limited by access or status when using their own dedicated API variables, and it's one of the reasons why they have their own dedicated API variables. I understand you want to use `$pages->findMany()` on users with hidden (?) users  included, so I'd agree it could be a good use case for `template=user, check_access=0, include=hidden`, or are you saying that it's not working? How are the users hidden? (PW doesn't support that status property as editable for users). I'm not 100% sure that findMany() would work with users, but am thinking that there's a good chance it might.

**Comment by adrianbj** [comment]
Hi Ryan,

Actually, it's kind of the opposite - I don't actually want to find the hidden users which is why when I was initially using `$users->find()`, I had to add the `array("findAll" => false)`. But then I switched over to wanting to use `findMany()` so obviously had to use `$pages` and then discovered the need to add `check_access=0`.

From what I can tell, `findMany()` seems to be working fine - it doesn't throw any errors and certainly loops through all users - I guess I haven't confirmed that it's functioning the way `findMany()` is meant to, rather than somehow falling back to a normal `find()` and getting all users at once. We don't have that many users just yet, but it will become important hopefully pretty soon :)

Back to my original question which really is why `$users->find()` overrides the need for `check_access=0`, or perhaps even better, is why `$pages->find()` needs it?

**Comment by teppokoivula** [comment]
> Back to my original question which really is why $users->find() overrides the need for check_access=0, or perhaps even better, is why $pages->find() needs it?

It's entirely possible that I'm missing the point here, but my understanding is that the key here is the distinction between accessing PagesType objects – such as users, roles, or permissions – which are pages (but typically not regular, publicly accessible ones) vs. accessing them as so-called raw page data via the $pages API variable.

I don't know if there's a deeper meaning to it, but in my opinion it makes sense: API variables such as $users provide a controlled, easy way to access objects you wouldn't regularly have access to (without bypassing accessing checking, as observed here). Presumably this also means that Pages::find() and similar methods can off-load some complexity to other parts of the core :)

**Comment by adrianbj** [comment]
What you say makes perfect sense @teppokoivula - I guess I the protection of access to users via `$pages` but not `$users` is partly the confusing thing, but I am sure it is intended and so long as `check_access` and `findAll = false` are documented then it's all ok.
